### ISSUE TITLE
NameProtect Help

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1000]
Statt ".nameprotect <fakename>" soll ".nameprotect fakename [NewName]" dar stehen.

**Comment by ThomasGabber** [comment]
.nameprotect fakename "test"

**Comment by superblaubeere27** [comment]
Ah das ist irgentwie unnötig

**Comment by superblaubeere27** [comment]
Und das gibts auch schon
