### ISSUE TITLE
Friend GUI

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1005]
Wenn ich .friend eingebe soll eine GUI kommen, wo all meine Freunde aufgelistet sind. 
Dort kann ich sie wieder von der Freundesliste entfernen oder sie **umbenennen.**
 (wenn man mit freunden spielt und Aufnimmt soll man den namen des Freundes umbenennen damit der dann nicht gebannt wird. 
(zudem soll ich auch freunde hinzufügen können)

**Comment by MaxHD0** [comment]
So ähnlich wie bei diesem Client:

http://www.bilder-upload.eu/show.php?file=4e79df-1499600967.png

**Comment by SenkJu** [comment]
Nein.
