### ISSUE TITLE
Ghosthand GUI

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1006]
Wenn ich .Ghosthand mache soll eine GUI erscheinen, wo ich Blöcke hinzufügen oder entfernen kann.

Bisher kann man nur eine Block ID nehmen. Mit der GUI kann man so viel man will nehmen. 

http://www.bilder-upload.eu/show.php?file=ec5eba-1499601299.png

**Comment by SenkJu** [comment]
Man kann in der GUI schon einen Block auswählen.

**Comment by MaxHD0** [comment]
ja aber nicht mehrere. Das ist es ja eben.

**Comment by MaxHD0** [comment]
Ich kann ghosthand nicht nutzen. ich benutze ja nicht nur eine Chest. Sonder auch z.b Türen öffnen.
