### ISSUE TITLE
X-Ray Bypass mode

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1010]
Ihr kennt es. Ihr startet X-Ray und der gesammte boden ist voller Erze. Wenn man sich aber dann hinbaut verschwinden die Erze. 

Bypass: X-Ray zeigt nur die Erze an neben dem noch ein Erz ist.

O = ERZ

X = Stone                       

XXXXXXXXXXXXX
XXXXXXXXXOXXX <---- Wird nicht gezeigt
XXXXXXXXXXXXX
XXXXOOXXXXXXX <---- Wird gezeigt
XXXXXXXXOXXXX  <---- Wird gezeigt
XXXXXXXXOXXX <---- Wird gezeigt

**Comment by SenkJu** [comment]
Und wie genau soll das helfen, Spigots AntiXRay zu bypassen?
