### ISSUE TITLE
AutoFish

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1012]
Er Angelt für dich.
(wenn die Angel kaputt geht nimmt er (etwa eine andere in der hotbar oder er zieht eine vom Inventar in die Hotbar. 
(Enchatete Angeln soll er als erstes nutzen. (egal was für ne Verzauberung))

**Comment by Marco-MC** [comment]
Benutz Wurst... .-.
ODER INSTALLIER DIR NE AUTO ANGEL MOD.
Mir snuppe.

**Comment by Marco-MC** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289421-autofish-mod-for-minecraft-1-12
