### ISSUE TITLE
Invcleaner + aura

### ISSUE THREAD

**Issue by Crax9999** [CCBlueX/LiquidBounce1.8-Issues#1013]
Invcleaner closed inv option
Ihr könntet auch bei der Aura machen dass 
Sie die targets im inv. nicht angreift (perfekt für rewi weil sowas autobannt)
Yawrate bei der aura 
Aura block/entity raycast es gibt nämlich nur eine
Aura FOV

**Comment by MaxHD0** [comment]
"Sie die targets im inv. nicht angreift (perfekt für rewi weil sowas autobannt)"
Gibts schon. NoInvAttack

"Yawrate bei der aura" Marco will das glaub nicht einfügen. KP warum. 

"Aura block/entity raycast es gibt nämlich nur eine" Beides gibts schon. (Ich sagte marco es soll 1 der beiden namen ändern XD Name: Raycast = EntityRaycast und ThoughWalls = BlockRaycast

Und FOV gibts auch.

**Comment by SenkJu** [comment]
Bis auf YawRate gibt es alles. Das mach ich einzeln.

**Comment by Crax9999** [comment]
XXXXXXXXDDDDDDDDD bin blind
