### ISSUE TITLE
KillAura: YawRate

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1014]

**Comment by MaxHD0** [comment]
lol. Ich dachte Marco wollte es nicht .-.

Naja. ich währe dafür-

PS: was ist eigendlich YawRate XD
(ich weiss das es irgendwas mit Rotation zu tun hat)

**Comment by Marco-MC** [comment]
Hä? YawRate = TurnSpeed???
