### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by GRUENESKINKIE** [CCBlueX/LiquidBounce1.8-Issues#1016]
Can u add a feauture that every one cann use a font that he/she likes??

Thanks for any anwsers.

With Friendly Greetings GRUENESKINKIE

**Comment by SenkJu** [comment]
Sorry, we tried it but it is very buggy. However, if you really want to change the font, go to %appdata%/.minecraft/LiquidBounce-1.8/fonts and replace the files with any font you want. Just don't expect it to look perfectly.
