### ISSUE TITLE
Antibot mode BotSpeed

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1017]
BotSpeed: Wenn ein Spieler sich schnell zu dir bewegt schlägt er diesen Spieler nicht. (Bei Timolia kommt der Bot ja recht fix zu dir. (Timolia Bypass. (eigendlich nur für timolia. Wenn ich es bei gomme mache und da jemand bei SG so eine flieg Druckplatte benutzt schlägt die Killaura nichts mehr.

(Es ist gut. Man sollte den Mode jedoch nicht bei jedem Server/Spielmodus benutzen.

**Comment by Crax9999** [comment]
LB hat auch keine Miniticks u. Maxticks
Könnte man hinzufügen
