### ISSUE TITLE
Livingtime/WasInvisible zeit delay [-----[]---]

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1018]
Bei Livingtime/WasInvisible soll man einstellen können wie lange es dauert bis er den Spieler dann wieder schlägt. (von 1er Sek bis 10 sekunden) (mit einem Befehl soll man es noch höher/niedriger drehen können)

**Comment by superblaubeere27** [comment]
Wenn es einen Server gibt, wo das bypasst, dann mach einen neuen issue, sonst ist es unnötig
