### ISSUE TITLE
Client auf GUI grösse Automatisch anpassen.

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1019]
mit GUI grösse Automatisch kann man nicht spielen. Und Normal ist vielen (auch mir) zu klein.

**Comment by SenkJu** [comment]
Skalieren sieht zu unschön aus.

**Comment by MaxHD0** [comment]
(wie währe es wenn man Egal auf was man die Gui stellt die Clickgui und die HUD immer auf Normal ist)

**Comment by MaxHD0** [comment]
wurst macht das bei manchen stellen auch so.

**Comment by SenkJu** [comment]
Die HUD und ClickGUI sind nun einmal GUI Elemente.
