### ISSUE TITLE
Enchant AutoArmor

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#102]
Könntet ihr Autoarmor dass die Verzauberten Rüstungsteile Anzieht statt irgend eine besser.

**Comment by Marco-MC** [comment]
Das ist relativ schwer zu machen, da man wirklich alles richtig berechnen muss wie Stark dann eine Rüstung ist etc... Kann mal schauen ob ich da was zaubern kann, aber ich muss mich dann erstmal mit dem Minecraft Enchant System auseinander setzen. ^^
Sollte aber in b24 hoffentlich kommen.

**Comment by Marco-MC** [comment]
Wird in der b24 nicht kommen. Aber vielleicht später.

**Comment by WoodyLetsPlay** [comment]
Das wäre so nice, wenn es kommen würde.

**Comment by thxforhelp** [comment]
lets go @Marco-MC

**Comment by Marco-MC** [comment]
Er wird in Zukunft lediglich auf Protection achten, mehr nicht.

**Comment by Marco-MC** [comment]
Added
