### ISSUE TITLE
Freecam Speedsetting + Noclipsetting

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1020]
(wurde zur B26 nicht hinzugefügt)

**Comment by MaxHD0** [comment]
Noclip: (wenn an kann man durch Wände fliegen wenn aus Nicht.) Währe oft nützlich.

**Comment by Crax9999** [comment]
Freecam speedsetting ist gut für badlion pls hinzufügen

**Comment by MaxHD0** [comment]
Marco hat wollte es ja hinzufügen. Aber irgendwie hat er es nicht. Kann ja mal passieren.

**Comment by superblaubeere27** [comment]
Für Noclip kannst du das Module `Noclip` nutzen, aber trotzdem ok

**Comment by MaxHD0** [comment]
superblaubeere27 du verstehst es falsch. Bis jetzt kannst du einfach durch blöcke gehen. Und mit dem Update soll ein Button hinzugefügt werden (der Noclip button) der wenn er aus ist du nicht mehr durch blöcke kannst. Jetzt auch wenn du noclip an oder aus hast kannst du durch blöcke. Zudem ist man sehr langsam mit dem modul Noclip.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/270 Hä? Habe ich das nicht geaddet?

**Comment by superblaubeere27** [comment]
@Marco-MC Sry ich dacht das wäre wahr

**Comment by Marco-MC** [comment]
https://gyazo.com/1faaaf77c404d518628eec063378918e Ich weiß zwar nicht ob ich das irgendwie in der b27 hinzugefügt habe, auf jedenfall giebt es ein Speed Setting bei Freecam.
Die NoClip Setting ist unnötig.

**Comment by Namebittehiereingeben** [comment]
k

**Comment by Namebittehiereingeben** [comment]
wundert mich warum Hier noch kein Ghost steht. Das heisst ich wurde noch nicht gebannt. lol ein wurder?
