### ISSUE TITLE
Buchstaben hinzufügen ö ä ü

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1021]
Bei eurer schriftart gibt es kein ö ü ä  
Manchmal sieht das scheisse aus.

http://www.bilder-upload.eu/show.php?file=a6bfcf-1499639532.png

**Comment by MaxHD0** [comment]
Dann könnt ihr auch wieder "Zurück zum Spiel" schreiben und nicht "Zurueck zum Spiel" etc.

**Comment by SenkJu** [comment]
Geht mit unserem Font Renderer nicht.
