### ISSUE TITLE
Upstack

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1022]
Du kannst **alle** Items bis 64 tragen. Auch Schwerter, Tränke, Enderperlen etc.

Funktioniert definitiv im Creative mode. Im Überlebensmode weiss ich es nicht. Muss man ausprobieren.

**Comment by superblaubeere27** [comment]
Ah eher ein unnötiges module

**Comment by MaxHD0** [comment]
.-. hä wenn dein Inventar voll ist kannst du immernoch alles aufsammeln.
