### ISSUE TITLE
Latest Spartan Speed

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1023]

**Comment by superblaubeere27** [comment]
Sry, aber lern mal Englisch oder formulier es auf Deutsch.

**Comment by MaxHD0** [comment]
habe es doch richtig geschrieben.

**Comment by IloveRickandmorty** [comment]
Ne Latest währe richtig. Aber Newst ist eigendlich auch nicht falsch.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1351
