### ISSUE TITLE
AAC 3.2.1 Speed

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1024]
Der AACv3 Longjump funktioniert. Mann muss es nur nicht bei jedem Sprung machen sondern ca. jeder 3 sprung. (1 Auf dem Testserver hatte das sogar auch.)

Daraus kann man ein Speed machen.

**Comment by SenkJu** [comment]
Wir haben schon einen AAC3.2.1 Speed
