### ISSUE TITLE
KillAura Vanilla

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1028]
http://prntscr.com/ftz8x4 in Vanilla Servern bzw ohne AntiCheat: You sending too many packets!

**Comment by MaxHD0** [comment]
#1030

**Comment by MaxHD0** [comment]
das problem habe ich in eine issue geschrieben.

**Comment by SenkJu** [comment]
Das liegt nicht an den Targets, sondern eher daran, dass du vermutlich Packet Criticals an hast.

**Comment by WistarWolf** [comment]
Kann man das irgendwie fixen?

**Comment by WistarWolf** [comment]
Habe Criticals ganz deaktiviert, werde trotzdem gekickt.

**Comment by Marco-MC** [comment]
Oh mein Gott, alta... xD
Das liegt nicht an der KillAura, das ist ganz normal.
Der kick kommt nicht von Vanilla, sondern von ViaVersion.
ViaVersion checkt nicht wie viele MovePackets, sondern checkt alle Packets wie viele geschickt werden.

Du hast 2 Gegner und deine Aura auf 20cps.

1sek = 40 Attack packets + 40 Swing Packets + 80 Unblock/Block (falls du grade am blocken bist) packets.

80 Packets pro Sekunde... Sind für nen Legit zu viel, also kickt ViaVersion dich.
Mach mal die Settings tikkel runter, erst recht die CPS...

**Comment by WistarWolf** [comment]
Ok sry du dass ich nicht so weise bin wie du, du 1337 skid.




Trotzdem danke :D
