### ISSUE TITLE
Multiaura hit anzahl [-----[]--] 2-20

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1030]
Man kann auswählen wieviel Spieler die Killaura hitten soll. (wenn man mehr als 4 Spieler hittet wird man für Packets gekickt. Darum währe es cool wenn man das einstellen könnte.

man soll von 2 bis 20 Spieler auswählen können (wieviel Spieler die Killaura gleichzeitig schlagen soll.)

**Comment by SenkJu** [comment]
Nein, das geht nicht. Sagen wir mal du wählst vier Spieler aus, alle vier rennen weg, du willst jemand anderen angreifen, aber die Aura wird ihn nicht schlagen.

**Comment by Bircko** [comment]
SenkJu ich glaube du verstehst den Sinn nicht. Du wählst auch nicht die Spieler aus die er hitten soll, sondern nur die anzahl, die er gleichzeitig schlagen soll.

**Comment by Marco09MC** [comment]
Added

**Comment by Teals53** [comment]
this issue wait 2 years xD
