### ISSUE TITLE
Add LiquidLauncher Utils

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#1031]
Für den LiquidLauncher start argumente für LiquidBounce
- `--noVersionCheck` es gibt keinen Screen mehr, wenn man eine alte version spielt
- `--authServer <authserver(MCLeaks/Mojang/AltDispenser)>` 
@Marco-MC wäre nett, wenn du es einbaust

**Comment by Marco-MC** [comment]
authServer=Nein
noVersionCheck=Vielleicht

Ich weiß überhaupt nicht, ob ich das mit Forge Injection überhaupt machen kann. Ich bezweifel das nämlich stark.

**Comment by superblaubeere27** [comment]
ok

**Comment by superblaubeere27** [comment]
ah doch geht 100%ig

**Comment by Marco-MC** [comment]
Nope, habe jetzt vieles ausgetestet.

Ich habe mich in die Main Class injected was leider nicht geklappt hat.
Danach habe ich es versucht mit MXBean mir die start arguments zu geben, was auch geklappt hat nur... wurde --noVersionCheck nicht angezeigt.
