### ISSUE TITLE
Add AltDispenser Auth mode

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#1032]
Es gibt derzeit nur MCLeaks und Monjang als Auth, ich fände AltDispenser auch ganz gut.
== Wie?
Die IP vom authserver muss man von der Site hier lesen: https://api.altdispenser.net/authserver
Die IP vom sessionserver muss man von der Site hier lesen: https://api.altdispenser.net/sessionserver

**Comment by MaxHD0** [comment]
superblaubeere27 kannst du mich aufn Discord entbannen? habe mal gespammt. sry dafür

**Comment by SenkJu** [comment]
Nein, mit AltDispenser werden wir nicht mehr zusammenarbeiten. Die haben uns vorgeworfen, wir würden API Keys stehlen.

**Comment by superblaubeere27** [comment]
MAAAAAN

**Comment by Marco-MC** [comment]
@superblaubeere27 Haha.

**Comment by superblaubeere27** [comment]
xD

**Comment by Marco-MC** [comment]
AltDispenser sind so ne kackbratzen.

**Comment by Marco-MC** [comment]
btw deren API geht nicht mal. xD
