### ISSUE TITLE
Man kann auf griefergames nicht joinen

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1033]
http://www.bilder-upload.eu/show.php?file=6ad459-1499776676.png

**Comment by WistarWolf** [comment]
#723

**Comment by MaxHD0** [comment]
ich dachte es währe was anderes. ok?

**Comment by MaxHD0** [comment]
frägt sich nur wann b27 rauskommt.
