### ISSUE TITLE
Velocity Back mode

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1035]
Wenn du geschlagen wirst wirst du nur nach hinten geschmissen.
(für Bedwars. Wenn jemand dich Runterschlagen will oder du von der seite vom Bogen getroffen wirst.)
(stärke wie stark du dach hinten geworfen werden sollst soll einstellbar sein.)

**Comment by SenkJu** [comment]
???

**Comment by superblaubeere27** [comment]
Äh nein?
Wofür brauch man das?
Ünnotiger aufwand
