### ISSUE TITLE
Neuer Schneller AAC Scaffold. (FastEagle)

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1036]
https://gyazo.com/d0fd6b634767b1864b0fdbad86b6434c

wenn ich Eagle an habe und mit den tasten S und D Eagle bin ich sau schnell. (zudem bypasst es auf jedes Anticheat.

(ich muss die Rechte maustaste spammen um ganz schnell zu sein. (fastplace bypasst nicht. Dann werde ich runtergeworfen.))

**Comment by SenkJu** [comment]
Wir haben schon einen schnelleren?

**Comment by MaxHD0** [comment]
Senk Ju. Ok lasst das offen. Wenn es keinen mehr gibt könnt ihr diesen dann hinzufügen. (zudem sieht dieser mode Legit aus. Dann wird man nicht gebannt obwohl man sich schnell vorbaut.
