### ISSUE TITLE
AtAllProvider

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#1041]
Man kann z.B. `/party invite @a` machen und dann wird für jeden Spieler einmal `/party invite %playerName%` ausgeführt.
Das ganze gibts auch mit Delay.
Ich habs schon mal gecodet: [ModuleAtAllProvider.zip](https://github.com/CCBlueX/LiquidBounce1.8-Issues/files/1148049/ModuleAtAllProvider.zip)

**Comment by Bircko** [comment]
gleiches bitte auch mit tpa oder generel für alle commands ein @a oder irgendein anders zeichen das nicht benutzt wird machen um an alle z.b nachrichten oder sonstiges senden.

**Comment by superblaubeere27** [comment]
Yes thx

**Comment by Marco-MC** [comment]
Added.
