### ISSUE TITLE
Spammer options

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#1042]
Man soll in die Spammer msg `%int%` oder `%float%` einbauen können und dann wird das halt mit rdn nummern aufgefüllt:
`%int% LiquidBounce %int% Hacked %int% client %int% by %int% CCBlueX %int%`
Wird zu:
`754 LiquidBounce 456 Hacked 235 client 65 by 563 CCBlueX 654` das würde das rewi antispam bypassen

**Comment by Bircko** [comment]
%string% für random generierte strings mit buchstaben und eventuell mit zahlen gemischt.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1042

**Comment by DieSwitch** [comment]
Marco zeigt eine Zahl zur selben issue XD  lul

**Comment by Marco-MC** [comment]
@DieSwitch Fixed.
