### ISSUE TITLE
Add Kick

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1044]

**Comment by Marco-MC** [comment]
**Modes:** _Quit (Disconnect), SelfHurt, InvaildPacket, PacketSpam_

**Comment by Bircko** [comment]
Wo genau kann man das als Vorteil nutzen?

**Comment by Ldcr993519867** [comment]
another kick method: send chat message "§", then you get kicked (color code).

**Comment by Marco-MC** [comment]
@Ldcr993519867 Added
