### ISSUE TITLE
KeepAlive

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1046]
Versucht dich nach dem Tod wieder zu beleben. Dies tut es mit "/heal"( welcher auf einigen faction server verfügbar ist und auch in Essentials) und durch Suppe Heilung falls soup PvP an Ist.

**Comment by MaxHD0** [comment]
Eine Möglichkeit währe noch schnelles Regenerieren. Ein fastheal, dass dich wenn du tot bist regeneriert. 
Den Bug gab es mal auf AAC 3.0.2 _(oder war es 3.0.3? Kp)_ 
sollte auch in vanilla gehen.

**Comment by IloveRickandmorty** [comment]
Stimmt Ghost den gab es. Es war in der 3.0.2

Wartemal Ghost? GEIST AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Marco09MC** [comment]
/heal ist möglich, Soups geht auch (wenn Keep Inventory an ist und das Soup Plugin keine Überprüfung hat ob der Spieler noch am leben ist).
Golden Apple und Regen ist/wird nicht möglich sein, weil dafür die Zeit nicht reicht.
