### ISSUE TITLE
Neuer Schneller AAC Scaffold. (FastEagle)

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1050]
**(ich weiss das es derzeit einen Scaffold gibt. Macht diesen einfach rein wenn die anderen nicht mehr gehen.)**

https://gyazo.com/d0fd6b634767b1864b0fdbad86b6434c

wenn ich Eagle an habe und mit den tasten S und D Eagle bin ich sau schnell. (zudem bypasst es auf jedes Anticheat.

(ich muss die Rechte maustaste spammen um ganz schnell zu sein. (fastplace bypasst nicht. Dann werde ich runtergeworfen.))

**Comment by SenkJu** [comment]
Dass der andere Scaffold nicht gebypasst hat, lag an den Rotations. Das da hat keinerlei Vorteile.
