### ISSUE TITLE
improve aac 1.9.10 fly

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1056]
aac 1.9.10 fly ist relative schlecht im vergleich zu anderen clients (alpha centaurie, eazy usw.).

**Comment by Bircko** [comment]
besser ausgedrückt fix/improve aac 1.9.10 fly

**Comment by B3nutz3r** [comment]
Hive hat AAC 3.2.2

**Comment by MaxHD0** [comment]
seit wann? lol

**Comment by MaxHD0** [comment]
ok getestet. Ja scheimbar gab es gestern ein update. Habe nämlich gestern da noch gespielt.

**Comment by Bircko** [comment]
ändern nichts daran das der aac 1.9.10 fly trotzdem scheiße ist

**Comment by Teals53** [comment]
clearing timeeee marco is back
