### ISSUE TITLE
Improve Rewi Teleport

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1058]
Wie in diesem Video
https://www.youtube.com/watch?v=jkdGanYAgFE

**Comment by B3nutz3r** [comment]
Oder in dem https://www.youtube.com/watch?v=_fYz-NWGntQ XD

**Comment by Rick200** [comment]
Hä. Ein Rewi teleport ist ja schon drin.

**Comment by Marco-MC** [comment]
Yoa, der in b26.2 geht zwar noch aber nicht mehr so wirklich gut.

**Comment by Marco-MC** [comment]
Also, ich habe mal tikkel rumgetestet und habe auf jedenfall jetzt nen tikkel verbesserten gemacht. Der geht relativ gut und kickt auch nicht mehr für Flying.
Den neuen habe ich als Rewinside Mode bei Teleport gespeichert.
Den alten habe ich als OldRewinside Mode bei Teleport gespiechert.
