### ISSUE TITLE
Hypixel Fast Scaffold

### ISSUE THREAD

**Issue by Rick200** [CCBlueX/LiquidBounce1.8-Issues#1059]
https://youtu.be/_fYz-NWGntQ?t=105

**Comment by Bircko** [comment]
In dem Video wurde einfach vorgespult das ist fake

**Comment by Bircko** [comment]
nein bind einfach scaffold+timer auf eine taste und mach timer um die 4.0

**Comment by SenkJu** [comment]
Mach es wie, @Bicko es sagt. So ein schneller Scaffold hat sowieso keinen nutzen. Kann man ja kaum kontrollieren.
