### ISSUE TITLE
Deadscreen: Ghost button + NoLimit

### ISSUE THREAD

**Issue by Rick200** [CCBlueX/LiquidBounce1.8-Issues#1068]
- Der Ghost button ist dafür da, dass wenn du tot bist noch im Freecam mode alles anschauen kannst.
 [zum Wiederbeleben soll so ein button oberhalb des Inventares sein. [So wie ungefähr wie wenn du im Bett liegst. Dieser "aufstehen" Button.]]

- NoLimit. Wenn du stirbst dauert er kurz bis du den Wiederbeleben button drücken kannst. Diese Zeit soll entfernt werden.

**Comment by SenkJu** [comment]
Diese Zeit, die es braucht bis du respawnen kannst, ist vom Server abhängig und bedeutet meistens, dass du eine miese Connection hast.

**Comment by Marco-MC** [comment]
Naja, trz kann man das machen.
Trz wozu? Mach doch einfach AutoRespawn an?
