### ISSUE TITLE
Blockesp keine laggs + mode

### ISSUE THREAD

**Issue by Rick200** [CCBlueX/LiquidBounce1.8-Issues#1071]
Bei Chestesp laggt nichts. Wenn ich aber Blockesp an habe laggt es. [auch wenn ich das Item Chest als ID nehme laggt es.

Zudem soll es mehrere modes geben.

- Box

- Outline

- Tracer

Bei Tracer soll ein strich zu dem Block gehen.

**Comment by Marco-MC** [comment]
Nein.
