### ISSUE TITLE
Better Rainbow Array List

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1073]
https://youtu.be/_fYz-NWGntQ?t=15s

würde viel besser aus sehen als einfach die farbvielfalt zu verringern oder erhöhen.

**Comment by MaxHD0** [comment]
mir währe es egal.

**Comment by IloveRickandmorty** [comment]
Naja. Solange man die jetzige Geschwindigkeit beibehalten kann.
