### ISSUE TITLE
Add Kick (b27 module) modes to AutoLeave

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1074]
mit denn kick modis wie bei dem bereits vorhandenen modul 

Modes: Quit (Disconnect), SelfHurt (Hit yourself), InvaildPacket (Send a packet with illegal positions), PacketSpam (Spam many move packets (Only ViaVersion etc))
Added.

**Comment by Bircko** [comment]
oder kick mode unter auto leave

**Comment by MaxHD0** [comment]
allesklar. Bei mir wurde es gelöscht. Ich habe ne idee. (die ich euch natürlich nicht sage)

**Comment by MaxHD0** [comment]
aber die idee war halt echt gut.

**Comment by Marco-MC** [comment]
Added.
