### ISSUE TITLE
Bitte eine Rechtsklick Option 

### ISSUE THREAD

**Issue by B3nutz3r** [CCBlueX/LiquidBounce1.8-Issues#1075]
Das ist echt frustrierend wenn das neue Update kommt fast alle den neuen Teleport genießen und man selber kann das nicht also bitte eine Rechtsklick Option

**Comment by SenkJu** [comment]
Wieso kannst du Mid-Click nicht nutzen?

**Comment by B3nutz3r** [comment]
Überall funktioniert es außer bei LB

**Comment by Marco-MC** [comment]
Added.

**Comment by B3nutz3r** [comment]
thx
