### ISSUE TITLE
eigendlich eine gute idee.

### ISSUE THREAD

**Issue by WlstarWolf** [CCBlueX/LiquidBounce1.8-Issues#1077]
Dieses "TrueSight Barriere setting" ist doch eine gute Idee. Ich würde es immer an haben.

Genau wie dieser Ghost knopf und das direkt verbinden im multiplayer.

Währe schön wenn du es hinzufügen würdest.

**Comment by Marco-MC** [comment]
Max, dass ist so lächerlich.
https://gyazo.com/42a0e916e2c7a6ea0dd3dd782f59d727

**Comment by WistarWolf** [comment]
Junge. Was soll das? Jetzt versuchst du mich zu faken.

**Comment by WistarWolf** [comment]
Lächerlich

**Comment by WistarWolf** [comment]
Dadurch kommst du auch nicht weiter.
