### ISSUE TITLE
plz lesen

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#1078]
Hey Marco. Sag ehrlich. Das sind doch recht gute ideen. Manche sind leicht überflüssig. Jedoch haben die alle einen sinn. 

Zudem merkst du, dass du mich schon 732648736 mal gebannt hast und ich immernoch hier bin. Du kannst zwar dieses "neue personen dürfen nicht schreiben an machen. Aber dann können nur wenige schreiben. (zudem habe ich noch 6 Accounts die hier noch sind. Schreiben könnte ich so oder so.)

Aber eigendlich will ich euch nur helfen. Es ist kein Attentat hier zu schreiben. Wobei ich mich bei manchen Modules sehr wundere warum du sie nicht haben willst. (NoRender, TrueSight Barrier, CMDBlock etc.)
Sie sind ja eigendlich sehr gut. Nur weil du mich nicht leiden kannst machst du die nicht rein?

Begonnen hat es eigendlich mit Fleroxh. Er hat sich genervt gefühlt bei mir und ich bei ihm. Das wurde dann mehr bis ich mich 1 mal auf github entbannt habe. Das ging dann so weiter bis ich ganz gebannt wurde. (Naja. Nur halt auf meinem Main Discord. Auf eurem schreibe ich immernoch manchmal.)
Das bit Github stört mich nicht. Ist eh nicht mein Main. 

Zugegeben. Manchmal übertreibe ich wenn du was nicht hinzufügen willst. 

Ich würde dich einfach bitten lass mich meine issues schreiben. (ohne "ohh ich mag dich nicht. Ich lösch die issue und bann dich") Das mit dem Discord stört mich nicht. Ich bleib jetzt mal bei meinem 2 acc. und Später entbanne ich mich auf meinem Main. Grüsse an den Discord der das sicher auch lesen wird.

**Comment by MaxHD0** [comment]
ich wusste es das du es in den Chat sendest

**Comment by Marco-MC** [comment]
haha

**Comment by scorpion3013** [comment]
Nützt dir auch das du schreiben kannst ohne das es je angenommen wird oder ?

**Comment by MaxHD0** [comment]
wenn ich aber schreibe würdet ihr mich bannen.

**Comment by MaxHD0** [comment]
ich finde es doch nicht schlimm XD

**Comment by MaxHD0** [comment]
Ich mache es trotzdem

**Comment by MaxHD0** [comment]
un wenn unter anderem namen

**Comment by Fleroxh** [comment]
Nab.

**Comment by Fleroxh** [comment]
LIFETIME ANTI PROXY/VPN IP & ACCOUNT BAN :3
