### ISSUE TITLE
Reconnect button ingame

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1082]
Ein reconnect button auch ingame so das man z.b nicht runter gehen muss und wieder denn server suchen muss.

**Comment by MaxHD0** [comment]
hatte ich schon mal vorgeschlagen.

**Comment by MaxHD0** [comment]
#328 ich musste ein wenig suchen ^^

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1162
