### ISSUE TITLE
macros

### ISSUE THREAD

**Issue by SavageSOC** [CCBlueX/LiquidBounce1.8-Issues#1091]
Add keybinds to any command like "/home"

**Comment by Maxhd0** [comment]
ihh. direkte sinnlose idee von wurst.

( auf fast alles servern muss man ehh 3 sekunden warten.)

**Comment by Maxhd0** [comment]
mach so das man einstellen kann welcher command man schreibt

**Comment by Maxhd0** [comment]
#1092

**Comment by MaxHD0** [comment]
sry. habe es falsch verstanden.

**Comment by Bircko** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2698256-forge-macrokey-keybinding-for-minecraft-1-8-1-8-8

**Comment by Bircko** [comment]
ด้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็﻿ด้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็﻿ด้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็﻿ด้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็้้้้้็็็็็้้้้้้้้็็็็็﻿ด้้้้้็็็็็้้้้้็
