### ISSUE TITLE
Keysay

### ISSUE THREAD

**Issue by Maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1092]
wenn du .keysay <Befehl oder Satz> machst und du danach den Hack aktivierst schreibst du das sofort.

(Ähnlich wie spammer. Nur spammst du nicht. Du schreibst es nur in den Chat wenn du den keybind drückst.)

(den Namen könnt ihr ändern. Mir ist nichts gescheites eingefallen.)

**Comment by SenkJu** [comment]
Macros findest du sinnlos aber so einen Blödsinn sollen wir einbauen?
