### ISSUE TITLE
Auto disable speed when scaffold enable

### ISSUE THREAD

**Issue by Ldcr993519867** [CCBlueX/LiquidBounce1.8-Issues#1096]
if speed mode is hop,scaffold may fall down

**Comment by Bircko** [comment]
should be able to toggle it on an off

**Comment by Ldcr993519867** [comment]
but it you have to manually toggle it off, right?

**Comment by Bircko** [comment]
No i mean like there is a box where you can set if it should automaticly toggle of or not.

**Comment by SenkJu** [comment]
Bind speed and scaffold to the same key, enable one of them using the GUI. If you use the keybind now it will switch between scaffold and speed.
