### ISSUE TITLE
Selfdamage

### ISSUE THREAD

**Issue by IloveRickandmorty** [CCBlueX/LiquidBounce1.8-Issues#1098]
Du gibts dir selbst damage. Wie viel man schaden bekommt soll einstellbar sein.

Es soll mehrere modes geben sich selbst damage zu geben.

**Comment by Marco-MC** [comment]
Es giebt schon .damage <wie viel dmg>

Außerdem wie willst du dir bitte selbst Schaden geben bis auf Fallschaden?
Fallschaden ist die einzige Möglichkeit sich selbst schaden zu geben, was der Command halt macht.
Er simuliert als würdest du ne distance fallen.

**Comment by IloveRickandmorty** [comment]
ok.
