### ISSUE TITLE
Nametag settings

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1099]
1. Man soll die Minimale grösse einstellen können.
2. Man soll die Maximale grösse einstellen können.
3. Man soll Herzen, Armor und Ping an/aus stellen können.
4. Man soll einstellen ob die Nametags durch wände gehen. (ThroughWalls) 
5. Man soll einstellen können ob man die Client Schriftart haben will oder die von Minecraft (MCFont)
6. Es soll ein maximalen Abstand geben. Ab dann soll der Nametag nicht mehr angezeigt werden. (man kann auch auf unendlich stellen)

Manchmal nervt es duzend Nametags auf dem Bildschrirm zu haben. [dafür ist dann Nr. 4 und Nr. 6]

**Comment by superblaubeere27** [comment]
Herzen und Ping ist ok aber der Rest ist absolut unnötig (Meine Meinung)

**Comment by IloveRickandmorty** [comment]
Nr. 1 und 2 hat einen Grund. Wenn ich z.b SG Spiele dann will ich nicht überall riesige Nametags haben. Also verringere ich die Maximale grösse. Und wenn ich ganz nah bin will ich das Nametag auch grösser haben. Ich finde es viel zu klein. Dafür das minimum.

Das Mit der Schriftart finde ich auch wichtig.(MCFont) Manche mögen die Client Schriftart mehr manche die Minecraft Schriftart. (Ich mache es mit einem Resourcepack. Ich finde die Schriftart richtig cool)

Und 4 und 6 sind dazu da nicht den Bildschirm voll zu müllen.

**Comment by Marco-MC** [comment]
Ich füge lediglich "Man soll Herzen, Armor und Ping an/aus stellen können." hinzu.

**Comment by Marco-MC** [comment]
Added

**Comment by Teals53** [comment]
Marco Working Live :D
