### ISSUE TITLE
Killaura bypass

### ISSUE THREAD

**Issue by Ldcr993519867** [CCBlueX/LiquidBounce1.8-Issues#1101]
there was an anticheat uses strange way to find out killaura.
I don't know what this anticheat plugin is.

when the anticheat guess you are hacking, it will spawn some invisible bot around the target(bot will keep about 2 seconds), so you're unable attack the target(all damage will taken on the bot), if you damaged the target(even just once), you will get kicked for hacking

the bot is not always player, sometimes mobs(like witch. zombie or villager)

AntiBot not works(AntiBot make killaura not attack the bot, so killaura will directly attack target, then get kick)

can you make killaura bypass this anticheat?

**Comment by CrackFileso** [comment]
It's Reflex

**Comment by CrackFileso** [comment]
It's Latest Reflex ,Try /reflex

**Comment by CrackFileso** [comment]
wujinze = =!?

**Comment by Marco-MC** [comment]
#997
