### ISSUE TITLE
Un-Inject LiquidBounce

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1103]
Something to make it invisible.

**Comment by Bircko** [comment]
Hat nicht forge nen deactivate button in mods

**Comment by IloveRickandmorty** [comment]
ja aber den kann man nie Drücken XD

**Comment by SenkJu** [comment]
@Bircko LiquidBounce ist Injection. Das kann man so nicht beenden.
