### ISSUE TITLE
Improve Scaffoldwalk Normal

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1104]
It should build even if you are on the corner of the block. http://i.imgur.com/jrvN6v1.png

**Comment by IloveRickandmorty** [comment]
This is so with every mode

**Comment by Marco-MC** [comment]
@scorpion3013 

1. Das ist bei jedem Mode wie @IloveRickandmorty es auch geschrieben hat.
2. Er platziert halt keinen Block, weil der Scaffold nicht mit einem anderen Block interargieren kann.
