### ISSUE TITLE
FakeFPS

### ISSUE THREAD

**Issue by IloveRickandmorty** [CCBlueX/LiquidBounce1.8-Issues#1106]
Wenn an wechseln die FPS von 300 bis 400

Man soll es einstellen können.

Man könnte mit seinem PC angeben. XD

**Comment by Marco-MC** [comment]
rly? Dein Ernst?
FakeFPS?
Ich komme nicht drauf klar, alta.

**Comment by IloveRickandmorty** [comment]
schlimm ist das nicht?

**Comment by Marco-MC** [comment]
Wozu? FakeFPS?!
FakeFPS sind so hart unnötig? wtf?
Kauf dir lieber ne bessere Graffikarte um anzugeben, nicht mit so einem scheiß.

**Comment by IloveRickandmorty** [comment]
habe ne GTX 1080ti 

Ich muss nicht angeben. 

Hatte nur ein anderen client den ich grade spielte.

**Comment by Marco-MC** [comment]
https://www.youtube.com/watch?v=1h7XhziL3Bc LiquidBounce ist eh eine Forge Mod und somit kannst du diese Mod z.B mit in den Mods Ordner tuhen.

**Comment by IloveRickandmorty** [comment]
es gibt dazu ein mod XD lol
