### ISSUE TITLE
Armor über name

### ISSUE THREAD

**Issue by IloveRickandmorty** [CCBlueX/LiquidBounce1.8-Issues#1107]
Könnt ihr machen das man die Rüstung über dem namen seht ohne dieses extra krimskrams bei nametags

Ich will so wie ohne Nametag. Nur mit Armor und das was er in der Hand hat über dem Kopf. Kann man dazu ein mode für Nametags machen oder ein eigenes Modul?

**Comment by SenkJu** [comment]
#1099

**Comment by IloveRickandmorty** [comment]
ok.
