### ISSUE TITLE
1.8 crosshair bug

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1109]
(in der 1.9 gefixt)

Wenn du F5 drückst soll der crosshair nicht mehr zu sehen sein. In der 1.8 ist er noch vorhanden.

**Comment by Marco-MC** [comment]
Ich fixe ledeglich wichtige Minecraft Bugs wie der https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1055.
