### ISSUE TITLE
rename command [Creative]

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1110]
wenn man .rename <Name> macht kann man gegenstände die man in der hand hält umbenennen. 
Farbcodes wie &4 sollen auch gehen. 

Wenn ich jetzt ein Diamantschwert in der Hand halte und .rename &1H&4a&5ll&2o mache dann soll das schwert hallo (halt mit diesen farbcodes) heissen.

Für Admin Plugins währe es cool.  Garkolym machte es auch. Er hat diese funktion im Izemod drin.

**Comment by Marco-MC** [comment]
Added
