### ISSUE TITLE
NoAFK

### ISSUE THREAD

**Issue by IloveRickandmorty** [CCBlueX/LiquidBounce1.8-Issues#1111]
Soll kein Modul sein. (Man soll es über ein Befehl an oder ausschalten können. Mit .noafk on/off ) Wenn du dich 28 Sekunden nicht bewegst soll der client einfach jede 28 sekunden ein Jumppacket senden. (Im Client Bewegst du dich garnicht)

Bei Rewi wirst du dann nicht als AFK gekennzeichnet. Natürlich auch nicht bei anderen Servern.

**Comment by Bircko** [comment]
oder er läuft einfach in denn greis

**Comment by IloveRickandmorty** [comment]
greis? du meinst er läuft einen kreis. 

Springen währe einfacher. Wenn neben dir ne Schlucht ist fällst du rein. Und dann? Beim Springen kann nichts passieren. (ok ausser über dir ist lava die sich nicht bewegt -.- aber ernsthaft. Wann passiert sowas. Und wenn kann man es dann aus machen. .noafk off )

**Comment by SenkJu** [comment]
Springen bypasst kaum noch ein AFK System. Und wieso willst du nicht als AFK gekennzeichnet werden, wenn du AFK bist?

**Comment by IloveRickandmorty** [comment]
nein. Wenn du auf Rewi 60 sekunden nichts machst wirst du in so ne Lobby teleportiert. Das nervt. Bei manch anderen servern ist das auch so.

**Comment by IloveRickandmorty** [comment]
Wenn springen nicht geht dann derpst du alle 28 sek kurz. Das geht sicher.

**Comment by IloveRickandmorty** [comment]
"Und wieso willst du nicht als AFK gekennzeichnet werden, wenn du AFK bist?" Wenn man nur schnell aufs Klo geht und dann Im AFK bereich ist nervt das sehr. (oder wenn man auf gemanden wartet)
