### ISSUE TITLE
AAC Noswing

### ISSUE THREAD

**Issue by IloveRickandmorty** [CCBlueX/LiquidBounce1.8-Issues#1113]
Der Hybrid Client hat ein Noswing der auf AAC Perfekt funktioniert.

**Comment by IloveRickandmorty** [comment]
MaxHD hat es mir gezeigt. Er ist grade auf dem Server. Wenn ihr es sehen wollt.

**Comment by IloveRickandmorty** [comment]
Man sieht nicht mal die Abbauanzeige.

**Comment by IloveRickandmorty** [comment]
Bei Hybrid heisst es NoBlockBreak

**Comment by Marco-MC** [comment]
Der von Hybrid ist soweit ich weiß Clientside und das hat LiquidBounce auch. (Kann man einstellen)
