### ISSUE TITLE
Rename Rainbowspeed und nen richtigen Rainbowspeed hinzufügen

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1115]
Rainbowspeed in Rainbowamount renamen weil mehr ist das auch nicht und einen richtigen Rainbowspeed hinzufügen so wie bei Ambien.

**Comment by IloveRickandmorty** [comment]
hä so wie es ist ist es doch schön?
Wen du Ambien so feierst kauf ihn dir und spiel mit dem Client.

**Comment by Bircko** [comment]
IloveRickandmorty selbst Hauptschüler würden den Sinn hinter meiner Aussage begreifen....

**Comment by IloveRickandmorty** [comment]
Ich habe es schon verstanden. Es nervt nur wie du dieses "Tolle" Ambien design hochlobst obwohl es nur ein Langweiliger Rainbowspeed ist. Wenn du viele Farben sehen willst geh in die Disco.

PS: Ich habe das im Discord gesehen -.- _Fick dich_

**Comment by IloveRickandmorty** [comment]
Ach ja ich komme diesen Sommer ins Gymi ^^ Du hingegen gehörst in den Kindergarten. Bemerke ich an deinem Profilbild auf Discord.

**Comment by Bircko** [comment]
Ja ich lobe das designe von Ambien so viel in dem ich einfach sag das Ambien einen richtigen Rainbowspeed hat und Liquidbounce nicht.... übrigens das nennt sich schwarzer Humor, war mir schon klar das du soetwas nicht verstehst. Aber wenn mir schon mal von Profilbildern sprechen, du hast irgendeine Comic Figur als PB...

**Comment by IloveRickandmorty** [comment]
Schwarzen Humor kann man mit Witzen ausdrücken. Wenn ich einen Hasen der ein Hitlergruß macht als Profilfoto setze hat das nichts mit Schwarzen Humor zutun. Klar kann man das mit Humor sehen. Man kann aber alles mit Humor sehen. Ich kann ne Banane als Profilbild machen und manche sehen darin einen Penis. Zudem Ist Rick and Morty eine Sehr beliebte Serie die in der USA beliebter sind als Dragonball etc. Zudem ist es ab 16. Nichts für keine Kinder wie dich.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1073
