### ISSUE TITLE
Änderbarer Command Präfix

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1116]
Also das man statt .  einen - hat oder sonst irgendetwas, falls du gefragt wirst . in den chat zu schreiben.

**Comment by IloveRickandmorty** [comment]
#596 hat jemand schon vorgeschlagen. macht .say (ich weiss. der geht immoment nicht. In der b27 geht er wieder)

**Comment by Bircko** [comment]
Wo hat das bitte jemand vorgeschlagen? Er hat nur vorgeschlagen das man zwischen 4 präfixe auswählen kann aber nicht das man selbst irgendetwas beliebiges auswählen kann z.b. .prefix - oder .prefix ?

**Comment by IloveRickandmorty** [comment]
ernsthaft?? Junge. Senk ju sagte das man .say verwenden soll wenn man einen Punkt schreiben will. Da kannst du das ganze alphabet hinschreiben das ist egal. Punkt bleibt Punkt. (Ok ausser das CCBluex team hat sich um entschieden.)
