### ISSUE TITLE
KillAura: BlockRate option

### ISSUE THREAD

**Issue by B3nutz3r** [CCBlueX/LiquidBounce1.8-Issues#1119]
Legit Autoblock wie damals in Vice/Hush

**Comment by Bircko** [comment]
Autoblock von Scaffold oder Autoblock bei Killaura xD

**Comment by Marco-MC** [comment]
Er meint ein Combat AutoBlock, kein Build AutoBlock. @Bircko

**Comment by DieSwitch** [comment]
Ich denk es anders rum. Wenn ich bei scaffold autoblock an habe baue ich mit dem Schwert (was man halt in der hand hat) Clientside und Serverside. Und er meint ob der Scaffold nicht einfach legit auf den block geht und dann baut. Würde bei alles servern Bypassen.

**Comment by SenkJu** [comment]
Nein, er meint den Combat AutoBlock, weil Vice das hatte.

**Comment by maxhd0** [comment]
k

**Comment by Marco-MC** [comment]
Added
