### ISSUE TITLE
Anti Arrow in Player

### ISSUE THREAD

**Issue by Namebittehiereingeben** [CCBlueX/LiquidBounce1.8-Issues#1130]
Wie in BouncePlus

**Comment by SenkJu** [comment]
Nutzlos. Gibt einen Grund, warum das entfernt wurde.

**Comment by Namebittehiereingeben** [comment]
schon ok XD Ich weiss nicht mal genau was es macht XD. Sieht man die Arrows einfach nicht mehr? oder sind die Für andere auch nicht mehr sichtbar? Wenn ja währe es halt gut für Unsichtbarkeit. Wenn da fliegende Pfeile laufen.
