### ISSUE TITLE
Auto Fish

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1131]
BouncePlus hat es auch. Da LB der nchfolger von BouncePlus ist soll LB es auch haben. Währe cool. 

Kann man rausgehen und wenn man wieder kommt hat man ein Schatz geangelt XD

**Comment by Namebittehiereingeben** [comment]
[88] scorpion3013  woher weisst du das ich auf dem discord bin?

**Comment by Namebittehiereingeben** [comment]
"MaxHD du bist n abfuck kiddy geh in den sandkasten spielen und werf all deine drecks elektronik aus dem fenster."  nö

**Comment by scorpion3013** [comment]
"Hier wurde man eine Server ip reingeschickt nur hier, rate mal wer kurz danach auf dem server war, der MaxHD"

**Comment by Namebittehiereingeben** [comment]
ich habe es gelesen

**Comment by Namebittehiereingeben** [comment]
Warum nochmal kann mich marco nicht leiden?

**Comment by Namebittehiereingeben** [comment]
Wegen der vielen Issues?

**Comment by Namebittehiereingeben** [comment]
Ist das nicht eher gut? XD

**Comment by Namebittehiereingeben** [comment]
ja finde ich auch gut. github is beschte.

**Comment by Marco-MC** [comment]
1. Du hast andauernd uns mit irgendwelchen Sachen auf Discord zu gespammt.
2. Du hast durchgehend Issues gespammt, die entweder schon gab oder schonmal abgelehnt wurden.
3. Du umgehst immer die Bans, egal ob auf Discord oder GitHub.

**Comment by Namebittehiereingeben** [comment]
> Du hast uns andauernd mit irgendwelchen Sachen auf Discord zu gespammt. ( mach ich nicht mehr)

> Du hast durchgehend Issues gespammt, die entweder schon gab oder schonmal abgelehnt wurden. (ok sry. bei 3-4 Issues fand ich es halt sehr schade. beispiel Cmdblock. wer macht bitteschön 
.give command_block 1 0 {Command:"/gamemode @p"} machen.  Da ist doch .CMDBlock <Befehl> einfacher.

> Du umgehst immer die Bans, egal ob auf Discord oder GitHub. (klar wenn man 1 mal gebannt ist will man sich doch entbannen. Wer will schon gebannt werden.

**Comment by Namebittehiereingeben** [comment]
http://www.bilder-upload.eu/show.php?file=789e54-1501515593.png

sry ich war das nicht.

**Comment by Namebittehiereingeben** [comment]
Mir ist nichts besseres eingefallen. Darum habe ich mich I love rick and morty genannt. **mal**

**Comment by Fleroxh** [comment]
lol... 

> (klar wenn man 1 mal gebannt ist will man sich doch entbannen. Wer will schon gebannt werden. )

Schon klar... xDD

**Comment by MaxHD0** [comment]
stimmt doch ^^

**Comment by superblaubeere27** [comment]
gabs das nicht schon mal? und ausserdem für sowas nutz Wurst

**Comment by DieErdnuss** [comment]
Ne wurst ist scheisse. Man will nicht 600 Clients im Launcher haben. sondern man will 1 guten client haben. Wenn man autofisch nutzt nutzt man auch andere sachen die Wurst nicht hat sondern nur Liquidbounce.

**Comment by Marco-MC** [comment]
Junge, AutoFish ist zum AFK rumstehen und dann angelt er für dich halt.
Für sowas mal Wurst zu starten ist echt nicht schwer.
Du kannst dir auch AutoFish Forge Mod in den Mods Ordner hauen: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2530407-autofish-forge-mod-for-minecraft-1-12-1-11-1-10-1

**Comment by Marco-MC** [comment]
Damit du mir nicht auf den piss gehts weiter mit dieser super tollen Idee die total nicht unnötig ist, schaue ich trz mal ob ich nen AutoFish machen kann.
Sollte in der 1.8 noch recht leicht sein.

**Comment by MaxHD0** [comment]
._.

**Comment by Maxhd0** [comment]
noch 1. Forge ist scheisse. Pro mod verliere ich mindestens 3 FPS. Da ich ohne forge knap über 60 komme will man da natürlich nichts noch zumüllen. (finde es desshalb auch schade, dass du dieses Realistische Item auf dem Boden entfernt hast (kp wie der mod heisst))

**Comment by Bircko** [comment]
ghost dann hättest bei großen modpacks wie ftb aber 0 fps weil da sind 100+ mods meist enthalten...

**Comment by superblaubeere27** [comment]
Nimm den [LiquidLauncher](https://ci.liquidbounce.net/job/LiquidLauncher) und die die Mod von @Marco-MC (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2530407-autofish-forge-mod-for-minecraft-1-12-1-11-1-10-1) und füge sie bei "Configure mods ein"

**Comment by DieSwitch** [comment]
Es kommt auf die Forge version an. In der 1.7.10 kann ich so viele Mod wie ich will rein machen. Juckt nicht.
(naja stimmt nicht ganz. Gui mods senken nur die fps. Also wenn auf meinem Bildschirm irgenwas angezeigt werden. ) Bei modpacks mache ich desshalb immer diese zusatz sachen in der gui aus.

**Comment by Marco-MC** [comment]
Added
