### ISSUE TITLE
Chat color buttons

### ISSUE THREAD

**Issue by Namebittehiereingeben** [CCBlueX/LiquidBounce1.8-Issues#1132]
http://i.imgur.com/imOFGLC.png

man kennt ja nicht immer alle farben &1 .... 
Dafür währe es da.

**Comment by Namebittehiereingeben** [comment]
#1110 Man könnte das leichter auch bedienen.

**Comment by Fleroxh** [comment]
Hey, Max. xDD

**Comment by MaxHD0** [comment]
hey ^^

Marco ich sage Features die Vorteile gegen über einem Normalen Spieler bringen.  Denkst du ein hack client hat nur speeds flys und ne killaura?  Es ist doch auch inordnung wenn man was anderes auch hinzu kommt. Es gibt viele clients mit bypasses. Aber ein Client der auch mal ne Abwechslung hat wo andere nicht haben ist das doch auch mal gut.  Jetzt zu dieser isse denke ich mir Normale spieler müssen Google öffnen, die Farbe suchen, auswählen und anschliessend eintippen.  LB spieler können einfach die Rot taste drücken und schon hat man es vereinfacht. Punkt.

**Comment by MaxHD0** [comment]
Bei jeder issue denke ich wie kann ich MC vereinfachen. (das eigendlich der sinn beim Hack client ist.) z.b killaura. Wer will schon schwitzen. Die aura macht es für dich. Usw. 
Auto Fish vereinfacht. 

Natürlich gibt es auch sachen wie fly wo man nichts vereinfacht sondern Sachen macht wo im Orginalen MC nicht funktionieren. Sowas sage ich dann auch. Nur oft gibt es sowas nicht.

Und Nur weil man issues sagt die Was bringen ( ich weiss schon das nicht jede Issue so nötig ist. Aber es würde vereinfachen.)

**Comment by SenkJu** [comment]
Nein, LiquidBounce ist und bleibt ein hacked Client und kein Utility Mod. So gut wie alles, was du vorschlägst, gibt es bereits als eigenständige Mod. Wieso sollten wir das adden? LiquidBounce ist schließlich ein Forge Client.

**Comment by maxhd0** [comment]
ok. Dann mache ich mich nützlich und mache Autosettings.
