### ISSUE TITLE
Gamehacks modul

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1134]
Dieses Modul dient nur für gewissen Spielmodis. Man kann jewals nur 1 mode auswählen.
Es ist nicht immer ein ESP. 

- MurderESP [Hypixel] (Wenn ein Spieler ein Schwert in der Hand hält wird dieser von einem Roten ESP angezeigt.

- Hide and seek ESP [Mineplax , Hive]  (wird in #590 erklärt)

- TTTESP  [gomme, etc]  (Spieler die andere Spieler Schlagen werden vom ESP angezeigt.)

-Minecartaura [cytooxien] (Ein spiel von Marioparty. Reise nach Jerusalem. Man muss in die Minecarts steigen.)

(Team CCbluex falls ihr noch mehr Spielmodis kennt, die eine Hilfe benötigen könnt ihr sie Natürlich hinzufügen.)

**Comment by SenkJu** [comment]
Ich persönlich finde Cheats, die auf Minigames spezialisiert sind, die sowieso so gut wie niemand spielt, extrem nutzlos.

**Comment by DieErdnuss** [comment]
Ich habe die jetzt mal aufgelistet, die Ich persönlich viel spiele. Wenn andere Spieler noch ideen haben können die es ja noch dazu schreiben.

**Comment by superblaubeere27** [comment]
wie wäre es mal mit einem ingame radio? oder eine automatische massage oder man könnte ja LB mit seinem Iphone connenten

**Comment by DieErdnuss** [comment]
._. rly?

Also das mit dem Radio würde ich gut finden. Jedoch weiss ich das Marco es sinnlos findet. Naja Ein Radio ist auch sinnlos XD Un wenn son Noteblock spieler. Denn für radio öffnet man einfach den Browser. Für noteblocks gibts nichts. Und wenn Pascal (arab) wieder ein lied spielt auf dem Pokeserver hört jeder gerne zu XD
