### ISSUE TITLE
Hand bug 1.8

### ISSUE THREAD

**Issue by DieErdnuss** [CCBlueX/LiquidBounce1.8-Issues#1136]
http://www.bilder-upload.eu/show.php?file=f9bd8b-1501602788.png

ES nervt wenn die Hand manchmal so rumbugt.

**Comment by Marco-MC** [comment]
Das ist ein Bug von normalen Minecraft, ich persöhnlich weiß nicht woran es liegt und kann es daher auch nicht fixen.
