### ISSUE TITLE
Antibot armor funktioniert nicht 

### ISSUE THREAD

**Issue by DieErdnuss** [CCBlueX/LiquidBounce1.8-Issues#1137]
http://www.bilder-upload.eu/show.php?file=20a00b-1501602900.png

**Comment by Marco-MC** [comment]
https://gyazo.com/8410b67607508c724c4c3c39b34b7f53
Ich konnte jetzt nichts feststellen, dass etwas nicht klappt.

**Comment by Marco-MC** [comment]
Könntest du mir die IP von dem Server sagen, damit ich es besser überprüfen kann?

**Comment by DieErdnuss** [comment]
Rewinside.tv

**Comment by DieErdnuss** [comment]
Das sind die Bots wenn man das Inventar öffnet.

**Comment by Marco-MC** [comment]
Anscheind in der b27 gefixt.
Es ist mir nicht aufgefallen, aber anscheind habe ich es bei den ganzen Changes der b27 einfach schon gefixt gehabt.
