### ISSUE TITLE
Copy, paste und Markieren button im Chat

### ISSUE THREAD

**Issue by DieErdnuss** [CCBlueX/LiquidBounce1.8-Issues#1138]
Oben rechts soll ein Copy, Paste und Markieren Button sein. (damit soll man Texte die im Chat geschrieben worden sind kopieren können. (währe cool wenn dir jemand ein Javacode sendet. Dann kannst du es gemütlich markieren und anschließend Kopieren.))

**Comment by SenkJu** [comment]
Nein, nein, nein, nein, nein, nein, nein, nein.

**Comment by DieErdnuss** [comment]
hem k

**Comment by Marco-MC** [comment]
WTF?

**Comment by DieErdnuss** [comment]
positives WTF oder negatives?

So schlimm ist die idee nicht.
