### ISSUE TITLE
textfile spammer

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1139]
Man kann eine txt auswählen und der spammer spammt dann den Inhalt, neue Zeile = Neuer Satz(so wie bei alt import halt). Random und Linear mode, Delay und bypass natürlich auch.

**Comment by RealFantaCoke** [comment]
Wäre gut.

Also im Prinzip so wie in "Saint" (der Vorgänger von "Icarus")

**Comment by Bircko** [comment]
Würde übrigens auch 99% der anti Spam plugins bypassen.

**Comment by superblaubeere27** [comment]
Für den bypass hab ich was anderes, und zwar den custom spammer
`%i LiquidBounce %i by %i CCBlueX %i` wird zu `2342 LiquidBounce 3466 by 6366 CCBlueX 5263`

**Comment by DieSwitch** [comment]
Man ann beides rein machen. Das eine ist wenn man es im Client machen will das andere ist eine Liste von Texten. [Das mit den Texten fällt aber auch nicht auf. Wenn du im chat liest [hallo 8hfrow ich wiierz bin 932r2839 klug zwiurz ] dann weiss jeder du hackst (und eventuell liest es dann auch keiner/kann es nicht lesen)

**Comment by scorpion3013** [comment]
Textspammer ist nice, erstmal Songtexte spammen :lenny:

**Comment by maxhd0** [comment]
XD

**Comment by TheRealDAT** [comment]
Gute idee aber dann noch im Textfile irgendwelche codes zb %delay=20% damit man die nachrichten unterscheidlich schnell schreibt.

**Comment by Teals53** [comment]
https://forum.ccbluex.net/thread.php?id=837
