### ISSUE TITLE
MC Tab bug

### ISSUE THREAD

**Issue by DieErdnuss** [CCBlueX/LiquidBounce1.8-Issues#1140]
Wenn ich ein server betrete (z.b gomme) und tab drücke laggt es 2 Sekunden. Dies passiert nur in der 1.8 und 1.9. In der 1.7 sah Tab noch anders aus. (da hat es nie gelaggt) und seit der 1. 10 oder 1.11 laggt es auch nicht mehr. Bitte fixen.

**Comment by Marco-MC** [comment]
Junge, ist nicht unser Problem.

**Comment by Marco-MC** [comment]
Wir oft denn noch ich FIXE NUR BUGS DIE WIRKLICH WAS BRINGEN
