### ISSUE TITLE
FakeHackers Modul

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1141]
Wenn eingeschaltet sieht es für dich so aus als würden alle Spieler hacken.

Man kann damit beweise fälschen, dass jemand hacken solle.

Es soll so aussehen als hätte er Derp, Killaura, SkinDerp und Sneak an.

 Settings:

Killaura [on/off]

Derp [on/off]

SkinDerp [on/off]

Sneak [on/off]

**Comment by TheRealDAT** [comment]
Ich find das sehr hilfreich du kannst auch in echt sowas machen dann wirkt das so als ob andere dich umbringen nimm ein Strick wickel ihn um dein Hals stell dich auf einen stuhl und kick den stuhl weg.

**Comment by Maxhd0** [comment]
was findest du hilfreich? Das die Leute die Fackehackers an haben sich erhängen XD k mir doch egal.

**Comment by TheRealDAT** [comment]
Du blickst gar nichts durch oder?

**Comment by Marco-MC** [comment]
Ich fass es kurz für dein Schildkröten Hirn:
Er will das du dich erhängst.

Du! Seiel! Decke! Knoten! Kopf! Tot!

**Comment by DerDetlef** [comment]
TheRealDAT ich wollte schreiben das ich es schon verstanden habe aber es mir total scheiss egal ist und das ich dich damit provoziere. Leider hat mich marco schon gebannt. Also musste ich paar sekunden warten bis der bot mir en neuen acc machte. sry bro

**Comment by TheRealDAT** [comment]
Ok krass provoziert du hurensohn

**Comment by superblaubeere27** [comment]
Da ist ja ein Radio noch besser.
Was soll das denn bringen, ausser dass wir unnötigen code schreiben müssen
