### ISSUE TITLE
ArrowDodge

### ISSUE THREAD

**Issue by DieErdnuss** [CCBlueX/LiquidBounce1.8-Issues#1142]
Wenn an soll er Pfeilen ausweichen. Dies macht er mit einem Teleport einem Blink oder einem Timer.

Mode:

- Teleport (wenn ein Pfeil den Spieler treffen sollte Teleportiert ArrowDodge dich unter das Grundgestein und Anschließend wieder zurück (dies macht es mit Vclip -[tiefe bis zum Grundgestein] 
(nützlich auf Low Anticheats wie Mineplax oder Vanilla)

- Blink (wenn ein Pfeil den Spieler treffen sollte läuft Blink 0,5 blöcke links, rechts , vor oder zurück. (jenachdem was dafür sorgt das er nicht mehr vom Pfleil getroffen wird.)

- Timer (wenn ein Pfeil den Spieler treffen sollte läuft Timer 0,5 blöcke links, rechts , vor oder zurück. (jenachdem was dafür sorgt das er nicht mehr vom Pfleil getroffen wird.)

(nach dem Pfeilausweichen soll ArrowDodge dich wieder dahin stellen wo du warst. Bei allen Modes.)

Blink und Timer sollten sogar auf Anticheats bypassen.

**Comment by Marco-MC** [comment]
Geh sterben.

**Comment by Maxhd0** [comment]
nö :P

**Comment by Maxhd0** [comment]
"WIE SCHWER IST ES EINEN FUCKING PFEIEL AUSZUWEICHEN?" wenn man in Bedwars zur mitte läuft ist es schwer.

**Comment by Maxhd0** [comment]
ja gut keine Tobsuchtsanfälle.

**Comment by Maxhd0** [comment]
schon gut.

**Comment by Marco-MC** [comment]
Du weißt nicht wie viel Arbeit es wäre dieses so extrem unnötige Modul zu coden?

**Arrow tracing
Path finding**

**Comment by Marco-MC** [comment]
Geh einfach sterben, lass uns endlich entruh. Mit deinen doppelten Issues, vorallem ist zu 80% irgendwas dass einfach total unnötig ist.
