### ISSUE TITLE
Schnell scrips auswählen im Click GUI

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce1.8-Issues#1144]
Also dass man sich Scripts erstellen kann und die dann im ClickGUI auswählen kann oder voreingestellte wie zb. AAC, NCP, usw. Und das soll in einem neuen Reiter sein.

**Comment by Maxhd0** [comment]
XD

**Comment by TheRealDAT** [comment]
Bist du nicht MaxADHS?

**Comment by Marco-MC** [comment]
Habe ich schonmal abgelehnt.
