### ISSUE TITLE
Eine ClickGUI erweiterung

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce1.8-Issues#1145]
Dass die Settings als extra Reiter im Click GUI sind wie ich Alpha Centauri oder Rapture

**Comment by Maxhd0** [comment]
Ps: habe es schon verstanden. Provoziere dich nur weil es mir total scheiss egal ist. :P

**Comment by Marco-MC** [comment]
Nein, definitiv nicht. @TheRealDAT
