### ISSUE TITLE
Reconnect button ein aus schalten können

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce1.8-Issues#1146]
Wie ich Alpha Centauri wenn man drauf klickt wird er Grün(an) und wenn man drauf klickt wird er Rot(rot) dann ist er aus Falls man screenshoten muss oder sowas wär usefull

**Comment by maxhd0** [comment]
NEIN ES BLEIBT ALLES SO WIE ES IST UND ES WIRD SICH DARAN AUCH NICHTS RÜTTELN EGAL OB DU HIER BIST ODER NICHT!

**Comment by maxhd0** [comment]
XD

**Comment by RealFantaCoke** [comment]
Total unnötig.
