### ISSUE TITLE
GhostMode

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1147]
Ein GhostMode welchen man mit einem Knopf im Optionen-Menü ein und ausschalten kann.

Der Platz für den Knopf ist egal.
Kann auch in der GUI sein.

**Comment by SenkJu** [comment]
#1103

**Comment by RealFantaCoke** [comment]
@SenkJu Das ist was anderes.
Ich meine einen richtigen GhostMode.

Wenn man LiquidBounce uninjected dann muss man Minecraft sicherlich neustarten.
Bitte den Thread wieder öffnen.

@Marco-MC Was sagst du dazu? :)

**Comment by Marco-MC** [comment]
Alles beide scheiße.
LiquidBounce ändert soooo fucking viele Minecraft Class Sachen und das dann einfach deaktivierbar zu machen ist einfach scheiße viel Arbeit.

**Comment by RealFantaCoke** [comment]
Okay, danke für dein Feedback.

**Comment by Marco-MC** [comment]
Ich denke eher das ich es nicht mache, aber vielleicht irgendwann. Es kann auf jedenfall in der TODO List bleiben.

**Comment by Marco-MC** [comment]
Der Ghostmode und der in Anführungs Zeichen Un-inject würde, eh komplett gleich funken.
Leider kann man in Forge (Mixin), soweit ich weiß nicht einfach die classes un-injecten.
Daher müsste ich mir etwas anderes ausdenken, um das einfach invis zu machen. (bzw. habe ich schon)

**Comment by DieSwitch** [comment]
Ich dachte beim Ghostmode deaktiviert man alles ausser die Clickgui. Damit man noch hacken kann nur halt das andere sachen wie die Chat animation oder der Reconekt button verschwinden. So funktionierte auch der Ghostmode bei Alpha centauri. (ab version 6.4)

**Comment by Adryd** [comment]
Ghost mode is just hiding GUI (other than clickgui), Un-injection is panic
I'd primarily like ghost mode for the title screen
