### ISSUE TITLE
Custom spammer

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#1148]
https://git.liquidbounce.net/CCBlueX/BypassClient/blob/master/src/main/java/net/ccbluex/LiquidBase/module/modules/chat/CustomSpammer.java

Man kann als text `%i sp_%i_am %i` und raus kommt `2335 sp_7534_am 6546`
 %i  | Zahl von 0-10000                
 %f  | Gleitkommazahl (z.B: 45.0634)   
 %s  | Text von 1-8 Buchstaben         
 %ss | Kurzer Text von 1-4 Buchstaben  
 %ls | Langer Text von 1-15 Buchstaben 
 %ls | Langer Text von 1-15 Buchstaben

**Comment by Marco-MC** [comment]
Added to Spammer as option

**Comment by Marco-MC** [comment]
Added
