### ISSUE TITLE
Anti x-ray bypass

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1149]
http://www.bilder-upload.eu/show.php?file=c046be-1501852782.png

X-ray zeigt nur erze an wo 2 , oder 4 nebeneinander sine (einstellbar)

Ich habe schon mal Diese issue gebracht. Da senk ju sagte wie soll es das Spigot anti xray bypassen. Denn so geht das nicht. Aber es gibt noch ein anderes Anti xray. Und das kann man so bypassen.

**Comment by maxhd0** [comment]
von wann ist ist das duplicated

**Comment by maxhd0** [comment]
#1010 fals du denkst wegen dem. Ich habe es gecloset weil ich dachte diese Art von Antixray gibts nicht mehr. Da ich jetzt aber den server gefunden habe kann ich die issue wieder on machen.

**Comment by maxhd0** [comment]
*griefergames

**Comment by maxhd0** [comment]
Also ist es nicht doppelt

**Comment by maxhd0** [comment]
und ne arbeit ist es auch nicht.

**Comment by maxhd0** [comment]
PS: ich habe mein bot geupdated. er macht es jetzt innerhalb 10 sekunden ^^

**Comment by maxhd0** [comment]
Und wenn du alle kommentare speerst können andere aucgh nicht schreiben

**Comment by maxhd0** [comment]
k
