### ISSUE TITLE
Anti x-ray bypass 

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1150]
http://www.bilder-upload.eu/show.php?file=c046be-1501852782.png

X-ray zeigt nur erze an wo 2 , oder 4 nebeneinander sine (einstellbar)

Ich habe schon mal Diese issue gebracht. Da senk ju sagte wie soll es das Spigot anti xray bypassen. Denn so geht das nicht. Aber es gibt noch ein anderes Anti xray. Und das kann man so bypassen.

#1010 falls du denkst wegen dem. Ich habe es gecloset weil ich dachte diese Art von Antixray gibts nicht mehr. Da ich jetzt aber den server gefunden habe kann ich die issue wieder on machen.

**Comment by maxhd0** [comment]
hr kennt es. Ihr startet X-Ray und der gesammte boden ist voller Erze. Wenn man sich aber dann hinbaut verschwinden die Erze.

Bypass: X-Ray zeigt nur die Erze an neben dem noch ein Erz ist.

O = ERZ

X = Stone

XXXXXXXXXXXXX
XXXXXXXXXOXXX <---- Wird nicht gezeigt
XXXXXXXXXXXXX
XXXXOOXXXXXXX <---- Wird gezeigt
XXXXXXXXOXXXX <---- Wird gezeigt
XXXXXXXXOXXX <---- Wird gezeigt

**Comment by Fleroxh** [comment]
@maxhd0 Geschlossen heißt geschlossen!
