### ISSUE TITLE
süss

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1151]
http://www.bilder-upload.eu/show.php?file=43dbac-1501855979.png

die suchen nach mir. süss

Seit 1 nem monat habt ihr mich nicht mehr gebannt. Ihr bannt verzweifelt leute weil euch nichts besseres einfällt XD

**Comment by maxhd000** [comment]
PS: habe jetzt auch ip änderer im bot

**Comment by maxhd000** [comment]
ihr könnt die issue closen. ich habe kein bock

**Comment by SenkJu** [comment]
Nein, wir bannen verzweifelt dich, weil deine pure Anwesenheit den IQ im Discord signifikant herabsetzt. Und wenn wir dich nicht vom Discord gebannt hätten, wieso eröffnest du dann hier einen Issue und sagst uns das nicht einfach im Discord? Ich sage so etwas ja wirklich nicht oft, aber Kill yourself.

**Comment by maxhd000** [comment]
Wenn ich es im discord sage bannt ihr mich direkt. Und sich im discord zu entbannen ist nervig. Discord hat seit nem haben jahr ein bug wo man sich entbannen kann. Dieser funktioniert gut jedoch dauert es ca. 36 minuten und man muss sehr viel klicken. Und das nervt. Zudem schreibe ich auf dem discord ehh nicht mehr viel. Bzw wenn marco on ist schreibe ich garnicht.

**Comment by SenkJu** [comment]
Verreck am Sperma deines Vaters, dummes Lügenkind.
