### ISSUE TITLE
So verarscht man richtig XD

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1154]
Wenn ich sage Spoopy dann ist es automatisch snoppy. Das solltest du doch wis.. Och ne. bist ja zu dumm. sry das ich dir es erklären wollte ;-)

wie kommt man auf den namen Spoopy? hört sich wie scheisse an. Lass es bei snoppy.

ach. ich amüsiere mich bei dir Marc

Ich nenne dich ab jetzt Marc XD das o hast du nicht verdient XD

**Comment by Marco-MC** [comment]
https://gyazo.com/92f2a33efade01e3f19036d8db28d12e Dir ist schon klar das ich als ich ihn umbennant habe, noch garnicht dein unnötigen GitHub Issue noch garnicht gesehen habe. Kid (Aufs geistige alter bezogen).
