### ISSUE TITLE
ClickGUI Speed

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce1.8-Issues#1158]
Dieser eine Punkt ist komplett useless mach lieber Speed dann Bhop, OnGround, YPort, AntiCheats und dann da die Speeds rein und bei Custom machst du so ein + hin damit man das einstellen kann.

**Comment by Marco-MC** [comment]
Welcher Punkt?
Was meinst du?

**Comment by TheRealDAT** [comment]
Dieses "+" zum rechtsklicken
