### ISSUE TITLE
em Benjarobbi

### ISSUE THREAD

**Issue by maxhd00** [CCBlueX/LiquidBounce1.8-Issues#1160]
Benjarobbi Ich habe mein Bot eingestellt das er Jede 10 min Kontrolliert ob ich auf github server xy gebannt bin. Wenn nein wartet er wieder 10 min. Wenn ja Löscht er meinen 2 account. Anschliessend erstellt er einen Völlig neuen. Dann Klickt er auf diesen Bestätigungslink (e-mail) Am anfang musste ich das mit der e-mil immer machen bevor er weiter machte. Anschliessend soll er noch ein bild rein machen. (habe ich immoment aus) (leider geht das nicht immer.) Und dann fertig. Dieser bot spammt nicht. Warum auch? Benjarobbi.
Und beim Discord habe ich garkein bot mehr. Den den ich vor 2 monaten gemacht habe habe ich schon gelöscht, da er scheisse war. er hat er hat einfach das war ich 1 mal gemacht habe immer wiederholt. Und dieses Entbannen macht kein bot. Das mache ich allein. Und das fuckt ab. Wenn ich nur 1 sek ein Knopf zuspät drücke sind 30 min am Arsch. Heute habe ich 1 stunde und 16 minuten gebraucht. Also Benjarobbi was laberst du XD

**Comment by maxhd00** [comment]
ich habe diese frage beantwortet #1152

**Comment by Benjarobbi** [comment]
"auf github server xy"
Hää? Ob du auf einem Github Server gebannt bist?

Bitte nutz auch in deinen künftigen Beiträgen mal Groß- und Kleinschreibung.

**Comment by Fleroxh** [comment]
@Benjarobbi xD
