### ISSUE TITLE
Friend-System (GUI, Search function)

### ISSUE THREAD

**Issue by Fleroxh** [CCBlueX/LiquidBounce1.8-Issues#1161]
(like LabyMod's FriendSystem)

**With an ID system (LiquidID):**

A GUI, where you can search LiquidBounce users and send them a friend request, via their LiquidID (an ID system) or via their name. 
If they accepted your friend request, then you can chat with them and you can see, if they are online. 

**Without an ID system (LiquidID):**

A GUI, where you can search LiquidBounce users and send them a friend request, via their minecraft name. 
If they accepted your friend request, then you can chat with them and you can see, if they are online.

**Comment by SenkJu** [comment]
Way too complicated. LiquidBounce is a hacked client and not a PvP extension. Install 5zig if you want these features. This would also make it extremely easy for server owners to find out who is using LiquidBounce.

**Comment by maxhd00** [comment]
Was ist denn jetzt Liquidbounce? Ein PVP Client oder ein Griefing client?

**Comment by maxhd00** [comment]
Bei griefing features sagt ihr nein und bei PVP feature sagt ihr nein.

**Comment by maxhd00** [comment]
Und bis jetzt hibt es nur griefing und PVP clients. Ihr nehmt paar sachen von dem und paar sachen von dem.

**Comment by Fleroxh** [comment]
@SenkJu I respect that. No problem.
