### ISSUE TITLE
Smoothfly Vannila anticheat bypass

### ISSUE THREAD

**Issue by maxhd00** [CCBlueX/LiquidBounce1.8-Issues#1163]
Der Smoothfly soll alle 3 Sekunden ein onground packet senden damit du auf Vanillaservern nicht für: "Fliegen ist nicht auf dem server erlaubt" gekickt wirst.

**Comment by Marco-MC** [comment]
Geht nicht.

**Comment by maxhd00** [comment]
Hä der Skash client hatte das doch. selbst der leak 2.0

**Comment by maxhd00** [comment]
Schau dir den Skash client mal an. (mach den Vannila mode bei fly an)

**Comment by Marco-MC** [comment]
Junge, so geht der Bypass aber nicht.
Ich weiß zwar wie der Bypass geht, nur so wie du gesagt hast geht er nicht. Sonst würde ja der Hypixel Fly auf Vanilla auch nicht kicken, laut deiner aussage.

**Comment by Fleroxh** [comment]
Bitte nicht nochmal posten. Abgelehnt bedeutet Abgelehnt. @ghost

**Comment by SenkJu** [comment]
Der Bypass funktioniert, indem man regelmäßig serverside kurz auf den Boden tpt.
