### ISSUE TITLE
Gomme Reach

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1169]
Wie das hier
https://www.youtube.com/watch?v=jgVbxMXMk60

**Comment by MaxHD00** [comment]
Du kannst Spieler über viele blöcke schlagen.

(funktioniert noch auf dem neusten aac. Aber auch wenn es nicht mehr auf aac gehen würde ist es noch für Vanilla oder low server gut.)

PS: nenn es Godhit ^^

**Comment by SenkJu** [comment]
Patched.
