### ISSUE TITLE
AAC Killaura ohne Flags

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1178]
Hier ein Beispiel:
https://youtu.be/uZH-4Vbw4Q0?t=7m9s

**Comment by Marco-MC** [comment]
Heuristics sind schon gebypasst. (_Komplett, mit korrekten Settings. Habe sogar eben nomma getestet, keine Heuristic Flags bekommen auf poke.sexy_)
Für Hitbox, muss ich noch nen Force Raycast einbauen.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1179

**Comment by Marco-MC** [comment]
Kann sein das die Heuristics erst in der b27 bypassed sind... Weiß grade nicht ob ich da noch was dran gearbeitet hatte... Hm, egal.
