### ISSUE TITLE
Areaminer

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1180]
Man gib Position1 und Position2 an, der Charakter läuft in dem Gebiet dann rum und baut das Gebiet ab.
Example: Cerura hatte soeinen namens "Survivalnuker" da die src von Cerura öffentlich ist ( von Macher public gemacht) könntest du diesen verbessern(effektiver machen(beim Rückweg baut er nicht ab)) und z.b die abau range einstellen lassen können, da es so ab und zu zu ghostblöcken kommt.

**Comment by SenkJu** [comment]
Dafür gibt es bestimmt einzelne Mods, die wesentlich effektiver sind.
