### ISSUE TITLE
fast AAC step (no flags)

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1193]
https://youtu.be/PHMXPRe-ZYU?t=297

https://youtu.be/PHMXPRe-ZYU?t=502

Liquidbounce hat derzeit keinen schnellen Step der nicht flaggt.

**Comment by MaxHD00** [comment]
https://www.youtube.com/watch?v=XaT2TefGzUo

der währe auch schnell

**Comment by hfgddgsjxajdh** [comment]
ghost könnte man nicht einfach die stepdelay bei b27 nicht runterstellen

**Comment by maxhd0** [comment]
ne
