### ISSUE TITLE
Fullbright modes

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1197]
Mode:

- Gamma

- Night Vision

- Day

**Comment by maxhd00** [comment]
Day kann es auch heller machen.

**Comment by Bircko** [comment]
ich hatte schon gehofft dass es dich nicht mehr gibt

**Comment by maxhd00** [comment]
sorry. Ich bin leider aber die Ganze zeit da. Nur halt unter anderem Namen.

**Comment by Marco-MC** [comment]
Added
