### ISSUE TITLE
Tracer Bug (false position while zooming)

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1198]
Der Tracer ist nicht in der Mitte :O
http://www.bilder-upload.eu/show.php?file=57d450-1502919829.png

Anzeige is raus.

wenn man Fov aufs minimum macht und dann noch zoomt sieht man es.

Ich weiss. Ich habe keine hobbys XD

**Comment by Marco-MC** [comment]
Das einzige was nicht in der Mitte ist, ist dein Gehirn.

**Comment by Marco-MC** [comment]
Naja, auf jedenfall... ist es normal das die Tracers bei so nem Zoom nicht direkt in der Mitte sind. Werde mir trz mal anschauen...

**Comment by Bircko** [comment]
Beim zoomen wird wahrscheinlich das Crosshair mit verkleinert und deshalb ist das so.
