### ISSUE TITLE
Custom Autoreconnect

### ISSUE THREAD

**Issue by Mangohax** [CCBlueX/LiquidBounce1.8-Issues#1204]
important 4 bruteforcing.

**Comment by Marco-MC** [comment]
Was soll das sein? xD
Junge, wenn du eh Deutsch kannst dann schreib Deutsch... MaxHD...
Wenn du immer etwas auf English schreibst, dann verstehen wir dich nie.

**Comment by maxhd00** [comment]
Das bin ich nicht XD

**Comment by maxhd00** [comment]
Was soll Custom Autoreconnect sein?

**Comment by maxhd00** [comment]
zudem wann schreibe ich englisch? XD
