### ISSUE TITLE
Panik Modul

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#1206]
Ein Modul dass alle aktiven Module deaktiviert wenn man das Panik oder anderer name Modul aktiviert. Kann auch ein . Command sein. Ist praktisch weil es mich stört immer alle Module einzeln zu deaktivieren.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/304
Nein, unnötig.

**Comment by SavageSOC** [comment]
i just keybind all my render mods to one key.
