### ISSUE TITLE
Bypass Server sided Texturepack

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1207]
If possible add a mode to bypass Texturepack from Minestrike since when you decline you get kicked. So you can play with your own Texturepack

**Comment by superblaubeere27** [comment]
Kann man das nicht selber umgehen?

**Comment by maxhd0** [comment]
ja, aber bei manchen servern wirst du dann gekickt.

**Comment by Marco09MC** [comment]
https://axolotl.church/BBih/jVHe8Nxt.mp4

Added
