### ISSUE TITLE
Antibot (needhit) verbesserung

### ISSUE THREAD

**Issue by maxhd00** [CCBlueX/LiquidBounce1.8-Issues#1208]
Wenn ich einen Spieler schlage soll der Client auch die Position merken. (so ähnlich wie ein Textradar) Das wenn ein Bot kommt der 1 zu 1 gleich ist aber die Pos nicht die Gleiche ist wie die des geschlagenen Spielers. (Wenn der geschlagene Spieler nicht mehr gerendert wird muss man ihn nochmal schlagen)
(das bypasst timolia)

**Comment by Marco-MC** [comment]
NeedHit bypasst Timolia schon, außerdem was ist das denn für ein Dreck? xD
Dir ist schon klar das jedes Entity eine EntityID hat und diese nicht doppelt sein kann.
Dieser Vorschlag ist komplett Müll.

**Comment by maxhd00** [comment]
ok. sorry wusste ich nicht.
