### ISSUE TITLE
Killaura auto switch to lowest health gegner

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1209]
killaura soll automatisch zum spieler mit dem wenigsten leben wechseln falls z.b. einer mit 3 herzen kommt und du kämpfst gerade mit einem mit 7 herzen soll er zu dem mit 3 herzen wechseln.

**Comment by Marco-MC** [comment]
Setz einfach die "Priority" auf "Health".

**Comment by Bircko** [comment]
Switched er da automatisch zu dem gegner mit dem niedrigsten leben?

**Comment by Marco-MC** [comment]
Klar.
Wenn du TartgetMode "_Single_ " aktiviert hast wird immer das beste Target genommen.
Bei Switch wird halt dann halt mit dem _"lowest health"_  Gegner angefangen.

_Sent from my Samsung SM-G531F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
