### ISSUE TITLE
Fucker renderbug with 5zig Mod

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1212]
Wenn man Fucker aktiviert, verschwinden die Displayanzeigen von 5zig Mod: 
https://youtu.be/O362SeVV1Nw

**Comment by Marco-MC** [comment]
Haha, das ist kein Bug... Du hast Fucker auf B oder?
Diese Taste ist bei 5zig Mod die "Display Toggle" Taste.

_Sent from my Samsung SM-G531F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by WistarWolf** [comment]
Achso. xd
