### ISSUE TITLE
LiquidBounce-1.8 Folder in .minecraft rename to LiquidBounce-1.8.x or 1.8.9

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1219]

**Comment by Marco-MC** [comment]
No.

**Comment by WistarWolf** [comment]
Wieso? Nenn mir nen guten Grund.

**Comment by Marco-MC** [comment]
1. Es müsste jeder Benutzer den Ordner nach der änderung renamen. (Könnte ich auch automatisieren, was ich in einem bestimmten update schon mal gemacht hatte)
2. **1.8.9** ist eine unter Version von **1.8**
3. Es ist nur ein Ordner Name? Wozu?

**Comment by FlorijonG** [comment]
ER SAGTE NUR 1 GUTEN GRUND SAMMA

**Comment by Marco-MC** [comment]
ER SAGTE NICHT "EINEN" SONDERN "NEN".

**Comment by FlorijonG** [comment]
"NEN" = "EINEN"

DU BLÖDER FETTSACK
