### ISSUE TITLE
Speed "Bug"

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1222]
Wenn man z.B. AACOnGround Speed deaktiviert, springt man kurz.
Mir ist noch was aufgefallen ich weiß nicht ob dasn Bug ist: Wenn man als Speed OnGround an hat, bugt man manchmal kurz runter. Tested Server: CCBlueX Test Server AntiCheat: Vanilla

**Comment by Bircko** [comment]
versuch mal hairjump aus zu machen.

**Comment by WistarWolf** [comment]
Ich hatte AirJump nichtmal an.

**Comment by Bircko** [comment]
Step oder reversestep?

**Comment by WistarWolf** [comment]
Nope. Keins von beidem

**Comment by WistarWolf** [comment]
Warte

**Comment by WistarWolf** [comment]
https://youtu.be/maPg0XWLuAo
