### ISSUE TITLE
Changable TabGUI/Text color

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1224]
Man soll denn Hintergrund/rect und text color ändern können. +RainbowMode

**Comment by WistarWolf** [comment]
Du kennst Marco... Er wird es nicht einbauen, soviel kann ich dir sagen.

**Comment by hfgddgsjxajdh** [comment]
Marco hat sowas schonmal abgelehnt bei diesem Maxhd außerdem bringt es nichts 20 design einstellunfen zu haben hauptsache der client ist gut und dass ist er auch

**Comment by MaxHD0** [comment]
:O

**Comment by Bircko** [comment]
hfgddgsjxajdh kys du bist maxhd guck dir mal deinen namen an

**Comment by MaxHD0** [comment]
ach ne

**Comment by superblaubeere27** [comment]
Warum nicht gleich ein Radio in LiquidBounce

**Comment by superblaubeere27** [comment]
Und eine Funktion mit der man jeden Rechner auf der Welt hacken kann
