### ISSUE TITLE
RainbowMode/Clear RainbowArraylist

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1225]
So wie das hier also das der RainbowEffect schon im String selbst vorhanden ist.
![rainbowarray](https://user-images.githubusercontent.com/29576723/29489194-780d95a6-851b-11e7-9011-0ce185305704.PNG)

**Comment by WistarWolf** [comment]
Jo wäre mal eine gute und neue Idee. Habe bisher glaube ich nur 1 Video gesehen in dem so eine ArrayList war.
