### ISSUE TITLE
Rainbow Arraylist Mode: Left to Right

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1226]
Also das es nicht von Oben nach Unten sondern von Links nach Rechts
![rbw](https://user-images.githubusercontent.com/29576723/29489220-0be93154-851c-11e7-9410-61f243601bef.PNG)

**Comment by WistarWolf** [comment]
Jo wäre mal eine gute und neue Idee. Habe bisher glaube ich nur 1 Video gesehen in dem so eine ArrayList war.
