### ISSUE TITLE
InGame LocalSettings rename Command

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1227]
.localsettings rename (oldscriptname) (newscriptname)

**Comment by SenkJu** [comment]
Rename the file

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by WistarWolf** [comment]
Ich weiß dass das geht. Aber dann muss ich jedes mal in den .minecraft Ordner und es ist leicht umständlich.

**Comment by SenkJu** [comment]
Wie oft willst du bitte ein Script renamen, dass man nicht mal den "Aufwand" auf sich nehmen will, den Dateinamen zu ändern.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
