### ISSUE TITLE
ESP Mode

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1229]
Ein ESP Mode mit dem Icon von AAC xd

**Comment by Marco-MC** [comment]
1. Könnte Copyright Probleme machen, wenn konsolas lust auf beef hat.
2. Unnötig.
3. **Reis Suppe**

**Comment by WistarWolf** [comment]
1. Hm vllt
2. Kannst du auch was anderes als unnötig schreiben? Kappa
3. **Frühlingsrolle**
