### ISSUE TITLE
Removing BedGodMode(It's for 1.9 in a 1.8 Client)

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1235]

**Comment by maxhd0** [comment]
naja ein bischen funktionierts ja. Man kann z.b ums Bett bauen oder andere schlagen während man im Bett ist. Das Problem ist dass man aber nicht wieder aufstehen kann. Der Aufstehen Button würde da helfen.

**Comment by superblaubeere27** [comment]
Jo das wäre gut

**Comment by maxhd0** [comment]
superblaubeere27 willstg du immer das gegenteil von dem was ich will?

Aber ok. Ich bentzte es ehh selten.

**Comment by Marco-MC** [comment]
Es funktioniert ebenfalls in 1.8.
Man kann sich mit dem Blink Teleport teleportieren, während man schläft und die Positions werden dann geupdated. Wenn man selbst rumleuft geht das nicht, das liegt daran das die 1.8 keine Move Packets normal schickt, während man schläft.

**Comment by maxhd0** [comment]
köntest du aber so ein "aufstehen" button noch hinzufügen?
