### ISSUE TITLE
Command Sign 

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1237]
"Command-Sign for 1.10.0 - 1.10.2" zu "Command-Sign for 1.8.0 - 1.8.3" oder halt in eine 1.8 Version in der ein Command-Sign funktioniert. Da es dumm ist wenn dort 1.10 steht der Client aber für 1.8 ist

**Comment by maxhd0** [comment]
geht der Command sign überhaupt noch irgendwo?

**Comment by superblaubeere27** [comment]
Nimm Wurst

**Comment by WistarWolf** [comment]
Ich will aber nicht Wurst sondern LiquidBounce benutzen sonst hätte ich es hier nicht reingeschrieben ._.

**Comment by maxhd0** [comment]
Ditto

**Comment by maxhd0** [comment]
Ich habe mich noch informiert. Ab der 1.8.4 kann man nur .give sachen machen. Davor ging alles: Gamemode, op etc. Das heisst wenn man sich ein schild macht kann man sich z.b opäpfel in gm0 geben.

**Comment by maxhd0** [comment]
ich probiere es mal aus.

**Comment by maxhd0** [comment]
hem. Es geht. Aber nicht auf spigot. Da geht garnichts mehr durch.

**Comment by SenkJu** [comment]
#700
