### ISSUE TITLE
Fucker: Block list

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1239]
Hi, 
is it possible to make an option for the Fucker (ID Nuker) to mine different blocks (e.g. Iron Ore, Coal Ore) without having to change the fucker (e.g. ".fucker select iron_ore" to ".fucker select coal_ore") every time?

**Comment by maxhd0** [comment]
Das gleiche bitte auch bei Ghosthand. Dann kann man endlich mit Ghosthand SG spielen. Im Moment geht das schlecht, da man ja auch Türen, etc bedienen muss.

**Comment by Marco-MC** [comment]
https://gyazo.com/5313e98043b40fada082c5f74b95dfeb ?

**Comment by henrydatei** [comment]
Was soll mir das sagen? Wie ich einen einzelnen Block einstellen kann, weiß ich, aber ich hätte gerne eine Funktion, wo ich mehrer Blöcke einstellen kann.

Beispiel: Ich befinde mich in einem Strip-Mine-Gang. Da ich ganz dringend Eisen und Diamanten brauche, würde ich gerne den Fucker so einstellen, dass er, wenn ich durch die Gänge laufe, sämtliches Eisen-Erz und Diamant-Erz abbaut, ohne dass ich zweimal durch den Gang laufen muss (einmal mit einem Fucker für Eisen-Erz und ein zweites mal mit einem Fucker für Diamant-Erz).

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3057
