### ISSUE TITLE
2D Mode für StorageESP und BlockESP + Full 2D Mode für ESP, StorageSP und BlockESP

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1240]
Full 2D Mode: Es kommt halt ein ganzer Rahmen um die Entitys, Kisten, Blöcke etc

**Comment by superblaubeere27** [comment]
Unnötig!

**Comment by WistarWolf** [comment]
Wenn es so unnötig ist kann man doch auch die ganzen anderen esp modes und storage esp modes entfernen man brauch ja nur einen mode.

**Comment by maxhd0** [comment]
WistarWolf superblaubeere27 findet alles unnötig. Wurdert mich warum er noch lebt. Warum noch leben? Das leben ist doch auch UNNÖTIG. stimmts? superblaubeere27. sag nichts. ich weiss das es ein ja ist.

**Comment by Marco-MC** [comment]
ESP (https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1375)
StorageESP
BlockESP

**Comment by Marco-MC** [comment]
Added
