### ISSUE TITLE
 velocity reverse strength command

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1241]
Ich weiss nicht ob es diesen Befehl schon gibt. Da ich aber im Stream keine Antwort bekam schreibe ich es jz mal als issue.

**Comment by Marco-MC** [comment]
Was ist denn jetzt passiert? Ich dachte du hasst Befehle?

**Comment by maxhd0** [comment]
ja aber bei manchen sachen sind sie besser. (bzw. Am besten ist GUI und Befehl)

**Comment by maxhd0** [comment]
Zudem. Wenn man was schnell einstellen will Ist die GUI am besten. Wenn man aber was ausprobieren will dann ist das in Befehlen besser.

**Comment by Marco-MC** [comment]
Added.
