### ISSUE TITLE
ArrayList 

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1242]
Eine Option mit der man den ArrayList Background "heller" machen kann: http://prntscr.com/gd55j8

**Comment by maxhd0** [comment]
XD Das ist die 1.11er Version. Bei der B26.2 sieht es doch gut aus. Für was muss man das heller bzw dunkler machen? (Marco wenn er ne gute begründung sagt versteh ichs und dann bin ich auch dafür)
