### ISSUE TITLE
All mods not showing up??

### ISSUE THREAD

**Issue by Fuzzy121** [CCBlueX/LiquidBounce1.8-Issues#1243]
I have recently installed your hacked client and i loved it but i came across something unusual. I was messing with the TABGui and saw tons of mods but when i go onto the click gui only haf of the mods show up. like this:
<img width="1280" alt="screen shot 2017-08-26 at 13 05 27" src="https://user-images.githubusercontent.com/31368406/29741178-44038e7a-8a5f-11e7-8d11-37efeb714914.png">
(See all them mods) Look:
<img width="1043" alt="screen shot 2017-08-26 at 13 06 08" src="https://user-images.githubusercontent.com/31368406/29741182-5cb492e8-8a5f-11e7-9ffa-1793cf9ed0c8.png">
(Look at movement it stops at jetpack)

Anyways i hope you can find how to solve and thanks

**Comment by Marco-MC** [comment]
You can scroll in the clickgui. ^^

**Comment by Fuzzy121** [comment]
Ok thanks a lot

**Comment by Fuzzy121** [comment]
Btw is there a way to enlarge the thing so i dont hafto scroll or no?

**Comment by maxhd0** [comment]
Ja aber wenn man die Speed settings öffnet geht es in den Boden. (Auch wenn man hoch scrollt)

**Comment by Fuzzy121** [comment]
Ok
