### ISSUE TITLE
LiquidChat führt zu Absturz des Spiels bei Linux-Systemen

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1244]
Das aktivieren des LiquidChats bringt das Spiel instant zum Absturz mit dem folgenden (gekürzten) Crash-Report: 

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 26.08.17 15:08
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at byCCBlueX.Zz. (Unknown Source)
	at byCCBlueX.YZ. (Unknown Source)
	at byCCBlueX.nh. (Unknown Source)
	at byCCBlueX.nh. (Unknown Source)
	at byCCBlueX.JR.　(Unknown Source)
	at byCCBlueX.mD. (Unknown Source)
	at byCCBlueX.nf.func_73864_a(Unknown Source)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at byCCBlueX.Zz. (Unknown Source)
	at byCCBlueX.YZ. (Unknown Source)
	at byCCBlueX.nh. (Unknown Source)
	at byCCBlueX.nh. (Unknown Source)
	at byCCBlueX.JR.　(Unknown Source)
	at byCCBlueX.mD. (Unknown Source)
	at byCCBlueX.nf.func_73864_a(Unknown Source)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)

-- Affected screen --
Details:
	Screen name: byCCBlueX.nf

-- Affected level --
Details:
	Level name: MpServer
	All players: 18 total; [...]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -110,00,4,00,157,00 - World: (-110,4,157), Chunk: (at 2,0,13 in -7,9; contains blocks -112,0,144 to -97,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 701583583 game time, 1872000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 38 total; [...]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.12-SNAPSHOT:bd5a7e5:1260) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 4.4.0-92-generic
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E8400 @ 3.00GHz
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 226534576 bytes (216 MB) / 490209280 bytes (467 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 Optifine OptiFine_1.8.9_HD_U_H8 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0 NVIDIA 340.102' Renderer: 'GeForce GT 240/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1902-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GT 240/PCIe/SSE2 GL version 3.3.0 NVIDIA 340.102, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E8400 @ 3.00GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_H8
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0 NVIDIA 340.102
	OpenGlRenderer: GeForce GT 240/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by maxhd0** [comment]
1 zu 0 für Windows XD

**Comment by henrydatei** [comment]
aber Linux hat bei diesen System-Stats echt die bessere Performance

**Comment by maxhd0** [comment]
hatte mit Windows noch nie Probleme. Wenn man sich mit Windows gut auskennt (auch mit regedit) Dann Ist Windows mit abstand das beste Betriebsystem. Wenn man sich nicht/wenig auskennst ist windows auch besser, da es benutzerfreundlich ist. Linux ist nur für läute, die sich mittelgut auskennen.

**Comment by maxhd0** [comment]
Zudem funktionieren viele Programme nicht auf linux.

**Comment by henrydatei** [comment]
Nunja mit regedit kann man bei Windows jede Menge machen, genau wie bei Linux. Als für XP damals der Support eingestellt wurde, hab ich mich nach Alternativen umgesehen und bin bei Linux hängen geblieben, weil ich keine Lust hatte Geld für ein neues OS zu bezahlen bzw. das Ganze zu cracken. Und bezüglich Programmen, die auf Linux nicht funktionieren, scheinst du dich nicht wirklich informiert zu haben. Ich bekomme alles, was ich brauche, auf meinem PC zum laufen. Zudem werde ich nie Probleme mit allen Arten von Malware haben, da sich niemand die Mühe macht für Linux Schadware zu schreiben. Bei Windows bräuchte ich da wieder einen Virenscanner, der meinen kompletten Rechner beschäftigt.

**Comment by maxhd0** [comment]
120€ sind doch nicht viel. 1 ist Xp immernoch super. Zudem ist Xp garnicht richtig abgestellt. ^^ Wenn ich will kann ich die neusten updates für xp haben. Das gilt noch bis 2019. Wait ich gebe dir mal ein video.
https://www.youtube.com/watch?v=BVDkorPtWms hier

**Comment by maxhd0** [comment]
zudem währe die alternative windows 7. Ich finde es super. Ist im gegensatz zu win 10 noch nie abgekackt und ich habe windows 7  5 jahre

**Comment by maxhd0** [comment]
Ein bluescreen hatte ich ich mit windows 7 nie. Das merkt man daran das ich nicht weiss wie der überhaupt bei Win7 aussieht XD. Ich kenne ihn nur bei Windows 95,2000, xp ,Vista und 10.

**Comment by henrydatei** [comment]
Das man XP noch eine Weile weiterverwenden kann, hab ich erst mehrer Jahre nach meinem Umzug auf Linux erfahren und ich habe keine Lust mich mit dem ekligen Update-Prozess bei Windows zu beschäftigen. Bei Linux verläuft das vollautomatisch, ohne dass ich davon etwas hinsichtlich Geschwindigkeit und Meldungen, die mir erzählen wollen, dass ich meinen PC mal neustarten soll, merke. Auch die nervigen Fenster a la "Update 1 von 50 wird installiert, bitte warten" beim Herunterfahren und beim Hochfahren "Windows wird konfiguriert..." sind Geschichte. 

Zudem sind 120€ ziemlich viel, wenn man Student ist und für sein Geld arbeiten muss. Die Entscheidung "Geld für etwas ausgeben, was es im Internet kostenlos gibt" vs. "sehr viele Tiefkühl-Pizzen und Döner für 120€" ist dann ziemlich leicht zu fällen.

**Comment by maxhd0** [comment]
em. 1 geht das updaten auch in windows vollautomatisch und 2. Linux macht das das auch alles beim herunterfahren nur mit dem unterschied das da nichts steht. Und das beim hochfahren kann man bei Windows abschalten. Dann dauert es aber länger bis windows komplett oben ist. Denn das macht linux. Beim hochfahren macht er es im hintergrund. Nachteil. Die ersten 5 minuten ist der PC langsamer. Und es besteht eine Fehlerquote von ca. 0,2% niedrig aber es gibt sie. Dadurch muss man linux noch mal neustarten. Diesen Fall hatte ich jetzt aber noch nie. Ich glaub sie ist noch tiefer. Im internet stand es 0.2.

**Comment by maxhd0** [comment]
Aber lieber Linux zu nehmen nur wegen updates die Scheimbar bei linux leicht besser währen? rly. Ich will lieber ein Betriebsystem wo ich praktisch alle programme verwenden kann, oder wo das Bios oder Uefi nicht spinnen kann. (bei linux kann es manchmal sehr spinnen. (nicht indem was nicht geht. Sondern indem das Bios oder uefi manchmal was falsches startet oder nicht startet. z.b der Audiotreiber etc. Dies passiert bei Windows nicht.

**Comment by henrydatei** [comment]
Hast du Linux überhaupt schon mal selber getestet? Also damit meine ich im Normalbetrieb, nicht für 5 Minuten in einer VM. Ich habe XP, 7 (wegen Uni), 10 (auch wegen Uni) und Linux mehrere Jahre benutzt und bin zu dem Ergebnis gekommen, dass ich mit Linux am Besten klarkomme. Die Gründe dafür hab ich dir oben alle aufgezählt (und nein, es sind nicht nur die besseren Updates). 

Da du mit Fehlerwahrscheinlichkeiten um dich wirft, vermute ich, dass du dich in irgendwelchen Foren belesen hast, wo Leute mit root-Rechten ihren ganzen PC zerschossen haben. Unter Windows ist das deutschlich schwieriger, da sich Windows mit Systemrechten vor dummen Admins zu schützen versucht.

**Comment by maxhd0** [comment]
Ja habe ich. 
 "dass ich mit Linux am Besten klarkomme." Das ist der Grund warum du Linux benutzt und nicht weil es besser sei.

Zudem. Ich habe zwar teils auf foren mich erkundigt aber ohne Root rechte. 
Alles was ich hier geschrieben habe habe ich selbst herausgefunden und selbst (oder ein freund hat es manchmal ) getestet.

**Comment by henrydatei** [comment]
"dass ich mit Linux am Besten klarkomme." Mit diesem Satz meine ich, dass es AUS MEINER SICHT das bessere OS für MICH ist. Das mag aus deiner Sicht nicht stimmen, aber ich bestimme immer noch selber, was für ein OS ich benutze. 

Wenn du angeblich alles selber getestet hast, wie kannst du dann 0,2% als Wahrscheinlichkeit für etwas angeben? Ich bezweifle, dass du 500 Versuche gemacht hast und 1 dabei schief ging. 

In den letzten Jahren hatte ich noch keine der von dir beschriebenen Probleme von nicht funktionierendem BIOS/UEFI. Und solange ich diese Probleme nicht habe, sehe ich keine Notwendigkeit 1 Tag zu verschwenden und Windows zu installieren und einzurichten.

PS: Bitte achte auf deine Interpunktion, Kommatasetzung und Orthographie. Es ist manchmal echt schwer deine "Sätze" grammatikalisch richtig zu verstehen.

**Comment by maxhd0** [comment]
._.

**Comment by maxhd0** [comment]
Egal. behalte dein Linux. Ich würde es mir jedenfalls nicht Instalieren.

PS: "dass ich mit Linux am Besten klarkomme."  mit dem meine icch das es dir Gefällt und du es desshalb benutzen wirst.

**Comment by superblaubeere27** [comment]
@maxhd0 Schon dein alter Account hat gezeigt, dass du mit Englisch scheinbar in der 6. Klasse bist, ich habe auch Linux, weil es bessere perormance hat und wegen apt und apt-get

**Comment by superblaubeere27** [comment]
Aber das gleiche Problem hab ich auch

**Comment by superblaubeere27** [comment]
Moment @maxhd0 DU HAST WINDOWS XP?
:man_facepalming:

**Comment by superblaubeere27** [comment]
Ohhh updates gehen garnicht automatisch mann muss eine sooo lange Zeile ins Terminal eingeben `sudo apt update && sudo apt upgrade`
Und das wenn man nur Debian hat ohne Ubuntu oder Kubuntu

**Comment by superblaubeere27** [comment]
@henrydatei Ja, aber @maxhd0 Ist ein Klugscheisser aus der 6.-7. Klasse mit WINDOWS XP den kann man nicht ernst nehmen

**Comment by henrydatei** [comment]
@superblaubeere27 ich habe es immerhin mit Argumenten versucht. Aber du siehst ja, man kann gegenüber Fakten auch sehr intolerant sein.

**Comment by superblaubeere27** [comment]
Ja das Stimmt, ich Tagge das mal als Bug, ich weiss nicht, ob es in LiquidBounce gefixt wird.
Und welche Distribution hast du? (Von Linux)

**Comment by henrydatei** [comment]
Ubuntu 16.04 LTS

**Comment by Marco-MC** [comment]
Fixed.
