### ISSUE TITLE
AAC PortHop Speed

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1245]

**Comment by Marco-MC** [comment]
Added.
10% - 12% faster than legit

**Comment by Marco-MC** [comment]
https://gyazo.com/b8224409da1298a798468e5f82c7c493

**Comment by Crax9999** [comment]
Was? LOL diese issue habe ich mal vor zwei Monaten geschrieben XD

**Comment by maxhd0** [comment]
Marco ist halt ein skidder ^^

**Comment by maxhd0** [comment]
Er skiddet issues XD
