### ISSUE TITLE
New AAC Icespeed

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1247]
der alte wurde gefixt.

**Comment by Marco-MC** [comment]
Ich habe eben mal ausgetestet was jetzt maximal geht... Maximal geht nur legitMotionXZ * 1.04D...
Das ist langsamer als würdest du auf Eis springen...
Einen IceSpeed der schneller ist als auf Eis zu bhopen der nur auf dem Boden ist derzeit nicht wirklich möglich ist.

**Comment by maxhd0** [comment]
medox hat doch einen icebhop. Frage ihn mal. (wenn du willst)

**Comment by maxhd0** [comment]
Marco. Es kann auch ruhig ein Bhop sein.
