### ISSUE TITLE
Spammer RandomDelay between two values

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1248]
Random Delay wie bei cheststealer(zwischen zwei zahlen z.b 2000-4000).

**Comment by maxhd0** [comment]
gibts das nicht schon lul .-.

**Comment by Bircko** [comment]
Nein nur bei Cheststealer und InvCleaner glaub ich, bei Spammer jedenfalls nicht.

**Comment by maxhd0** [comment]
lol Stand da nicht gestern Cheststeeler. loooooooooooool. Ich wasche mal meine Augen. sry

_mit Persil ^^_

**Comment by Marco-MC** [comment]
Added
