### ISSUE TITLE
AltManager Search

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1249]
Das man nach Alts im Altmanager suchen kann(Name, Email oder pw). So etwas ähnliches wie beim Browser mit Strg+F.

**Comment by WistarWolf** [comment]
+1

**Comment by superblaubeere27** [comment]
Wer brauch das dann?

**Comment by scorpion3013** [comment]
Leute wie ich die ihre gesamte altliste drin haben.

**Comment by maxhd0** [comment]
und ich auch

**Comment by maxhd0** [comment]
superblaubeere27 kannst du mal was anderes schreiben als: "Wer braucht das schon" oder "Unnötig" 
Jede Issue hier hat einen Sinn.

**Comment by SenkJu** [comment]
Ne, für sowas ist kein Platz im GUI.

**Comment by scorpion3013** [comment]
http://i.imgur.com/Vod8SAR.png ?

**Comment by maxhd0** [comment]
"Ne, für sowas ist kein Platz im GUI." Aber er sagte einen akzeptabelen Grund.
