### ISSUE TITLE
Schneller AAC Speed

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1250]
https://www.youtube.com/watch?v=bqXVky5m5As

**Comment by maxhd0** [comment]
https://vgy.me/HY9PPw.png

**Comment by Bircko** [comment]
da hätte ich lieber denn von skush weil der hier flaggt wahrscheinlich

**Comment by maxhd0** [comment]
ne er flagt nicht.

**Comment by maxhd0** [comment]
bzw. er autobannt nicht.
