### ISSUE TITLE
join bug

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1251]
http://www.bilder-upload.eu/show.php?file=cf7575-1504017746.png

Manchmal bleibt man hier hängen. (wenn man es nicht beheben kann wünsche ich mir aber einen button, dass man wieder ins Hauptmenü kommt. Denn sonnst muss ich mc immer neustarten.)

**Comment by SenkJu** [comment]
Das liegt entweder am Server oder deimem Internet.

**Comment by maxhd0** [comment]
poke.sexy

**Comment by Marco-MC** [comment]
Das ist ein normaler Minecraft (Forge) Bug...
