### ISSUE TITLE
Anti Crash Modul

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1252]
Es gibt manche Pluggins die mit einem Befehl Minecraft zum Crashen bringen. (Z.b AAC hatte oder hat immernoch ein crash command. Und wenn das Modul an ist soll MC nicht mehr crashen sondern etwa nur wieder ins Hauptmenü gehen oder sogar auf dem Server bleiben. (Minecraft soll einfach nicht crashen)

(Das Modul soll man nicht in der ClickGui an machen können sondern im Multiplayer. (Da wo man auch das Forgebypass einschalten kann.))

**Comment by Marco-MC** [comment]
... witzig... dir ist schon klar das der Server mit so gut wie jeden Packet crashen kann... vergiss es...
