### ISSUE TITLE
BookFlood Server Crasher

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1258]
A Hacked Client has a "Server Crash" function implemented, which spams "CUSTOM_PAYLOAD"-Packets (using minecraft's book channels) with max size. The NCP packet frequency check doesn't block it, because it doesn't spam that much packets, but really big ones. This makes the server lag really hard and finally crash.

**Comment by Bircko** [comment]
Gibts dazu auch ein video oder wenigstens denn namen des clients

**Comment by maxhd0** [comment]
Da wird es doch gut erklärt. Woher soll ich ein video haben? Mein PC ist scheisse. Und Client? Meiner UnitedS. Das hilft dir aber nicht weiter.

**Comment by Marco-MC** [comment]
Added

**Comment by Tcm9** [comment]
Hi 2Hard

**Comment by Teals53** [comment]
lol why i take notify for this comment rn wtf
