### ISSUE TITLE
.friend bug

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1262]
Wenn man ".friend add  name" macht bugt es sehr rum (durch das zweite Leerzeichen)
![v2bfzcj](https://user-images.githubusercontent.com/27446646/29873582-0f0d6974-8d94-11e7-9cf9-99754705100b.png)

**Comment by maxhd0** [comment]
lul. Ok

**Comment by WistarWolf** [comment]
Das ist kein Bug. Das ist ein Key der LiquidBounce, NSA und GommeHDnet Server.

**Comment by maxhd0** [comment]
stimmt als ich es bei gommeh.net in  den Chat schrieb bekam ich Op. ez forceop

**Comment by Marco-MC** [comment]
Okay... habe jetzt einfach gemacht, dass er rummeckert wenn du keinen Namen angiebst.
