### ISSUE TITLE
A module to show barriers

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1263]

**Comment by SenkJu** [comment]
blockesp

**Comment by WistarWolf** [comment]
Wenn man aber z.b. BedWars spielt, in BlockESP bed eingestellt hat und nicht jede minuten von barrieren zu betten wechseln will? ._.

**Comment by SenkJu** [comment]
wo muss man in bedwars barriers sehen können?

**Comment by WistarWolf** [comment]
Mir ist grad nix anderes eingefallen. Ich meine halt wenn man in blockesp schon ein block eingestellt hat, aber trozdem barrieren sehen will.
