### ISSUE TITLE
Bockesp more IDs

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1264]
Man soll mehre Blöcke auswählen können

Am Besten mit der eigenen GUI wo alle Blöcke drin sind die ausgewählt sind. Falls nicht kann man das auch mit .blockesp add/remove <ID>
Wenn man alle Blöcke gelöscht haben will .blockesp delete
Und wenn man alle gelöscht haben will ausser 1 kann man .blockesp set <ID> machen.

_Oder ihr macht ne eigene GUI wo man das ganz schnell und übersichtlich einstellen kann._

**Comment by maxhd0** [comment]
Man soll es zudem nicht nur bei Blockesp machen können. Sondern auch bei Ghosthand und Fucker

**Comment by maxhd0** [comment]
Hm. Schade. Hätte jeder gebraucht und auch benutzt. Ist aber zu schwer für euch.

**Comment by Fleroxh** [comment]
Ich hätte es nicht gebraucht, aber danke das du alle in eine Schublade drückst.

**Comment by maxhd0** [comment]
hem. nur in eine? Ich habe für euch einen ganzen schrank gekauft.

**Comment by Fleroxh** [comment]
Du weißt auf was ich heraus wollte.
