### ISSUE TITLE
Blockesp + Barriers oder setting bei Truesight.

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1265]
Wenn Blockesp auf Barriers gestellt ist soll dieses Kreuz kommen und keine Box

http://www.bilder-upload.eu/show.php?file=7fc3e9-1504130598.png

Und wenn ihr es nicht in Blockesp macht macht bitte ein setting bei Truesight. 
(Für manche Spielmodis oder Bauevents bräute man diese kreuze.)

_(Das mit Truesight währe mir lieber, da ich Blockesp für was anderes nutze)_

**Comment by WistarWolf** [comment]
+1

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1923
