### ISSUE TITLE
NoWeb AAC verbesserung

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1266]
Wenn ich Sneake soll der NoWeb nach unten gehen.

Der AAC NoWeb geht nicht nach unten. Das ist auch gut so. Aber wenn ich mal durch Web durch muss(y), dann muss ich immer NoWeb ausschalten damit ich durchkomme. Den Rewimode zu nehmen ist nicht viel besser da es ja gut ist, dass ich nicht nach unten gehe. z.b Bedwars. Wenn ich aber wegen irgend eines Grundes plötzlich nach unten muss bin ich am Arsch. (ist mir passiert. Darum schreibe ich das auch grade)

Bitte hinzufügen, dass wenn du Sneakst er nach unten geht und (gegebenenfalls schneller macht als Legit).

**Comment by Marco-MC** [comment]
Added.
