### ISSUE TITLE
Red ESP

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1267]
Diesen roten ESP bei Fly, KillAura usw entfernen bzw (de-)aktivierbar machen.

**Comment by maxhd0** [comment]
achso das. Xave hatte doch auch ein setting dafür. Es währe gut wenn man es in so Client settings machen könnte.

**Comment by WistarWolf** [comment]
Jo. Aber so wie ich Marco/Senk Ju kenne, werden sie das wahrscheinlich nicht einbauen.
