### ISSUE TITLE
Scaffold NoHit Setting

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1268]
Wenn an schlägt die Killaura, aimbot etc. Nicht mehr wenn du Scaffoldest.

Autobannt auf gomme wenn du Scaffoldest und gleichzeitig Schlägst. Und auf anderen servern kannst du auch nicht beides machen. (Bauen und Schlagen)
(Ist mir mindestens aufgefallen.)

**Comment by WistarWolf** [comment]
Mir ist auch aufgefallen das auch auf anderen Servern der ScaffoldWalk einfach aufhört zu bauen bzw die KillAura nicht hittet.

**Comment by maxhd0** [comment]
ja. Und wenn NoHit an ist konzentriert sich der Client nur aufs bauen.
