### ISSUE TITLE
Chaststealer setting NoDuplicate

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1269]
Wenn an nimmt Chaststealer nichts mehr, wenn du es schon hast. Beispiel: Wenn du ein Holzschwert im Inv hast und ne Truhe öffnest nimmt er nicht das Holzsschwert raus, da du es ja schon hast. (Dies soll er nur bei Items machen die du nur 1 mal im Inventar haben kannst wie Schwerter oder Bögen. Äpfel, Faden etc sollen  weiterhin rausgenommen werden.

**Comment by WistarWolf** [comment]
+1

**Comment by maxhd0** [comment]
Tränke soll er auch rausnehmen auch wenn du schon 1en hast. Tränke sind immer nützlich.

**Comment by Marco-MC** [comment]
Enable InventoryCleaner.

**Comment by maxhd0** [comment]
für gewisse Spielmodis kann man Invleaner nicht benutzen.( z.b Endergames, Marioparty,oder viele mineplax games wie witchers. Da er dann die falschen sachen rauswirft, die ich noch brauche. Und da kann ich invcleaner nicht verwenden. Und da währe no duplikat viel viel viel besser und man könnte es überall verwenden.
