### ISSUE TITLE
Autoarmor Verbesserung

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1271]
Wenn das Inventar voll ist soll Autoarmor die Rüstung die du grade an hast in den Craftingslot legen damit Autoarmor dann die Rüstung anziehen kann.

Zudem soll es ein Clean setting geben. Wenn an droppt er die Rüstung die du an hast und zieht die bessere an um Platz zu sparen.

**Comment by SenkJu** [comment]
Das tut InvCleaner.
