### ISSUE TITLE
Client settings GUI

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1272]
Soll im Pausemenü zu finden sein. (Oder ein Settings knopf im ClickGUI unten rechts/links (so wie  in Skash: http://www.bilder-upload.eu/show.php?file=7713bb-1504134929.png ))

Wenn du draufdrückst sollen folgende settings einstellbar sein:

- Clickgui settings (alle vorhandenen die in b26,2 drin sind wie Scale etc.)

- RedESP #1267

- Ghostmode (wenns drin ist)

- Liquidbounce Style settings (bisher nur null und  Liquidbounce)

- Blockesp/Ghosthand/Fucker gui #1264 (falls ihr es einfügt) (wenn man mehrere Blöcke auswählt währe es mit ner GUi am besten wo man ne gute Übersicht hat, welche Blöcke man hinzugefügt hat. Man kann sie gegebenfallst dann auch wieder entfernen.

- OtherSwingAnimation

- Liquidchat an/aus (finde es als Client settings besser als ein Misc modul.

- Gegebenenfalls mehr settings wenn euch noch welche einfallen. 

Der Client benötigt so eine Gui wo man Clientsettings einstellen kann.

**Comment by WistarWolf** [comment]
Joa wäre schon cool.

**Comment by maxhd0** [comment]
Währe dann Aufgeräumter. Und es würde besser passen. Ghostmode, HelpESP oder Liquidchat zum Beispiel. Liquidchat passt besser als ein settings als ein Modul.

**Comment by WistarWolf** [comment]
Jo das stimmt. Aber was soll der HelpESP bringen?

**Comment by Bircko** [comment]
ja richtige coole idee

**Comment by maxhd0** [comment]
Das ist der redesp. Dieses rote bei der killaura soll doch helfen. Darum habe ich es so genannt. Kann es aber auch umbennenen. (Es ist jedenfals der redesp)

**Comment by WistarWolf** [comment]
achso

**Comment by maxhd0** [comment]
ok. Dann nicht. Aber wie will Marco dann die settings hinzufügen. Er könnte alles als Module machen. Aber der Client hat ja jetzt schon so viele Module, dass man schon den überblick verliert.
