### ISSUE TITLE
Auto Reconnect / Reconnect Button

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1273]
Der Auto Reconnect Button und der Reconnect Button soll getrennt angezeigt werde, und der Auto Reconnect Button soll (de-)aktivierbar sein. Da es ziemlich nervt wenn man von der Ban Nachricht irgendwas abschreiben will (Ban Grund/Ban Nachricht oder so) aber man nicht immer dafür nen Screen machen will, und man jedes mal neu Connectet wird.

**Comment by maxhd0** [comment]
Diese issue gibts schon

**Comment by maxhd0** [comment]
Hm scheimbar foch nicht.

**Comment by SenkJu** [comment]
#1172
