### ISSUE TITLE
Sneak mode: NoMove

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1274]
Du sneakst immer automatisch wenn du dich nicht bewegst. (Er soll auch sneaken wenn du im Inventar bist und dich nicht bewegst.)

 In vielen Spielmodis kann das sehr helfen. Und es geht auf jedem Anticheat.

**Comment by SenkJu** [comment]
Quatsch mit Soße

**Comment by maxhd0** [comment]
schade. Hätte mir gefallen. Ich hätte es in jeder runde TTT an gemacht.
