### ISSUE TITLE
Ghost Mode

### ISSUE THREAD

**Issue by Kontorted** [CCBlueX/LiquidBounce1.8-Issues#1277]
When enabled, it will hide all the GUI settings and make your game look like vanilla minecraft. You will not be able to open the clickgui until you disable Ghost through a bind, but you can interact with your binds.

**Comment by maxhd0** [comment]
Duplikat: #1147

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1147
