### ISSUE TITLE
Rainbow "Speed"

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1278]
Ich finde, das ist kein Rainbow Speed, sondern es verkleinert nur die Rainbow Scale.... Entweder sollte Rainbow Speed zu Rainbow Scale umbenannt werden, oder ein gescheiter Rainbow Speed soll gemacht werden.

**Comment by maxhd0** [comment]
Das ist ansichtssache.

**Comment by Bircko** [comment]
Nein Ambien z.B. hat einen richtigen Rainbowspeed.

**Comment by WistarWolf** [comment]
Ja. Aber in LiquidBounce verkleinert der Rainbow Speed nur die Rainbow Scale.

**Comment by maxhd0** [comment]
Nehmt wie ihr es wollt. Das jetztige finde ich schön. Aber man kann wen man es will ruhig erweitern. Sollange das jetztige man später auch einstellen kann.

**Comment by WistarWolf** [comment]
man kann ja eine rainbow scale option (jetztige) und eine gescheite rainbow speed option einfügen

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1073
