### ISSUE TITLE
AutoSign

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1281]
Wenn ich [ .Autosign hallo ] mache und dann das Schild setzte soll keine Gui kommen sondern das Schild soll direkt gesetzt werden mit dem was ich bei .autosign geschrieben habe. (in diesem Fall hallo)

**Comment by SenkJu** [comment]
ne

**Comment by maxhd0** [comment]
Wenn man gewisse sachen auf servern schnell schreiben will kann es sehr viel Zeit sparen.
