### ISSUE TITLE
MC Server Version Anzeige

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1282]
Neben den Servern soll angezeigt werden welche Version, und ob der Server Bungeecord, Spigot, Bukkit etc ist. Wieso das? Falls der Port Scanner und der Server Finder eingebaut wird, will man glaube ich nicht auf jeden einzelnen Server joinen und /bungee, /spigot etc eingeben. Das ist ziemlich nervig. Deshalb wäre es gut wenn diese Infos angezeigt werden bzw es eine Option im Multiplayer Menu gibt, mit der man diese Anzeige ein und aus schalten kann.

**Comment by maxhd0** [comment]
+1

**Comment by superblaubeere27** [comment]
Warum?
