### ISSUE TITLE
Serverlist Cleaner (Like Wurst or IzeMod)

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1283]

**Comment by maxhd0** [comment]
HEILIGE SCHEISSE JESUS GOTTES MUTTER MARIA HEILIGE DES MINECRAFT SPIELS BITTE NICHT!!!

**Comment by WistarWolf** [comment]
xd

**Comment by WistarWolf** [comment]
Zusatz:
Die Server die vom Server Finder gefunden werden, bekommen einen spezielen namen. Die Server die man einzelnd/schon davor eingetragen hat, haben halt nen anderen Namen, die man denen halt gegeben hat. Im Serverlist Cleaner gibt es dann halt ne funktion, mit der man entweder alle Server, oder nur Server mit diesem spezielen Namen löschen will.

**Comment by maxhd0** [comment]
fügt ein Filter zu Serverfinder hinzu wo das einstellt aber bitte nicht wenn es schon in der Serverliste drin ist. Habe ca 180 server. und wenn ich alle von Grief me#1 wieder in ihren normalen namen machen muss fuckt das haaart ab

PS: Vielen dank für die Aufmerksamkeit.

**Comment by WistarWolf** [comment]
Jo. Marco baut das dann hoffentlich ein und er findet dafür auch bestimmt eine gute Lösung xd

**Comment by maxhd0** [comment]
MaxHD0 closed this 12 minutes ago
