### ISSUE TITLE
Teleporthand

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1286]
Du kannst über +100 Blocke Bauen und Abbauen (Clientside und Serverside) 
Bauen macht er über die gleiche Methode wie Superhit und Abbauen macht er indem er hinfliegt kurz abbaut wieder zurückfliegt (wenn Teleporthand das mit Abortbreaking macht baut er über 100 Blöcke z.b 1 Kiste innerhalb 10 sek ab. (soll vorallem für Vannila dienen)
Währe fürs Griefing super.

**Comment by WistarWolf** [comment]
hm. Joa und wäre auch lustig fürs trollen. +1

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1287
