### ISSUE TITLE
Teleport Interact

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1287]
Schlägt Spieler von +100 Blöcken 
(Es dient super fürs Trolling auf Vannila servern)

**Comment by maxhd0** [comment]
Damit soll man auch von +100 Blöcken Bauen und Abbauen können.

**Comment by maxhd0** [comment]
Funktioniert auf der neusten AAC version (man muss aber springen) (AAC 3.3.2)

**Comment by maxhd0** [comment]
Ich habe für euch Superhit gecodet.

**Comment by maxhd0** [comment]
me.UnitedS.client.mod.mods.combat;

importiere java.util.ArrayList;import java.util.ArrayList;
importiere mich.UnitedS.client.events.EventPreMotion;import me.UnitedS.client.events.EventPreMotion;
importiere mich.UnitedS.client.mod.Mod;import me.UnitedS.client.mod.Mod;
importiere mich.UnitedS.client.mod.Mod.Category;import me.UnitedS.client.mod.Mod.Category;
importiere mich.UnitedS.client.util.Colors;import me.UnitedS.client.util.Colors;
importiere mich.UnitedS.client.util.CombatUtil;import me.UnitedS.client.util.CombatUtil;
importiere mich.UnitedS.client.value.Value;import me.UnitedS.client.value.Value;
import net.minecraft.client.Minecraft;import net.minecraft.client.Minecraft;
import net.minecraft.client.entity.EntityPlayerSP;import net.minecraft.client.entity.EntityPlayerSP;
importieren net.minecraft.client.network.NetHandlerPlayClient;import net.minecraft.client.network.NetHandlerPlayClient;
import net.minecraft.entity.EntityLivingBase;import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.network.play.client.C02PacketUseEntity;import net.minecraft.network.play.client.C02PacketUseEntity;
import net.minecraft.network.play.client.C02PacketUseEntity.Action;import net.minecraft.network.play.client.C02PacketUseEntity.Action;
import net.minecraft.network.play.client.C03PacketPlayer.C04PacketPlayerPosition;import net.minecraft.network.play.client.C03PacketPlayer.C04PacketPlayerPosition;
import net.minecraft.util.MovingObjectPosition;import net.minecraft.util.MovingObjectPosition;
import net.minecraft.util.Vec3;import net.minecraft.util.Vec3;
import org.lwjgl.util.vector.Vector3f;import org.lwjgl.util.vector.Vector3f;

Öffentliche Klasse SuperHit erweitert Modpublic class SuperHit extends Mod
{{
  private EntityLivingBase Entity;private EntityLivingBase entity;
  privater Wert <String> modes = neuer Wert ("SuperHit", "TargetMode", 0);private Value<String> modes = new Value("SuperHit", "TargetMode", 0);
  privater Boolean-Hit;private boolean hit;
  
  public SuperHit () {public SuperHit() {
    super ("SuperHit", Mod.Category.COMBAT, DARKREDc);super("SuperHit", Mod.Category.COMBAT, DARKREDc);
    modes.mode.add ("FOV");.mode.add("FOV");
    modes.mode.add ("Entfernung");.mode.add("Distance");
  }}
  
  @ com.darkmagician6.eventapi.EventTarget@com.darkmagician6.eventapi.EventTarget
  public void onPreMotion (EventPreMotion-Ereignis) {public void onPreMotion(EventPreMotion event) {
    if (! hit) {if (!hit) {
      entity = null;= null;
      Wenn ((mc.objectMouseOver! = null) && (mc.objectMouseOver.entityHit! = null) && ((mc.objectMouseOver.entityHit instanceof EntityPlayer))) {if ((mc.objectMouseOver != null) && (mc.objectMouseOver.entityHit != null) && ((mc.objectMouseOver.entityHit instanceof EntityPlayer))) {
        entity = ((EntityPlayer) mc.objectMouseOver.entityHit);= ((EntityPlayer)mc.objectMouseOver.entityHit);
      } sonst} else
        anvisieren();();
    }}
    if ((entity! = null) && (org.lwjgl.input.Mouse.isButtonDown (0))) {if ((entity != null) && (org.lwjgl.input.Mouse.isButtonDown(0))) {
      if (! hit) {if (!hit) {
        hit = true;= true;
        Rückkehr;return;
      }}
      if ((hit) && if ((hit) && 
        (mc.thePlayer.onGround)) {(mc.thePlayer.onGround)) {
        mc.thePlayer.jump ();.thePlayer.jump();
      }}
      if (mc.thePlayer.fallDistance> 0.0F) {if (mc.thePlayer.fallDistance > 0.0F) {
        yaw = CombatUtil.getRotations (Entität) [0];= CombatUtil.getRotations(entity)[0];
        pitch = CombatUtil.getRotations (Entity) [1];= CombatUtil.getRotations(entity)[1];
        if (mc.thePlayer.getDistanceToEntity (Entity)> 3.5D) {if (mc.thePlayer.getDistanceToEntity(entity) > 3.5D) {
          Vec3 vec = mc.thePlayer.getVectorForRotation (0.0F, mc.thePlayer.rotationYaw);Vec3 vec = mc.thePlayer.getVectorForRotation(0.0F, mc.thePlayer.rotationYaw);
          double x = mc.thePlayer.posX + xCoord * (mc.thePlayer.getDistanceToEntity (Entity) - 1.0F);double x = mc.thePlayer.posX + xCoord * (mc.thePlayer.getDistanceToEntity(entity) - 1.0F);
          double z = mc.thePlayer.posZ + zCoord * (mc.thePlayer.getDistanceToEntity (Entity) - 1.0F);double z = mc.thePlayer.posZ + zCoord * (mc.thePlayer.getDistanceToEntity(entity) - 1.0F);
          double y = entity.getPosition () getY () + 0.25D;double y = entity.getPosition().getY() + 0.25D;
          
          ArrayList <Vector3f> Positionen = Me.UnitedS.client.util.PlayerUtil.vanillaTeleportPositionen (x, y + 1.0D, z, 4.0D);ArrayList<Vector3f> positions = me.UnitedS.client.util.PlayerUtil.vanillaTeleportPositions(x, y + 1.0D, z, 4.0D);
          für (int j = 0; j <1; j ++) {for (int j = 0; j < 1; j++) {
            für (int i = 0; i <position.size (); i ++) {for (int i = 0; i < positions.size(); i++) {
              Vector3f pos = (Vector3f) position.get (i);Vector3f pos = (Vector3f)positions.get(i);
              Vector3f oldPos = i == 0? Neuer Vector3f ((float) mc.thePlayer.posX, (float) mc.thePlayer.posY, (float) mc.thePlayer.posZ): (Vector3f) position.get (i - 1);Vector3f oldPos = i == 0 ? new Vector3f((float)mc.thePlayer.posX, (float)mc.thePlayer.posY, (float)mc.thePlayer.posZ) : (Vector3f)positions.get(i - 1);
              mc.thePlayer.sendQueue.addToSendQueue (neue C03PacketPlayer.C04PacketPlayerPosition (pos.getX (), pos.getY (), pos.getZ (), false));.thePlayer.sendQueue.addToSendQueue(new C03PacketPlayer.C04PacketPlayerPosition(pos.getX(), pos.getY(), pos.getZ(), false));
            }}
          }}
          mc.thePlayer.onCriticalHit (Entität);.thePlayer.onCriticalHit(entity);
          mc.thePlayer.sendQueue.addToSendQueue (neue C02PacketUseEntity (Entity, C02PacketUseEntity.Action.ATTACK));.thePlayer.sendQueue.addToSendQueue(new C02PacketUseEntity(entity, C02PacketUseEntity.Action.ATTACK));
          hit = false;= false;
        }}
      }}
    }}
  }}
  
  private void setTarget () {private void setTarget() {
    doppelt am nächsten = 2.147483647E9D;double closest = 2.147483647E9D;
    EntityLivingBase target = null;EntityLivingBase target = null;
    für (Objekt o: mc.theWorld.loadedEntityList) {for (Object o : mc.theWorld.loadedEntityList) {
      if ((o Instanz von EntityLivingBase)) {if ((o instanceof EntityLivingBase)) {
        EntityLivingBase e = (EntityLivingBase) o;EntityLivingBase e = (EntityLivingBase)o;
        if (isValidTarget (e)) {if (isValidTarget(e)) {
          if (modes.isCurrentMode ("FOV")) {if (modes.isCurrentMode("FOV")) {
            float yaw = CombatUtil.getRotations (e) [0];float yaw = CombatUtil.getRotations(e)[0];
            float yawDiff = CombatUtil.getYawDifference (CombatUtil.getNewAngle (mc.thePlayer.rotationYaw), CombatUtil.getNewAngle (Gier));float yawDiff = CombatUtil.getYawDifference(CombatUtil.getNewAngle(mc.thePlayer.rotationYaw), CombatUtil.getNewAngle(yaw));
            wenn (yawDiff <am nächsten) {if (yawDiff < closest) {
              am nächsten = yawDiff;= yawDiff;
              Ziel = e;= e;
            }}
          } sonst {} else {
            double dist = mc.thePlayer.getDistanceToEntity (e);double dist = mc.thePlayer.getDistanceToEntity(e);
            wenn (dist <am nächsten) {if (dist < closest) {
              am nächsten = dist;= dist;
              Ziel = e;= e;
            }}
          }}
        }}
      }}
    }}
    entity = target;= target;
  }}
  
  private boolean isValidTarget (EntityLivingBase Entity) {private boolean isValidTarget(EntityLivingBase entity) {
    if (entity == mc.thePlayer)if (entity == mc.thePlayer)
      falsch zurückgeben;return false;
    if (entity.isInvisible ())if (entity.isInvisible())
      falsch zurückgeben;return false;
    if (! (Entity Instanz von EntityPlayer))if (! ( Entity Instanz von EntityPlayer ))  
      falsch zurückgeben;Rückkehr falsch ; 
    zurückkehren;Rückkehr wahr ; 
  }}
}}

**Comment by maxhd0** [comment]
Habe dir den Code gegeben. (Ja selbstgemacht -.-)

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1359
