### ISSUE TITLE
Intelligenter ChestStealer Option (Like Skush)

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1288]

**Comment by maxhd0** [comment]
was macht der der Liquidbounce nicht hat?

**Comment by WistarWolf** [comment]
Nein? Der in Skush nimmt soweit ich gesehen habe nur die Items die gut sind und die anderen lässt er drin. LiquidBounce nimmt alles aus der Kiste. Link zu dem Skush Video: https://youtu.be/e1f2VerocAk

**Comment by maxhd0** [comment]
ne? Skush nimmt keine Doppelnden sachen aus der Kiste. Ich habe bereits eine issue geöffnet. Diese hier kannste schliesen.

**Comment by maxhd0** [comment]
k

**Comment by Marco-MC** [comment]
Mach InventoryCleaner an. Punkt.

**Comment by WistarWolf** [comment]
Tut mir leid du Model ._.
