### ISSUE TITLE
Changeable TabGUI Color

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1289]

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
![5a5f5a5a937d481fd2c83b0bbc6ad1a1](https://user-images.githubusercontent.com/12410754/33516899-84117e1a-d77a-11e7-82e4-ad36c5aa6951.png)
Allows you to edit the color of the highlight box

**Comment by WistarWolf** [comment]
<3
