### ISSUE TITLE
ArmorBreaker

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#129]
pls add Armor Breaker like (Alpha or Pandora) .Because I can't beat my friend(He is using Pandora )

I have turned on the best setting........
But he is on Normal config but turn on Armor Breaker....

I think I am a noob......

pls pro

**Comment by DieErdnuss** [comment]
http://www.bilder-upload.eu/show.php?file=dce654-1501720948.png

Einem Rüstungsteil kann man durch mehrere sachen Haltbarkeit abziehen. Das einzige, dass aber hierfür funktioniert ist schaden durchs schlagen eines anderen Spielers. Also muss der spieler schneller schadem machen können. Dies würde mit einer /give waffe gehen. Aber nicht Ohne Creative.
Falls man es schafft mehr schaden auf einmal zu machen. Hat man aber auch einen KO schlag. Egal wen man schlägt er würde sofort sterben. Man könnte es vielleicht schaffen indem man wenn man einen Spieler schlägt 3 oder 4 mal die gleichen Hit Packets sendet. Versuche es doch mal Marco.


Hier noch die Armorbeak Weapon. Wer sie haben will ^^
/give @p diamond_hoe 1 0 {
    display: {
        Name: "Armorbeak Weapon"
    },
    AttributeModifiers: [
        {
            AttributeName: "generic.attackDamage",
            Name: "generic.attackDamage",
            Amount: 20000,
            Operation: 2,
            UUIDMost: 43939,
            UUIDLeast: 820122
        }
    ],
    Unbreakable: 1
}

**Comment by Marco-MC** [comment]
"Ausnahme des Packet das dafür sorgt das Armor damage" Dir ist schon klar das dass Item Damage Handling ClientSide und ServerSide ist? Es giebt kein ItemDamagePacket, haha. xD

**Comment by Marco-MC** [comment]
"Man könnte es vielleicht schaffen indem man wenn man einen Spieler schlägt 3 oder 4 mal die gleichen Hit Packets sende" Ist ja nicht so das Minecraft einen Hitdelay hat.

**Comment by DieErdnuss** [comment]
Ich überlege nur wie ein Armorbeaker funktioniert. Es gab einen das weiss ich . xave 12 hatte damals einen. 
Das sind hier alles nur Theorien XD

**Comment by Teals53** [comment]
UP @Marco-MC

**Comment by Kodikusik** [comment]
UP @Marco-MC

**Comment by Kodikusik** [comment]
UP @Marco-MC

**Comment by Kodikusik** [comment]
UP @Marco-MC

**Comment by Teals53** [comment]
@Marco-MC UPUPUUP

**Comment by Kodikusik** [comment]
UP @Marco-MC

**Comment by SenkJu** [comment]
Stop spamming or I will block you both @Kodikusik @Teals53

**Comment by Teals53** [comment]
Okey Sorry.

**Comment by Teals53** [comment]
hi again xd

**Comment by CrackFileso** [comment]
Closed.this function is not important and abstract.

**Comment by Teals53** [comment]
@CrackFileso What ?

**Comment by Teals53** [comment]
no pls reopen that

**Comment by Kodikusik** [comment]
Please open. PLEASE

**Comment by unknownscommunity** [comment]
@Marco09MC UP. Please open
