### ISSUE TITLE
KillAura Verbesserung

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1291]
Ich hab mal was im Singleplayer getestet. Und zwar macht die Aura nur schaden wenn maximal 4 Blöcke zwischen dir und dem Gegner sind. http://prntscr.com/gfmnn9 Ab 5 Blöcken (Siehe Bild) macht die Aura nichtmal mehr schaden. Es kommt zwar diese Animation und die Partikel aber es passiert sonst nix. Bitte machen, dass die KillAura auch noch bei 8.0 Blöcken schaden macht.

**Comment by maxhd0** [comment]
Das ist nicht so leicht. Im Singleplayer ist es leicht ja. Da kannst du mit 1nem Schlag alle Mobs die im Umfeld sind Onehitten. Aber schon auf dem Vannilaserver ist alles anders. man könnte natürlich wieder so ne art Teleporthit machen. Denn die Möglichkeit die Range hochzustellen dient meistens für AAC etc, da AAC anders testet. Und dann kann man durch irgendwas Plötzlich die Range auf 5 oder sogar 6 machen. Vielleicht kann aber Marco es schaffen eine 8 Range Killaura für Vanilla (bzw Spigot 1.8.8/1.8.9) zu machen.

**Comment by maxhd0** [comment]
Und wenn du Die Killaura richtig einstellst sollte die Range jetzt sogar höher gehen.

**Comment by Marco-MC** [comment]
Um eine 8ter Range zu bekommen muss man sich tp'n... Die KillAura ist aber keine TP-Aura, deshalb geht halt nur die Range die vom Vanilla Range Check zugelassen wird.
