### ISSUE TITLE
MidClick

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1292]
Bitte beheben dass das MidClick getriggert wird, wenn man in der ClickGUI, Inventar etc ist.

**Comment by maxhd0** [comment]
Wozu brauchst du den Midclick in der ClickGUI, Inventar etc

Ich verwende ihn nur beim Teleport ound freunde adden.

**Comment by maxhd0** [comment]
aber ok. E ist ein Bug.

**Comment by WistarWolf** [comment]
..... Ich brauche das ja eben nicht.... Es wird aber ausgelöst wenn man im Inventar etc ist und midclickt ._. Das ist ein Bug ._.

**Comment by maxhd0** [comment]
k

**Comment by Marco-MC** [comment]
Fixed.
