### ISSUE TITLE
NameProtect: Other Names

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1293]
Man kann den Namen, wenn man AllProtect bei NameProtect an hat selber bestimmen. z.B. ".nameprotect othernames Test123" Dann hat jeder andere Spieler außer du, den Namen Test123. Sofern du das aktiviert hast dass andere Namen geschützt werden sollen.

**Comment by maxhd0** [comment]
Das kenne ich doch von woher.

**Comment by WistarWolf** [comment]
??

**Comment by maxhd0** [comment]
hybrid ^^
