### ISSUE TITLE
Chams Bug

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1294]
Manchmal Bugt Chams und man sieht die Spieler für kurze Zeit nicht mehr durch Blöcke

**Comment by maxhd0** [comment]
Ist das auf AACAD?

Da ist es normal. Du musst einfach invisible an machen, da AACAD spieler unsichtbar macht (soll ein ESP test sein.)

**Comment by WistarWolf** [comment]
Nein. Das ist auch manchmal in Vanilla.... http://prntscr.com/gfql4y

**Comment by maxhd0** [comment]
Oh heilige scheisse ist ja auch nicht so das AACAD bei vannilla immernoch an ist :o 
teste es mal auf poke.sexy wenn es unter killswitch immernoch ist dann ist es wirklich ein bug.

**Comment by WistarWolf** [comment]
K ich teste es mal

**Comment by maxhd0** [comment]
^^

**Comment by WistarWolf** [comment]
Habs im Singleplayer getestet http://prntscr.com/gfqqai

**Comment by maxhd0** [comment]
auf dem bild wo  soll da was sein XD 

Chams zeigt es nicht mehr bei ner hoher range an.

**Comment by WistarWolf** [comment]
och junge Ich Teste es nochmal

**Comment by WistarWolf** [comment]
http://prntscr.com/gfqvd4 http://prntscr.com/gfqvmf http://prntscr.com/gfqvrd

**Comment by maxhd0** [comment]
okok es ist buch chill
