### ISSUE TITLE
Add "HeadDB" Support for "Heads" Inventory

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1297]
http://headdb.com/api

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1223

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1223

**Comment by maxhd0** [comment]
WTF?! 900 Köpfe??? lol nice.
