### ISSUE TITLE
Fucker Nohit

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1298]
Wenn an schlägt die Killaura nicht mehr wenn der Fucker aubbaut. (dann geht fucker auch durch Blöcke)

**Comment by WistarWolf** [comment]
+1

**Comment by ThreRealGatrox** [comment]
Useless. AAC Und NCP checken das komplett anders

**Comment by maxhd0** [comment]
ja aber dann baut fucken überhaupt mal ab. wenn die aura da noch schlägt kannst du in 100 jahren das bed nicht abbauen.

**Comment by Marco-MC** [comment]
Added
