### ISSUE TITLE
Velocity mode: glitching

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1299]
Wenn ich geschlagen werde bug ich mich in den Boden rein. (Wie als ob ich mit noclip sneake und in den Boden bugge. (damit bekommst du kein Knockback) )

Der einzige Nachteil ist das du dich dann aber auch kurz nicht bewegen kannst. darum ist der mode bei SG nicht so gut. jedoch bei Bedwars kann es helfen.

(bei meinem Client funktioniert es perfekt.)
(funktioniert nicht in der Luft, beim Springen. Wenn man in der Luft ist soll man auf den Boden geworfen werden und dann in den Boden buggen.)

**Comment by Marco-MC** [comment]
Added.
