### ISSUE TITLE
Add .binds command

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#130]
/binds oder /bindlist und dann werden alle Module im chat angezeigt und auf welcher taste sie gebindet sie. Die Module die nicht gebindet sind werden nicht angezeigt.

**Comment by FlorijonG** [comment]
besser währe es doch wenn man im ClickGUI ist eine taste drückt und man hinter jedem Module den Bind sieht also (KillAura "R", Sprint "None")

**Comment by WistarWolf** [comment]
Aber ich glaub nicht das du jedes Modul auf klappen willst und schauen willst auf welcher Taste dieses Modul liegt c:

**Comment by FlorijonG** [comment]
Ne ich meine das wie in Xave man drückt eine Taste und daneber ist der Bind

**Comment by WistarWolf** [comment]
Achso

**Comment by Marco-MC** [comment]
Added.
