### ISSUE TITLE
ScaffoldWalk

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1300]
Der scaffold sollte keine Fackeln, Ambosse, sand etc platzieren.

**Comment by maxhd0** [comment]
hä wann braucht man savewalk denn nicht. (ausser wenn man treppen runter geht)

**Comment by SenkJu** [comment]
wozu?

**Comment by maxhd0** [comment]
Es währe besser wenn scaffold mal nicht mit Fackeln etc baut.

**Comment by WistarWolf** [comment]
+1
