### ISSUE TITLE
Jedi Jump Module

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1301]
Man springt hoch und weit. Die höhe und die "länge" des Sprunges natürlich auch selbst bestimmen. Also sozusagen HighJump und LongJump in einem

**Comment by maxhd0** [comment]
Cosim speed ^^

**Comment by maxhd0** [comment]
Custom*

**Comment by maxhd0** [comment]
Lässt sich alles da einstellen. Ab der b27 sogar auch den Timer.
