### ISSUE TITLE
Friend short Commands / friend clear command

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1303]
.friend clear: Man cleart alle friends die man eingespeichert hat

Man kann halt entweder friend oder f, add oder a, remove oder r, und clear oder c verwenden

**Comment by SenkJu** [comment]
nein

**Comment by WistarWolf** [comment]
Wieso?

**Comment by SenkJu** [comment]
Die Frage stelle ich zurück. Wieso sollten wir sowas einbauen? Änderst du alle 20 Sekunden deine Freunde, oder wieso kannst du nicht .friend add [username] schreiben? Und nur so am Rande, Pfeil nach oben drücken bringt einem die letze Nachricht.

**Comment by WistarWolf** [comment]
1. Nein änder ich nicht. Aber ich hab halt gedacht damit man z.B. im Kampf gegen nen Freund hackt, ihn aber als friend hat, ihn schneller als Freund entfernen kann. Dann  halt nicht.

2. .friend clear? Und wehe du kommst mir jetzt mit: Man kann doch ein paar befehle eingeben um die Freunde zu entfernen oder du kannst sie doch in der Config löschen. 

Und 3. Was meinst du mit "Und nur so am Rande, Pfeil nach oben drücken bringt einem die letze Nachricht."

**Comment by SenkJu** [comment]
Das klingt für mich nach keinem relaitischem Szenario. Sollen wir vllt auch noch statt .killaura range einen Command wie .k r machen, weil man ja irgendwann im Kamp mal ganz schnell die Range ändern muss?

**Comment by WistarWolf** [comment]
Joa wäre auch gut. c: ne jetzt mal echt jetzt. Ich hab halt wie gesagt gedacht, dass man befehle einfach schneller ausführen kann. Aber anscheinend wollt ihr das nicht. Mir scheint es auch so, Dass ihr LiquidBounce so klein und kompakt wie möglich halten wollt. No hate.

**Comment by maxhd0** [comment]
Em. Wenn du alle friends clearen willst lösch den freunde ordner. Und um freunde hinzuzufügen mach ich immer milclick. Das ist ein Knopfdruck. 
(Falls du kein mittelklick bei deiner Maus hast kauf dir eine. Die Billigste kostet 1€. Das sind umgerechnet 10 alts. ^^)

**Comment by WistarWolf** [comment]
http://prntscr.com/ggdqyx Klar restarte ich jedes mal mein MC um die freunde zu löschen. Und bis mc gestartet ist geht es auch SEHR schnell jo

**Comment by maxhd0** [comment]
._.

**Comment by WistarWolf** [comment]
:3

**Comment by maxhd0** [comment]
Nachdem die friends datei draussen ist musst du nur den server verlassen und fertig. Und wenn das auch so wichtig ist auf dem server zu beiben. Dann verwende midclick. Damit kannst du adden und removen.

**Comment by maxhd0** [comment]
Also das mit den abkürzungen ist schwachsinn. Den .f kann friend aber auch fucker bedeuten. Ich verwende da z.b mehr fucker. Und das gilt bei jedem buchstabe.

**Comment by WistarWolf** [comment]
1. Wenn ich in einer Runde bin? Hm. HM?
2. Es ist SEHR SEHR unwahrscheinlich dass ALLE freunde die du hinzugefügt hast, in der selben runde und auf dem selben server wie du sind.

**Comment by WistarWolf** [comment]
"Also das mit den abkürzungen ist schwachsinn. Den .f kann friend aber auch fucker bedeuten. Ich verwende da z.b mehr fucker. Und das gilt bei jedem buchstabe." ja stimmt auch wieder

**Comment by maxhd0** [comment]
1. Daumen drehen und warten bis man stirbt. Ist nicht die Welt.

2.dann ist das auch egal. Du kannst es nämlich dann im friends order machen.

**Comment by WistarWolf** [comment]
Deine antworten wenn etwas dumm ist, überzeugen mich mehr als die vom ccbluex team xd (No hate ans ccbluex team)

**Comment by maxhd0** [comment]
Das CCbluex Team programmiert. Zudem wollen sie nicht unendlich viele gespräche mit läuten die es nicht verstehen. Warum? Weil sie genug von denen haben. Habe ich auch erst vor kurzem begriffen. Jeden tag kommt jemand und fragt die das teams z.b nicht funktionniert. Und jeden tag müssen sie sagen. In der b27 ist es gefixt. Das strengt die nerven an und mit ner zeit gibt man auf.

**Comment by maxhd0** [comment]
Und wegen mir? Ich bin politiker. Bzw mein vater. Und ich dann auch. Das was ich am liebstem mache ist mich mit jemanden unterhalten. Darum bin ich auf vielen servern mod oder friend. Kann einfach super reden.

**Comment by WistarWolf** [comment]
Ja schon. Aber wenn sie mir antworten, wieso etwas nicht geaddet wird, überzeugt mich die antwort einfach nicht.

**Comment by maxhd0** [comment]
K. Dazu kann ich nichts sagen.
