### ISSUE TITLE
TabGUI: Activated modules have the color of the TabGUI

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1305]
http://prntscr.com/ggdazl man kann das nicht gerade gut erkennen. (Wehe einer kommt mir mit, du kannst doch in die ArrayList schauen)

**Comment by maxhd0** [comment]
Hä. Bist du Farbenblind? XD 

Ne erlich. Wenn du das wirklich nicht erkennst. Geh mal zum Optiker. (nicht böse gemeint)

**Comment by maxhd0** [comment]
Oder meinst du dieses grau zu weiss? ( dann nehme ich es zurück) joa. Naja. Man kann es vill ein bissle grauer machen.

**Comment by WistarWolf** [comment]
xd

**Comment by WisaWolf2** [comment]
Und wenn man mit diesem "auswähl ding da" über ein module geht,soll es weiß / gra sein, egal ob es deaktiviert/aktiviert ist
