### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1306]
DELETED

**Comment by maxhd0** [comment]
Autoblock? XD Genau das macht autoblock. 

Autoblock blockt ja nicht die ganzezeit bei der Killaura. Da kannst du ja auch rechtsklick gedrückt halten.

**Comment by WistarWolf** [comment]
AutoBlock, block durchgehen.... Lesen ist so ne sache http://prntscr.com/ggdo8v
