### ISSUE TITLE
Watermark, ArrayList font

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1308]
Man kann einstellen ob nur die ArrayList die Font haben soll und die WaterMark die mc Font, und ob die WaterMark die Font hat und die ArrayList die mc Font. Ich fände es halt schön wenn man das einstellen kann. So z.b.

HUD > WaterMark > MC Font oder Custom Font
HUD > ArrayList > MC Font oder Custom Font

**Comment by maxhd0** [comment]
Gibts doch schon.

**Comment by WistarWolf** [comment]
nein? Wenn man MC Font hat, übt sich das auf die ArrayList und die WaterMark aus. Und wenn man die font von lb benutzt, übt sich das auch auf die arraylist und die watermark aus.

**Comment by maxhd0** [comment]
Also ich will eher nur 1 Schiftart haben. 
Ich stell mir schon vor: Jeder Text ne andere Schriftart xD

(Übertrieben gesehen)

**Comment by WistarWolf** [comment]
Nein. So übertrieben jetzt auch nicht xd Ich finde halt die WaterMark mit der mc font nicht so schön. Die arraylist mit der mc font aber schon.

**Comment by maxhd0** [comment]
Marco hat da eher wichtigere sachen zu machen als eine Font überal zu ändern.

**Comment by maxhd0** [comment]
Ich kenne marco nach 100 Kriegen über etwas sinnlosem xD

Wenn er es macht wird es die Letzte issue sein die hier ist xD

**Comment by maxhd0** [comment]
Aber ok. Marco kanns enscheiden.

**Comment by WistarWolf** [comment]
Ich kenne Marco auch sehr gut. Zumindest wenn es um Design Änderung geht. Bevor er etwas am design macht, hast du eine viel VIEL größere chance im lotto zu gewinnen

**Comment by maxhd0** [comment]
Da closet er es selber XD
