### ISSUE TITLE
Bowaimbot Through Blocks Setting

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1311]
Bowaimbot Through Blocks mode

**Comment by WistarWolf** [comment]
Das problem ist, wie willst du ihn treffen wenn er ja hinter einer Wand steht xd

**Comment by Bircko** [comment]
Es geht darum das der bowaimbot eben nurch die Wand auf den Gegner aimt und man kann durch die wand drefen wenn die Wand so ist X = Wand und 0,H Leere
XOO
HXX 

Bei dem H wenn man genau in die ecke schießt kann man den gegner falls er dort steht durch treffen.

**Comment by WistarWolf** [comment]
Achso ja. Da war ja was.

**Comment by maxhd0** [comment]
dann soll er die Hitbox anzielen. Aber doch nicht algemein durch blöcke. da wählt er ja den 1 besten aus.
