### ISSUE TITLE
Instapickup

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1312]
Du sammelst schneller items ein.

Dies funktioniert indem du beim stehen den Timer auf 1.1 machst und den Ping auf 1 runterdrehst.

**Comment by maxhd0** [comment]
Das letzte mal wurde es gecloset weil marco nicht wusste wie es funktioniert. Jetzt weiss er es.

**Comment by Marco-MC** [comment]
1. Das mit Timer und so geht nicht, das habe ich schon ausgetestet.
2. Man kann einen Ping nicht verbessern. (Server Schickt Ping Packet >> Client bekommt es >> Client schickt Ping Packet >> Server bekommt es >> Zeit)

**Comment by maxhd0** [comment]
medox sagte mir es so. Sein instapickup funktioniert bestens.

**Comment by Marco-MC** [comment]
https://www.youtube.com/watch?v=ihXPb9W4VUU&feature=youtu.be

**Comment by SenkJu** [comment]
Das ergibt alleine schon überhaupt keinen Sinn. Warum sollte das funktionieren? Der Server bestimmt, wann du ein Item aufheben kannst, Timer ist clientside.

**Comment by maxhd0** [comment]
Ja. Kp. Ich weiss das einer geht.
