### ISSUE TITLE
FOV 360

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#1320]
Das FOV soll bis 360 gehen.

**Comment by RealFantaCoke** [comment]
Wozu benötigst du dieses Feauture?
Total unnötig und außerdem kannst du es auch in den normalen Minecraft Einstellungen im ".minecraft"-Ordner umändern.

**Comment by FlorijonG** [comment]
DAS IST GEIEL

**Comment by Marco-MC** [comment]
INSTALLIER DIR DOCH EINFACH 5ZIG MOD WENN DAS 5ZIG MOD HAT

**Comment by maxhd0** [comment]
hat er nicht XD
