### ISSUE TITLE
NoPumpkin Option for AntiBlind/NoBlind

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1322]
Man bekommt halt diese sicht vom Kürbis nicht wenn man einen auf hat

**Comment by SenkJu** [comment]
Wenn dann als Option bei NoBlind

**Comment by WistarWolf** [comment]
k

**Comment by maxhd0** [comment]
+1

**Comment by superblaubeere27** [comment]
Warum?

**Comment by WistarWolf** [comment]
Weil es stört wenn man einen Kürbis auf hat und sone komische sicht hat?

**Comment by Marco-MC** [comment]
Added
