### ISSUE TITLE
HiveMC AutoSettings: 

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1326]
In den Hive AutoSettings denn ScaffoldMode Slow Eagle Mode umstellen. Auto Block kann man auch aktivieren. Bypasst perfekt

**Comment by maxhd0** [comment]
Die Autosettings wird man denke ich erst wieder Aktualisieren wenn die B27 draussen ist.

**Comment by maxhd0** [comment]
Kann ich dann aber machen ;-)

**Comment by SenkJu** [comment]
Geändert.
