### ISSUE TITLE
ArrayList Tags with [] 

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1327]
Es wäre nett wenn @Marco-MC mir mal ein Bild senden kann, wie es aussieht wenn statt 
KillAura Switch,
KillAura [Switch] 
in der ArrayList steht. Bin mir nämlich sicher wie es bei LB aussieht ;) Wäre also nett wenn du mir ein Bild schicken könntest wie das aussieht @Marco-MC

**Comment by superblaubeere27** [comment]
Oh mein gott
