### ISSUE TITLE
MC bug Gui verschiebt sich bei trank effekten

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1330]
Nur in der 1.8 verschiebt sich die GUI wenn Trankeffekte kommen. (In der 1.7 wars noch nicht und in der 1.9+ ist es wieder so wie in der 1.7)
http://www.bilder-upload.eu/show.php?file=13412d-1504731113.png

Wenn man zusätzliche mods hat, die was bei der GUI machen, dann geht die GUI in eine andere rein und man kann nichts mehr machen.

(Ich weiss das es nicht der übelste Bug ist aber es nervt sehr oft und es sieht auch viel schöner aus wenn die Gui in der mitte bleibt.)

**Comment by Marco-MC** [comment]
... DAS IST KEIN BUG. DAS IST VON MINECRAFT 1.8 SO GEWOLLT.

**Comment by maxhd0** [comment]
Ich weiss. Aber keiner mochte es. Und darum wurde es ab der 1.9 entfernt.
