### ISSUE TITLE
Auto QSG

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1331]
Ein Modul das für dich automatisch QSG spielt, wärend du afk bist und auch automatisch ihn neue Runden geht.

**Comment by maxhd0** [comment]
Und was ist daran eig so gut. Wenn der Bot alles für dich macht. Macht es doch dann kein Spass mehr. Oder machst du es für stats. Alter Stats sind nur was für leute die kein Leben haben. Was ändert es wenn du statt einer 3 K/D eine 18 hast? Du kannst angeben. Krass. Das ist aus den Hackern geworden. Sie wollen mit ihren Hacks angeben. ._.
