### ISSUE TITLE
Scoreboard 

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1335]
Ein Module bzw in LiquidBounce integrieren, dass das Scoreboard (Wenn eins exestiert) immer ein bisschen unter der ArrayList ist.

**Comment by SenkJu** [comment]
Wenn dann irgendwo als Setting.

**Comment by WistarWolf** [comment]
Okay. Vllt bei HUD als setting

**Comment by maxhd0** [comment]
Bei Skid b6.9 ist das unten rechts. Sieht eigendlich auch sehr gut aus.

**Comment by maxhd0** [comment]
Man könnte NoScoreboard zu Scoreboard umbennenen und dann y settings hinzufügen und halt noch das NoScoreboard setting. (Und vielleicht noch das setting: (das was WistarWolf schreibt)
