### ISSUE TITLE
Tracers

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1337]
Um so näher die gegner sind, um so dunkler soll die farbe vom ESP werden. Wenn sie halt weit weg sind grün, dann gelb/orange und wenn sie ganz nah sind rot. Da das Module sonst komplett kein sinn macht. Was soll man denn sonst mit dem module anfangen können? 
Und man soll die dicke vom Tracer einstellen können (Vllt nicht umbedingt aber das obere wäre ganz sinnvoll)

**Comment by maxhd0** [comment]
Gibts schon -.-

**Comment by WistarWolf** [comment]
Wo?
