### ISSUE TITLE
Altmanager setting: Copy

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1344]
Wenn ich ein Alt auswähle und dann den Copy button clicke, dann soll dann der Account in der clipboard gespeichert sein. (als: E-mail:Passwort)

Wenn man einem Freund einen Alt geben möchte.

**Comment by FlorijonG** [comment]
Guck doch in die Accounts.(ka) rein da stehen alle alts + altname

**Comment by Marco-MC** [comment]
Added.

**Comment by maxhd0** [comment]
FlorijonG ja aber man muss suchen. So weiss man immer direkt welcher es ist.
