### ISSUE TITLE
HUD setting: Backgound

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1345]
Wenn ich eine Truhe öffne, dann wird der Hintergrund dunkler. und wenn ich Background aus mache soll der Hintergrund nicht mehr dunkler werden. manchen gefällst. (und je nach Monitor kann man auch besser sehen.)

**Comment by WistarWolf** [comment]
Marco und Design Optionen / Design änderung = Totale verfeindschaft

**Comment by maxhd0** [comment]
Sowas ist halt in vielen Clients. Und wenn man es nicht haben will kann man es ausschalten.

**Comment by WistarWolf** [comment]
Hotbar ist auch in vielen Clients. Trotzdem will marco es nicht.

**Comment by maxhd0** [comment]
Wenn er es nicht will und es Closet ist das ja ok. Bei Design kann er es. Nur bei modulen die nichts mit Design zu tun haben finde ich es manchmal schade. Und zudem kann man ab der B27 alles machen. Hotbar etc.

**Comment by SenkJu** [comment]
Mach Blur an, wenn du so einen Effekt willst.

**Comment by maxhd0** [comment]
auch wahr. Mir gefällt das blur zwar nicht aber dieses andere würde ich auch nicht verwenden. Alles gut ^^
