### ISSUE TITLE
LiquidScript

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1347]
1. Ein XYZ Value
2. Ein Username Value
und 3. (Vllt ist das schon drin) Dass man den Chat halt erhöhen kann. z.B. Falls man unten links eine hotbar macht, die etwas höher ist.

**Comment by Marco-MC** [comment]
XYZ:
```
player.posX
player.posY
player.posZ
```
Username Value:
Kann ich einbauen.

Und was soll das letze sein?

**Comment by WistarWolf** [comment]
1. Achso k
2. Jo wäre tull
3. Dass man in lb script den chat um die Y Koodinate erhöhen/tiefer machen kann.

**Comment by Marco-MC** [comment]
1. k
2. k
3. nein

**Comment by WistarWolf** [comment]
3. Dann bringt mir eine username anzeige recht wenig. Da die FPS dann ein stück in den chat reingeht.
Ich möchte es halt so machen:
FPS:
User:
XYZ:
Aber dann geht fps wie gesagt in den chat rein

**Comment by Marco-MC** [comment]
Ja juckt?

**Comment by WistarWolf** [comment]
._.

**Comment by FlorijonG** [comment]
1:0 für Marco

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/705
