### ISSUE TITLE
Anti Killaura

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1352]
Ein Modul das es killaura von anderen Clients schwerer macht dich zu hitten bzw gar nicht möglich macht.

**Comment by maxhd0** [comment]
hä? Das währe dann ein Godmode. Man könnte es vielleicht mit ner TP-Aura machen. Aber diesen Vorschlag gibts bereits.

**Comment by maxhd0** [comment]
Wie soll er es denn machen?

**Comment by SenkJu** [comment]
Wie stellst du dir das vor?

**Comment by Bircko** [comment]
Wie in cs go anti aim z.b das die hitboxen verschoben werden bzw. das die hitboxen und der spieler auf einer anderen stelle sind.

**Comment by SenkJu** [comment]
Ich bin mir ziemlich sicher, dass das in Minecraft nicht funktionieren wird.

**Comment by Bircko** [comment]
probieren kann man es ja mal.

**Comment by maxhd0** [comment]
Es geht. Aber 1 nur vanilla und 2 nicht auf spigot.
