### ISSUE TITLE
add Teammate detect mode to Team Module

### ISSUE THREAD

**Issue by Ldcr993519867** [CCBlueX/LiquidBounce1.8-Issues#1353]
scoreboard - in the same scoreboard team will be marked as teammate
nametag - has same nametag color will be marked as teammate
armor - has same the leather armor color will be marked as teammate
color - let we select team color manually, and who has this nametag color will be marked as teammate

nametag color check please use contains(String),not startWith(String)
because in some minigame,the nametag will be like : 
_(white)_[_(teamcolor)_ TEAMNAME _(white)_] _(teamcolor)_playername
so if you use startWith(),all player will be marked as white team

i don't know current Team module how to detect teammate,but it not works for me,all player will be "teammate" when i enabled Team

**Comment by maxhd0** [comment]
Apart from that with the armor everything is good.

**Comment by Ldcr993519867** [comment]
Ok it now works in newest version.
