### ISSUE TITLE
Smoother ScaffoldWalk 

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1354]
Scaffold sollte auch bauen wenn man in der ecke vom block steht. Sowie in Jigsaw

**Comment by BlackHawk2306** [comment]
Nice Idee, aber man kann auch Savewalk und Fastplace zum schräg bauen nutzen. #LegitschwitzerMode

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
https://img.ccbluex.net/moc/2018-07-16_00-37-53.mp4
