### ISSUE TITLE
.say bug

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1356]
wenn ich .say ._. mache dann erkennt er das . nach dem say auch als lb befehl. Damit könnte man:
.say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say .say usw machen und dann crasht der irgendwann.
plz fixen.

**Comment by FlorijonG** [comment]
lal

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/708
