### ISSUE TITLE
mcleaks forgemod

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#1357]
Könnt ihr den mcleaks forge mod so umcoden dass man das symbol für das einoggmenü von mcleaks im startmenü von lb sieht, dann könnten die leute die keine alts haben auch mit lb spielen. (ich denke, das ist nicht schwer.)

https://mcleaks.net/altloader

**Comment by SenkJu** [comment]
Ist doch schon längst im Client, nur geht es in der b26 nicht.
