### ISSUE TITLE
Sorted AutoArmor, InventoryCleaner and ChestStealer

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1360]
Als erstes wird halt die Kiste gelootet wenn man eine Kiste lootet, dann wenn man nichtmehr in dem Inventar der Kiste ist, wird das Inventar von Inventory Cleaner gecleart, und zum Schluss wird AutoArmor "benutzt".

**Comment by superblaubeere27** [comment]
Ja und genau so läuft das

**Comment by Marco-MC** [comment]
Schwachsinn
