### ISSUE TITLE
Update hypixel fly (Hypixel infinity fly)

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1365]

**Comment by Marco-MC** [comment]
Updated.

**Comment by maxhd0** [comment]
"infinity" wo bitteschön soll der infinity sein. Der geht wie der Alte ca. 5 Blöcke.

**Comment by SenkJu** [comment]
Hypixel hat ihn gefixt soweit ich weiß.

**Comment by maxhd0** [comment]
bei mir geht es nicht. Hat Hypixel da was geupdated? Oder geht der nur in Skywars?
