### ISSUE TITLE
B27: MCfont

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1371]
Wenn ich die MCfont auswähle habe ich plötzlich nurnoch 16 FPS statt 60. (Es liegt an HUD) Wenn ich HUD ausmache habe ich dann wieder 60 FPS.

**Comment by Marco-MC** [comment]
Was für ein Oma PC hast du bitte, wenn dein PC in die Knie geht beim Minecraft FontRenderer?
Benutzt halt einfach MCFont nicht, wir können das nicht fixen und da gibt es auch nichts zu fixen.
https://gyazo.com/3b4726913a880ee2793a8f41918cce61
