### ISSUE TITLE
Fucker sollte nicht versuchen das eigene Bett abzubauen (Bedwars)

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1372]
Wie gesagt, die Idee steht schon im Titel. Möglich wäre es zum Beispiel, wenn beim Spawnen in der Map alle Betten im Umkreis vom z.B. 20 Blöcken nicht vom Fucker betroffen sind.

**Comment by maxhd0** [comment]
oder er soll ein Bett 4 malabbauen und dann soll er das Bett nicht mehr abbauen. (soll ein settings sein)
