### ISSUE TITLE
InventoryCleaner Bug Max/Min

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1374]
http://prntscr.com/gwxepp

**Comment by SenkJu** [comment]
Das sollte nur über Commands so einstellbar sein.

**Comment by WistarWolf** [comment]
nein
Hab es getestet. Das geht auch Manuel

**Comment by Marco-MC** [comment]
Das sollte allgemein nicht funktionieren... xD

**Comment by Marco-MC** [comment]
Fixed.
