### ISSUE TITLE
b27 AntiForge bug!!!

### ISSUE THREAD

**Issue by txgs888** [CCBlueX/LiquidBounce1.8-Issues#1377]
Hello, I am a player from China.
You should already know the NetEase agent Minecraft.
b27 version of the AntiForge function is turned on by default, but NetEase agent Minecraft start the game will automatically join the server, and NetEase agent Minecraft server will detect the client is not forge, if the client is not forge will banned.
So I hope AntiForge this function can save config or default to off

**Comment by cui0v0** [comment]
I am a player from China, too.
NetEase doesn't let us to open gui of Multiplayer. So we can't toggle BypassAntiForge to Off. When I couldn't connect to server (disconnect) the server, I can toggle it. But I can't connect to the server in first time, if you want to join the server, you need to restart the game. So it was so bad! And I found, if you toggled it to Off, when I open the game next time, it was toggle to On again. So I really hope you can change this problem next version. We really need it!

**Comment by zmz2333** [comment]
That is not good, ccblux is a lasy boy

**Comment by Marco-MC** [comment]
![cf4aa306774ee0ef3ae6f6b6f6b87c7a](https://user-images.githubusercontent.com/12410754/31850240-2cb9c786-b64f-11e7-882b-7edd83e2c82c.png)
The state will be saved now in the values.json. :)
