### ISSUE TITLE
"Custom" swing animation

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce1.8-Issues#1378]
Wie in Amera dass man x, y, Speed (oder mehr) einstellen kann beim schlagen

**Comment by WistarWolf** [comment]
Unnötig :kappa:

**Comment by TheRealDAT** [comment]
Für dich

**Comment by SenkJu** [comment]
Junge, nein.

**Comment by maxhd0** [comment]
XD. Wie viel mal habt ihr dieses "Unnötig :kappa:" und "Für dich" und anschliessend leht es senk ju ab XD

Ich feier das XD
