### ISSUE TITLE
Rainbow StorageESP

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce1.8-Issues#1379]
Wie bei allen anderen ESP's um die Rainbow reihe zu beenden

**Comment by WistarWolf** [comment]
Unnötig :kappa:

**Comment by TheRealDAT** [comment]
Für dich

**Comment by SenkJu** [comment]
Nein, weil es bei StorageESP ein Farbensystem gibt, das dann nicht mehr funktioniert.

**Comment by WistarWolf** [comment]
Ich finds lustig dass Senk Ju bei anderen einen Ablehngrund angiebt (Manchmal zumindest) aber bei mir nicht lel.  @TheRealDAT Das "Unnötig :kappa:" war ein spaß xd
