### ISSUE TITLE
Speeds in Kategorien

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce1.8-Issues#1386]
AAC Speeds in AAC reiter, NCP Speeds in NPC reiter, Custom in Custom rein inkl. einstellungen. Mein GUI ist auf 0.9 und mit speed passt es nicht ins Fenster bei mir. Abgesehen davon wär es schon übersichtlich.

**Comment by maxhd0** [comment]
Ditto. Ich sehe auch nicht mehr alles.

**Comment by TheRealDAT** [comment]
Ich hab das Marco schon in der b24 geschrieben
