### ISSUE TITLE
Twitch-Streaming & SuperSecretSettings

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1387]
Hey,

könntet ihr bitte die Super-Secret-Settings und die Twitch-Streaming Funktion aus den Einstellungen entfernen?

Das ganze funktioniert sowieso nicht mehr, und ab der 1.9 wurde es von Mojang entfernt.

**Comment by Marco-MC** [comment]
Nein
