### ISSUE TITLE
LiquidLauncher Performance

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1388]
Hey,

der Download der Libraries von Minecraft dauert im LiquidLauncher sehr lange.
Wäre es möglich die Performance etwas anzuheben oder auf bestimmte Sachen zu verzichten?

**Comment by Marco-MC** [comment]
1. Das hier ist für LiquidBounce und nicht für LiquidLauncher. (Hier das richtige: https://git.liquidbounce.net/CCBlueX/LiquidLauncherIssues)
2. Das laden der Libraries ist doch nur einmalig, wo ist das Problem?
3. Bei mir lädt es fucking schnell, also ich verstehe nicht was dein Problem damit ist.
