### ISSUE TITLE
ClickGUI render bug

### ISSUE THREAD

**Issue by GameEaters** [CCBlueX/LiquidBounce1.8-Issues#1394]
I found a small bug with the clickgui while messing around with some settings, not a big problem, but its still a bug...
short clip: https://gyazo.com/e920472e2fb9284eb5972b380e5723d5
clickgui settings: https://gyazo.com/57a13a44d4fd490c0bfdfccd60c431e0

**Comment by Marco-MC** [comment]
Fixed.
