### ISSUE TITLE
LiquidScript: Ability to add modes to already existing modules

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1396]
man sollte auch eine Einstellung für ein Module mit LiquidScript machen können. Dass man z.b. einen Speed den man mit LiquidScript gemacht hat, nicht als Module sonder als einen Speed Mode beim Speed Module. z.b.

registerOption(Modulename, Option Name);

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1768
