### ISSUE TITLE
Add GUIControl Bruteforcer

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1398]
https://www.spigotmc.org/resources/%E2%9C%AAguicontrol%E2%9C%AA-console-ultimate-server-control-free-version.24331/

https://www.spigotmc.org/resources/%E2%9C%AAguicontrol%E2%9C%AA-ultimate-server-control-real-desktop-application.27227/

**Comment by Marco-MC** [comment]
Added

**Comment by maxhd0** [comment]
Und was soll LB da machen?

**Comment by Marco-MC** [comment]
@maxhd0 https://de.wikipedia.org/wiki/Brute-Force-Methode
