### ISSUE TITLE
Force Unicode Chat

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1400]
All messages are sent as Unicode characters.

**Comment by Bircko** [comment]
zuwas?

**Comment by WistarWolf** [comment]
Was soll das bringen?

**Comment by SenkJu** [comment]
Nachrichten die man sendet während Unicode an ist werden in Server- und Clientlogs nicht angezeigt.

**Comment by Bircko** [comment]
könnte man damit anti spam usw bypassen?

**Comment by SenkJu** [comment]
Früher schon aber die meisten AntiSpam PLs blockieren Unicode einfach komplett.

**Comment by maxhd0** [comment]
die die es aber nicht machen sind am Arsch. Damit könnte man den Server Crashen. Hmmm

Einen Unicode Servercrasher währe schon gail. XD

**Comment by Bircko** [comment]
Also ich kenne manche server da kannst mit symbolen und japanischer schrift usw. anti spam komplett bypassen

**Comment by WistarWolf** [comment]
"Nachrichten die man sendet während Unicode an ist werden in Server- und Clientlogs nicht angezeigt." ich frag mich trotzdem noch was das bringen soll

**Comment by Marco-MC** [comment]
Added
