### ISSUE TITLE
No description for some modules

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1402]
Wenn man auf ein Modul zeigt, dann kommt immer die Infomation dazu. 
Bei manchen neuen Modulen steht da aber garnichts. 
(Beispiel ist Teleporthit)

**Comment by Marco-MC** [comment]
https://img.liquidbounce.net/moc/2018-02-15_20-36-39.png
![2018-02-15_20-36-39](https://img.liquidbounce.net/moc/2018-02-15_20-36-39.png)

**Comment by Marco-MC** [comment]
Added / Fixed
