### ISSUE TITLE
NameProtect: Friends

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1403]
Wenn man Freunden keinen Name als friend gegeben hat, sollen sie den Namen "Protected Friend" bekommen, wenn man bei NameProtect allPlayers an hat. (Idee by MaxHD lel)

**Comment by maxhd0** [comment]
XD

**Comment by maxhd0** [comment]
Schon aber ich habe es nicht als issue gemacht weil eh keiner das "Friend" anschaut. Keiner würde es bemerken. Ich sehe Freunde an ESP etc. Aber ok. NameProtect währe dann "Logisch". Werden ja nur ca. 2 zeilen hinzugeügt. Also juckt?

**Comment by maxhd0** [comment]
Ach ja @WistarWolf schaust du eigendlich jede Minute in die Github Issues? Habe das gefühl du würdest regelrecht darauf warten Issues zu schreiben/Issues zu beantworten. XD
Ich schaue da vielleicht mal rein wenn ich Langeweile habe. Aber mehr nicht. XD (das sind so ca. 2 mal am Tag)(und auch nicht jeden Tag)

**Comment by WistarWolf** [comment]
Da hast du sogar recht xd Ich schau iwie alle 10 oder 5 minuten auf github und schau ob es was neues gibt xd

**Comment by Marco-MC** [comment]
Hmm, wozu gibts wohl Aliases bei .friend?? Hmmm, ich weiß es nicht... HMMMMMM????

**Comment by WistarWolf** [comment]
http://prntscr.com/gxltyw Lesen kannst du wohl nicht
