### ISSUE TITLE
GommeHD Endergames Cheststealer bug

### ISSUE THREAD

**Issue by maxhd0** [CCBlueX/LiquidBounce1.8-Issues#1408]
Ich habe jetzt viele runden Endergames gespielt. Und er nimmt oft nicht alle Items aus der Truhe. Manchmal dauert es 1 bis 2 Sekunden bis er was aus der Truhe nimmt. Und mit ChastAura geht es immoment garnicht. Oft öffnet er die Chast garnicht und wenn er sie öffnet schliesst er sie direkt, weil er eine andere Truhe sah. Etc

**Comment by SenkJu** [comment]
Welcher Server?

**Comment by maxhd0** [comment]
Gommehd.net

**Comment by maxhd0** [comment]
Ist ja glaub der einzige Server mit Endergames.

**Comment by SenkJu** [comment]
Muss ich überprüfen
