### ISSUE TITLE
bugfix b27.1

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1410]
release b27.1 wo der dreckige scheiß bug mit den commands gefixt wurde

**Comment by SenkJu** [comment]
Junge, den Drecksbug haben wir schon längst gefixt und wenn du den noch einmal reportest werde ich dich aus den Issues bannen.

**Comment by maxhd0** [comment]
So wie man mich aus den Issues bannte? :lenny:
