### ISSUE TITLE
Keybind Settings

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1413]
Wie das Config-System ein Keybind-System (.localkeybinds <load/save>)

**Comment by SenkJu** [comment]
ne, die binds kannste aus den konfigs auslesen

**Comment by RealFantaCoke** [comment]
Okay, das wusste ich nicht.
Naja, ich wusste es schon, aber habe nicht daran gedacht.

Habe seit über 2 Monaten circa nicht mehr mit LiquidBounce gespielt.
