### ISSUE TITLE
Keybinds GUI

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1414]
Ich wäre dafür, dass es in der GUI eine Art "Button" gibt, welcher einen direkt die Keybinds setzen lässt.

Oder eventuell mit der mittleren Maustaste auf die Modules drücken und dann erscheint eine virtuelle Tastatur, wo man nur noch die Tasten anklicken muss. (Wie in Null).

**Comment by Marco-MC** [comment]
Das mit der Virtuellen Tastatur, wollte ich mal machen, nur gibts dann Probleme wegen dem Tastatur Layout. LiquidBounce wird ja schließlich nicht nur von Deutschen genutzt. Das mit der Virtuellen Tastatur wäre zwar mega geil, aber nicht machbar. Ich baue einfach ein das sich ein kleines Menü öffnet wo man dann die Taste drücken muss die man haben will.

**Comment by RealFantaCoke** [comment]
Naja, im Prinzip könnte man das auch in der HUD einstellen.
Oder du machst auf dem Willkommensbildschirm (beim ersten Start von LB) eine Auswahl, in welchem Land man lebt, bzw. welches Tastatur-Layout man verwendet.

**Comment by Marco-MC** [comment]
Das mit dem "Land wo man lebt" kann ich auch über Language machen, aber trotzdem ist das mit dem Keyboard zwar schöner aber umständlicher.

**Comment by RealFantaCoke** [comment]
> Das mit dem "Land wo man lebt" kann ich auch über Language machen, aber trotzdem ist das mit dem Keyboard zwar schöner aber umständlicher.

Auch dafür gibt es eine Lösung ... einfach eine Option bei dem GUI mit einbauen.

**Comment by Marco-MC** [comment]
Nein, ich werde nicht für jede fucking Sprache eine Tastatur machen.

**Comment by SenkJu** [comment]
#1625

**Comment by RealFantaCoke** [comment]
> Nein, ich werde nicht für jede fucking Sprache eine Tastatur machen.

Da du dich ja scheinbar nach langer Zeit doch noch umentschieden hast (du hast einen anderen Vorschlag, der genau gleich aufgebaut ist angenommen), wird's langsam höchste Eisenbahn :P
