### ISSUE TITLE
Addon Manager

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1415]
Eine Art Addon-Manager, wie in LabyMod 3.0

Mit dem Addon-Manager soll man Mods wie OptiFine, ItemPhysics oder ähnliches direkt herunterladen können.

Danach muss man nur noch den Client neustarten und schon hat man die Mods aktiviert.

**Comment by SenkJu** [comment]
Nein, das können wir allein rechtlich schon nicht machen. Denke nicht, dass es zum Beispiel dem Optifine Dev gefallen würde, wenn wir es möglich machen, Optifine ohne seine Adflys und Werbebanner runterzuladen.

**Comment by RealFantaCoke** [comment]
Dann macht es zumindest so, dass man direkt die Download-Links zu den kompatiblen Versionen bekommt.

Das wäre deutlich einfacher.

**Comment by maxhd0** [comment]
@RealFantaCoke lade dir einfach die Mods runter und schiebe ihn in den Mods Ordner. Ist doch nicht schwer.
