### ISSUE TITLE
Fly: Option to disable mark

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1416]
Diese rote Fläche bei Fly deaktivierbar machen oder komplett entfernen.

Es nervt einfach nur.

**Comment by WistarWolf** [comment]
Allgemein auch bei killaura etc. Vllt dass man es im Module HUD deaktivieren kann.

**Comment by RealFantaCoke** [comment]
Jo, stimmt.

Daran habe ich gar nicht gedacht.

**Comment by maxhd0** [comment]
Das ist doch sehr hilfreich. Vielleicht eine Funktion, die es ausschaltet aber auf keinen Fall ganz entfernen.

**Comment by RealFantaCoke** [comment]
@maxhd0 Genau das habe ich doch oben geschrieben.
Lies bitte meinen Beitrag erneut oder unterlasse diese Bemerkungen.

**Comment by maxhd0** [comment]
Habs schon gelesen. Ich habe es nur verdeutlicht.

**Comment by RealFantaCoke** [comment]
Hätte ich gewollt, dass du es "verdeutlichst", dann hätte ich dir bescheid gesagt.
Nimm dir nicht immer Rechte raus, die du gar nicht hast.

**Comment by Marco-MC** [comment]
Added
