### ISSUE TITLE
Autosettings list

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1418]
Beim Autosettings Syntax sollte auch "list" angezeigt werden

**Comment by RealFantaCoke** [comment]
Gute Idee.

**Comment by Marco-MC** [comment]
Diese List ist eigentlich garkeine richtige list... SenkJu hat das einfach mit einem AutoSettings script gemacht... Ich muss schauen, das ich das irgendwie mal richtig mache. Ich will das auch nicht so machen das die namen in einer txt stehen, sondern die richtig von github geladen werden.

**Comment by SenkJu** [comment]
.autosettings list

**Comment by WistarWolf** [comment]
Nein. Das man .settings list machen kann weiß ich schon. Aber es soll auch angezeigt werden dass man das überhaupt eingeben kann. http://prntscr.com/hht5vs
