### ISSUE TITLE
altmanager disable alts

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1419]
altmanager alts von random entfernen damit sie nicht von random erfasst werden, weil ich wurde mal mit einem meiner main accounts deshalb gebannt

**Comment by maxhd0** [comment]
Habe ich mal vorgeschlagen. Dass man Favoriten machen kann.

**Comment by WistarWolf** [comment]
so sinnvolle sachen werden nicht eingebaut.
