### ISSUE TITLE
Killaura not working

### ISSUE THREAD

**Issue by HeiIsFlying** [CCBlueX/LiquidBounce1.8-Issues#1421]
Killaura will only hit once and then it stops.

**Comment by Marco-MC** [comment]
Dude, I cant help you if you just say "Killaura will only hit once and then it stops.".
You need to get more informations, because the killaura work for me very good

**Comment by HeiIsFlying** [comment]
Can you show me the settings you use??

**Comment by Marco-MC** [comment]
... try the AutoSettings.
