### ISSUE TITLE
Add InventorySave Module

### ISSUE THREAD

**Issue by Ldcr993519867** [CCBlueX/LiquidBounce1.8-Issues#1422]
make i can close a inventory(just clienside) and reopen it
it should works like InventoryMove but doesn't display the inventory gui.
(the Inventory can be reopen by press a key)

so, in some minigame,
i can open a shop and close(save) it
and reopen the shop anywhere to buy something :)

**Comment by SavageSOC** [comment]
I don't think that is possible

**Comment by Ldcr993519867** [comment]
it can be possible by close inventory in clientside(in the serverside your inventory still keep open)
and then if you want to reopen the inventory,just display the inventory again
(you had never closed the inventory in serverside,all close and reopen action only happend in client)

**Comment by FireMasterK** [comment]
Sure is possible, AAC or ncp?

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/604
