### ISSUE TITLE
LiquidScript: Current Time and Date value (english format)

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1428]
Ich könnte die zwar auch über 5zig einfügen, aber wenn ich die hotbar dann deaktiviere, ist das halt immernoch da

**Comment by Marco-MC** [comment]
Added `time.timeMillis` value
Added `object TIME <current time in millis> <time format...>`

**Format**
![f0be6de7f1034a0f7f9bdeabc52b7e6a](https://user-images.githubusercontent.com/12410754/31854221-a7b74f80-b695-11e7-8e5b-10b48ae6b498.png)
![9ca0a80075ab9d5844933b0e73d6b0d7](https://user-images.githubusercontent.com/12410754/31854219-a69b54d4-b695-11e7-8c4c-db96ce6d9ca8.png)
