### ISSUE TITLE
Recode LiquidChat

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1449]

**Comment by RealFantaCoke** [comment]
Was genau willst du "Rec0de"n?

**Comment by Marco-MC** [comment]
Alles. @RealFantaCoke

**Comment by Marco-MC** [comment]
Ich habe eben komplett LiquidChat neugeschrieben und nicht so hingerotzt wie vorher.
Fehlt nur noch das das die Nachrichten verschlüsselt werden und ich muss die einzelnen Checks wieder einbauen, die gegen Name-Faking usw sind.

**Comment by Marco-MC** [comment]
**Recoded LiquidChat.**

- [ ] Packet System
- [ ] Encryption/Decryption with static key
- [ ] Improved Spam Protection
