### ISSUE TITLE
Credits Menu

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1451]

**Comment by RealFantaCoke** [comment]
Wozu braucht man so einen unnötigen Mist?
Kann man das ganze nicht einfach (wenn schon nötig) in das Hauptmenü zeichnen?

**Comment by SenkJu** [comment]
Dafür haben wir viel zu viele Leute, denen wir Credit geben müssen.

**Comment by WistarWolf** [comment]
Unnötig. Man kann es auch einfach auf der CCBlueX Website nachschauen.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1476
