### ISSUE TITLE
Recode Hud

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1456]
Hud zieht sobald ich es anmache 100 Fps weg, dass kann doch nicht normal sein

**Comment by FlorijonG** [comment]
JUDE!

**Comment by scorpion3013** [comment]
Neh passt. War glaube ein fehler meinerseits.

**Comment by RealFantaCoke** [comment]
> JUDE!
Hör auf mit so einem Mist!

**Comment by maxhd0** [comment]
Ne scorpion. Die FPS werden Abgezogen wenn du MCfont an hast. Sonst nicht.
