### ISSUE TITLE
Being able to bind speed separately

### ISSUE THREAD

**Issue by GeoGamerLP** [CCBlueX/LiquidBounce1.8-Issues#1460]
Currently, you can only bind the module "Speed" so you can only use one speed at the same time.

It would be useful to be able to bind the speed modes separately because on some servers, multiple speeds are working, but one is better for combat, the other one is better with chasing/works with scaffold/etc.

**Comment by TheRealDAT** [comment]
This is very good, nobody make this and its better with [speed1 and speed2]
