### ISSUE TITLE
LiquidScript if object is null

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1464]
1. Manchmal kommen solche Fehler mit der Hotbar http://prntscr.com/h3sqi8 vielleicht kann man die iwie fixen.
2. Wenn man bei der Hotbar von scorpion3013 das Datum/Zeit ganz nach rechts verschiebt, gehen die Zahlen ja aus dem Bildschirm raus wenn sie größer werden. Da die Sachen ja von Links nach Rechts gerendert werden. Kann man das irgendwie machen dass die hintere Zahl an der stelle bleibt, die vorderen aber dann nach Links verschoben werden so dass es wieder passt? Konnte es jetzt nicht besser erklären xd

**Comment by Marco-MC** [comment]
Das ist kein Bug, sondern ein Fehler des Scripts...
Während man noch nicht richtig ingame ist, versucht das Script schon die Hotbar zu drawn... bloß... exestieren die Values zu dem Zeitpunkt noch nicht...
LiquidScript hat aber auch keine Überprüfung ob etwas null ist, daher passiert so ein Fehler.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1768
