### ISSUE TITLE
NoSlow

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1469]
Dass man einstellen kann bei was NoSlow "aktiv" werden soll. (Soul Sand, Blocking, CobWeb etc)

**Comment by superblaubeere27** [comment]
Ok, wo ist da der Unterschied?

**Comment by WistarWolf** [comment]
da es server gibt auf denen z.b. noslow beim blocken bypasst aber beim über soulsand laufen nicht

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/572
