### ISSUE TITLE
inventory cleaner improvement

### ISSUE THREAD

**Issue by MrGcGamer** [CCBlueX/LiquidBounce1.8-Issues#1471]
Die Möglichkeit beim Inv cleaner sticks an und aus zuschalten.
Es ist hard anstrengend wenn du dir ein schwert machen willst und du keine sticks hast.
Wäre cool wenn ihr das added

Grüße _MrGcGamer_

**Comment by superblaubeere27** [comment]
Wie wäre es damit, dass man es komplett selbst Einstellen kann

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1393
