### ISSUE TITLE
Verschiede Modi des Regen-Hacks

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1472]
1. So lange man in der Luft ist (z.B. beim Springen, Fallen, ...) sollte Regen nicht versuchen, einen hochzuheilen, da man so zum Teil für Fly gekickt wird. Ist man dann wieder auf dem Boden, kann Regen einen ja wieder heilen.

2. Regen ist nur dann aktiv, wenn man eine gewisse Anzahl von Leben unterschreitet.

**Comment by Marco-MC** [comment]
Added health value
Added food value
Added noair value
