### ISSUE TITLE
Killaura AAC Heuristics Issue/ Bypass Request

### ISSUE THREAD

**Issue by FusionStyles** [CCBlueX/LiquidBounce1.8-Issues#1474]
Die Killaura wirft beim Kämpfen nach einer Minute kontinuierlich Heuristic Flags zwischen dem Level 2-3 ab.
Dies bannt einen z.B. auf Servern wie Gomme nach wenigen Minuten für Killaura auto.
Die oben genannten Punkte habe ich auf TestServern und auf GommeHD.net nachgewiesen.

**Comment by superblaubeere27** [comment]
Naja muss ich mal gucken

**Comment by BlackHawk2306** [comment]
wie stark sind denn die RandomRotations? Sind die evtl. nicht zufällig genug?

**Comment by FusionStyles** [comment]
Ich erkäre es jetzt mit der b29 wirklich unter Angabe des Problems.
Die Killaura autobannt nicht in Bedwars, sondern jedeglich in Spielmodi, wie QSG oder normales SG, FFA oder 1vs1. Das Problem ist hierbei die Heuristic b69 die einen nach spätestens einer QSG Runde autobannt.
Ich bin mir nicht sicher was b69 auslöst, nur das ausschließlich beim bewegen und angreifen auftritt und höchstwarscheinlich ein Problem zwischen Rotation der Killaura und dem Laufen ist. 
Ich schätze die Killaura versucht z.B. beim Springen die Rotation trotz Random zwangsweise anzupassen, was das Issue verursacht.

**Comment by Marco-MC** [comment]
Alle Heuristic Patterns bis auf "P/66 conf: 78" sind gebypasst.
Man wird durch "P/66 conf: 78" nicht gekickt, da der Flag relativ unhäufig kommt und dann auch maxinal bis vl 2 kommt.

**Comment by Marco-MC** [comment]
@superblaubeere27 und ich haben die KillAura etwas verbessert.
Sie wird nicht mehr durch **Heuristics** geflaggt (_lediglich wenn man die KillAura too hardcore einstellt xd_).
**Hitbox** Flags sind relativ selten und kommen somit nicht über vl: 2.
Natürlich kann es immer mal wieder zu einem **Heuristic** Flag kommen, das ist normal.

Dies KillAura wurden an normalen Spielern und bei Aim getestet (_poke.sexy_).
Natürlich auch auf Gomme. :3

**Comment by superblaubeere27** [comment]
Noice @Marco-MC
