### ISSUE TITLE
Player ESP für andere LB-User

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1477]
Ich dachte, vielleicht könnte man eine Option für den ESP einbauen, der z.B. andere Liquidbounce-User nicht weiß umrandet (so wie normale Spieler), nicht blau (wie Freunde), sondern z.B. rot.

**Comment by WistarWolf** [comment]
Dann könnten Gomme Mods aber einfach mit LB online kommen und alle LB user einfach erkennen und bannen. Man würde sich somit ziemlich selbst ficken.

**Comment by WistarWolf** [comment]
Dann könnten Gomme Mods aber einfach mit LB online kommen und alle LB User erkennen und bannen. Man würde sich somit ziemlich selbst ficken.

**Comment by henrydatei** [comment]
Ein Skript was versucht allen Spieler eine LCPN-Nachricht zu schicken, und dann zu schauen, ob diese ankommt, würde ja nix anderes machen. Von daher wäre es nur einfacher, User zu erkennen, aber nicht unmöglich. Trotzdem sollte man vielleicht LB-User nur anzeigen (wenn überhaupt) wenn die LC aktiviert haben.

**Comment by Marco-MC** [comment]
Wie @WistarWolf schon sagte, es würde nur die User selbst ficken.

**Comment by WistarWolf** [comment]
Ich hab mal recht. Wow
