### ISSUE TITLE
Module Commands

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1479]
Mal alle Modules durchschauen und gucken, ob man die ganzen Sachen von einem Module mit einem Command einstellen kann. (An alle die Langeweile haben xd)

**Comment by superblaubeere27** [comment]
Nein man sollte einen automatischen Module Command machen, der sich für alle Modules regristriert

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1597
