### ISSUE TITLE
LiquidScript: Value/Methode (idk xd) Back/ForegroundRendering

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1480]
Dann wird etwas halt im Hintergrund/Vordergrund gerendert. Das ist zum beispiel bei der Hotbar gut. Dann kann man die Farbe besser anpassen dass sie mit der kurzen Hotbar übereinander stimmt und dann kann man glaube ich auch diesen Bug beheben: http://prntscr.com/hbsdi3 Dass die Zahlen von den Blöcken halt nicht mehr die eine Hälfte grau und die andere weiß ist.

**Comment by Marco-MC** [comment]
Geht nicht.

**Comment by WistarWolf** [comment]
k
