### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by CrashedLife** [CCBlueX/LiquidBounce1.8-Issues#1483]
Wie wärs mit ein Button im Alt Manager oder so wo man sich mit ein Proxy einloggen kann.

**Comment by superblaubeere27** [comment]
Gute Idee, aber das soll man im Alt Dialog machen

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2009
