### ISSUE TITLE
Automatic bind

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#1484]
Ich fände es gut wenn man nicht nur `.bind step grave` machen könnte sondern auch nur `.bind step`
und es dann auf die nächste Taste gebindet wird, die man drückt

**Comment by WistarWolf** [comment]
Noch schneller würde es gehen wenn man in der ClickGUI das einstellen kann. Wie in Jigsaw.

**Comment by superblaubeere27** [comment]
Ja vlt kann man das ja auch machen

**Comment by BlackHawk2306** [comment]
Oder im GUI auf das Modul mid-clicken, und dann die Taste drücken

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1625
