### ISSUE TITLE
Fucker für Cakes

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1486]
Ist es möglich einen Fucker für Cakes (also speziell für den Spielmodus Cakewars) zu schreiben, der - wie in Bedwars das Bett - den Kuchen (den man ja in Scheiben isst) vollautomatisch abzubauen?

**Comment by superblaubeere27** [comment]
`.fucker select <Block >` da kann man einen Block auswählen

**Comment by henrydatei** [comment]
Nun gut, ich hab die Erfahrung gemacht, dass dies Probleme bereitet, da erst versucht wird den Kuchen als Block abzubauen und erst DANACH der Kuchen in Scheiben gegessen wird. Manuell bin ich da schneller, wenn ich gleich auf das "Scheiben-Essen" umsteige.
