### ISSUE TITLE
Discord died & Code Share

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#1489]
` 
//Hypixel Fast Speed

   @EventTarget
    public void onMove(EventMove event){
        if(!Helper.playerUtils().MovementInput()){
            level = 1;
            timerino.reset();
            return;
        }
 
        MovementInput movementInput = mc.thePlayer.movementInput;
        float forward = movementInput.moveForward;
        float strafe = movementInput.moveStrafe;
        float yaw = mc.thePlayer.rotationYaw;
        if ((forward == 0.0F) && (strafe == 0.0F)) {
            event.x = 0.0D;
            event.z = 0.0D;
        } else if (forward != 0.0F) {
            if (strafe >= 1.0F) {
                yaw += (forward > 0.0F ? -45 : 45);
                strafe = 0.0F;
            } else if (strafe <= -1.0F) {
                yaw += (forward > 0.0F ? 45 : -45);
                strafe = 0.0F;
            }
            if (forward > 0.0F)
                forward = 1.0F;
            else if (forward < 0.0F)
                forward = -1.0F;
        }
        double mx = Math.cos(Math.toRadians(yaw + 90.0F));
        double mz = Math.sin(Math.toRadians(yaw + 90.0F));
        
        if(mode.value.equals(speedMode.NEWHOP)){
            EventMove em = (EventMove)event;
    //        mc.timer.timerSpeed = 1.085F;
            if (mc.thePlayer.moveForward == 0.0F && mc.thePlayer.moveStrafing == 0.0F) {
               this.moveSpeed = getBaseMoveSpeed();
            }
              

            
            
            if (stage == 1 && mc.thePlayer.isCollidedVertically && (mc.thePlayer.moveForward != 0.0F || mc.thePlayer.moveStrafing != 0.0F)) {
               this.moveSpeed = 1.35D + getBaseMoveSpeed() - 0.01D;
            }

            if (stage != 2 || !mc.thePlayer.isCollidedVertically || mc.thePlayer.moveForward == 0.0F && mc.thePlayer.moveStrafing == 0.0F) {
               if (stage == 3) {
                  forward = (float) (0.66D * (this.lastDist - getBaseMoveSpeed()));
                  this.moveSpeed = this.lastDist - forward;
               } else {
                  List collidingList = mc.theWorld.getCollidingBoundingBoxes(mc.thePlayer, mc.thePlayer.boundingBox.offset(0.0D, mc.thePlayer.motionY, 0.0D));
                  if ((collidingList.size() > 0 || mc.thePlayer.isCollidedVertically) && stage > 0) {
                     stage = mc.thePlayer.moveForward == 0.0F && mc.thePlayer.moveStrafing == 0.0F ? 0 : 1;
                  }

                  this.moveSpeed = this.lastDist - this.lastDist / 159.0D;
               }
            } else {
               em.setMotionY(mc.thePlayer.motionY = 0.4D);
               this.moveSpeed *= 1.533D;
            }

            this.moveSpeed = Math.max(this.moveSpeed, getBaseMoveSpeed());
            if (stage > 0) {
               forward = (float)mc.thePlayer.movementInput.moveForward;
               strafe = (float)mc.thePlayer.movementInput.moveStrafe;
               yaw = mc.thePlayer.rotationYaw;
               if (forward == 0.0D && strafe == 0.0D) {
                  em.setMotionX(0.0D);
                  em.setMotionZ(0.0D);
               } else {
                  if (forward != 0.0D) {
                     if (strafe > 0.0D) {
                        yaw += (float)(forward > 0.0D ? -45 : 45);
                     } else if (strafe < 0.0D) {
                        yaw += (float)(forward > 0.0D ? 45 : -45);
                     }

                     strafe = (float) 0.0D;
                     if (forward > 0.0D) {
                        forward = (float) 1.0D;
                     } else if (forward < 0.0D) {
                        forward = (float) -1.0D;
                     }
                  }

                  em.setMotionX(forward * this.moveSpeed * Math.cos(Math.toRadians((double)(yaw + 90.0F))) + strafe * this.moveSpeed * Math.sin(Math.toRadians((double)(yaw + 90.0F))));
                  em.setMotionZ(forward * this.moveSpeed * Math.sin(Math.toRadians((double)(yaw + 90.0F))) - strafe * this.moveSpeed * Math.cos(Math.toRadians((double)(yaw + 90.0F))));
               }
            }

            if (mc.thePlayer.moveForward != 0.0F || mc.thePlayer.moveStrafing != 0.0F) {
               ++stage;
            }	
        }
}}}}

    private double getBaseMoveSpeed() {
        double baseSpeed = 0.2873;
        if (mc.thePlayer.isPotionActive(Potion.moveSpeed)) {
            final int amplifier = mc.thePlayer.getActivePotionEffect(Potion.moveSpeed).getAmplifier();
            baseSpeed *= 1.0 + 0.2 * (amplifier + 1);
        }
        return baseSpeed;
    }

    @EventTarget
    public void onPre(EventPreMotionUpdates e){
    	if(mc.thePlayer.isEating()){
           }

        double xDist = mc.thePlayer.posX - mc.thePlayer.prevPosX, zDist = mc.thePlayer.posZ - mc.thePlayer.prevPosZ;
        lastDist = Math.sqrt(xDist * xDist + zDist * zDist);
        if(sanik.value)
            delay1++;
        if (canSpeed() && sanik.value)
            delay2++;
        if(!canSpeed()){
            delay2 = -2;
            Timer.timerSpeed = 1.0F;
        }
      

        
        if (mode.value.equals(speedMode.NEWHOP)){
            if(mc.thePlayer.onGround){
            	mc.timer.timerSpeed = 1.55f;
            }else{
            	mc.timer.timerSpeed = 1.07f;
            }
            
           double forward = mc.thePlayer.posX - mc.thePlayer.prevPosX;
           double strafe = mc.thePlayer.posZ - mc.thePlayer.prevPosZ;
           this.lastDist = Math.sqrt(forward * forward + strafe * strafe);
       }
}
}
}
}
`

**Comment by superblaubeere27** [comment]
Ok I will try it

**Comment by superblaubeere27** [comment]
I formatted it
```java
//Hypixel Fast Speed

@eventtarget
public void onMove(EventMove event) {
	if (!Helper.playerUtils().MovementInput()) {
		level = 1;
		timerino.reset();
		return;
	}

	MovementInput movementInput = mc.thePlayer.movementInput;
	float forward = movementInput.moveForward;
	float strafe = movementInput.moveStrafe;
	float yaw = mc.thePlayer.rotationYaw;
	if ((forward == 0.0 F) && (strafe == 0.0 F)) {
		event.x = 0.0 D;
		event.z = 0.0 D;
	} else if (forward != 0.0 F) {
		if (strafe >= 1.0 F) {
			yaw += (forward > 0.0 F ? -45 : 45);
			strafe = 0.0 F;
		} else if (strafe <= -1.0 F) {
			yaw += (forward > 0.0 F ? 45 : -45);
			strafe = 0.0 F;
		}
		if (forward > 0.0 F) forward = 1.0 F;
		else if (forward < 0.0 F) forward = -1.0 F;
	}
	double mx = Math.cos(Math.toRadians(yaw + 90.0 F));
	double mz = Math.sin(Math.toRadians(yaw + 90.0 F));

	if (mode.value.equals(speedMode.NEWHOP)) {
		EventMove em = (EventMove) event;
		//        mc.timer.timerSpeed = 1.085F;
		if (mc.thePlayer.moveForward == 0.0 F && mc.thePlayer.moveStrafing == 0.0 F) {
			this.moveSpeed = getBaseMoveSpeed();
		}

		if (stage == 1 && mc.thePlayer.isCollidedVertically && (mc.thePlayer.moveForward != 0.0 F || mc.thePlayer.moveStrafing != 0.0 F)) {
			this.moveSpeed = 1.35 D + getBaseMoveSpeed() - 0.01 D;
		}

		if (stage != 2 || !mc.thePlayer.isCollidedVertically || mc.thePlayer.moveForward == 0.0 F && mc.thePlayer.moveStrafing == 0.0 F) {
			if (stage == 3) {
				forward = (float)(0.66 D * (this.lastDist - getBaseMoveSpeed()));
				this.moveSpeed = this.lastDist - forward;
			} else {
				List collidingList = mc.theWorld.getCollidingBoundingBoxes(mc.thePlayer, mc.thePlayer.boundingBox.offset(0.0 D, mc.thePlayer.motionY, 0.0 D));
				if ((collidingList.size() > 0 || mc.thePlayer.isCollidedVertically) && stage > 0) {
					stage = mc.thePlayer.moveForward == 0.0 F && mc.thePlayer.moveStrafing == 0.0 F ? 0 : 1;
				}

				this.moveSpeed = this.lastDist - this.lastDist / 159.0 D;
			}
		} else {
			em.setMotionY(mc.thePlayer.motionY = 0.4 D);
			this.moveSpeed *= 1.533 D;
		}

		this.moveSpeed = Math.max(this.moveSpeed, getBaseMoveSpeed());
		if (stage > 0) {
			forward = (float) mc.thePlayer.movementInput.moveForward;
			strafe = (float) mc.thePlayer.movementInput.moveStrafe;
			yaw = mc.thePlayer.rotationYaw;
			if (forward == 0.0 D && strafe == 0.0 D) {
				em.setMotionX(0.0 D);
				em.setMotionZ(0.0 D);
			} else {
				if (forward != 0.0 D) {
					if (strafe > 0.0 D) {
						yaw += (float)(forward > 0.0 D ? -45 : 45);
					} else if (strafe < 0.0 D) {
						yaw += (float)(forward > 0.0 D ? 45 : -45);
					}

					strafe = (float) 0.0 D;
					if (forward > 0.0 D) {
						forward = (float) 1.0 D;
					} else if (forward < 0.0 D) {
						forward = (float) - 1.0 D;
					}
				}

				em.setMotionX(forward * this.moveSpeed * Math.cos(Math.toRadians((double)(yaw + 90.0 F))) + strafe * this.moveSpeed * Math.sin(Math.toRadians((double)(yaw + 90.0 F))));
				em.setMotionZ(forward * this.moveSpeed * Math.sin(Math.toRadians((double)(yaw + 90.0 F))) - strafe * this.moveSpeed * Math.cos(Math.toRadians((double)(yaw + 90.0 F))));
			}
		}

		if (mc.thePlayer.moveForward != 0.0 F || mc.thePlayer.moveStrafing != 0.0 F) {++stage;
		}
	}
}

private double getBaseMoveSpeed() {
	double baseSpeed = 0.2873;
	if (mc.thePlayer.isPotionActive(Potion.moveSpeed)) {
		final int amplifier = mc.thePlayer.getActivePotionEffect(Potion.moveSpeed).getAmplifier();
		baseSpeed *= 1.0 + 0.2 * (amplifier + 1);
	}
	return baseSpeed;
}

@EventTarget
public void onPre(EventPreMotionUpdates e) {
	if (mc.thePlayer.isEating()) {}

	double xDist = mc.thePlayer.posX - mc.thePlayer.prevPosX,
	zDist = mc.thePlayer.posZ - mc.thePlayer.prevPosZ;
	lastDist = Math.sqrt(xDist * xDist + zDist * zDist);
	if (sanik.value) delay1++;
	if (canSpeed() && sanik.value) delay2++;
	if (!canSpeed()) {
		delay2 = -2;
		Timer.timerSpeed = 1.0 F;
	}

	if (mode.value.equals(speedMode.NEWHOP)) {
		if (mc.thePlayer.onGround) {
			mc.timer.timerSpeed = 1.55 f;
		} else {
			mc.timer.timerSpeed = 1.07 f;
		}

		double forward = mc.thePlayer.posX - mc.thePlayer.prevPosX;
		double strafe = mc.thePlayer.posZ - mc.thePlayer.prevPosZ;
		this.lastDist = Math.sqrt(forward * forward + strafe * strafe);
	}
}```

**Comment by superblaubeere27** [comment]
What is `canSpeed()`?

**Comment by superblaubeere27** [comment]
@Marco-MC I will integrate it into the Bypass client and send you the Module

**Comment by Marco-MC** [comment]
That looks like copy paste from a decompiler...

Like. `if ((forward == 0.0F) && (strafe == 0.0F)) {`
