### ISSUE TITLE
Skinchanger(Player Skin)

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1497]
Das man Ingame seinen Skin mit screenshot auf desktop oder url zu einem screenshot wechseln kann client sided und server sided(wenn möglich),

**Comment by scorpion3013** [comment]
Clientsided gibt es eine mod dafür: SkinChanger 2.0

**Comment by superblaubeere27** [comment]
Ok nutz den LiquidLauncher https://ci.liquidbounce.net/job/LiquidLauncher/

**Comment by Faabyy** [comment]
can u give me that mod?

**Comment by Faabyy** [comment]
> Clientsided gibt es eine mod dafür: SkinChanger 2.0
> 

kannst du den schicken?
