### ISSUE TITLE
Add TimeChanger and EnchantEffect

### ISSUE THREAD

**Issue by BlackHawk2306** [CCBlueX/LiquidBounce1.8-Issues#1510]
Please add an option with a slider to change the time clientside, like in Lyvell or Flux.

Also, a module to change the EnchantEffect color like in Flux with RGB sliders would be nice.

And: Thx for making a good client, that I still love to use, even though I own good paid clients. <3

**Comment by scorpion3013** [comment]
Just install the TimeChanger  mod. For Timechanger
Just install the GlintColorizer mod. For the EnchantEffect

**Comment by scorpion3013** [comment]
https://2pi.pw/mods/timechanger Made by Fyu, Ported by 2Pi
http://www.mediafire.com/file/z2lq3lqupl3zxz1/%5B1.8.9%5D+GlintColorizer+-+1.0.jar Made by powns

**Comment by BlackHawk2306** [comment]
Danke. Und gut, das du beim 2. (nur) die Source verlinkt hast xD (ist nicht schlimm, kann man googlen, oder selbst compilen)

**Comment by scorpion3013** [comment]
Bei beiden ist die .jar dabei o.O

**Comment by BlackHawk2306** [comment]
![screenshot 320](https://user-images.githubusercontent.com/17730120/33665588-ba8b3056-da97-11e7-868a-489f47e3b1a4.png)
![screenshot 321](https://user-images.githubusercontent.com/17730120/33665590-bd81c68a-da97-11e7-94b3-56e448f22e49.png)

sieht ganz so aus xD

**Comment by BlackHawk2306** [comment]
mir ist grad aufgefallen, das Java decompiler + Eclipse gleichzeitig aufgaben übelst nach skidden aus sieht xDD

**Comment by scorpion3013** [comment]
Ahh... das wurde bei dir als .jar.zip runtergeladen, einfach .zip wegmachen

**Comment by BlackHawk2306** [comment]
ik
