### ISSUE TITLE
HUD Designer

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1513]
Eine Möglichkeit um Elemente vom HUD anders zu Positionieren und ggf. die Arraylist anders zu sortieren.
Bei der Watermark nur vorher festgelegte Positionen zulassen um das ausblenden dieser zu verhindern. ( Wegen Leuten wie z.b. DPHacks)

**Comment by WistarWolf** [comment]
HAHAHAHHA du glaubst echt dass marco das einbaut

**Comment by WistarWolf** [comment]
Ohaaa. Marco was ist zurzeit mit dir los? Du machst LB zum besten Client. So kenn ich dich garnicht dass du so viel zum Thema design machst.

**Comment by WistarWolf** [comment]
neija. Vorher festgelegt. Man kann es ja so machen dass man die Watermark schon verschieben kann, aber man nichts über die WaterMark machen kann. Sodass diese immer sichtbar ist.

**Comment by Marco-MC** [comment]
Okay, nun...
Wie siehst mit CustomHUD aus... joa... ich bin relativ zufrieden so von der Art, Code technisch... überhaupt nicht da muss ich noch nachbessern und was jetzt noch fehlt ist das die scheiße gespeichert und geladen wird. Vllt auch noch paar mehr Options, weiß aber noch nicht ob ich das lieber verschiebe.

**Comment by WistarWolf** [comment]
Lass dir Zeit mit CustomHUD. Solange sie gut wird kann es ruhig dauern.

**Comment by RealFantaCoke** [comment]
Hätte nicht gedacht, dass Marco so etwas hinzufügen wird ... (!)

Gute Arbeit (bisher) @Marco-MC :+1:

**Comment by Marco-MC** [comment]
Ich bin sozusagen fertig.
Sachen wie eigene Rechts usw werde ich denke erst in den späteren Versionen hinzufügen.

Problem was mir sich jetzt noch stellt ist... Wo soll ich den CustomHUD Open dings bums hinpacken... habs halt derzeit in dem HUD Module als boolean value drin sobald man diesen drückt/changed öffnet sich halt das CustomHUD...

**Comment by WistarWolf** [comment]
rechts? Neija egal. Das mit den Rects kann auch irgendwann später hinzugefügt werden, hauptsache es kommt irgendwann. Meinst du jetzt wie du den Button für den HUD designer machst, oder was man hinzufügen kann, dass sich der hud designer öffnet?

**Comment by WistarWolf** [comment]
Eine Idee wäre es auch CustomHUD als Module wie ClickGUI zu machen, aber ich persönlich fände es schöner wenn es eine art Button unten rechts/links in der clickgui gäbe
