### ISSUE TITLE
Alt Manager request

### ISSUE THREAD

**Issue by yKsenomorf** [CCBlueX/LiquidBounce1.8-Issues#1514]
- Add "Last Login" button, which is logging in in last successfull login ( ͡° ͜ʖ ͡°)
- Add "Clipboard Login" button, which is logging in alt, located in the clipboard (for example: h@gmail.com:228)

_ye_

**Comment by superblaubeere27** [comment]
Use the LiquidLauncher https://ci.liquidbounce.net/job/LiquidLauncher/

**Comment by superblaubeere27** [comment]
The Last Login feature will be added in 1.3 release
