### ISSUE TITLE
Cs go clickgui

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1517]
like skeet PLS

**Comment by WistarWolf** [comment]
Junge... Du glaubst echt dass Marco der Fettsack das einbaut

**Comment by Bircko** [comment]
exhibition ist unobf leaked der hat skeet gui einfach pasten

**Comment by WistarWolf** [comment]
Marco baut nichts ein wenn es um Design geht bzw es ist SEHR schwer in von etwas zu überzeugen. Auch wenn es noch so einfach ist.

**Comment by LAUCHTINTE337** [comment]
Irgendwie verständlich der Client ist nicht da um einen Client schönheitswettbewerb zu gewinnen sondern um legits zu zerquetschen

**Comment by WistarWolf** [comment]
Ja aber es gibt halt Leute die auch sehr aufs Design eines Clients achten und dort auch viel einstellen möchten. (Ich z.b.)

**Comment by LAUCHTINTE337** [comment]
Das ist natürlich schön aber darum finde ich sollte man sich als letztes kümmern
