### ISSUE TITLE
Besserer Tp hit

### ISSUE THREAD

**Issue by LAUCHTINTE337** [CCBlueX/LiquidBounce1.8-Issues#1519]
Ich weiss zwar nicht warum aber in der b29 flaggt der tp hit ab und zu könnt ihr versuchen das zu verbessern vlt auch ihne diese hüpferei beim hit wäre ganz nice

**Comment by WistarWolf** [comment]
und dass der TP Hit wie in Skash anzeigt wann man einen Spieler schlagen kann und wann nicht

**Comment by LAUCHTINTE337** [comment]
Ja genau das wünsch ich mir auch

**Comment by superblaubeere27** [comment]
Sry, aber das kann nicht nicht flaggen

**Comment by LAUCHTINTE337** [comment]
Ich glaube ich habe flaggen etwas falsch ausgedrückt ich meine damit das man oft z.b. auf minesucht ffa oder hive und sogar auf dem alten aac 1.9.10 beim tp hitten nach vorne in die luft gezogen wird oder falldamage bekommt oder einfach vom aac erkannt wird und folgende allseits bekannte nachricht bekommt ich Zitiere: it's might you are glitching please tap sneak and block with your sword oder so ähnlich.

**Comment by LAUCHTINTE337** [comment]
L
