### ISSUE TITLE
PLEASE FIX!!!!!! Autoclicker is right click and left click

### ISSUE THREAD

**Issue by OFPDEV** [CCBlueX/LiquidBounce1.8-Issues#1520]
If autoclicker is toggled, it autoclicks for right click and left click.  Give option for only left click, only right click, and both.

Example:
Autoclicker 》 Mode 》 Left Click Only
Autoclicker 》 Mode 》 Right Click Only
Autoclicker 》 Mode 》 Both Click

**Comment by OFPDEV** [comment]
PLEASE FIX!!!!! me really want this

**Comment by WistarWolf** [comment]
yeeee

**Comment by Bircko** [comment]
fix your english!

**Comment by Marco-MC** [comment]
Added
