### ISSUE TITLE
LiquidLauncher 1.3

### ISSUE THREAD

**Issue by TMLetsPlays** [CCBlueX/LiquidBounce1.8-Issues#1522]
Der LiquidLauncher v1.3 speichert soweit ich das Probiert habe weder Alts, welche zuvor Importiert wurden, noch File Management Einstellungen, also welche Ordner man ausgewählt hat.
Ausserdem kommt bei jeden Start das Feld mit dem YouTube Link zum Release Video,

Sprich der Launcher speichert keine eigenen Einstellungen sondern setzt sich jedes mal vor dem neuen Ausführen zurück.

**Comment by superblaubeere27** [comment]
Da ich das wundervolle Plugin "Find Bugs" für Intellij IDEA gefunden habe, wurden 90% der bugs gefixt
