### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by TMLetsPlays** [CCBlueX/LiquidBounce1.8-Issues#1523]
Wäre gut wenn ihr ein NoXP Module einbauen könntet, welches die XP Leiste Ausblendet.
Danke.

TM aka xCoder

**Comment by WistarWolf** [comment]
Unnötig. (ich hab nur grad Marco und Senk Ju nachgemacht. c:)

**Comment by superblaubeere27** [comment]
Unnötig ich hab nur @WistarWolf nachgrmacht ^^

**Comment by superblaubeere27** [comment]
Nein es ist wirklich so, brauch man nicht

**Comment by WistarWolf** [comment]
xd
