### ISSUE TITLE
More fastbow modes

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1525]
- Double shot (If you shoot with the bow it will shoot twice)
- Single tap (It will shoot instantly ONE arrow)
- Normal mode but with changeable speed

**Comment by superblaubeere27** [comment]
Why?

**Comment by scorpion3013** [comment]
Es gibt silents ac's die sowas wie Instantshoot(Single tap) nicht detecten sondern erst wenns gespammt wird.

**Comment by BlackHawk2306** [comment]
Dieses Meme namens GWEN z.B.?

**Comment by Teals53** [comment]
Like BowSpam
