### ISSUE TITLE
Pathfinder für Labyrinthe

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1526]
So wie es das Modul mal vor Ewigkeiten in Wurst gab bzw. noch gibt, wäre es schön, wenn man die Zielkoordinaten eingeben könnte und LB zeigt einem den Weg dorthin. Wäre ganz nützlich für Labyrinthe.

**Comment by scorpion3013** [comment]
+1

**Comment by Marco-MC** [comment]
Ja, kann ich machen. Hatte mal nen a* algorithmus für 2D gemacht... kann den vllt mal umbauen auf 3D.
