### ISSUE TITLE
Dead command

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1539]
Führt im oment des sterbens einen ausgewählten command aus. Z.b. /sethome für Factions server sehr nützlich.

**Comment by scorpion3013** [comment]
Wieso wurd das closed ? Was spricht dagegen ?

**Comment by superblaubeere27** [comment]
Unnötig

**Comment by scorpion3013** [comment]
Wo ist das bitte unnötig ?
Factions beispiel -> Du machst /sethome an deinen Todesort = Kannst direkt wieder hin.
Factions beispiel2 -> Du machst /heal und hast somit den KeepAlive effekt.
Minigames -> Du machst /hub sobald du stirbst = Musst nicht extra leaven
Kitpvp -> Du hast instant wieder ein kit ohne was schreiben zu müssen
Normalen beispiel -> Du hast schreibst als Nachricht "Huresohn" sobald du stirbst.

Also im vergleich zum Snowfly ist das "(Snowflynötigkeit +  1) * 88 = Dead command nötigkeit"
( Die "+ 1" damit es nicht 0 ist)
