### ISSUE TITLE
ESP Color

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1540]
- raibow mode
- healthmode ( esp is green when health is full, if the health get lower -> esp is turnig red)
- normal mode (the current one but with changeable color )
- team mode (color of the team)

**Comment by WistarWolf** [comment]
Du glaubst echt das Marco sowas einbaut? HAHAHHAHAHA. Träum weiter

**Comment by Marco-MC** [comment]
Ja, kann ich machen.

**Comment by Marco-MC** [comment]
Nacher oder so

**Comment by WistarWolf** [comment]
....

**Comment by WistarWolf** [comment]
Ich glaub der fettsack hat dezent was gegen mich.

**Comment by BlackHawk2306** [comment]
Wundert dich das etwa? Kappaklaus Nikolaus

**Comment by Marco-MC** [comment]
Added
