### ISSUE TITLE
knockobacks velocity broke

### ISSUE THREAD

**Issue by unwit** [CCBlueX/LiquidBounce1.8-Issues#1545]
fix knockobacks velocity MODule. can not set take only 90 percentage of normal knockobacks velocity.  alway take about 0 knockobacks velocity.

sory for baad english SEIN is still in school.

**Comment by scorpion3013** [comment]
German is allowed here too if you are a german,
You need to set the velocity mode to "simple" and 
put vertical and horizontal to 0.9.
