### ISSUE TITLE
Switch Killaura

### ISSUE THREAD

**Issue by LoYungSum** [CCBlueX/LiquidBounce1.8-Issues#1546]
![image](https://user-images.githubusercontent.com/25066078/34370491-6e5c64e8-eaff-11e7-8034-4244f9044d62.png)

Switchaura not fully bypassing.

Also, I cannot login to "test.ccbluex.net"

**Comment by SenkJu** [comment]
Show me your settings.

**Comment by leumasme** [comment]
![image](https://user-images.githubusercontent.com/29953391/34389915-b0380b46-eb3c-11e7-8231-07a34a9eef06.png)
