### ISSUE TITLE
Rotations in F5 sichtbar machen

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1548]
Siehe Titel

(Senk Ju, Marco sagte im Stream er hätte sowas vor, dass hier dient als Errinerung)

**Comment by SenkJu** [comment]
Das ist schwul. Hatten das schon mal im client. Fuckt ab

**Comment by scorpion3013** [comment]
Kann man ja als Modul machen...

**Comment by WisaWolf2** [comment]
oder als HUD Option

**Comment by Mauzikuk** [comment]
Ja als setting. Wäre sick
