### ISSUE TITLE
LiquidScript: ShowArray

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1549]
Dass man am Anfang eines Modules schreiben kann, ob es in der ArrayList angezeigt werden soll oder nicht.

**Comment by scorpion3013** [comment]
Und ob errors angezeigt werden sollen oder nicht

**Comment by WistarWolf** [comment]
das kann marco ja bei hud einfügen. "LS Errors"

**Comment by WistarWolf** [comment]
Als option

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1768
