### ISSUE TITLE
More HUD settings

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1550]
WaterMark: Eigene Farbe oder Rainbow 
ArrayList: Random Farben, Eigene Farbe, Rainbow, LeftRect, RightRect oder Nichts und einstellbare Hintergrund stärke
TabGUI: Den Text Rechts, links oder Mittig und diese ">" aktivierbar und deaktivierbar, die TabGUI soll umrandet werden mit der gleichen Farbe wie die ausgewählte TabGUI Kategory

Oder einfach ein CustomHUD Designer

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1513
