### ISSUE TITLE
Xray Bypass Mode（With image&code）

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#1555]
Just see surface
Works on AntiXray default Settings(Hypixel UHC)
net.minecraft.block.block
shouldSideBeRendered()
https://ghostbin.com/paste/o5srq

**Comment by CrackFileso** [comment]
http://prntscr.com/hupqll

**Comment by Teals53** [comment]
why closed ? its fake ?

**Comment by Teals53** [comment]
.....
