### ISSUE TITLE
BlockOverlay Info option

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1559]
Wenn man diese Option aktiviert steht über deinem Fadenkreuz der Block und die ID von dem Block auf dem du grad schaust.

**Comment by Marco-MC** [comment]
![07856daa7eecd05b940f066c2074f7d2](https://user-images.githubusercontent.com/12410754/34453891-c6fbbeb2-ed5e-11e7-9906-5ad879225eb2.png)
