### ISSUE TITLE
More spammer messages

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#156]
Das man so 5-10 Spammer Messages einrichten kann.
.spammer message1 HHA
.spammer message2 hhwhuuh
Und so weiter. Und dann auch ein Random Mode. Wenn der aktiviert ist werden die Nachrichten Random in den Chat geschrieben und wenn er deaktiviert ist werden die Nachrichten in der Reihenfolge in den Chat geschrieben in der man sie auch eingetragen hat.

**Comment by Marco-MC** [comment]
Ja... idk. Muss ich schauen ob ich das umsetzen kann.

**Comment by Brotgeschmack** [comment]
Sollte nicht so schwer sein (switch)

**Comment by Marco-MC** [comment]
Ja, ist auch nicht...
Nur kommt das mit meinem Value System nicht so. Müsste mein ValueSystem erweitern, was aber auch eigentlich nicht schwer ist nur weiß ich nicht ob gson HashMaps abspeichern kann.
Naja, maps brauch ich nicht mal...
Ich könnte auch einfach ne List machen wo dann:

[
"1:hallo",
"2:hallowelt"
]

und dann mit sort das sortieren lassen.
Ich habe nämlich die Erfahrung das GSON Listen einfach komplett durch einander lädt...
Zum Beispiel muss ich das bei meinem Launcher machen, weil er das einfach komplett unsortiert lädt. :)
Ich habe genug Ideen wie man das umsetzen kann. xd
Ich war bisher nur zu faul das überhaupt zu machen. 💺
