### ISSUE TITLE
Aimassist, Aimbot, Autoclicker, Reach, Wtap, Tracers, Radar

### ISSUE THREAD

**Issue by HalfMoon0609** [CCBlueX/LiquidBounce1.8-Issues#1566]
Aimassist, Aimbot  : FOV, speed of vertical, and horizontal, team
Autoclicker : jitterclick
(Plz add) Reach : minium, maxium reach
Wtap
Tracers : more red when the player is closer
Radar GUI
It would be great if this request is accepted. Thx

-

**Comment by BlackHawk2306** [comment]
LiquidBounce is not a ghost client, and what you request for, looks like you need better stats on your main account ;)
The tracers idea, or the comeback of a reach module is not bad though imo

**Comment by Marco-MC** [comment]
AutoClicker jitterclick: https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1542
