### ISSUE TITLE
Settings in TabGUI

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1567]
Man soll optionen von Modulen auch über die TabGUI ändern können. Dann ist zwar das problem mit den vielen speed modes, aber man könnte es ja machen dass es bis zu einem bestimmten punkt angezeigt wird und man dann sozusagen "scrollt".

**Comment by WistarWolf** [comment]
Achja und wenn man dann halt diese Pfeile aktiviert hat, werden die neben den Modules/Settings in der TabGUI bei denen man was einstellen kann angezeigt

**Comment by RealFantaCoke** [comment]
Wäre langsam echt mal hilfreich, so gut wie jeder Client hat es mittlerweile und der führende Free-Client LiquidBounce nicht ...

**Comment by superblaubeere27** [comment]
Durch die AutoCompletion geht das im Chat schneller

**Comment by RealFantaCoke** [comment]
Die Auto Completion vom Client wird aber von manchen AntiCheats mittlerweile erkannt.

Bspw. ThotPatrol

Daher wäre es mehr als sinnvoll, etwas anderes als Alternative einzubauen.

**Comment by Navex** [comment]
Wie zur Hölle soll das von einem Anticheat erkannt werden?

**Comment by RealFantaCoke** [comment]
> Wie zur Hölle soll das von einem Anticheat erkannt werden?

Ich weiß es nicht, wie genau.
Pack dir ThotPatrol einfach mal bspw. auf einen lokalen TestServer.

Ich habe es am Anfang auch nicht geglaubt, dass so etwas möglich ist.
