### ISSUE TITLE
ClickGUI Themes and Tablist Settings 

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#157]
Mehr ClickGUI Themes. z.B. Themes die an die ClickGUI von Ambien und Suicide angelehnt sind.
Und das man über die Tablist auch die ganzen Module einstellen kann. Nachrichten und so kann man nicht verändern aber so Sachen wie die Killaura range, die Bypasses von Speed und Fly etc
Und in der TabGUI hinter den Category einen blauen Strich. So wie z.B. in Amera

**Comment by FlorijonG** [comment]
oder die man mit den Script System machen
