### ISSUE TITLE
2 Block Speed

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1573]
Wenn man in einem 2 Blöcke hohem gang steht und rennt und springt, ist man ja schneller. Und mit dem Speed soll man nach und nach schneller werden wenn man unter diese blöcke läuft

**Comment by gitLukkyz** [comment]
you have stage 5 gay

**Comment by WistarWolf** [comment]
kys xd

**Comment by WisaWolf2** [comment]
oke ne. Please close this.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1592
