### ISSUE TITLE
Playermodel

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1574]
Man soll einstellen können um wie viel Grad sich das Playermodel dreht. z.b. wenn er sich nur zu 90 Grad drehen soll, dreht er sich 90 Grad nach links und rechts. Und bei 0 dreht er sich garnicht. Man Kann es bis zu 180 grad einstellen.

**Comment by WistarWolf** [comment]
Und man soll auch die größe des playermodels einstellen können.

**Comment by Marco-MC** [comment]
Größe kann man mit CustomHUD in zukunft.

**Comment by WistarWolf** [comment]
Könntest du das drehen des PlayerModels deaktivieren? Ich meine was bringt das?

**Comment by WistarWolf** [comment]
Außerdem sieht es besser aus wenn er sicht nicht dreht. Zumindest wenn das playermodel kleine ist. Und wenn es sich schon dreht, dann schon um 360 Grad
