### ISSUE TITLE
Derp Mode

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1576]
Change: Spin mode (Im moment Random Pitch ändern zum Momentaten Pitch die man auch clientside hat)

Add: Reverse (Guckt immer in die entgegengesetzte Richtung in die man in echt guckt)
        Down ( Guckt Permanent runter, sollte mit spin Kompatibel gemacht sein)

**Comment by BlackHawk2306** [comment]
Warum? xD
