### ISSUE TITLE
KillAura

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1577]
http://prntscr.com/hurcqu Man soll die Range bis 8.0 einstellen können.
FailRate bis zu 100
TurnSpeed bis 180
und FOV bis zu 180

Ich weiß dass das schon geht, aber das geht nur mit Commands.

**Comment by Marco-MC** [comment]
Kann man.

**Comment by WistarWolf** [comment]
Bei mir geht das nicht

**Comment by Marco-MC** [comment]
Du musst auch richtig zum Ende gehen... .-.

**Comment by WistarWolf** [comment]
hab ich

**Comment by superblaubeere27** [comment]
Dann mach 
```
.killaura <key> <value>
```

**Comment by WistarWolf** [comment]
1. ich hab doch geschreiben es soll auch ohne gehen. und
2. Es geht nur bei größe 0.7 und 0.9-20 bei 0.8 geht es nur nicht.

**Comment by Marco-MC** [comment]
Du bist nur zu behindert dafür, junge. Bei jedem geht es nur bei dir nicht, was ist dein scheiß problem.
