### ISSUE TITLE
SnowFly

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#1578]
I made a video about this on my channel

**Comment by BlackHawk2306** [comment]
Good work, but what is the point in it?

**Comment by superblaubeere27** [comment]
What?

**Comment by Marco-MC** [comment]
@superblaubeere27 JUNGE LERN ENGLISH
@BlackHawk2306 SnowFly allows you to hover over snow... I don't know why he want to add this shit...

**Comment by Marco-MC** [comment]
Added

**Comment by superblaubeere27** [comment]
Danke
