### ISSUE TITLE
Bypass forge check

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#158]
Some servers have a Forge check as anti-cheat.
So many Hack clients but Ghost client (Forge) can't join.

**Comment by Marco-MC** [comment]
What do you mean?

**Comment by RealFantaCoke** [comment]
If you connect to "twerion.net", you will see what he mean.

**Comment by CrackFileso** [comment]
?

**Comment by CrackFileso** [comment]
Yes.@RealFantaCoke

**Comment by Marco-MC** [comment]
???????????????????????????? xd

**Comment by Marco-MC** [comment]
I know now, what do you mean... No. LiquidBounce isn't a forge application. LiquidBounce is only a modified version of minecraft.
