### ISSUE TITLE
Importierbare Fonts / Add Arial and MotorBlock font

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1581]
Wenn man die Roboto Font nicht mag, kann man ja seine eigene lieblings font importieren.

**Comment by superblaubeere27** [comment]
@WistarWolf Ich glaube marco will da nicht einbauen, da sowas eine Menge arbeit ist

**Comment by WistarWolf** [comment]
Ich weiß dass das viel Arbeit ist, aber wenn man schon ein CustomHUD einbaut, dann auch soll man auch sich das Client design wirklich selber aussuchen können und nicht an Fonts gebunden sein.

**Comment by WistarWolf** [comment]
och junge

**Comment by Marco-MC** [comment]
@superblaubeere27 trash talkt
