### ISSUE TITLE
Timolia Settings

### ISSUE THREAD

**Issue by Saotex** [CCBlueX/LiquidBounce1.8-Issues#1583]
Könntet ihr bitte Timolia Settings erstellen? Und gibt es einen Fly für Timolia?

**Comment by marcel0113** [comment]
Timolia hat ein sehr gute Anticheat.Das ist nicht so einfach

**Comment by superblaubeere27** [comment]
@marcel0113 ääähhhh nein

**Comment by BlackHawk2306** [comment]
Soweit ich weiß, gibt es aktuell sogar einen Fly-Bypass. Also scheint gut zu sein.
