### ISSUE TITLE
Minesucht cheststeal und AutoArmor.Alts not working

### ISSUE THREAD

**Issue by marcel0113** [CCBlueX/LiquidBounce1.8-Issues#1585]
Ihr müsst umbedingt was fixen.Auf minesucht funktioniert der cheststealer und AutoArmor nicht.Beim cheststealer lässt er immer viele Items über und.Autoarmor zieht die falsche Ausrüstung an.Und wenn man alts reinmachen will,dann steht da account ist not working,obwohl der geht.

**Comment by superblaubeere27** [comment]
Das mit dem Cheststealer ist absolut so gewollt. Der cheststealer nimmt unnütze Sachen nicht raus wie Rüstung, die schlechter ist als die Gradige, warum auch?
