### ISSUE TITLE
Better Colorchanger

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1587]
Something like this instead of having slider for red, green and blue.
![color](https://user-images.githubusercontent.com/29576723/34543060-5e7ac9d0-f0df-11e7-9298-57d7131901be.PNG)

**Comment by WisaWolf2** [comment]
Glaube nicht dass marco das einbaut.

**Comment by Marco-MC** [comment]
Junge, wer auch immer das geschrieben hat. (warscheinlich WistarWolf der Spast)...
Natürlich würde ich sowas machen, problem ist eher.... wie man sowas macht. Das berechnen und drawn denke ist nicht grade schwer, aber...
Wo sollte ich das bitte hin machen? Es würde in der ClickGUI einfach nicht passen.

**Comment by WistarWolf** [comment]
Was ist eigentlich dein scheiß problem? Wieso beleidigst du mich als spast hm? Sag mal. Ich hab doch nur gesagt was ich denke und wenn du damit ein problem hast dann beachte die nachricht nicht. Meine fresse. Und wetten dass wenn ich eine Anfrage gemacht hätte mit dem, wäre es nach nichtmal einer Minute geschlossen worden.

**Comment by WistarWolf** [comment]
Hm. Erst die ganze zeit die fresse aufreisen dass ich ja so ein spast bin und dann nichtmal sagen wieso ich denn einer bin.

**Comment by Marco-MC** [comment]
@WistarWolf Bei jeder scheiße sagst du: "Baut marco eh nicht ein", das ist der Grund.

**Comment by WistarWolf** [comment]
Weil ich dich einigermaßen kenne und du schon oft sachen wie sowas nicht angenommen hast.

**Comment by superblaubeere27** [comment]
Ok sowas wie den Farbhintergrund lässt sich mit Shader machen, aber die Frage ist: WARUM REICHT DIR DAS NICHT? Du kannst ja den google color chooser nehmen und damit die RGB werte ermitteln

**Comment by Bircko** [comment]
ja was gefühlt eine stunde dauert

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2659
