### ISSUE TITLE
Teams Manual Mode

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1589]
Wäre es möglich im Teams-Modul die Farbe des eigenen Teams manuell einzustellen bzw. der Killaura zu sagen: Greife nur Spieler des gelben Teams an und keine Roten, Blauen und Grünen?

**Comment by superblaubeere27** [comment]
Warum? Das msn crossteaming machen kann? Find ich unnötig

**Comment by superblaubeere27** [comment]
Warum? Das msn crossteaming machen kann? Find ich unnötig

**Comment by henrydatei** [comment]
ne, ich habe auf Mineplex den Spielmodus "Blockhunt" entdeckt. Diejenigen, die verstecken sollen, werden als unsichtbare Hünchen des Teams Gold im ESP angezeigt. Ich würde gerne die Killaura laufen lassen (Target: Animal & Invisible) und es werden automatisch alle unsichtbaren Hünchen des Teams Gold angegriffen. Aktuell muss ich die Aura immer an und aus machen, weil diese sonst alle anderen Tiere, die über die Map verteilt sind, angreift.

**Comment by henrydatei** [comment]
![2018-01-07_17 08 11](https://user-images.githubusercontent.com/31316025/34651242-eacf0dce-f3cd-11e7-9e07-5edce639c90b.png)

**Comment by Marco-MC** [comment]
Teams beachtet normalerweise auch keine Tiere, sondern nur Spieler... Muss ich dafür dann ändern.

**Comment by superblaubeere27** [comment]
Vielleicht würde das als ScriptAPI Addition Sinn machen, aber so denke ich eher nicht
