### ISSUE TITLE
Improve BufferSpeed

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1592]

**Comment by Marco-MC** [comment]
Improved

**Comment by superblaubeere27** [comment]
Was heißt improved?

**Comment by superblaubeere27** [comment]
Was heißt improved?

**Comment by Marco-MC** [comment]
Improved == Verbessert
Lern English oder benutzt Google Übersetzer.

**Comment by superblaubeere27** [comment]
.-. Ich meinte was meinst du mit verbessert bzw. was hast du verbessert?

**Comment by WistarWolf** [comment]
Also kann man jetzt StarSpeed, SnowSpeed und Slab Speed über bufferspeed "aktivieren" Hm.

**Comment by Marco-MC** [comment]
@WistarWolf Ich habe an den StairsSpeed und SlabSpeed Moduls nichts verändert.

**Comment by WistarWolf** [comment]
Okay
