### ISSUE TITLE
Rename FakeSharp to FakeCrit/Crack and move to Criticals as option

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1593]

**Comment by SenkJu** [comment]
1.) FakeSharp != FakeCrits
2.) Was wenn man Fake Partikel und echte Criticals will?

**Comment by superblaubeere27** [comment]
A: nein B: FakeSharp = Falsch scharf, es faked die Sharp particles
