### ISSUE TITLE
Colorsign

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1600]
Erlaubt es einen in Schildern § zu benutzen um in Farbe zu schreiben

Wieso ? Gut um einige Plugins die sonst Permissions brauchen um z.b. Item Schilder zu erstellen zu umgehen.

Woher ? In nem Video von "ravenje" gesehen.

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
äh.

**Comment by Marco-MC** [comment]
Die Schilder bleiben einfach unfarbig... also die colorcodes werden rausgefiltert.

**Comment by Marco-MC** [comment]
https://gyazo.com/25797f49f4434cd96c4d480a32061e77

**Comment by Marco-MC** [comment]
Sehr wahrscheinlich wurde das damals zur Force OP Sign gefixt. Ich habe alles überprüft und es wird 1zu1 mit Colorcodes an den Server geschickt.

**Comment by Marco-MC** [comment]
https://gyazo.com/c456207603417cd40ff20d358cfed4b3
https://gyazo.com/f822de9187fcbc17fa97d67228b7e4b3

**Comment by Marco-MC** [comment]
BOOOOOOOOOOOOOOOOOOOOOOOOOOM. Ich hab's dir gesagt, dass das nicht an meiner Kompetenz liegt sondern daran das es in der 1.8.9 gefixt ist, aber in der 1.8 nicht.
