### ISSUE TITLE
Friend alias rename command

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1608]
.friend rename (UserName) (newalias)
oder so in der art. sonst muss man den Freund immer entfernen und wieder adden wenn man was am alias ändern möchte

**Comment by SenkJu** [comment]
Dann mach das halt. So oft muss man einen Freund auch nicht umbenennen.

**Comment by WistarWolf** [comment]
Aber es nervt wenn man ihm ein Alias geben will, und den namen andauernd falsch schreibt und ihn immer wieder deleten muss. Und wenn man in einer runde ist, ist es noch nerviger
