### ISSUE TITLE
Discord Rich Presence 

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1612]
https://discordapp.com/rich-presence
Als beispiel Labymod
![ezuzgkj](https://user-images.githubusercontent.com/27446646/34953396-fc5de862-fa1c-11e7-889d-199036fad969.png)(Poke's Profil)

**Comment by RealFantaCoke** [comment]
Klingt nach einer sehr guten Idee.
Warte bereits sehr lange schon darauf, dass andere Anwendungen (z.B. Spotify) so etwas hinzufügen.

Wenn LiquidBounce diese Funktion implementiert hätte, wäre es schon sehr geil.

**Comment by Marco-MC** [comment]
Added
