### ISSUE TITLE
Fucker/BlockESP Tag

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1614]
Hinter dem block soll auch die id von dem block stehen. Also so ungefähr:
Fucker Bed : (ID)
BlockESP Bed : (ID)

Oder man könnte es beim HudDesigner bei der ArrayList als option machen. Entweder ohne Tags, mit tags, oder mit detaillierten tags

**Comment by Marco-MC** [comment]
nein
