### ISSUE TITLE
Improve NCP Yport(OLD)

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1621]
Den alten NCP Yport Namens "YPORT" verbessern. 

Wie ? Beim losspeeden soll er einen kleinen hüpfer machen, dass senkt die gefahr am anfang geflaggt zu werden sehr.

**Comment by superblaubeere27** [comment]
hier der code ``` if (mc.thePlayer.onGround) mc.thePlayer.jump(); else mc.thePlayer.motionY = 0.8;```

**Comment by Marco-MC** [comment]
@superblaubeere27 Bist du eigentlich doof? Manchmal frage ich mich echt wie zurückgeblieben du bist, es geht doch nicht darum. Wie man einen YPort macht, ist simpel und war sogar das erste Video auf dem CCBlueX Channel. Es ging aber darum, das der SEHRRRR SCHNELLE YPort einen kleinen sprung machen soll, damit man nicht stecken bleibt.

**Comment by Marco-MC** [comment]
Added
