### ISSUE TITLE
Client-Friends

### ISSUE THREAD

**Issue by Lolen100** [CCBlueX/LiquidBounce1.8-Issues#1624]
Könntet ihr eine Option bei **"Nametags"** machen dass **vor den Namen** der Personen die auch Liquidbounce Client benutzen **"Liquidbounce User" oder "Client User"** oder ähnliches steht. (Wie im beigefügtem Beispiel(Mit Photoshop erstellt)). So könnte man andere Hacker erkennen und mit ihnen Kooperieren. Man könnte auch ein **Modul** erstellen wo **andere User mit dem Liquidbounce Client** von der Killaura, Bow-Aimbot, u.s.w **ignoriert** werden.

![unbenannt-1](https://user-images.githubusercontent.com/35660643/35195603-fa26a020-febd-11e7-952b-edb6c4e634f9.png)

Bei dieser Idee habe ich mich vom Skid-Client inspirieren lassen.

**Comment by SenkJu** [comment]
Nein.
Und zwar ganz einfach deswegen, weil Leute wie geNAZt dann dahergehen, das Protokoll knacken und ein Plugin machen, dass automatisch alle LiquidBounce User bannt.

**Comment by Lolen100** [comment]
Und wieso hat er das bisher nicht gemacht? Ich meine der Skid Client von Ghost hat dieses Feature auch und da wird auch niemand gebannt der diese Funktion benutzt

**Comment by SenkJu** [comment]
Ich kann geNAZts Gedanken nicht lesen, aber ich vermute Mal, dass es für ihn einfacher ist, das bei einem Free Client zu patchen.

**Comment by Lolen100** [comment]
Kann schon gut sein.
