### ISSUE TITLE
BLACKHOTBAR!!!!!!!!!!!

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#1628]

**Comment by WistarWolf** [comment]
Ich weiß nicht ob du so zurück geblieben bist. Denk mal nach was man mit CUSTOMHUD machen kann. HM 
(SOllange marco das einbaut dass man auch ein label mit zeit etc und eine blackbar machen kann

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1513

Ich will auch das man farbige Rects machen kann und das mit Labels usw habe ich schon lange gemacht.

**Comment by WistarWolf** [comment]
Nice
