### ISSUE TITLE
Code Help pls

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#1630]
I want to make a Water Bucket Nofall mod
But I tried C08PacketPlayerBlockPlacement
It doesn't work
Pls help me thanks

**Comment by CrackFileso** [comment]
Video:https://www.youtube.com/watch?v=9HHWJzE4GGs

**Comment by Marco-MC** [comment]
This is not a place to ask things like this!

**Comment by CrackFileso** [comment]
ok
