### ISSUE TITLE
CustomHUD Scoreboard Options

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1631]
Also entweder die Standart option (Standart scorboard position), dann under ArrayList (Sie wird unter der arrayList gerendert) und dann custom position (Man kann die position selber auswählen, und auch auswählen in welche richtung das scoreboard geht wenn sie größer/kleiner wird. Entweder rendert die dann halt so viel nach oben wie es mehr geworden ist, oder nach unten.) Hoffe es war verständlich (besonders das letzte) Wenn es das schon gibt, dann ist ja ok

**Comment by superblaubeere27** [comment]
Marco arbeitet grad dran

**Comment by WistarWolf** [comment]
Ah achso
