### ISSUE TITLE
MCLeaks Not working

### ISSUE THREAD

**Issue by 369David369** [CCBlueX/LiquidBounce1.8-Issues#1634]
Man kann sich nicht mit einem MCLeak account einloggen.
Getestete Versionen: 29, 30
Es kommt der Fehler "An error occured! [G2]
Leut McLeaks(twitter) kommt dieser fehler wenn man einen veralteten Cleint benutzt!

**Comment by Teals53** [comment]
yes thats true

**Comment by Marco-MC** [comment]
I already contacted a MCLeaks admin

**Comment by Marco-MC** [comment]
this is not a bug of liquidbounce

**Comment by Marco-MC** [comment]
Fixed.
