### ISSUE TITLE
Update LAAC NoFall to AAC 3.3.9

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1643]

**Comment by Marco-MC** [comment]
Updated.

**Comment by superblaubeere27** [comment]
xD lass mich raten... Aus meinem video?

**Comment by Marco-MC** [comment]
Jein, ist exakt der gleiche Code wie früher nur das ich bei mc.thePlayer.onGround die Invertierung rausgenommen habe.
