### ISSUE TITLE
CustomHUD Variables

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1650]
For FPS, XYZ, Ping, date, time and username

**Comment by Marco-MC** [comment]
Ich werde einfach noch schnell %fps% und %ping% hinzufügen.

**Comment by Marco-MC** [comment]
Added

**Comment by WistarWolf** [comment]
Jo. Wäre cool wenn du datum und zeit auch adden könntest. In den nächsten versionen halt
