### ISSUE TITLE
B31 Crash the Game while starting the game

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#1651]
http://prntscr.com/i6k9oa

**Comment by CrackFileso** [comment]
Logs:

[fml-client-latest.log](https://github.com/CCBlueX/LiquidBounce1.8-Issues/files/1670684/fml-client-latest.log)

**Comment by CrackFileso** [comment]
It seems that i am using a Proxy?
But I am not

**Comment by SenkJu** [comment]
We will have a look

**Comment by Marco-MC** [comment]
Obfuscator Bug

**Comment by Marco-MC** [comment]
Fixed.
