### ISSUE TITLE
I dont even know... (b32)

### ISSUE THREAD

**Issue by koraseeq** [CCBlueX/LiquidBounce1.8-Issues#1658]
![2018-01-28_14 52 00](https://user-images.githubusercontent.com/25563700/35481767-34394cc2-043b-11e8-91db-a7f92f009ad9.png)

**Comment by SenkJu** [comment]
What is the problem?

**Comment by koraseeq** [comment]
I cant see entire pause menu

**Comment by SenkJu** [comment]
Oh, wtf. Maybe your scaling is weird. Try to set it to Normal.

**Comment by koraseeq** [comment]
same thing
![2018-01-28_15 03 24](https://user-images.githubusercontent.com/25563700/35481812-6c553264-043c-11e8-91b4-107cef8036b1.png)

**Comment by koraseeq** [comment]
first screen was on Normal, second on large

**Comment by SenkJu** [comment]
I am unable to reproduce this bug. Does it happen with vanilla as well?

**Comment by koraseeq** [comment]
still not fixed
![2018-02-06_12 00 36](https://user-images.githubusercontent.com/25563700/35850461-f764ee94-0b35-11e8-8436-840369318d64.png)
https://pastebin.com/tnqGcxbi
