### ISSUE TITLE
ArrayList on the left glitch 

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1661]
https://imgur.com/a/HhH9i

**Comment by BongHit** [comment]
Without tags:
https://imgur.com/a/GqiuC

Only happens if the item being added/removed is on the top of the array list.

**Comment by Marco-MC** [comment]
Um, I dont have this bug if I start LiquidBounce in my IDE... wtf?

**Comment by scorpion3013** [comment]
![2018-02-03_03-45-19](https://user-images.githubusercontent.com/27446646/35762322-1b69cce0-0895-11e8-9a96-04ee3c6a67eb.gif)

**Comment by Marco-MC** [comment]
https://gyazo.com/4613998b1a9254658db9c2b5854e53dd

**Comment by BongHit** [comment]
It only happens if the item being added or removed is at the top of the list. Anywhere else in the list, it behaves as it should.

**Comment by Marco-MC** [comment]
ohhh, thanks. I will fix it.

**Comment by Marco-MC** [comment]
Fixed.
