### ISSUE TITLE
Add Custom Fly , Custom ESP , Custom KillAura and Velocity

### ISSUE THREAD

**Issue by GiiryBejkol** [CCBlueX/LiquidBounce1.8-Issues#1668]
It should be good if you add these things . With the custom fly , we can find more combinations of aac bypasses and even make fly , the same with the aura and the velocity . Also it will be more useful . It gives you unlimited possibilities which everyone would like to have.

**Comment by SenkJu** [comment]
You can already configure all these modules by rightlicking them...
