### ISSUE TITLE
Custom module

### ISSUE THREAD

**Issue by GiiryBejkol** [CCBlueX/LiquidBounce1.8-Issues#1669]
I have an idea about letting the users of  LiquidBounce make their own module . Exactly i dont know how to do it , so i decided to leave it like suggestion . The idea of it is like this : 
Speed on Sponges [amount of speed]
speed on bricks [amount of speed]
etc... But not only blocks , more , i just cant imagine it , i hope you know what i am talking about 
And after all the process , you can add it like module , like you know , you name it  and then you can use it..

**Comment by SenkJu** [comment]
You can already do that. Use LiquidScript: https://github.com/CCBlueX/LiquidScript/wiki
