### ISSUE TITLE
Better Script System

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#167]
Also wenn ihr gute scripts hochlädt auf github wie bei den Autosettings nur das man die alle aufgelisstet hat und die dann downloaden kann wenn man sie möchte mit einem knopf seitlich man wählt ein script aus und drückt downloaden.

**Comment by FlorijonG** [comment]
und hat die dann automatisch

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/182
