### ISSUE TITLE
Compatibility with custom commands.

### ISSUE THREAD

**Issue by SextupleTap** [CCBlueX/LiquidBounce1.8-Issues#1679]
The client is not compatible with mods that **add custom commands/rendering**, the mods have these custom commands to open up GUI's or change a setting for the mod **(an example of a command: "/timechanger night", which is not a vanilla command)**. The glitch that occurs is that the client commands that use "." no longer function on multiplayer and only function on single player. Also, sometimes mods that add extra rendering cause other rendering modules to fail such as nametags or esp, making them not render or switch between rendering and not rendering when looking through transparent blocks or being in a different perspective (point of view). Sometimes this can also cause confliction with the ability for legit aura, kill aura, and other aiming and attacking modules to fail at targeting or avoiding entities set in the targeting module as well as its ability to avoid bots; being in different game modes (such as spectator, adventure, or survival) mess up targeting as well with these types of mods.

Some examples of mods include: "Time Changer, Sidebar mod, Ping Tag mod, Orange Marshall's Vanilla Enhancements / 1.7 Animations, CPS mod, and other mods that add custom commands or rendering."

**Comment by SenkJu** [comment]
I thought we had already patched the command bug. Will have a look later.

The reason why some GUIs are broken with other mods might be LiquidBounce overwriting them when injecting. Will see.

**Comment by scorpion3013** [comment]
I tested a bit, it works on a few server but not on all. And the  "Orange Marshall's Vanilla Enhancements " fucks up liquidbounce command system, so dont use it.
