### ISSUE TITLE
CustomHUD ArrayList Uppercase Fix

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1694]
http://prntscr.com/i9hw22 http://prntscr.com/i9hw47 http://prntscr.com/i9hw6n http://prntscr.com/i9hw86

**Comment by Marco-MC** [comment]
Das passiert nur wenn du mehrere Arraylists hast.

**Comment by WistarWolf** [comment]
Hab ich aber nicht

**Comment by Marco-MC** [comment]
ah moment...

**Comment by Marco-MC** [comment]
Fixed.
