### ISSUE TITLE
CustomHUD: Image Box fix

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1696]
wenn ich ein image mache, und darunter z.b. die rüstungsanzeige, und ich die rüstungsanzeige auswählen will, wählt er das image aus. Bzw es soll die Box von einem bild angezeigt werden

**Comment by Marco-MC** [comment]
Die Box des Bilds ist genauso groß wie das Bild selbst... Kann sein, das am Interact check ein Fehler ist... mal schauen.

**Comment by Marco-MC** [comment]
Ah, ich weiß glaube was du meinst... Sobald das Bild transparent ist, kann man sehen wo die Bild Box ist...
Ich adde einfach eine Box

**Comment by WistarWolf** [comment]
Hm da wenn ein bild rein setzt, es größer bzw kleine scalet, kann es sein dass man ein stück unter das bild geht, es aber trotzdem das bild auswählt.

**Comment by WistarWolf** [comment]
ja

**Comment by Marco-MC** [comment]
Added
