### ISSUE TITLE
Cleanarraylist

### ISSUE THREAD

**Issue by FantixX** [CCBlueX/LiquidBounce1.8-Issues#1698]
Cool wäre ein Modul, welches in der Arraylist nur wichtige (bzw. ausgewählte) Module anzeigt. Außerdem sollte es möglich sein die Farbe der Arraylist selbst anzupassen.

**Comment by WistarWolf** [comment]
Zu dem "ClearArrayList" Module kann man ja in jedem module ein feld ganz unten machen, in dem man einstellen kann ob es in der arraylist angezeigt werden soll oder nicht. Und zu dem ArrayList eigene farbe: #1670

**Comment by SenkJu** [comment]
Ne, das wäre gegen den Sinn einer ArrayList.
