### ISSUE TITLE
Make CubeCraft Teleport fly mixed up with Hawk Eye fly , you will see it bypasses

### ISSUE THREAD

**Issue by wiqg** [CCBlueX/LiquidBounce1.8-Issues#1701]

**Comment by Marco-MC** [comment]
What do you mean with "CubeCraft Teleport fly"?

**Comment by Fleroxh** [comment]
???

**Comment by gitLukkyz** [comment]
???

**Comment by wiqg** [comment]
You know that if you dont use timer , you can use vanilla but you press the button to make your player go ahead a bit and stop and do it again and again , but its still bannable , so you can mix it with the hawk eye fly or something else .

**Comment by Bircko** [comment]
now in english?
