### ISSUE TITLE
CustomHUD: UpperCase Bug

### ISSUE THREAD

**Issue by gitLukkyz** [CCBlueX/LiquidBounce1.8-Issues#1718]
![grafik](https://user-images.githubusercontent.com/26135660/35777792-44929b72-09b4-11e8-8e0f-9f93ab49dfb8.png)

**Comment by WistarWolf** [comment]
Das hat er schon gefixt du kek

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1694
