### ISSUE TITLE
CustomHUD: BlockOverlay Info Settings

### ISSUE THREAD

**Issue by gitLukkyz** [CCBlueX/LiquidBounce1.8-Issues#1719]
![grafik](https://user-images.githubusercontent.com/26135660/35777824-d6c10cae-09b4-11e8-9d3b-13d8f9bc294d.png)

Am besten das man Position, Alpha und Font ändern kann

**Comment by SenkJu** [comment]
Nein, komplett übertrieben für so etwas simples.
