### ISSUE TITLE
Jump/Port AutoPot

### ISSUE THREAD

**Issue by freaky767** [CCBlueX/LiquidBounce1.8-Issues#172]
Suggestion: Jump AutoPot. Basically it jumps and pots upwards. That is the simple explanation.

**Comment by Marco-MC** [comment]
What? xdd
AutoPot is already in LiquidBounce? :D

**Comment by freaky767** [comment]
i edited it
read again

**Comment by freaky767** [comment]
im retarded sorry

**Comment by Marco-MC** [comment]
ok. I can add it in the next time.

**Comment by freaky767** [comment]
okay

**Comment by Marco-MC** [comment]
Added.
