### ISSUE TITLE
İnventory Cleaner Pls Dont Drop Stick

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1721]
Because İts Need To Hunger Games

**Comment by Teals53** [comment]
Or Select Which İtem Drop Or Not Drop İn GUİ

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1393

**Comment by Teals53** [comment]
Sorry :P
