### ISSUE TITLE
ArrayList: Modules are not in the center of the box 

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1729]
http://prntscr.com/iajs95 Und zwar ist mir aufgefallen, dass nur das oberste Module in der arraylist mittig steht, Die unteren sind am oberen rand der box. Allgemein gibt es Fonts bei denen der text nicht mehr mittig ist (BebasNeue Bold zum beispiel). Kp ob man das iwie fixen kann.

**Comment by Marco-MC** [comment]
Fixed.
