### ISSUE TITLE
Some Modules

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1732]
LiquidVision (See UnderWater Perfect)
AntiCheatDetection (Write Automatically /aac /spartan /reflex Etc And Find Anti-Cheat)
AntiAfk
AutoFish
ArrowDodge
Damage (Damaged Yourself)
PerfectHorseJump
And MiniGames Hack (For Example See Animal İn Animal Hunter Hypixel Minigames)
HvH (Kill Him İn One Stroke)

**Comment by SenkJu** [comment]
Most of them are useless in my opinion. To give yourself damage use .damage <amount>

**Comment by Teals53** [comment]
Not useless pls add :(

**Comment by Teals53** [comment]
can you take a look @Marco-MC  maybe there are features you can add
