### ISSUE TITLE
.help suggestion

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1733]
I'm writing help, but it doesn't show how many pages

For Example 
[LiquidBounce] Help Page 1/9

**Comment by SenkJu** [comment]
It does say that there are multiple pages. Use .help <page> like .page 2

**Comment by Teals53** [comment]
I dont say this

**Comment by Teals53** [comment]
[https://i.hizliresim.com/jy86dn.png](url)

**Comment by Teals53** [comment]
and when you type more numbers than the number of pages, you can give such a warning.

**Comment by Teals53** [comment]
@SenkJu  @Marco-MC

**Comment by Marco-MC** [comment]
Added
