### ISSUE TITLE
NameTags Nuker X-ray More Customization

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1735]
NameTags
-Choosing which information is displayed (Added)
-Add Showing Enchantmend Level İn Game Language (Armor &  Sword & Any İtems)
-Add İtems Health-Durability Bar Or Number (Armor &  Sword & Any İtems)
-Add Chat Durability Spam Like Some PvP Clients (For The Player You Attacked)
Nuker
-Personalization must be added in the menu
-Add More Option For Example İnstant Nuker,İd Nuker,Reach Etc
-Add Legit Mode/Bypass For Factions Server (NCP)
-Recode Good For Nuker https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2581
X-Ray
-Personalization must be added in the menu
-Select Block İn Menu
-Set Opacity İn GUİ
-Cave Option (Only Show Blocks Touching Air)

**Comment by Teals53** [comment]
Updated NameTags Request

**Comment by Teals53** [comment]
Reach(Radius) Added https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2628

**Comment by superblaubeere27** [comment]
List issues = Invalid

**Comment by Teals53** [comment]
Its better if i spamming post for every request ? @superblaubeere27

**Comment by superblaubeere27** [comment]
Yes, @Teals53. The name already tells you that an issue is opened for **one** issue.
