### ISSUE TITLE
CustomHUD: Scaling ändert position

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1736]
Wenn man mit dem mausrad etwas scalen will (ArrayList z.b.) Ändert es wie die position leicht. Kann man es machen dass die position bleibt und es halt nur gescalet wird? (So vllt: https://youtu.be/1NFkuNkGRW0?t=39s)

**Comment by SenkJu** [comment]
Alter, hat der Client ne beschissene Logo Animation im Main Menu xd

**Comment by WistarWolf** [comment]
xd
