### ISSUE TITLE
CustomHUD speichern

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1738]
Wie die LocalSettings ein Befehl für die CustomHUD.
Der Befehl soll so aufgebaut sein: **_.customhud <save/load/list> <name>_**.

Beim Speichern sollen alle Bilder, Texte & Positionen (inkl. Eigenschaften) der HUD-Items gespeichert werden.

**Comment by SenkJu** [comment]
meh, mach backups von der hud.json
