### ISSUE TITLE
OldNCP YPort

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1739]
Ein YPort für das alte NoCheatPlus (z.B. für Cubecraft).
Der "neue" YPort ist viel zu langsam, da aber YPort's generell nicht schlecht sind, wünsche ich mir einen für das alte NoCheatPlus.

**Comment by Marco-MC** [comment]
@RealFantaCoke Es gibt zwei YPort Modes?
Der erste ist der sau schnelle, der andere der einfach nur ein normaler YPort... beide sind für's alte NCP, als noch auf NCP YPorts gingen.
