### ISSUE TITLE
2 neue CustomHUD-Items & 2 Optionen

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1740]
CustomHUD-Items:

1. auswählbare Watermarks (so circa 3-5 Stück für's erste)
2. breite BlackHotbar (um nicht ständig auf Scripts zurückzugreifen müssen, eventuell als Option)

CustomHUD-Optionen:

1. Hotbar, Herzen, Scoreboard & Chat verschiebbar machen
2. Model feststellen (soll den Körper bei aktivierter Option nicht ständig bewegen)

**Comment by WistarWolf** [comment]
Dass man eine large/little hotbar machen kann ist soweit ich weiß geplant. Und das mit scoreboard auch. Bei den anderen sachen kp
