### ISSUE TITLE
Notifications Left support

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1741]
Im CustomHUD-Editor kann man ja die Notificationleiste verschieben, allerdings wechselt das "blaue Ende" beim Auswählen von "Left" nicht.

Normalerweise müsste das blaue "Ding" nach rechts wechseln, wenn man auf "Left" klickt.

Wenn es gewollt ist, dann bitte eine Option dafür hinzufügen:
_**Right, Left, None**_

**Comment by RealFantaCoke** [comment]
Bereits umgesetzt? Dauert echt ziemlich lange für so ein kleines Feature?

**Comment by superblaubeere27** [comment]
Done in CustomGUI
