### ISSUE TITLE
BlockESP: Outline, WireFrame and Box Mode

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1744]
Und ich erinnere auch nochmal daran: #1240

**Comment by SenkJu** [comment]
Die OutlineUtils von Hexeption unterstützen keine Blöcke und Marco ist wohl zu fauel/zu blöd das zu adden.

**Comment by WistarWolf** [comment]
Okay

**Comment by Bircko** [comment]
ich glaub zweiteres
