### ISSUE TITLE
More Bypass

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1748]
https://www.youtube.com/watch?v=4qqUE_zGkbs
https://www.youtube.com/watch?v=d8P9egNEqk4

**Comment by SenkJu** [comment]
We already have both of it. https://www.youtube.com/watch?v=fzxr9u6yPvw

**Comment by Teals53** [comment]
you know settings ? @SenkJu

**Comment by Teals53** [comment]
custom speed @SenkJu  ?
