### ISSUE TITLE
CustomHUD ArrayList Minecraft minimized bug if the element is scaled

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1751]
http://prntscr.com/idpmy9

**Comment by Marco-MC** [comment]
Junge, das ist kein Bug... das ist deine eigene Schuld... du musst das Arraylist element auch auf die richtige Seite bounden.

**Comment by Marco-MC** [comment]
Normalerweise passiert dies nicht, doch sobald das Element einmal gescaled wurde passiert dies... Muss ich mir mal anschauen, wieso...

**Comment by WistarWolf** [comment]
Mir ist aufgefallen dass das allgemein bei gescaleten elementen ist (Effekten z.b.)

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1736
