### ISSUE TITLE
Hide and Seek ESP for Hive and Mineplex

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1752]

**Comment by gitLukkyz** [comment]
oder im block esp falling sand möglich machen.

**Comment by WistarWolf** [comment]
nein. Sonst wird der ganze Sand auf der Map markiert

**Comment by Bircko** [comment]
und soll ja so sien

**Comment by gitLukkyz** [comment]
damit sich die blöcke bewegen wird falling sand benutzt. falling heißt nicht das es ein normaler block ist, falling sand kann physik haben

**Comment by gitLukkyz** [comment]
falling sand = blöcke bewegen sich.
normale blöcke = normale blöcke.

**Comment by gitLukkyz** [comment]
dummer wolf

**Comment by WistarWolf** [comment]
Trotzdem ist ein Hide and seek esp besser bzw eine Option im ESP Module für HaS

**Comment by gitLukkyz** [comment]
ja.
