### ISSUE TITLE
AntiCheat Detected and Crash the Client

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#1753]
server :mc233.cn
AC:AAC(EDITED)
Do .settings gomme
Turn on AntiBots
and
Just join and play skywars(空岛战争) for 1 minutes
And You will got Detected(just stand for a while) and IP banned
And the Client will Crashed
==============
I will take a video soon

**Comment by CrackFileso** [comment]
Logs:
https://ghostbin.com/paste/ayyop

**Comment by CrackFileso** [comment]
video:https://www.youtube.com/watch?v=uf49sh3ju1c&feature=youtu.be

**Comment by ForSkyblue** [comment]
Can brother add QQ?

**Comment by ForSkyblue** [comment]
My QQ：1657979433
