### ISSUE TITLE
Fix: ArmorStand NameTags bug

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#176]
![javaw_2017-04-23_05-17-59](https://cloud.githubusercontent.com/assets/27446646/25310446/a211122c-27e4-11e7-8341-3ff35d041e09.png) Mit nichts an in LiquidBounce

![javaw_2017-04-23_05-18-13](https://cloud.githubusercontent.com/assets/27446646/25310450/b0c6e9cc-27e4-11e7-9447-42aea154c198.png) Mit TrueSight an in LiquidBounce

![javaw_2017-04-23_05-20-05](https://cloud.githubusercontent.com/assets/27446646/25310454/c173eb8a-27e4-11e7-9cd8-16d792fc888e.png)Vanilla

**Comment by scorpion3013** [comment]
Falscher button lul, also Die Namen die in Vanilla auch sichtbar sind bitte sichtbar lassen.. danke

**Comment by Marco-MC** [comment]
Das war kein Bug von TrueSight sondern in der "ArmorStandRendere" Klasse wurde die Methode "canRenderName" nicht überschrieben. :)
Habe ich jetzt behoben. Das war ledeglich ein decompile Fehler von MCP.
