### ISSUE TITLE
BufferSpeed Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1763]
Buffer Speed Boost Not Set 0.00 Minimum Value 0.05 And Not Have Command Fix Pls I Not Need Boost I Only Need Jumping HeadBlock Because Boost Options Blocked AAC

**Comment by gitLukkyz** [comment]
that is not a bug.

**Comment by Teals53** [comment]
How Set This 0.00 ? You Know ?

**Comment by Teals53** [comment]
No ? Ok İts A Bug , Yes Ok İts Not Bug :D

**Comment by Marco-MC** [comment]
This is not a bug.

**Comment by Teals53** [comment]
@Marco-MC How To Set 0.00 ?

**Comment by Marco-MC** [comment]
... dude why you want to set boost to 0?! wtf?
If you set it to 0 nothing will happen?...

**Comment by Teals53** [comment]
I Only Need Jumping Automatically And Fastly HeadBlock

**Comment by Teals53** [comment]
Not Need Boost Because AAC Block This

**Comment by Teals53** [comment]
@Marco-MC ??? Can You Answer My Question

**Comment by Teals53** [comment]
@Marco-MC can you help ?
