### ISSUE TITLE
Nofall-Freecam Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1764]
I open nofall and open freecam but my freecam İs Falling Down I think freecam should be impressed.

**Comment by Teals53** [comment]
And KillAura attack myself in freecam

**Comment by gitLukkyz** [comment]
those aren't bugs.

**Comment by Teals53** [comment]
Why ?

**Comment by Marco-MC** [comment]
Fixed.
