### ISSUE TITLE
Detect Enchantment On Sword

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1765]
İn Hotbar Select Best Enchantment Sword With AutoSword

For Example "StoneSword(Sharpness V) Attack Power >İronSword(No Enchant) Attack Power" But AutoSword Select DiamondSword ?

**Comment by SenkJu** [comment]
duplicated

**Comment by Teals53** [comment]
@Marco-MC Which İssue Duplicated ?
