### ISSUE TITLE
LiquidScript v3 (Complete recode!)

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1768]
LiquidScript wird sobald ich das nächste mal wieder an LiquidScript arbeite kompeltt neugeschrieben und wird sich komplett ändern.
Ich nehme keine neuen Ideen fürs erste an, sondern close sie sofort.

**Comment by superblaubeere27** [comment]
Whatever. Ich mache einen Java -> LiquidScript compiler also mach die Sprache sehr flexibel!

**Comment by superblaubeere27** [comment]
Ausserdem: Machs mal so, dass Strings mit `""` kennzeichnen muss

**Comment by CrackFileso** [comment]
Be Better Add an API to access Minecraft.getMinecraft()

**Comment by Marco-MC** [comment]
@CrackFileso Forge?...

**Comment by Marco-MC** [comment]
Replaced by https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2649
