### ISSUE TITLE
Bypass Minecraft Account Blocked

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1772]
İf You Try A Lot Of Wrong Acc Can Add LB/Or Mc Launcher Minecraft Block You And Now Not Add Working Account You Need Reset Modem

**Comment by SenkJu** [comment]
Impossible to bypass it without changing your IP.

**Comment by Teals53** [comment]
Ok Thanks

**Comment by Teals53** [comment]
Proxy Cant Bypass This ?

**Comment by Teals53** [comment]
@SenkJu

**Comment by Teals53** [comment]
Bcs EggCrack etc Using Proxy And Check A Lot Of Account How İts Possible ? İts Possible İn Program But İmposible İn Minecraft ?

**Comment by SenkJu** [comment]
#1483

**Comment by Teals53** [comment]
Oke :)
