### ISSUE TITLE
Settings load crash

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1774]
Undzwar crasht mc wenn man settings läd, man davor die clickgui aber net geöffnet hat. dies passiert anscheinend auch nur wenn man andere Mods außer Lb und optifine drin hat (bsp itemphysics, old animations )

**Comment by SenkJu** [comment]
Vermutlich ein Fehler mit einer der Mods.

**Comment by Marco-MC** [comment]
Ich kann ohne Crashlog usw auch nichts machen?

**Comment by WistarWolf** [comment]
https://hastebin.com/iburuhoqos.php Anscheinend passiert dass auch nur bei .settings und nicht bei .setting
