### ISSUE TITLE
Hotbar höhe

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1776]
Die blackbar soll nicht bis zur xp leiste sein, aber auch net zu niedrig, es soll etwas platz zwischen der hotbar und der xp leiste sein. Würde meiner meinung nach besser aussehen. Wie in xave beispielsweise
http://prntscr.com/ig3pr0

**Comment by gitLukkyz** [comment]
Aber deine Meinung interessiert hier keinen :^^^^)
