### ISSUE TITLE
Main menu: Button Border

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1780]
Bei den ganzen mc buttons soll eine weiße umrandung haben. Das würde besonders bei dunkleren hintergründen besser aussehen

**Comment by SenkJu** [comment]
Welche Buttons meinst du?

**Comment by WistarWolf** [comment]
Add Server, back to main menu, options etc. Das würde einfach besser aussehen (http://prntscr.com/ig18kf)

**Comment by Marco-MC** [comment]
kys @WistarWolf
