### ISSUE TITLE
AAC 3.3.9 Velocity

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1781]

**Comment by Marco-MC** [comment]
Zwar geht Reverse2Velocity auf 0.05 strength durch, aber mir hat letzens `JustDustYT` einen AAC Push Velocity geschickt...

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
Okay, er bypassed nicht.
Wow.

**Comment by Marco-MC** [comment]
Ist eh egal, wir haben genug AAC Velocity modes
