### ISSUE TITLE
Jigsaw ClickTeleport Work AAC Server

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1783]
I give information on the video
https://youtu.be/NADAwKoPgmM
Pls Add

**Comment by Marco-MC** [comment]
The teleport of jigsaw is just a blink teleport.

(Select blink mode in teleport)

**Comment by Teals53** [comment]
@Marco-MC But İts Not Working

**Comment by Teals53** [comment]
Its not blink Teleport its Different pls Add Check Video Its working on AAC server @Marco-MC @Marco-MC ,

**Comment by Teals53** [comment]
But LiquidBounce Blink Teleport Not Working @Marco-MC
