### ISSUE TITLE
Scaffold + InvCleaner Bug

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1787]
wenn man Scaffold an hat und invcleaner, dann wirft er die items immer auf die stelle auf der man steht (ist zumindest bei den cubecraft settings so. Obs bei den anderen so ist kp)

**Comment by SenkJu** [comment]
Kein Bug. Du schaust serverside wegen Scaffold auf den Boden und deswegen fliegen dahin auch die Items.

**Comment by WistarWolf** [comment]
Ah xd
