### ISSUE TITLE
Better longjump

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#179]
A longjump which goes a bit longer, as well as in Xave or syntax

**Comment by Marco-MC** [comment]
Ja und dann noch einen NCP Fly und einen GommeHD.Fett ForceOP? Denkste alles ist mit einem Tasten druck eZ... .-.
Nicht böse gemeint, aber es triggerd mich echt krass wenn Leute so welche anforderungen bei einem Free Client stellen.

**Comment by FlorijonG** [comment]
Es ist ja geil für nen Free Client der die neusten Bypasses hat aber es wird halt viel für aac gemacht und für ncp halt fast nichts deswegen hatte ich gehofft du könntest einen besseren machen der derzeitige ist nicht grade schlecht aber da besseres geht hatte ich gehofft dass du einen machst.

**Comment by Marco-MC** [comment]
https://www.youtube.com/watch?v=TxFqXu7quL8

**Comment by airbus2** [comment]
gibts derzeit eigendlich einen guten Longjump?

**Comment by airbus2** [comment]
gibts derzeit eigendlich einen guten Longjump?

**Comment by airbus2** [comment]
gibts derzeit eigendlich einen guten Longjump?

**Comment by airbus2** [comment]
gibts derzeit eigendlich einen guten Longjump?

**Comment by airbus2** [comment]
gibts derzeit eigendlich einen guten Longjump?

**Comment by airbus2** [comment]
gibts derzeit eigendlich einen guten Longjump?

**Comment by airbus2** [comment]
gibts derzeit eigendlich einen guten Longjump?

**Comment by airbus2** [comment]
gibts derzeit eigendlich einen guten Longjump?
