### ISSUE TITLE
Hide n Seek ESP

### ISSUE THREAD

**Issue by gitLukkyz** [CCBlueX/LiquidBounce1.8-Issues#1792]

**Comment by Marco-MC** [comment]
Wofür ein extra Modul? Einfach als Target type zu Targets, dann kann man die auch mit KillAura kaputt hauen.
Doofe ist halt lediglich das nur die angezeigt werden die sich derzeit bewegen, wollte eigentlich machen dass sich das abspeichert aber dadurch das die falling blocks 0 spielerbezogen sind geht dies nicht.

**Comment by Marco-MC** [comment]
Added
