### ISSUE TITLE
Module Toggle beim Laden der Settings

### ISSUE THREAD

**Issue by Gegreenpeaced** [CCBlueX/LiquidBounce1.8-Issues#1796]
Bitte fügt die Einstellung Module Toggle(wie bei Skid) hinzu.

**Comment by Marco-MC** [comment]
Gibt es bereits, zwar nicht als Option doch die AutoSettings toggeln in den meisten Fällen wichtige Module an und Module die nicht bypassen aus.

`<moduleName> toggle <state>`
