### ISSUE TITLE
AAC 3.3.10 Longjump

### ISSUE THREAD

**Issue by Gegreenpeaced** [CCBlueX/LiquidBounce1.8-Issues#1797]
Bitte fügt den AAC 3.3.10 Longjump als seperates Modul hinzu.

**Comment by Marco-MC** [comment]
Ich werde ihn, falls ich ihn hinbekomme als AAC6BHop hinzufügen und nicht für sowas ein seperates Modul?

**Comment by Marco-MC** [comment]
Er workt genauso wie der AAC4BHop, lediglich mit dem unterschied das er schneller ist.

**Comment by Marco-MC** [comment]
Der LongJump/Speed scheint lediglich auf Gomme zu gehen.

**Comment by Gegreenpeaced** [comment]
ok, danke

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
btw Gomme hat wieder 3.3.9... :c
