### ISSUE TITLE
Änderung im LiquidLuncher und LiquidScript

### ISSUE THREAD

**Issue by Gegreenpeaced** [CCBlueX/LiquidBounce1.8-Issues#1798]
Keine Ahnung ob das hier hin gehört, da ich keine Idee habe wo ich das sonst sagen kann:
@superblaubeere27 bitte ändere in der nächsten version vom LiquidLuncher, das die Liste der Geladen also schon mal hinzugefügten Mods gespeichert wird. Es nervt immet wieder die selbe Mod neu auszuwählen!

@Marco-MC ich weiß das du LiquidScript neu codest. Bitte füge die Einstellung zu LB hinzu, das das Script geladen bleibt und man es immer neben bei in einem Editor ändern kann. Und Bei LB, ohne den server zu verlassen im Pause Menü einen Script Reload durchführen kann.

@superblaubeere27 kannst du im LiquidLuncher auch ein Fenster für LiquidScript hinzufügen(Einfach das Mod Fenster nehmen und für LiquidScript machen.

Danke 
Julius aka Gegreenpeaces

**Comment by gitLukkyz** [comment]
Das mit den Mods stört mich auch total.

**Comment by SenkJu** [comment]
Der Launcher sollte wieder gehen. Der Rest ist sowieso geplant.
