### ISSUE TITLE
Bug im HUD Editor

### ISSUE THREAD

**Issue by Gegreenpeaced** [CCBlueX/LiquidBounce1.8-Issues#1799]
@Marco-MC bitte fügt zu den Schriften die man im Hud Editor hat auch die Schrift hinzu die man beim normalen Installieren hat, also der "LiquidBounce" Text der über dem Tab GUI steht. Löscht man diesen kann man die gleiche Schriftgröße nur mit einem neuaufsetzten von LB beheben. Bitte ändern.

**Comment by Marco-MC** [comment]
...
Wähl Roboto Medium - 40 aus, dann Scale es auf 2.0 mit deinem Mausrad...
