### ISSUE TITLE
Ore Farm Bot

### ISSUE THREAD

**Issue by Gegreenpeaced** [CCBlueX/LiquidBounce1.8-Issues#1800]
@Marco-MC kannst du  Server wie z.b. GrieferGames.net einen Bot als Module programmieren, der mit dem Plugin Ore Generator arbeitet d.h. Wenn durch das Plugin in einem Cobble Generator ein Erz entsteht, wird dieses durch LiquidBounce bzw. durch das Module abgebaut. (wäre das möglich oder geht das nicht)

**Comment by gitLukkyz** [comment]
AutoBreak

**Comment by Gegreenpeaced** [comment]
thx
