### ISSUE TITLE
Idee

### ISSUE THREAD

**Issue by Gegreenpeaced** [CCBlueX/LiquidBounce1.8-Issues#1801]
Also das klingt jetzt lächerlich und ich habe wieder keine ahnung wo ich die Frage stellen kann. Aber @Marco_MC kannst du LiquidBounce mit den Wenigsten Modulen auch für Minecrafz PE Schreiben?

Über eine Antwort würde ich mich freuen.

**Comment by Marco-MC** [comment]
Nein.

**Comment by SenkJu** [comment]
Theoretisch könnten wir LiquidBounce für die Bedrock Edition machen, nur gibt es (noch) keine brauchbare Modding API.

**Comment by Marco-MC** [comment]
Bedrock Edition? Was ist das?

**Comment by SenkJu** [comment]
Gibt kein Minecraft PE mehr. Das heißt jetzt Minecraft Bedrock Edition und läuft Cross-Platform kompatibel auf Handys, Konsolen, etc

**Comment by Marco-MC** [comment]
ah, k.
