### ISSUE TITLE
[BUG] LiquidChat Zeilenumbruch

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1802]
Wenn man im sog. "LiquidChat" die zwei Zeichen "\n" eingibt, wird eine neue Zeile erstellt bzw. der Text in eine neue Zeile "verschoben".

Bitte beheben, da es manchmal sehr störend sein kann, wenn es jemand ausnutzt.

//edit: Es ist auch möglich, komplett leere Nachrichten damit im LiquidChat abzusenden.

**Comment by Gegreenpeaced** [comment]
finde ich gut

**Comment by Marco-MC** [comment]
Fixe ich nacher im LiquidChat Server.

**Comment by Marco-MC** [comment]
ah, hab ich inzwischen schon lange gefixt.
