### ISSUE TITLE
Normale Ansicht

### ISSUE THREAD

**Issue by Niclas-Bacon** [CCBlueX/LiquidBounce1.8-Issues#1803]
Das man es so sieht wie Normale Spieler also Server Side z.B: Scaffoldwalk so wie Normale Legits als Neues Module wäre cool.Danke

**Comment by Gegreenpeaced** [comment]
jup wäre nice

**Comment by SenkJu** [comment]
Eagle?

**Comment by Marco-MC** [comment]
Einfach wie @SenkJu schon sagte, Eagle benutzen.
