### ISSUE TITLE
NoteblockAura

### ISSUE THREAD

**Issue by MCMDEV** [CCBlueX/LiquidBounce1.8-Issues#1812]
Wie wäre es damit:
Man stellt sich in einen Bereich mit Notenblöcken, gibt dem Client eine NBS Datei, und er spielt die Musik mit den Notenblöcken

**Comment by Gegreenpeaced** [comment]
Haha,
Die Idee ist Lustig!

Marco_MC muss das umsetzen. Würde es mega Feieren.

xD

**Comment by scorpion3013** [comment]
Hätte soeine Mod dafür. Kann die nachher hier rein schicken. Die rotations sind aber ziemlich schlecht gemacht und geht deshalb auf keinen Server der ein Anti-Cheat hat. Ebenfalls sind die rotations visible. Also ziemlich AIDS wenn man die Person ist die das benutzt.

**Comment by scorpion3013** [comment]
Sieht so aus  https://streamable.com/o1fwe (Original mod von zeairmouse, hab die nur für höhere Versionen kompatibel gemacht und paar Fehler behoben)

**Comment by SenkJu** [comment]
Nichts fûr einen hacked client
