### ISSUE TITLE
Script List

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#182]
Im Script Manager an der Seite ein Button der Script List oder so ähnlich heißt. Wenn man darauf klickt kommt man zu einer Seite bei der Scripts sind die User erstellt haben und anbieten.

**Comment by Marco-MC** [comment]
https://gyazo.com/23737cce18f514929f343316b29f27d6
https://github.com/CCBlueX/LiquidScript/wiki/Scripts

Added.
