### ISSUE TITLE
AntiCheatDetection

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1820]
Write Automatically /aac /spartan /reflex Etc And Find Anti-Cheat

or better

**Comment by SenkJu** [comment]
Do it yourself. Its really not that much work

**Comment by Teals53** [comment]
But Some Server Block This Command How Find Anti-Cheat ? @SenkJu

**Comment by SenkJu** [comment]
If the command is blocked, a module which sends it automatically won't work either. You try to find out which AntiCheat the server is using by observing the way it flags players.

**Comment by Teals53** [comment]
Okey Thanks
