### ISSUE TITLE
TabGUI Category Full

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#183]
Dass in einer TabGUI Category höchstens 25 oder so Module angezeigt werden können und wenn es mehr sind scrollt man in der TabGUI auch mit den Pfeil Tasten. So wie in der ClickGUI bei der man ja auch scrollen kann. Also das in der TabGUI unten ein Modul mehr erscheint aber oben dann eins "verschwindet".

**Comment by RealFantaCoke** [comment]
//Zusatz: Falls jemand nicht wissen sollte was gemeint ist, dann startet den Client und klappt bei der TabGUI den Tab "Movement" auf.
