### ISSUE TITLE
Mineplex Fly: Automatically switch to an empty slot

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1833]
Es wäre hilfreich, wenn der Fly auf Mineplex, der ja einen leeren Slot benötigt, auf diesen automatisch wechselt bzw. einen Slot in der Hotbar freiläuft, wenn der Fly ausgewählt wird.

**Comment by Gegreenpeaced** [comment]
Wäre echt gut. Das man immer einen freien Slot haben muss ist echt Krebs.
