### ISSUE TITLE
Scaffold Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1834]
Why sometimes he puts a block under it. 

AutoSettings: AAC

https://youtu.be/zR8rEVwRyZ8

**Comment by Teals53** [comment]
I Upload Video

**Comment by ShadowLBx** [comment]
das is kein bug so funktioniert minecraft

**Comment by Teals53** [comment]
English ?

**Comment by Teals53** [comment]
wenn Sie mehr beschreibende ?

**Comment by Ju200** [comment]
@Teals53 This is not a bug the scaffoldwalk tries to place a block and opens the chest

**Comment by Teals53** [comment]
@Marco-MC last up
