### ISSUE TITLE
Scaffold platziert Spinnennetze

### ISSUE THREAD

**Issue by WoodyLetsPlay** [CCBlueX/LiquidBounce1.8-Issues#184]
Wenn man Spinnennetze im Inventar hat, platziert der Scaffold die Spinnennetze.

**Comment by RealFantaCoke** [comment]
Dann musst du entweder "AutoBlock" bei Scaffold & evtl. bei Tower deaktivieren, oder die Spinnenweben aus deiner Hotbar nehmen.

Dies ist kein Bug.

**Comment by WoodyLetsPlay** [comment]
Ja, aber es wäre besser wenn er das nicht tun würde, weil wer baut sich mit Spinnennetzen?

**Comment by Marco-MC** [comment]
Ich baue immer mit Spinnennetzen? Wenn ich welche habe weil das lustig ist mit WebWalk. Deshalb.. Ne. Und nein ich werde auch keine Option einbauen weil das dann noch unnötiger wäre.

**Comment by WoodyLetsPlay** [comment]
Ja okay. Sorry für den falschen Beitrag. An das habe ich nicht gedacht.
