### ISSUE TITLE
AutoSword Suggestion

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1840]
İf You Have A Sword İn İnventory And Attack Him , Automatically Put Sword İn Hotbar 

and if the server you're playing has not blocked inventory hacks, let it do this without opening inventory

it works in an emergency.

**Comment by Ju200** [comment]
Exactly the same makes an Invsort. 
So please add an Invsort.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1601
