### ISSUE TITLE
Scaffold Not Put Block İf You Have A Sapling İn Hand

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1841]
if you have a seed, scaffold doesn't put a block,

autosettings AAC

**Comment by Marco-MC** [comment]
A Sapling is also a block. .-.

**Comment by Teals53** [comment]
https://youtu.be/3CeMwqwr-zA @Marco-MC

**Comment by Marco-MC** [comment]
A SAPLING IS ALSO A BLOCK

**Comment by Teals53** [comment]
don't be mad. bcs ı love you :) <3
