### ISSUE TITLE
automatisches ausweichen vor Pfeilen

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#1843]

**Comment by Gegreenpeaced** [comment]
Finde ich gut. Endlich mal was gegen Bow Schwitzer

**Comment by SenkJu** [comment]
Eher sinnlos, das würde einem zB. in SkyWars oder BedWars runterspringen lassen. Außerdem würde das nur bypassen, wenn man sich dabei Legit verhält. Letzendlich also nicht besser als legit ausweichen.
