### ISSUE TITLE
Autosettings Not Changed Killaura Max Cps

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1847]
Sometimes Autosettings Not Changed Killaura Max Cps

For Example Change 20 Max Cps And Write .autosettings aac but cant change max cps but you write rety .autosettings aac max cps is now changed

**Comment by Marco-MC** [comment]
Bug Config Example:
`killaura mincps 10
killaura maxcps 15
`

**Comment by Teals53** [comment]
and maybe sometimes not open keepsprint

**Comment by Marco-MC** [comment]
Fixed.
