### ISSUE TITLE
Friend System Alias Bug

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#185]
Wenn man mehrere Freunde hinzufügt im Client, und Ihnen alle einen Alias gibt, wird immer nur der zuletzt hinzugefügte Freund inkl. Alias angezeigt.

Die anderen, vorher hinzugefügten Freunde werden normal angezeigt, und der Alias verschwindet einfach.

**Comment by Marco-MC** [comment]
Already patched.
