### ISSUE TITLE
Command Macros

### ISSUE THREAD

**Issue by ImDrops** [CCBlueX/LiquidBounce1.8-Issues#1853]
Wäre Cool

**Comment by ImDrops** [comment]
Außerdem wäre es Cool, wenn ihr am NCPYPort speed arbeiten könnt, der bypasst irgendwie überall
(selbst wenn alle anderen nicht Funktionieren)

**Comment by ImDrops** [comment]
also ihn weiterentwickeln

**Comment by SenkJu** [comment]
#3255
