### ISSUE TITLE
SuperKnockback setting

### ISSUE THREAD

**Issue by ImDrops** [CCBlueX/LiquidBounce1.8-Issues#1859]
SuperKnockback ist ein Krasses Modul, dass irgendwie überall bypasst. Wäre cool wenn man die anzahl der onGround Packets einstellen könnte (um so die Stärke einzustellen).
Quasi wie hier, wo 250 Packets gesendet werden die den Gegner !Extrem! weit "schludern"
https://imgur.com/zFYnISI
Danke

**Comment by Marco-MC** [comment]
Unser Superknockback funktioniert völlig anders und ist nicht einstellbar.
