### ISSUE TITLE
Mehr TabGUI Themes

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#186]
Vielleicht ein paar mehr Themes für die TabGUI ...

Ich weiß, es ist sehr viel Arbeit, aber das Standart Aussehen wie es jeder Client zurzeit hat ist einfach echt ausgelutscht.

Es wäre cool, wenn Ihr eventuell eine runde TabGUI & eine TabGUI oben am Rand (wie der Material Client) hinzufügen könntet, um ein bisschen Abwechslung zu garantieren.

**Comment by DieSchuessel** [comment]
Wäre immer noch für ein GUI wie bei cs go cheats z.B. so http://imgur.com/a/eYzZN.

**Comment by RealFantaCoke** [comment]
CS:GO GUI ist auch nicht schlecht ... so in Richtung "InterwebZ" ;)
