### ISSUE TITLE
CustomHUD: Automatically swap ArrayList alignment

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1863]
Wenn man die ArrayList auf die rechte Seite des Screens zieht, sollte sie sich nach rechts ausrichten, wenn sie auf der linken Häflte ist, nach links.

**Comment by Marco-MC** [comment]
Dafür gibt es eine Option, die muss man sowieso umschalten.

**Comment by SenkJu** [comment]
Ich weiß, dass es da eine Option gibt. Ich will dass er *automatisch* umswitcht.
