### ISSUE TITLE
CustomHUD false position saving

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1864]
Habe einen Hauptbildschirm und einen neben bildschirm. Der neben bildschirm ist in der höhe höher als der haupt und dort werden zumindest die sachen unten links/rechts nicht richtig abgespeichert:
Hauptbildschirm: http://prntscr.com/imf4vg Nebenbildschirm: http://prntscr.com/imf59s Minimized: http://prntscr.com/imf5lu

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1751
Der Bug passiert nur bei gescalten Elementen, wie du schon gemeldet hast.

**Comment by WistarWolf** [comment]
http://prntscr.com/impvgc

**Comment by Marco-MC** [comment]
Ja auch wenn da Scale 1 steht, kann es scaled sein weil es gerundet ist

**Comment by WistarWolf** [comment]
ah ok
