### ISSUE TITLE
LegitKillaura Suggestion

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1865]
Aimbot -> TurnSpeed
AimAssist -> TurnSpeed
LegitAura -> LegitBlockHit -> Delay/Randomize Chance

**Comment by Marco-MC** [comment]
Aimbot -> Added (https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1875)
AimAssist -> Moved into Aimbot (https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1874)

**Comment by Teals53** [comment]
LegitAura -> LegitBlockHit -> Delay/Randomize Chance ?

**Comment by Marco-MC** [comment]
I didn't closed the issue yet

**Comment by Teals53** [comment]
Oh Ok Sorry

**Comment by Teals53** [comment]
@Marco-MC You Removed LegitAura So Closed This İssue
