### ISSUE TITLE
.configreload command

### ISSUE THREAD

**Issue by koraseeq** [CCBlueX/LiquidBounce1.8-Issues#1866]
Reloads settings, maybe alts

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
https://img.liquidbounce.net/moc/java_2018-03-04_16-35-37.png

**Comment by Teals53** [comment]
what does it do and why should we use it? @Marco-MC  @koraseeq

**Comment by Marco-MC** [comment]
@Teals53 It just reload all configs of liquidbounce. So if you change something in the values.json and type .reload the value in liquidbounce will be change also.

**Comment by Teals53** [comment]
so its set default evrything ? @Marco-MC

**Comment by Marco-MC** [comment]
Nah, it just reload your current configs.

**Comment by Teals53** [comment]
current config ? how create my current config

**Comment by Teals53** [comment]
and why do I need to re-load the settings I currently use?

**Comment by Teals53** [comment]
@Marco-MC

**Comment by Marco-MC** [comment]
If you changed something in your configs (the files in the LiquidBounce folder) you can instantly load it into liquidbounce.

**Comment by Teals53** [comment]
oh ok ı understand now thx
