### ISSUE TITLE
Aimbot Aim Option

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1876]
Like Csgo Cheat

AimBot
Head
Neck
Arm (LeftArm/RightArm/Randomize Arm)
Body
Foot (LeftFoot/RightFoot/Randomize Foot)
Full Randomize (Aim Everything)

**Comment by Marco-MC** [comment]
It make no difference what body part you hit... so no.

**Comment by Teals53** [comment]
I thought maybe anti-cheat bypasses. @Marco-MC

**Comment by Marco-MC** [comment]
nah
