### ISSUE TITLE
Change Spam Message And NameProtect Name İn Gui

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1877]

**Comment by WistarWolf** [comment]
If that will be possible, than its godd if you can also change the NameProtect name in the GUI

**Comment by Teals53** [comment]
yes its good suggestion :D ı updated

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2659
