### ISSUE TITLE
ChestAura & GhostHand SelectBlock

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1879]
why don't you just add the blocks that can be opened with a right click ?

(furnace not working)

**Comment by Marco-MC** [comment]
because many server has other blocks to click

**Comment by Teals53** [comment]
@Marco-MC  and chestaura cant open furnace

**Comment by Marco-MC** [comment]
https://img.liquidbounce.net/moc/2018-03-04_17-27-37.mp4
@Teals53 It's working...
