### ISSUE TITLE
I Write ".chestaura chest" But

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1881]
I Firstly Write .chestaura chest Furnace and ChestAura Chest Set https://i.hizliresim.com/vjND9r.png
and now ı write again .chestaura chest show me https://i.hizliresim.com/qGNDzZ.png

**Comment by Marco-MC** [comment]
Just type .chestaura chest furnace

**Comment by Teals53** [comment]
but its a bug ?

**Comment by Teals53** [comment]
@Marco-MC İts A Bug Or Not :P ?

**Comment by scorpion3013** [comment]
Becuase your screenshot link is broken: 
![firefox_2018-06-23_18-14-51](https://user-images.githubusercontent.com/27446646/41811507-5bfe11e0-7711-11e8-9171-410b7c4ace79.png)
