### ISSUE TITLE
CustomHUD: ArrayList random module color & color saturation & ArrayList Fade option

### ISSUE THREAD

**Issue by yKsenomorf** [CCBlueX/LiquidBounce1.8-Issues#1882]
For the color saturation: http://ksenomorf.tk/screen/u/h1FrYr.png should look like http://ksenomorf.tk/screen/u/s6wOxS.png

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1670
