### ISSUE TITLE
Aimbot Settings / Command

### ISSUE THREAD

**Issue by SextupleTap** [CCBlueX/LiquidBounce1.8-Issues#1889]
The command for Aimbot is missing the FOV and TurnSpeed Parameters.

Also two extra options for Aimbot:

Jitter - Jitters mouse a little bit (Like Legit Aura's wobbly mouse movements, and like the old aim assist)

On Click -  Aims while holding down the attack button or while clicking, works in conjunction with jitter where jitter will only occur when clicking if on click is active.

The Jitter feature could be added to legit aura as well, and for the jitter function all together there could be a multiplier slider for how jittery it is, (maybe 0.1 to 2.0)

This is not for being a ghost client, these are just features that sound cool / nice to have...

**Comment by Marco-MC** [comment]
Jitter: https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1893
OnClick: https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1894
Missing Commands: https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1895
