### ISSUE TITLE
More Hypixel Update

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1891]
https://www.youtube.com/watch?v=7Er8j9o5UlE

fly/criticals/tower

**Comment by Marco-MC** [comment]
Fly == LiquidBounce has already one. (Select Fly Hypixel mode)
Criticals == LiquidBounce has already one. (Select Criticals Packet mode)
Tower == LiquidBounce has already one. (Select Tower motion mode)

**Comment by Teals53** [comment]
fly = BAN
criticals = Criticals toggle false
tower = Tower Type Jump

BAD AUTOSETTİNGS UPDATE PLS

**Comment by scorpion3013** [comment]
I'm playing with autosettings and I get banned after like 30-40mins so....
They're good autosettings. Just don't use noslowdown and no Autoblock if
you want to be more safe.


Teals53 <notifications@github.com> schrieb am Di., 6. März 2018, 17:24:

**Comment by Marco-MC** [comment]
The fly is working you idiot.

**Comment by Teals53** [comment]
yes its working but ı am banned işf use fly
