### ISSUE TITLE
Remove EmptyMessage Module

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1909]
Only working in singleplayer

**Comment by Teals53** [comment]
Dont Remove PLS

**Comment by Marco-MC** [comment]
Doch, es geht auch auf manchen Servern... z.B poke.sexy

**Comment by SenkJu** [comment]
Nein, tut es nicht...

**Comment by SenkJu** [comment]
JUNGE ES GEHT NICHT

**Comment by Teals53** [comment]
DONT REMOVE PLS because it is a useful feature :(

**Comment by Marco-MC** [comment]
![s1](https://img.liquidbounce.net/moc/idea64_2018-03-08_13-22-06.png)
![s2](https://img.liquidbounce.net/moc/idea64_2018-03-08_13-22-22.png)
![s3](https://img.liquidbounce.net/moc/idea64_2018-03-08_13-22-40.png)
