### ISSUE TITLE
TrendE NCP Speed nachcoden

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#191]
-TrendE speed bitte einfügen wenn du nicht zu faul bist.

-Longjump mode, dieser der so "glided". Für NCP.

Würde mich freuen wenn du die Sachen einbaust. :)

**Comment by Marco-MC** [comment]
Und dann noch einen GommeHD ForceOp und einen NCP Teleport und einen PayPal Hack. Zum mitnehmen oder hier?

**Comment by scorpion3013** [comment]
Ja gerne, geht auch ein force op für Rewinside ?

**Comment by Marco-MC** [comment]
#179

**Comment by RealFantaCoke** [comment]
Marco, du solltest die Ideen auch mal ernst nehmen.
Es war ein ganz normaler Vorschlag.

**Comment by RealFantaCoke** [comment]
Marco, du solltest die Ideen auch mal ernst nehmen.
Es war ein ganz normaler Vorschlag.

**Comment by Marco-MC** [comment]
https://www.youtube.com/watch?v=XUjjiiD3gDs
Hm. Ich weiß net, ob ich das so leicht nachgecoded bekomme...
