### ISSUE TITLE
ESP: Team Members Color & Bots ignored

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1910]
Team Mebers should have a different colored ESP when Teams is enabled and Bots should not be highlightes by ESP at all.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2304
and Bots ignored: https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2241
