### ISSUE TITLE
Value XXXXX dont found in module YYYYYYY.

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1912]
need update autosettings

**Comment by Marco-MC** [comment]
... dude which autosettings you mean?
I can't help you without informations.

**Comment by Teals53** [comment]
you can see errors by trying all automatic settings :) but ı make a video

**Comment by SenkJu** [comment]
we will fix the autosettings over time. could you give me a list of errors?

**Comment by Teals53** [comment]
I'il send it tomorrow.
