### ISSUE TITLE
[Scaffold] [Zitter] Smooth mode fix

### ISSUE THREAD

**Issue by Nvaros** [CCBlueX/LiquidBounce1.8-Issues#1921]
The lateral movements of the zitter smooth modes aren't regularly, i. e., yo tendencially move further to one side than to the other one.

**Comment by Leejames2305** [comment]
Yeah , It will automatically slightly move to the other side .

**Comment by Marco-MC** [comment]
There is no bug.

**Comment by Nvaros** [comment]
There is indeed a bug; just stand still and you will move a bit more to a certain direction than to the other one. Annoying because lateral movements caused by keyboard (A and D") is blocked, i. e., you can't prevent that from happening.
