### ISSUE TITLE
NoRotateSet: RotConfirm & NoZero & Invaild rotation option

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#1924]

**Comment by Marco-MC** [comment]
Was? Was für ein alter Mode?

**Comment by scorpion3013** [comment]
Der norotateset von b40 rotatet einen auf Mineplex trotzdem ziemlich oft.
Der alte tat dies nicht.

Marco MC <notifications@github.com> schrieb am Fr., 9. März 2018, 09:34:

**Comment by Marco-MC** [comment]
Added
