### ISSUE TITLE
LiquidChat is Spamming Packets

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1927]
https://streamable.com/6giia
https://streamable.com/6giia

**Comment by Marco-MC** [comment]
Also, der Bug scheint lediglich in der obfuscated b40 zu sein.
Ist also möglich, dass die obfuscation schuld ist... Ich werde mir den Code von LiquidChat mal angucken, wenn er obfuscated ist.

**Comment by Marco-MC** [comment]
Okay, nein quit.
ImFrozen war auf dem Poke TestServer... Poke leuft auf 54.36.131.183:1337....
Er dachte das wäre LiquidChat...
LiquidChat ist aber: 94.23.164.211:1337
