### ISSUE TITLE
İtemESP Glow Option

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1930]

**Comment by Teals53** [comment]
I will add screenshot or video tomorrow

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/96

**Comment by Teals53** [comment]
@Marco-MC not this like this
http://prntscr.com/k7j52m

**Comment by Teals53** [comment]
@Marco-MC Up
