### ISSUE TITLE
Vanilla Skybox Clipping

### ISSUE THREAD

**Issue by SextupleTap** [CCBlueX/LiquidBounce1.8-Issues#1932]
The Vanilla Skybox clips through MCPatchers (Custom Texture packs) skybox (bug did NOT happen from the first public version to b39 and started happening in b40). The angle you look effects the way the vanilla skybox clips. Also the images have player information censored...

![2018-03-08_10 00 04](https://user-images.githubusercontent.com/36042986/37234674-2bac07b0-23c7-11e8-975b-797fc3f91f68.png)
![2018-03-08_10 00 32](https://user-images.githubusercontent.com/36042986/37234676-2e38d904-23c7-11e8-91dd-744bad6e67bf.png)

**Comment by Marco-MC** [comment]
Fixed.
