### ISSUE TITLE
More Commands

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1934]
AutoClicker Left Right Jitter Command
AutoLeave Mode
AutoPot Delay Mode OpenInv
AutoSoup Delay OpenInv
BowAimbot TargetMode
Criticals Delay Command
.fastbow Command
KillAura RangeSprintReducement Command
Velocity Reverse2Strenght Command
.derp Command
better .esp Command
ı dont write all commands

and much much more

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2157
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1597
