### ISSUE TITLE
TabGUI Options

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1943]
Diese H: Option soll nur bestimmen wo die TabGUI ausfährt (Allso nach links oder rechts) Wie der Text Aber ausgerichtet sein soll, soll man extern bestimmen können (Also ob er nach rechts links oder mittig ist)

**Comment by Marco-MC** [comment]
Die H und die V Option sind für jedes Element, ein Option als Anhaltspunkt von welcher Screen Seite er die Position des Elementes berechnen soll.
