### ISSUE TITLE
Ingame Changelog

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce1.8-Issues#1954]
"entweder ein normaler changelog oder wenigens ein kleines changelog wo man danm zum milestone weiter geleitet wird" ~The unreal barbiehunter1337#9614

**Comment by Fryhyi** [comment]
👍

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/180
