### ISSUE TITLE
Custom Fly

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1965]
Man soll im CustomHUD-Editor auswählen können, ob man eine kleine oder eine große Hotbar haben möchte.

Es soll einen Custom-Item-Creator (wie in Pyrite: https://reinerwahnsinn.com/hackerkit/index.html) geben, womit man sich eigene Items wie z.B. Tränke, Schwerter, Rüstung, etc. erstellen kann (am besten via GUI).

Ein Custom-Fly wäre nicht schlecht (wie der Custom-Speed, nur als Fly) mit folgenden Möglichkeiten:

1. Höhe [Y]
2. Geschwindigkeit ["Speed"]
3. Timer [1-50?]
(wenn euch mehr einfällt, einfach dazupacken).

**Comment by SenkJu** [comment]
Es gibt .give im Client. Nimm irgendeine Item Generator Seite und gib dir das Item damit.

**Comment by superblaubeere27** [comment]
Weiß du was? Der "Hackerkit" creator von reinerwahnsinn is fürn Arsch, aber Tuneor wollte mal einen Client mit so einer Funktion machen. https://www.youtube.com/channel/UCLeaaJFqJhUGILamxP0AutQ

**Comment by Marco09MC** [comment]
Es wäre zwar gut, aber ich denke ein Custom Fly umzusetzen ist mit Einstellungen deutlich problematischer als wenn man es über ein Script macht.
