### ISSUE TITLE
Gui Suggestion

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1967]
İf You Open + (Mode/Bypass) İts Need To Save But Not Save ?

**Comment by SenkJu** [comment]
What do you mean?

**Comment by Teals53** [comment]
I Make Video Tomorrow

**Comment by Teals53** [comment]
ı dont have time for make a video sorry for delay :(

**Comment by Marco-MC** [comment]
I know, what you mean.

**Comment by Teals53** [comment]
k thx

**Comment by Marco-MC** [comment]
Added
