### ISSUE TITLE
FastBreak And FastPlace Suggestion

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1968]
Customize Speed

**Comment by WistarWolf** [comment]
#1221

**Comment by scorpion3013** [comment]
FastPlace just removes the delay from minecraft.... Just use the Autoclicker if you want a delay.

**Comment by Teals53** [comment]
What ?

**Comment by WistarWolf** [comment]
FastPlace doesn't speed up the placing speed, it removes only the placing dely from minecraft

**Comment by Teals53** [comment]
oh ok thx

**Comment by SenkJu** [comment]
#1221 duplicated
