### ISSUE TITLE
 scrollbar in options of moduls

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1970]
for example there are many speed types so it would be easier if you would add a scrollbar to the options

**Comment by WistarWolf** [comment]
Wie wäre es, wenn sich die ClickGUI Scale auch auf die Settings der Modules ausübt

**Comment by RealFantaCoke** [comment]
A very good idea, thanks for publishing :-)

**Comment by superblaubeere27** [comment]
Would be nice

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2659
