### ISSUE TITLE
AutoTool Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#1971]
I Look Block Automatic Select Pickaxe But I Dont Break Block I Only Look Block ?

**Comment by Marco-MC** [comment]
What do you mean?

**Comment by Teals53** [comment]
in older versions, only when I started to break the block, he would take the necessary tool in my hand, but now I have to look at the block.

**Comment by Teals53** [comment]
I will prepare a video for a better explanation

**Comment by Teals53** [comment]
dont close pls

**Comment by Teals53** [comment]
@Marco-MC https://youtu.be/vcH5P1qynCg

**Comment by Teals53** [comment]
@Marco-MC Up

**Comment by Marco-MC** [comment]
Fixed.
