### ISSUE TITLE
How to use .autoclicker

### ISSUE THREAD

**Issue by Leejames2305** [CCBlueX/LiquidBounce1.8-Issues#1973]
Please give me a example . I am so noob at this .

**Comment by Teals53** [comment]
you can open this in gui and you hold left mause button

**Comment by Leejames2305** [comment]
No , I want the command . Sometimes my mouse cant adjust it in guide so I want the commands .

**Comment by Leejames2305** [comment]
*GUI

**Comment by Teals53** [comment]
Use Trigger ?

**Comment by Marco-MC** [comment]
.autoclicker mincps 5
.autoclicker maxcps 10

**Comment by Leejames2305** [comment]
Thanks
