### ISSUE TITLE
Gomme AutoBan.

### ISSUE THREAD

**Issue by Fryhyi** [CCBlueX/LiquidBounce1.8-Issues#1974]
When you use Switch mode in Aura, and, for example, there are two or more players in front of you, and you enter into battle with them, Gomme gives you a ban. The same thing happens with Single Aura, but if you kill the players one by one, expecting everyone separately, everything will work fine, and there will be no ban (I personally checked, I played 6 full games on QSG and did not get autobann). I wanted to say that Killaura on Gomme works fine and without autobann, just put the mode of the single and try as much as possible avoid the big pvp, otherwise you will get autobanned.

And yes, Marco, is it possible to correct it? Thanks ;)

Sorry for my maybe broken english :)

**Comment by Marco-MC** [comment]
I changed it for the first.
I will check it later.

https://github.com/CCBlueX/FileCloud/commit/256eef845486c235dfa38ba8f949481ede5ce4d9

**Comment by spaik66** [comment]
Fryhyi , have you tried the killaura switch or single mode with priority health. That means testing the MOD idea of start hitting one till he dies then change, or giving hits to the one that is more time closer till he gets out the hit area then change to the other.. to confuse the autoban checker?? That will give us more full understanding i believe.

**Comment by Fryhyi** [comment]
spaik66, nice idea. Thanks. I'll test it our soon.
