### ISSUE TITLE
GUI Search Field

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1975]
Ein Suchfeld für die ClickGUI - für Module & Optionen.
Neben die Suchergebnisse am besten noch schreiben, ob es sich um eine Option oder ein Modul handelt.

Nicht zwingend notwendig, wäre allerdings sehr praktisch (besonders für nicht so erfahrene Leute).

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2659
