### ISSUE TITLE
Wie funktioniert der BufferSpeed?

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1976]
Hey,

kann mir jemand bitte mal erklären, wie der BufferSpeed funktioniert, warum er nicht mit als Option unter "Speed" vorhanden ist und wozu er nötig ist?

Danke schon mal im Voraus.

**Comment by scorpion3013** [comment]
Das ist der Slabspeed nur halt mit geschwindigkeit beibehalten.
