### ISSUE TITLE
Fishing RodAimBot 

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#1981]
It would be nice if in time pvp fishing rod automatically took in the hand, hit the opponent and automatically switched to the sword. And so all the time until you kill the enemy. You could add something like a slider that regulates with what frequency the fishing rod will automatically be taken in hand and hit the enemy.

**Comment by superblaubeere27** [comment]
Oh ein Reinerwahnsinn Zuschauer. Ich habe diese Funktion bereits mal gecodet.

**Comment by Fryhyi** [comment]
Reinerwahnsinn has nothing to do with it. I liked to play with Ghost clients (like Rupture) and loved to use this function (RodAimBot). Sometimes she really helped in pvp. It would be very cool if you added it to the liquidbounce. ( for me :))

**Comment by superblaubeere27** [comment]
Ok
