### ISSUE TITLE
EaZy Crasher

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#1988]
Bau mal den Crasher der im EaZy Client war in LB ein. Der funktioniert noch auf manchen Servern. Vergess den Regler für die crash Stärke nicht.

**Comment by superblaubeere27** [comment]
Was macht der denn? Wie funktioniert er?

**Comment by QWER16** [comment]
Weiß ned der halt: [https://www.youtube.com/watch?v=_ouqvKZqZH0](url)

**Comment by QWER16** [comment]
Der geht noch auf nen paar unbekannteren servern

**Comment by QWER16** [comment]
wird aber warscheinlich eh niemand außer ich benutzen

**Comment by Marco-MC** [comment]
ServerCrasher: BookFlood
