### ISSUE TITLE
AAC Glide

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#1989]
Geht der Glas highjump noch? Wenn der noch geht könnte man aus dem glide von eaglletshacks und dem highjump von superblaubeere einen guten nutzbaren gomme glide machen.

**Comment by QWER16** [comment]
Wenn der highjump nicht mehr geht den glide trotzdem hinzufügen.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2004
