### ISSUE TITLE
ShaderESP Bug

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#1990]
http://prntscr.com/it0iwb
Idk ob das relevant ist, aber ich hab ne intel hd graphics. kp ob es daran liegt

**Comment by SenkJu** [comment]
Das besondere von Shadern ist, dass sie direkt auf der Grafikkarte laufen. Wenn du keine hast, gehen die nicht. Kann man nicht fixen.

**Comment by WistarWolf** [comment]
Achso k
