### ISSUE TITLE
AltManager Player Head Preview not working anymore

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#1994]

**Comment by Marco-MC** [comment]
`http://skins.minecraft.net/MinecraftSkins/Notch.png` ist broken, deshalb können keine Skins geladen werden.

**Comment by Marco-MC** [comment]
Okay, ich muss das zu `http://textures.minecraft.net/texture/787c461e6466e137ab34d9917a1b6e1ba597e57f2d6dd027c04daaac1a19fa4e` ändern, die Frage ist... was in dem hash steht.

**Comment by Marco-MC** [comment]
Man sendet eine Anfrage an: https://sessionserver.mojang.com/session/minecraft/profile/<uuid> dann bekommt man bei textures einen base64 string. Diesen einfach base64 decode und dann kriegt man wieder eine json wo dann die url drin steht.

**Comment by Marco-MC** [comment]
Added

**Comment by Teals53** [comment]
You Removed Head Preview @Marco-MC

**Comment by Marco-MC** [comment]
@Teals53 ... ![](https://img.ccbluex.net/moc/firefox_2018-05-17_16-48-56.png)

**Comment by Teals53** [comment]
@Marco-MC Sorry :(
