### ISSUE TITLE
Source für bypasses

### ISSUE THREAD

**Issue by ImDrops** [CCBlueX/LiquidBounce1.8-Issues#1995]
Hey, ich würde euch gerne den Source für folgende bypasses, die ihr alle für LiquidBounce verbessern/einfügen könnt, schicken:
Gomme 2 Block step
Der Timer Gomme Glide, der ca 100% schneller ist als die anderen Glides im moment
Ein AAC Fly, der z.B. auf Gomme in Skywars & Bedwars funktioniert (man Braucht Cobwebs oder Wasser wegen FallDamage)
Gomme Nofall der meistens mit 0 Damage Funktioniert
Die Source für den Cubecraft Fly den man schon in einigen Videos gesehen hat.
und eine extrem Interessante Entdeckung auf Gomme, die man eventuel zu z.B. einem Fly weiterentwickeln kann (ich bin nur zu blöd dafür)
Ich habe dafür keinen nutzen, allerdings würde ich euch alles gerne Privat schicken, da ich sehr sehr viel Zeit dafür verwendet habe.
Wie mach ich das am Besten?
Hoffe ihr könnt es verwenden,
ImDrops

**Comment by Marco-MC** [comment]
Schreib mich auf Discord an: Marco09MC#4763 (Discord Server: https://discord.gg/qp8nN5r)
