### ISSUE TITLE
Missing module commands

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#2010]
.wallspeed, .wallclimb usw...
Mach einfach einen Generator für sowas

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1597

**Comment by Marco-MC** [comment]
"Mach einfach einen Generator für sowas"

Junge, manche Values haben nen wichtigies limit manche nicht, ich kann nichts einfach einen globalen Value Generator machen. Ebenfalls müssen manche values z.B unter einem anderen Value sein. (maxcps und mincps) etc
Es gibt sau viel zu beachten.
Es ist nicht "Mach einfach", wie du dir das so vorstellst.

**Comment by Marco-MC** [comment]
An sich ist es aber simpel.

**Comment by Marco-MC** [comment]
Es ist lediglich kompletter Krebs, weil ich dann wieder so viel umändern muss weil lb so viele values hat.

**Comment by superblaubeere27** [comment]
Ok
