### ISSUE TITLE
Client Resolution

### ISSUE THREAD

**Issue by Leejames2305** [CCBlueX/LiquidBounce1.8-Issues#2013]
The resolution does not changed even I changed the settings in the launcher. It stay the same resolution everytime .

**Comment by Marco-MC** [comment]
This is no bug, I set the resolution to w: 1067 h: 622.

**Comment by Marco-MC** [comment]
I changed it now, it will just set the resolution to w: 1067 h: 622 if width is lower than 1067 or height is lower than 622.
