### ISSUE TITLE
Color Name Bypass

### ISSUE THREAD

**Issue by CrashedLife** [CCBlueX/LiquidBounce1.8-Issues#2014]
Hallo ich habe ein ColorName Bypass gefunden (Ich möchte es nicht öffentlich schreiben, wenn hier einer aus dem Team das gerne wissen möchte schreibt mich bitte Privat an).

Also das man ein Farbigen Namen hat und man auf Servern nicht gebannt werden kann!

Könnt ihr das gerne als Feature auch einbauen?

**Comment by SenkJu** [comment]
https://discord.gg/WCCYt3 Schreib uns hier an

**Comment by CrashedLife** [comment]
Ich werde so bald wie möglich Marco oder dich anschreiben dir noch ein Schönen Abend :)

**Comment by Marco-MC** [comment]
Ich werde einfach denke einbauen, dass man mit Color Codes im Login Feld schreiben kann.

**Comment by Marco-MC** [comment]
So, habe einfach hinzugefügt das man beim Direct Login wenn man sich versucht als Cracked einzuloggen alle & Zeichen durch § ersetzt werden.

**Comment by Marco-MC** [comment]
![java_2018-05-05_02-06-59](https://user-images.githubusercontent.com/12410754/39657549-0f78c826-5009-11e8-8fba-dbda01d41ec0.png)
![java_2018-05-05_02-07-17](https://user-images.githubusercontent.com/12410754/39657550-10da2520-5009-11e8-8d64-386d231cbec6.png)
