### ISSUE TITLE
Add İtemESP Show Arrow

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2016]

**Comment by Teals53** [comment]
closed ? @SenkJu

**Comment by Teals53** [comment]
@Marco-MC Maybe You Add This :P

**Comment by Teals53** [comment]
@Marco-MC show only collectable arrows upupuppu

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
There is one problem.. the client can't know if the arrow is pickupable or not...

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2288 @Marco-MC
