### ISSUE TITLE
KeyBinds reseted

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#2019]
Bei mir werden manchmal immernoch keybinds resettet. Die meisten keys die resettet werden sind Numpad3 und Numpad4

**Comment by CrashedLife** [comment]
Stimmt wollte ich auch noch melden ist bei mir dauerhaft

**Comment by Leejames2305** [comment]
Same things happen to me , only some keybind will be auto reseted after quitting the game .

**Comment by Marco-MC** [comment]
Hm, also ich konnte nichts feststellen... Ich könnte mir lediglich denken, das ihr LiquidBounce nicht richtig beendet und somit die module keybinds nicht abgespeichert werden können.
Ich baue einfach mal ein, das er beim setzen eines Keybinds sofort diesen auch abspeichert.
