### ISSUE TITLE
Read me

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#2020]
1. Danke, dass ihr mich aus dem Team geworfen habt und mich danach einfach ignoriert habt. Sehr erwachsen von euch. 2. Wie habe ich euch mit dem NCP Scaffold Video geschadet? Hat es nur 1 Download verhindert? 3. Ich habe euch mit viel geholfen. Ohne mich hättet ihr darmals keine richtige Obf gehabt. 4. Was hat das jetzt gebracht? Nichts. Ich kann jetzt mehr Skid Videos machen und euch damit mehr schaden.

**Comment by superblaubeere27** [comment]
Btw: Wir können gerne nochmal Reden

**Comment by SenkJu** [comment]
Können nachher reden.

superblaubeere27 <notifications@github.com> schrieb am Sa., 24. März 2018,
19:11:

**Comment by superblaubeere27** [comment]
Danke @SenkJu
