### ISSUE TITLE
ClickGUI ModuleElement Show Bypass save 

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2025]

**Comment by Teals53** [comment]
Why Closed ? @SenkJu

**Comment by SenkJu** [comment]
Because it saves already

**Comment by Teals53** [comment]
No Not Saves İts Saves İf Open + But I Say İn Menu + For Example I Right Click Fly And Open Fly Menu Yes İts Saved But I Click Mode Button And Open Mode Menu But İts Not Saved Okey ?

**Comment by Teals53** [comment]
@Marco-MC Maybe You Add This :P

**Comment by Teals53** [comment]
@Marco-MC Up

**Comment by Teals53** [comment]
@Marco-MC Up

**Comment by Marco-MC** [comment]
I know what he mean, but I don't know if I add this useless save

**Comment by Teals53** [comment]
:/

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2659

**Comment by Teals53** [comment]
<3
