### ISSUE TITLE
New Esp

### ISSUE THREAD

**Issue by Gegreenpeaced** [CCBlueX/LiquidBounce1.8-Issues#2033]
Es wäre cool wenn es einen Esp Geben könnte, Der so wie damals in Xave ist. Mit einem Pelika oder irgendnem anderen Tier oder einem Youtuber eventl. Gleichmitte.

Wäre cool

MFG Julius aka. Gegreenpeaced

**Comment by Gegreenpeaced** [comment]
warum?

**Comment by Bircko** [comment]
unnötig af
