### ISSUE TITLE
.friend command

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2050]
.friend add [nick] and .friend remove [nick]

**Comment by SenkJu** [comment]
What are you trying to tell us with that?

**Comment by Teals53** [comment]
if ı need remove my friend ı need find him and click middle button

**Comment by Teals53** [comment]
why ı cant remove friends in command ?

**Comment by Teals53** [comment]
Why Closed ? @SenkJu

**Comment by Teals53** [comment]
Sorry İts Already Have But Not friend İts friends xD
