### ISSUE TITLE
AltManager Scrolling with Arrow Keys + Login with return

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2054]
Pls Add Up Down Button Up Button Upper Your Selected Account İn List

**Comment by SenkJu** [comment]
What do you mean?

**Comment by je5442904** [comment]
？？？

**Comment by Leejames2305** [comment]
It mean you can arrange the alt list

**Comment by Teals53** [comment]
Yes

**Comment by Teals53** [comment]
up or down

**Comment by Teals53** [comment]
I Cant Change My Alt Position How To Use ? @Marco-MC

**Comment by Marco-MC** [comment]
With your arrow keys...

**Comment by Teals53** [comment]
But I Only Go Up Or Down I Cant Change Alt Position ? @Marco-MC

**Comment by Teals53** [comment]
For Example My Alt List This

lslflfwowf
DPWPOAPW
457894586
+^&%+^&+^%

But I Need This List

+^&%+^&+^%
DPWPOAPW
lslflfwowf
457894586

**Comment by Teals53** [comment]
I wanted to change the sort

**Comment by Marco-MC** [comment]
oh you mean that...

**Comment by Teals53** [comment]
so ?

**Comment by Teals53** [comment]
@Marco-MC can you add this ? because you misunderstood me at first. :D

**Comment by Teals53** [comment]
PageUp And PageDown İs A Good Button For This @Marco-MC

**Comment by Teals53** [comment]
@Marco-MC Up :D

**Comment by Teals53** [comment]
@Marco-MC UPUPUPU

**Comment by Teals53** [comment]
@Marco-MC last up
