### ISSUE TITLE
Discord Spieleinladung 

### ISSUE THREAD

**Issue by Gegreenpeaced** [CCBlueX/LiquidBounce1.8-Issues#2060]
Ein Symbol in Discord, so wie bei Fortnite, mit dem man Leute auf seinen Server zum Cheaten einladen kann.

**Comment by scorpion3013** [comment]
Nicht möglich da dafür die Application von Discord verifiziert werden muss.
Da LiquidBounce aber ein Cheat ist wird dies nicht passieren. (Discord ist streng GEGEN Cheater)
