### ISSUE TITLE
fast aac tower

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2069]
https://www.youtube.com/watch?v=ZPuHhbzzrMk

**Comment by Janmm14** [comment]
@Teals53 Don't expect your language to stay on our issue tracker.

**Comment by Teals53** [comment]
@Janmm14 What ?

**Comment by Fryhyi** [comment]
Oh, old issue. I just wont to say what its just Motion tower in LiquidBounce
