### ISSUE TITLE
LiquidBounce Launcher 

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#207]
Also ein Launcher für LiquidBounce damit er keinen Obfusucater (oder wie auch immer man das schreibt)
man downloaded den  den Client und startet ihr mit dem Launcher

**Comment by FlorijonG** [comment]
da kann auch irgendwo Werbung seine, weil ihr euch ja so finanziert

**Comment by Marco-MC** [comment]
1. Wie du auch schon geschrieben hast wir finanzieren uns durch Werbung und daher können wir das nicht richtig umsetzen.
2. Ich kenne mich damit jetzt auch nicht richtig aus, aber man kann die jar einfach aus dem Arbeitsspeicher dumpen und somit hat man dann ne Unobfuscated LiquidBounce version. Also ohne Obfuscator geht da nichts.
3. So fauel muss man jetzt auch net sein einen Client wieder nomma runterzuladen... ._.

Für mich ist dieses Thema beendet und ich sage zu einem Launcher nein. Vielleicht in Zukunft, aber eigentlich nicht.
