### ISSUE TITLE
The "WatchCat" AntiCheat

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#2075]
It said that it can check liquidbounce
Obfu with allatori:
[Link](https://mega.nz/#!mI4GwbLb!bpY1UlUOwOe2K-nghlWUBS4TNZFQ2mWYH8bQ96R5Erk)
InvMove(LiquidBounce Special checks)
Killaura/ClickAura/MultiAura —— 
Aimbot —— 
AutoClicker —— 
AimAssist/Aimbot —— 
Criticals —— 
FightBot ——
NoVelocity —— 
FastBow —— 
Regen —— 
MachineLearning —— 
Reach —— 
Angle —— 

Scaffold —— 
Tower —— 
NoFall —— 
SkinDerp ——
FastPlace —— 
FastBreak ——
CivBreak —— 
Blink —— 

HeadLess —— 
Flight —— 
Glide —— 
Jesus —— 
Speed —— 
Timer —— 
Spider —— 
BoatFly —— 

Tracer —— 
ChestESP —— 
HealthTag —— 
Freecam ——

**Comment by cui0v0** [comment]
it's mc233.cn server's anticheat

**Comment by superblaubeere27** [comment]
Obfuscated by Allatori. This is good

**Comment by Marco-MC** [comment]
I will try out the AntiCheat and maybe make some bypasses. :)

**Comment by Marco-MC** [comment]
WatchCat is a NTAC Skid, haha.

**Comment by cui0v0** [comment]
What is NTAC?

**Comment by Marco-MC** [comment]
oh my god these false flags, haha xddd

**Comment by Marco-MC** [comment]
wtf dude this anticheat is so fucking shitty

**Comment by Marco-MC** [comment]
I can't even jump legit or something other

**Comment by Marco-MC** [comment]
and... I cant die...

**Comment by Marco-MC** [comment]
The KillAura workt for me fine, without any flags. :)
I also added a WatchCat Fly now.

**Comment by cui0v0** [comment]
That sounds amazing! :)

**Comment by Marco-MC** [comment]
And for scaffold:
![chk_jschl](https://user-images.githubusercontent.com/12410754/38769156-8bbb9514-3ffe-11e8-8df9-37dac2308ec3.png)

**Comment by CrackFileso** [comment]
@Marco-MC This AntiCheat is writed as AAC additions
