### ISSUE TITLE
New AAC Fly

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2076]
https://www.youtube.com/watch?v=vro9NXMLODQ

**Comment by Leejames2305** [comment]
It does not work in AAC 3.3.14 anymore , it will pull you down in a certain distance .

**Comment by superblaubeere27** [comment]
I made a Video about this. We already know about it

**Comment by Marco-MC** [comment]
LiquidBounce already have this fly xd
