### ISSUE TITLE
ArrayList Module Y Option

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#2077]
Dass man an einem Regler die Y Option der Modules in der arrayList selber bestimmen kann. Das ist dann z.b. hilfreich wenn man eine font hat bei der das module nicht ganz in der mitte der box ist. Die Box soll sich so gesehen dann beim verändern dieser Y Option nicht verändern, nur die Module Position. Und es soll auch nicht nur 0, 0.5, 1.0, 1.5 usw sein, sondern eben 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0 usw Da es ja manchmal auch ist dass das module nur ein kleines stück zu weit oben/unten ist.

**Comment by Marco-MC** [comment]
Sowas, wie 0.1 usw gibt es nicht. Lediglich immer 1, 2, 3, 4 etc.
Ich werde es aber einbauen.

**Comment by WistarWolf** [comment]
Okay

**Comment by Marco-MC** [comment]
Added
