### ISSUE TITLE
AntiVirus FalsePositives

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#2078]
[VirusTotal link](https://www.virustotal.com/#/file/e035f0418755f035317ca404bfd55de93ce0600042263abbfdf68683a3bf546b/detection)

**Comment by Marco-MC** [comment]
Sowas kann ich nicht beheben, bruh.

**Comment by superblaubeere27** [comment]
@Marco-MC öhm, man kann das als FP reporten

**Comment by Marco-MC** [comment]
Na dann, viel spaß.

**Comment by superblaubeere27** [comment]
Mache ich doch grade y ._. Und add mich zu CCBlueX ^^ (triggered)
