### ISSUE TITLE
Party und friend invite spammer

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#2093]
Spammer der versucht Spieler zu frienden oder in eine Party einzuladen. Also dass man dann alle Spieler in der Lobby in seine Party einlädt oder sie als Freund hinzufügt wenn man dass für den party invite braucht. War im sinergy b5 Client von d3sox

**Comment by WistarWolf** [comment]
du musst soweit ich weiß AtAllProvider an machen und dann z.b /friend add @all oder /friend add all machen

**Comment by Marco-MC** [comment]
AtAllProvider

**Comment by QWER16** [comment]
OK👍
