### ISSUE TITLE
Super-Duper Cube Expand-Scaffold

### ISSUE THREAD

**Issue by Fryhyi** [CCBlueX/LiquidBounce1.8-Issues#2097]
**# Of course, these Scaffold settings are much faster than those in .config cubecraft, but i do not think it's the limit ;)**  
Important!
Use only as Expand-ScaffoldWalk. I do not advise t go forward immediately after switching on. You just get the autoban from Sentinel in about 1-3 secconds after the starting of use Scaffold. 
Turn on Scaffold, wait a little, about a second (give the Scaffold to put 2-3 blocks) and after that you can safely run forward.
I played many games with these Scaffold-settings and did not get autobanned from Sentinel.
Settings:
Type > **Expand**
Delay > **0**
Autoblock **On**
Sprint **Off**
Swing  **On**
Eagle  **Off**
ExpandLenght  **5-6**
KeepRotation **On**
Zitter **On**
ZitterMode **Teleport**
ZitterSpeed  **0.18**
ZitterStrenght  **0.10**

Good luck **:)**   
https://prnt.sc/j64jzw

**Comment by SenkJu** [comment]
AutoBans me.
