### ISSUE TITLE
Killaura help

### ISSUE THREAD

**Issue by Niclas-Bacon** [CCBlueX/LiquidBounce1.8-Issues#2100]
Bei mir geht die Killaura nicht wenn ich was in der Hand hab also z.B. Schwert bei leerer Hand schlägt sie warum?

**Comment by scorpion3013** [comment]
Weil du eine nichtkompatible mod installiert hast... Wahrscheinlich eine mod von OrangeMarshall.

**Comment by Niclas-Bacon** [comment]
Danke
