### ISSUE TITLE
localautosettings save open/closed modules

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2102]
for example 

+Zoot toggle false
+Regen toggle false
 AntiBot toggle false
 Fly Toggle Fly
 FastClimb toggle false

**Comment by Marco-MC** [comment]
same system like the normal autosettings.

**Comment by cui0v0** [comment]
@Teals53 You can find and edit your localsettings in Minecraft files path of “%appdata%/.minecraft/LiquidBounce-1.8/settings”

**Comment by Teals53** [comment]
@cui0v0 ?
