### ISSUE TITLE
Secondary Inventory: Search function not working

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2103]
search not working I need to find the head I set.

**Comment by Marco-MC** [comment]
[](https://img.ccbluex.net/moc/java_2018-04-25_14-38-00.png)
Working for me?... ._.

**Comment by Teals53** [comment]
But ı cant write anything why _?

**Comment by Marco-MC** [comment]
I don't know, why you can't write there.

**Comment by Teals53** [comment]
@Marco-MC you can find any fix ?

**Comment by Teals53** [comment]
@Marco-MC Find Anythnig For This Reason ?

**Comment by Teals53** [comment]
@Marco-MC Already Not Working Anybody..... İts Only Working For You xD

**Comment by Teals53** [comment]
@Marco-MC Pls Find Error And Fix
