### ISSUE TITLE
Tick KillAura

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2105]
İts Really İmportant Because İts Break Armor Perfectly

for example jigsaw have a tick aura and attack delay options and jigsaw really fastly break armor some servers not use anti-cheat (only simple ncp movement) and you fight with

**Comment by Kodikusik** [comment]
+1

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/129

**Comment by Teals53** [comment]
add pls :( <3

**Comment by Kodikusik** [comment]
add pls
