### ISSUE TITLE
NameTags and ESP work wrong in some servers

### ISSUE THREAD

**Issue by cui0v0** [CCBlueX/LiquidBounce1.8-Issues#2108]
NameTags and ESP can detect bot but can't detect normal players. So that although Antibot can Bypass bot but killaura couldn't attack players :(  Because of the Name tags were different from most servers so that client couldn't detected normal players.
![2018-04-22_10 57 49](https://user-images.githubusercontent.com/29875719/39090890-3b62c33e-461c-11e8-823a-991cfcbc1a25.png)
![2018-04-22_10 57 20](https://user-images.githubusercontent.com/29875719/39090884-33c1f046-461c-11e8-9b82-7abca35657de.png)
![2018-04-22_10 58 10](https://user-images.githubusercontent.com/29875719/39090892-43013ba2-461c-11e8-97d8-0c9760a760f1.png)

**Comment by scorpion3013** [comment]
Try to put "Dead" on in the Targets.
