### ISSUE TITLE
Better Projectile and Autoshoot

### ISSUE THREAD

**Issue by Cloak3** [CCBlueX/LiquidBounce1.8-Issues#211]
Can you make the Projectile module show trajectories of other players' arrows and show the trajectory of the arrow while the bow is not fully loaded? And an Autoshoot module. Both of two modules can be found in the Wolfram Client (wolfram-client.tk). Thanks!

**Comment by Marco-MC** [comment]
AutoShoot already in LiquidBounce. Enable AutoBow!
And yes I can add a option for projectiles for other players.
