### ISSUE TITLE
Rename Modes

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2118]
Step Mode AAC_334   -->  AAC3.3.4
Liquidwalk Type AAC_3.3.11 ---> AAC3.3.11

Because All Fly And Other Modes Write Like AACX.X.X

**Comment by Marco-MC** [comment]
um oops xd

**Comment by Marco-MC** [comment]
sry

**Comment by Teals53** [comment]
euhehue xD
