### ISSUE TITLE
Killaura, Legit autoblock mode

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2121]
Nur zwischen Hits blocken und nicht während des Schlagens blocken.

**Comment by Teals53** [comment]
duplicated ? https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1865

**Comment by Marco-MC** [comment]
... Die Killaura blockt nicht während man schlägt. Das ist ja auch nicht der Sinn, hinter AutoBlock... sondern, wie du schon sagtest, dass sie zwischen den Hits blockt.
