### ISSUE TITLE
Auto MLG

### ISSUE THREAD

**Issue by MrGcGamer** [CCBlueX/LiquidBounce1.8-Issues#2124]
a auto MLG module would be very nice for some situations, I would recommend a field to switch between cobweb and water.
And with that a toggle for mlg items in the invcleaner would be helpful

**Comment by RaminDemirtas** [comment]
Any news about that?

**Comment by superblaubeere27** [comment]
@RaminDemirtas no

**Comment by CzechHek** [comment]
Added, close this.

**Comment by Teals53** [comment]
lol two same issues in one milestone @superblaubeere27
