### ISSUE TITLE
More Regen Options

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2132]
Idk Lb Have This ?

https://hizliresim.com/XPABoR

**Comment by Marco-MC** [comment]
[](https://img.ccbluex.net/moc/firefox_2018-04-25_14-34-22.png)
Website dosn't work.

**Comment by Teals53** [comment]
its work for me ?

**Comment by Teals53** [comment]
http://prntscr.com/j9zkex

**Comment by Marco-MC** [comment]
!()[https://img.ccbluex.net/moc/java_2018-04-25_14-38-56.png]

**Comment by Marco-MC** [comment]
Speed is the same like packets.
