### ISSUE TITLE
What does it do ?

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2138]
AtAllProvider BugUp And Liquids ?

And İn Killaura RayCast RayCastIgnored LivingRayCast Predict RandomCenter Mark

That's all I don't know.

**Comment by BongHit** [comment]
AtAllProvider lets you do a command in chat, like /msg @a, and it will message every online player that.

BugUp abuses anticheat to prevent you from being able to fall. Useful in skywars/etc.

Raycast, RaycastIgnored, LivingRaycast all have to do with various trick anticheat use to detect killaura... namely (could be wrong here) hitting entities that have an entities between you and them... you should have hit both, but you hit behind. The raycast checks can fix that by also hitting the in-between entity.

Predict helps predict movement, and thus where to hit, if I'm not mistaken.

Mark shows the overlay floating over the entity your are attacking.

RandomCenter I'm not quite sure about.

**Comment by Teals53** [comment]
Thx <3

**Comment by Teals53** [comment]
How To Use AtAllProvider And BugUp I Open BugUp But I Cant Work This ?
