### ISSUE TITLE
New BackGround Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2158]
Not Only This Error , This Bug Work All Connection Errors
http://prntscr.com/je4vpf
http://prntscr.com/je4ypd

**Comment by Marco-MC** [comment]
!()[https://img.ccbluex.net/moc/idea64_2018-05-06_02-22-39.png]

**Comment by Marco-MC** [comment]
![](https://img.ccbluex.net/moc/java_2018-05-06_02-29-30.png)

Fixed.
