### ISSUE TITLE
Add NoSwing Module (ServerSide option) + NoSwing command

### ISSUE THREAD

**Issue by TheRealDAT** [CCBlueX/LiquidBounce1.8-Issues#216]
NoSwing:
Ich hätte gerne einen NoSwing Client-Side der unter dem Modul "SwingAnimation" wäre.

HitAnimation:
Also die Idee hab ich von Amera und vielleicht kann man auch Speed Changen wenn es rein kommen sollte. Und es müsste dann auch unter SwingAnimation sein.

MFG

DAT

**Comment by Marco-MC** [comment]
1. Idee:
Werde ich als NoSwing Modul einbauen. Indem kann man dann auswählen, ob nur ClientSide oder auch ServerSide.

2. Idee:
Nein.

**Comment by Marco-MC** [comment]
Added. :)
