### ISSUE TITLE
Add description

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2161]
X-ray and much more

**Comment by Marco-MC** [comment]
![](https://img.ccbluex.net/moc/idea64_2018-05-06_21-25-02.png)

X-Ray already have a description, currently there a no module without an description.

**Comment by Teals53** [comment]
@Marco-MC Up  http://prntscr.com/jjvypv

**Comment by Teals53** [comment]
@Marco-MC Up İts Already Not Show İn b50
