### ISSUE TITLE
CCBlueX Team und User Anzeige

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#218]
Wenn man Ingame ist und ein CCBlueX Team Mitglied auf dem selben Server ist steht vor/über dem Spieler Namen z.B. [LBDev], [LBSup] usw. 
Und bei normalen Usern die gerade LiquidBounce verwenden steht z.B. [LBUser]

**Comment by TheRealDAT** [comment]
und
-ClientFriends Modul.
-Das es bei jedem User angezeigt wird [LB] zb.
-Das wär vielleicht kompliziert aber IGN also eigenen namen und dann auch im LiquidChat und auch für die LiquidBounce im Nametag der name.

**Comment by FlorijonG** [comment]
und ein Login System sodass nicht jeder Spammen kann und Freunde leichter erkennen kann.

**Comment by TheRealDAT** [comment]
Jo das war bei meinem "comment" eigentlich selbstverständlich aber trotzdem könnte jeder sich einen neuen Account holen und Spammen... (Ich hatte eine Idee Marco :/ aber ist sehr umständlich und damit verdienst du mehr Geld.)

**Comment by Marco-MC** [comment]
Ne, ne.
