### ISSUE TITLE
Bot: Auto Switch name, armor and armor enchants

### ISSUE THREAD

**Issue by cui0v0** [CCBlueX/LiquidBounce1.8-Issues#2194]

**Comment by cui0v0** [comment]
![2018-05-](https://user-images.githubusercontent.com/29875719/39952843-05c1b54e-55d2-11e8-98f1-975dd9cde16b.jpg)

**Comment by cui0v0** [comment]
When I died, the bot name has changed.
![2018-05-12_10 53 59](https://user-images.githubusercontent.com/29875719/39952982-380da650-55d4-11e8-8f8b-05aa157a39bb.png)
![2018-05-12_10 54 49](https://user-images.githubusercontent.com/29875719/39952981-37f526d4-55d4-11e8-82ee-d91cd38f6b2c.png)
![2018-05-12_10 54 56](https://user-images.githubusercontent.com/29875719/39952983-393c312c-55d4-11e8-9905-58e531dcc1eb.png)
![2018-05-12_11 02 57](https://user-images.githubusercontent.com/29875719/39952985-3ac5e5ba-55d4-11e8-8004-4d0a2d8b8469.png)

**Comment by cui0v0** [comment]
Armor had changed, too.

**Comment by cui0v0** [comment]
In b48, I has a config can bypass the bot. But it sometimes detected common players are bots.
Maybe the bot name is a color name, or the bot is snaking.

**Comment by YuiPuP** [comment]
I feel I can't get bypass at all
