### ISSUE TITLE
Add these modules

### ISSUE THREAD

**Issue by MrShevtsov2k** [CCBlueX/LiquidBounce1.8-Issues#2199]
Killaura:
Raytrace
Start Looking
Switch Ticks from the slowly
Change the module Turnspeed to Yaw Speed and Peetch Speed
Antibot:
reflex invisibles bot

**Comment by SenkJu** [comment]
RayTrace: LiquidBounce's KillAura has RayCast. That is what you mean.
StartLooking: What is that supposed to be?
SwitchTicks: Use HurtTime.

**Comment by MrShevtsov2k** [comment]
Startlooking is that you spin for a certain time before hitting. All this is to bypass the anticheat reflex.

**Comment by MrShevtsov2k** [comment]
If that, this anti-cheat is on the server mc.liecloud.me on smasher

**Comment by Fryhyi** [comment]
mc.litecloud.me * So shit server
