### ISSUE TITLE
X-Ray And Blink Description

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2204]
I Know You Add But I Cant See İn Game

**Comment by CrackFileso** [comment]
what?

**Comment by Teals53** [comment]
? -_-

**Comment by Teals53** [comment]
@Marco-MC Why Closed ?

Proof: http://prntscr.com/jjvypv

**Comment by Teals53** [comment]
@Marco-MC UpUpUp

**Comment by Teals53** [comment]
@Marco-MC UPUPUPUPUPPUPUPUPUP

**Comment by Marco-MC** [comment]
https://img.ccbluex.net/moc/java_2018-06-23_16-02-35.png
https://img.ccbluex.net/moc/java_2018-06-23_16-03-01.png

**Comment by Teals53** [comment]
@Marco-MC Pls Connect
TeamViever İnfos
510 550 813
4172

**Comment by scorpion3013** [comment]
![javaw_2018-06-23_18-20-14](https://user-images.githubusercontent.com/27446646/41811550-1c455f08-7712-11e8-9b9b-48164c69e02c.png)
![javaw_2018-06-23_18-20-22](https://user-images.githubusercontent.com/27446646/41811551-1df28dbc-7712-11e8-9e09-31dbb2a4975c.png)
Sadly he is right, there is no description visible for us. ( Tested in b50)

**Comment by Teals53** [comment]
@Marco-MC Up
