### ISSUE TITLE
Partikel

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#221]
Bitte ein Extra Modul um die Critical Partikel und die Sharpness Partikel zu erhöhen.
Wieso in ein einem Modul ? Damit es auch wenn man legit spielt geht und auch geht wenn man Criticals nicht an hat. Am besten dort die Option ob Criticals Partikel oder Sharpness Parikel oder beides erhöht werden soll. VIELEN DANK

**Comment by Marco-MC** [comment]
Sorry, aber nein.
