### ISSUE TITLE
Remove Old Fly Modes

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#2222]
They do not bypass anymore, are therefore completely useles and make it much harder to see all modes on smaller screens.

**Comment by scorpion3013** [comment]
But that makes LiquidBounce so universall, there are still a few server with old/bad anticheats.
But flymodes that were made for Poke should be removed.

**Comment by SenkJu** [comment]
For example?

**Comment by MrGcGamer** [comment]
You could remove the old Cubecraft flymodes
