### ISSUE TITLE
Hypixel Criticals(With code)

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#2227]
https://ghostbin.com/paste/gyg3w
delay 490MS

**Comment by CrackFileso** [comment]
I will make a liquid Scripts to set it work
But how to use Timer delay in liquid Scripts
@Marco-MC

**Comment by Marco-MC** [comment]
Added

**Comment by CrackFileso** [comment]
@Marco-MC Might got Pathed any time,So set it test.
