### ISSUE TITLE
ClientFriends Alias Tab-Autocomplete

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#2235]
Wenn man z.B. /party macht und dann <Tab> drückt, sollten die Namen, die im Client als Friends drin sind, zuerst kommen und dann die Namen der anderen Spieler auf dem Server

**Comment by Marco-MC** [comment]
Ich verweise immernoch darauf, das dies von Serverbesitzern Ausgenutzt werden könnte.

**Comment by SenkJu** [comment]
Er meint .friend Friends

**Comment by henrydatei** [comment]
In wiefern könnte das von Serverbesitzern ausgenutzt werden? Können die sehen, was ich zuerst im Autocomplete habe?

**Comment by Marco-MC** [comment]
Ich hatte es falsch verstanden wegen dem Titel des Issues.

**Comment by Marco09MC** [comment]
Added

**Comment by Marco09MC** [comment]
https://axolotl.vip/tgLw/KwoweyhX.mp4

**Comment by henrydatei** [comment]
hm, also bei mir hängt sich das spiel auf, wenn ich das autocomplete nutzen möchte
