### ISSUE TITLE
[Request] ESP mode on "Teams" Module 

### ISSUE THREAD

**Issue by SextupleTap** [CCBlueX/LiquidBounce1.8-Issues#2241]
An option for the "Teams" Module to also ignore player ESP and Tracers.

Teams >
Scoreboard
Color
**Hide Esp/Tracer**

This will make your teammates not have ESP or tracers while those not on the same team will still have ESP/Tracers.

Edit:
Requests from others, under the anti-bots section, an option for the same thing above but with anything flagged as a "bot." (Can be toggled on/off), could be named something like:
Bots Ignore ESP/Tracers

**Comment by scorpion3013** [comment]
Samething also with Bots.
