### ISSUE TITLE
ESP Bug

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2248]
![javaw_2018-06-14_05-08-27](https://user-images.githubusercontent.com/27446646/41389415-0b68e836-6f91-11e8-8449-b7002a1fa2a1.png)
Esp Farbe: Lila
Modus: Outline und Wireframe

Ab und zu werden Spieler bei mir mit einer weißen esp outline gerendert obwohl die farbe lila ist.

**Comment by Marco-MC** [comment]
Sollte jetzt behoben sein.
