### ISSUE TITLE
[Request] "Reach" module improvements

### ISSUE THREAD

**Issue by SextupleTap** [CCBlueX/LiquidBounce1.8-Issues#2256]
#-1 Reach should be able to go from 3 to 6 instead of 3.5 to 6.

#-2 There should be a command for reach (.reach [value from 3 to 6]), the command will also deny any values that are under 3 or above 6.
Example: .reach 3.2

**Comment by Teals53** [comment]
And nofov need like this command improvements

**Comment by Marco-MC** [comment]
#-2 `.reach reach 3.2`
