### ISSUE TITLE
Font in chat

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#2265]
Wenns geht deaktivierbar

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1861

**Comment by Marco-MC** [comment]
autist

**Comment by WistarWolf** [comment]
ohhhh tut mir leid dass ich das nicht gesehen habe du spaggo
