### ISSUE TITLE
Add JumpDelay option to NeruxVaceFly

### ISSUE THREAD

**Issue by Nvaros** [CCBlueX/LiquidBounce1.8-Issues#2269]
On some servers with a even worse config, you can jump even more often with the particular motion.
It would be useful to add the slider "JumpDelay" (the command too ofc) to be able to change the delay between the jumps.

**Comment by Fryhyi** [comment]
+++++++ Iys work on server PLAY.TESLACRAFT.ORG

**Comment by Marco-MC** [comment]
Added
