### ISSUE TITLE
Autosword -> Autoweapon

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2272]
Rename Autosword to Autoweapon.
Add two modes; Sword, All
With all selected it should use the item with the highest attackdamage
With sword selected it should use the sword with highest attackdamage

Why all ? In survivalgames like on mineplex or hypixel there are axes or other items which are atm not used by autosword but have a higher attackdamage.
Why sword ? Because without "spoofitem" it has the ability to blockhit

**Comment by WistarWolf** [comment]
AutoTool not AutoWeapon

**Comment by scorpion3013** [comment]
#2622
