### ISSUE TITLE
How To Use .give Command ?

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2278]
what is data and datatag ı need example

**Comment by Marco-MC** [comment]
`.give stone` (1x Stone)
`.give stone 64` (64x Stone)
`.give stone 64 1`  (64x Granite Stone)
`.give stone 64 1 {display:{Name:"Cyka blyat"}}` (64x Granite Stone with name "Cyka Blyat")

**Comment by Teals53** [comment]
Thx For İnformation <3
