### ISSUE TITLE
Rewinside Teleport Fails

### ISSUE THREAD

**Issue by MultiDJRoni** [CCBlueX/LiquidBounce1.8-Issues#229]
Ich werde immer gekickt wenn ich mich über längere Distanzen Teleportieren will. Max 5 Blöcke, ansonsten kick wegen flying.

**Comment by Marco-MC** [comment]
Er wurde gepatcht. Hatte das auch schon unterm DEVLOG geschrieben.
Wir arbeiten aber schon an einem neuen. Der geht sogar schon relativ durch.

**Comment by Marco-MC** [comment]
https://www.youtube.com/watch?v=7ctMF89mqUQ
