### ISSUE TITLE
server-resourcepack spoofer

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2299]
Das man nicht das server resourcepack runterladen muss aber der server denkt man hat es heruntergeladen

Wieso? Es gibt Leute die haben einen so schlechten pc das diese dann wärend ein großes rp runterläd und sich in minecraft läd einen timeout bekommen.
Es ist oft nicht notwendig das ein resourcepack benötigt wird.
Es gibt oft bessere fanmade textruepacks für gewisse server bei denen man das server-resourcepack runterladen muss

**Comment by WistarWolf** [comment]
Deshalb gibt es eine "Frage" ob man das server resource pack runterladen will.

**Comment by scorpion3013** [comment]
Es gibt leider ein paar Server die einen kicken wenn man das Resourcepack ablehnt.
Aus diesem Grund wäre es schon sehr hilfreich soein modul zu haben.
Beispiele für solche server; Mineplex: minestrike minigame; hypixel: blocking dead minigame(in arcade lobby)

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1207
