### ISSUE TITLE
Disconnect button on the "Downloading terrain" screen

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2300]
https://prnt.sc/jziok3
Very much engrages, especially on the server Cubecraft. Thanks.    ♡( ◡‿◡ )

**Comment by Teals53** [comment]
+1

**Comment by Teals53** [comment]
+1

**Comment by NiggerFister** [comment]
+1

**Comment by yKsenomorf** [comment]
+1

**Comment by CzechHek** [comment]
Added, close this.

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3785 two same issues in one milestone too again
