### ISSUE TITLE
Scaffold ESP

### ISSUE THREAD

**Issue by Fryhyi** [CCBlueX/LiquidBounce1.8-Issues#2301]
Like this https://prnt.sc/jzjy3a
Or this  http://prntscr.com/jzjz5e

**Comment by Teals53** [comment]
what is this ?

**Comment by Teals53** [comment]
maybe try open blockoverlay

**Comment by Fryhyi** [comment]
Scaffold block esp/ Scaffold Blockoverlay.
as you like, the essence is the same :)

**Comment by Teals53** [comment]
Yeah ı know this and its like blockoverlay :D

**Comment by Fryhyi** [comment]
Okay

**Comment by Marco-MC** [comment]
Added
