### ISSUE TITLE
More strafe option

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2307]
Like vape

**Comment by SenkJu** [comment]
What exactly do you mean?

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/49672940-d834e000-fa7d-11e8-8deb-859560dd60f6.png)

**Comment by Teals53** [comment]
@Marco09MC @SenkJu

**Comment by Teals53** [comment]
@Marco09MC
