### ISSUE TITLE
Chams Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2313]
https://prnt.sc/k0ktay
https://prnt.sc/k0ktra

**Comment by coolpvpv1** [comment]
> https://prnt.sc/k0ktay
> https://prnt.sc/k0ktra

can you recheck the newer versions of liquidbounce to see if there fixed and if its fixed can you take this issue down

**Comment by Teals53** [comment]
:FacePalm:

**Comment by superblaubeere27** [comment]
More like an OpenGL error. This bug is not that much of a problem
