### ISSUE TITLE
Improve CubeCraft 3 Mode

### ISSUE THREAD

**Issue by Fryhyi** [CCBlueX/LiquidBounce1.8-Issues#2322]
Or improve Cubecraft3 fly mode
Code - https://hastebin.com/ipihalovad.cpp
Its teleport fly.

 /* The 2 is the teleport length */
_double_ x = -Math.sin(yaw) * 2;
            _double_ z = Math.cos(yaw) * 2; 

2 teleport length not tested, but this should work. I tested 1 teleport lenght, it works. I suggest adding the opportunity to adjust this value, for greater unevarsality.

**Comment by Marco-MC** [comment]
Added / Improved.
