### ISSUE TITLE
Plugin Manager

### ISSUE THREAD

**Issue by Pissler** [CCBlueX/LiquidBounce1.8-Issues#2323]
We need a script manager for LiquidBounce.
This would work like that:
+ .script upload myscript
  uploads the myscript liquidscript file
+ .script install myscript
  downloads and installs the script
+ .script uninstall myscript
  uninstalls the script
+ .script search my
  searches for scripts, if no argument is added, it will list all the available scripts

**Comment by Marco-MC** [comment]
![](https://img.ccbluex.net/moc/java_2018-07-02_19-51-30.png)

- .script upload myscript
No, because many people could abuse this and flood our server with data.

- .script install myscript
Just use the import button, lol.

- .script uninstall myscript
Just use the delete button...

- .script search my
https://github.com/CCBlueX/LiquidScript/wiki/Scripts

**Comment by Pissler** [comment]
kill yourself big fat jewish nazi nigger hoe
nobody wants to download those scripts that easy

**Comment by SenkJu** [comment]
+

**Comment by Pissler** [comment]
exactly
now add those features

**Comment by Marco-MC** [comment]
And who want to use fucking commands? (+ liquidscript dosn't support live installation and uninstalling of scripts)

**Comment by Pissler** [comment]
then add that to your gui

**Comment by Marco-MC** [comment]
You want a searching and a sharing feature in the gui?
Like I said, some people could abuse this features. We can't support uploading files to our server.

**Comment by Pissler** [comment]
nigger just do this like liquidchat

**Comment by Marco-MC** [comment]
LiquidChat is something completely different.

**Comment by Pissler** [comment]
jew
liquidchat doesnt work with cracked

**Comment by SenkJu** [comment]
No shit, genius.
It is supposed to.

**Comment by Pissler** [comment]
yes
and that can be done with the uploading

**Comment by Pissler** [comment]
stupid nigger answer now or ill report u

**Comment by Marco-MC** [comment]
What do you want to report? xd

**Comment by Pissler** [comment]
you

**Comment by Pissler** [comment]
but answer or code that feature

**Comment by Marco-MC** [comment]
Where do you want to report me?

**Comment by Pissler** [comment]
on github discord and youtube
