### ISSUE TITLE
ArrayList bug (2)

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#2331]
1- Wenn man arraylist shadowtext aus hat und mcfont an hat passiert das: https://i.imgur.com/iSfQEmc.png . Hier nochmal wenn der background nicht komplett schwarz ist https://i.imgur.com/sZriQZv.png

2- Bei manchen positionen auf dem bildschirm kann man bei den CustomHUD element einstellungen nichts bzw fast nichts ändern

**Comment by Fryhyi** [comment]
B51?

**Comment by WistarWolf** [comment]
b52

**Comment by Fryhyi** [comment]
Come out 2 hours ago http://dl.ccbluex.net/download/index.php?file=TGlxdWlkQm91bmNlLzEuOC9hMTVkOHNkZjQxL0xpcXVpZEJvdW5jZTEuOC45LWI1Mi56aXA=

**Comment by Fryhyi** [comment]
Come out 4 hours ago
http://dl.ccbluex.net/download/index.php?file=TGlxdWlkQm91bmNlLzEuOC9hMTVkOHNkZjQxL0xpcXVpZEJvdW5jZTEuOC45LWI1Mi56aXA=

**Comment by WistarWolf** [comment]
yeah

**Comment by Marco-MC** [comment]
1- https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2355
