### ISSUE TITLE
Neues Modul: InventorySorter

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#2345]
Ein Modul, dass das Inventar, insbesondere die Hotbar sortiert. Cool wäre es, wenn man z.B. per Datei einstellen könnte, dass auf die 1. Position das Schwert, auf die 2 der Bogen, usw. gelegt wird. Vielleicht könnte man noch verschiedene "Profile" einrichten, also dass man für jedes Profil eine eigene Config-Datei hat, und dann so einmal das Inventar für Skywars sortieren lassen kann und mit dem Wechsel des Profils dann das Inventar für Bedwars umsortieren lassen kann.

**Comment by Teals53** [comment]
Duplicated

**Comment by Fryhyi** [comment]
+1

**Comment by SenkJu** [comment]
#1601
