### ISSUE TITLE
Implement this Hypixel Scaffold

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce1.8-Issues#2346]
https://youtu.be/X3_GzUk52uU?t=17s

**Comment by NiggerFister** [comment]
https://youtu.be/X3_GzUk52uU?t=2m46s
2min 46sek du dummer neger, was kannst du eigentlich? mit dem blocksafe

**Comment by CrackFileso** [comment]
Liquidbounce has bypassed it.Turn "blockabledelay" on.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1354
