### ISSUE TITLE
Civbreak

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2350]
Civbreak soll nachdem der block gebreakt wurde weiter auf der block position bleiben.
Civbreak soll auch wenn man aus der Abbaureichweite ist die block position des ziel blockes behalten.
Eine option um den delay zum einstellen wann immer der block gebreakt werden soll. (Damit es nicht nur auf vanilla geht sondern auch auf "schwächeren" anticheats.

**Comment by scorpion3013** [comment]
Hier am beispiel des Pandora Clients auf einen Vanilla Server.
[https://streamable.com/0brb1](url)

**Comment by Marco-MC** [comment]
![](https://img.ccbluex.net/moc/java_2018-07-13_22-54-08.png)
