### ISSUE TITLE
X-Ray PerfectHorseJump And Blink Description

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2351]

**Comment by scorpion3013** [comment]
its an issue but its useless af, if someone needs a description for those things should not cheat and should consider suicide.
So why do you bother about those things and keep making useless issue post's about this shit?

**Comment by Teals53** [comment]
I'm obsessed sorry.

**Comment by Marco-MC** [comment]
So, the xray and blink description is a bug by the Obfuscator. I don't know correctly why, but it seems that if I set the description after the category the obfuscator don't obfuscate the strings correctly. I will fix that in the next version.

(and a perfecthorsejump description is not added yet I will add one)

**Comment by Teals53** [comment]
<3

**Comment by Teals53** [comment]
@Marco-MC 2. İnventory cant search bug like this obfuscation ?

**Comment by Marco-MC** [comment]
no

**Comment by Marco-MC** [comment]
![](https://axolotl.club/hA9NEc8M.png?key=QvYfcfxGGeU70L)
![](https://axolotl.club/kVSaKpES.png?key=Bl24jKKud74fGd)

uh, I should close this issue cuz I already fixed that problem with Blink and Xray.

**Comment by Teals53** [comment]
uh xD

**Comment by Teals53** [comment]
its already fixed just for you or for everyone :P

**Comment by Marco-MC** [comment]
Should be fixed for everyone (already since 14 jul)

**Comment by Teals53** [comment]
👌
