### ISSUE TITLE
Recode Inventory Cleaner (Make new cleaner and add new features, options etc)

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#2402]
# InventoryCleaner

**Item support** (Including enchantment support etc)
- [x] Swords
- [x] Tools
- [x] Bows
- [x] Compass
- [x] Other items

**Options**
- [x] Delay
- [x] InvOpen
- [x] SimulateInventory
- [x] NoMove
- [x] Hotbar
- [x] RandomSlot

# Inventory Sorter
**Base**

- [x] Basic sort
- [x] Slot item type options

**Item support**
- [x] Sword
- [x] Bow
- [x] Pickaxe
- [x] Axe
- [x] Food
- [x] Block

**Comment by Teals53** [comment]
soo good <3

**Comment by Fryhyi** [comment]
Wooow

**Comment by Fryhyi** [comment]
👍

**Comment by Marco-MC** [comment]
Preview: https://img.ccbluex.net/moc/Jdk1.8.0_162%202018.07.18%20-%2001.44.12.01.mp4

**Comment by Fryhyi** [comment]
Insane
