### ISSUE TITLE
Velocity

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2403]
aacpush maybe is broken bcs if ı select this mode its not bypass anythid and if himhit me ı am flying like vanilla its not normal and reverse velocity not do anything why ? its not set reverse knockback ??

**Comment by Marco-MC** [comment]
Working fine for me. 🤔

**Comment by Teals53** [comment]
you see description you write something secondary inventory but ı cant do this ? and really ı am not say lie never

**Comment by Teals53** [comment]
can you come my server ? ı can show you pm you on discord my server ip

**Comment by Teals53** [comment]
aacpush fixed https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2408

reverse fixed in b54

pls closed
