### ISSUE TITLE
.chestaura Syntax Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2404]
write chat ".chestaura chest" 

https://prnt.sc/jygigc

but its say .fucker chest

**Comment by Teals53** [comment]
and if ı say ".fucker chest" its show me  https://prnt.sc/k7iv2y but its not need have this command

**Comment by C1u0R** [comment]
@Teals53 
For Chestaura you still have to specify the type of chest
Example: ".chestaura chest chest"

and if you want to set the block to destroy with fucker use ".fucker select [block]
Example: ".fucker select bed"
