### ISSUE TITLE
some color bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2405]
https://prnt.sc/k7iv5p
https://prnt.sc/k7iv2y
http://prntscr.com/k80b1d

**Comment by Teals53** [comment]
@Marco-MC

**Comment by Marco-MC** [comment]
I know that, but I don't know a solution for this problem. The minecraft chat is a little bit retarded.

**Comment by Marco-MC** [comment]
I will have a look tomorrow.

**Comment by Teals53** [comment]
ı think its same problem like this sorry https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2756 https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2755

**Comment by Marco-MC** [comment]
nah

**Comment by Teals53** [comment]
okey dude <3

**Comment by coolpvpv1** [comment]
> okey dude <3

can you close this issue then sense its expose to look like that

**Comment by Teals53** [comment]
Why my issues important for you dude ?

**Comment by Teals53** [comment]
Its still not reported about fix ? @superblaubeere27
