### ISSUE TITLE
Invsorter swaps the same sword

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2416]
Invsorter throws away sword in hotbar for the same sword in the inventory.

**Comment by scorpion3013** [comment]
![2018-07-23_05-34-19](https://user-images.githubusercontent.com/27446646/43056043-21e2e22a-8e3a-11e8-87ec-be10abbc5f8b.gif)

**Comment by freaky767** [comment]
invcleaner does that too, its kinda annoying :C

**Comment by Marco-MC** [comment]
Fixed
