### ISSUE TITLE
Tower custommotion

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2419]
A tower mode with changeable motion

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2519
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2522
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2520
