### ISSUE TITLE
DisableCommands Module or “.prefix” Command

### ISSUE THREAD

**Issue by Cloak3** [CCBlueX/LiquidBounce1.8-Issues#2421]
Some servers’ hacked client verification is impossible to bypass using “.say”(e.g. a server needs you to fill your chat bar with “.” and send it to the chat to verify, which cannot be bypassed with “.say”). Adding a command “.prefix” to change command prefix(“.” by default) or a module “DisableCommands” to temporarily disable LiquidBounce commands would solve these problems.

**Comment by Teals53** [comment]
Up thats a good idea for captcha check servers @Marco-MC

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2388
