### ISSUE TITLE
Scaffold is a bit buggy in spartan

### ISSUE THREAD

**Issue by freaky767** [CCBlueX/LiquidBounce1.8-Issues#2424]
Im using the spartan settings and spartan keeps stopping meh from scaffolding so i have to keep clicking w to bypass it.

**Comment by Marco-MC** [comment]
![https://img.ccbluex.net/moc/javaw_2018-08-28_17-45-35.png](https://img.ccbluex.net/moc/javaw_2018-08-28_17-45-35.png)
I found working settings for Spartan.

**Comment by Marco-MC** [comment]
Updated AutoSettings of spartan. (https://github.com/CCBlueX/FileCloud/commit/805db996a54400fc7adb2302ffd8d83e2af67609)
