### ISSUE TITLE
Hypixel Nofall【With code】

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#2428]
if（mc.thePlayer.falldistance >3.5&&!mc.thePlayer.onGround）(
co3.onGround = true；
)

**Comment by CrackFileso** [comment]
In some game rooms(i guess it depends whether you got /wdr) you need to get at least 0.5 damage

**Comment by Marco-MC** [comment]
NoFall SpoofGround seems to bypass on hypixel.
