### ISSUE TITLE
Guardian/VeltPvP 2 Speeds ( With code )

### ISSUE THREAD

**Issue by Fryhyi** [CCBlueX/LiquidBounce1.8-Issues#2434]
https://hastebin.com/holivitefu.cs

**Comment by CrackFileso** [comment]
your computer is awesome.

**Comment by Fryhyi** [comment]
What?

**Comment by CrackFileso** [comment]
4FPS Player

**Comment by Fryhyi** [comment]
I don't understand you, man...

**Comment by NotVerble** [comment]
Hey there!
I was pretty interested in seeing this, and realized your code is very similar to a client I worked on with another developer called Vlad_and_Lol.
In fact, it's **too** similar.
[https://sw00zed.is-fucking.men/i/xd257.png](url) shows the fly code from Artix. 
[https://sw00zed.is-fucking.men/i/5zxq9.png](url) shows the fly code that you are suggesting.
Try making it less obvious next time.
