### ISSUE TITLE
Guardian/VeltPvP HighJump ( With code )

### ISSUE THREAD

**Issue by Fryhyi** [CCBlueX/LiquidBounce1.8-Issues#2435]
https://hastebin.com/acurezuhas.cs

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
Skidded from `Artix leak`, will be removed next in the next version of liquidbounce.
Thanks to @NotVerble for the information.

**Comment by Marco-MC** [comment]
@Fryhyi Don't post stolen code again, when you do that again I will ban you from this repository.

**Comment by Teals53** [comment]
its not open source ? so how you see him code if its obfuscated ? ar u haker xD (and skidded is beateful ehuehehue)
