### ISSUE TITLE
New AutoSettings Suggestion (Guardian)

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2442]
Anybody make a config for guardian anti cheats ? because some pvp servers use this anti cheat like veltpvp

Thx <3

**Comment by Fryhyi** [comment]
Waiting when Marco is back and add bypasses for guardian what are released here to new version.

**Comment by Teals53** [comment]
ok

**Comment by Marco-MC** [comment]
Can you tell me where I can find the plugin?

**Comment by Teals53** [comment]
@Marco-MC ı dont know but maybe this

https://www.spigotmc.org/resources/guardian-anti-cheat-1-8-1-12-2.47034/

**Comment by Fryhyi** [comment]
@Marco-MC  Veltpvp.com -  pvp server what have guardian anticheat. After Guardian ban you need to use vpn ( ip ban ). After Staff ban you dont need vpn. Banned you or not you can see in the chat when you connected to the server

**Comment by Teals53** [comment]
True

**Comment by Marco-MC** [comment]
Just ask in the Forum, there will be more people to help.
