### ISSUE TITLE
Hypixel Fast BHop + Code

### ISSUE THREAD

**Issue by Fryhyi** [CCBlueX/LiquidBounce1.8-Issues#2452]
Myself Hypixel BHop for LiquidBounce :)
https://hastebin.com/ixohokaruc.java

**Comment by Teals53** [comment]
why closed old issue and open new issue without different ?

**Comment by Marco-MC** [comment]
Added

**Comment by Marco-MC** [comment]
![](https://img.ccbluex.net/moc/idea64_2018-09-22_21-08-30.png) oof?

**Comment by Teals53** [comment]
lul
