### ISSUE TITLE
(With code) Killaura-Util: Block-Evasion

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2455]
@Tru3  " Diese Methode sucht den nächst besten Vector auf der Hitbox, um die Range zu maximieren und versucht gleichzeitig einen Punkt zu finden, wo die Killaura durch keine Blöcke schlägt.  "

Video from YT how its work:
https://youtu.be/GCGrbHM7Eys

Code: 
public static Vec3 resolveBestHitVec(Entity enty, int precision, boolean evadeBlocks) {

    try {
        Vec3 headVec = mc.thePlayer.getPositionEyes(1.0f);
        Vec3 bestHitVec = new Vec3(Double.MAX_VALUE, Double.MAX_VALUE, Double.MAX_VALUE);

        int offset = precision / 3;

        float height = enty.getEyeHeight() / precision;
        float width = (enty.width * 0.5f) / offset;

        for (int offsetY = 0; offsetY <= precision; offsetY++) {
            for (int offsetX = -offset; offsetX <= offset; offsetX++) {
                for (int offsetZ = -offset; offsetZ <= offset; offsetZ++) {

                    Vec3 possibleVec = new Vec3(enty.posX + width * offsetX, enty.posY + height * offsetY,
                            enty.posZ + width * offsetZ);

                    if (evadeBlocks) {
                        MovingObjectPosition movingObj = mc.thePlayer.getEntityWorld().rayTraceBlocks(headVec,
                                possibleVec);
                            
                        if(movingObj != null) {
                            continue;
                        }
                            
                    }
                    if (headVec.distanceTo(possibleVec) < headVec.distanceTo(bestHitVec)) {
                        bestHitVec = possibleVec;
                    }
                }
            }
        }

        if (bestHitVec.xCoord == Double.MAX_VALUE) {
            bestHitVec = null;
        }

        return bestHitVec;
    } catch (Throwable t) {
        t.printStackTrace();
        return enty.getPositionVector();
    }
    }

**Comment by CrackFileso** [comment]
emm,How to cover Vec3 into yaw/pitch(I don't know)
