### ISSUE TITLE
NameProtect Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2456]
İf I Open NameProtect And My NickName İs "XXX" All "XXX" Text Convert My FakeName LOL

http://prntscr.com/kfc7eh İn Gui NickName "Player

https://prnt.sc/kfch7t  http://prntscr.com/kfchk1  Chat And Sign

https://prnt.sc/kfcg43 NickName "Movements"

http://prntscr.com/kfcib6 NickName "Fly"

https://prnt.sc/kfcjss NickName "Vanilla"

http://prntscr.com/kfckh5 İn CustomHUD

http://prntscr.com/kfclhb İn CustomHUD NickName "Armor"

**Comment by Fryhyi** [comment]
Loool

**Comment by Marco-MC** [comment]
I'm a lazy guy, so I replace everything.

**Comment by Teals53** [comment]
hahaahaha :D

**Comment by Teals53** [comment]
@Marco-MC Why ?

**Comment by Teals53** [comment]
@Marco-MC and why xD ?

**Comment by Marco-MC** [comment]
because your username can be everywhere... that's why I need to replace everything.

**Comment by Marco-MC** [comment]
I can't fix it, so simple.

**Comment by Teals53** [comment]
ok dude <3

**Comment by SenkJu** [comment]
This is not even really a bug.

**Comment by Teals53** [comment]
lol
