### ISSUE TITLE
Killaura save target option

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2459]
Save target until it dies. Helps to bypass some anticheats :3
Correction: There is a certain amount of time running. For example 600 microseconds. If the target is lost more than 600 microseconds, Killaura changes to another target.

**Comment by ArrowReport** [comment]
Pls also add this to Aimbot, and BowAimbot

**Comment by Marco-MC** [comment]
I think I would add this to AntiBot, because I can't detect who killed someone.
