### ISSUE TITLE
Scaffold made an other expand mode

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2462]
https://streamable.com/9o7t4

LiquidBounce expand mode flags ncp
SkillClients expand mode doesent flag ncp (only with static rotations)

**Comment by Marco09MC** [comment]
https://i.axo.im/e4G-loli-B4G/dgUwZAFN.mp4
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2977
