### ISSUE TITLE
Client Title

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#2466]
LiquidBounce b54 | 1.8.9 --> LiquidBounce b54 | Minecraft 1.8.9
or
LiquidBounce b54 | 1.8.9 --> LiquidBounce b54 | Based on Minecraft 1.8.9

Why? Looks cooler

**Comment by Teals53** [comment]
:D

**Comment by Marco-MC** [comment]
![](https://img.ccbluex.net/moc/Discord_2018-09-27_16-08-28.png) -> ![](https://img.ccbluex.net/moc/Discord_2018-09-27_16-08-45.png)

**Comment by WistarWolf** [comment]
kk

**Comment by Teals53** [comment]
@Marco-MC new discord channel is released ?
