### ISSUE TITLE
FastUse Timer mode

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2471]
Working on hypixel

**Comment by liamjdorsey** [comment]
why? it makes it basically no faster and if the item will not finish and you use it too long, you get autoban

**Comment by ClientvsAnticheat** [comment]
Useless and Duplicate of #2686

**Comment by 215789586** [comment]
in fact fastuse aac mode bypasses hypixel(a lot of chinese configuration-maker use it ans bypasses hypixel)

**Comment by 215789586** [comment]
i think fastuse aac mode is just timer
