### ISSUE TITLE
https://forum.ccbluex.net/ İs Down ?

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2479]
Why ?

**Comment by Janmm14** [comment]
because you don't deserve it

**Comment by CrackFileso** [comment]
Ok,Seems that liquidbounce is dying

**Comment by Teals53** [comment]
@Janmm14 haha -__-

**Comment by Teals53** [comment]
@CrackFileso NOOOO xD

**Comment by scorpion3013** [comment]
The forum is currently down caused by an error.

Senk Ju :
> something has selfdestroyed itself there (Original Text: "irgendwas hat sich da selbstzerstört")

**Comment by Marco-MC** [comment]
I currently working on the 1.13 version, that's why I don't work on new updates for the 1.8.9 currently.

**Comment by drkousek** [comment]
Players want new 1.8.9 :D, one month waiting on new LB is a lot :´D

**Comment by ThomCrafter** [comment]
Yeah

**Comment by Marco-MC** [comment]
btw https://forum.ccbluex.net/ is back online, if someone didn't noticed.
