### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2482]
It would better if u can change the Font size ingame in CustomHUD and u need to drag&drop the font file in the fonts folder only. Why? If u want a bigger font and u don't which size looks good, u need to restart the game the whole time. (And not every person have a fast pc and the game takes longer to load.)

**Comment by Fryhyi** [comment]
👍

**Comment by superblaubeere27** [comment]
This feature is already present, not as easy to accomplish, but it is there.
