### ISSUE TITLE
Killaura FakeSwing issues (Forum)

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2485]
https://forum.ccbluex.net/thread.php?id=498 author: yorik100

Looks like the option "FakeSwing" has some issues.
1. Like yorik100 said its not attacking
2. If the option is false, the killaura doesent care about the rotations. https://i.imgur.com/cPBKe9Q.gif

Versions before "FakeSwing" was an option dont have these problems 

https://i.imgur.com/yofoc8U.gif

**Comment by Fryhyi** [comment]
Could you please explain what is "fakeswing" and what does this function do?

**Comment by yorik100** [comment]
"FakeSwing: Makes KillAura send swing packets before it finished aiming at an enemy (Makes it harder for AntiCheats to detect it)"

**Comment by Fryhyi** [comment]
Thank you.

**Comment by Marco-MC** [comment]
Fixed.
