### ISSUE TITLE
CubeCraft fast teleport tower + code

### ISSUE THREAD

**Issue by Fryhyi** [CCBlueX/LiquidBounce1.8-Issues#2488]
By GleichAngemeldet
https://youtu.be/tKZHDZ5TgZM

https://ghostbin.com/paste/qu8sv

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2519

1.15 Teleport Height
0 Teleport Delay
