### ISSUE TITLE
AAC 3.4.2 NoFall

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2491]
https://www.youtube.com/watch?v=sJInB_9r7Y0

**Comment by SenkJu** [comment]
Shitty glide and he does not even show it on GommeHD.

**Comment by NaNaShiSan1** [comment]
The title says 'NoFall' and I found no glide in this video.

**Comment by Teals53** [comment]
Yes ?

**Comment by Fryhyi** [comment]
Its already in LiquidBounce GitHub
