### ISSUE TITLE
Invisible chat lines

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#2495]
Messages are invisible when they are two lines long.

**Comment by Marco-MC** [comment]
Der Bug hat nichts mit FontChat zu tun, sondern ist eher ein allgemeiner Bug mit dem Chat in LiquidBounce.

![](https://img.ccbluex.net/moc/java_2018-09-21_13-56-50.png)
![](https://img.ccbluex.net/moc/java_2018-09-21_13-57-03.png)

**Comment by Marco-MC** [comment]
Okay, es hat doch etwas mit FontChat zu tun. Sobald der Text während FontChat an ist hinzugefügt wird, werden oft manche Zeilen nicht angezeigt. Es halt zumindest schonmal nichts mit dem allgemeinen drawn zu tun, sondern das Problem liegt beim hinzufügen.

**Comment by Marco-MC** [comment]
Fixed
