### ISSUE TITLE
(Request) SafeHop in speed module

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2504]
It is just normal Hop with which we move simply by pressing or holding Space

**Comment by Teals53** [comment]
not useable

**Comment by Fryhyi** [comment]
SafeHop + Strafe = already good. Its not autobanned ( in every anticheat ) and looks like normal bunny hopping ( another plus is that you do not get banned from the stuff ). And maybe somebody does not want to constantly keep the space button, and at the same time does not want to use for example "aaclowhop3" or "ncphop", it depends on the anti-cheat. Perfect for Legit game.

**Comment by Teals53** [comment]
dude why not press damn space ? and open strafe ?

**Comment by Fryhyi** [comment]
God, are we talking about cheats or about a vanilla minecraft? This function takes place to be, like everyone else. Why are you using autoarmor dude? You can wear armor yourself. Why do you use ChestStealer? Dude, you can just take things out of the chest yourself. Shit discussion.

**Comment by Teals53** [comment]
Pls dont be mad :P
