### ISSUE TITLE
Clipboard login in AltManager

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2506]

**Comment by Teals53** [comment]
what is this ?

**Comment by Fryhyi** [comment]
You dont need to paste your alt to email:pass for login. Just copy alt in the format email:pass and click to the Clickboard login.

**Comment by Teals53** [comment]
use directlogin ?

**Comment by Fryhyi** [comment]
Are you kidding me or do you just do not understand my English? Why are you constantly looking for reasons why my ideas should be rejected ???? I'm explain again, especially for you. Very simple and fast. In Directlogin you can see 3 lines : 1) Email 2)Password 3)Email:password. Clickboard login is the button that will be located in Directlogin. With the copied account, you simply click on the Clickboard login button. And that's all! You do not need to enter any data, insert it somewhere. You just need to copy the account and click on the button Clickboard login. This is much faster than copying, inserting an account and clicking on the Login button. Like Skid client. If you dont understand me, just download cracked version of this client and go to the AltManager.

**Comment by Teals53** [comment]
😕

**Comment by Gegreenpeaced** [comment]
Use Direct Login
