### ISSUE TITLE
Configurable colors for ESP, BlockESP and BlockOverlay

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#251]
Man kann dann bei StorageESP einzeln einstellen welche Farbe z.B. der Ofen, die Kiste, EnderKiste usw haben soll,

**Comment by thxforhelp** [comment]
+rep

**Comment by Marco-MC** [comment]
Für StorageESP mache ich dies nicht, da dass einfach für alles einzelnde komplett übertrieben wäre.
Für BlockESP und BlockOverlay, habe ich dies aber soeben hinzugefügt.
Wegen ESP muss ich schauen.

**Comment by Marco-MC** [comment]
Für ESP bau ich es auch nicht ein.
