### ISSUE TITLE
Scaffold Bypass ( Rotations ) for this server

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2510]
Play.TeslaCraft.org
Server with VERY cool self-made bedwars
AAC 3.3.14 and maybe AACAP but with very shit settings, because there wors NeruxVace fly with 5 ticks and timer 0.30  :/
LiquidBounce scaffold dont work on this server. Work only scaffold of Spartan setting, (setting spartan) but after a while time antichet flag you and you fall down ( for example If you make a turn when using scaffold ). I think that the problem is in scaffold rotations.

**Comment by yKsenomorf** [comment]
akrien b14 :/

**Comment by BlackHawk2306** [comment]
Try AAC config and timer 0.9  0.8 in for scaffoldwalk (.scaffold timer 0.9)

**Comment by yKsenomorf** [comment]
@BlackHawk2306 it doesnt work

**Comment by Gegreenpeaced** [comment]
Make a Legit Scaffoldwalk Delay 300, Keep Rotation and toggle Sprint off. If it not bypass try the lastet Spartan Config.

**Comment by yKsenomorf** [comment]
> 
> 
> Make a Legit Scaffoldwalk Delay 300, Keep Rotation and toggle Sprint off. If it not bypass try the lastet Spartan Config.

It only bypasses with legit rotations (always sneaking / breezily (zitter)

**Comment by Fryhyi** [comment]
@Gegreenpeaced funny fact. With a large or very large delay you will kicked faster than with 0 delay.

**Comment by Marco-MC** [comment]
https://img.ccbluex.net/moc/2018-10-15_17-42-15.mp4

![](https://img.ccbluex.net/moc/javaw_2018-10-15_17-43-32.png)

Working fine for me with this settings.
