### ISSUE TITLE
Old UI (Suggestion)

### ISSUE THREAD

**Issue by MDMCK10** [CCBlueX/LiquidBounce1.8-Issues#2513]
There should be an option to use the old main menu UI from the older versions, since in my opinion it:

- Was less laggy than the new one
- Looked way better design-wise

**Comment by SenkJu** [comment]
You can re-enable the old main menu by opening Values.json inside the LiquidBounce folder and setting Main Menu Style to 'Old'.

**Comment by MDMCK10** [comment]
Well i guess i learn something new every day, thanks!
