### ISSUE TITLE
SlowMotion Module (Lässt die Umgebung in SlowMotion erscheinen)

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#253]

**Comment by SenkJu** [comment]
Timer speed unter 1. Gibt keine andere Methode.

**Comment by WistarWolf** [comment]
Kann man sowas mit den scripts machen?

**Comment by Marco-MC** [comment]
```
scriptName = "SlowMo";
scriptVersion = 1.0;
scriptAuthor = "Marco_MC";

registerModule(SlowMotion, Render) {
	
	func onEnable {
		Timer.timerSpeed = 0.3;
	}
	
	func onDisable {
		Timer.timerSpeed = 1;
	}
}
```

**Comment by Marco-MC** [comment]
Hoffe das Script geht habe es net ausgetestet.

**Comment by WistarWolf** [comment]
hab mir schon selber eins mit dem Script gemacht

**Comment by Marco-MC** [comment]
BRUH

**Comment by WistarWolf** [comment]
xd Aber fix bitte endlich dass moredisplay script und adde wenns möglich ist noch dass man coodintane anzeigen lassen kann xd Nur das vor dem komma bei den coodinaten xd
