### ISSUE TITLE
Localsettings new option "saveall"

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2535]
This option should save also which modules are toggled and not toggled

**Comment by Marco09MC** [comment]
Added

**Comment by Marco09MC** [comment]
**Syntax**
![](https://axolotl.club/SqtnJRhS.png?key=NbSRvqkxr6BOpN)

**All**
![](https://axolotl.club/WZ5biEHD.png?key=soogVK29ykYr7K)
https://paste.ccbluex.net/?view=0a6ac1708
**Values & Binds**
![](https://axolotl.club/kQvaw2NT.png?key=ce2j7BUteF4hDG)
https://paste.ccbluex.net/?view=7fae9357a
**States**
![](https://axolotl.club/W9PBzFA4.png?key=3lxBYGLb8Fx2dq)
https://paste.ccbluex.net/?view=c88805025
