### ISSUE TITLE
MİNER DETECTED

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2567]
this website have a any miner things ?

https://ccbluex.net/

if ı join this site my cpu usage

http://prntscr.com/kxk6e0

my normal cpu usage

https://prnt.sc/kxk6ia

CPU Model i7-3770k

**Comment by SenkJu** [comment]
Someone was able to gain access to our webserver and add a crypto miner to some of our websites. However, we found out about it, removed it from all our websites and got his account terminated. If your CPU usage still bumps up when visiting the website, you might be viewing a cached version. Try clearing the cache of your browser.

**Comment by Teals53** [comment]
How its possible ? İnteresting.

**Comment by Teals53** [comment]
"Someone" is hacker ?

**Comment by d1player** [comment]
Malwarebytes was yelling at me when this was on the website
