### ISSUE TITLE
Readd old Gomme Bhop/Longjump

### ISSUE THREAD

**Issue by ArrowReport** [CCBlueX/LiquidBounce1.8-Issues#2571]
Readd old Gomme Bhop/Longjump because you can make it slower using the Reverse2 Velocity Mode, and it looked pretty gud

**Comment by Marco-MC** [comment]
Nah, give me a good reason to readd.

**Comment by ArrowReport** [comment]
AHHHHHHHHHHHHHHHHHH, im a tree
