### ISSUE TITLE
BowAimbot + FastBow bug

### ISSUE THREAD

**Issue by Kaufi2** [CCBlueX/LiquidBounce1.8-Issues#2578]
The silent option doesn't work together with  fastbow

**Comment by Marco-MC** [comment]
Working fine for me.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2595

Seems to don't work in multiplayer.

**Comment by Marco-MC** [comment]
Fixed.
