### ISSUE TITLE
Auto Use water bucket when landing 

### ISSUE THREAD

**Issue by je5442804** [CCBlueX/LiquidBounce1.8-Issues#2580]
it can be useful in the server which can not use nofall
if worried about the delay and high speedinair 
it can add a timer when closing to Ground

**Comment by BlackHawk2306** [comment]
So you mean they should add NoFall mode "MLG" or so?

**Comment by Teals53** [comment]
MLG haev baetefuauıl colorussss

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2124
