### ISSUE TITLE
xray bug

### ISSUE THREAD

**Issue by icewormy3** [CCBlueX/LiquidBounce1.8-Issues#2583]
if you turn it on, it doesn't show the ores and if you turn it off, it causes huge lag and sometimes crashes the game.

**Comment by icewormy3** [comment]
b56 got released and the bug didnt get fixed yet i tried it

**Comment by Marco-MC** [comment]
https://forum.ccbluex.net/thread.php?id=666

![firefox_2018-10-15_16-58-27](https://user-images.githubusercontent.com/12410754/46959105-8c784280-d09b-11e8-9f8f-7e2d822785f0.png)
Seems to be solved.
