### ISSUE TITLE
Global inventory delay

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#2587]

**Comment by Teals53** [comment]
what is this ?

**Comment by yKsenomorf** [comment]
@Teals53 its like delay for invcleaner, autoarmor and cheststealer in one setting

**Comment by Teals53** [comment]
Dude pls dont add this because its not good for customization close pls :(

**Comment by Teals53** [comment]
<3

**Comment by Marco-MC** [comment]
With this idea was meant something else and even something meaningful, but... I'm just too lazy.

The idea was that... when invcleaner and autoarmor has the same click delay of 500ms (as example), that not the two modules click at the same time.

**Comment by Marco-MC** [comment]
I'm not sure, why I closed that... that would solve a lot of problems.

**Comment by Marco-MC** [comment]
maybe later

**Comment by Teals53** [comment]
lol :D

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/036866e983d77c9b5d6e46ed83fab46998261611

currently in testing
