### ISSUE TITLE
Spammer Custom-Mode funktioniert nicht richtig

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#2589]
Wenn man im Spammer den Custom-Mode **AUS** macht, hängt er an jede Nachricht eine zufällige Zeichenkette ran. Macht man den Custom-Mode **AN**, so ist jede Nachricht gleich.

Sollte es nicht genau anders herum sein?

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1148
