### ISSUE TITLE
Nice things to do

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#2595]
- Improve Fucker Surroundings (it sometimes tries to break more than 1 block to access the selected block)
- Add effects and enchants on nametags and ArmorHUD (example for enchant : 
![image](https://user-images.githubusercontent.com/16320315/46247854-b0882280-c411-11e8-96d9-8a55eb451355.png))
- Pentential clipstepping https://cdn.discordapp.com/attachments/485813075237142543/487663108056416287/2018-09-07-1838-41.mp4 (and an option to step even without the need of colliding with a block)
- Do not throw soups with InventoryCleaner (or add an option to do not do that)
- Constant motion tower with scaffold
- Packet reversestep (instantly going down) with motion of the packets
- Delayed FastBow (each X secs), useful for Mineplex wich has a delay of 1-2 secs per fully charged packets
- 50% slower diagonal scaffolding option (also useful for Mineplex) since it scaffolds 2 times faster (places 2 times more blocks)
- Fix BlockHead (it makes you speed up underwater since it thinks you're colliding with the waterblock that is above your head)
- More than 1 block in BlockESP (useful for switching games fast)
- Packet NoFall doesn't work on very big distances
- Automated checkerclimb in Wallclimb that misplaces the player slightly into the block its colliding with and then climb with 2 modes : Default Spider (with a speed slider to make it climb faster or slower), Jump (Hero belike)
- FastBow + BowAimBot works in solo but not in multiplayer

**Comment by Marco-MC** [comment]
> Fix BlockHead (it makes you speed up underwater since it thinks you're colliding with the waterblock that is above your head)
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2610

> Do not throw soups with InventoryCleaner (or add an option to do not do that)
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2614

> More than 1 block in BlockESP (useful for switching games fast)
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2203

> FastBow + BowAimBot works in solo but not in multiplayer
https://img.ccbluex.net/moc/2018-10-02_18-30-34.mp4 Okay, I will fix that.
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2578

> Packet NoFall doesn't work on very big distances
That's normal, because Packet NoFall sending every 2 blocks a onground packet to prevent damage but when the motion is too high he can't prevent damage. That's how the packet nofall work. Use SpoofGround or NoGround when you want 0% Damage.

**Comment by Teals53** [comment]
Well superstrawberry started terminate all suggestion lists

**Comment by superblaubeere27** [comment]
@Teals53 Yes because those are a missuse of the issue system and they make our lifes harder. If you want to discuss suggestions, use our forums. In times when we haven't had our forums, this was the only place (besides our discord) to do so. Now it has changed.
