### ISSUE TITLE
Soo fuqink minor bug xd

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2596]
![screenshot_2018-09-30-02-29-27](https://user-images.githubusercontent.com/13446881/46251345-cd941400-c458-11e8-982c-de7c9dd49c80.png)

**Comment by Teals53** [comment]
Dude why forget press space ehehehehehe

**Comment by Teals53** [comment]
fixed euheheuhuehehu https://github.com/superblaubeere27/FileCloud/pull/1/files/e51dfb0555f4528795b3c4621c588993d43949ba..ea5e3d6f174b4b704de50e06198df822a093dd8e

**Comment by Marco-MC** [comment]
@Teals53 Wrong repository, but @NaNaShiSan1 already made a [pull request](https://github.com/CCBlueX/FileCloud/pull/30) in the **correct** repository.
