### ISSUE TITLE
InvCleaner: Option to clean Hotbar as well

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#260]

**Comment by Marco-MC** [comment]
._.

**Comment by Crax9999** [comment]
Könntet ihr bitte auch bei invcleaner machen was 
für Sachen rausgeworfen werden damit meine ich z.b.
>Pickaxe
>Axe
>Milk 
etc.

**Comment by Crax9999** [comment]
Ps:Xave hat dass u. Fals es noch geht die delay bitte manchmal ist es zu schnell u. Es Autobannt dann

**Comment by SenkJu** [comment]
Stell den Delay halt niedriger @Crax9999

**Comment by Crax9999** [comment]
Oh danke wusste es nicht

**Comment by Crax9999** [comment]
Fasd man die delay runterstellen kann

**Comment by superblaubeere27** [comment]
Da gibts ein paar Probleme, da er wenn man Items in der Hotbar wegwirft, Armor  wegwirft
