### ISSUE TITLE
Pressable urls | LiquidChat

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#261]
als wenn man jemanden einen Link schickt das der Klickbar ist und sich der Browser öffnet wie im normalen MC Chat https://gyazo.com/e8f68bec09a791f8397eed6b37c0943a

**Comment by icewormy3** [comment]
LMAO CLOSE THIS ISSUE LIQUIDSCRIPT IS FUCKIN OUTDATED

**Comment by SenkJu** [comment]
The issue is about LiquidChat, not LiquidScript.

**Comment by icewormy3** [comment]
okay. liquidchat was replaced by axochat tho so...

**Comment by SenkJu** [comment]
It is still not working, however.

**Comment by Teals53** [comment]
xd

**Comment by Marco09MC** [comment]
Done.
