### ISSUE TITLE
Add StorageESP OtherBox, Outline, Shader, 2D and Wireframe support to minecart with chest

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#2615]

**Comment by Marco-MC** [comment]
**Box**
![](https://img.ccbluex.net/moc/java_2018-10-02_19-41-27.png)
**OtherBox**
![](https://img.ccbluex.net/moc/java_2018-10-02_19-41-52.png)
**Outline**
![](https://img.ccbluex.net/moc/java_2018-10-02_19-42-15.png)
**Shader**
![](https://img.ccbluex.net/moc/java_2018-10-02_19-42-53.png)
**2D**
![](https://img.ccbluex.net/moc/java_2018-10-02_19-43-11.png)
**Wireframe**
![](https://img.ccbluex.net/moc/java_2018-10-02_19-43-44.png)

**Comment by Teals53** [comment]
Finally <3
