### ISSUE TITLE
Change access implementation to access transformer

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#2619]
https://tutorials.darkhax.net/tutorials/access_transformers/

**Comment by Marco09MC** [comment]
![](https://img.ccbluex.net/moc/idea64_2019-02-23_21-06-38.png)

**Comment by Marco09MC** [comment]
![](https://img.ccbluex.net/moc/idea64_2019-02-23_23-13-21.png)
Moved all access implementations into access transformer

**Comment by Teals53** [comment]
Best <3
