### ISSUE TITLE
Mineplex WallClimb

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#2620]

**Comment by yorik100** [comment]
WallClimb CheckerClimb bypasses it already (yet you can still make an automated version of it)

**Comment by Marco-MC** [comment]
> 
> 
> WallClimb CheckerClimb bypasses it already (yet you can still make an automated version of it that when colliding with a wall, it misplace the player into the blocks you collide and make you spider like basic WallClimb)

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2623
Yep, already added a motion value for checkerclimb.

**Comment by Marco-MC** [comment]
CheckerClimb should be enough.

**Comment by yorik100** [comment]
This feature is completly broken ->  #2636
