### ISSUE TITLE
BowAimbot: AutoShoot

### ISSUE THREAD

**Issue by Kaufi2** [CCBlueX/LiquidBounce1.8-Issues#2624]
Der BowAimbot soll schießen sobald ein Gegner in Sicht ist

**Comment by yorik100** [comment]
Use AutoBow

**Comment by Kaufi2** [comment]
Autobow is shooting all the time and Autoshoot only if the enemy is visible

**Comment by Marco-MC** [comment]
Maybe I could add this to AutoBow, so AutoBow will detect if you are aiming on a enemy.

**Comment by superblaubeere27** [comment]
I implemented it
