### ISSUE TITLE
Cubecraft faststart

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2635]
Einfach ein Faststart modul für cubecraft (oder/und andere server) was .vclip benutzt (2.67) oder du es selbst schaffst zu coden ohne vlcip. Damit es einfacher zumachen, als es dauerhaft einzugeben etc.

PS: nicht skidden ;3

**Comment by scorpion3013** [comment]
I guess -> https://streamable.com/4gnad

https://workupload.com/file/uy2jeDJh
