### ISSUE TITLE
wallclimb wallcheker not working at all

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#2636]
![image](https://user-images.githubusercontent.com/16320315/46663954-cd65e800-cbbf-11e8-8466-a26d72184198.png)
Wallclimber only allows you to climb one block (2 blocks walls) and motion doesn't work if you keep going into a wall instead of blocking movement and making you motion up

**Comment by Marco-MC** [comment]
ItemESP Shader is not broken, just a bug with your hardware (maybe).

**Comment by Marco-MC** [comment]
Fixed
