### ISSUE TITLE
More Antibot Settings

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#264]
Skin Check/Setting
Ping Check/Setting
Armor Check/Setting

**Comment by Marco-MC** [comment]
- [ ] Skin Check/Setting
- [ ] Ping Check/Setting
- [ ] Armor Check/Setting
- [ ] Moved Check/Setting
- [ ] HadMotionY Check/Setting

**Comment by Marco-MC** [comment]
UUID Check, Skin Check lasse ich mal weg, da bei dem UUID Check immer eine Connection aufgebaut werden müsste zum checken etc und beim Skin check nunja... relativ unnötig, da man so nem Steve/Alex oft über den Weg leuft.
