### ISSUE TITLE
Shader Esp Bug

### ISSUE THREAD

**Issue by Kaufi2** [CCBlueX/LiquidBounce1.8-Issues#2645]
Wenn ich egal welchen shader esp benutze, dann wird die ganze Welt heller und ich kann die Lebens, Essens - und Xpanzeige nur noch sehen, wenn ich das Menü oder clickgui öffne

**Comment by Marco-MC** [comment]
Einfach nicht den Shader benutzen, wenn deine Hardware es nicht unterstützt. Danke.
