### ISSUE TITLE
Improve xray

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#2647]

**Comment by Marco-MC** [comment]
![](https://img.ccbluex.net/moc/java_2018-10-10_06-36-31.png)

**Comment by Teals53** [comment]
whats different ?

**Comment by Teals53** [comment]
![asdasd](https://user-images.githubusercontent.com/13446881/46735239-4cc9e900-cc9e-11e8-9633-90f42f5540ea.png)
LOL aktivet windows bro
