### ISSUE TITLE
InvertoryCleaner SortFirst module

### ISSUE THREAD

**Issue by GladValakasik** [CCBlueX/LiquidBounce1.8-Issues#2648]

**Comment by BlackHawk2306** [comment]
???

**Comment by GladValakasik** [comment]
Title

**Comment by BlackHawk2306** [comment]
What about it? It isn't really that informative in my eyes

**Comment by GladValakasik** [comment]
SortFirst - When enable ( in invcleaner ), invcleaner first sorts items, then clean inventory
