### ISSUE TITLE
LatestHypixel fly: Start count BoostDelay when player is on air

### ISSUE THREAD

**Issue by NaNaShiSan1** [CCBlueX/LiquidBounce1.8-Issues#2656]
Start count boostdelay when player is on air, not when fly is toggled.

**Comment by Marco-MC** [comment]
What do you mean?

**Comment by NaNaShiSan1** [comment]
Currently, "Boostdelay" on Hypixel fly boosts when the fly is toggled.
In my suggestionl, "Boostdelay" boosts when you take off.

**Comment by Marco-MC** [comment]
Nah, then use Timer or something other. (or make a own module with the new sexy js support lol jk)

**Comment by Teals53** [comment]
ehehehe

**Comment by NaNaShiSan1** [comment]
> Nah, then use Timer or something other. (or make a own module with the new sexy js support lol jk)

Sorry but then why “BoostDelay” setting exist?
@Marco-MC

**Comment by Marco-MC** [comment]
Because the Hypixel Boost is just timer.

**Comment by NaNaShiSan1** [comment]
ik, but I want use “delay” (or boosttime?). as seen in title.

**Comment by Marco-MC** [comment]
I don't understnad your problem? Just enable HypixelLatest-Boost?
