### ISSUE TITLE
add tracers colors

### ISSUE THREAD

**Issue by icewormy3** [CCBlueX/LiquidBounce1.8-Issues#2670]
https://forum.ccbluex.net/thread.php?id=401

**Comment by icewormy3** [comment]
wow 7 months and still nothing. you sure are lazy

**Comment by Teals53** [comment]
yeah marco is super lazy xD

**Comment by icewormy3** [comment]
I have Marco as a friend in discord and he's almost always playing beat saber xD

**Comment by Teals53** [comment]
xD
