### ISSUE TITLE
Localsettings: fucker select cake

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#2688]
Ich würde gerne beim Laden der Autosettings-Datei gleich mit einstellen, dass der Fucker auf den Block cake gesetzt wird, genau so wie der Blockesp. Aber wenn ich in die Localsettings-Datei die Befehle
```
fucker select cake
blockesp select cake
```
schreibe, bekomme ich Fehlermeldungen, wie "value not found".

**Comment by Kaufi2** [comment]
Fucker id 26 (cake)

**Comment by Marco-MC** [comment]
Solved.
