### ISSUE TITLE
Add ResetXZOnToggle and ResetYOnToggle Booleans to Speed

### ISSUE THREAD

**Issue by ClientvsAnticheat** [CCBlueX/LiquidBounce1.8-Issues#2690]
Add ResetXZOntoggle and ResetYOntoggle Booleans to Speed

ResetXZOnToggle sets your X and Z Motion to 0.0 when you turn speed on/off
ResetYOnToggle sets your Y Motion to 0.0 when you turn speed on/off

**Comment by Marco09MC** [comment]
Added (just for Custom Speed)
