### ISSUE TITLE
Add Safe+ Option to SafeWalk

### ISSUE THREAD

**Issue by ClientvsAnticheat** [CCBlueX/LiquidBounce1.8-Issues#2695]
SafeWalk will still protect you from falling down even when you Jump

**Comment by ClientvsAnticheat** [comment]
Pls add to b59 Milestone

**Comment by Marco-MC** [comment]
Added as "AirSafe"

**Comment by yorik100** [comment]
This option isn't working as it should, it stops us from moving while jumping and it should only block movements and velocity when going into the void
