### ISSUE TITLE
ChestStealer autoclose delay

### ISSUE THREAD

**Issue by Kodikusik** [CCBlueX/LiquidBounce1.8-Issues#2696]

**Comment by Teals53** [comment]
AMCIĞA BAK SEN İNGİLİZCEYİ SÖKMÜŞTE LB YE İSSUES ATIYOR İSTEDİĞİ ŞEYDE GEREKSİZ SİKKO BİŞEY NABER LAN YARRRAM SADEOFKAPDFKSPOSAFDASWEFD

**Comment by Kodikusik** [comment]
sen 7/24 burdamısın amk

**Comment by Teals53** [comment]
NE SANDIN YARRAM ASLDÖKFWSAOFJMASOWEFDJRSAMFDESA

**Comment by Teals53** [comment]
SEN NE BOK YİYON BU ARALAR

**Comment by Teals53** [comment]
TÜRÇE KONUŞUYOZ DİYE BAN YİYECEZ AQ ANA SKM

**Comment by Kodikusik** [comment]
Swearing

**Comment by Teals53** [comment]
ÇEVİRİ DETECTED

**Comment by Kodikusik** [comment]
okadarınıda biliyok amk

**Comment by Teals53** [comment]
ehuehueheuhe

**Comment by Kodikusik** [comment]
Marco uyuyhormu

**Comment by Teals53** [comment]
yoq arada uğruyor buralara ama bi bomba bekliyoruz yakında

**Comment by Kodikusik** [comment]
R.a.c. (Best antiçet) crasher getirsin beıveobhı

**Comment by Teals53** [comment]
öyle birşey niye adamın sikinde olsunki aq adam global şeylerle uğraşıyor

**Comment by Kodikusik** [comment]
Mantıklı ozm tick killaura gelsin

**Comment by Teals53** [comment]
harbi ha o zmn +1 +1+1+1+1+1+1+1+1+1+1+1+1+1+1+1

**Comment by Kodikusik** [comment]
Tick killaura  issue UP çekesim var ban yeriz uyarı yedik sıbsbısvog okadar çok up çektikki amk

**Comment by Teals53** [comment]
aynen pasokjfdaıjfaewpofdjseaswed

**Comment by Teals53** [comment]
164 issuesle rekor babada bebeq ayıqs

**Comment by Kodikusik** [comment]
Mal mal issue atarım seni geçerim oc sonra ban yerim ıhsvhıeıgv (yada dur her boka delay isteyem)

**Comment by Teals53** [comment]
mantıklı seni zeki orospu

**Comment by Teals53** [comment]
burayı keraneye çevirdik diyede ban yiyebiliriz

**Comment by Teals53** [comment]
o yüzden tüm yorumlarımı siliyorum sende kendi kendine konuşan yıkık bir orospu evladı olarak duruyosun ağaağağa

**Comment by Kodikusik** [comment]
Kfür etme oc günah Allahımız küfürü farz kılmış ayğ pardon günah kılmış küfür eden çehenlemde yarağı yer

**Comment by Teals53** [comment]
yiyosa 2. dünyada heçk aç bekle ananı sikckeler senin oç

**Comment by Kodikusik** [comment]
Krdşm biz din yolundan çıktık allaha küfür ediyoz istemsizce :/

**Comment by Teals53** [comment]
ağağ salak orospu evladı kendi kenide konuşmuz yazık sakat heralde

**Comment by Kodikusik** [comment]
https://youtu.be/NG9gWLGe6g4 Ehli ıbehıv

**Comment by Teals53** [comment]
bu ne amk

**Comment by Teals53** [comment]
nese ana skm ben gider işim var aq

**Comment by Kodikusik** [comment]
Çi bays

**Comment by Teals53** [comment]
<3

**Comment by Kodikusik** [comment]
Kalp atma gay oc

**Comment by Teals53** [comment]
eyw

**Comment by Teals53** [comment]
temzile şurayı sil yorumları aq

**Comment by Kodikusik** [comment]
Sözde işi vardı bayla burda

**Comment by Kodikusik** [comment]
Kaan Uyar#0001 eqle qrdşm qonuşuruz

**Comment by ClientvsAnticheat** [comment]
Pls add to b59 Milestone

**Comment by Teals53** [comment]
%95 chance its closed like chestaura reach issues

**Comment by Marco09MC** [comment]
Added
