### ISSUE TITLE
ShaderGlow & Shader ESP ignores team color

### ISSUE THREAD

**Issue by yKsenomorf** [CCBlueX/LiquidBounce1.8-Issues#2697]
![7bb33a51b85f73935462bb3fa746b4c4288a1746896c0fa23e6389defd5b0480](https://user-images.githubusercontent.com/34306421/47736180-2684e100-dc7f-11e8-98eb-0ec4a2ee60d3.png)

**Comment by Marco-MC** [comment]
yeah, I know that. I can't modify the color for every player so that's why he use the esp color or rainbow.
