### ISSUE TITLE
Lag caused by Placing & Breaking Blocks

### ISSUE THREAD

**Issue by ClientvsAnticheat** [CCBlueX/LiquidBounce1.8-Issues#2704]
I reallized that placing Blocks seems to cause Lag in LiquidBounce b58 and when the Block that got Placed is near to the Player it lags even more, i sended Marco09MC on the Forums enough Information at the Last Time i reported Performance Issues the Last Time but he never responded to the PM so idk, here Links to Vids: 

Block Placements cause Lag: https://www.mediafire.com/file/ftj4vgd2joo5u4v/BlockLag.mp4/file

I also find that LiquidBounce b55 runs really Smooth, compared to b58
Here a Game with b55, http://www.mediafire.com/file/7rz6rh69gatzutz/LBb55Round.mp4/file
Here a Game with b58, http://www.mediafire.com/file/uc89z046y82fm8t/LBb58Round.mp4/file

**Comment by NaNaShiSan1** [comment]
Me too, I just experienced lag when I use scaffold

**Comment by yKsenomorf** [comment]
+1

**Comment by Dronatar** [comment]
+1

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2715

**Comment by Marco-MC** [comment]
We uploaded a fixed version of LiquidBounce b58. Try re-downloading.
