### ISSUE TITLE
ClickGUI Panel Bug

### ISSUE THREAD

**Issue by yKsenomorf** [CCBlueX/LiquidBounce1.8-Issues#2707]
Perfectionist hell

![3f4e029ff89e34d4f6fa0b16aae967a5bafddcbc5763c80aaf9a7ffb5e1718e8](https://user-images.githubusercontent.com/34306421/47910935-5d3c4080-dea5-11e8-8126-392f0351a0bb.png)

**Comment by SenkJu** [comment]
This is on purpose.
