### ISSUE TITLE
Feature to disable AutoReconnect

### ISSUE THREAD

**Issue by NaNaShiSan1** [CCBlueX/LiquidBounce1.8-Issues#2709]
Since it’s annoying sometime.
Well, that’s looks like duplicated. But please not close. 
Because original suggestion from like 10 months ago.

**Comment by Kodikusik** [comment]
#1667

**Comment by SenkJu** [comment]
Duplicated

**Comment by NaNaShiSan1** [comment]
@SenkJu please open the issue. I NEVER think dev can go to page 6 for consider what should’ve add in LB... I guess dev can only view page 1-2. not page 6.
