### ISSUE TITLE
Suggestion: close the very old issue/suggestion

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2710]
Very old issue is not closed! What could it means? You know, that because dev don’t want to fix/add.

**Comment by Kodikusik** [comment]
old open issue = waiting to add

**Comment by NaNaShiSan1** [comment]
What about 1 year old issue? Lol

**Comment by Teals53** [comment]
cuz marco is lazy

**Comment by Marco-MC** [comment]
uh, I don't know.
