### ISSUE TITLE
Add a Module which allows you to look in a Different Direction than the Walking Direction

### ISSUE THREAD

**Issue by ArrowReport** [CCBlueX/LiquidBounce1.8-Issues#2713]
Add a Module which allows you to look in a different direction than the direction you are Walking to, so when you would hold LCONTROL, the Camera Pitch and Yaw would deattach from the Minecraft Char, 
Bad Example: https://vgy.me/xBmTTL.mp4

**Comment by SenkJu** [comment]
Seems pretty useless to me.
