### ISSUE TITLE
add baritone(mining bot, pathing finding, ...)

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#2718]
add this
https://github.com/cabaletta/baritone

**Comment by Slimerblue22** [comment]
Baritone was made for 1.12, might be better to move this to the 1.12 issues/suggestions. But then again 1.12 isn't really being worked on so I don't know.

**Comment by Teals53** [comment]
this a.ı have a fightbot ? @Marco09MC
