### ISSUE TITLE
FOVChanger Hand or Holding item

### ISSUE THREAD

**Issue by MaxUltimat3** [CCBlueX/LiquidBounce1.8-Issues#2721]
Hi you can do it to me a liquidscript FOV Changer for hand to change a position on hand

**Comment by MaxUltimat3** [comment]
![omjvspz](https://user-images.githubusercontent.com/31041659/48361126-7f09a480-e6a9-11e8-84af-35aa97490c55.jpg)
Exemple

**Comment by SenkJu** [comment]
There are 3rd-party mods for that.

**Comment by MaxUltimat3** [comment]
>           There are 3rd-party mods for that.

You cant send my a link pls?
