### ISSUE TITLE
File Chooser freeze client (file chooser behind lwjgl window)

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2725]
Two people have reported that as soon as they click on Import they don't have any feedback and can't do anything anymore (not even in the Import menu). 

https://vgy.me/xYPjbn.png
https://vgy.me/9ydC2D.png

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1201

**Comment by Marco09MC** [comment]
https://axolotl.vip/HL7l/RZufLwWu.mp4
