### ISSUE TITLE
Inventorycleaner Skywars mode

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2728]
add a skywars mode thats clean out Chests, ladders, furnance, workbench, cobweb and Note Block. Its sucks with the scaffold if its place one of the blocks.

**Comment by barbiehunter** [comment]
#1393

**Comment by yKsenomorf** [comment]
#2239

**Comment by SenkJu** [comment]
Duplicated
