### ISSUE TITLE
Scaffold Option SameY

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2733]
Diese Scaffold option sorgt dafür das der scaffold nur auf der Starthöhe baut. Also auch wenn man Sprint nichts unter einem plaziert wird.
Wieso? Nützlich für Server auf denen Speed geht und wenn diese Springen baut sich der scaffold ungewollt hoch.

**Comment by Marco09MC** [comment]
Added
