### ISSUE TITLE
problem with the gui 

### ISSUE THREAD

**Issue by ori1337** [CCBlueX/LiquidBounce1.8-Issues#2739]
when i got to funTAB on the guiTab on screen 
everything just glitch out 

Please fix it thanks

**Comment by yKsenomorf** [comment]
![454924918950199316](https://user-images.githubusercontent.com/34306421/49384603-692d5380-f72c-11e8-9e5a-dab01b8c6706.gif)

**Comment by Marco-MC** [comment]
What do you mean?
