### ISSUE TITLE
Aimbot Ideas [Suggestions]

### ISSUE THREAD

**Issue by SextupleTap** [CCBlueX/LiquidBounce1.8-Issues#2742]
Here are a few ideas I had for the aimbot modes, you can do with these as you wish. (Whether that be including, none, some or all of them).

Improvement: 
"TurnSpeed" should be able to accept a decimal value (in the command) instead of only integers.

New Ideas:
1) TurnSpeed could be updated to have vertical and horizontal speed settings. 
(Example: VTurnSpeed and a HTurnSpeed, command syntax is also changed respectively)

2) (This one is probably not needed but I am still tossing the idea out there):
A toggle-able mode could be added (such as the existing "OnClick," or "Jitter" features) maybe called "HitboxTracking" that stops all tracking when the cursor successfully raycasts within a specific distance inside the opponents hitbox, but once the cursor leaves the hitbox, you start tracking your opponent again.

3) "AimingPriority" dropdown mode, where the settings can be: 
**head** (aims at the head), 
**body** (aims at the center of the body as it currently does as of B59 - this is the default setting),
**feet** (aims at the feet), 
**tracking** (it tracks the position of the player relative to you [y value], and will try to aim at the head, body, or feet respectively to ensure you land the most hits.)

4) Lastly, "TargetPriority" dropdown mode, where the settings can be:
**none** (default tracking [as of B59] - this is the default setting)
**lock** (remembers which entity it started tracking first and it will continue to track that entity until it is dead or it is out of range)
**distance** (closest entity is targeted)
**health** (lowest health entity is targeted)

Anyways, those are my ideas, you can do what ever you wish to do with them, thank you for reading.

**Comment by Dronatar** [comment]
Impact 2.0 :)

**Comment by ClientvsAnticheat** [comment]
ThroughWallsRange should be added too

**Comment by Soulplexis** [comment]
Aimpriority is NOT (completely) useless. If you aim for the head, you can get the most range. If you aim for body or head some anticheats will flag (bad ones... though).

**Comment by SextupleTap** [comment]
:D I hope some of these could be added too

**Comment by SextupleTap** [comment]
Bump

**Comment by yorik100** [comment]
Bump 2

**Comment by SextupleTap** [comment]
It has been a while, but I certainly hope that "AimingPriority" and "TargetPriority" could be added at least, since those are the most useful ones

**Comment by Teals53** [comment]
But so why close issue ?

**Comment by yorik100** [comment]
But so why close issue ?
