### ISSUE TITLE
Whitelist Heads (Skulls) in InvCleaner & ChestStealer

### ISSUE THREAD

**Issue by ClientvsAnticheat** [CCBlueX/LiquidBounce1.8-Issues#2743]
Whitelist Heads (Skulls) in InvCleaner & ChestStealer

Because UHC and Hive Skywars still a thing.

**Comment by Teals53** [comment]
ı am waiting this https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1393 @Marco-MC

**Comment by Teals53** [comment]
custom whitelist

**Comment by ClientvsAnticheat** [comment]
If you don't want to Whitelist more stuff add this instead #2538

**Comment by SenkJu** [comment]
Duplicated
#1393
