### ISSUE TITLE
InventoryCleaner custom whitelist

### ISSUE THREAD

**Issue by NaNaShiSan1** [CCBlueX/LiquidBounce1.8-Issues#2745]
Why not?

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1393

**Comment by Marco-MC** [comment]
@NaNaShiSan1 Stop reporting... dl.ccbluex.net to uBlock... .-. xd
I'm a lazy guy and don't want to always add new detections to the AdBlocker detection, oof.

![soc9g6pr](https://user-images.githubusercontent.com/12410754/49466471-74ea4a00-f800-11e8-9bb1-5a3438fdd4ac.png)

+ Duplicated Issue

**Comment by NaNaShiSan1** [comment]
@Marco09MC that’s not ublock though

**Comment by Teals53** [comment]
why ı cant find this issues ? #1004 #959 #956 #940 its show different issues ? maybe its different place ?

**Comment by NaNaShiSan1** [comment]
I’m a lazy guy and don’t want to always report new detections to the nano defender, oof.

**Comment by Teals53** [comment]
xD

**Comment by SenkJu** [comment]
No ads -> no money -> no servers -> no websites -> no LiquidBounce

**Comment by NaNaShiSan1** [comment]
There’s people using LiquidBounce without AdBlocker, so it’s fine

**Comment by SenkJu** [comment]
And why are you using LiquidBounce but do not want us to earn money from your ad impressions? It is only five seconds.

**Comment by Teals53** [comment]
use adguard windovs application its undetectable

**Comment by NaNaShiSan1** [comment]
Because I don’t like ad, period.

**Comment by Teals53** [comment]
can you send this issue link ? me

**Comment by NaNaShiSan1** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues?utf8=✓&q=dl.ccbluex.net

**Comment by SenkJu** [comment]
Nobody "likes" ads but they are necessary otherwise we will not be able to maintain LiquidBounce for free.

**Comment by Teals53** [comment]
its a anti-adblock extension ?

**Comment by NaNaShiSan1** [comment]
Ad revenue will remain since there’s people using liquidbounce without Adblocker.
@Teals53 that’s like anti-anti-adblock

**Comment by SenkJu** [comment]
What if everyone thought like you?

**Comment by NaNaShiSan1** [comment]
Not going to happen. Look, you still receive your revenue.

**Comment by Teals53** [comment]
anti-anti-adblock = adblock

(-1)x(-1)= +1

ehueheuheheu

**Comment by SenkJu** [comment]
To put this discussion to an end: If you don't stop reporting our website, we will no longer work on any suggestions made by you.

**Comment by NaNaShiSan1** [comment]
That’s fine, you could create a new account.

**Comment by NaNaShiSan1** [comment]
Period.
