### ISSUE TITLE
Adding KeepSprint module

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#2748]
Title

**Comment by CzechHek** [comment]
Sprint module? Close this.

**Comment by yorik100** [comment]
> 
> 
> Sprint module? Close this.

SPRINT MODULE DOESN'T REMOVE THE SLOWDOWN YOU GET BY HITTING PEOPLE (I made a script that fixed that tho, it's not needed anymore)

**Comment by Teals53** [comment]
but killaura already have that for remove this slowdown ?

**Comment by yorik100** [comment]
> 
> 
> but killaura already have that for remove this slowdown ?

AutoClicker doesn't have that bruv, and only having KeepSprint wasn't possible
