### ISSUE TITLE
Add heads tab configuration to file cloud

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#2753]

**Comment by Marco-MC** [comment]
Added

https://github.com/CCBlueX/FileCloud/blob/master/LiquidBounce/heads.json

**Comment by Teals53** [comment]
what is this marco

**Comment by Marco-MC** [comment]
Just a configuration for me to disable the heads tab or change API url etc...

**Comment by Teals53** [comment]
oh ok
