### ISSUE TITLE
.binds clear command

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2758]
This will clear all binds -> nothing will be bound
Useful for clearing his bind, clearing the defaul binds

**Comment by Marco09MC** [comment]
Added

**Comment by Marco09MC** [comment]
![](https://axolotl.club/Qs8CKVNc.png?key=BQxZBGog8r5KVV)
![](https://axolotl.club/6L3SeZsu.png?key=se1mnNXEaNBQHO)
