### ISSUE TITLE
Scrolling in settings of the ClickGUI

### ISSUE THREAD

**Issue by Trol1337** [CCBlueX/LiquidBounce1.8-Issues#2761]
At the moment, you can't scroll in the ClickGUI settings, which is bad for monitors below the 1920x1080 resolution.

**Comment by Teals53** [comment]
what ?

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1970
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2659
