### ISSUE TITLE
İnteresting Wurst Option

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2763]
https://www.wurstclient.net/updates/wurst-6-25/

**Comment by Teals53** [comment]
Wurst İs Really Shitly Client But İts Have Some İnteresting Module

**Comment by Teals53** [comment]
And Lb AutoFish Automatically Select Best Fishing Rod ? Or Not

**Comment by Teals53** [comment]
https://www.wurstclient.net/updates/wurst-6-23/

İntersting AutoFish Range Option

**Comment by Teals53** [comment]
And some nice autoarmor things
https://www.wurstclient.net/updates/wurst-6-20/

**Comment by Teals53** [comment]
and what is forceop ?

**Comment by Teals53** [comment]
https://www.wurstclient.net/updates/wurst-6-10/

interesting A.I things

**Comment by Teals53** [comment]
and some jigsaw options like hackerdetectorgui or fakehacker(ı dont remember this option name full but if u open this your near player attack you like a killaura but he actually not attack you its fake so you can report him xD)

**Comment by Teals53** [comment]
damn dude

**Comment by Teals53** [comment]
this autofish range is reallay interesting but ı dont know its needed things or not ? can you give me more information for this ? thx @Marco09MC

**Comment by Marco09MC** [comment]
Please don't ... just list some things and say: "hey look that could be cool to have". Just create a new issue, explain what is does and then I will maybe implement the feature into LiquidBounce.

As example there is already a Issue about an AI:  https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2718
Or the AutoArmor features that LiquidBounce already have???... ![](https://axolotl.club/fbv6MP19.png?key=wHAguQMul8yFZ6)

and... LiquidBounce is not a client for random AFK Farming or something (so I don't care about AutoFish). It's more a combat and griefing client.

**Comment by Teals53** [comment]
liquidbounce is the best client in the world for pvp minigames or other but ı think its need more good modules or options for compatible with all server types like faction servers(farming mining) and server griefing and like this thing ı dont know  , and ı dont remember for autoarmor things ı dont play minecraft long time sorry

because all things for hacking just in 1 client = GOD

and sorry for my shit english @Marco09MC xD
