### ISSUE TITLE
Q: I Can Find Spawner Use BlockESP ?

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2767]

**Comment by Teals53** [comment]
and what the fuck is this LMFAO 

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/356

**Comment by Marco09MC** [comment]
Sure, just select Monster Spawner as target Block.

![](https://axolotl.club/ZFhziLKV.png?key=11AxSoamYJVP7h)

**Comment by Teals53** [comment]
<3<3<3<3
