### ISSUE TITLE
W-Tap

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2768]
![image](https://user-images.githubusercontent.com/13446881/49673111-5f825380-fa7e-11e8-93a7-34ab7da44f6c.png)

**Comment by Marco09MC** [comment]
Could you explain what this module do?

**Comment by Teals53** [comment]
its a pvp tactic maybe its spamming W but ı dont know how its work in client like (what is range)

**Comment by SenkJu** [comment]
This basicalls is what SuperKnockback does.

**Comment by Teals53** [comment]
but maybe its more legit and have customization ?
