### ISSUE TITLE
Q: Can Possibly ?

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2769]
is it possible to do a trick that can be injected into the game without forge ?

or just with optifine ?

**Comment by Marco09MC** [comment]
Sure, LiquidBounce already have the possibility to inject into Vanilla Minecraft. It's just that LiquidBounce is not fully compatible yet with Vanilla (so it will crash very often etc).

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2698

**Comment by Teals53** [comment]
With All Modules ? And I Can İnject This Version Some Custom Clients ?

**Comment by Teals53** [comment]
ı am saying "firstly open vanilla client or optifine client or custom client after than open hack client"

**Comment by Teals53** [comment]
and vape 2.47 crack use this method ? but its need forge ı need without forge inject client

**Comment by Teals53** [comment]
@Marco09MC thank you in advance for your answer.

**Comment by Teals53** [comment]
or like vape lite ı dont know how its work but if blatant features injected vanilla why no body dont do/make any client or other thing ?

**Comment by Teals53** [comment]
can you inject lb into sonoyuncu client ? @Marco09MC if this version released ı test this but u already have this so can you test this for me ? ı already write u in discord laucnher link and alt @Marco09MC
