### ISSUE TITLE
proper color selection

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#2770]
Statt sliders für Rot Grün Blau könntet ihr nen colorpicker adden.

Beispiel:
https://www.purplesquirrels.com.au/2014/02/creating-mathematical-colour-picker/

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1587
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2659
