### ISSUE TITLE
More Minigames Support

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2780]
![image](https://user-images.githubusercontent.com/13446881/49704208-2209fb80-fc21-11e8-860f-1bc5961bc52e.png)

idk prophuntesp do all ?

ss from impact

**Comment by superblaubeere27** [comment]
List

**Comment by Teals53** [comment]
> List

So

**Comment by superblaubeere27** [comment]
QuakeCraft and MurderMystery should be supported IMO since it is fairly easy to do so. But in terms of QuakeCraft... can't you just use aimbot?
