### ISSUE TITLE
Pingspoof sytanx bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2782]
https://forum.ccbluex.net/thread.php?id=886

**Comment by Teals53** [comment]
İts like this https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2404

**Comment by Marco09MC** [comment]
![](https://axolotl.club/tZ4LofSn.png?key=OTSwy7WrTE3SlG)

???

**Comment by Teals53** [comment]
this is not my issues

**Comment by ThisIsAccount** [comment]
@Marco09MC please reopen this issue

**Comment by ThisIsAccount** [comment]
Prefix is wrong
