### ISSUE TITLE
Add module to see commands in clickable chat elements.

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2785]
/tellraw @A {"text":"Das ein test click me","clickEvent":{"action":"run_command","value":"/gamemode 1"}}

As example for this, it would show the "/gamemode 1" command when hovering over the chat element

Possible way todo it: Instead of executing the command, its write the command in the chat.

**Comment by scorpion3013** [comment]
/tellraw @a {"text":"Das ein test click me","clickEvent":{"action":"run_command","value":"/gamemode 1"}}

As example for this, it would show the "/gamemode 1" command when hovering over the chat element

**Comment by Marco09MC** [comment]
Added
