### ISSUE TITLE
InventoryCleaner Improve

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2788]
Enteweder:
A: ein eigenen Mode für Inventorysorter machen
B: Beim Inventorycleaner adden das man Cleaner ausmachen kann, damit das inv halt sortiert wird aber trotzdem nix raugeschmissen wird (könnte nützlich sein bei manchen minigames etc.)

**Comment by yorik100** [comment]
+1

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3141
