### ISSUE TITLE
Man kann LiquidBounce nicht ohne Internet starten.

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#279]
Bitte Fixen

**Comment by Marco-MC** [comment]
1. Was zum teufel willst du ohne Internet in Minecraft mit Cheats machen? Im Singelplayer rumlaufen und Kühe schlachten oder was?

2. Das ist mit absicht, damit es nicht so leicht ist LiquidBounce zu renamen. ^^

**Comment by WistarWolf** [comment]
1. Wenn das Internet ausfällt? Und man im Singelplayer was bauen will? 
2. Ist die Obf. bzw Anti Modify nicht im Client Code?

**Comment by SenkJu** [comment]
1. Wozu braucht man dafür LiquidBounce.
2. Nein, das funktioniert mit MD5 Checksums, die aus dem Internet geladen werden müssen.

**Comment by Marco-MC** [comment]
War grade auch am schreiben. xd

**Comment by WistarWolf** [comment]
1. Just for Fun xd
2. Oke
