### ISSUE TITLE
Vanilla & Mineplex FullBlock Phase

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#2794]
by @yorik100 (written in JavaScript with the LiquidBounce ScriptAPI)

**Comment by yKsenomorf** [comment]
:new_moon_with_face:

**Comment by Teals53** [comment]
vanilla ? phase not working from vanilla ?

**Comment by Marco09MC** [comment]
sure? @Teals53

**Comment by Teals53** [comment]
alright why title say Vanilla FullBlock Phase

**Comment by Marco09MC** [comment]
because this phase work for vanilla too idk

**Comment by Teals53** [comment]
ı say this vanilla phase already have in lb and its working ?

**Comment by yorik100** [comment]
None of the phases were working on LB since it was getting the violation level too high before being able to go thru blocks wich was making all the phases useless

**Comment by Teals53** [comment]
no

**Comment by Teals53** [comment]
no for this "all the phases useless"

**Comment by yorik100** [comment]
You'll most likely get kicked if you try to use a phase before going thru a block plus this one instantly go thru the block without any problem

**Comment by Marco09MC** [comment]
Added

**Comment by Marco09MC** [comment]
https://img.ccbluex.net/moc/2018-12-17_18-36-00.mp4
