### ISSUE TITLE
New Cubecraft bypasses maybe

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2799]
1. A new cubecraft fly that doesn't flag back
2. Maybe make a Nofall for cubecraft if its possible

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2814

**Comment by Marco09MC** [comment]
CubeCraft NoFall: https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2852
