### ISSUE TITLE
Hypixel tower (faster tower for hypixel)

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#2802]

**Comment by 215789586** [comment]
"Tower": {
    "Mode": "ConstantMotion",
    "AutoBlock": "true",
    "StayAutoBlock": "false",
    "Swing": "false",
    "StopWhenBlockAbove": "false",
    "Timer": "1.0",
    "JumpMotion": "0.42",
    "JumpDelay": "0",
    "ConstantMotion": "0.42",
    "ConstantMotionJumpGround": "0.76",
    "TeleportHeight": "1.15",
    "TeleportDelay": "3",
    "TeleportGround": "false",
    "TeleportNoMotion": "false",
    "Counter": "false"
  },
This bypasses

**Comment by 215789586** [comment]
default ConstantMotion bypasses.but sometimes it still bans(maybe too fast?)
