### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2806]
bei Multiplayer oder ka wo die möglichkeit haben (wenn es geht) die RPC (anzeige) für Liquidbounce zu deaktivieren. (fallst die legit schwitzer nicht wollen, dass ihre kumpels wissen das sie cheaten :) )

**Comment by barbiehunter** [comment]
Edit: mach das man sieht, dass man Minecraft spielt oder wenn man mit Labymod zockt halt Labymod angezeigt wird bei discord

**Comment by NurMarvin** [comment]
bump @Marco09MC

**Comment by mrphax0r** [comment]
@NurMarvin Issues bumpen nicht

**Comment by mrphax0r** [comment]
Glaube ich
