### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2813]
Adde mal radio damit die leute mal was zum hören haben ( ͡° ͜ʖ ͡°) und wenn es geht 10 std loli atmen damit man was zum entspann auch hat ヽ(✧ᗜ✧)ﾉ

**Comment by Elelrxi** [comment]
10/10

**Comment by yorik100** [comment]
11/10

**Comment by Elelrxi** [comment]
12/10 :axomad:

**Comment by SenkJu** [comment]
http://www.radio.de/
