### ISSUE TITLE
".localautosettings save" command didn't work

### ISSUE THREAD

**Issue by cui0v0** [CCBlueX/LiquidBounce1.8-Issues#2829]
".localautosettings save" command didn't work in LB b60, client just save a empty file. And certainly, no texts are in that file.
![mx5t lpbe r1tkmla8 f1](https://user-images.githubusercontent.com/29875719/50725432-7dec7500-1138-11e9-97e5-7a19f169a1e6.png)
![a bahzg _a7d0jj3w51c20z](https://user-images.githubusercontent.com/29875719/50725438-8644b000-1138-11e9-981b-35b1a8e68d3b.png)
![n6 3c 191hfb js1h3 14 e](https://user-images.githubusercontent.com/29875719/50725442-9066ae80-1138-11e9-9e2d-4ee8be65aabd.png)
![h0v f_6zg f_k 1s o8zcpm](https://user-images.githubusercontent.com/29875719/50725445-965c8f80-1138-11e9-8e9a-d36d48e9f819.png)

**Comment by scorpion3013** [comment]
Workaround:
Give the optional option.
You can see all options with ".localsettings save"
Example: ".localsettings save 123 all"

**Comment by SenkJu** [comment]
Fixed.
