### ISSUE TITLE
Nametags Settings

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#283]
NameTags Dont Show Armor Ench Level Pls Update Thanks

**Comment by MaxHD00** [comment]
Bitte noch hinzufügen das man die grösse der Nametags einstellen kann.

**Comment by Teals53** [comment]
Am I talking about this ?

**Comment by Teals53** [comment]
@Marco-MC Maybe You Add This :P

**Comment by Teals53** [comment]
@Marco-MC Up

**Comment by Teals53** [comment]
@Marco-MC last up
