### ISSUE TITLE
Fullbright nicht ausschaltbar

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#2830]
Wenn ich Fullbright anschalte, wird alles hell - soweit ok. Aber wenn ich Fullbright ausmachen, bleibt alles hell, es sollte aber dunkel werden.

**Comment by Marco09MC** [comment]
before restart: https://i.axo.im/9b7-loli-Ame/9GAmKiv4.mp4
after restart: https://i.axo.im/tll-loli-yQT/rfRiMzzc.mp4
