### ISSUE TITLE
Hypixel New Fly bypass (Jan 2019)

### ISSUE THREAD

**Issue by Leejames2305** [CCBlueX/LiquidBounce1.8-Issues#2832]
During this week , there are many client start having the new Hypixel fly bypass . It bypass by damaging themselves and Fly with high timer . 

Here's a client preview video showing off it is bypassing . https://www.youtube.com/watch?v=jbc4lk7grbE

**Comment by Marco09MC** [comment]
@yorik100 I will not use stolen code.

**Comment by Marco09MC** [comment]
Added
