### ISSUE TITLE
Scaffold setspeed broken

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#2836]
Not working at all
https://gyazo.com/344a37a1809edf1701580635728f5507
See speed going crazy

**Comment by SenkJu** [comment]
SpeedModifier only makes you go faster when you are actually using Scaffold https://img.liquidbounce.net/uxc/2019-02-16_19-13-44.mp4

**Comment by yorik100** [comment]
I had Rewinside mode, but the speed modifier doesn't work while jump scaffolding, in Normal and Expand modes too
