### ISSUE TITLE
Inventorycleaner + Autoarmor fix/improve

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2838]
Mach es so, dass zuerst das Unnötige/schlechte zeug vom invcleaner weg geworfen wird (wenn es halt natürlich an ist) aber die gute/bessere rüstung und/oder rüstung, waffen etc. behalten werden und es dann halt "sortiert/angezogen" wird. Und am ende wird halt das alte zeug weg geworfen was bug fixt was man manchmal am ende kein schwert hat oder ein rüstung teil fehlt

**Comment by Elelrxi** [comment]
Most of the time it works but that sometimes happens for me aswell

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3056
