### ISSUE TITLE
list of suggest

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#2840]
MurderMystery mod (checks like Sprint, Weapons, Tools, HoldingAnyItem, Team\color)
Remove nofriends add Friends as target
Hypixel LongJump
Hypixel diagonal scaffold bypass
New Hypixel fly (Current sometimes bans i think?) 
Rename Hypixel and OtherHypixel to Airwalk or something
Hypixel Zoom fly
Hypixel AutoBlock(?)
Hypixel YPort
Hypixel... Timer? (No onground timer?)
Disable KillAura,ConsoleSpammer, Godmode (similar to Nuker and Timer) upon disconnecting.

**Comment by yorik100** [comment]
> New Hypixel fly (Current sometimes bans i think?) -> Ye, that's what I thought
> Rename Hypixel and OtherHypixel to Airwalk or something -> I'm pretty sure Airwalk doesn't mean that it bypasses Hypixel
> Hypixel Zoom fly -> It's being made
> Hypixel... Timer? (No onground timer?)  -> ?
> Disable KillAura,ConsoleSpammer, Godmode (similar to Nuker and Timer) upon disconnecting. -> Also servercrasher (and upon world change) *as an option*

**Comment by Soulplexis** [comment]
rename the fly modes so that new users don't use them. they might see otherhypixel and try to use it and get banned.
hypixel doesn't detect timer if you are in the air using it. also theres no use to timer while standing still other than fasteating
