### ISSUE TITLE
Enchant command

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#285]
Wenn du Creative bist sollen diese Befehle hinzugefügt werden: 
.enchant Schärfe 100 =   Das Item in deiner Hand bekommt die Verzauberung Schärfe 100
.enchant all = Das Item in deiner Hand bekommt alle Verzauberungen die es gibt. (LVL 127)
.enchant none = Das Item in deiner Hand verliert alle Verzauberungen die es drauf hat.

**Comment by MCmodding4K** [comment]
benutz .give solange es das noch net gibt

**Comment by Marco-MC** [comment]
Added.
