### ISSUE TITLE
Add CubeCraft NoFall (with code) 

### ISSUE THREAD

**Issue by DeleteAndInsert** [CCBlueX/LiquidBounce1.8-Issues#2852]
Coded in LiquidScript ;)

    this.onUpdate = function() {;
        if(mc.thePlayer.fallDistance > 2.0) {
            mc.thePlayer.onGround = false;
            mc.thePlayer.sendQueue.addToSendQueue(new C03PacketPlayer(true));
        }
    } 

I don't know if the other nofall's in LB work on Cube, but this one works 100%.
For people who want to use it right now, here is code for LiquidScript. 

    this.onUpdate = function() {;
        if(mc.thePlayer.fallDistance > 2.0) {
            mc.thePlayer.onGround = false;
            C03PacketPlayer = Java.type('net.minecraft.network.play.client.C03PacketPlayer');
            mc.thePlayer.sendQueue.addToSendQueue(new C03PacketPlayer(true));
        }
    }

**Comment by Marco09MC** [comment]
Added
