### ISSUE TITLE
Diagonal Expand scaffold not working sometimes

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#2862]
https://streamable.com/zsfo7
Same goes for jump sprint scaffold
This is a problem since Normal scaffold is detected on Plex

**Comment by CzechHek** [comment]
Probably fixed, close this.

**Comment by superblaubeere27** [comment]
No @CzechHek

**Comment by Teals53** [comment]
if no why u closed that ? @superblaubeere27

**Comment by superblaubeere27** [comment]
Because it `Works as intended`?

**Comment by Teals53** [comment]
true im stupit blind

**Comment by yorik100** [comment]
The fuck what, I'm at the border of a block and pressing forward, my player isn't moving and 0 blocks are getting placed
