### ISSUE TITLE
AutoSettings use GitHub API instead of list file

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#2887]
https://api.github.com/repos/CCBlueX/FileCloud/contents/LiquidBounce/autosettings

**Comment by SenkJu** [comment]
New syntax: 
.autosettings <list/load>
.autosettings load <servername/url>

**Comment by icewormy3** [comment]
now you just make it longer to get the settings. stupid

**Comment by SenkJu** [comment]
No, we made it more coherent with LocalAutoSettings and improved it by using GitHub's API instead of simply loading a settings file called "list".
