### ISSUE TITLE
[FEATURE] New cubecraft fly

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2888]
Neuer/Besserer Cubecraft Fly der wie Akrien ist (Gerader scaffold der aber hoch und runter geht)

Wenn du Akrien nicht hast heul mich eben an kann dich freischalten :)

**Comment by yorik100** [comment]
+1 ja

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2980
