### ISSUE TITLE
[FEATURE] Scaffold Randomize Place Position

### ISSUE THREAD

**Issue by je5442804** [CCBlueX/LiquidBounce1.8-Issues#2891]
Don't always place blocks in the center
It seem that some server can detect it now
https://streamable.com/gxzgn

**Comment by je5442804** [comment]
but skid bypass it
https://streamable.com/h8ouv

**Comment by itsTyrion** [comment]
You have scaffold set to "Expand". 
Expand places one or more blocks ahead. (look where it aims at in F5)
Try setting it to "Normal"

**Comment by 6alpha9** [comment]
Skid b12.4 bypasses AACP but not cubecraft (scaffold)

**Comment by je5442804** [comment]
ya,the server have AAC ,AACP and BAC

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2977
