### ISSUE TITLE
[FEATURE] AutoMLG

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2892]
Mach mal  automlg rein, da es mit fastplace oder Normal scheiße (also das man stirbt) Mach einfach das als modul was man vor dem runter laufen/spring anmachen muss und es dann wasser/spinnenwebe unter ein platziert.

als keline funktion vllt noch machen, dass man aus und anmachen kann was es sein soll (eimer und/oder web) und ob es automatisch in der hand platziert werden soll

**Comment by Tcm9** [comment]
Könnte man als Nofall mode einfügen. Wenn Man dann Wasser oder Spinnweben in der Hotbar hat, dann platziert er den Block unter einem, wenn man mehr als 1 Herz schaden bekommt.
