### ISSUE TITLE
[BUG] Fix the reach module - It is very broken

### ISSUE THREAD

**Issue by SextupleTap** [CCBlueX/LiquidBounce1.8-Issues#2897]
**Describe the bug**
The reach module is just all around broken, firstly it manipulates the block interaction range (destroying, placing, interacting with tile entities etc.) when it shouldn't do that, it should remain unmodified only modifying the attack range.

Then the range for reach should go from 3.0 to 5.0 and 3.0 being the default range you can attack a player from. Currently, at 3.50 (the lowest minimum) it is actually less then what you're able to normally hit a player from, which shouldn't be happening, and values such as 4.0 are actually a bit over 4 when it shouldn't be. It needs to be re-written to work as it is supposed to from 3.00 to 5.00 and without effecting the block interaction range.

**To Reproduce**
1. Activate reach an attempt to attack players/break or interact with blocks

**Screenshots**
N/A

**Additional information:**
 - OS: Windows 10
 - LiquidBounce B61
 - 1.8.9

**Comment by Marco09MC** [comment]
... the Reach module is for build and combat.

I will add a slider for combat range and build range.

**Comment by Marco09MC** [comment]
Added
