### ISSUE TITLE
[Improve]  Projectiles

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2902]
1. Improven das es halt nicht beim bow die voll "Loading" anzeigt sondern die reichweit stufen (beschreibung 11/10)
2. es WENN du willst bla bla es auch für andere spieler machen. Also das du siehst z.b wenn ein anderer spieler mit dem bow oder Schneeball etc.  wo hin "schießt" könnte eins nice feature sein

**Comment by SenkJu** [comment]
1. Added DynamicBowPower setting to Projectiles: https://axolotl.club/18E3isyd.mp4?key=QZKLVxebtbw2QK
2. Might add that in the future.
