### ISSUE TITLE
[BUG] Criticals block "bug" (maybe not only cubecraft)

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2903]
Beschreibung
Wenn über dir ein block ist besteht die Wahrscheinlichkeit, dass du autogebannt wirst und das passiert auch wohl WENN über oder unter dir ein Gras Block ist. Wäre schön das mal fixed zu haben ;)

Screenshots
Kein bock :axolaugh:

Information
 - LLiquidbounce b62
 - Minecract 1.8.9

**Comment by SenkJu** [comment]
Unable to reproduce.
