### ISSUE TITLE
[Improve] Scaffold/Tower Autoblock

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2904]
Hier war nur müll achte auf das unten

**Comment by barbiehunter** [comment]
Ok ehm Marco vergiss das Oben xD du msust nur noch Dropper/Werfer adden

**Comment by barbiehunter** [comment]
Ahja und Soul sand auch damit geht scaffold nichtmal so richtig. Ps must nur*

**Comment by barbiehunter** [comment]
PS: Counter "Improve" das die ignorierten blöcke beim scaffold nicht beim Counter mit als Blöcke angezeigt werden ( https://vgy.me/9exlve.png )

**Comment by SenkJu** [comment]
Added droppers, dispensers, lilypads, pressure plates and noteblocks to blacklist.

**Comment by yKsenomorf** [comment]
Don't forget about crafting tables and furnaces @SenkJu
