### ISSUE TITLE
[Improve] Little Discord RPC "Improve"

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2905]
bei der Liquidbounce RPC noch so machen, wenn man über das Logo geht das Liquidbounce.net angezeigt wird (wie auf dem bild https://vgy.me/bgkCbl.png

**Comment by Marco09MC** [comment]
https://i.axo.im/FPX-loli-a2t/bg8FR3um.png
