### ISSUE TITLE
[FEATURE/Improve] Cubecraft fly

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2906]
Versuchen die beiden Infinify cubecraft fly's zu updaten. Die gehen durch bei den runden aber nur während der warte zeit, Sobald die runde beginnt gehen die flys nicht mehr. Wäre einfach guter/schöner ersatz für den anderen fly

**Comment by True-cc** [comment]
Akrien has an infinite fly.

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2980
