### ISSUE TITLE
[FEATURE/Improve] Automatic Vclip

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2908]
Einfach erklärt in deutsch: 2 vclip option, wenn er die obare nicht benutzen kann z.b + nehmt er die darunter die im - bereich ist. Kann nützlich sein für andere server bestimmt wo es auch bestimmte maps gibt, wo dann das im + bereich nicht geht.

vclip with + and - and then do it via automatic vclip. So if he can't up with + (as example 4.0) then he tries to go down with the - specification (as example -2.7) Could be helpfull would be some maps and maybe other server.

**Comment by SenkJu** [comment]
What?
