### ISSUE TITLE
[FEATURE] PEX ServerCrasher

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2911]
Wie sir scorpion schon vorgeschlagen hat https://axolotl.club/7hvdSZma.png?key=RvOjYoA7Td92wQ ;)

**Comment by scorpion3013** [comment]
anmerkung: alle zeichen die in der uuid möglich sind.

**Comment by Marco09MC** [comment]
Added
