### ISSUE TITLE
[FEATURE] Module Commands

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2914]
A function that you can e.g. bind to .bind l speed mode g. that you just have multiple bindes for modules but with different modes/values.

Eine Funktion, dass du dir z.b binden kannst .bind l speed mode g. dass du halt mehrere bindes hast für module aber mit verschiedene modes/values.

**Comment by ArrowReport** [comment]
I had something like that in Mind for multiple Months, and i think its a good idea

**Comment by SenkJu** [comment]
#1853
