### ISSUE TITLE
[FEATURE] A way to disable the generator checks

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#2915]
**Describe your feature request.**
A way to disable the generator checks.
https://github.com/CCBlueX/FileCloud/blob/master/LiquidBounce/generators.json

**Additional context**
A few vpns and users cant access github so the generator buttons dont load up.

**Comment by SenkJu** [comment]
They should just be disabled by default.

**Comment by SenkJu** [comment]
Now enabled by default.
