### ISSUE TITLE
[Improve] Binds

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2916]
Change/Improve the binds for the numpads, if you want to bind what on numpad 1 you must write .bind module home. and thats weird. Improve it so that you can write numpad1, numpad 2 etc. 
Ps: the Numpads names are right now numpad 1 = end, numpad 2 = down, numpad 3 = next, numpad 4 = left, numpad 5= left, numpad 6 = right, numpad 7 = home, numpad 8=  up, numpad 9 =  prior

Information
 - LB b62
 - Minecraft 1.8.9

**Comment by SenkJu** [comment]
These are the internal names of the keys. We would have to manually remap them to a different name. Just look up the name of each key in the default Minecraft keybinds menu.
