### ISSUE TITLE
NoSlowdown % Options

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#292]
Add NoSlowdown % Options

**Comment by Teals53** [comment]
https://www.youtube.com/watch?v=KRfRzGhp9xY

Look At Right Up NoSlowdown %75 I Think İts Bypass GCheat

**Comment by MaxHD00** [comment]
man soll es aber zu zur jeder sache machen. 
Waterslow   [------[]----]
Sneak          [---[]-------]
SwordBlock [-[]---------]
Soulsand     [-[]---------]
Eat               [--[]--------]

**Comment by Teals53** [comment]
Do you try to write english now I do not understand what you said ?

**Comment by maxhd000000000** [comment]
But you should be able to adjust it to every thing.
[------[]----] Waterslow
[---[]-------] Sneak
[-[]---------] SwordBlock
[-[]---------] Soulsand
[--[]--------] Eat
[--[]--------] Bow

**Comment by Marco-MC** [comment]
@maxhd000000000 Declined
@Teals53 I add it soon. :)

**Comment by MaxHD00** [comment]
ja aber dann nützt es ja garnichts.  Bei gomme kann ich 100 % mit dem schwert geblockt laufen aber essen kann ist nicht mal 1 %

**Comment by Teals53** [comment]
@Teals53 I add it soon. :) SOOOONNN

**Comment by Marco-MC** [comment]
Added.
https://gyazo.com/bbdc1097b44e3eb07c2423d60923cfe5
