### ISSUE TITLE
[FEATURE] Keeprotation for Tower

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2924]
**Describe your feature request.**
Add Keeprotations to the tower ;3

**Comment by icewormy3** [comment]
Yes, and I also suggested this on the forum.
I binder airjump with scaffold and it does work as a tower on cubecraft

**Comment by yorik100** [comment]
+1

**Comment by SenkJu** [comment]
Added
