### ISSUE TITLE
[BUG] cannot login to any server when you first login with mcleaks alt and then with thealtening alt

### ISSUE THREAD

**Issue by Klockowy** [CCBlueX/LiquidBounce1.8-Issues#2926]
**Describe the bug**
When you will login with a mcleaks alt and then with a thealtening alt you can't login into any server.

**To Reproduce**
1. Login into mcleaks alt
2. Join to any server and disconnect
3. Login into thealtening alt
4. Try to join to any server (and you can't join)

**Screenshots**

**Additional information:**
 - OS: Windows 10 Home 1809
 - LiquidBounce Build Version b62
 - Minecraft Version 1.8.9

**Comment by Marco09MC** [comment]
Fixed
