### ISSUE TITLE
[FEATURE] Liquidbounde download

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2928]
**Describe your feature request.**
Add the Download video ( https://www.youtube.com/watch?v=t47_U7f_ccg ) by the Liquidbounde download site.
Maybe there https://axolotl.club/DNG19Ngf.png?key=d6F0DUifYr93kU

**Comment by SenkJu** [comment]
Instructions are on the main site.
