### ISSUE TITLE
[FEATURE] Suchfunktion im Altmanager

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce1.8-Issues#2929]
**Describe your feature request.**
Eine Suchfunktion oder so etwas ähnliches. Zum Beispiel wie bei Dropdown-Menüs auf Webseiten: Wenn man dort das Dropdown-Menü aufklappt und einfach anfängt zu tippen, wird automatisch der Eintrag ausgewählt der mit den getippten Buchstaben anfängt. So was wäre auch gut für den Altmanager, insbesondere wenn man viele Alts hat, ist die Liste ziemlich lang...

**Comment by mrphax0r** [comment]
Gute Idee. Wäre vermutlich nicht allzu schwer, wäre LB OpenSource

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2268
