### ISSUE TITLE
. commands unlimited chat length

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#293]

**Comment by MaxHD00** [comment]
Aber bitte so, dass man immer eine unbegrenzte Chatlänge hat und nicht, dass man erst ein Befehl eingeben muss. Zudem bitte noch. Wenn man über das Maximum schreibt soll die Schrift gelb werden damit man weiss man hat zu lang geschrieben.

**Comment by MCmodding4K** [comment]
GuiChat.class:
this.inputField.setMaxStringLength(256);
->
this.inputField.setMaxStringLength(Integer.MAX_VALUE);

**Comment by Marco-MC** [comment]
Lass das mal offen, sonst vergesse ich das noch. ^^
Außerdem hatte ich das ja schonmal als Modul geaddet, aber wieder entfernt.

**Comment by MaxHD00** [comment]
PLZ no Command

**Comment by Marco-MC** [comment]
@MaxHD00 Kannst du English?
Ich bezweifel es langsam... Auf jedenfall soll sobald man .give eingegeben hat keine chat lenght sein. ^^

**Comment by Marco-MC** [comment]
Added.
