### ISSUE TITLE
[BUG] Discord RPC doesn't work on Linux. (Seems like obfuscation bug)

### ISSUE THREAD

**Issue by Fr3shTea** [CCBlueX/LiquidBounce1.8-Issues#2934]
**Describe the bug**
Discord RPC doesn't work on Linux. LiquidBounce throws exception to game console on launch.

EDIT: Attached logs.

**To Reproduce**
Launch LiquidBounce.

**Additional information:**
 - OS: Linux
 - LiquidBounce Build Version: b62
 - Minecraft Version: 1.8.9

[fml-client-latest.log](https://github.com/CCBlueX/LiquidBounce1.8-Issues/files/3234769/fml-client-latest.log)

**Comment by yKsenomorf** [comment]
That's probably not a bug in LiquidBounce, but rather the Discord RPC library it uses

**Comment by ItzFreshyyy** [comment]
Seems like it's have unresolved dependencies.

**Comment by ItzFreshyyy** [comment]
Seems like it's have unresolved dependencies.

**Comment by Fr3shTea** [comment]
@Marco09MC that might cause some problems in future when using reflection, so bumping this.

**Comment by Fr3shTea** [comment]
LiquidBounce is open-source now. This issue doesn't matter anymore.
