### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gc2023** [CCBlueX/LiquidBounce1.8-Issues#2937]
**Describe the bug**
When i try and use .timer <speed> i tried .timer 1.01 and it does nothing and says Syntax: .timer <speed> in chat
**To Reproduce**
.timer <speed>

**Screenshots**

**Additional information:**
 - OS: [e.g. iOS] Windows 10
 - LiquidBounce Build Version [e.g. b61] Latest b62
 - Minecraft Version [e.g. 1.8.9] 1.8.9

**Comment by scorpion3013** [comment]
its 
timer speed 1.01
