### ISSUE TITLE
[FEATURE] Forum account in client

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#2938]
**Describe your feature request.**
You can login to your CCBlueX forums account with the client.
You will have the donator cape on whatever ign you are on(Since its on the forum account), nobody hacks on their main so this would be a great idea, also you could implement this into liquidchat and have your forum name displayed there, nobody will know your account name and your name will be consistent.

**Additional context**
not much else to say.

**Comment by mrphax0r** [comment]
Would be nice but making it necessary to play would be **_bad_ **

**Comment by SenkJu** [comment]
This could easily be used by plugins to automatically ban players who donated to LiquidBounce.
