### ISSUE TITLE
[FEATURE] GommeHD InvertoryMove Bypass

### ISSUE THREAD

**Issue by DeleteAndInsert** [CCBlueX/LiquidBounce1.8-Issues#2942]

**Comment by mrphax0r** [comment]
AACP should work

**Comment by DeleteAndInsert** [comment]
No, gomme not only uses AACP, they use a self-written plugin called InvFakeArmor.  Just look this https://youtu.be/4UaSrHKSgeQ

**Comment by mrphax0r** [comment]
Is there code available?

**Comment by mrphax0r** [comment]
Of the plugin i mean

**Comment by mrphax0r** [comment]
It would be possible to beautify it

**Comment by DeleteAndInsert** [comment]
No, its gomme self-made plugin

**Comment by mrphax0r** [comment]
Well Crap. The Possibility of a Gomme Dev leaking code, intentional or not, is there though.

**Comment by Marco09MC** [comment]
There is already a inventory move bypass for Gomme: AACAdditionPro
and when you mean the fake item. Just ignore it, just don't click it and everything is fine.
