### ISSUE TITLE
[FEATURE] CubeCraft InvertoryMove bypass

### ISSUE THREAD

**Issue by DeleteAndInsert** [CCBlueX/LiquidBounce1.8-Issues#2943]

**Comment by icewormy3** [comment]
sometimes inventorymove flags so +1

**Comment by Marco09MC** [comment]
InventoryMove works fine on cubecraft?

**Comment by icewormy3** [comment]
@Marco09MC no, moving items while moving will flag and sometimes autoban

**Comment by DeleteAndInsert** [comment]
@Marco09MC Senyinel flags you and closing invertory if you trying to click in invertory while moving.
