### ISSUE TITLE
[FEATURE] Bind "Improve"

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2947]
**Describe your feature request.**
Entweder mal adden, dass man mit Midclick von auf ein module binden kann (wie andere clients es ja haben)  oder Halt wenn man auf das module rechtsklick macht, dass man dort Bind setzen kann

**Additional context**
Könnte einfacher sein wenn mal Probleme auftreten oder so :axodrink:

**Comment by yKsenomorf** [comment]
#2659
