### ISSUE TITLE
[FEATURE] AutoArmor/InvCleaner ResetItemDelay

### ISSUE THREAD

**Issue by DeleteAndInsert** [CCBlueX/LiquidBounce1.8-Issues#2948]
**Describe your feature request.**
I don’t know if it was conceived, or if it’s a bug, but ItemDelay doesn’t reset when the invertory is reopened.  For example: you play QSG, in your invertory there is garbage from which you need to get rid of, you use invcleaner for this, for example, your ItemDelay value is 1100. You open the invertory with garbage, InvCleaner waits for the time specified in ItemDelay, but if you close the invertory before  As IncCleaner finishes work, or close the invertory before the ItemDelay time passes, and reopen the invertory, the ItemDelay will continue to count the time from the time the invertory was closed.  ResetItemDelay reset a time and after re-opening the invertory counts it again. 
Same with AutoArmor ItemDelay.

**Comment by Marco09MC** [comment]
ItemDelay means how long the item is in your inventory.
