### ISSUE TITLE
Replace LiquidChat with axochat

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#2960]
- [x] Basic Web Socket Client
- [x] SSL support
- [x] Mojang Auth
- [x] JWT Auth
- [x] Commands (chat, pchat, chattoken, chatadmin)
- [x] Message support
- [x] Private Message support
- [x] Ban/Unban support

**Comment by Marco09MC** [comment]
https://i.axo.im/Iw0-loli-QpT/c1G7m6Jk.mp4

**Comment by yKsenomorf** [comment]
Would be nicer to see ban reasons and additional time limit

**Comment by icewormy3** [comment]
The bans would be so easy to bypass...

**Comment by Marco09MC** [comment]
Our goal was to provide a more stable and secure chat.

We know that the bans are very easy to bypass. The chat is using the same authentication like normal minecraft server.
So it's possible to login into a new account everytime you get banned.
It's impossible to block all spam attacks but we are going to find ways to prevent spam attacks.

The current LiquidChat v2 server is very broken. The server has no username verification, no spam protection, the ban system don't work etc 
Some people also created their own chat clients to spoof their username etc
The old protocol had a lot of issues.

So the new axochat is a good way for better chat experience. :wink:

**Comment by icewormy3** [comment]
Yea nice to see it being improved
