### ISSUE TITLE
[FEATURE] Randomize Tower/Scaffold Rotation

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#2961]
**Describe your feature request.**
Currently Tower and Scaffd always face the exact same spot. Might be a cause of autobans on certain servers.

**Comment by mrphax0r** [comment]
+1

**Comment by icewormy3** [comment]
YEA FINALLY A ROTATIONS IMPROVMENT

**Comment by icewormy3** [comment]
+1

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2977
