### ISSUE TITLE
[BUG] Minecraft Launcher Login

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2962]
Idk if other people have the problem too, but Liquidbounde think i'm logged in in a cracked acc 
![image](https://user-images.githubusercontent.com/38357837/60650223-01ff8b00-9e44-11e9-92e6-1130d16ec4d6.png) 
![image](https://user-images.githubusercontent.com/38357837/60650236-088e0280-9e44-11e9-9df3-adddbe79ab00.png)

**Comment by Marco09MC** [comment]
Ich konnte den Fehler nicht reproduzieren mit dem neuen Launcher.

**Comment by Marco09MC** [comment]
Ist mir nun auch passiert, scheint aber nicht immer so zu sein.

**Comment by Marco09MC** [comment]
Fixed.
