### ISSUE TITLE
[FEATURE] Replace "E-Mail:Password" field with Clipboard button

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#2965]
![](https://i.axo.im/k1L-loli-xfc/AFw2R3eY.png)

**Comment by Marco09MC** [comment]
https://i.axo.im/ydi-loli-Jfi/Uw4xUoBY.mp4

**Comment by icewormy3** [comment]
You could've left the email:password box
