### ISSUE TITLE
Bypass combat cheats on reflex

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#297]
Could You Do Something Bypass For Reflex ?

Reflex Test Server
test.reflex.rip

Spigot
https://www.spigotmc.org/resources/reflex-%C2%BB-advanced-cheat-prevention-%C2%BB-1-7-1-11.21122/

**Comment by Benjarobbi** [comment]
What isn't bypassed / working correct on Reflex? Can you provide more informations for us? 

_Sincerely
Ben_

**Comment by Teals53** [comment]
What ?

**Comment by Marco-MC** [comment]
Legit:
https://www.youtube.com/watch?v=GQCO8fViZLQ

I think I it could be not easy to bypass reflex because it flags also legits very hard

**Comment by Teals53** [comment]
ı dont look flag message ?﻿

**Comment by Benjarobbi** [comment]
Do you see that the zombie doesn't get damaged whilst hitting him?

Best regards,
Ben.

Am 10.06.2017 5:04 nachm. schrieb "Teals53" <notifications@github.com>:

**Comment by Teals53** [comment]
ah okey ı see thanks

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1364
Added for Reflex dead spoof

**Comment by Marco-MC** [comment]
![2017-10-10_04 10 29](https://user-images.githubusercontent.com/12410754/31366441-2d016b04-ad71-11e7-9f1d-6bde1bce945e.png)

**Comment by Teals53** [comment]
Nice Good Job Thank <3
