### ISSUE TITLE
Rotations Update

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#2977]

**Comment by Marco09MC** [comment]
**Closest point from current rotation (server side) to block**
https://i.axo.im/IUN-loli-xmy/YNYqA3du.mp4

**Comment by Marco09MC** [comment]
**The Bow Aimbot can now also handle not fully loaded bows**
https://i.axo.im/cic-loli-Y18/vA3HPWYL.mp4

**Comment by Teals53** [comment]
finally huge come back from marco <3

**Comment by Marco09MC** [comment]
**Improved killaura rotations**
The KillAura can now find holes in the wall, allowing it to attack the enemy and will select the point that is closest to your last rotation. (like in the block rotations - see fucker example)
RandomCenter and Outborder work flawless with the new rotations. ;)

Example Video on AAC 3.6.4: https://i.axo.im/Aub-loli-30N/uEV3XFv2.mp4

We are going to continue improving our rotations. I won't close the issue until I'm sure that everything works fine and bypass fine on NoCheatPlus, AAC 3.6.4 and Gomme (AAC 3.3.13)

**Comment by je5442804** [comment]
#2922

**Comment by icewormy3** [comment]
Yea Marco ur the best. U should also port b63 to 1.13 lb and maybe 1.12.2 lb

**Comment by Marco09MC** [comment]
**Fixed performance issue**... (found after first release of b63, hotfix released)
https://i.axo.im/f8a-loli-9Z9/QQQruaSB.mp4

**Comment by je5442804** [comment]
Nice!!!
