### ISSUE TITLE
[FEATURE] Infinite CubeCraft fly

### ISSUE THREAD

**Issue by icewormy3** [CCBlueX/LiquidBounce1.8-Issues#2980]
**Describe your feature request.**
https://forum.ccbluex.net/thread.php?id=1505

**Additional context**
Made by Sms_Gamer_3808. He probably already sent you the src code but idk

**Comment by DeleteAndInsert** [comment]
Yay, wait a bit, I recently found out that someone was working out my scripts and src with changes on lb forum, I don’t upload them anywhere else.  I made the fly much faster than this, as soon as I’m at home I’ll post it and a few more flays here.

**Comment by icewormy3** [comment]
@DeleteAndInsert nice! Would like to see

**Comment by Marco09MC** [comment]
We are not going to add new cubecraft flys to the client. It's more useful when people share their scripts in the forum. We can't update the client everyday just because the fly got value patched or something.

**Comment by icewormy3** [comment]
Makes sense

**Comment by DeleteAndInsert** [comment]
Yep
