### ISSUE TITLE
[BUG] Fix Hypixel NPE with AntiForge (again... fucking hypixel)

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#2981]

**Comment by icewormy3** [comment]
Can you just turn off antiforge or is it an instant ban?

**Comment by Marco09MC** [comment]
Sure, you can turn off antiforge. Hypixel can't detect LiquidBounce.

**Comment by icewormy3** [comment]
That's nice to know

**Comment by Teals53** [comment]
.d marco working hard but still lazy for something xd

**Comment by Marco09MC** [comment]
the bug is already fixed

**Comment by Teals53** [comment]
lol sorry :d btw ur sound so cool (from live stream)
