### ISSUE TITLE
[FEATURE] Better Aimbutt/Aura Rotations. (Pitch/Yaw)

### ISSUE THREAD

**Issue by True-cc** [CCBlueX/LiquidBounce1.8-Issues#2985]
**Describe your feature request.**

Make it so that we can change the speed of Pitch and Yaw rotations in AimBot/KillAura. Example down below.

**Additional context**

https://cdn.discordapp.com/attachments/437796580184162306/597096714201202699/unknown.png
(Taken from exception client)

**Comment by True-cc** [comment]
Would be nice. Could bypass Horizon, Matrix, and AAC better.

**Comment by Marco09MC** [comment]
... LiquidBounce already have a TurnSpeed option?

**Comment by True-cc** [comment]
No, not separate ones for Pitch and Yaw. It has one, for both, not separate ones.
