### ISSUE TITLE
[BUG] Sneak Legit mode broken

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#2988]
**Describe the bug**
Sneak mode legit does not sneak serverside and prevents the player from sneaking even if Snek is disabled.

**Comment by Marco09MC** [comment]
![](https://i.axo.im/Jod-loli-7fI/MG9LDcSq.png) -> ![](https://i.axo.im/0wu-loli-a2G/9fXKqN3C.png)
