### ISSUE TITLE
[FEATURE] LiquidWalk NoJump option

### ISSUE THREAD

**Issue by icewormy3** [CCBlueX/LiquidBounce1.8-Issues#2989]
**Describe your feature request.**
Prevents you from jumping when walking on water 

**Additional context**
Prevents flags on NCP and other anticheats. also using aac3.3.11 or dolphin mode while holding the spacebar speeds you up, causing you to get flagged on aac and other anticheats

**Comment by SenkJu** [comment]
Added

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/60832842-957ae800-a1c5-11e9-973a-e456ba23fcb4.png)
u forgot xd

**Comment by icewormy3** [comment]
@SenkJu u forgot to add this to the b63 milestone
