### ISSUE TITLE
Update client to Injection client

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#299]
https://www.youtube.com/watch?v=TucnG2-p4OY

**Comment by Fleroxh** [comment]
Leave a like on the video, or you get striked. <br>
<img src="https://static-cdn.jtvnw.net/emoticons/v1/25/3.0">

**Comment by byCaptain** [comment]
#298 Open

**Comment by Marco-MC** [comment]
@byCaptain Was?

**Comment by Hexeption** [comment]
Hot ❤️

**Comment by Crax9999** [comment]
Wird es optifine geben wenn der client eine Injection bekommt?

**Comment by Marco-MC** [comment]
@Crax9999 Forge Injection = Alles was mit Forge kompatible ist kannst du hinzufügen.

**Comment by byCaptain** [comment]
wie lang noch bin schon hyped

**Comment by byCaptain** [comment]
ddos
