### ISSUE TITLE
[BUG] Killaura autobannt auf AAC 3.6.4 (latest)

### ISSUE THREAD

**Issue by AlienGurke** [CCBlueX/LiquidBounce1.8-Issues#2991]
Habe bereits schon viele Änderungen in den Einstellungen der Killaura vorgenommen, werde aber immer wieder vom AntiCheat geautobannt.
Getest auf: play.jartexnetwork.com
Spielmodus: Skywars und Bedwars (in beiden ist AAC 3.6.4)
Build-Version: b62

Anmerkung: Es ist nicht 1 zu 1 AAC 3.6.4, da sie keine NoSlow, InvCleaner und ChestStealer Checks haben und die Fly Checks von ihrem letzen Anticheat-Update beibehalten haben, deswegen geht dort z.B. Neruxvace Fly mit 2 Ticks , allerdings die Killaura Checks sind die von latest AAC.

**Comment by Marco09MC** [comment]
Die b62 sollte eigentlich auf AAC 3.6.4 problemlos funktionieren mit KillAura, solange man nicht mehrere Gegner mit der Switch Aura angreift (kann zu flags führen). Single Target funktioniert aber völlig flag frei.

Ich werde die KillAura sowieso in diesem Update noch weiter verbessern.
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2977#issuecomment-508962267

Ich denke es sollte kein Problem werden die KillAura auch für Switch Targets flag frei zu kriegen, daher einfach auf die neue Version warten und schauen. ;)

**Comment by AlienGurke** [comment]
Okay, danke für so eine schnelle Antwort.
Hoffe das Update kommt bald, denn auf AAC 3.6.4 geht immer noch Teleport und das mach fun auf jartex. :)
