### ISSUE TITLE
[Website/Improve] Website AD improve

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#2992]
Bei der Liquidbounce.net seite (und maybe auch anderen von dir/euch) Mal ein banner von thealtening  hinzufügen via ein ref link. so Bekommt er mehr käufer und ihr bekommt durch den ref link auch noch ein stück extra geld.  ist mal eine gute idee von mir also mach sie!
![image](https://user-images.githubusercontent.com/38357837/60762309-fb982b80-a05c-11e9-9780-e3ed1188775c.png)

**Comment by Marco09MC** [comment]
![](https://i.axo.im/ia9-loli-GHR/6ywZazga.png)

**Comment by Marco09MC** [comment]
Ist zwar nicht auf der Webseite, aber im Client gibt es ab dem (glaube) dritten Build der b63 einen Buy button.
