### ISSUE TITLE
[BUG] Regen not working

### ISSUE THREAD

**Issue by icewormy3** [CCBlueX/LiquidBounce1.8-Issues#2995]
**Describe the bug**
I lose some health and when i eat food, it doesn't work. Tryed in singleplayer and different settings, still doesn't work

**To Reproduce**
1. Lose some health and hunger
2. Eat something for full hunger

**Screenshots**
No need for fucking screenshots

**Additional information:**
 - OS: [windows 10 pro 1607]
 - LiquidBounce Build Version [b62]
 - Minecraft Version [e.g. 1.8.9] (no shit)

**Comment by SenkJu** [comment]
Cannot reproduce: http://img.liquidbounce.net/uxc/2019-07-08_16-45-07_%25pn.mp4
