### ISSUE TITLE
Devs/scripters if you would be kind enough to steal Sigmas/Exhi module.

### ISSUE THREAD

**Issue by Hackerokuz** [CCBlueX/LiquidBounce1.8-Issues#3002]
**Describe your feature request.**
devs if you would be kind enough to steal Sigmas and Exhibitions modules I'll be really grateful for it.
Riquests:
Batter scaffold
AutoClatch
Infinite Aura
Batter Teleport
Batter TeleportHit
and other modules if possible 😃 
Video:
https://www.youtube.com/watch?v=tWcWA...

Downloads SRC:
Exhi: https://www77.zippyshare.com/v/Qz1SAr...
Sigma: https://www70.zippyshare.com/v/lvvidN...
and maybe add baritone from Impact client...

**Comment by icewormy3** [comment]
They won't add this because they don't skid code

**Comment by Hackerokuz** [comment]
Sorry for broken links
Video:
https://www.youtube.com/watch?v=tWcWAqvOL_g

Downloads SRC:
Exhi: https://www77.zippyshare.com/v/Qz1SArLj/file.html
Sigma: https://www70.zippyshare.com/v/lvvidNfq/file.html

**Comment by Teals53** [comment]
marco never skid any codes
