### ISSUE TITLE
[REQUEST] .prefix command

### ISSUE THREAD

**Issue by akuankka128** [CCBlueX/LiquidBounce1.8-Issues#3009]
It would be cool to change the prefix of the commands to something else, but having the prefix of the prefix command as static, just in case something goes wrong. Also make it editable in the settings/config file just in case something goes very wrong.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RealFantaCoke** [comment]
Just in Case: For what do you need it?

**Comment by akuankka128** [comment]
>Just in Case: For what do you need it?

@RealFantaCoke I feel like it’d be a cool addition to the client, it’s not necessarily needed but I’d like to have it

**Comment by SenkJu** [comment]
Added.
