### ISSUE TITLE
[BUG] game gonna crash when i do alt+tab or etc

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3015]
soo buggy

**Comment by Marco09MC** [comment]
Could you send me a video? I'm not able to reproduce the issue.

**Comment by Teals53** [comment]
i send here little video this night <3

**Comment by RealFantaCoke** [comment]
> Could you send me a video? I'm not able to reproduce the issue.

I also cannot reproduce the error. Everything works just fine for me.

**Comment by SenkJu** [comment]
I cannot reproduce this issue either. Do you still experience it?

**Comment by Teals53** [comment]
nope idk but i just live this issue on first times idk why its little bit lagged rn but gonna crash :)

**Comment by Teals53** [comment]
actualy i still have this problem sometimes

**Comment by RealFantaCoke** [comment]
> actualy i still have this problem sometimes

But that's not our problem. Nobody else than you can re-produce the error so we can't help you.
Maybe you should try to update your drivers (sometimes that could help) - I would recommend **AiO Runtimes**
