### ISSUE TITLE
[BUG] KillAura rotations out of border when player is too fast

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3018]
Disable RandomCenter
Disable Outborder

-> use Speed

**Comment by je5442804** [comment]
Now AAC is build 4.0.5,
Added a new module to the killaura check: modules.direction

**Comment by Marco09MC** [comment]
Fixed.

**Comment by icewormy3** [comment]
yes finally
