### ISSUE TITLE
[BUG] CustomHUD Images don't load after client restart

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3021]
**To Reproduce**
1. Add image
2. Restart client
3. well huh image broke

**Screenshots**
![](https://i.axo.im/P1k-loli-haa/SDdQrvfo.png)
![](https://i.axo.im/2w4-loli-sj2/XKjjrxws.png)

**Comment by Teals53** [comment]
bad example photo xD

**Comment by icewormy3** [comment]
> bad example photo xD

Probably because its Marcos face

**Comment by Teals53** [comment]
no way :d

**Comment by RealFantaCoke** [comment]
> > bad example photo xD
> 
> Probably because its Marcos face

I think it's Marco's mother and he's ashamed of her.

**Comment by yKsenomorf** [comment]
@RealFantaCoke If Marco's mother is a loli, how hes 15 years old? The only way I can think of, is that he's adopted

**Comment by Teals53** [comment]
LOL

**Comment by Marco09MC** [comment]
Fixed.
