### ISSUE TITLE
[BUG] Chat with yourself (LiquidChat website)

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#3024]
**Describe the bug**
You can chat with yourself on the LiquidChat website [Click](https://lc.liquidbounce.net/)

**To Reproduce**
1. Go to 'https://lc.liquidbounce.net/'
2. Login into your Account via JWT-Token
3. Write something in the public chat
4. Click on your name next to your head

**Screenshots**
https://i.imgur.com/qr72m70.png (public chat img)
https://i.imgur.com/53EFwdM.png (dm chat img)

**Additional information:**
 - OS: Windows 10 | 1903
- Microsoft Edge Insider Canary Version 77.0.218.0

**Comment by SenkJu** [comment]
Not a bug. Many chat apps allow this (eg. Signal).

**Comment by RealFantaCoke** [comment]
> Not a bug. Many chat apps allow this (eg. Signal).

But why should you chat with yourself? That's simply stupid.
