### ISSUE TITLE
[FEATURE] AntiFire

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#3026]
**Describe your feature request.**
I died in SG because somebody placed fire under me. That was not cool.
Please add a module to prevent this.

**Additional context**
Maybe add modes (Ex. NCP, AAC, Spartan)

**Comment by je5442804** [comment]
no way..,it is never easy to bypass,are you think bypass any AntiCheat is easy ?

**Comment by CzechHek** [comment]
There is an AntiFire in Zoot but it doesn't bypass on most servers.

**Comment by RealFantaCoke** [comment]
> no way..,it is never easy to bypass,are you think bypass any AntiCheat is easy ?

It is very easy to bypass AntiCheats, i'm also a developer and got a bypass for AAC and Spartan in under 5 minutes. It's quite simple.



> There is an AntiFire in Zoot but it doesn't bypass on most servers.

Oh, LB has Zoot? I never saw anything like that, but i will look for it, thanks.
