### ISSUE TITLE
[FEATURE] AntiPotion

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#3027]
**Describe your feature request.**
Removes bad potion effects when enabled.

**Additional context**
Mode selection (Ex. Keep good effects, Remove all effects)

**Comment by CzechHek** [comment]
Zoot does this

**Comment by je5442804** [comment]
It should be closed

**Comment by coolpvpv** [comment]
> **Describe your feature request.**
> Removes bad potion effects when enabled.
> 
> **Additional context**
> Mode selection (Ex. Keep good effects, Remove all effects)

this is useless legit use zoot this issue should be closed sense its a waste of space
