### ISSUE TITLE
[BUG] MineplexGround speed not working on carpets and halfslabs

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#3030]
**Describe the bug**
When you speed on Mineplex with the MineplexGround speed and walk on carpets or halfslabs while having speed enabled you are getting flagged.

**To Reproduce**
1. Join on Mineplex (us.mineplex.com / eu.mineplex.com)
2. Join a game (like BlockHunt)
3. Wait til the game starts
4. Try to speed on a carpet or on halfslabs with MineplexGround

**Screenshots**
No screenshots taken.

**Additional information:**
 - OS: Windows 10 | 1903
 - LiquidBounce Build Version: b63
 - Minecraft Version: 1.8.9

Maybe try to bypass it or auto-disable speed on carpets or halfslabs / don't allow speeding on carpets and halfslabs.

**Comment by yorik100** [comment]
It's not working on some blocks : stairs, slabs, ice, snow and I may be missing some more

**Comment by RealFantaCoke** [comment]
> It's not working on some blocks : stairs, slabs, ice, snow and I may be missing some more

Yeah, that's exactly what i mean. There must be a bypass to change that.

**Comment by mrphax0r** [comment]
If itf lags, it flags. I don't see your problem

**Comment by RealFantaCoke** [comment]
> If itf lags, it flags. I don't see your problem

nvm, i also didn't asked you for your opinion.

**Comment by yorik100** [comment]
You can't fix that lol, ask Mineplex to fix it, it's their problem

**Comment by RealFantaCoke** [comment]
> You can't fix that lol, ask Mineplex to fix it, it's their problem

You can fix it. I know, that it's fixeable, cuz i am also a developer. If you don't know what u r talking about, then shut your mouth.

**Comment by yorik100** [comment]
> 
> 
> > You can't fix that lol, ask Mineplex to fix it, it's their problem
> 
> You can fix it. I know, that it's fixeable, cuz i am also a developer. If you don't know what u r talking about, then shut your mouth.

Excuse me sir, but I would like to compare my 14 blocks Mineplex longjump and 200% bhop Mineplex speed AND Mineplex highjump with yours? Oh sorry, you don't have one, and unlike me you're not making Mineplex bypasses since a year, saaaad ):
BY THE WAY, it's not fixable SINCE Mineplex checks are different on these blocks, the only way to fix it would be by not speeding on these blocks or speeding differently, if you don't know what you're talking about, then do not you filthy scumbag

**Comment by RealFantaCoke** [comment]
> > > You can't fix that lol, ask Mineplex to fix it, it's their problem
> > 
> > 
> > You can fix it. I know, that it's fixeable, cuz i am also a developer. If you don't know what u r talking about, then shut your mouth.
> 
> Excuse me sir, but I would like to compare my 14 blocks Mineplex longjump and 200% bhop Mineplex speed AND Mineplex highjump with yours? Oh sorry, you don't have one, and unlike me you're not making Mineplex bypasses since a year, saaaad ):
> BY THE WAY, it's not fixable SINCE Mineplex checks are different on these blocks, the only way to fix it would be by not speeding on these blocks or speeding differently, if you don't know what you're talking about, then do not you filthy scumbag

Son of a bitch
