### ISSUE TITLE
[BUG] Mineplex fly doesn't work anymore

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#3031]
**Describe the bug**
The Mineplex fly isn't working anymore. I think they patched it.
I tried it, a friend tried it, we can't get it to work.

**To Reproduce**
1. Join on Mineplex (us.mineplex.com / eu.mineplex.com)
2. Enter a game and wait til it starts
3. Try Mineplex fly

**Screenshots**
No screenshots taken.

**Additional information:**
 - OS: Windows 10 | 1903
 - LiquidBounce Build Version: b63
 - Minecraft Version: 1.8.9

**Comment by icewormy3** [comment]
Ok, this isn't a bug. This fly has been patched for over a year and flys in general don't work on mineplex

**Comment by RealFantaCoke** [comment]
> Ok, this isn't a bug. This fly has been patched for over a year and flys in general don't work on mineplex

If a fly isn't possible anymore then they just need to remove the Mineplex fly.
It is really confusing and i got kicked several times just because i tried the fly.

But the AntiCheat is so bad on Mineplex, i really think that a new fly would be possible.

**Comment by coolpvpv** [comment]
> **Describe the bug**
> The Mineplex fly isn't working anymore. I think they patched it.
> I tried it, a friend tried it, we can't get it to work.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Join on Mineplex (us.mineplex.com / eu.mineplex.com)
> 2. Enter a game and wait til it starts
> 3. Try Mineplex fly
> 
> **Screenshots**
> No screenshots taken.
> 
> **Additional information:**
> 
> * OS: Windows 10 | 1903
> * LiquidBounce Build Version: b63
> * Minecraft Version: 1.8.9

can you close this issue its a waste of space and this fly has been patched for like what 1 or 2 years?

**Comment by RealFantaCoke** [comment]
> > **Describe the bug**
> > The Mineplex fly isn't working anymore. I think they patched it.
> > I tried it, a friend tried it, we can't get it to work.
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Join on Mineplex (us.mineplex.com / eu.mineplex.com)
> > 2. Enter a game and wait til it starts
> > 3. Try Mineplex fly
> > 
> > **Screenshots**
> > No screenshots taken.
> > **Additional information:**
> > 
> > * OS: Windows 10 | 1903
> > * LiquidBounce Build Version: b63
> > * Minecraft Version: 1.8.9
> 
> can you close this issue its a waste of space and this fly has been patched for like what 1 or 2 years?

No, i can't.

If it's not working anymore, @Marco09MC should remove it or find a new bypass.
Currently it's really confusing and not good.

**Comment by coolpvpv** [comment]
> > > **Describe the bug**
> > > The Mineplex fly isn't working anymore. I think they patched it.
> > > I tried it, a friend tried it, we can't get it to work.
> > > **To Reproduce**
> > > Steps to reproduce the behavior:
> > > 
> > > 1. Join on Mineplex (us.mineplex.com / eu.mineplex.com)
> > > 2. Enter a game and wait til it starts
> > > 3. Try Mineplex fly
> > > 
> > > **Screenshots**
> > > No screenshots taken.
> > > **Additional information:**
> > > 
> > > * OS: Windows 10 | 1903
> > > * LiquidBounce Build Version: b63
> > > * Minecraft Version: 1.8.9
> > 
> > 
> > can you close this issue its a waste of space and this fly has been patched for like what 1 or 2 years?
> 
> No, i can't.
> 
> If it's not working anymore, @Marco09MC should remove it or find a new bypass.
> Currently it's really confusing and not good.

you cant fly on mineplex anymore

**Comment by RealFantaCoke** [comment]
> > > > **Describe the bug**
> > > > The Mineplex fly isn't working anymore. I think they patched it.
> > > > I tried it, a friend tried it, we can't get it to work.
> > > > **To Reproduce**
> > > > Steps to reproduce the behavior:
> > > > 
> > > > 1. Join on Mineplex (us.mineplex.com / eu.mineplex.com)
> > > > 2. Enter a game and wait til it starts
> > > > 3. Try Mineplex fly
> > > > 
> > > > **Screenshots**
> > > > No screenshots taken.
> > > > **Additional information:**
> > > > 
> > > > * OS: Windows 10 | 1903
> > > > * LiquidBounce Build Version: b63
> > > > * Minecraft Version: 1.8.9
> > > 
> > > 
> > > can you close this issue its a waste of space and this fly has been patched for like what 1 or 2 years?
> > 
> > 
> > No, i can't.
> > If it's not working anymore, @Marco09MC should remove it or find a new bypass.
> > Currently it's really confusing and not good.
> 
> you cant fly on mineplex anymore

Oh, what you don't say :O

**Comment by scorpion3013** [comment]
Old bypasses will not get removed cause there is a change that they work on other servers.

**Comment by RealFantaCoke** [comment]
> Old bypasses will not get removed cause there is a chance that they work on other servers.

![image](https://user-images.githubusercontent.com/27063009/61295890-50644080-a7d9-11e9-8f4a-db876255c179.png)

**Comment by mrphax0r** [comment]
Scorp is right

**Comment by RealFantaCoke** [comment]
> Scorp is right

stfu

**Comment by Soulplexis** [comment]
they should remove the requirement to hold an empty slot for it.
if it works other places, what the heck are the odds that their anticheat works the same way, and you'd need to hold an empty slot for it to work?

**Comment by RealFantaCoke** [comment]
> they should remove the requirement to hold an empty slot for it.
> if it works other places, what the heck are the odds that their anticheat works the same way, and you'd need to hold an empty slot for it to work?

I think there is a reason for that, otherwise @Marco09MC wouldn't implement such a piece of shit.

**Comment by scorpion3013** [comment]
The fly basicly interacts with the block you are standing on (yes, air too).

**Comment by Soulplexis** [comment]
no i meant because it doesn't bypass mineplex anymore, or at least spoof the slot like mineplexspeed? but that's unnecessary code so just remove the requirement altogether, you dont need interact with the block below you to bypass other servers.

**Comment by Marco09MC** [comment]
no.
