### ISSUE TITLE
[FEATURE] ScriptAPI: Custom FontRenderer support

### ISSUE THREAD

**Issue by skidunion** [CCBlueX/LiquidBounce1.8-Issues#3032]
**Describe your feature request.**
There should be an object, called FontManager
You can use fonts that you've added through CustomHUD
It can contain methods like `getFont(String name)` (should return a Font object, with functions from vanilla FontRenderer, such as `drawString()`, `getStringWidth()`, etc..) or getFonts()

**Comment by kawaiinekololis** [comment]
easily possible after we open sourced liquidbounce
