### ISSUE TITLE
[FEATURE] Change chat commands

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#3033]
Erste Lösung:
Das man die taste von .help zu   sowas wie ,help -help etc. ändern kann.

Zweite Lösung:
Ein Module oder einfach "button" im ESC menü machen um das ausszuschalten mit dem .help .killaura etc.

Grund:
Wenn Leute Legit cheaten und welche im chat schreiben "write .legit in the chat"   Was sie ja nicht können wirkt es blöd für die.

**Comment by RealFantaCoke** [comment]
> Erste Lösung:
> Das man die taste von .help zu sowas wie ,help -help etc. ändern kann.
> 
> Zweite Lösung:
> Ein Module oder einfach "button" im ESC menü machen um das ausszuschalten mit dem .help .killaura etc.
> 
> Grund:
> Wenn Leute Legit cheaten und welche im chat schreiben "write .legit in the chat" Was sie ja nicht können wirkt es blöd für die.

Ziemlich unnötig ... wie wär's einfach mal den extra dafür entwickelten Befehl _.say <Text>_ zu nutzen?
Damit kann man schließlich auch Texte senden, die mit einem Punkt anfangen wie bspw.: **.help**.

Und wozu sollte man bitte die Befehle in einem Client, der extra dafür entwickelt wurde, ausschalten?

**Comment by barbiehunter** [comment]
> > Erste Lösung:
> > Das man die taste von .help zu sowas wie ,help -help etc. ändern kann.
> > Zweite Lösung:
> > Ein Module oder einfach "button" im ESC menü machen um das ausszuschalten mit dem .help .killaura etc.
> > Grund:
> > Wenn Leute Legit cheaten und welche im chat schreiben "write .legit in the chat" Was sie ja nicht können wirkt es blöd für die.
> 
> Ziemlich unnötig ... wie wär's einfach mal den extra dafür entwickelten Befehl _.say _ zu nutzen?
> Damit kann man schließlich auch Texte senden, die mit einem Punkt anfangen wie bspw.: **.help**.
> 
> Und wozu sollte man bitte die Befehle in einem Client, der extra dafür entwickelt wurde, ausschalten?

Hab die issue nur gemacht, da jemand damit zu mir kam und habe aus "höfflichkeit" einfach es mal hier rein gemacht.  Aber jo .say kann man natürlich auch benutzen, Sorry.
