### ISSUE TITLE
[FEATURE] Killaura disable when killed

### ISSUE THREAD

**Issue by Mspy1** [CCBlueX/LiquidBounce1.8-Issues#3034]
**Describe your feature request.**
An option to disable KillAura when killed.

**Additional context**
I can't give a specific server that bans you after dying with killaura enabled, but yet still i think that is required.

**Comment by RealFantaCoke** [comment]
Yeah, good idea! Maybe @Marco09MC could also add a button in every GuiScreen to disable Aura.
When i play a game on a server and then go to the lobby i often forget to disable Aura and it's so irritating.

**Comment by CzechHek** [comment]
You can make that in ScriptAPI.

**Comment by Mspy1** [comment]
Well, i know it is doable but like i have no knowledge of ScriptAPI commands so.

**Comment by Soulplexis** [comment]
AAC will detect you if you hit while dead, ncp prevents it so maybe they should have something in it like "Deathcheck" which is on by default preventing you from attacking when dead

**Comment by Mspy1** [comment]
Yes, i witnessed that in poke.sexy anticheat test server.

**Comment by SenkJu** [comment]
Just use this script. It will automatically disable KillAura after dying.

```js
var scriptName = "KillAuraDisabler";
var scriptAuthor = "Senk Ju";
var scriptVersion = 1.0;

function KillAuraDisabler() {

    this.killAuraModule = moduleManager.getModule("KillAura");

    this.getName = function () {
        return "KillAuraDisabler";
    }

    this.getCategory = function () {
        return "Misc";
    }

    this.getDescription = function () {
        return "Automatically disables KillAura after dying.";
    }

    this.onEnable = function () {
        if (!this.killAuraModule.getState()) {
            this.killAuraModule.setState(true);
        }
    }

    this.onUpdate = function () {
        if (mc.thePlayer.isDead || mc.thePlayer.getHealth() <= 0) {
            this.killAuraModule.setState(false);
        }
    }
}

var KillAuraDisabler = new KillAuraDisabler();
var KillAuraDisablerClient;

function onEnable() {
    KillAuraDisablerClient = moduleManager.registerModule(KillAuraDisabler);
}

function onDisable() {
    moduleManager.unregisterModule(KillAuraDisablerClient);
}
```
