### ISSUE TITLE
Panic command

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#304]

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/203

On/Off Client Keybind

**Comment by MaxHD00** [comment]
ich würde es besser finden wenn man es mit .panic machen könnte.

**Comment by Teals53** [comment]
LiquidBounce Dont Have .panic Command

**Comment by Marco-MC** [comment]
Added.
