### ISSUE TITLE
[BUG] NoSlow and FastUse not working on Milk Bucket

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3043]
**Describe the bug**
NoSlow will not prevent slowdown while using Milk Buckets 

**To Reproduce**
1. Go to any world
2. Turn on NoSlow with any mode
3. Get a milk bucket
4. Try to drink it and move. your movement won't be affected by noslow

**Screenshots**
not applicable

**Additional information:**
 - OS: windows 10
 - LiquidBounce Build 62, 63
 - Minecraft 1.8.9 with Optifine

**Comment by Marco09MC** [comment]
Fixed.
