### ISSUE TITLE
[BUG] KillAura aiming but not hitting.

### ISSUE THREAD

**Issue by freaky767** [CCBlueX/LiquidBounce1.8-Issues#3047]
**Describe the bug**
While on server with no anticheat (even singleplayer) if you are speeding/bhopping and auraing around your opponent, then you press f5, you will see that your head is aiming at player, but it isnt attacking him as normal. it still IS attacking, but at a very low APS.

**To Reproduce**
1. Go to any server or singleplayer server with no anticheat
2. Turn on headrotations module, speed and killaura
3. try to attack an entity in f5, you'll see that your head is aiming to entity, but somehow even in set range it isnt attacking it as often as it should.

**video**
https://youtu.be/St9JiYcs2iQ

**Additional information:**
 - OS: Windows 8
 - LiquidBounce Build Version: b63
 - Minecraft Version 1.8.9 forge, am running a few mods such as mousedelayfix, but doubt that they should cause a problem.

**Comment by DeleteAndInsert** [comment]
#3018

**Comment by freaky767** [comment]
okay, gonna close this den
