### ISSUE TITLE
[FEATURE] more cps for removed hit delay servers

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3050]
or a option for ms or durability attack idk

maybe about that

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/129#issuecomment-513484673

**Comment by Teals53** [comment]
bcs i cant kill anybody on mc.kingnw.com 

this players hitting so interesting. players hands attack super fast

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3022

**Comment by Teals53** [comment]
i not tallk about that :d

**Comment by Marco09MC** [comment]
I know what you mean, but it will solve the problem and allow to attack with more than 20cps.
(when using the command)

**Comment by Teals53** [comment]
actually idk its fixed just with cpm i just want kill this niggers on kingnw xd
