### ISSUE TITLE
[BUG] Duplicated Commands

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3052]
![image](https://user-images.githubusercontent.com/13446881/61753165-04a42f00-adb7-11e9-82c7-459f7ddb1423.png)

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/61753187-1980c280-adb7-11e9-9d37-6ed29fcc75fc.png)

**Comment by icewormy3** [comment]
They are already gona fix it in b64

**Comment by Teals53** [comment]
oh
