### ISSUE TITLE
[BUG] InventoryCleaner should not swap item when it's already the best

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3056]
why put the same sword in my inventory back in my hotbar when I already have the same sword in my hotbar ?

**Comment by thegamerx1** [comment]
Also if you have it to do in random mode the first thing it will throw is your hotbar and if you have the no move option you don't have sword

**Comment by Marco09MC** [comment]
I'll do it later, sorry.

**Comment by Teals53** [comment]
.d

**Comment by Teals53** [comment]
<3
