### ISSUE TITLE
[FEATURE] Scaffold Down option ( Downwards )

### ISSUE THREAD

**Issue by DeleteAndInsert** [CCBlueX/LiquidBounce1.8-Issues#3063]
Scaffold abbility put the blocks down when holding Sneak button.

**Comment by je5442804** [comment]
yeah It seem that possible in hypixel,may it have Interact flag.
The Jello Client have done It 
https://www.youtube.com/watch?v=v2NRiVco4Vg&app=desktop

**Comment by kawaiinekololis** [comment]
In pull request: https://github.com/CCBlueX/LiquidBounce/pull/81

**Comment by superblaubeere27** [comment]
Isn't merged yet :o
