### ISSUE TITLE
[BUG] HUD is disabled by default

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#3064]
When starting liquidbounce for the first time, HUD is disabled but it should be enabled

**Comment by SenkJu** [comment]
<img src="https://axolotl.vip/AmoBC343.png?key=N5WqJNo8hL1Dsv">

**Comment by icewormy3** [comment]
Lol no wonder why so many people say that the hud is off in the discord

**Comment by mrphax0r** [comment]
In b63 you mean? In b62 it worked.

**Comment by SenkJu** [comment]
Fixed.
