### ISSUE TITLE
[BUG] When dimiss Update, it shows new Main Menu, even when selected the legacy one

### ISSUE THREAD

**Issue by ClientvsAnticheat** [CCBlueX/LiquidBounce1.8-Issues#3066]
**Describe the bug**
When start LiquidBounce on an older Version and you dismiss the Update Message it will show the new Main Menu even when you have selected the old one

**To Reproduce**
1. Go to 'Start Launcher'
2. Click on 'Spielen: Forge: 1.8.9'
3. Scroll down to 'OK'
4. Click on 'OK'
5. See error

**Screenshots**

**Additional information:**
 - OS: [Windows]
 - LiquidBounce Build Version [b62]
(Happened in any Version from b49 to b62)
I can't test with b63 bc b64 isn't released yet.
 - Minecraft Version [1.8.9]

**Comment by SenkJu** [comment]
Also happens after getting banned or kicked from a server.

**Comment by SenkJu** [comment]
Now using #3083 anyway.
