### ISSUE TITLE
[BUG] AntiForge not working on play.craftrise.tc

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3067]
**To Reproduce**
1. Enable AntiForge
2. Join `play.craftrise.tc`

**Screenshots**
![](https://i.axo.im/tlp-loli-Dqg/BSFa3vBa.png)

**Additional information:**
 - OS: Windows
 - LiquidBounce Build Version b63
 - Minecraft Version 1.8.9

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3012 ?

**Comment by Mspy1** [comment]
Yea duplicate thread, he mustn't have seen the #3012 thread.

**Comment by Teals53** [comment]
:D

**Comment by Teals53** [comment]
damn duplicated one is your issues marco, not my one ? @Marco09MC
