### ISSUE TITLE
OverArmor

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#307]
Funktioniert nur in Creative:
Du kannst alle Items/Blöcke in den Rüstungsslot legen. 
Wenn du 4 mal eine Diamantbrustplatte in alle Rüstungsslots reinlegst erhöht sich der Rüstungswert enorm.

**Comment by superblaubeere27** [comment]
Dafür gibts MoreCarry

**Comment by Tcm9** [comment]
nope, MoreCarry erweitert nur das interne Crafting. Aber in die Rüstungsslots kann man nichts legen.
