### ISSUE TITLE
[BUG] InventoryCleaner randomly causes massive lags

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3071]
**Describe the bug**
InventoryCleaner with RandomSlot true randomly causes massive lags.

**To Reproduce**
1. Use InventoryCleaner to throw items out of your inventory (MaxMinDelay: 67, InvOpen, Sort, everything else false)
2. Experience random massive lag spikes

**Log**
[https://pastebin.com/raw/jnBGKdiW](url)

**Additional information:**
 - OS: Win10 64x
 - LiquidBounce Build Version [b63 and lower]
 - Minecraft Version [1.8.9]

**Comment by CzechHek** [comment]
Restarting LB fixed it

**Comment by CzechHek** [comment]
It appears every time now, also happens when you have 3 swords and sorting to 1. slot = sword

**Comment by Marco09MC** [comment]
I'm not able to reproduce this bug and the exception is very weird because there is no class with this name:
"net.ccbluex.liquidbounce.C9f527ca0.l1111lll.l"

**Comment by Marco09MC** [comment]
after some testing I was able to reproduce the bug... I'm going to fix it.

**Comment by Marco09MC** [comment]
Fixed
