### ISSUE TITLE
[FEATURE]custom clickgui fonts and designer

### ISSUE THREAD

**Issue by icewormy3** [CCBlueX/LiquidBounce1.8-Issues#3072]
**Describe your feature request.**
Like with the CustomHUD designer, add support for custom fonts and if possible, add a custom clickgui designer

**Additional context**

**Comment by Shiv3RPolak** [comment]
+++

**Comment by mrphax0r** [comment]
You can replace the .ttf, but multiple font support would be nice

**Comment by SenkJu** [comment]
Not possible with our current ClickGUI system.
