### ISSUE TITLE
[BUG] Velocity not working on Hypixel (and maybe some other servers)

### ISSUE THREAD

**Issue by mariolatiffathy** [CCBlueX/LiquidBounce1.8-Issues#3078]
**Describe the bug**
Whenever I use velocity on Hypixel, it either uses 0% velocity or 100% velocity which immediately bans the player (me or any other one), it doesn't use the velocity rate that I choose.

**To Reproduce**
1. Go to mc.hypixel.net
2. Go to any game (don't try that in the lobby)
3. Try to set velocity to any number.
4. You will either get banned or the velocity won't be functional at all.

**Screenshots**
Unfortunately, no screenshots.

**Additional information:**
 - OS: [e.g. iOS]: Windows 7 64-bits
 - LiquidBounce Build Version [e.g. b61]: b63
 - Minecraft Version [e.g. 1.8.9]: 1.8.9

**Comment by mrphax0r** [comment]
Mine works perfectly fine on b62.

**Comment by Mspy1** [comment]
> Mine works perfectly fine on b62.

So, you set custom rates for simple mode for instance; %90 horizontal and it worked? 
You must be wrong i tested it just now?
https://youtu.be/xfhz_2h-w1w

**Comment by mariolatiffathy** [comment]
> Mine works perfectly fine on b62.

Same issue for me on b62

**Comment by Mspy1** [comment]
@Marco09MC  Could you take a look at this?

**Comment by CzechHek** [comment]
Already fixed, close this.
