### ISSUE TITLE
DamageIndicator

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#308]
Wenn du ein Spieler anschaust erscheint Obenlinks eine Anzeige die:

- Die dir Anzeigt wieviel leben der andere Spieler hat.

- welche Effekte der Spieler hat.

- Wieviel Blöcke der Spieler von dir entfernt ist. 

- Ein Bild vom Spieler (Model)

Es soll 3 Designs geben.

**Comment by Marco-MC** [comment]
Sicherlich nicht.
Außerdem wird LiquidBounce demnächst zur Minecraft Mod und dann kannst du dir auch einfach dmg indicator reinhauen.
