### ISSUE TITLE
[FEATURE] Main Menu "Customize"

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#3082]
1.  Die verschiedene "Backgrounds" wie der neue der in b64 Kommt, den man aber bei "Change Wallpaper" Ändern kann zu den alten oder halt auch Ganz alten.
2. Was (Manchen) Leuten gefallen Könnte wäre auch bei "Change Wallpaper" auch  Zwischen den Zwei designs Wechseln kann. Also das Jetzige und das alte wie in 1.11.2 Fallst das Leuten mehr gefällt.
3. "Change Wallpaper" zu   Change GUI, Change HUD oder ähnliches Ändern.

**Comment by SenkJu** [comment]
#3110
