### ISSUE TITLE
[FEATURE] New Main Menu

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#3083]
**Describe your feature request.**
Now using old main menu as its base again but with a new shader background and other small visual tweaks.
<img src="https://axolotl.us/VnzMUnrf.png?key=lckHu6lmticgOK">

<a href="https://youtu.be/r4Ck1iD4xSI">Video</a>

**Comment by Teals53** [comment]
lol why ?

**Comment by icewormy3** [comment]
> lol why ?

Because senk ju hates the current main menu https://forum.ccbluex.net/thread.php?id=624

**Comment by Mspy1** [comment]
> lol why ?

sum ppl love plain designed GUI's chill lol.
