### ISSUE TITLE
[FEATURE] Some configurations

### ISSUE THREAD

**Issue by mariolatiffathy** [CCBlueX/LiquidBounce1.8-Issues#3085]
**Describe your feature request.**
LiquidBounce must contain an option to disable:
- The moving sparkles on the LiquidBounce start screen
- The Discord rich presence

**Additional context**
None.

**Comment by Teals53** [comment]
Lb already have "Discord rich presence" .d

**Comment by mariolatiffathy** [comment]
> Lb already have "Discord rich presence" .d

Please read the issue well.

**Comment by Teals53** [comment]
ups sorry

**Comment by SenkJu** [comment]
#3110
#2177
