### ISSUE TITLE
[FEATURE] ChestAura Multiple Chests

### ISSUE THREAD

**Issue by thegamerx1** [CCBlueX/LiquidBounce1.8-Issues#3086]
**Describe your feature request.**
Allow to open normals chests and enderchests at the same time

**Comment by Teals53** [comment]
how its possible at the same time ?

**Comment by Mspy1** [comment]
@SenkJu  Want to clean useless feature requests like this sometime?

**Comment by thegamerx1** [comment]
what's useless in here?

**Comment by Mspy1** [comment]
why would one want to open chests at the same time?

**Comment by thegamerx1** [comment]
because most hunger game servers use both type of chests and the actual version only allows to open 1 at the same time?

**Comment by yorik100** [comment]
+1

**Comment by scorpion3013** [comment]
#3057

**Comment by Teals53** [comment]
lol he talking about that ? damn

**Comment by thegamerx1** [comment]
@teals53 sry for my bad England

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3057

**Comment by xHackerBey** [comment]
So usable in HiveMC. HiveMC's SurvivalGames using heads instead of chests.
