### ISSUE TITLE
AntiKnockback 

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#309]
Es soll die Einstellung Knockback+ geben. Bzw. man soll einstellen können das horizonal und vertikal mehr als 1.0 geht. (es soll bis 4.0 gehen)

**Comment by MaxHD00** [comment]
Zudem soll es eine Back Einstellung geben. (Jeden Knockback den man bekommt soll nach hinten gehen. Also wenn du von der Seite geschlagen wirst tut [Back] so als würdest du von vorne geschlagen werden. also geht der Knockback nach hinten )

**Comment by Marco-MC** [comment]
Knockback+:
.velocity horizontal 4.0
.velocity vertical 4.0
Knockback-:
.velocity horizontal -4.0
.velocity vertical -4.0
