### ISSUE TITLE
[BUG] Writing mistake

### ISSUE THREAD

**Issue by ventOwO** [CCBlueX/LiquidBounce1.8-Issues#3090]
Replace "was" with "were"
![image](https://user-images.githubusercontent.com/43090398/63211417-f5cf4480-c0f6-11e9-8737-9700759e0ef9.png)

**Comment by Mspy1** [comment]
This is not a mistake lol :d? Did you learn english from school or smth?

**Comment by SenkJu** [comment]
Fixed.

**Comment by ventOwO** [comment]
> This is not a mistake lol :d? Did you learn english from school or smth?

yes, unlike you
