### ISSUE TITLE
[FEATURE]LiquidWalk NoJump

### ISSUE THREAD

**Issue by DeleteAndInsert** [CCBlueX/LiquidBounce1.8-Issues#3093]
Make NoJump option no forbids you to jump when you are on 
+ lilypad
+ half blocks when there is water under them

**Comment by icewormy3** [comment]
It is already in liquidbounce https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2989

**Comment by DeleteAndInsert** [comment]
@icewormy3 my mistake, you misunderstood me, sry

**Comment by yorik100** [comment]
It doesn't jump when you're ona lilypad

**Comment by DeleteAndInsert** [comment]
@yorik100 uh? yes.  And my issue was created in order to fix it.  Please read the description, ok?

**Comment by mrphax0r** [comment]
@yorik100 misread @DeleteAndInsert 's description. " No forbids" is not really clear. He wants to have an option to allow jumping on Lilypads.

**Comment by yorik100** [comment]
That's why I said that

**Comment by DeleteAndInsert** [comment]
+ also half blocks when there is water under them

**Comment by coolpvpv1** [comment]
> Make NoJump option no forbids you to jump when you are on
> 
> * lilypad
> * half blocks when there is water under them

change this to a bug cause it should allow you to jump on it if you made this a feature request its just stupid cause this is a bug
