### ISSUE TITLE
[Website/Client] thealtening "Support"

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#3098]
A: Add a Banner to the Liquidbounce.net website with the thealtening Banner

B: Add a buy button to the thealterning part by the Altmanger (https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2992#issuecomment-511126347 )

PS: Both with ccbluex ref link (or Liquidbounce idk)

**Comment by Marco09MC** [comment]
A: Later.
B: ... already added.
