### ISSUE TITLE
[BUG] New Background Wallpaper SOOO LAGGY AND HEAVY

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3108]
its fuck my pc pls delete that or add a option for change this shit its so laggy

![image](https://user-images.githubusercontent.com/13446881/64074897-fc92b580-ccb9-11e9-8c4a-7717e1cbced4.png)

**Comment by Marco09MC** [comment]
There is already a option to change the wallpaper. Use "Change Wallpaper".

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3110

We are going to find a new wallpaper and we are going to add more customizability for wallpapers.

**Comment by Marco09MC** [comment]
oh and it would be nice when you could tell me what's the specs of your computer.

**Comment by Teals53** [comment]
İ7-3770k
16 Gb DDR3 Ram
Nvidia GT730 2 Gb (Fermi)

@Marco09MC

**Comment by Teals53** [comment]
Btw i forgot change wallpaper settings sorry xd but i think its would be nice if default wallpaper want less pc specs
