### ISSUE TITLE
HUD einstellungen.

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#311]
Füge bitte 3 Einstellungen zu HUD hinzu:

- Koordinaten

- Ping

- Textradar (der Nächste Spieler wird in Blöcken und Leben unten angezeigt)(also so:  [MaxHD(20)(50)] )
                                             (die 20 sind die Herzen und die sollen dunkelrot sein)
                                             ( die 50 ist der Abstand zum Spieler. Die 50 und der Name ist hellgrau)
                                             (  Bei Langen Namen ( 18 zeichen) wird es zu 12 zeichen also so:
                                                [Dersuperprof...(20)(50)] 
                               Orginal: [Dersuperprofispieler008(20)(50)]

**Comment by Marco-MC** [comment]
Nein.

**Comment by MaxHD00** [comment]
ok? why?

**Comment by Marco-MC** [comment]
Weil ich das nicht möchte?
