### ISSUE TITLE
[FEATURE] Tracers color based on enemy distance

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3114]
**Describe your feature request.**
-If a player is far away, then the line should be green at the tracer. When the player gets closer, the line should turn softly yellow. If the player is very close, then the line should turn softly red so that you know how close the player is. At the moment the line is only white.

-The thickness of the tracer line should be adjustable.

**Additional context**
https://www.bilder-upload.eu/bild-5ef5ba-1567351688.png.html

**Comment by Soulplexis** [comment]
or if a player is far away the tracer becomes more transparent. and maybe something like vape has if the player looks at you the tracer gets bold/thicker

**Comment by Tcm9** [comment]
too complicated. It is enough if the colour changes with the closeness.

**Comment by Tcm9** [comment]
Please add a setting that the tracer knit does not go to the legs, and then to the head. Sonndern that the stroke goes directly to the upper body. That looks nicer. 
![tracer](https://user-images.githubusercontent.com/31276706/65835145-e55bdd80-e2e2-11e9-9d9b-4c989c2b3d23.PNG)

**Comment by Marco09MC** [comment]
Done.
