### ISSUE TITLE
[BUG] .reload and .scripts reload sometimes kicks you for java.util.concurrentModificationException..

### ISSUE THREAD

**Issue by True-cc** [CCBlueX/LiquidBounce1.8-Issues#3115]
**Describe the bug**
Sometimes when I want to reload so I can reload one of my scripts, it kicks me from the server for java.util.concurrentModificationException but not all the time. Only sometimes it does. I can't find a pattern.

**To Reproduce**
1. Do .reload or .scripts reload I guess?

**Screenshots**

**Additional information:**
 - OS: Windows 10
 - LiquidBounce b64
 - Minecraft Version 1.8.9

**Comment by DeleteAndInsert** [comment]
+1

**Comment by CzechHek** [comment]
If you try to enable module that does commandManager.executeCommand(".scripts reload") it crashes or freezes the game now.
https://pastebin.com/raw/fR9eFLSV
- happens in b64 only

Concurrent modification exception happens since b63

**Comment by SenkJu** [comment]
Could you show me a script which causes this problem?

**Comment by True-cc** [comment]
Sometimes when I do .scripts reload, it crashes or freezes the game in singleplayer and disconnects you in multiplayer. I notice it does it more often when there was a change to a script.

**Comment by CzechHek** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/68
https://github.com/CCBlueX/LiquidBounce/pull/69
