### ISSUE TITLE
[FEATURE] Fastcraft Liquidbounce

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3116]
**Describe your feature request.**
i have a not so powerful computer, so forge with liquidbounce doesn't work so well for me (normally about 30- 45 FPS/ hivemc co about 15 Fps), but when i add the mod fastcraft, everything runs quite smoothly. However, there is no fastcraft for version 1.8. could you add a setting that mimics fastcraft?

**Additional context**
maybe it will help you if I give you the config of fastcraft.

[fastcraft.txt](https://github.com/CCBlueX/LiquidBounce1.8-Issues/files/3563664/fastcraft.txt)

**Comment by SenkJu** [comment]
Just use Optifine instead. It is compatible with Forge 1.8.9.
