### ISSUE TITLE
AbortBreaking

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#312]
Du kannst beim abbauen aufhören und wieder anfangen,ohne dass der Abbau-Fortschritt verloren geht.

**Comment by Benjarobbi** [comment]
Danke für deine Idee, jedoch möchten wir dies z.Z nicht hinzufügen.
_Grüße,
Ben._

**Comment by Marco-MC** [comment]
Vielleicht bau ich das ein, irgendwann... Derzeit haben wir aber echt andere Probleme...

**Comment by MaxHD00** [comment]
Ich weiss schon das ihr derzeit was anderes macht. Aber wenn ihr Zeit habt, habt ihr die ideen ^^

**Comment by Marco-MC** [comment]
Added.
