### ISSUE TITLE
[FEATURE] Arraylist should only show important hacks (setting in HUD)

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3120]
**Describe your feature request.**
Arraylist should only show important hacks (setting in HUD).
You should also be able to use ".importentArraylist speed false" to set which hacks are "important" for you and which are not, because if you have a lot of hacks on it, half of the screen will be filled with the Arraylist.

**Comment by Soulplexis** [comment]
I was gonna suggest this but little diffferently:

Arraylist will only show hacks which are bound to a key

**Comment by Tcm9** [comment]
you can set it that way. Just set killaura, speed... (hacks you can also have as keybind) to important and then you have only the ones you have as keybind.

**Comment by SenkJu** [comment]
That's not the purpose of an array list.
