### ISSUE TITLE
[BUG] Visual Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3128]
if open tower "LiquidBounce" gonna invisible

![image](https://user-images.githubusercontent.com/13446881/64388298-55aa7280-d047-11e9-8685-39321730d670.png)

![image](https://user-images.githubusercontent.com/13446881/64388308-5e9b4400-d047-11e9-80e7-1b6203b74533.png)

**Comment by coolpvpv1** [comment]
> if open tower "LiquidBounce" gonna invisible
> 
> ![image](https://user-images.githubusercontent.com/13446881/64388298-55aa7280-d047-11e9-8685-39321730d670.png)
> 
> ![image](https://user-images.githubusercontent.com/13446881/64388308-5e9b4400-d047-11e9-80e7-1b6203b74533.png)

what??

**Comment by Teals53** [comment]
Look at left up logo

**Comment by coolpvpv1** [comment]
> Look at left up logo

just a bug for you cause i turned on tower and the logos still there for me so idk why yours is bugged

**Comment by Teals53** [comment]
lol

**Comment by SenkJu** [comment]
You probably just accidentally removed the element in CustomHUD.

**Comment by Teals53** [comment]
No lol @SenkJu I'm not that retarded
