### ISSUE TITLE
mehr Nuker Modi

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#313]
- Creative (funktioniert nur in creative. )

- Click    (funktioniert nur in creative. Drücke die Linke Maustaste damit er alle Blöcke um dich herum entfernt )

- ID  (funktioniert nur in creative. Du baust nur eine Blocksorte ab. (kannst du mit .nukerid <blockid> ändern)

Survival ist es automatisch in /gamemode 0 (bzw die oberen Einstellungen werden ausserkraft gesetzt im Survivalmode)

**Comment by Marco-MC** [comment]
Für Griefing benutzt SkillClient.

**Comment by SenkJu** [comment]
ID Nuker = Fucker

.fucker select <block

**Comment by Marco-MC** [comment]
yeeee
