### ISSUE TITLE
[BUG] ScriptAPI module values and keybinds reset after using .reload

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#3136]
**Describe the bug**
After reloading the client keybinds and values of script modules are back to default. Scripts have to be reloaded before configs are re-applyed.

**Comment by SenkJu** [comment]
Fixed.

**Comment by CzechHek** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/69
