### ISSUE TITLE
[FEATURE] Tower Stop

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3137]
**Describe your feature request.**
You can tower while moving(horizontally) and it flags sometimes, a feature to stop your movement/motion when towering would be nice

**Comment by Tcm9** [comment]
If you do, then you need a "TowerifSpace" setting. whenever you press the spacebar, it towers.

**Comment by Tcm9** [comment]
because otherwise you can just bind Tower.

**Comment by coolpvpv1** [comment]
> **Describe your feature request.**
> You can tower while moving(horizontally) and it flags sometimes, a feature to stop your movement/motion when towering would be nice

legit just bind tower this isn't a issue lmao

**Comment by Soulplexis** [comment]
> > **Describe your feature request.**
> > You can tower while moving(horizontally) and it flags sometimes, a feature to stop your movement/motion when towering would be nice
> 
> legit just bind tower this isn't a issue lmao remove this issue its just stupid

I did bind tower. you dont understand what im talking about

**Comment by True-cc** [comment]
> > > **Describe your feature request.**
> > > You can tower while moving(horizontally) and it flags sometimes, a feature to stop your movement/motion when towering would be nice
> > 
> > 
> > legit just bind tower this isn't a issue lmao remove this issue its just stupid
> 
> I did bind tower. you dont understand what im talking about

I really don't.

**Comment by Soulplexis** [comment]
> > > > **Describe your feature request.**
> > > > You can tower while moving(horizontally) and it flags sometimes, a feature to stop your movement/motion when towering would be nice
> > > 
> > > 
> > > legit just bind tower this isn't a issue lmao remove this issue its just stupid
> > 
> > 
> > I did bind tower. you dont understand what im talking about
> 
> I really don't.

if tower is on (regardless of onJump or bind) you're able to press WASD to move around but it will still continue towering, and with constantmotion mode it will sort-of glide if you even tap the keys. the option here would stop your horizontal movements when towering so you dont flag.

**Comment by superblaubeere27** [comment]
Just disable Tower
