### ISSUE TITLE
[FEATURE] Better clickgui, remove ncpfhop

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3139]
**Describe your feature request.**

**ClickGUI double click values**
it would be nice if you could double-click on a value in the menu and quickly change values. 
For example here it would let me double click on the red 100 and I could type what I wanted it set to. same with text
![image](https://user-images.githubusercontent.com/43506202/64567339-482a0c80-d315-11e9-8e23-935a7291a0ba.png)
**NCPFHop doesnt bypass please remove it**
it doesn't work... flags.

**Comment by coolpvpv1** [comment]
> **Describe your feature request.**
> 
> **ClickGUI double click values**
> it would be nice if you could double-click on a value in the menu and quickly change values.
> For example here it would let me double click on the red 100 and I could type what I wanted it set to. same with text
> ![image](https://user-images.githubusercontent.com/43506202/64567339-482a0c80-d315-11e9-8e23-935a7291a0ba.png)
> **NCPFHop doesnt bypass please remove it**
> it doesn't work... flags.

the better clickgui i agree with but the removing ncpfhop is stupid cause it might bypass on other servers and i dont see a reason to remove it just cause it flags its called ncpFLAGhop for a reason genius

**Comment by Soulplexis** [comment]
> > **Describe your feature request.**
> > **ClickGUI double click values**
> > it would be nice if you could double-click on a value in the menu and quickly change values.
> > For example here it would let me double click on the red 100 and I could type what I wanted it set to. same with text
> > ![image](https://user-images.githubusercontent.com/43506202/64567339-482a0c80-d315-11e9-8e23-935a7291a0ba.png)
> > **NCPFHop doesnt bypass please remove it**
> > it doesn't work... flags.
> 
> the better clickgui i agree with but the removing ncpfhop is stupid cause it might bypass on other servers and i dont see a reason to remove it just cause it flags its called ncpFLAGhop for a reason genius

'genius' wtf?? anyway, the F doesn't stand for 'Flag', it stands for 'fast' (ncpfasthop). it only works on servers which don't cancel 0survivalfly violations. you can determine this by trying to fly with Hypixel mode, if it works NCPFHop will work. otherwise it will almost always flag the player after a couple hops. They wouldn't make a flag-type speed for NCP unless it had a flawed setback system, like AAC1.9.10 does, thats why teleport will 'work' on it but technically not 'bypass' it.

**Comment by SenkJu** [comment]
#2659
