### ISSUE TITLE
[BUG] Reach Calculation

### ISSUE THREAD

**Issue by SextupleTap** [CCBlueX/LiquidBounce1.8-Issues#3144]
**Describe the bug**
The combat reach portion of the reach module isn't function as it should be, at 3.837 reach (also tested with flat values of 3.8, 3.83 and 3.84) is when you can start hitting entities from a normal 3 block range. Something is probably wrong with the module, yet block reach seems to be working just fine at the minimum value of 4.5.

**To Reproduce**
1. Use build 64
2. Activate reach module and set combat reach to 3.84 (or 3.837)
3. Run a teleport command to set your rotation to 90 and 0 so your test is accurate (look vector thing is perfectly straight?)
4. Make sure you're in survival since reach is different from the two modes
5. Try to hit an entity from 3 blocks away with a value of reach like 3.5 and it is less than normal 3 block reach, now toggle back and forth with 3.84 and it feels like 3 block reach.

The Intended behavior I expected is for 3 block reach to be normal and values above to make it extended.

**Screenshots**
Video Demonstration:
https://www.youtube.com/watch?v=lURjpqZ1nN8&feature=youtu.be

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version 64
 - Minecraft Version 1.8.9
 - Forge 1.8.9-11.15.1.1722

Reference:
#2919

**Comment by SextupleTap** [comment]
Bump because it's broken

**Comment by SextupleTap** [comment]
Bump

**Comment by SenkJu** [comment]
That's due to the way LiquidBounce calculates reach. The distance is calculated to the center of the opponent at the level of his feet. It is not directly a bug, but I will not close this issue. Maybe we will deal with it sometime, but currently I don't see the need for it.

**Comment by SextupleTap** [comment]
Understandable, but the main question is if this causes flagging or makes it easily detectable

**Comment by SenkJu** [comment]
No, to the server it does not matter.

**Comment by SextupleTap** [comment]
What I've stated here can be extended to this more recent post:
#3244

**Comment by superblaubeere27** [comment]
This was fixed in #3244 I'd guess
