### ISSUE TITLE
[FEATURE] about anti forge again for different server

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3145]
Marco know what is that

Keyword (sonoyuncu)

**Comment by Emreploit** [comment]
mc.sonoyuncu.network omfg

**Comment by SenkJu** [comment]
That server seems to be down all the time.

**Comment by Teals53** [comment]
> That server seems to be down all the time.

why ? its online always

**Comment by Teals53** [comment]
bump

**Comment by Teals53** [comment]
@kawaiinekololis can you recheck for this ? also same thing for riseclient (craftrise) this servers have their own clients for join otherwise u cant join its say "u need use our client for join this server" what you can do for bypass that like a feature that allows you to log in by mimicking the packets sent by clients idk

**Comment by madeust1337** [comment]
**riseup xd**

**Comment by Teals53** [comment]
Bruh
