### ISSUE TITLE
[BUG] Why HeadRotations is shit

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3146]
why headrotations doesn't it reflect the truth ?

**Comment by SenkJu** [comment]
What do you mean?

**Comment by Teals53** [comment]
when i open headrotation and cilcik f5 then for example i test scaffold and want to how my head looks like when im using scaffold but headrotation not reflect the truth my head do stupit random thing but in reality its not like that if u watch ur friend in game when using scaffold or aura its not same him in game headrotation showing

**Comment by Teals53** [comment]
can you reopen this ? i just mean this headrotation is not smooth like in real
