### ISSUE TITLE
[FEATURE] Alt Manager beim Multiplayer menü

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#3148]
Add mal das man beim Multiplayer Tab/Menü oben irgendwo den Knopf "Alt Manager" hat wo man dann einfach weiter geleitet wird zum alt manager. Dass spart am ende einfach die Zeit sich in ein alt einzuloggen.

**Comment by SenkJu** [comment]
No.
