### ISSUE TITLE
[FEATURE] More Carry Items Pick up

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3151]
**Describe your feature request.**

If your inventory is full and there are items below you that you would like to collect, then More Carry moves Items from the inventory into the crafting slot.

More Carry is not allowed to insert ores, diamonds or arrows. If so, then some of the inventory should go into the crafting slots so that the ores, diamonds or arrows go into the normal inventory.

**Comment by superblaubeere27** [comment]
Again, not much advantages for a few players, but a huge coding time :/
