### ISSUE TITLE
[FEATURE] ClickGui Setting: No outdated cheats

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3153]
**Describe your feature request.**
If I have activated the setting in clickgui, outdated cheats are no longer displayed. For example, the Spectre settings count as obsolete at Speed. 
With ".outdated add Speed OldAACBHop" I can add or remove outdated hacks myself.

This is now more than necessary with this large number of cheats. So you can hide some unimportant and outdated cheats.

**Comment by Soulplexis** [comment]
very good

**Comment by SenkJu** [comment]
No, we will find a better solution to this problem eventually.
