### ISSUE TITLE
[BUG] WallGlide

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3157]
Describe the bug
if you try to go up ladders or vines with wallglide on it will just glide you down and you cant go up them

To Reproduce
1. turn on wallglide
2. try to go up vines or ladders then you cant

Videos
https://streamable.com/jxjkh

Additional information:
 - OS: [e.g. iOS] Windoes 10
 - LiquidBounce Build Version [e.g. b61] b64
 - Minecraft Version [e.g. 1.8.9] 1.8.9

**Comment by SenkJu** [comment]
Fixed.
