### ISSUE TITLE
[BUG] BlockOverlay

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3158]
Describe the bug
if you hover over string placed on the ground with blockoverlay it will say its a tripwire

To Reproduce
1. turn on blockoverlay hover over a placed string and it will say its a tripwire

Video
https://streamable.com/wmbow

Additional information:
 - OS: [e.g. iOS] windows 10
 - LiquidBounce Build Version [e.g. b61] b64
 - Minecraft Version [e.g. 1.8.9] 1.8.9

**Comment by Tcm9** [comment]
but it's also a trip wire. That is not a bug.

**Comment by Tcm9** [comment]
This block is a tripwire. It isn't a string.

**Comment by coolpvpv1** [comment]
> but it's also a trip wire. That is not a bug.

what???

**Comment by SenkJu** [comment]
What? Thats not a bug. This is a tripwire.
