### ISSUE TITLE
[FEATURE] No Lag module

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3160]
**Describe your feature request.**
- (setting) Frame: Picture frames are no longer loaded. On some servers, large picture frames on medium to bad pcs (with or without shader) can lower Minecraft FPS.

- (setting) Armorstands: Armorstands are no longer loaded. 

- (setting) Headskins: Heads are no longer have a skin. It is always a steve skin.

- (setting) Projectiles: Projectiles are no longer loaded. E.g. arrows, snowballs, ender pearls.

- (setting) Players: Players are no longer loaded. Friends should continue to be displayed.

- (setting) Mobs: Mobs are no longer loaded.

- (setting) Animals: Animals are no longer loaded.

**Additional context**
This picture frame and picture would disappear if you activated Frame:
https://www.bilder-upload.eu/bild-642d65-1569770339.png.html

**Comment by coolpvpv1** [comment]
> **Describe your feature request.**
> 
> * (setting) Frame: Picture frames are no longer loaded. On some servers, large picture frames on medium to bad pcs (with or without shader) can lower Minecraft FPS.
> * (setting) Armorstands: Armorstands are no longer loaded.
> * (setting) Headskins: Heads are no longer have a skin. It is always a steve skin.
> * (setting) Projectiles: Projectiles are no longer loaded. E.g. arrows, snowballs, ender pearls.
> * (setting) Players: Players are no longer loaded. Friends should continue to be displayed.
> * (setting) Mobs: Mobs are no longer loaded.
> * (setting) Animals: Animals are no longer loaded.
> 
> **Additional context**
> This picture frame and picture would disappear if you activated Frame:
> https://www.bilder-upload.eu/bild-642d65-1569770339.png.html

meh i guess this would be semi decent for bad pcs but i dont really think this should be added kinda seems useless

**Comment by Tcm9** [comment]
so above all Frame is important. When I play on servers, I regularly have about 15 FPS on lobbies. And there is a client that turns off the frames and armorstands. Then you suddenly have 40 FPS. So it surely brings something. And Projektile is helpful if there are a lot of arrows on the map. And Minecraft already starts to lag

**Comment by Soulplexis** [comment]
add it with Items because sometimes you can get tons of items, it's annoying. flux has it (noRender) and it actually came in handy when i crashing a server using mass amounts of items.

**Comment by SenkJu** [comment]
There are probably other Forge mods which have these features already.

**Comment by Tcm9** [comment]
I don't think so. The only mod who would do something like that would be the fastcraft mod. But it's for Minecraft version 1.7.10. For 1.8 it doesn't exist.
