### ISSUE TITLE
[FEATURE] Fast screenshots

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3161]
**Describe your feature request.**
If you make a screenshot, then you always have a short still image. If you replace the standard Minecraft screenshot mode with Liquidbounce, it should be smooth. It's only a small gimmick, but it's still an improvement.

**Comment by SenkJu** [comment]
It's not LiquidBounce job to do that. There might be mods which make screenshots non-blocking.
