### ISSUE TITLE
[FEATURE] Better Skinprotect.

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3166]
**Describe your feature request.**
first. If you press Tab, you still see your real skin, not the "fake skin".

I also want you to be able to add a custom skin. The one about 
"...\Roaming\.minecraft\LiquidBounce-1.8\fakeskin.png" saved is.
![2019-10-03_20 55 33](https://user-images.githubusercontent.com/31276706/66155587-49064380-e620-11e9-9cc2-a04d528a3fec.png)

**Comment by Tcm9** [comment]
fakeskin.png should always be a Steve, so that the custom skin does not look strange with an Alex.

**Comment by superblaubeere27** [comment]
I will fix this, but I am not going to add the custom skin feature

**Comment by superblaubeere27** [comment]
I also added this protection for skulls.

**Comment by Tcm9** [comment]
i created this issue for the custom skin and not for the little tab bug.

**Comment by Tcm9** [comment]
i want to play my main skin on alt accounts.

**Comment by superblaubeere27** [comment]
Nobody else would see that skin and yagni

**Comment by Tcm9** [comment]
yes, but I see my own skin on myself. That's what I want.
I do not always want to see an alex or steve skin on an alt account.

**Comment by superblaubeere27** [comment]
This feature is not worth the code for that one user that has his favourite skin ingame
