### ISSUE TITLE
[BUG] Problem in scripts

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3169]
**Describe the bug**
When I set  mc.gameSettings.keyBindJump.pressed = false and hold spacebar, even if it stops setting it to false, it doesn't jump

**To Reproduce**
OnUpdate mc.gameSettings.keyBindJump.pressed = false and hold spacebar then disable the script, it won't let you jump until you unhold and hold spacebar back

**Additional information:**
Tested in b64
Was working from b60 to b64 (Worked 4 hours ago on b64, stopped working, restarted the game, tried with different ways, still getting that)

**Comment by SenkJu** [comment]
That's not a bug.

**Comment by yorik100** [comment]
It's a bug, when I have inventorywalk enabled it works properly
