### ISSUE TITLE
LSD

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#317]
Fun Mod XD wenn man Zeit vertreiben will.

**Comment by MCmodding4K** [comment]
gibts auch als shader xD

**Comment by Marco-MC** [comment]
Drück dich einfach mal durchs "Secret Settings" durch. ^^

**Comment by MCmodding4K** [comment]
xD

**Comment by MaxHD00** [comment]
wow. LSD ist das aber immernoch nicht xD (ist ja nur ein fun mod)
