### ISSUE TITLE
CMD-Block

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#318]
Creative: du erhällst einen Comandblock **der schon ein command hat!**

du musst .cmdblock [befehl] machen um ihn zu bekommen. (der im extra inventar hat keine befehle drin)

PS: es soll auch mit comandblocklohren gehen. dazu .cmdlore [befehl] machen. (das geht nämlich noch auf servern)

**Comment by MCmodding4K** [comment]
kannst du mit .give machen, geht sowieso nur bis 1.8.3

**Comment by MaxHD00** [comment]
als ich es machte ist mc gecrasht

**Comment by MaxHD00** [comment]
und das geht sogar noch in der 1.11.2

**Comment by MaxHD00** [comment]
bitte wieder öffnen.

**Comment by Marco-MC** [comment]
Du musst es auch richtig machen, bei falscher Syntax crasht mc...

**Comment by Marco-MC** [comment]
Muss ich noch fixen

**Comment by MaxHD00** [comment]
bitte mit .CMDBlock befehl.
