### ISSUE TITLE
[FEATURE]Simple mode for a "legit" killaura

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3182]
It could be like just triggerbot with silent autoaim. That would be 100% legit without any packet based killaura methods. It will be very useful to completely avoid killaura detections on almost any server and it is not very complicated to code. There are autobanns on gomme for example that can't be fixed just with other values because raycast don't work perfect in the killaura. This would be just one usage of the new mode.

**Comment by Soulplexis** [comment]
Normal killaura already does that, it's called a 'facing' check and was added a few builds ago, they just need to change the aiming so it's more human-like and then not much can detect it from then.

**Comment by apexCode1337** [comment]
Yeah but the problem is that raycast don't work very well on gomme qsg and in gomme bw you got autobanns even without the aac raycast check. But when I play just with reach and triggerbot instead of killaura I don't have autobanns. And even when the mode isn't very useful It doesn't take much effort to code it.

**Comment by apexCode1337** [comment]
I tried many many hours to fix the autobanns with a better config but it's not possible. You need this new feature and then liquidbounce really is the best gomme client at the moment.

**Comment by Soulplexis** [comment]
yeah it's very strange you're probably right. they would probably just fix whatever flaws exist in the current killaura though
