### ISSUE TITLE
[FEATURE] Improve blink (should queue places, attacks, animations, actions)

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3183]
**Describe your feature request.**
Blink does not allow you to attack upon disabling, it can be very useful. (I think) Other clients have the ability to run to an enemy, attack them, run back and on disabling it will attack that enemy, as in halting attacking-packets too. 
I don't know which client allows this, but here:
to recreate:
1. turn on blink
2. run to an enemy some distance away
3. hit them
4. disable blink 
5. observe the entity not being attacked

**Comment by Marco09MC** [comment]
Attack: https://axolotl.vip/HV5I/TfcZg8Cy.mp4

**Comment by Marco09MC** [comment]
Build: https://axolotl.pics/nm4R/EdTYMLeJ.mp4
