### ISSUE TITLE
[FEATURE] Change default shader background

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3186]

**Comment by dddkj** [comment]
Dont be lazy Marco

**Comment by dddkj** [comment]
It is the last issue.Finish it and release b65 pls

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3214

**Comment by Teals53** [comment]
> It is the last issue.Finish it and release b65 pls

no its not last one he can add more issues instantly bcs he is marco xd
