### ISSUE TITLE
[FEATURE]NoFall AAC3.3.15

### ISSUE THREAD

**Issue by DeleteAndInsert** [CCBlueX/LiquidBounce1.8-Issues#3188]
Make that nofall mode auto disable when connected to CubeCraft ( cuz almost immediately autoban, in lobby too )

**Comment by coolpvpv1** [comment]
> Make that nofall mode auto disable when connected to CubeCraft ( cuz almost immediately autoban, in lobby too )

just dont turn it on then it if autobans? lol

**Comment by DeleteAndInsert** [comment]
> > Make that nofall mode auto disable when connected to CubeCraft ( cuz almost immediately autoban, in lobby too )
> 
> just dont turn it on then it if autobans? lol

you can go to cube from another config, forget about nofall and literally after 5-10 seconds get Ban. IP Ban.

**Comment by DeleteAndInsert** [comment]
Nah,

**Comment by DeleteAndInsert** [comment]
Nah, just done in scriptapi
