### ISSUE TITLE
eigener trank

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#319]
Creative:
mit .mypotion [trankeffekt] [trank LVL] [zeit] kannst du dir eigene Tränke machen.

du kannst auch mehrere effekte machen. mit  
.mypotion **(**[trankeffekt] [trank LVL] [zeit]**)** **(**[trankeffekt] [trank LVL] [zeit]**)** **(**[trankeffekt] [trank LVL] [zeit]**)** 
du musst einfach jeden Effekt **umklammern**.

**Comment by SenkJu** [comment]
.give

**Comment by SenkJu** [comment]
.give
