### ISSUE TITLE
Gomme teleporthit and teleport bedfucker??? 

### ISSUE THREAD

**Issue by 6alpha9** [CCBlueX/LiquidBounce1.8-Issues#3193]
So i was watching some hacking videos and i found this one:
https://youtu.be/cBanBn2WmBs
I just wanted to ask
cAn We HaVe ThIs?

**Comment by scorpion3013** [comment]
We have this... since months.... https://forum.ccbluex.net/thread.php?id=1261

**Comment by 6alpha9** [comment]
Thanks <3

**Comment by Lytexx** [comment]
you cant break beds with this tho

**Comment by scorpion3013** [comment]
@Lytexx how about not being stoopid? https://streamable.com/c958b

**Comment by Soulplexis** [comment]
AACClickTP is not in vanilla client,  so there is not a TPBedNuker/TPBedFucker.

**Comment by scorpion3013** [comment]
And it wont be added, cause there is a script for it.
