### ISSUE TITLE
[BUG] Tower/Scaffold Counter text disappier bug with ShaderESP

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3195]
https://axolotl.lol/UcSY/HSQ8vt4j.mp4
https://i.axo.im/vyqo/gPKNaCRt.mp4

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3128

**Comment by Teals53** [comment]
damn nigg

**Comment by Marco09MC** [comment]
https://axolotl.club/4qAk/9jV5oHzr.mp4 Seems to work now, maybe fixed the shaderesp disappier bug too. (sometimes shaderesp just stops working)
testing it later
