### ISSUE TITLE
[FEATURE] Toggle command should show "on" or "off" (module enabled or not)

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3198]
**Describe your feature request.**

**Additional context**

**Comment by CzechHek** [comment]
Make it so that .t module changes the state to opposite, but .t module on/off changes the state depending on the condition.

**Comment by Marco09MC** [comment]
![](https://axolotl.pics/ZWuA/UYtncuRc)
