### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by MinisBett** [CCBlueX/LiquidBounce1.8-Issues#3201]
**Describe your feature request.**
I don't know if its already possible but is there any kind of API to use(read would be enough) the liquidchat outside liquidbounce?

**Comment by scorpion3013** [comment]
Yes, its possible.
You can just look how its done here. https://git.liquidbounce.net/SenkJu/axochat-client/tree/master/src

**Comment by MinisBett** [comment]
Thanks!

**Comment by MinisBett** [comment]
@scorpion3013 Which AddressFamily do I have to use? Im trying to establish a connection from C#.

**Comment by MinisBett** [comment]
I've been messing around for hours but I cant figure out how to do it. Can you give me an example in Java, C#, python or something similar?
