### ISSUE TITLE
[FEATURE] Hud setting: Spactate on Death

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3208]
**Describe your feature request.**
If you died in Minecraft, you will see another button on the death screen.
"Spactate"
If you press it, you should be able to fly around even though you died in the game.

In the middle of your hotbar there should be a barrier called "Respawn". If you press it, you respawn.

**Comment by superblaubeere27** [comment]
Why is this needed?

**Comment by whycantiusemyname** [comment]
why is this needed? you can use freecam to fly around

**Comment by superblaubeere27** [comment]
Too hard to implement, too useless
