### ISSUE TITLE
[FEATURE] Minigame type mods

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3210]
**Describe your feature request.**
MurderMystery - Hypixel
checks for an array of items and detects the murderer
MurderMystery - MCPZ
checks for swords OR if the player sprints and then marks them as murderer
DisguiseDetector - Normal
Checks if mobs sprint or have weird pitch/yaw which is identifiable as a player not a real mob
SilentAimbot - Normal
thats why i suggested that Aimbot has a silent option a Long time ago, it's for this minigame. It can be used in quake and cops n crims
Fix to AutoWeapon Spoof 
AutoWeapon Spoof makes KillAura not work, because it's swapping item too fast? it cancels all of the hits. its also useful in murdermsyery so you can hide your sword easily.
ChestStealer - WhiteList
Only steal whitelisted items , for chestAura only open chests which contain whitelisted items.
_.cheststealer whitelist add <item>
.cheststealer whitelist remove <item>_

**Comment by superblaubeere27** [comment]
First of all, this issue has a bad format. Please create a standalone issue for every bug/feature.

**Comment by Teals53** [comment]
probly he not see your comment and this issue forgotted forever why u close issues instantly ? :d

**Comment by superblaubeere27** [comment]
@Teals53 If your issue has a such bad format, I will close it instantly. There is no way if turning this issue into a good format.

**Comment by Teals53** [comment]
:3
