### ISSUE TITLE
AntiNausea

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#322]
macht anti nausea ist antiblind rein.

**Comment by MaxHD00** [comment]
(AntiNausea soll kein eigenes Modul sein sondern wenn man Antiblind an hat soll es automatisch dabei sein.)

**Comment by superblaubeere27** [comment]
Ich adde es zum Milestone, aber @Marco-MC kann es gerne wieder removen

**Comment by Marco-MC** [comment]
Added

**Comment by Teals53** [comment]
Where Are This ? I Cant See

**Comment by Teals53** [comment]
And what is this ? @Marco-MC
