### ISSUE TITLE
[BUG] .damage

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3223]
Describe the bug
you cant do .damage to damage yourself even doing .damage damage then the number still doesn't work

To Reproduce
1. Do .damage 5 or any number and it doesn't work

Screenshots

Additional information:
 - OS: [e.g. iOS] Windoes
 - LiquidBounce Build Version [e.g. b61] b66
 - Minecraft Version [e.g. 1.8.9] 1.8.9

**Comment by Marco09MC** [comment]
use .hurt 5

https://axolotl.lol/GjHM/3TfVkcy6.mp4

**Comment by Haberno** [comment]
> use .hurt 5
> 
> https://axolotl.lol/GjHM/3TfVkcy6.mp4

ur in a singleplayer world it doesn't work on servers...
