### ISSUE TITLE
[FEATURE] Save On Modules On LocalAutoSettings

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3224]
Describe your feature request.
Save On Modules On LocalAutoSettings

Additional context
its annoying cause you make a localautosettings config for a anticheat then when you load it none of the modules for it load so you have to remember each module you had on and its just kinda annoying so i thought i should put this up on the github

**Comment by scorpion3013** [comment]
.localsettings save test312 values states
