### ISSUE TITLE
[FEATURE] 'NoDetectable' setting for InventoryMove

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3225]
Describe your feature request.
Move in clickgui without invmove

Additional context
lets say a anticheat detects both of liquidbounces inventorymoves and you disable it but when your like running from people and have to change some setting and you dont have inventorymove on you just stand still and would die so i just thought it was a good idea

**Comment by coolpvpv1** [comment]
not really what i meant i just meant to make it so you can walk in the clickgui without inventorymove but ok

**Comment by Marco09MC** [comment]
yeah I know but it's kinda the same

**Comment by Marco09MC** [comment]
and I think it's much better

**Comment by Marco09MC** [comment]
Added
