### ISSUE TITLE
[IMPROVE] Resort tab player list to client friends

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#3226]
**Describe the bug**
Pressing tab in chat will sometimes result in the client crashing.

**Comment by scorpion3013** [comment]
Happens when the person has too many friends saved.

**Comment by scorpion3013** [comment]
#2235

**Comment by Marco09MC** [comment]
Done.

**Comment by Haberno** [comment]
Wooo fibally
