### ISSUE TITLE
[FEATURE] Criticals HurtTime

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3228]
**Describe your feature request.**
for packet-like modes, this option would only critical when the entity can be hit, or only do criticals on the hit the entity was hurt at. it could help with "too many packets" kicks, and it could help with bypassing 

**Additional context**

**Comment by Lytexx** [comment]
big brain

**Comment by Marco09MC** [comment]
Added
