### ISSUE TITLE
[FEATURE] Improved longjump movement 

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3229]
**Describe your feature request.**
I made this script which makes longjump different and more easy to use. 
https://streamable.com/pam2h
as you can see it's difficult to land where you want to land without turning down the boostamount. it stops motion when you stop pressing movement keys which makes it very easy to control. that script i made also disabled longjump upon landing which could also be good to add. 

**Additional context**

**Comment by aftery142** [comment]
_very easy to control_
_**falls anyways**_

**Comment by Soulplexis** [comment]
> _very easy to control_
> _**falls anyways**_

i didn't fall though, did you even watch

**Comment by Marco09MC** [comment]
https://axolotl.vip/DRmMdrZW.mp4?key=kCQwBcfkWl6uCf

Done.
