### ISSUE TITLE
MidClick+

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#323]
Jedesmal wenn ich mir in Creative ein Item geben will kommt es. Oft komme ich auf RageQuit wenn ich ein freund adden will. Bitte überarbeitet das Midclick. Wenn ich ein Spieler anvisiere soll Midclick es selbstmerken und den Spieler zum Freund adden. (ohne Gui)  Und wenn ich in Creative bin und ein Block anvisiere soll er auch keine gui öffnen sondern mir den Block geben. Ansonsten soll eine eigene Schnellzugriff Gui haben. So wie bei dem Client (unten der link) die gui (es soll aber kleiner sein) Mit midclick öffne ich die Schnellzugriffgui (ich kann währenddesser weiterhin laufen, springen, hitten, blocken. man bedient die gui mit dem mausrad und der mitteltaste. schliessen kann man die schnellgui mit Chatöffnen, Inventaröffnen, esc oder Lb gui öffnen. 
Hier der link zum client mit dieser kreis gui:  www.wizardhax.com/2016/01/22/minecraft-disco-party-client-v2-1-8-1-8-9-hacked-client-download/

PS: man soll die Gui nicht mit der Maus steuern und 2 Lasst euch zeit. behält es im Hinterkopf. den sowas dauert sicher lange ^^

**Comment by SenkJu** [comment]
Wir werden garantiert nicht die Deluge GUI skidden.

**Comment by Marco-MC** [comment]
Lehne ich alles ab.
