### ISSUE TITLE
[FEATURE] .panic all and .panic (category)

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3238]
Describe your feature request.
there should be normal .panic that doesn't turn of render modules and .panic all that turns off every module

Additional context

**Comment by Teals53** [comment]
why its need turn off render modules ?

**Comment by Teals53** [comment]
render modules cannot seeable from other players and lb not a ghost client etc

**Comment by coolpvpv1** [comment]
> render modules cannot seeable from other players and lb not a ghost client etc

just saying it should be a feature

**Comment by Teals53** [comment]
:)

**Comment by Tcm9** [comment]
It would also be useful if you could only turn off the top category.
Example:

.panic combat
.panic movement
.panic render

**Comment by Marco09MC** [comment]
> 
> 
> It would also be useful if you could only turn off the top category.
> Example:
> 
> .panic combat
> .panic movement
> .panic render

Sounds good, I'm going to add it too.

**Comment by Marco09MC** [comment]
Added
