### ISSUE TITLE
[BUG] KeepAlive Description

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3240]
Describe the bug
when you hover over the module to see what it does it shows nothing

To Reproduce
1. Go to the 'clickgui'
2. Hover over 'KeepAlive'

Screenshots
not needed

Additional information:
 - OS: [e.g. iOS] Windows 10
 - LiquidBounce Build Version [e.g. b61] b66
 - Minecraft Version [e.g. 1.8.9] 1.8.9

**Comment by Marco09MC** [comment]
Changed to `Tries to prevent you from dying.`
