### ISSUE TITLE
[BUG]Killaura Rotations

### ISSUE THREAD

**Issue by Jxzh123** [CCBlueX/LiquidBounce1.8-Issues#3241]
Can you code a great rotations?
I think b66 rotations does not select the target
it is terrible

**Additional information:**
 - OS: [Windows]
 - LiquidBounce Build Version [e.g. b66]
 - Minecraft Version [e.g. 1.8.9]

**Comment by Marco09MC** [comment]
The killaura rotations are fine and we do our best to improve them. There is currently no reason why we should "improve" them when there is not that much to improve.
