### ISSUE TITLE
[FEATURE] NoPitchLimit ClientSide Option

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3242]
Describe your feature request.
i was looking through other clients and found one that had a nopitchlimit option for either clientsided nopitch or serverside sense serverside is detectable i guess the dev made a clientside option so i thought it should be in liquidbounce

Additional context

**Comment by Soulplexis** [comment]
i made a script that can make it do that

**Comment by Marco09MC** [comment]
Added
