### ISSUE TITLE
[BUG] All modules should calculate reach from the nearest point of the bounding box

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3244]
**Describe the bug**
Killaura range/Combat reach are INCORRECT : The range is from your head to the center of the enemy's hitbox, 3.8 reach will hit a villager farther than in vanilla but will not be able to hit an iron golem as far as in vanilla, you need to set from your head to the enemy's EDGE of hitbox
"function getDistanceToEntity(entity) {
    var DistanceX = mc.thePlayer.posX - (entity.getEntityBoundingBox().minX < entity.getEntityBoundingBox().maxX ? entity.getEntityBoundingBox().minX : entity.getEntityBoundingBox().maxX);
    var DistanceY = mc.thePlayer.posY - (entity.getEntityBoundingBox().minY < entity.getEntityBoundingBox().maxY ? entity.getEntityBoundingBox().minY : entity.getEntityBoundingBox().maxY);
    var DistanceZ = mc.thePlayer.posZ - (entity.getEntityBoundingBox().minZ < entity.getEntityBoundingBox().maxZ ? entity.getEntityBoundingBox().minZ : entity.getEntityBoundingBox().maxZ);
    var Distance = Math.sqrt(Math.pow(DistanceX, 2) + Math.pow(DistanceY, 2) + Math.pow(DistanceZ, 2));
    return Distance;
};" - Shiv3r

Aimbot and Killaura do not follow Minecraft rotation grid (GCD) making it possible to detect in few lines of code

Killaura and autoclicker (and trigger bot?) send attack packet before swing and move packet making it detected for noswing and invalid movement in some ACs

ALSO PLEASE, ADD KILLAURA SWITCH DELAY (AND AUTOBLOCK RANGE)!!!

**To Reproduce**
Use killaura or aimbot or autoclicker or combat reach

**Additional information:**
 - LiquidBounce Build Version 66
 - Minecraft Version [1.8.9]

**Comment by Lytexx** [comment]
maybe if you stop using caps he will add it to the milestone :d

**Comment by apexCode1337** [comment]
> maybe if you stop using caps he will add it to the milestone :d

Hi Lytexx xd

**Comment by yorik100** [comment]
Bump

**Comment by Shiv3RPolak** [comment]
GCD doesn't even exist and its bullshit

**Comment by yorik100** [comment]
> 
> 
> GCD doesn't even exist and its bullshit

It does perfectly exist

**Comment by aftery142** [comment]
Dont you have to check all edges then?

**Comment by yorik100** [comment]
> 
> 
> Dont you have to check all edges then?

Just take player's hitbox and get the closest position point from the head of your player

**Comment by aftery142** [comment]
> > Dont you have to check all edges then?
> 
> Just take player's hitbox and get the closest position point from the head of your player

Yes, that's what I meant.

**Comment by Marco09MC** [comment]
- [ ] KillAura
- [ ] Aimbot

**Comment by Marco09MC** [comment]
Done.
