### ISSUE TITLE
[FEATURE] LiquidScript API missing something

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3245]
**Describe your feature request.**
Something like mc.thePlayer.renderYawOffset but for pitch [eg : mc.thePlayer.renderPitchOffset]

**Additional context**
It's needed to make headrotation module to see rotations of LiquidScripts who modify your rotation [eg : Custom killaura, Derp]

**Comment by SenkJu** [comment]
LiquidBounce's script API simply exposes Minecraft classes, methods and fields to the user. It does not add any functionality to Minecraft's source code. If a method does not exist, you will have to implement it yourself just like you would if you were working on a regular Java Minecraft client.

**Comment by yorik100** [comment]
This will require to catch the render with an event and finding where the pitch is, I don't know if it's possible with LiquidScript

**Comment by scorpion3013** [comment]
" Something like mc.thePlayer.renderYawOffset but for pitch [eg : mc.thePlayer.renderPitchOffset]"

If something like that is in minecraft but not useable in the scriptapi, mostlikely means that the mappings are just incomplete. Its there, just with an genereric name like field_XXXXX_XX

**Comment by yorik100** [comment]
How to set pitch of the player (like headrotations) to ourself?
