### ISSUE TITLE
[FEATURE] Translator

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3246]
**Describe your feature request.**
When I write a text in the chat, there should be a button at the edge of the chat. If I press it, then I can select languages. If I have selected a language, and then send a text into the chat, then the written text is first translated with Google translator, before it is sent. So you can write in many languages to all of them. (this setting could be switched off in HUD) 

If I want to turn off the translator, all I have to do is press the X next to More..

**Additional context**
![Unbenannt](https://user-images.githubusercontent.com/31276706/70194126-b2c6ca80-1701-11ea-8227-264d253a4250.png)

![Unbenannt](https://user-images.githubusercontent.com/31276706/70192547-5dd48580-16fc-11ea-85bb-292a4439f4a6.png)

**Comment by Soulplexis** [comment]
I would like it too but the owners probably think it shouldn't be in a hacked client , I hope it's at least in a mod.

**Comment by yorik100** [comment]
So you don't understand what other people that answer you say XD

**Comment by superblaubeere27** [comment]
I will see if google translate still offers their translation

**Comment by superblaubeere27** [comment]
Done in CCBlueX/LiquidBounce#22
