### ISSUE TITLE
[FEATURE] Rotate back delay should be optional

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3247]
For example if scaffold is rotated back and you disable the rotations mode or the scaffold module itself it will take half a second to rotate back (This is not only clientsided). I know it's supposed to do that but It's bad that the scaffold does it even if keeprotation is disabled so please make it optional or just fix it in scaffold.

**To Reproduce**
1. Enable scaffold and headrotation
2. Enable keeprotations so it's easier to test
3. Make the scaffold rotate somehow so that you can see the rotation
4. Disable scaffold or the rotations option in the scaffold and you will see that it won't rotate back instantly

 - LiquidBounce Version: tested it on b64 and b66
 - Minecraft Version: 1.8.x

**Comment by Lytexx** [comment]
Neuer scaffold?    ![Download](https://user-images.githubusercontent.com/28214667/70347337-9e4d1400-1860-11ea-88ba-d4d54a12f6e5.jpeg)

**Comment by Soulplexis** [comment]
it's supposed to do that. the client is built for anticheats like AAC, if your head moves too fast they will flag some stuff (for example if scaffolding too fast, it ignores that you were looking at the block because ur head moves too quick)
so they added this system its like a sortof "rotation buffer" thing. i honestly think there should be a switch to turn it off or on, but that's just me

**Comment by apexCode1337** [comment]
I don't need the feature anymore but I think it should be optional too.

**Comment by apexCode1337** [comment]
> Neuer scaffold?

Ja diesmal so schnell wie ein Speed auf gomme eben sein kann.
Im Moment ist er 5% schneller als legit sprintjumping xd

**Comment by Marco09MC** [comment]
The problem is that we don't know where to put this option... LiquidBounce got no "global settings" etc stuff so... yeah that's a problem.

**Comment by apexCode1337** [comment]
> The problem is that we don't know where to put this option... LiquidBounce got no "global settings" etc stuff so... yeah that's a problem.
> 
It would be great if each module that uses rotations got the option because then there are many more things possible in the future.

**Comment by Marco09MC** [comment]
> 
> 
> > The problem is that we don't know where to put this option... LiquidBounce got no "global settings" etc stuff so... yeah that's a problem.
> 
> It would be great if each module that uses rotations got the option because then there are many more things possible in the future.
> 
> BTW why were 2 of my issues deleted?

We are not able to delete any issues, we just close them with a respond (containing a reason).

**Comment by kawaiinekololis** [comment]
added in b69
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3359

**Comment by apexCode1337** [comment]
Oh man that's nice love you <3
