### ISSUE TITLE
[BUG] mc.thePlayer.fallDistance won't work if the aac 3.3.15 nofall once sent the packet

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3248]
I want to use mc.thePlayer.fallDistance to check the falldistance but when I use the aac 3.3.15 nofall it doesn't work. I don't know if it's even possible to fix this bug but I hope so. Maybe someone can help me with a little workaround?

**To Reproduce**
1. **USE!!!** the aac 3.3.15 nofall once without dying or respawning after on a aac server.
2. Try to use mc.thePlayer.falldistance as a check
3. It won't work

 - LiquidBounce Build Version: b64
 - Minecraft Version: 1.8.x

**Comment by Marco09MC** [comment]
This is not a bug or any of kind of issue.
We are not going to change our code. You have to find another way to check the fall distance.
