### ISSUE TITLE
Capes

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#325]
währe cool wenn man Capes haben könnte (nur für sich selbst)

Was für ein Cape es sein soll kann man in %appdata% im liquidbounce Ordner ändern.
(Es soll eine Option geben die Capes an oder aus zu schalten.)

**Comment by Marco-MC** [comment]
Capes bekommt man nur für Spenden...
http://ccbluex.net/sites/liquidbounce/donate-help.html

**Comment by MaxHD00** [comment]
ok

**Comment by Brotgeschmack** [comment]
voll die geldgier bei ambien ist das gratis dabei...

**Comment by Brotgeschmack** [comment]
außerdem hat man bei euch das cape nur für einen account und nicht auch für alts

**Comment by Marco-MC** [comment]
@Brotgeschmack Ambien ist auch ein paid client. Wir machen das kostenlos. Wir verdienen ledeglich durch Werbeeinahmen und Spenden.

**Comment by Marco-MC** [comment]
Wenn du umbedingt ein Cape willst kauf dir doch Ambien und heuel hier nicht rum nur weil wir keine Free Capes vergeben.
