### ISSUE TITLE
[FEATURE] [BUG] please make SpeedModifier in the scaffold optional.

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3251]
The speedmodifier in the scaffold really should be optional: When you are jumping while building the Speedmodifier will always have an effect to your onground speed no matter which value you choose I think because the Speedmodifier has a static speed and if you're jumping or using a speed your onGround speed varies. That will cause flags on the most anticheats. It would be very very helpful if you make the Speedmodifier optional so that I finally can release my script for the gomme scaffold bypass.

**Comment by Marco09MC** [comment]
Just set it to the default value 1.

.scaffold speedmodifier 1
