### ISSUE TITLE
[FEATURE] Hurttime check in superknockback

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3252]
**Describe your feature request.**
I don't know if it's already there but it would be nice to have an optional Hurttime check in the superknockback module.

**Comment by yorik100** [comment]
Same for crits pls

**Comment by Marco09MC** [comment]
> 
> 
> Same for crits pls

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3228
@yorik100

**Comment by Marco09MC** [comment]
Added
