### ISSUE TITLE
[FEATURE] [BUG] mc.clickMouse() as raycast / raytrace method in killaura

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3253]
The existing raycast don't work without flags on aac with activated raycast check (tested on an anticheat Testserver). As far as I know, mc.clickMouse() is almost the only perfect working raycast method (tested with different clients). Please add it as an option in the killaura.

**Comment by Lytexx** [comment]
+1

**Comment by Marco09MC** [comment]
LiquidBounce is using the same raycast method like minecraft itself. The LiquidBounce Raycast is perfectly fine.
