### ISSUE TITLE
[FEATURE] .shortcut command

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3255]
**Describe your feature request.**
It should be possible to create new commands that execute other commands.

.shortcut new shortcutname command, command, ...

.shortcutname or .shortcut shortcutname

Example: 
.shortcut new fullarmor /give @p diamond_helmet 1, /give @p diamond_chestplate 1, /give @p diamond_leggings 1, /give @p diamond_boots 1, .toggle Autoarmor

If I enter .fullarmor now, I get a complete diamond armor and Autoarmor turns on/off.

With this you can shorten complicated commands or many Liquidbounce settings to one command. 

you should also be able to write something behind the shortcut. When I write
.shortcut new getItemStack /give %input 64
so he should give me 64 dirt at e.g. 
.getItemStack dirt

%input -> dirt

All shortcuts are saved in a txt in the Liquidbounce folder.
You can remove shortcuts with .shortcut remove shortcutname

**Comment by Soulplexis** [comment]
i think better to use the " ; " symbool because its less used. did u play starcraft too?
anyway yes it's a great idea!!
_.shortcut damagefly .hurt;.toggle fly;.delay 4;.toggle fly_
this for example, might be something which damages you, turn on fly and then 4 seconds later, turn off fly

**Comment by Tcm9** [comment]
I think the comma is good enough. But the developer can decide that.

**Comment by Marco09MC** [comment]
I think `;` would be much better.

**Comment by SenkJu** [comment]
.macro would be a more appropriate name for the command.

**Comment by Tcm9** [comment]
no one thinks about macro. please use .shortcut

**Comment by Tcm9** [comment]
thx

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/b86b9e7c0c26dffe9c46468a3e3f0bff2f40cdf5

**Comment by Tcm9** [comment]
Very cool. Just a quick info. You cannot use @p. Or if you give yourself an armor, you need a command that says that the player should get this item. Or that all players should get the item.

**Comment by Teals53** [comment]
Pretty nice

**Comment by Teals53** [comment]
@Marco09MC fix syntax and i know its still devolopment build thats why i dont open a new issue for that <3

![image](https://user-images.githubusercontent.com/13446881/71719757-6241aa80-2e30-11ea-827f-fae233d8fb87.png)

**Comment by Soulplexis** [comment]
> .macro would be a more appropriate name for the command.

i thought that said .marco xD
