### ISSUE TITLE
[FEATURE] [BUG] please make SpeedModifier in the scaffold optional. (repost because the problem is not solved)

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3258]
When you are jumping while building the Speedmodifier will always have an effect to your onground speed no matter which value you choose I think because the Speedmodifier has a static speed but if you're jumping or using a speed your onGround speed varies. I think that's the reason why it wont work on the value 1 too. Thanks for the help in my first post, but I already tried many values and it never worked.

**Comment by Marco09MC** [comment]
SpeedModifier has NO STATIC SPEED OR ANYTHING.

It just multiply your current motion X and Z when you are on ground, but... 1 will always be the SAME VALUE AS BEFORE.

**Comment by Marco09MC** [comment]
Show me a video or something of your problem with much more details. I'm 100% sure that your issue has nothing to do with speed modifier.

**Comment by apexCode1337** [comment]
you can trust me i tested it very very often but here is the video:

https://streamable.com/fwnjy

first i use my script, that disables scaffold while being onGround so that speedmodifier wont change my onground speed.

then i use the exact same thing just without disabling the scaffold. i used speedmodifier 0.9 in the vid but it dont work on every other value as well. on 0.8 its working a bit but i still get flags if i change direction or something.

**Comment by Marco09MC** [comment]
SpeedModifier is not the reason. Everyone with common sense will understand that 
`a * 1 = a`

**Comment by apexCode1337** [comment]
ah ok it's * and not =.

but for some reason the speedmodifier flags. i can do another video where i show it. please just make it optional even if we dont understand why it flags. it is not much effort to do it and im sure it will solve the problem.

**Comment by Marco09MC** [comment]
... when you change the value to 1 it's disabled.

**Comment by Marco09MC** [comment]
it's already "optional"

**Comment by apexCode1337** [comment]
Hm ok.
Do you have an idea why it flags when I don't disable scaffold?

**Comment by ArrowReport** [comment]
wtf is this thread
