### ISSUE TITLE
[BUG] Sneak sprints backwards

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3259]
**Describe the bug**
If sneak with the switch mode is activated and you walk backwards it will automaticly sprint and you get flagged

**To Reproduce**
1. toggle sneak with the switch mode
2. walk a little bit 
3. walk backwards and it will sprint even if the sprint module is not activated

**Additional information:**
 - LiquidBounce Build Version b66
 - Minecraft Version 1.8.9

**Comment by gitvitox** [comment]
Couldn't reproduce the bug. Is this still working for you?

**Comment by apexCode1337** [comment]
Disable Sprint. You have to Sprint forward first
