### ISSUE TITLE
Inventory Tweaks

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#326]
Wenn man eine truhe öffnet soll oben rechts 3 buttons sein wo man das Inventar sortieren kann.
(genau so wie der Mod Inventory Tweaks (nur ohne die extra Einstellungen (die 3 punkte)) das soll man im client einstellen können. Zudem bitte noch ein slow mode.)

**Comment by Fleroxh** [comment]
@MaxHD00 Woher hast du so viele Ideen? Checke bitte auch, ob dein vorschlag/issue noch nicht im Client vorhanden ist. xD

**Comment by MaxHD00** [comment]
ok. ^^
