### ISSUE TITLE
[REMOVE] Remove MultiMode setting from KillAura (broken and useless anyway)

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3261]

**Comment by Marco09MC** [comment]
Removed

**Comment by Teals53** [comment]
so why its not removed before updates ? its broken now ? xD

**Comment by yorik100** [comment]
NCP Multi was bypassing on LB (hitting multiple targets that are close to eachothers

**Comment by icewormy3** [comment]
> NCP Multi was bypassing on LB (hitting multiple targets that are close to eachothers

It was only working on oldncp but k

**Comment by yorik100** [comment]
> 
> 
> > NCP Multi was bypassing on LB (hitting multiple targets that are close to eachothers
> 
> It was only working on oldncp but k

It's working on Mineplex

**Comment by icewormy3** [comment]
> > > NCP Multi was bypassing on LB (hitting multiple targets that are close to eachothers
> > 
> > 
> > It was only working on oldncp but k
> 
> It's working on Mineplex

without banwaves?

**Comment by Marco09MC** [comment]
MultiMode NCP is just FOV 40, so just set .killaura fov 40

**Comment by yorik100** [comment]
> 
> 
> MultiMode NCP is just FOV 40, so just set .killaura fov 40

Any way to have switch + NCP multiaura? Because it'd be super strong on Mineplex or an option to hit near targets at the same time

**Comment by yorik100** [comment]
And check if the targets near the player are in killaura range/thru walls range if these near targets are behind walls

**Comment by Soulplexis** [comment]
thank god it was so annoying
