### ISSUE TITLE
[FEATURE] Illusion (Autoarmor setting)

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3262]
**Describe your feature request.**
If you have good armor, all your rivals will run away from you. If you have (FakeNoArmor or Illusion) (setting) turned on at Autoarmor, then you have taken off your armor by default. If now a player closes on a some distance, then autoarmor puts on the armor. Then the players don't always run away because you give them the illusion that they are better equipped. 

The distance at which the armor is to be put on should be configurable.

**Comment by superblaubeere27** [comment]
I won't implement it since it is hard to do without much advantage. But it is a fun idea anyways ;D

**Comment by whycantiusemyname** [comment]
its a good idea :D

**Comment by superblaubeere27** [comment]
You can bind AutoArmor, take off your Armor and then renable it when a player is coming close ;D

**Comment by whycantiusemyname** [comment]
but u have to manual take off your armor again and again. is very troublesome

**Comment by superblaubeere27** [comment]
@whycantiusemyname Takes long too implement for some users having fun trolling others. Implementing every fun idea which could be useful in an absurd way will trash the client with useless options.

**Comment by whycantiusemyname** [comment]
and it will be a problem to take on armor in the eyes of the enemy. i dont know how to write code, so i dont know to check are you in the eyes of the enemy is hard.

**Comment by whycantiusemyname** [comment]
yes we only have Limited time

**Comment by superblaubeere27** [comment]
In the eyes of an enemy would be a bad idea, just look if the enemy is in rage. `if (mc.theWorld.loadedEntityList.stream().anyMatch(e -> e.getDistance(mc.thePlayer) < illusionDistance.getObject())) { <take on armor> }`
