### ISSUE TITLE
[FEATURE]Add onStep and onStepConfirm event for ScriptAPI

### ISSUE THREAD

**Issue by dddkj** [CCBlueX/LiquidBounce1.8-Issues#3263]
**Describe your feature request.**
this.onStep = function(event) {
    var height = event.getHeight();
    event.cancelEvent();
    event.isCancelled();
}
This is useful

**Additional context**

**Comment by dddkj** [comment]
I don't think it needs two events
just use:
var eventState = event.getEventState();
	eventState.getStateName(); // PRE or POST

**Comment by dddkj** [comment]
@Marco09MC

**Comment by Marco09MC** [comment]
There is already a StepEvent and a StepConfirmEvent in liquidbounce, so yeah. Not going to change it.

**Comment by dddkj** [comment]
Ok

**Comment by dddkj** [comment]
What events does liquidbounce have
and
If possible,please add them

**Comment by aftery142** [comment]
not related to step, but please add even more events/enable reflection/...

**Comment by Soulplexis** [comment]
can you add "onLand" upon landing on the ground after you were previously not on ground.

**Comment by aftery142** [comment]
Jeez you are lazy

**Comment by yorik100** [comment]
> 
> 
> can you add "onLand" upon landing on the ground after you were previously not on ground.

You can literally do that easily

**Comment by mrphax0r** [comment]
var a;
this.onUpdate = function() {
if(!mc.thePlayer.onGround) a = true;
if(mc.thePlayer.onGround && a) {
a = false;
//your code here
}
}

**Comment by dddkj** [comment]
> var a;
this.onUpdate = function() {
if(!mc.thePlayer.onGround) a = true;
if(mc.thePlayer.onGround && a) {
a = false;
//your code here
}
}

If you are falling?

**Comment by Marco09MC** [comment]
Added
