### ISSUE TITLE
[FEATURE] CustomHUD Scoreboard

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3265]
**Describe your feature request.**
You should change the position of the scoreboard in the liquid design settings.

You should also be able to change the background transparency of the scoreboard.

NoScoreboard can be deleted, because you can easily delete the scoreboard in the Liquiddesign settings.

(Alternatively you can rename NoScoreboard to Scoreboard, and all settings should be in there. 

- Yloction (you can move the Scoreboard in the Y-line
-Alpha (transparency) (0-100%)
-NoScoreboard
)

**Additional context**
![image](https://user-images.githubusercontent.com/31276706/70852214-366d7d80-1e9f-11ea-868b-1b90843804e8.png)

**Comment by DeleteAndInsert** [comment]
In many clients, I see the ability to move the Scoreboard only in the Y position.  Why Y only?  Moving the Scoreboard in any position would be great.

**Comment by superblaubeere27** [comment]
Particially added in CCBlueX/LiquidBounce#21

**Comment by kawaiinekololis** [comment]
Still not done because I have to figure out how I add the scoreboard to users with a existing custom hud config.

**Comment by kawaiinekololis** [comment]
Done. Scoreboard is now a fixed element which means that the scoreboard is **NOT** deletable and will added back to the HUD when missing

Use NoScoreboard.
