### ISSUE TITLE
[FEATURE]Add more module algorithms for ScriptAPI

### ISSUE THREAD

**Issue by dddkj** [CCBlueX/LiquidBounce1.8-Issues#3267]
**Describe your feature request.**
For example:
killauraModule.getTarget();
antibotModule.getBotList();
antibotModule.addBot(bot);
antibotModule.removeBot(bot);
teamsModule.addTeammate(teammate);
teamsModule.removeTeammate(teammate);

**Additional context**

**Comment by SenkJu** [comment]
Not possible because LiquidBounce modules are obfuscated.
