### ISSUE TITLE
[FEATURE] .Target, inventorysee of other players, and updating friending system.

### ISSUE THREAD

**Issue by Haberno** [CCBlueX/LiquidBounce1.8-Issues#3268]
Targetting:
-.target (name of player) it finds proiotizes the death of the hopper before any other player (for hvh most likely)
-InventorySee 
.inventorysee (playername) allows you tosee the inventory of player choosen 

It would be good if u guys changed the way of adding frienndsby just making it toggle .friend instead of writing .friend add so if you do .friend name of player -> checks if player is in friend list ->if false then add -> if player is already added then remove from f list.

**Comment by aftery142** [comment]
yes marco add .target u nn

**Comment by SenkJu** [comment]
#3293 
It is not possible to see the inventory of other players.
