### ISSUE TITLE
[BUG] Apples not eating killaura hitsplayer with gapple inhand

### ISSUE THREAD

**Issue by Haberno** [CCBlueX/LiquidBounce1.8-Issues#3269]
**Describe the bug**
When killaura is activated and you try to eat an apple and the apple hits or makes of motion of trying to hit a person, eating the apple doesn't register and makesa glitch happen where you don't actually eat it

**To Reproduce**
1. go to hypixel
2.go to hypixel the pit
3.Turn on killaura, NoSlow, criticals, Velocity (keeping criticals off getsu banned for some reason after a bit)
4. Then kill a player and having killaura activated target a player with the gapple in your hand and  then try eat a gapple 

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b66]
 - Minecraft Version [e.g. 1.8.9]

**Comment by SenkJu** [comment]
Hypixel's AntiCheat probably does not allow players to consume an item while attacking another entity. This is not a client bug.
