### ISSUE TITLE
[REMOVE] Remove RazerKeyboard module and turn into script

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3273]

**Comment by Marco09MC** [comment]
Done. Script made by @SenkJu 
Requires https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3276

**Comment by SenkJu** [comment]
Script version of module can be downloaded here: https://dl.ccbluex.net/download/skip/index.php?target=f443725b6
