### ISSUE TITLE
[FEATURE]Fix damage module[Does not work at all and does no damage for hypixel]

### ISSUE THREAD

**Issue by Haberno** [CCBlueX/LiquidBounce1.8-Issues#3279]
**Describe your feature request.**

**Additional context**

**Comment by yorik100** [comment]
Disable nofall heh

**Comment by Haberno** [comment]
> Disable nofall heh

I dont have it on

**Comment by yorik100** [comment]
Disable criticals

> 
> 
> > Disable nofall heh
> 
> I dont have it on

**Comment by yorik100** [comment]
You can also try this https://forum.ccbluex.net/thread.php?id=2294
