### ISSUE TITLE
World Downloader + rejoin button im Pausemenü.

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#328]
bitte fügt ein World Downloader hinzu.
(Im Pausemenü (esc im spiel) soll es noch die Möglichkeit geben die Welt runterzuladen. )
(PS: fügt bitte noch Rejoin hinzu. Kann hilfreich sein.)

**Comment by Marco-MC** [comment]
WorldDownloader kannst du dir selbst hinzufügen, wenn wir mit unserer Forge Injection fertig sind...
