### ISSUE TITLE
[FEATURE] More ScriptAPI events

### ISSUE THREAD

**Issue by True-cc** [CCBlueX/LiquidBounce1.8-Issues#3280]
**Describe your feature request.**

I'd like to have all of these events (took screenshot from my client) in the ScriptApi. I know you already have some in the script api, but if you could add these, it'd make the ScriptApi MUCH better.

**Additional context**

ScreenShot of the ones I want:
https://cdn.discordapp.com/attachments/514613503466668033/659118171869020162/unknown.png

**Comment by True-cc** [comment]
https://forum.ccbluex.net/thread.php?id=2278

**Comment by icewormy3** [comment]
agreed! +1

**Comment by True-cc** [comment]
https://github.com/CCBlueX/LiquidBounce-ScriptAPI/issues/25

**Comment by yorik100** [comment]
+1

**Comment by True-cc** [comment]
> +1

uwu

**Comment by SenkJu** [comment]
Added onStep, onStepConfirm, onWorld and onSession. Other events are not supported and not required. If you need a specific event tell me which and why you would need it.

**Comment by True-cc** [comment]
That's fair.
