### ISSUE TITLE
[FEATURE] InSight

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3282]
**Describe your feature request.**
If another player sees you on the screen, Liquidbounce will display an "InSight! 

Since many have their own FOV settings, you should be able to adjust the scan range of the screen by the opponent player. (FOV 30-110) Standard: 80

If another player can see you, then there should be a setting (sound) where bass.ogg is played every second, so that you can acoustically hear that another player is watching you.

**Comment by NurMarvin** [comment]
no

**Comment by gitvitox** [comment]
abgelehnt

**Comment by Lytexx** [comment]
Why whould you need this

**Comment by Tcm9** [comment]
If you want to use Scaffold, speed, fly... without another player noticing.

If a player sees you hacking, he will report you very quickly, and then it won't be long before you are banned.

and with InSight you can see if other players see you. If not, you can switch on your hacks at your leisure.

and with InSight you can see if other players see you. If not, you can switch on your hacks.

**Comment by Tcm9** [comment]
![image](https://user-images.githubusercontent.com/31276706/71447635-21aba800-2731-11ea-916b-b76a839be71d.png)

For example, someone here saw me multiplying items. So he called everyone directly to report on me.
If I had Insight, I wouldn't turn on the hack until I knew nobody was watching me.

**Comment by Tcm9** [comment]
and now...
![image](https://user-images.githubusercontent.com/31276706/71447798-7fd98a80-2733-11ea-8a03-3292df6d9fa5.png)

**Comment by Soulplexis** [comment]
It could have an open eye icon next to the nametag when they can see you, and closed eye when they cannot
and if you're behind an opaque wall and sneaking it will be closed even if they are looking toward you because they wont be able to see you.

**Comment by Tcm9** [comment]
way too complicated. Just have "InSight" pop up in the HUD if you're just seen.

**Comment by R0b3rt1337** [comment]
You could still be seen bc of ping

**Comment by superblaubeere27** [comment]
Maybe I will make this on a stream on my channel, but I don't think that many people are going to use it so I won't be actively working on it.

**Comment by superblaubeere27** [comment]
I don't think that this feature is ever going to be added, because it is hard to do, unprecise, CPU intense and not that useful
