### ISSUE TITLE
[FEATURE]Show Sneak state

### ISSUE THREAD

**Issue by Lytexx** [CCBlueX/LiquidBounce1.8-Issues#3284]
shows when you sneak using sneak modul

**Comment by Tcm9** [comment]
is this a setting for Sneak?

**Comment by yorik100** [comment]
+1

**Comment by Soulplexis** [comment]
yes its like head rotations, but it shows you sneaking even though client side you are not (third person)

**Comment by SenkJu** [comment]
Just look at the array list. When sneak is enabled, you are sneaking.
