### ISSUE TITLE
[BUG] Fucker Swing dont work

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3285]
**Describe the bug**
He does not swing if the setting is on.

**Additional information:**
 - OS: WIndows 
 - LiquidBounce Build Version b66
 - Minecraft Version 1.8.9

**Comment by Lytexx** [comment]
Works for me do you have any proof?

**Comment by SenkJu** [comment]
Only happens when Fucker Instant is enabled.

**Comment by Marco09MC** [comment]
Fixed
