### ISSUE TITLE
[FEATURE]Separate rotationspeed ontarget

### ISSUE THREAD

**Issue by Lytexx** [CCBlueX/LiquidBounce1.8-Issues#3286]

**Comment by Lytexx** [comment]
Seperate aimspeed when your aim is on a target

**Comment by yorik100** [comment]
I agree, it'd make randomcenter not snap every single ticks

**Comment by SenkJu** [comment]
What? Why?

**Comment by yorik100** [comment]
> 
> 
> What? Why?

Because snapping frantically on the enemy is kinda super easy to detect
