### ISSUE TITLE
[BUG] KillAura causing EXTREME lags with low timer since b65 (LiquidLauncher only) 

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3287]
**Describe the bug**
If you have timer lower than ~0.6 and try to hit with KillAura, you get extreme lag spikes. It only happens if your average cps are above 5, so it has something to do with the cps update, but it for some reason only happens with KillAura (AutoClicker and TriggerBot work correctly).

**To Reproduce**
1. ".timer speed 0.5"
2. ".t timer"
3. Hit with KillAura (average cps above 5)

**Log**
[https://hasteb.in/raw/fevumiwi](https://hasteb.in/raw/fevumiwi)

**Additional information:**
 - OS: Win 10 64bit
 - LiquidBounce Build Version: b65 & b66
 - Minecraft Version: 1.8.9

**Comment by Shiv3RPolak** [comment]
+1 marco bot

**Comment by yorik100** [comment]
+1

**Comment by icewormy3** [comment]
+1

**Comment by Shiv3RPolak** [comment]
same with fastplace

**Comment by SenkJu** [comment]
I am unable to re-produce this problem. Could you send me the exact Timer and KillAura values you are using.
