### ISSUE TITLE
[BUG] Threebugs that should be fixed (Intervals ,Ghosthand and Font)

### ISSUE THREAD

**Issue by Shiv3RPolak** [CCBlueX/LiquidBounce1.8-Issues#3288]
>Intervals are not cleared when .reload'ed
>Ghosthand makes scaffold and tower don't place blocks (tower will still jump/motionup/teleport etc)
>Fonts are not reloading on .reload

**Comment by SenkJu** [comment]
#3292 
You have to clear intervals yourself. This is not a bug.
The purpose of GhostHand is to allow the player to access chests through blocks. Of course Tower and Scaffold do not work when it is enabled. Not a bug either.
