### ISSUE TITLE
book hack

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#329]
Wenn man ein beschreibbares Buch öffnet, soll man oben rechts ein Befehl eingeben können. Wenn ein Spieler dann das Buch **nur** öffnet soll der Befehl ausgeführt werden.(mc 1.8.8) (Vanilla)
 (ob es bei Spigot geht weiss ich nicht. ich denke bei Spigot muss man auf den Text klicken damit der Befehl ausgeführt wird.)

**Comment by MCmodding4K** [comment]
nur durch öffnen geht nicht, mit befehl geht nur in gm1.
Buch sonst mit .give geben
