### ISSUE TITLE
[FEATURE] onPacket

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3290]
**Describe your feature request.**
this.onPacket = function(event) {
    var packetDirection = event.getDirection();
    eventState.getDirection(); // OUTGOING or INCOMING
};
OUTGOING = client packet -> server
INCOMING = server packet -> client

**Comment by SenkJu** [comment]
Why would you need that?

**Comment by Marco09MC** [comment]
There is no reason implementing something like that because there are seperate packet classes in minecraft for client and server packets.
