### ISSUE TITLE
[FEATURE] Save Background Settings

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3291]
so i not need close background everytime

**Comment by Haberno** [comment]
What

**Comment by Teals53** [comment]
> What

![image](https://user-images.githubusercontent.com/13446881/71560159-352f7980-2a77-11ea-8ad7-000a2f819fed.png)

**Comment by SenkJu** [comment]
Could you describe more clearly what you mean?

**Comment by Teals53** [comment]
i set enabled settings off then i close game and reopen but its came with on its not saved from off an i need close this everytime when i open game

**Comment by Marco09MC** [comment]
oh yeah... I forgot to implement saving the background settings...

**Comment by Marco09MC** [comment]
Added
