### ISSUE TITLE
[BUG] CPS Calcs causes error in LiquidLauncher

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#3294]
[liquidluancherlog.txt](https://github.com/CCBlueX/LiquidBounce1.8-Issues/files/4008510/liquidluancherlog.txt)
**Describe the bug**
Focking lags

**To Reproduce**
Killaura mincps 16, killaura maxcps 16
timerspeed 0.6
having killaura and timer activated and attacking something

Only happens in LiquidLauncher
No issue in default mc launcher & other launchers like multimc
(jvm arugments maybe the reason?)

**Additional information:**
 - Windows
 - LiquidBounce Build Version b66
 - Minecraft Version1.8.9
 - Latest LiquidLauncher version 1.1.3

#3287

**Comment by CzechHek** [comment]
Problem occured even with exactly same JVM Arguments and Java.

Problem is caused by LiquidLauncher only.
