### ISSUE TITLE
[FEATURE] Ignore NoFall option when using BoostHypixel fly

### ISSUE THREAD

**Issue by kloc9999** [CCBlueX/LiquidBounce1.8-Issues#3309]
**Describe your feature request.**
It annoys me to disable NoFall before using BoostHypixel fly.

**Additional context**
And why? Because when using BoostHypixel fly you get damage, and without that damage the fly just dosen't work. (talking about hypixel)

**Comment by Marco09MC** [comment]
the problem is that ... we are using the noground nofall for hypixel.
and when disabled after running around etc ... you will die because of fall damage... xd

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3313
