### ISSUE TITLE
Crash Map

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#331]
Im Extra Creativemenü soll eine Map sein die alle Spieler,die diese Map in der Hand haben crashen.
(Der Liquidbounce client soll nicht gecrasht werden wenn er diese Map in der Hand hat. (soll einfach nicht gerendert werden.))

**Comment by MCmodding4K** [comment]
sowas gibts in der 1.11 schon soweit ich weiß

**Comment by Marco-MC** [comment]
Ja, das giebts nur in der 1.11 seit den neuen Mensions wo dann die neuen Maps hinzugefügt wurden.
