### ISSUE TITLE
[FEATURE] Add a "Reconnect with a new TheAltening alt" button in the disconnect menu

### ISSUE THREAD

**Issue by kloc9999** [CCBlueX/LiquidBounce1.8-Issues#3310]
**Describe your feature request.**
Add a "Reconnect with a new TheAltening alt" button in the disconnect menu

**Additional context**
This button will only appear if you set the thealtening api key in Alt Manager > TheAltening

**Comment by Lytexx** [comment]
If you have an api token saved in liquidbounce you can just use reconnect with new account
It will take an thealtening account

**Comment by scorpion3013** [comment]
#3074

**Comment by superblaubeere27** [comment]
Dublicate
