### ISSUE TITLE
[BUG]scaffold zitter is broken since b65 

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3314]
Since the b65 the zitter mode teleport only teleport onground. If you jump it will be like the smooth zitter mode for some reason. Before it zittered always. Please fix this bug I need zitter as a bypass.

**To Reproduce**
1. Enable zitter  with the teleport mode in the scaffold
2. Turn on scaffold and just jump a bit.
4. You will see it will only teleport while being onground.

**Additional information:**
 - b66
 - 1.8.9

**Comment by Haberno** [comment]
What does zitter even do

**Comment by apexCode1337** [comment]
It moves left and right slightly while building

**Comment by Haberno** [comment]
Why use b65 Anyways use b66

**Comment by apexCode1337** [comment]
what do you mean?

**Comment by CzechHek** [comment]
You can also use zitter mode teleport with strength 0 to modify scaffold speed precisely using the zitter speed value.

**Comment by apexCode1337** [comment]
Oh that's nice thanks

**Comment by superblaubeere27** [comment]
This isn't a bug. It is suppose to work in this way because you can't move while being in mid-air

**Comment by apexCode1337** [comment]
But please make it optional I need it to bypass the scaffold in gomme

**Comment by superblaubeere27** [comment]
Gomme uses AAC, it flags mid-air movement

**Comment by apexCode1337** [comment]
Not in bw because the Velocity checks are disabled there

**Comment by superblaubeere27** [comment]
Ok, then make a script module and use it with scaffold

**Comment by apexCode1337** [comment]
Bit I don't know how :(
