### ISSUE TITLE
[FEATURE] Next Alt Option

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3316]
can you add this option for login more faster some servers without 

![image](https://user-images.githubusercontent.com/13446881/71619592-27443a80-2bd6-11ea-9f9e-695c99fcab57.png)

**Comment by superblaubeere27** [comment]
Nope. You can just go to alt manager and since #3380 is added you can just double-click the next alt

**Comment by Teals53** [comment]
kk anyway i not need this anymore
