### ISSUE TITLE
[BUG] Direct Login Visual Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3317]
its normal in here
![image](https://user-images.githubusercontent.com/13446881/71620471-472a2d00-2bdb-11ea-817b-59be9d0ec543.png)

then i click left arrow again and go first letter
![image](https://user-images.githubusercontent.com/13446881/71620478-514c2b80-2bdb-11ea-8d96-f92496a6e4ab.png)

**Comment by superblaubeere27** [comment]
I fixed it CCBlueX/LiquidBounce#17
