### ISSUE TITLE
[FEATURE] Update NoSlow Settings

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#3322]
**Describe your feature request.**
Make NoSlow fully customizable.

**Comment by SenkJu** [comment]
Updated by @ventolotl (https://github.com/CCBlueX/LiquidBounce/pull/4)

<img src="https://axolotl.club/HzuEGkSn.png?key=sToZpmdKXDUgOX">

**Comment by Teals53** [comment]
so old bypass options just have different multiplier values ? can u share old bypass multiplier settings so i can set this again with new version ? @SenkJu

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/71643603-c6e3f480-2ccc-11ea-913b-7d46af0276bd.png)
maybe this things is what i want :d
