### ISSUE TITLE
[FEATURE] ScriptAPI should catch all errors

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3323]
**Describe the bug**
If there is moduleManager.getModule("invalidmodule") in a script (probably other things too) it causes:
- .reload to crashes game
- .scripts reload to return kotlin.KotlinNullPointerException: null

It shouldn't load the script if there is an error.

**To Reproduce**
1. Script with moduleManager.getModule("invalidmodule") it probably has to be in OnDisable or somewhere.
2. .reload or .scripts reload

**Additional information:**
 - OS: Windows 10 64 bit
 - LiquidBounce Build Version b67
 - Minecraft Version 1.8.69

**Comment by Shiv3RPolak** [comment]
yes

**Comment by apexCode1337** [comment]
b67?

**Comment by Marco09MC** [comment]
Could you send a example script?

**Comment by Marco09MC** [comment]
Done.
