### ISSUE TITLE
[BUG] Add .panic Syntax

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3328]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3238

**Comment by R0b3rt1337** [comment]
Already exists in b67

**Comment by Teals53** [comment]
when i do .panic its just panic for with all without non render its dont have syntax like .panic (movement, combat ,all etc)

**Comment by R0b3rt1337** [comment]
.panic combat/movement/etc. are usable, will submit a pull request with syntax

**Comment by Teals53** [comment]
yeah im saying same thing <3

**Comment by R0b3rt1337** [comment]
Done, might take a while until the release though bc its too late for b68

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/628a87cd0e487b945f3bcf20b98de7c6a7e11e97
