### ISSUE TITLE
AAC wallspeed

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#333]
Es gibt derzeit ein Wallspeed für aac. Bitte Hinzufügen.

**Comment by Marco-MC** [comment]
Was soll das bitte sein?

**Comment by MaxHD00** [comment]
man kann an der Wand einen Vanillaspeed machen. (aac) (aber nur solange man dicht an der Wand ist und nicht direkt am Anfang ganz schnell ist.) Daraus kann man ein Speed machen.
