### ISSUE TITLE
[BUG] NameTags BUG

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3331]
![2020-01-01_19 01 08](https://user-images.githubusercontent.com/13446881/71643950-8fc41200-2cd1-11ea-892c-7bb77d2867c7.png)
![2020-01-01_19 01 17](https://user-images.githubusercontent.com/13446881/71643951-8fc41200-2cd1-11ea-94c5-f26e73a6035d.png)

**Comment by Lytexx** [comment]
+1

**Comment by Marco09MC** [comment]
Fixed.
