### ISSUE TITLE
[BUG] Arraylist Rect Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3332]
rect closed
![image](https://user-images.githubusercontent.com/13446881/71644031-08779e00-2cd3-11ea-914a-f4344d90bce7.png)

but when i open rect text's need going little bit left but it dont go rect and texts overlap
![image](https://user-images.githubusercontent.com/13446881/71644037-2fce6b00-2cd3-11ea-8d09-726751197ee0.png)

**Comment by Teals53** [comment]
credits my friend (same nigger from other credit)

**Comment by Marco09MC** [comment]
Fixed.
