### ISSUE TITLE
[IMPROVE]Hypixelboost fly

### ISSUE THREAD

**Issue by Haberno** [CCBlueX/LiquidBounce1.8-Issues#3333]
Hypixel boost fly doesnt do damage to the player when it is activated it has a delay

**To Reproduce**
1.Hypixel skywars
2.Use boostfly and you will see that you take damage around 1-2 seconds after you fly

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by Lytexx** [comment]
there is no delay for me maybe your ping is very high/hypixel is lagging

**Comment by Marco09MC** [comment]
Working fine for me too and I live in Germany... always high ping.
