### ISSUE TITLE
[FEATURE] Close source open source module

### ISSUE THREAD

**Issue by xHackerBey-Egemen** [CCBlueX/LiquidBounce1.8-Issues#3334]
In a server _play.craftrise.tc_ the anticheat checks the liquidbounce's source and u get autoban instantly when u join a game.

So Marco can add a module for that
**Close Source**, when it turned on every codes get obfuscate and when it turned off every codes get deobfuscate.

sorry for bad English.

**Comment by Marco09MC** [comment]
wtf xddd
thats a joke, right?

the server can't detect the liquidbounce source. there is no way doing this.

**Comment by xHackerBey-Egemen** [comment]
idk why but i tried it for a lot times i get ban without any illegal thinks

**Comment by Teals53** [comment]
@Marco09MC he is true

**Comment by xHackerBey-Egemen** [comment]
i have a short video for proof it https://www.youtube.com/watch?v=sP29g28iCgQ

**Comment by Marco09MC** [comment]
yeah but it has nothing to do with opensource or closed source.
there is no way doing this. you can't check for something like that.
please stop they are probably checking something diffrent.
