### ISSUE TITLE
[BUG] LiquidBounce is detected on CraftRise and Intave since b67

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3335]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3334

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/0478db95d4460872077b992713f880235143912c is working fine on Craftrise

**Comment by Teals53** [comment]
> [CCBlueX/LiquidBounce@0478db9](https://github.com/CCBlueX/LiquidBounce/commit/0478db95d4460872077b992713f880235143912c) is working fine on Craftrise
> 
> It seems something is broken in the mixins of liquidbounce.

its b67 so b67 working fine on craftrise now or its different version of b67 ?

**Comment by Marco09MC** [comment]
yeah. the first commit of b67 in the repository is working for me, the offical release version is not working. It seems somewhere in between someone made a huge mistake.

**Comment by Teals53** [comment]
🤔

**Comment by Marco09MC** [comment]
Caused by way how we implemented the GCD Bypass

which caused issues here:
![](https://axolotl.vip/4YjYMCWi?key=3LS6hFBM4Oi6II)

**Comment by Teals53** [comment]
but so what's with this ?

**Comment by Marco09MC** [comment]
I I fixed it.

https://github.com/CCBlueX/LiquidBounce/commit/75586bda3ef3423a4f93d9498b38bd891352334c

**Comment by Teals53** [comment]
you are best
