### ISSUE TITLE
[BUG] Slider Texture missing in Music & Sounds screen

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce1.8-Issues#3336]
**Describe the bug**
The slider texture in the Music & Sounds options screen is not bound and therefore the slider renders incorrectly.

**To Reproduce**
1. Go to the music & sound screen options
2. Observe

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17235016/71645980-0401b400-2cd8-11ea-917f-19a1fb0d09a2.png)

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/079540215d9314c374b224ee0098175a5c7db29f
