### ISSUE TITLE
[FEATURE] KillAura RotationStrafe option

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3338]
**Describe your feature request.**

**Additional context**

**Comment by Teals53** [comment]
what this options do ?

**Comment by Lytexx** [comment]
what does this?

**Comment by SenkJu** [comment]
Strafes into the direction you are facing server-side. Some AntiCheats require this.

**Comment by Teals53** [comment]
> Strafes into the direction you are facing server-side. Some AntiCheats require this.

so its good for bypass anti cheats ? whats change when i open that ? its make aura more bad/legit or ?=

**Comment by Marco09MC** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/d070317105b2a45dae9e50306a9eab4ff4d13611

**Comment by yorik100** [comment]
(Make an option pre/post to killaura and aimbot also)

**Comment by Teals53** [comment]
@Marco09MC whats different pre and post ? can you teach me

**Comment by Marco09MC** [comment]
@yorik100 there is no reason doing this wtf

**Comment by Marco09MC** [comment]
Done.
