### ISSUE TITLE
[FEATURE] Save/load keybind with localautosettings.

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3339]
**Describe your feature request.**
When I save the localautosettings, I want to save all keybinds, so that when I reload them, all keybinds are back again.

**Comment by Teals53** [comment]
liqudbounce already have that ? just use .localautosettings save all

**Comment by superblaubeere27** [comment]
Yes it does

**Comment by Tcm9** [comment]
Okey. Sorry.

**Comment by Tcm9** [comment]
and Thx. ^^
