### ISSUE TITLE
Strafe %

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#334]
Mann soll einstellen können wie stark der Strafe sein soll. (bitte auch bei dem Custom Speed Das strafe% hinzufügen. Und auch bitte nicht mit einem Befehl sondern mit so einer Leiste ( Z.b wie bei Killaura die range. ) also das
Range:4.1
 [-------[]-------]  <--------

**Comment by Marco-MC** [comment]
Ne?
