### ISSUE TITLE
[FEATURE] Nice features to add

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3343]
**Describe your feature request.**
1. An option to cancel hits on bots and friends (Except if NoFriends ON) and teammates (only when Teams is ON)
2. ScriptAPI to get if player is a friend, same to get if a player is a bot (detected by AntiBot)
3. Combat reach disable button

**Additional context**
Would be nice

**Comment by superblaubeere27** [comment]
What does the first mean?

**Comment by yorik100** [comment]
> 
> 
> What does the first mean?

OnAttack -> If target.isBot || target.isBot then event.cancel

**Comment by superblaubeere27** [comment]
Oh sry, I meant the third :o

**Comment by yorik100** [comment]
> 
> 
> Oh sry, I meant the third :o

A button to disable combat reach in reach and only keep building reach on

**Comment by superblaubeere27** [comment]
Imo, those features (except for the second one) aren't really needed. And this issue has a bad format. You should report every feature in it's own issue
