### ISSUE TITLE
[BUG] Scaffold etc affects KillAura RotationStrafe

### ISSUE THREAD

**Issue by xHackerBey-Egemen** [CCBlueX/LiquidBounce1.8-Issues#3344]
Sometimes scaffold is working but sometimes have bugs. if u watch the video u can understand
https://youtu.be/nVuQlDKTOUo

My scaffold settings is:
![scaffoldsettings](https://user-images.githubusercontent.com/59417898/71671935-1550cc00-2d7d-11ea-9574-b2109dc9dc85.PNG)

**Comment by yorik100** [comment]
> Sometimes scaffold is working but sometimes have bugs. if u watch the video u can understand
> https://youtu.be/nVuQlDKTOUo
> 
> My scaffold settings is:
> ![scaffoldsettings](https://user-images.githubusercontent.com/59417898/71671935-1550cc00-2d7d-11ea-9574-b2109dc9dc85.PNG)

Disable killaura

**Comment by xHackerBey-Egemen** [comment]
why i need to disable killaura for make a bridge

**Comment by Teals53** [comment]
maybe its caused by new aura options rotationstrafe
