### ISSUE TITLE
[BUG] Mineplex Autosettings are garbage

### ISSUE THREAD

**Issue by cl0rm** [CCBlueX/LiquidBounce1.8-Issues#3346]
Tested in Cake Wars. Worked very well for several years, however since a ?few weeks? it does not work anymore.

To reproduce this just go into cakewars with the settings enabled. Scaffolding etc works perfectly, however the killaura gets you banned instantly ("banned by Chiss") with the default 5.20 range. Reducing it to below 4.50 (4.44 in my test) and setting it to switch delays the ban ~30 sec. tested with many accs.

I have also noticed that since a few months, there are not only Gwen bans, but also those Chiss bans. They look like modbans, however they are definitely automatically generated. Maybe this mod has enabled a second, experimental anti cheat.

**Comment by yorik100** [comment]
> 
> 
> Tested in Cake Wars. Worked very well for several years, however since a ?few weeks? it does not work anymore.
> 
> To reproduce this just go into cakewars with the settings enabled. Scaffolding etc works perfectly, however the killaura gets you banned instantly ("banned by Chiss") with the default 5.20 range. Reducing it to below 4.50 (4.44 in my test) and setting it to switch delays the ban ~30 sec. tested with many accs.
> 
> I have also noticed that since a few months, there are not only Gwen bans, but also those Chiss bans. They look like modbans, however they are definitely automatically generated. Maybe this mod has enabled a second, experimental anti cheat.

Set reach to 3.4 and predict to max 0.1 min 0.1
