### ISSUE TITLE
[BUG] CustomHUD Coordinats Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3347]
how can i change for one letter ?
![image](https://user-images.githubusercontent.com/13446881/71686371-0df4e700-2dac-11ea-835f-da18bb7a0541.png)

**Comment by xHackerBey-Egemen** [comment]
dOn'T uSe C0OrDiAnEtEs pRoBLeM s0LvEd

**Comment by superblaubeere27** [comment]
@Teals53 This is not a bug report, it is a feature request. The coordinates just aren't rounded.

**Comment by Teals53** [comment]
> @Teals53 This is not a bug report, it is a feature request. The coordinates just aren't rounded.

but its not looks like clear so if its have a option for like simple/advanced mode its pretty good otherwise its not useful in my opinion cuz its just fuck my screen xD

**Comment by superblaubeere27** [comment]
@Teals53 I will take a look at it.

**Comment by superblaubeere27** [comment]
Fixed in CCBlueX/LiquidBounce#18
