### ISSUE TITLE
[FEATURE] CubeCraft simulateinventory in autoarmor and inventory cleaner

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3348]
**Describe your feature request.**
They get you instant banned, maybe make a bypass for CubeCraft

**Additional context**
Was trying a config and got instabanned because I hate openinv

**Comment by DeleteAndInsert** [comment]
works fine for me?

**Comment by yorik100** [comment]
> 
> 
> works fine for me?

I got banned in 2 secs

**Comment by CzechHek** [comment]
SimulateInventory is indeed detected on CubeCraft.

@DeleteAndInsert is probably using InvOpen + SimulateInventory which makes no sense

**Comment by Soulplexis** [comment]
if you use SimulateInventory and InvOpen the server will not receive any inventory packet.

**Comment by CzechHek** [comment]
https://www.youtube.com/watch?v=sCG65BkriKo

Proof that it does bypass if it is coded right

**Comment by CzechHek** [comment]
#3394
