### ISSUE TITLE
Custom speed. Mehr Einstellungen.

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#335]
Es währe schon wenn mehr Einstellungen für Custom dazukommen würden. 

- CustomTimer [--[]---------]

- Custommotion [--[]---------]  ( Custommotion ist wie stark du nach unten geworfen wirst (wie fastfall) z.b. wenn du  Custommotion auf 4 machst (1 ist normal) und gleichzeitig  CustomY auf 5 machst hast du ein Yport.

- CustomStrafe% [--[]---------] (habe ich in einem anderen issues geschrieben)

 - Customdamage  [--[]---------] (wenn aktiviert bekommst du immer regelmässig damage beim laufen. (je wie du es eingestellt hast)) 

- nosprint (wenn aktiviert dann sprintest du nicht mehr beim Speed. (auch wenn sprint aktiviert ist)

**Comment by Marco-MC** [comment]
Ich habe ledeglich CustomTimer geaddet...

**Comment by MaxHD0** [comment]
Custommotion währe noch schön gewesen.
