### ISSUE TITLE
[BUG] localautosettings syntax

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3350]
![image](https://user-images.githubusercontent.com/13446881/71690040-9c6d6680-2db4-11ea-828b-d792024a703e.png)

what this three dot mean ? can u change with the full sytntax ?

**Comment by superblaubeere27** [comment]
You can save it to a file and you can specify what you want to save.
For example:
`.localsettings save asdf all` Will save all states/binds/values to a file names asdf.
`.localsettings save asdf values` Will only save the values to a file names asdf.

`values` = Module settings (Stuff like Scaffold -> Mode)
`binds` = Keybinds
`states` = If the modules are enabled or disabled

**Comment by Teals53** [comment]
if its just have this four option why its have "..." ? three dot mean its have more but not wirted syntax

**Comment by Teals53** [comment]
> You can save it to a file and you can specify what you want to save.
> For example:
> `.localsettings save asdf all` Will save all states/binds/values to a file names asdf.
> `.localsettings save asdf values` Will only save the values to a file names asdf.
> 
> `values` = Module settings (Stuff like Scaffold -> Mode)
> `binds` = Keybinds
> `states` = If the modules are enabled or disabled

thx but i dont ask this dude :=)

**Comment by Marco09MC** [comment]
the ... just means that are able to add more arguments like
`.localsettings save test values binds`

**Comment by Teals53** [comment]
Oh okey thx
