### ISSUE TITLE
[BUG] BowAimbot Broken

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3351]
![image](https://user-images.githubusercontent.com/13446881/71697468-232c3e80-2dc9-11ea-8ebd-692ef07f42f7.png)

its my settings

**Comment by superblaubeere27** [comment]
Can you describe the unwanted behaviour in more detail than *broken*?

**Comment by Teals53** [comment]
basically not working

**Comment by Teals53** [comment]
> Can you describe the unwanted behaviour in more detail than _broken_?

btw welcome back @superblaubeere27 <3

**Comment by Marco09MC** [comment]
Working for me. I don't know what you mean.

**Comment by Teals53** [comment]
> Working for me. I don't know what you mean.

I am playing on craftrise and its not working here why ?

**Comment by superblaubeere27** [comment]
`Silent` is enabled. The BowAimbot aims, but your view isn't changed. You can only see that it is working when you shoot.

**Comment by Teals53** [comment]
no i know what is silent its not aiming people silent or not it doesnt matter

**Comment by Teals53** [comment]
> `Silent` is enabled. The BowAimbot aims, but your view isn't changed. You can only see that it is working when you shoot.

i am not stupit like that dude xD

**Comment by Teals53** [comment]
@Marco09MC btw autoarmor broken in b69 devolopment build

**Comment by superblaubeere27** [comment]
@Teals53 Dude, `broken` is no description of a bug

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/71724586-d3d62480-2e41-11ea-862d-e2139adb8dfe.png)
maybe its reason of it

**Comment by Teals53** [comment]
https://youtu.be/TK71tB3118E

and here is a short video for show that

**Comment by Teals53** [comment]
https://youtu.be/ozpCAQaXYj4

**Comment by superblaubeere27** [comment]
Is the other player a friend or something?

**Comment by Teals53** [comment]
nothing its happens on server in minigames skywars etc

**Comment by Teals53** [comment]
i just record this in singleplayer for showing faster and easier

**Comment by xarissthehalfgod** [comment]
i'm having the same problem, please repair.

**Comment by xHackerBey-Egemen** [comment]
it's same for me too

**Comment by superblaubeere27** [comment]
Can you send us any information about the context this bug appeared in?

**Comment by Teals53** [comment]
video is not enought for that ? how can i give you more information its just not working i open that and trying to shoot enemy but its not aiming SİMPLY not working

**Comment by superblaubeere27** [comment]
Ok if simply not working is the best description we get for it, we can't simply replicate the bug and then we can't fix it simply

**Comment by Teals53** [comment]
i already ask u what can i do more ?

**Comment by superblaubeere27** [comment]
On which server? Which Player? Is this player a friend? Is AntiBot enabled? What modules are enabled in general?

**Comment by Teals53** [comment]
in my server or in craftrise it doesnt matter anti bot enabled or disabled it doesnt matter too which player random player i try that in .panic all as you can see in a video

**Comment by Teals53** [comment]
@kawaiinekololis why ? its still not working

**Comment by Teals53** [comment]
i test this again when b69 relelased if its still not work pls reopen that

**Comment by Teals53** [comment]
just health option is working other ones are broken i test this in latest b69 dev build

**Comment by Teals53** [comment]
Its still not working just health option is working

From Offical Released b69

@kawaiinekololis

**Comment by kawaiinekololis** [comment]
dude health option is working fine.

**Comment by kawaiinekololis** [comment]
https://axolotl.vip/4Xm9t3Kk.mp4?key=AtqxfoYWw2HBMN

**Comment by Teals53** [comment]
i say already this dude

**Comment by Teals53** [comment]
just health option is working

**Comment by Teals53** [comment]
other ones are not working @kawaiinekololis

**Comment by superblaubeere27** [comment]
@Teals53 You aren't able to give us information we would need to replicate this bug. The only information you give us is *BowAimbot is not working* which is not enough. And when somebody doesn't give us the information we need, it's obviously not that critical and likely to be a misstake of the user.

**Comment by Teals53** [comment]
i can share my screen when im using bowaimbot can you add my discord ?
Teals53#1508

**Comment by Teals53** [comment]
from offical b70 still just health option is working direction and distanse still broken...

**Comment by kawaiinekololis** [comment]
and still a you problem

**Comment by Teals53** [comment]
no my friends have same problem too ?
