### ISSUE TITLE
[BUG] Script values are reset if module is enabled before unregistering it (.reload)

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3352]
**Describe the bug**
ClickGUI values, binds of ScriptAPI modules that are enabled when you execute .reload get reset. 
This can possible also lead to random MC crash caused by [this](https://pastebin.com/raw/498hLYUX). (doesn't happen after applying the fix)
The simple fix is to disable the custom module before unregistering it.

**Example**
Take this [script](https://github.com/Shiv3RPolak/turtlCore/blob/master/scripts/AntiAim.js) as an example, if you remove `moduleManager.getModule("AntiAim").state = false;`, it will reset values after .reload

**Additional information:**
 - OS: Win 10 64bit
 - LiquidBounce Build Version b68 (mc launcher)
 - Minecraft Version 1.8.9

**Comment by Marco09MC** [comment]
![](https://axolotl.vip/aTgNru2v?key=0Y5qcZP6Ix5afg)
We are already disabling the module before unregistering it.

**Comment by CzechHek** [comment]
idk what happened, but this was really a thing and disabling all the modules fixed it, but it for some reason doesn't reset now, even tho it got reset yesterday and it also stopped crashing.

wtf

**Comment by SenkJu** [comment]
#3494 Also occurs when the module is disabled.
