### ISSUE TITLE
[FEATURE] Add keep length rotation option to Scaffold

### ISSUE THREAD

**Issue by Marco09MC** [CCBlueX/LiquidBounce1.8-Issues#3359]
**Describe your feature request.**

**Additional context**

**Comment by Teals53** [comment]
What is that ? And value 0 mean infinity ? Its mean how much block your head keep rotate ?

**Comment by CzechHek** [comment]
@Teals53 no

**Comment by Teals53** [comment]
you can tell me what is this instead of writing no ?
