### ISSUE TITLE
[FEATURE] AntiFall / AntiVoid

### ISSUE THREAD

**Issue by Waterbuscus1** [CCBlueX/LiquidBounce1.8-Issues#3362]
**Describe your feature request.**
When falling into the void teleports you back to your original position, just like in other clients.

**Additional context**
Accidentally running into the void and teleporting up to original position.

**Comment by Leejames2305** [comment]
It's call already in the client . 
BugUp

**Comment by Lytexx** [comment]
Yeah but an onlyvoid option would be nice

**Comment by superblaubeere27** [comment]
@Lytexx Ok. I will add it...

**Comment by superblaubeere27** [comment]
I changed the MaxFallDistance to 255. If you set it to this value it is almost guaranteed that there is nothing below in CCBlueX/LiquidBounce#19
