### ISSUE TITLE
[BUG] AutoArmor Broken In b69 Devolopment Build

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3363]

**Comment by superblaubeere27** [comment]
Define *broken*. What happens? What settings are you using?

**Comment by Teals53** [comment]
it doesnt matter test it yourself its not take armors in any settings

**Comment by yorik100** [comment]
It does for me

**Comment by superblaubeere27** [comment]
@yorik100 Are you in creative mode?

**Comment by Teals53** [comment]
> @yorik100 Are you in creative mode?
dude its doesnt matter too xd

**Comment by yorik100** [comment]
> 
> 
> @yorik100 Are you in creative mode?

Oh you changed title, nevermind

**Comment by superblaubeere27** [comment]
Works fine for me even in creative. If you are unable to give use more information we are unable to fix it.

**Comment by Teals53** [comment]
what/how can i give more infos

**Comment by Marco09MC** [comment]
working fine for me 🤔

**Comment by Teals53** [comment]
why im always weird about this issues how its possible

**Comment by Teals53** [comment]
i test this again when b69 relelased if its still not work pls reopen that

**Comment by kawaiinekololis** [comment]
No. You are the only one with this issue! No one else got this issue.

**Comment by Teals53** [comment]
sorry i writed this here wrongly
