### ISSUE TITLE
[BUG] NoSlowBreak Description

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3364]
Describe the bug
when you hover over NoSlowBreak to see a description of what it does its just empty

**To Reproduce**
1. Go to 'clickgui'
2. Hover over 'NoSlowBreak'

Screenshots

Additional information:
 - OS: [e.g. iOS] Windows 10
 - LiquidBounce Build Version [e.g. b61] b68
 - Minecraft Version [e.g. 1.8.9] 1.8.9

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/1cd0b929ca9a1d1c2ea5ae6c268a515e29bdfe24
