### ISSUE TITLE
[BUG] Memory Leak caused by TextureManager

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#3366]
**Describe the bug**
Currently LiquidBounce suffers from a severe memory leak whose cause is not yet known.

Everytime the player respawns or changes the world, memory usage increases by over 100MB and stays there.
Video: https://axolotl.lol/LEvYBvu3.mp4?key=h71JnRWxPQ6gip

The issue does not seem to be caused by a specific module as memory usage also increaes when all modules are disabled.

**To Reproduce**
1. Open LiquidBounce
2. Join a sercer
3. Watch LiquidBounce's memory usage steadily increase over time

**Screenshots**
Screenshots of [Eclipse Memory Analyzer](https://www.eclipse.org/mat/) with LiquidBounce heap dump after playing for several minutes on CubeCraft:
<img src="https://axolotl.us/EKGoZ7EN.png?key=JITkWZatuUoE6J">
<img src="https://axolotl.us/AmNf2pPs.png?key=R1J4aWgf7kkJq6">

Could be caused by FontRenderer:
<img src="https://axolotl.lol/nssHamVT.png?key=N5j2uDmjsIBtdg">
<img src="https://axolotl.vip/ZjKvfoSu.png?key=yPgGtFRrPtDuw2">

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version: b68 (Also happens on older versions)
 - Minecraft Version: 1.8.9

**Comment by superblaubeere27** [comment]
How long was the client running to this point?

**Comment by SenkJu** [comment]
~10 minutes

**Comment by SenkJu** [comment]
### Caused by donator capes

**Comment by superblaubeere27** [comment]
Caused by loading the cape in a new texture everytime it is needed. ![grafik](https://user-images.githubusercontent.com/22642852/71772618-03725300-2f4e-11ea-8e80-82a2e0bf2e48.png)

**Comment by SenkJu** [comment]
Fixed.
