### ISSUE TITLE
[BUG] Spammer cant do client commands

### ISSUE THREAD

**Issue by coolpvpv1** [CCBlueX/LiquidBounce1.8-Issues#3367]
Describe the bug
the spammer module can do /help but it can do stuff like .help .vclip etc etc

To Reproduce
1. Go to spammer
2. make the message .help or some command the client has and it will just say it in chat

Screenshots

Additional information:
 - OS: [e.g. iOS] windows 10
 - LiquidBounce Build Version [e.g. b61] b68
 - Minecraft Version [e.g. 1.8.9] 1.8.9

**Comment by superblaubeere27** [comment]
This is more a feature than a bug. But why would you want to spam client commands?

**Comment by Marco09MC** [comment]
It's a feature.
