### ISSUE TITLE
[FEATURE] Antibot Livingtime/WasInvisible time changeable

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3368]
**Describe your feature request.**
It should be possible to set the time at Livingtime/WasInvisible.

**Comment by superblaubeere27** [comment]
There is no timeing check in `WasInvisible`. But there is one in `LivingTime` (Default: `20 ticks`). But why do you want this?

**Comment by Tcm9** [comment]
At WasInvisible you can add the timeing check.

Why I want this is logical. To bypass bots.

**Comment by yorik100** [comment]
+1

**Comment by whycantiusemyname** [comment]
> There is no timeing check in `WasInvisible`. But there is one in `LivingTime` (Default: `20 ticks`). But why do you want this?

some server will let the enemy invincible
after they respawn so you hit them you get kick

**Comment by superblaubeere27** [comment]
Added.
