### ISSUE TITLE
[BUG] LiquidBounce b68 Performance 20% worse than b55

### ISSUE THREAD

**Issue by ArrowReport** [CCBlueX/LiquidBounce1.8-Issues#3369]
Performance Comparison: b55/b63/b68
https://youtu.be/E9WOhJ2uJq0

**Additional information:**
 - OS: Windows 7
 - LiquidBounce Build Version b68
 - Minecraft Version 1.8.9

**Comment by CzechHek** [comment]
I though that it was 4,16% worse?

Oh, and that test was pretty bad.
