### ISSUE TITLE
[FEATURE] KillAura FailRate Delay (Max/Min)

### ISSUE THREAD

**Issue by DeleteAndInsert** [CCBlueX/LiquidBounce1.8-Issues#3371]

**Comment by Tcm9** [comment]
the fail rate is specified in %. There is no delay. And there is no need for a changing % indicator.

**Comment by DeleteAndInsert** [comment]
> the fail rate is specified in %. There is no delay. And there is no need for a changing % indicator.

Delay with which the division will occur?  Several clients are already using this, for example Sectio.

**Comment by Tcm9** [comment]
If other clients have it, it does not necessarily mean that it is useful. The argument only works for features or designs. With bypasses like this one, it doesn't work. The percentage display is most accurate here. As far as I know, in Endergames the fail rate can't be less than 5%. How exactly are you going to set that with a delay? % is already variable.
