### ISSUE TITLE
InstaPickUp

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#338]
Du sammelst schneller Items auf. (Gut für Bedwars. Da bekommst du nämlich dann alle items.)

(Funkioniert mit packets)

**Comment by SenkJu** [comment]
Ich bin mir relativ sicher, dass das unmöglich ist.

**Comment by Marco-MC** [comment]
Klar geht das?

**Comment by Marco-MC** [comment]
Hoffe ich xd
Ich habe aber eine Ahnung wie es geht glaube.

**Comment by MCmodding4K** [comment]
geht nicht

**Comment by Marco-MC** [comment]
rip

**Comment by MaxHD00** [comment]
doch es geht. Skash hatte es.

**Comment by Brotgeschmack** [comment]
Hatt es aber es funktioniert nicht...
