### ISSUE TITLE
[FEATURE] About Binds

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3385]
I do myself binds files for restore my binds quickly but its not accept my binds if its from renders ?

![image](https://user-images.githubusercontent.com/13446881/71772148-2ead7000-2f57-11ea-9a0a-226aab74775f.png)

![image](https://user-images.githubusercontent.com/13446881/71772152-44229a00-2f57-11ea-8b6e-7114b39d7be1.png)

**Comment by superblaubeere27** [comment]
I removed the restriction to render modules in a PR
