### ISSUE TITLE
[FEATURE]Proxy support

### ISSUE THREAD

**Issue by Lytexx** [CCBlueX/LiquidBounce1.8-Issues#3388]
I dont know why it got discontinued :https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2009
My forum post :https://forum.ccbluex.net/thread.php?id=2346
It would help many people who cant afford vpns and cant just restart there router to get a new ip i think everyone would appreciate this

**Comment by SenkJu** [comment]
#2009 
Avoid duplicates. You knew there was already an issue for it. Why did you open another one?
