### ISSUE TITLE
[FEATURE/BUG (idk)] Autoarmor prefer other protections than Protection

### ISSUE THREAD

**Issue by Shiv3RPolak** [CCBlueX/LiquidBounce1.8-Issues#3389]
Why autoarmor prefer Fire/Projectile/etc protection than normal protection, fix pls

**Comment by superblaubeere27** [comment]
https://github.com/CCBlueX/LiquidBounce/blob/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/AutoArmor.java#L129 🤔

**Comment by yorik100** [comment]
It prefers projectile protection 2 over protection 1 for example

**Comment by Shiv3RPolak** [comment]
it even prefers projectile protection 1 than protection 1

**Comment by superblaubeere27** [comment]
This only occurences when having more than two armor items of the same type and with the same material in your inventory. I know what the error is. Idk if I will rework this weird Ways of finding the best armor

**Comment by superblaubeere27** [comment]
Fixed in CCBlueX/LiquidBounce#27
