### ISSUE TITLE
[FEATURE] Avoid Reflection in EventManager

### ISSUE THREAD

**Issue by Shyrogan** [CCBlueX/LiquidBounce1.8-Issues#3390]
**Describe your feature request.**
There are better alternative to Java reflection when it comes to calling events.
https://stackoverflow.com/questions/19557829/faster-alternatives-to-javas-reflection

Maybe take a look at those solutions to improve performances? (Just a suggestion)

**Comment by Shyrogan** [comment]
There's also BCES from TheCyberBrick https://github.com/LeafClient/BCES

**Comment by superblaubeere27** [comment]
I could make such a event bus, but how do you think of this kinda eventbus?

**Comment by superblaubeere27** [comment]
Performance isn't such a big problem and reflections are just a little part of the time the client is updated.  Making this event bus would add plenty of bugs in the next releases. That's why I'm closing the issue for now, but we can reopen it when we think that we need a new event bus.

**Comment by Shyrogan** [comment]
https://github.com/Shyrogan/Buddy
