### ISSUE TITLE
[BUG] SimulateInventory doesn't send any inventory packets

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3394]
**Describe the bug**
SimulateInventory doesn't do anything differently from nonopeninv, it's in the code but it doesn't send any C16 or C0D packets. That's why it instabans on CubeCraft even if other clients can bypass.

**To Reproduce**
Check what packets are sent when using InventoryCleaner with SimulateInventory.

**[Video](https://ctrlv.tv/video/2020/01/08/19/nNzy.webm)**

**Additional information:**
 - OS: Win 10 64
 - LiquidBounce Build Version b68
 - Minecraft Version 1.8.9

**Comment by superblaubeere27** [comment]
I was completely unable to replicate this bug. In your video only certain packets are printed. May I ask you why?

**Comment by kawaiinekololis** [comment]
It seems SimulateInventory is just implemented for throwing items away and not for sorting

**Comment by kawaiinekololis** [comment]
Fixed.
