### ISSUE TITLE
[FEATURE] What else to improve in the legendary 69 version but the FUCKER? ;P

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3397]
Please add:
-variable tries (it tries to break the bed through blocks a couple of times and if it didn't work it breaks the blocks arround)

-an adjustable fucker range

btw does the selected build range affect to the scaffold?

**Comment by kawaiinekololis** [comment]
> -variable tries (it tries to break the bed through blocks a couple of times and if it didn't work it breaks the blocks arround)
No, sorry.

> -an adjustable fucker range
Added in b69

**Comment by apexCode1337** [comment]
No sorry? xd
