### ISSUE TITLE
KnockBackPlus 

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#340]
Wenn ich einen Spieler Schlage bekommt **er** einen gewaltigen Knockback
(sollte in Vanilla gehen. Fals du nicht weisst wie es funktioniert könnte ich dir ein Client senden.)
_hoffe ich habe den noch_

**Comment by Marco-MC** [comment]
GIEBT ES SCHON:
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/309

**Comment by MaxHD00** [comment]
ja aber das passiert mit mir. das was ich  meine ist das der gegner starken knockback bekommt.

**Comment by Marco-MC** [comment]
Das meinst du... ._.

**Comment by Marco-MC** [comment]
Ich weiß nur das dass mit player packets geht. Ich muss schauen.

**Comment by Marco-MC** [comment]
Wie du aber weißt habe ich aber echt andere Probleme derzeit als so n Kack.

**Comment by MaxHD00** [comment]
Ich weiss. Du musst es ja nicht jetzt machen. PS: kommts voran?

**Comment by SenkJu** [comment]
Velocity horitontal/vertical auf über 1.
