### ISSUE TITLE
[BUG] CustomHUD Effects Out of border (default)

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3401]
i need change position for see that in my screen default settings its ot of border
edit from last update its fixed now its come in my screen default

and it can put this things out of border with changing V, H options but from new update its need impossible
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1674
edit i added video for this bug

**Comment by Teals53** [comment]
and why its looks like broken
![image](https://user-images.githubusercontent.com/13446881/72570799-ec791c80-38ce-11ea-9796-820aaf54b63f.png)

**Comment by Teals53** [comment]
and second bug try to up scale your scoreboard between order its bugged

**Comment by Teals53** [comment]
its not true yet effects still come out of order and bug still working
![image](https://user-images.githubusercontent.com/13446881/73038447-87d83780-3e63-11ea-9794-826fb913d884.png)

**Comment by Teals53** [comment]
FROM B69 SOME OF BUGS ARE FİXED BUT STİLL LAST ONE İS ALİVE

**Comment by Teals53** [comment]
This elements not come back again when its out of border from bug

https://youtu.be/NpB2tjH2qPE

**Comment by Teals53** [comment]
And when i click reset button "effencts" element come out of border
![image](https://user-images.githubusercontent.com/13446881/73039428-126e6600-3e67-11ea-8ed4-5aa1afdc27de.png)

**Comment by kawaiinekololis** [comment]
Make a new issue for the other one and close all fixed issues (in development build - so I don't get confused).

**Comment by Teals53** [comment]
i created new one
