### ISSUE TITLE
[BUG] LiquidChat Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3405]
why its send 3x times ?
![image](https://user-images.githubusercontent.com/13446881/72666739-27da2f00-3a26-11ea-9d9f-6c106c813bea.png)

**Comment by scorpion3013** [comment]
![Discord_2020-01-20_02-24-01](https://user-images.githubusercontent.com/27446646/72692400-f8154f00-3b2b-11ea-85c7-765f926b1c2f.png)
Was only send once.

**Comment by xHackerBey-Egemen** [comment]
"**spoiler kekosu**"

**Comment by Teals53** [comment]
ACUOQYFWYODWDYLDWOYOYWLYFWFYLW
