### ISSUE TITLE
[FEATURE] a little command for

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3407]
sent emptymessage so i not need remember always what i need copy

**Comment by scorpion3013** [comment]
Thats just too useless in general.
Just make a script for it using scriptapi.

**Comment by Teals53** [comment]
How can i do that

**Comment by scorpion3013** [comment]
https://github.com/CCBlueX/LiquidBounce-ScriptAPI/wiki/Getting-started
