### ISSUE TITLE
[BUG] Strange Killaura behavior with the hit vector thing

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#3408]
https://streamable.com/nro7r
settings: https://axolotl.vip/idFxVejY.png?key=Z3tpDEWeKcYH6V

**Comment by scorpion3013** [comment]
Seems to work fine again?
Unable to reproduce again.

**Comment by scorpion3013** [comment]
happend again, cant find a reason why tho

**Comment by scorpion3013** [comment]
has todo with the targetMode switch

**Comment by scorpion3013** [comment]
https://streamable.com/dwp29

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3563
