### ISSUE TITLE
InstaPickUp

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#341]
-InstantPickUP (z.B. bei BedWars : Man steht mit mehreren Leuten an einem Bronze Spawner, und man bekommt immer das Bronze. Nur anlassen solange man die Items versucht zu bekommen Ansonsten aus!)

PS: es funkioniert. der Skash client hatte es. Ich habe es Jedentag auf gomme genutzt.

**Comment by MaxHD00** [comment]
Es gibt sogar ein Haze video

**Comment by Marco-MC** [comment]
Ich frage mich wie das geht... Mit C03PacketPlayer Packets bzw. Timer geht schonmal nicht...
setNoPickupDelay(); Methode aus EntityItem klappt auch nicht, was auch kein Wunder ist... Hm.

**Comment by Marco-MC** [comment]
Nope geht nicht.
Ich habe mir sogar Skash 2.0 runtergeladen, um zu sehen ob das wirklich geht... Nicht mal in Skash geht es.
Ich denke das ging ledeglich auf AAC 1.9.10 irgendwie...
