### ISSUE TITLE
CMD-Block command

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#342]
Creative: du erhällst einen Comandblock der schon ein command hat!

du musst .cmdblock [befehl] machen um ihn zu bekommen. (der im extra inventar hat keine befehle drin)

**Es funkioniert sogar noch auf der 1.11.2 zudem nervt es alles mit give du machen. Mein MC ist gecrasht als ich mir ein commandblock geben wollte.**

Habe es grade probiert. Es geht auf einem 1.8.9 Server mit Spigot.
macht es so .cmdblock [befehl]    das mit give verwirrt total Genau wie beim firework. legt es bitte in das creative menü. Ich will doch nicht ständig den code holen.

**Comment by MaxHD00** [comment]
PS: lasst euch zeit. ihr müsst es ja nicht jetzt anschauen. Ich habe erst 40% durch. es kommen ja noch 30 vorschläge XD

**Comment by SenkJu** [comment]
Man kann CMD Block Minecarts nicht mit NBT Tags commands geben

**Comment by Marco-MC** [comment]
Use .give
