### ISSUE TITLE
[BUG] Fix Notifications element default position

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#3420]

**Comment by Teals53** [comment]
and when i click reset button notification button not come
![image](https://user-images.githubusercontent.com/13446881/73077570-7d548700-3ed1-11ea-8288-c1f6a49955b3.png)

**Comment by Teals53** [comment]
@kawaiinekololis 
idk u see my post if i dont ping you ?
