### ISSUE TITLE
Strafe % (AAC bypass)

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#343]
Mann soll einstellen können wie stark der Strafe sein soll. (bitte auch bei dem Custom Speed Das strafe% hinzufügen. Und auch bitte nicht mit einem Befehl sondern mit so einer Leiste.) [-----[]----]

Wenn man die % auf 50 stellt bypasst es AAC.
(es war um 50% genau weiss ich es grade nicht.)

**Comment by Marco-MC** [comment]
Nein.
