### ISSUE TITLE
[BUG] Few more issues with CustomHUD

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3435]
[Video](https://ctrlv.tv/video/2020/01/25/18/WaWY.webm)

**Additional information:**
 - OS: Win 10 64bit
 - LiquidBounce Build Version: Latest b70 DEV
 - Minecraft Version: 1.8.9

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3423

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3442

**Comment by superblaubeere27** [comment]
Fixed in CCBlueX/LiquidBounce@94d113b
