### ISSUE TITLE
[BUG] Fucker Instant should also show the target block

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3438]
**Describe your feature request.**
https://streamable.com/mmijq Fix thruwalls around
Color the block that it's destroying in red (instant mode)

**Additional context**

**Comment by kawaiinekololis** [comment]
> https://streamable.com/mmijq Fix thruwalls around

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3439
