### ISSUE TITLE
Fucker Reach setting & FastBow speed setting

### ISSUE THREAD

**Issue by zikdriver** [CCBlueX/LiquidBounce1.8-Issues#344]
- Fucker Block Reach (Das man einstellen kann, von wv. Blöcken man das Bett baut.
- FastBow Speed (Shoot per Second? Geschwindigkeit beim Schießen einstellbar machen.)

**Comment by Crax9999** [comment]
Ihr könntet einen "reverse velocity" machen (sehr gut gegen angel schwitzer)

**Comment by SenkJu** [comment]
@Crax9999 .velocity horizontal -1, .velocity vertical -1

**Comment by maxhd000000000** [comment]
als ob ich alles mit befehlen mache.
Ich will das in der Gui.  (das geht echt 10 minuten)

**Comment by maxhd000000000** [comment]
Velocity (in der gui) soll von -5 bis +5 gehen. bitte. Da kann man alles relativ schnell einstellen. bzw mann kann schnell bypasses finden. ohne 100 mal
.veloc.velocity vertical 0.8 hem geht nicht
.velocity vertical 0.81 hem geht nicht
.velocity vertical 0.82 hem geht nicht zu machen.

**Comment by SenkJu** [comment]
Wenn wir das in der GUI machen, dann wird der Slider extrem ungenau werden, da sich die Länge von ihm nivht verändert. Wie oft musst du bitte die Velocity auf -5 setzen, dass du dafür nicht schnell den Command eingeben kannst?

**Comment by SenkJu** [comment]
Und du wirst niemals mit einem Slider dazu in der Lage sein, bis auf zwei Stellen hinter dem Komma genau einzustellen. Zumindest nicht bei unserem Client.

**Comment by maxhd000000000** [comment]
naja ok

**Comment by MaxHD00** [comment]
Die Fastbow idee finde ich gut. Aber die Fucker Reach. Naja. Wieso muss ich die Range verringern? Es bypasst überall. Und Range verlängern geht sicher nicht.

**Comment by Crax9999** [comment]
Macht bitte auch einen breakspeed auf manchen servern werde ich gekickt weil der fucker instant ist

**Comment by SenkJu** [comment]
Fucker baut mit Vanilla Speed ab, wenn 'Instant' deaktiviert ist. @Crax9999
