### ISSUE TITLE
[CUSTOMHUD] Change to modern default scoreboard

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#3446]
![](https://axolotl.vip/Untj9VTa?key=QRIpQvItt4BLKZ)
![](https://axolotl.vip/JArbS5c2?key=AD5IjnMnqPJFmO)
![](https://axolotl.vip/px9MuY14?key=ZSLbXoNUQOkrS4)

**Comment by kawaiinekololis** [comment]
I'll change it back to minecraft default because of senk ju

**Comment by Teals53** [comment]
just add a customization and stay default so everyone can change that what he want

**Comment by kawaiinekololis** [comment]
@Teals53 I already did?

**Comment by Teals53** [comment]
anyway np dude i writed that before test latest build <3
