### ISSUE TITLE
[BUG] Why the fuck are you guys adding useless shit fr

### ISSUE THREAD

**Issue by Haberno** [CCBlueX/LiquidBounce1.8-Issues#3448]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by Leejames2305** [comment]
What ? Which are useless stuff ?

**Comment by Teals53** [comment]
?

**Comment by xHackerBey-Egemen** [comment]
everything useful in liquidbounce

**Comment by SenkJu** [comment]
Do this again and you will be banned from opening new issues.

**Comment by apexCode1337** [comment]
He's right the killaura is completely useless if you got as many pvp skills as I do

**Comment by Teals53** [comment]
xD
