### ISSUE TITLE
[BUG] Autoarmor Bug

### ISSUE THREAD

**Issue by xHackerBey-Egemen** [CCBlueX/LiquidBounce1.8-Issues#3453]
**Describe the bug**
i have 2 armors, enchanted and not but autoarmor not wears enchanted armor
already i describe it on my video watch it https://www.youtube.com/watch?v=MTj0ntOFA1M

**Additional information:**
 - OS: Win7
 - LiquidBounce Build Version b70 *DEVELOPMENT*
 - Minecraft Version 1.8.9

**Comment by kawaiinekololis** [comment]
It's because auto armor is searching for the armor with the best protection and not... stuff like feather falling.

**Comment by yorik100** [comment]
No please, don't focus enchanted stuff over more protective stuff or make an option forit

**Comment by kawaiinekololis** [comment]
@yorik100 no the issue is just that the auto armor takes armor of the same protection level without comparing their enchantments (boots with feather falling of the same type like one without would still be better than nothing 🤔 ).
