### ISSUE TITLE
[BUG] arraylist saturation and brightness bug ShareEmbedEmail

### ISSUE THREAD

**Issue by xHackerBey-Egemen** [CCBlueX/LiquidBounce1.8-Issues#3455]
**Describe the bug**
just watch the video bottom

**Screenshots**
https://youtu.be/t0KK3WErIZQ

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by kawaiinekololis** [comment]
I'm not able to reproduce it myself but I see the problem.
