### ISSUE TITLE
[BUG] AutoArmor should take armor with more durabillity when armor has the same dmg reduction

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3457]
**Describe the bug**
https://streamable.com/m7l6a (tried with invOpen on)

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by apexCode1337** [comment]
Yeah there's a problem if you inventory is completely full that autoarmor and invcleaner get confused and don't do anything

**Comment by kawaiinekololis** [comment]
A golden helmet and a iron helmet has the same damage reduction so... yeah auto armor just ignores the iron one. Maybe it would be a good idea to add a max durabillity condition to the comparator so it's going to take the iron one instead of the gold one.

**Comment by yorik100** [comment]
> A golden helmet and a iron helmet has the same damage reduction so... yeah auto armor just ignores the iron one. Maybe it would be a good idea to add a max durabillity condition to the comparator so it's going to take the iron one instead of the gold one.

How about the leather helmet?

**Comment by kawaiinekololis** [comment]
probably because you moved the items around idk
shouldn't happen and I'm not able to reproduce it myself so yeah

**Comment by apexCode1337** [comment]
But please make it optional it could cause problems in some gamemodes
