### ISSUE TITLE
[FEATURE] Show Enchants In CustomHUD For Armor Elements

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3458]
Like my old issues when i suggest this for nametags

its bump too

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1735

**Comment by superblaubeere27** [comment]
How would you think of this? 🤔

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3460

**Comment by Teals53** [comment]
@kawaiinekololis lol actually i open this issue early than him xD

**Comment by kawaiinekololis** [comment]
yeah I don't care. The other issue has more description.

**Comment by Teals53** [comment]
:3
