### ISSUE TITLE
World Downloader + rejoin button im Pausemenü. 

### ISSUE THREAD

**Issue by maxhd000000000** [CCBlueX/LiquidBounce1.8-Issues#346]
(Es gibt keine forge version von World Downloader.) (ich habe 1,5 stunden gesucht.)

bitte fügt ein World Downloader hinzu.
(Im Pausemenü (esc im spiel) soll es noch die Möglichkeit geben die Welt runterzuladen. )
(PS: fügt bitte noch Rejoin hinzu. Kann hilfreich sein.)

**Comment by SenkJu** [comment]
Der World Downloader is natürlich eine Mod. Das hier habe ich nach zehn Sekunden googlen gefunden: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2520465-1-11-1-10-1-9-4-1-8-9-world-downloader-mod-create

**Comment by maxhd000000000** [comment]
Ich war da schon. lesen!

Forge
There is no forge version of World Downloader. However, you can use the Liteloader version with Forge, which will generally work. Look on the liteloader thread for instructions on how to install with forge, and then insert the .litemod file as described above.

**Comment by maxhd000000000** [comment]
bei mir ging es nicht. als ich es mit force verbunden habe.

**Comment by SenkJu** [comment]
Das geht. Du machst irgendetwas falsch. Ich habe den World Downloader schon mit Forge verwendet.

**Comment by maxhd000000000** [comment]
ok.
