### ISSUE TITLE
[BUG] Unbearable lag on some servers, apparently somehow gets fixed after a period of time (has happened on multiple servers now)

### ISSUE THREAD

**Issue by freaky767** [CCBlueX/LiquidBounce1.8-Issues#3461]
**Describe the bug**
Sometimes (not often) you get like real unbearable (connection) lag, talking about like 5k ms, (note, this has nothing to do with my internet, other servers work just fine, others lag like hell and get fixed over time)

**To Reproduce**
It is completely random (I think), main server where this constantly happens for me is cubecraft.

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version B69 (has happened on b68, b67 pretty sure)
 - Minecraft Version 1.8.9

**Comment by superblaubeere27** [comment]
I never had such an issue. It's either your internet or the server itself... If it really is a client bug and you know how to replicate it, tell us. We can't fix bugs when we aren't able to replicate them :/

**Comment by CzechHek** [comment]
That's a CubeCraft issue.

**Comment by freaky767** [comment]
idk if its really server, or a client issue, but im certain it isnt my internet
also not certain on how to replicate it, i could show you a video of it happening though

**Comment by superblaubeere27** [comment]
I never have this problem. Why are you sure that it isn't your internet's fault?

**Comment by CzechHek** [comment]
CubeCraft has connection problems to some Spain vpns for example. You can see everyone moving, but your ping is like 50k.

**Comment by freaky767** [comment]
@superblaubeere27 because it has happened to me so many times on cubecraft, and i know this because on other servers, it works just fine, whereas on cubecraft you can see people moving (slowly) but you get like massive connection lag (even without vpn, i know my internet isnt at fault for this)

**Comment by superblaubeere27** [comment]
I never had any problems with my connection and cubecraft. How do you know that this is LiquidBounce's fault? I will close this issue until there is any evidence that it is an issue associated with LiquidBounce.
