### ISSUE TITLE
[BUG] InventoryCleaner only keeps item with highest dmg

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3462]
**Describe the bug**
Some update in b70 made InventoryCleaner drop other tools than the one with highest dmg, it will only keep sword / axe / pickaxe depending on which has the highest dmg.

[Video](https://ctrlv.tv/video/2020/01/26/20/QeSU.webm)

**Additional information:**
 - OS: Win 10 64 bit
 - LiquidBounce Build Version: Latest b70
 - Minecraft Version: 1.8.9

**Comment by superblaubeere27** [comment]
InventoryCleaner needs a remake... I will fix that bug...

**Comment by CzechHek** [comment]
Here [are](https://ctrlv.tv/video/2020/01/27/18/HMkj.webm) some [more](https://ctrlv.tv/video/2020/01/27/15/O7b3.webm) bugs

**Comment by superblaubeere27** [comment]
The first "*bug*" is actually `ItemDelay` just set it to `0`. I made an issue for the second one #3465

**Comment by CzechHek** [comment]
> The first "_bug_" is actually `ItemDelay` just set it to `0`. The second one looks like unwanted behaviour I made an issue for it. #3465

It shouldn't wait for item every time, it should manipulate items which has been in the inventory for the time first, then wait for the other ones.

**Comment by superblaubeere27** [comment]
@CzechHek Nope. `ItemDelay` is the time since the item has created aka. time since the item has been added to the inventory.
