### ISSUE TITLE
[FEATURE] Overarmor

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3464]
**Describe your feature request.**
You can put any item you want in the armor slot in Creative mode. 
(It is only possible in creative mode)

you should be able to enable/disable this feature with .overarmor on/off.

You do not need to create a module for this.

**Additional context**
![image](https://user-images.githubusercontent.com/31276706/73199182-a58ff000-4134-11ea-848d-d1f5f18514e8.png)
![image](https://user-images.githubusercontent.com/31276706/73199269-d3753480-4134-11ea-927c-0d6d8d546bb3.png)
![image](https://user-images.githubusercontent.com/31276706/73199298-e25be700-4134-11ea-96fe-b7af1e1e1f4e.png)

**Comment by CzechHek** [comment]
sure

**Comment by superblaubeere27** [comment]
I think this should be a fun module

**Comment by Tcm9** [comment]
lul no. But it is also not supposed to be a module at all. That was simply always turned on. And if you want to turn it off, then there is a command for it.

**Comment by Tcm9** [comment]
Or it is always to be off, and with the command you can switch it on.
whatever, but plz no module.

**Comment by Teals53** [comment]
its same module or command its doesnt matter

**Comment by Tcm9** [comment]
No.
Module:
![image](https://user-images.githubusercontent.com/31276706/73215375-4b9f2280-4154-11ea-9197-f9e1697a4d5e.png)
![image](https://user-images.githubusercontent.com/31276706/73215402-578ae480-4154-11ea-9f17-cc2b73854386.png)
Command:
![image](https://user-images.githubusercontent.com/31276706/73215558-97ea6280-4154-11ea-9919-fb093aa390c6.png)

**Comment by Tcm9** [comment]
The arraylist and the Clickgui is already completely full. If you force such little things into there, it gets even worse.

**Comment by superblaubeere27** [comment]
Too many fun modules... 
![grafik](https://user-images.githubusercontent.com/22642852/73217898-1f39d500-4159-11ea-929d-0ef68dac7233.png)
It only makes sense to make it as module since it is toggelable and it can be found by a normal user.

**Comment by apexCode1337** [comment]
There should be a command to toggle the visibility of each module in the array list

**Comment by Tcm9** [comment]
plz no module.

**Comment by dddkj** [comment]
module can bind a key

**Comment by apexCode1337** [comment]
Please make 2 modules out of it xd

**Comment by Tcm9** [comment]
then nothing at all

**Comment by Tcm9** [comment]
i do it myself with a script as command.

**Comment by Teals53** [comment]
@Tcm9 can you share this with me ?
