### ISSUE TITLE
[BUG] AutoArmor ignores delay settings

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3466]
**Describe the bug**
AutoArmor always takes everything instantly probably since the InventoryCleaner being able to move items instantly update.

[Video](https://ctrlv.tv/video/2020/01/27/19/hyJc.webm)

**Additional information:**
 - OS: Win 10 64bit
 - LiquidBounce Build Version Latest b70
 - Minecraft Version 1.8.9

**Comment by superblaubeere27** [comment]
I fixed the bug in the past. For some reason I reverted the changes 🤔
