### ISSUE TITLE
[BUG] Block Blacklist Not Working

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3467]
For İnventoryCleaner

**Comment by superblaubeere27** [comment]
Block Blacklist only prevents InvCleaner from putting a blacklisted block into a hotbar slot that is specified to have a block in it. This works fine. If there is a problem with that, comment and then I'm going to reopen the issue.

**Comment by Teals53** [comment]
i already talking about that its still put my hotbar tnt or enchant table etc @superblaubeere27 
from last b70 build

**Comment by Teals53** [comment]
dude..

**Comment by superblaubeere27** [comment]
@Teals53 Tell me how to replicate it and I will fix it.

**Comment by Teals53** [comment]
its basically still take blacklist items in ur hotbar ?

**Comment by superblaubeere27** [comment]
It does not

**Comment by Teals53** [comment]
sorry i dont understand wdym "replicate" ?

**Comment by superblaubeere27** [comment]
Replicate = doing it again.

**Comment by Teals53** [comment]
a short video enought for that ?

**Comment by superblaubeere27** [comment]
Yes

**Comment by Teals53** [comment]
yes i know im stupit here is blacklisted blocks list

public static final List<Block> BLOCK_BLACKLIST = Arrays.asList(Blocks.enchanting_table, Blocks.chest, Blocks.ender_chest, Blocks.trapped_chest,
            Blocks.anvil, Blocks.sand, Blocks.web, Blocks.torch, Blocks.crafting_table, Blocks.furnace, Blocks.waterlily, Blocks.dispenser,
            Blocks.stone_pressure_plate, Blocks.wooden_pressure_plate, Blocks.noteblock, Blocks.dropper);

so this

![image](https://user-images.githubusercontent.com/13446881/73468476-e6d30a80-4395-11ea-9ae0-0ff4b7bac010.png)


and until now, I thought TNT was blaclisted but its not in this list..

sometimes i do some retarded shits ik

**Comment by Teals53** [comment]
this block is good for add blacklist ? its same like other ones
![image](https://user-images.githubusercontent.com/13446881/73468923-9f00b300-4396-11ea-8f3d-5749b573350f.png)
