### ISSUE TITLE
[BUG] StorageESP color bug

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3470]
**Describe the bug**
Outline and WireFrame StorageESP are coloring hotbar and hand.

[Video](https://ctrlv.tv/video/2020/01/28/22/PBM7.webm)

**Additional information:**
 - OS: Win 10 64bit
 - LiquidBounce Build Version Latest b70
 - Minecraft Version 1.8.9

**Comment by superblaubeere27** [comment]
I fixed it locally, I will publish my changes later

**Comment by Tcm9** [comment]
are you using opengl >4.0?
(press f3. On the right is the opengl version)

**Comment by superblaubeere27** [comment]
@Tcm9 Yes I do
