### ISSUE TITLE
[FEATURE]Autodisable

### ISSUE THREAD

**Issue by Lytexx** [CCBlueX/LiquidBounce1.8-Issues#3471]
disables the modules you selected after you died

**Comment by Teals53** [comment]
for what

**Comment by superblaubeere27** [comment]
y tho?

**Comment by Lytexx** [comment]
?

**Comment by CzechHek** [comment]
Just use CubeCore and HypixelCore, oh wait

**Comment by Tcm9** [comment]
fly?

**Comment by superblaubeere27** [comment]
@Tcm9 Why don't you just use a keybind?

**Comment by Leejames2305** [comment]
@superblaubeere27 Maybe he means that client auto disable module like Killaura when a you get killed ? ( Useful on Skywars tho.. , so it won't spam hitting compass )

**Comment by Lytexx** [comment]
> @superblaubeere27 Maybe he means that client auto disable module like Killaura when a you get killed ? ( Useful on Skywars tho.. , so it won't spam hitting compass )

yes thank you

**Comment by Lytexx** [comment]
Guess thats a no
