### ISSUE TITLE
[FEATURE] this script is useful and can be addable ?

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3472]
https://forum.ccbluex.net/thread.php?id=2421

**Comment by Lytexx** [comment]
+1

**Comment by superblaubeere27** [comment]
*tHiS sCrIpT* is not a proper description of a new feature. Please specify what you expect.

**Comment by Teals53** [comment]
idk i just ask its useful for more options in superknockback

**Comment by superblaubeere27** [comment]
So please reformulate your feature request.

**Comment by Teals53** [comment]
for what

**Comment by superblaubeere27** [comment]
Say what you want. Describe the feature.

**Comment by Teals53** [comment]
i just ask if this script have some useful addable things for more options in superknockback it can be useful if merged into lb

**Comment by dddkj** [comment]
He means add more mode for superknockback

**Comment by superblaubeere27** [comment]
@Teals53 What kinda options do you want?

**Comment by Teals53** [comment]
idk just add if its have any useful things xd

**Comment by superblaubeere27** [comment]
ok. Then this issue has a bad format. If you think there is anything that can be added, make a feature request. If you want to discuss if there is a good feature please use the forum.

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/73442186-5ed50c80-4365-11ea-9cf4-511c3f17f365.png)

**Comment by superblaubeere27** [comment]
@Teals53 An issue is a feature request, a bug report or a question. This is not a place for this kinda discussion. Make an explicit feature request or your issue will be closed. A feature request with *tHiS sCrIpT* is not explicit. And if you want to have options added to `SuperKnockback`, you have to say what option you want. Just saying that it needs more options is not a feature request.

**Comment by Teals53** [comment]
i already just ask you IF THIS SCRIPT HAVE ANY USEFUL ADDABLE THİNGS u can add I JUST ASK "ASK" 
i dont test this script and i dont know what this script do I JUST ASK YOU if this have any useful thing for more options about superknockback and if u add this people can reach that without using script

now u understand me ?

**Comment by superblaubeere27** [comment]
Yes, but this is GitHub not Reddit, the Forum or Discord. Discuss it anywhere else and if you have an idea for a feature, request it here.

**Comment by Teals53** [comment]
i not do this first time, u and marco are different

**Comment by superblaubeere27** [comment]
@Teals53 You are. Look at for example guava. I wish you much luck with finding an accepted issue of this kind. https://github.com/google/guava/issues
