### ISSUE TITLE
[FEATURE]Scaffold should place blocks in air with SameY

### ISSUE THREAD

**Issue by je5442804** [CCBlueX/LiquidBounce1.8-Issues#3474]
**Describe your feature request.**
I mean when player toggle Scaffold with SameY,player place blocks and jump in air at the same time.
Player can place blocks in air 

**Additional context**
Some AntiCheat can not check player whether Scaffold when it does. So I think it's useful and faster to Scaffold

**Comment by superblaubeere27** [comment]
I am not sure if this option is really needed.

**Comment by NetherStar64** [comment]
He means that when you are jumping while using scaffold, the blocks are not being placed higher than when you started.

**Comment by CzechHek** [comment]
Already added, close this.
