### ISSUE TITLE
[FEATURE] downscaffold

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3475]
Maybe you've seen it already in other clients it just scaffolds downwards. It's a useful feature and bypasses on many anticheats even aac. There could be a mode too that saves you if you fall down because of a block glitch or something.

**Comment by Teals53** [comment]
duplicated
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3063

**Comment by superblaubeere27** [comment]
Dublicate

**Comment by apexCode1337** [comment]
So why isn't it in the client already? xd

**Comment by superblaubeere27** [comment]
@apexCode1337 Because it won't bypass and there was no situation in the last 2 years where I could have needed this.

**Comment by apexCode1337** [comment]
It works even on aac if you don't use it too much
