### ISSUE TITLE
Scaffold Expand lenght setting

### ISSUE THREAD

**Issue by maxhd000000000** [CCBlueX/LiquidBounce1.8-Issues#348]
bei Expand baut man immer 5 Blöcke.
bitte eine leiste hinzufügen wieviele Blöcke er vorbauen soll
[---[]-----] 1-6

**Comment by maxhd000000000** [comment]
ps: bitte mit der GUI und keinem Befehl.

**Comment by maxhd000000000** [comment]
Bitte noch entfernen, dass Scaffold mit Fackeln, Leitern, Sand, Kies, Ambossen und Redstonefackeln baut.

**Comment by WistarWolf** [comment]
Das es mit alles was kein kein ganzer Block ist (Fackeln etc), mit allem was fallen kann (Sand etc) und mit allem was aktivierbar ist nicht baut.

**Comment by Marco-MC** [comment]
Jede Setting die wir einbauen wird automatisch in die ClickGUI eingebaut nur so als info, daher brauchst du nicht immer dieses "ps: bitte mit der GUI und keinem Befehl."
Wie fauel kann man eigentlich sein, um einen Befehl zu benutzen?

**Comment by MaxHD00** [comment]
Ich schreibe es lieber weil man sehr viele sachen mit . Befehlen macht die man nicht kennt. Ich mache nie . Befehle. (Ok ausser .autosettings, .bind  und .enchant*

Anderer client und ich hoffe bald auch bei diesem client.

**Comment by Marco-MC** [comment]
Added.
Subcommand to modify expand value also added.
