### ISSUE TITLE
[REMOVE] Remove some old fly modes

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#3481]
- [ ] Hypixel
- [ ] OtherHypixel
- [ ] InfinityCubeCraft
- [ ] InfinityVCubeCraft
- [ ] KillSwitch

**Comment by apexCode1337** [comment]
No pls don't remove anything the many features and bypasses are the best things in liquidbounce.

**Comment by kawaiinekololis** [comment]
Yeah but these are server specific bypasses and they are not going to bypass anymore... we can't keep every bypass.

**Comment by Teals53** [comment]
F

**Comment by apexCode1337** [comment]
ok

**Comment by Tcm9** [comment]
nice.
Is the gomme fly still working?
You could also remove it?

**Comment by apexCode1337** [comment]
No the gomme fly's still work as a bypass for something else on aac
