### ISSUE TITLE
[FEATURE] Rename some fly modes

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#3483]
- [x] AAC -> AAC1.9.10
- [x] AACv3 -> AAC3.0.5
- [x] Gomme -> AAC3.1.6-Gomme

**Comment by Tcm9** [comment]
But the gomme fly no longer works on gomme. 
Or does it?

**Comment by superblaubeere27** [comment]
@Tcm9 The fly worked when Gomme used AAC 3.1.6
