### ISSUE TITLE
[BUG] please improve sameY

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3485]
I got some problems with sameY and I found out a little "bug". I know that the option should work like that but i think it can be improved a little bit. The problem is that it just saves the one coordinate you're starting with. but if you're legit jumping you jump 1.25 block high so it wont build in that range and you will fall down even if you use sameY in vanilla while jumping. please add a customizable height or something. Please let the selected build range affect to the scaffold too.

**Comment by Lytexx** [comment]
+1

**Comment by apexCode1337** [comment]
Please add it to the milestone

**Comment by superblaubeere27** [comment]
You have to enable `SafeWalk` in the `Scaffold` options

**Comment by apexCode1337** [comment]
No thats not the problem it falls down even if safewalk is enabled. Please trust me I can show you a video tomorrow if you want

**Comment by apexCode1337** [comment]
I know my description is a little bit shitty but I'm sure you know what I mean

**Comment by je5442804** [comment]
if possible,it is better to give a video

**Comment by apexCode1337** [comment]
at the first two clips i show the problem and in the last one i use a lowhop that jumps just 1.003 blocks high so you want fall down with it.

https://streamable.com/iytli

**Comment by superblaubeere27** [comment]
You disabled `AirSafe`. What a surprise that it won't work in mid air xD

**Comment by apexCode1337** [comment]
Come on you see the problem. It would work great if it would build in the normal jump height. It works with a lowhop too with disabled safewalk and airsafe

**Comment by apexCode1337** [comment]
In the video I enabled fly at the highest point while jumping and it didn't build.

**Comment by apexCode1337** [comment]
I already improved sameY a little bit with a script but that's not enough I need a little help from you guys please.

**Comment by apexCode1337** [comment]
It's not that hard to code so please just reopen it. It would be very helpful and a big improvement

**Comment by apexCode1337** [comment]
https://youtu.be/LmQWqfmi2zg

Here you can see it works with a lowhop but sometimes there are blockglitches because sameY is buggy.

**Comment by superblaubeere27** [comment]
This is obviously not a bug. You could make a feature request for expanding the y-search-size

**Comment by apexCode1337** [comment]
That's exactly what I did. I can do a new issue with a correct title.
