### ISSUE TITLE
[FEATURE] please add a killaura option that keeps aiming and blocking at a target even if the hurttime is set to 0 and the target is higher

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3489]
could you make an option where the killaura only attack players if they are in a specific hurttime?

**Comment by Teals53** [comment]
i think this guide good for you and its answer your question too :3 
https://forum.ccbluex.net/thread.php?id=1301

**Comment by Lytexx** [comment]
He knows what it does it just doesnt really make sense together with cps option

**Comment by Lytexx** [comment]
Weirdchamp

**Comment by apexCode1337** [comment]
sorry xd
