### ISSUE TITLE
[FEATURE] TheAltening reconnect button using set TheAltening key in menu after getting kicked

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3490]
**Describe your feature request.**
A clear and concise description of what the problem is.
I'm always frustrated when I need to exit server list click TheAltening and generate

**Additional context**
Any other context

**Comment by Lytexx** [comment]
If you have an api token set just press reconnect with random alt it will generate an account and use it

**Comment by yorik100** [comment]
> If you have an api token set just press reconnect with random alt it will generate an account and use it

It'll not take an alt from the alt list?

**Comment by Lytexx** [comment]
> > If you have an api token set just press reconnect with random alt it will generate an account and use it
> 
> It'll not take an alt from the alt list?

No

**Comment by superblaubeere27** [comment]
Already implemented. Press `Reconnect with random Alt` and you will get a new account from the altening
