### ISSUE TITLE
[FEATURE] NoFall Legit Option

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3491]
Its put water into your falling block then take it back

**Comment by Teals53** [comment]
also legit option for zoot to like when u r burning do same thing

**Comment by Teals53** [comment]
actually i just looking up cubecore and its have more options for fastuse and fastclimb its useful for add into the liquidbounce ?

**Comment by Teals53** [comment]
and superblaubeere27 pls dont say me same stuff from other issue thx

**Comment by Teals53** [comment]
also this script for more derp options 
![image](https://user-images.githubusercontent.com/13446881/73583385-de1c2a80-44a2-11ea-9a1a-1cc63bf65140.png)

**Comment by Tcm9** [comment]
#2892

**Comment by Tcm9** [comment]
#2124

**Comment by Tcm9** [comment]
#1090

**Comment by Tcm9** [comment]
the idea is not new

**Comment by Lytexx** [comment]
I dont really understand what you want just use the scripts lol

**Comment by Teals53** [comment]
> I dont really understand what you want just use the scripts lol

its better if lb already have this so everyone can use that without using script

**Comment by superblaubeere27** [comment]
Dublicate x3. For the second one, you can just use invcleaner and make it put water buckets into slot 5, press 5 and rightclick the best block. This feature is not really needed

**Comment by superblaubeere27** [comment]
Third one is actually ok, but we decided that list issues are invalid in general since they are hard to handle. When we find some, we tell you to make issues for every feature you want, label it as invalid and close it. If you want to have the third feature in the client, please create a new one

**Comment by Teals53** [comment]
@superblaubeere27 which one ?

**Comment by superblaubeere27** [comment]
> 
> 
> actually i just looking up cubecore and its have more options for fastuse and fastclimb its useful for add into the liquidbounce ?
> 
> ![image](https://user-images.githubusercontent.com/13446881/73583325-9f867000-44a2-11ea-9d98-7a2f01e2ea33.png)
> ![image](https://user-images.githubusercontent.com/13446881/73583342-b036e600-44a2-11ea-9f00-7484003aef38.png)
> ![image](https://user-images.githubusercontent.com/13446881/73583350-b88f2100-44a2-11ea-8bcb-55201a382f77.png)

**Comment by Teals53** [comment]
why u dont use this issues for that ? and want a new one for what ?

**Comment by superblaubeere27** [comment]
@Teals53 Because I can't say in my comment `Updated XYZ, fixes #3491`, if I just fixed/implemented one of the 20 suggestions. And it is a usage of Issues that is not intended
