### ISSUE TITLE
[BUG] .reload clears binds

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#3494]
**Describe the bug**
Apparently reloading the client clears binds of script modules again.

**Comment by kawaiinekololis** [comment]
working for client modules. might be just a problem with script modules?

**Comment by CzechHek** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/68
https://github.com/CCBlueX/LiquidBounce/pull/69

**Comment by CzechHek** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/69

**Comment by SenkJu** [comment]
> [CCBlueX/LiquidBounce#69](https://github.com/CCBlueX/LiquidBounce/pull/69)

Does not seem to fix this problem.
