### ISSUE TITLE
[FEATURE] Improve Killaura RotationStrafe

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3495]
**Describe your feature request.**
Based on your clientside rotations and the move keybinds you press, out of the 8 possible directions to do, find the closest one

Example : You're hitting a target that is behind you, you walk forward, actual RotationStrafe will make you go towards your enemy. Based on the fact that you press the forward key and the fact that you're looking backwards, it should go backwards. If there is an enemy behind you and you press forward (example), then walk backwards (backwards which is at the opposite of the enemy) so you'll walk forward on your screen while you'll be walking backwards server sided (without sprinting obviously)

**Additional context**

**Comment by yorik100** [comment]
Bump

**Comment by superblaubeere27** [comment]
This feature is useless for the average user. Basically just adding trash to `KillAura` which already has enough options.

**Comment by yorik100** [comment]
> This feature is useless for the average user. Basically just adding trash to `KillAura` which already has enough options.

Not useless at all, more than not useless, have you ever tried to move properly with killaura RotationStrafe? You can't really do that but it's easy to fix that without losing the purpose of RotationStrafe

**Comment by superblaubeere27** [comment]
Ok, sry, I had the wrong idea. But this is not how `RotationStrafe` is supposed to work.

**Comment by yorik100** [comment]
> Ok, sry, I had the wrong idea. But this is not how `RotationStrafe` is supposed to work.

It is but you can make it the way out of the 8 possible directions it goes the closest possible direction where you want to go, if a player looks forward while attacking backwards and try to go forward the actual RotationStrafe will make the player go backward when it could've simply went backwards (while respecting the possible movements from AAC movement grid)

**Comment by Lytexx** [comment]
please add it its annoying to use it how it is right now

**Comment by yorik100** [comment]
+1
