### ISSUE TITLE
[FEATURE] TeleportHit Aura

### ISSUE THREAD

**Issue by fuckingnigga** [CCBlueX/LiquidBounce1.8-Issues#3497]
So since you have a TeleportHit that already works on quite a few servers, I was wondering if you could add it so that it automatically hits players up to 40+ blocks away from you. Add a cps, range, throughwalls etc. settings like you have on killaura, and I think that it would be great.

**Comment by fuckingnigga** [comment]
Also maybe a Lock feature if you do make this happen (so it locks on a particular player until you kill that player, turn it off or die).

**Comment by Tcm9** [comment]
teleporthit is not a killaura. If you hit too fast, you can be kicked fast. Likewise, if the opponent suddenly runs between a wall, the teleportaura misses too.
i would recommend you simply aimbot and trigger in addition to teleporthit. 
You can increase the range with .aimbot range 150.
I once created 1 issue about aimbot and trigger.

**Comment by superblaubeere27** [comment]
Dublicate. The original issue is in german.  #321

**Comment by Tcm9** [comment]
you can realize your idea by binding teleporthit, aimbot, range and trigger to the same key.
Then you give in the chat:
.reach combatreach 150 and
.aimbot range 150

to save all this you can 
.localautosettings save tphit all
enter.

**Comment by Tcm9** [comment]
finish :D

**Comment by Tcm9** [comment]
But you will soon find that the constant beating has its problems. I can therefore recommend you to simply increase your range on Aimbot. That should do it.
