### ISSUE TITLE
[FEATURE] VanishAlert?

### ISSUE THREAD

**Issue by fuckingnigga** [CCBlueX/LiquidBounce1.8-Issues#3498]
So, I was wondering if It's possible to get a module that alerts you in the bottom right corner if a player is vanished like sigma does, as it would be very useful for small servers with bad anticheat to know when staff are on. I know that it may confuse bots (like mineplex's) to be vanished, however I think it would be a great module and I would always keep it on while on small servers.
(Sorry for using other clients for reference)

**Comment by superblaubeere27** [comment]
Dublicate #3049
