### ISSUE TITLE
Smooth Scrolling in ClickGUI

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#35]

**Comment by superblaubeere27** [comment]
Warum?

**Comment by MrGcGamer** [comment]
kommt noch was?

**Comment by BlackHawk2306** [comment]
🤔

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2659

Ich close den Issue hier einfach mal, weil Smooth Scrolling reinkommt sobald ich eine komplett neue ClickGUI mache.
