### ISSUE TITLE
[FEATURE] Aimbot Silent setting

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3501]
**Describe your feature request.**
When i turn on silent, the aimbot looks at each player without the player noticing (like bowaimbot silent)
The opponent the Aimbot currently has selected should have markers.

**Comment by Tcm9** [comment]
in connection with #3502 you can use your own Killaura with each module.

**Comment by Tcm9** [comment]
#2418

**Comment by Soulplexis** [comment]
i already suggested it they dont want to add it

**Comment by superblaubeere27** [comment]
Why would you want to have this feature? Everyone is able to see the Aimbot, except for you.

**Comment by kawaiinekololis** [comment]
wtf? aimbot is mostly for legit cheating and I see no reason to add a silent mode.
