### ISSUE TITLE
[FEATURE] Trigger Range

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3502]
**Describe your feature request.**
You should be able to set the range of trigger

**Comment by superblaubeere27** [comment]
Trigger triggers when there is something your mouse is over. And for lower ranges... Where would you need it?

**Comment by Tcm9** [comment]
you can create a killaura with any range adapted for modules. This is also how #3497 can work

**Comment by superblaubeere27** [comment]
This is not the sense of this module.

**Comment by Tcm9** [comment]
also TP aura != teleport hit aura.

With TP-Aura you teleport around the player and hit him all the time. (on a short range)

TeleportHit Aura is teleport hit only in connection with Killaura. So that the player attacks the opponent over a great distance.

**Comment by Tcm9** [comment]
k, i see you can change the range from Trigger with range. Well then the module is really not necessary here.

**Comment by superblaubeere27** [comment]
TPHit Aura is a bad idea, since it would cause bad packet spam

**Comment by Tcm9** [comment]
i know. That's why I wrote him a letter on how to make it happen. After that, he'll only use teleporthit and aimbot.
