### ISSUE TITLE
[FEATURE]bowaimbot Switch target

### ISSUE THREAD

**Issue by whycantiusemyname** [CCBlueX/LiquidBounce1.8-Issues#3503]
when you use bowaimbot and is on direction mode, you aim a enemy and you change your direction want aimbot to aim another enemy,but it doesnt change

**Comment by Tcm9** [comment]
You could add that when you sneak that it changes the target.

**Comment by whycantiusemyname** [comment]
i think it can just aim the closest enemy at your direction. that's better

**Comment by superblaubeere27** [comment]
This isn't the purpose of the Direction mode. You can just disable BowAimbot and look around to find another target
