### ISSUE TITLE
[BUG] .give bug

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3504]
**Describe the bug**
when I type .give, it replaces an item that I have. And if my inventory is empty, then he says the inventory is full

**To Reproduce**
use .give

**Screenshots**
![image](https://user-images.githubusercontent.com/31276706/73609303-9265a000-45cc-11ea-90c6-6c5039e5cd3c.png)
![image](https://user-images.githubusercontent.com/31276706/73609319-a8736080-45cc-11ea-84e0-0ad6c07964e3.png)
![image](https://user-images.githubusercontent.com/31276706/73609324-bd4ff400-45cc-11ea-90c1-9e941c5bc409.png)
![image](https://user-images.githubusercontent.com/31276706/73609343-e07aa380-45cc-11ea-933d-3af5886ea6f0.png)

**Additional information:**
 - OS: Windows
 - LiquidBounce Build Version B70
 - Minecraft Version 1.8.9

**Comment by yorik100** [comment]
Add .give infinite chat lenght

**Comment by Tcm9** [comment]
That already exists @yorik100
