### ISSUE TITLE
[FEATURE] Civefinder

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3505]
**Describe your feature request.**
You can see the caves and mines.
So it is easier to find caves to farm faster at SpeedUHC.

**Additional context**
![image](https://user-images.githubusercontent.com/31276706/73609593-8d562000-45cf-11ea-9141-0142d7d97105.png)
![image](https://user-images.githubusercontent.com/31276706/73609601-a5c63a80-45cf-11ea-8073-ea70e195a087.png)

**Comment by superblaubeere27** [comment]
I's called X-Ray

**Comment by Tcm9** [comment]
No. Cavefinder != Xray
