### ISSUE TITLE
[FEATURE] Get font for ScriptAPI

### ISSUE THREAD

**Issue by dddkj** [CCBlueX/LiquidBounce1.8-Issues#3507]
**Describe your feature request.**
value.createFont("Font", Fonts.font40);
etc

**Additional context**

**Comment by SenkJu** [comment]
Since LiquidBounce is now open source you can directly use LiquidBounce classes.
https://forum.ccbluex.net/thread.php?id=2473

```java
var Fonts = Java.type("net.ccbluex.liquidbounce.ui.font.Fonts");
this.onRender2D  = function(event) {
    Fonts.font40.drawString("This is a text", 100, 100, 0xccff33)
}
```

**Comment by dddkj** [comment]
> Since LiquidBounce is now open source you can directly use LiquidBounce classes.
> https://forum.ccbluex.net/thread.php?id=2473
> 
> ```java
> var Fonts = Java.type("net.ccbluex.liquidbounce.ui.font.Fonts");
> this.onRender2D  = function(event) {
>     Fonts.font40.drawString("This is a text", 100, 100, 0xccff33)
> }
> ```

You don't know what I mean
I want to use custom font to draw string
but this one can only use LiquidBounce's font

**Comment by dddkj** [comment]
I want a opition to get custom font renderer

**Comment by SenkJu** [comment]
#3032
