### ISSUE TITLE
Fastbreak fast

### ISSUE THREAD

**Issue by maxhd000000000** [CCBlueX/LiquidBounce1.8-Issues#351]
Es soll einen Instant Modus geben
Und vielleicht noch einen schnellerern Modus. der jetzige Fastbreak ist 0.1 schneller. (hat man mindestens das Gefühl

**Comment by Marco-MC** [comment]
WASD=?VJG
FAD
BG
ADF
GASDF
G
SDFG
DFG

**Comment by Marco-MC** [comment]
CivBreak.
