### ISSUE TITLE
[FEATURE] SuperSecretSettings not working

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3515]
**Describe your feature request.**
A module that lets you select which effect in "Super Secret Settings" you want . currently super secret settings don't work because they disable when you turn off the menu.

**Additional context**

**Comment by Tcm9** [comment]
Lol the Super Secret Settings doesn't work.
Btw, if you set them, they reset when you go out of the options menu.

**Comment by Tcm9** [comment]
You don't need a module, you only have to repair the Super Secret Settings.

**Comment by whycantiusemyname** [comment]
Super Secret Settings just a visual effect.so repair Super Secret Settings can do what?

**Comment by Soulplexis** [comment]
is it worthy of putting super secret settings into it's own module?

**Comment by Haberno** [comment]
> **Describe your feature request.**
> A module that lets you select which effect in "Super Secret Settings" you want . currently super secret settings don't work because they disable when you turn off the menu.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

Exactly, Why do you need this?

**Comment by Soulplexis** [comment]
> > **Describe your feature request.**
> > A module that lets you select which effect in "Super Secret Settings" you want . currently super secret settings don't work because they disable when you turn off the menu.
> > **Additional context**
> > Add any other context or screenshots about the feature request here.
> 
> Exactly, Why do you need this?

Ａｅｓｔｈｅｔｉｃ

**Comment by kawaiinekololis** [comment]
Probably caused by the HUD Blur option. I'm gonna fix it.
# Confirmed

**Comment by kawaiinekololis** [comment]
https://axolotl.vip/4tkPyJUv.mp4?key=CL7mMWvRxcsPBW HUD Blur is not going to affect the super secret settings anymore :)
