### ISSUE TITLE
[BUG]LiquidBounce Crash

### ISSUE THREAD

**Issue by MrCreeper2046** [CCBlueX/LiquidBounce1.8-Issues#3516]
**Describe the bug**
在某些服务器，LiquidBounce被崩溃，并且Sigma、Skid等其他客户端却没有崩溃，服务器ip地址:play.mcyc.win、mc233.cn这些服务器在你注册/登录后传送中会把LiquidBounce崩溃

Crash log: [crash-2020-02-05_11.48.40-client.txt](https://github.com/CCBlueX/LiquidBounce1.8-Issues/files/4157329/crash-2020-02-05_11.48.40-client.txt)

**To Reproduce**

**Screenshots**

**Additional information:**
 - OS: [e.g. iOS] Windows 10
 - LiquidBounce Build Version [e.g. b61] b70
 - Minecraft Version [e.g. 1.8.9] 1.8.9

**Comment by whycantiusemyname** [comment]
its only on B70? i can normally play these server on other version
只在B70么？其他版本都正常

**Comment by whycantiusemyname** [comment]
![2020-02-05_12 48 54](https://user-images.githubusercontent.com/60563852/73812006-31c9a380-4816-11ea-9159-ad6d6d8f00a7.png)
this is a screenshot on play.mcyc.win and i don crash 
这是在游戏世界我不崩溃

**Comment by whycantiusemyname** [comment]
![2020-02-05_12 54 17](https://user-images.githubusercontent.com/60563852/73812118-a7357400-4816-11ea-9ec5-2bba6ec73323.png)
and its mc233.cn i don crash
mc233也不蹦

**Comment by MrCreeper2046** [comment]
我还试着删掉了除LiquidBounce B70外的所有mod(InputFix v2, Optifine L5)，结果还是这样

**Comment by whycantiusemyname** [comment]
You can try close all module 
你试试关掉全部功能进去

**Comment by MrCreeper2046** [comment]
我试试

**Comment by MrCreeper2046** [comment]
哦，我进去了，看来确实是某些功能的问题

**Comment by whycantiusemyname** [comment]
capture a screenshot of your all enabled module
截图你的功能我看看

**Comment by MrCreeper2046** [comment]
可刚才我都关了

**Comment by whycantiusemyname** [comment]
那你先开功能⑧ 开到崩溃就大概知道了

**Comment by MrCreeper2046** [comment]
哦

**Comment by MrCreeper2046** [comment]
知道了!是NameProtect

**Comment by MrCreeper2046** [comment]
NameProtect导致游戏崩溃

**Comment by whycantiusemyname** [comment]
你改一下这个假名的名称看看还会不会崩溃

**Comment by MrCreeper2046** [comment]
没有加颜色字符也会崩溃

**Comment by MrCreeper2046** [comment]
![image](https://user-images.githubusercontent.com/60681944/73817169-42cde100-4825-11ea-88e7-1e31436a244b.png)

**Comment by whycantiusemyname** [comment]
Let me try try

**Comment by whycantiusemyname** [comment]
你的假名开了那几个选项 皮肤保护和全部玩家名字保护都没开吗

**Comment by MrCreeper2046** [comment]
只有皮肤保护

**Comment by whycantiusemyname** [comment]
复现成功 这是真的
NameProtect SkinProtect option can crash LB

**Comment by MrCreeper2046** [comment]
好吧，我试试关掉皮肤保护?

**Comment by MrCreeper2046** [comment]
关掉不会崩溃

**Comment by Teals53** [comment]
Nice nuke plans xD

**Comment by SenkJu** [comment]
Please provide details about this crash in English.

**Comment by MrCreeper2046** [comment]
NameProtect module setting "SkinProtect" well crash LiquidBounce On some servers(play.mcyc.win mc233.cn)

**Comment by superblaubeere27** [comment]
I am going to fix that one...
