### ISSUE TITLE
[BUG] Broken distance calculation, here is the code for proper one

### ISSUE THREAD

**Issue by Shiv3RPolak** [CCBlueX/LiquidBounce1.8-Issues#3517]
calculation reach check is wrong, my bad, here is code that works and is accurate:
`function getFixedDist(entity) {
    var x = Math.sqrt(Math.pow(mc.thePlayer.posX - entity.getEntityBoundingBox().minX,2)) < Math.sqrt(Math.pow(mc.thePlayer.posX - entity.getEntityBoundingBox().maxX,2)) ? Math.sqrt(Math.pow(mc.thePlayer.posX - entity.getEntityBoundingBox().minX,2)) : Math.sqrt(Math.pow(mc.thePlayer.posX - entity.getEntityBoundingBox().maxX,2));
    var y = Math.sqrt(Math.pow(mc.thePlayer.posY - entity.getEntityBoundingBox().minY,2)) < Math.sqrt(Math.pow(mc.thePlayer.posY - entity.getEntityBoundingBox().maxY,2)) ? Math.sqrt(Math.pow(mc.thePlayer.posY - entity.getEntityBoundingBox().minY,2)) : Math.sqrt(Math.pow(mc.thePlayer.posX - entity.getEntityBoundingBox().maxX,2));
    var z = Math.sqrt(Math.pow(mc.thePlayer.posZ - entity.getEntityBoundingBox().minZ,2)) < Math.sqrt(Math.pow(mc.thePlayer.posZ - entity.getEntityBoundingBox().maxZ,2)) ? Math.sqrt(Math.pow(mc.thePlayer.posZ - entity.getEntityBoundingBox().minZ,2)) : Math.sqrt(Math.pow(mc.thePlayer.posX - entity.getEntityBoundingBox().maxX,2));
    var result = Math.sqrt(x*x + y*y + z*z);
    return result;
}`

**Comment by yorik100** [comment]
@kawaiinekololis

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce/blob/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/extensions/PlayerExtension.kt

**Comment by Shiv3RPolak** [comment]
> https://github.com/CCBlueX/LiquidBounce/blob/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/extensions/PlayerExtension.kt

that one is broken, thats why im giving fixed code

**Comment by kawaiinekololis** [comment]
yeah

**Comment by Lytexx** [comment]
> > https://github.com/CCBlueX/LiquidBounce/blob/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/extensions/PlayerExtension.kt
> 
> that one is broken, thats why im giving fixed code

i think he means you should make a pull request

**Comment by yorik100** [comment]
Fix

**Comment by aftery142** [comment]
Only the corners? Doesn't seem very accurate to me.
Well, here is the code that I use in my old private client, if anyone wants it (in java ofc, no js 4 u).
![Untitled](https://user-images.githubusercontent.com/41885049/74084149-a0b92d80-4a9e-11ea-96c4-f5203d45c9ef.png)
`
    public static double getDistanceAccurate(Entity ent) {
        Vec3 eyes = Minecraft.getMinecraft().thePlayer.getPositionEyes(0);
        Vec3 pos = getNearestPointBB(eyes, ent.getEntityBoundingBox());
        double xDist = Math.abs(pos.xCoord - eyes.xCoord);
        double yDist = Math.abs(pos.yCoord - eyes.yCoord);
        double zDist = Math.abs(pos.zCoord - eyes.zCoord);
        return Math.sqrt(xDist * xDist + yDist * yDist + zDist * zDist);
    }
    public static Vec3 getNearestPointBB(Vec3 eye, AxisAlignedBB box) {
        double[] origin = {eye.xCoord, eye.yCoord, eye.zCoord};
        double[] dest_mins = {box.minX, box.minY, box.minZ};
        double[] dest_maxs = {box.maxX, box.maxY, box.maxZ};
        for (int i = 0; i < 3; i++) {
            if (origin[i] > dest_maxs[i]) origin[i] = dest_maxs[i];
            else if (origin[i] < dest_mins[i]) origin[i] = dest_mins[i];
        }
        return new Vec3(origin[0], origin[1], origin[2]);
    }
`

**Comment by yorik100** [comment]
> 
> 
> Only the corners? Doesn't seem very accurate to me.
> ![Untitled](https://user-images.githubusercontent.com/41885049/74084149-a0b92d80-4a9e-11ea-96c4-f5203d45c9ef.png)
> Well, here is the code that I use in my old private client, if anyone wants it (in java ofc, no js 4 u).
> edit: sorry about the formatting, that's github, not me.
> `public static double getDistanceAccurate(Entity ent) { Vec3 eyes = Minecraft.getMinecraft().thePlayer.getPositionEyes(0); Vec3 pos = getNearestPointBB(eyes, ent.getEntityBoundingBox()); double xDist = Math.abs(pos.xCoord - eyes.xCoord); double yDist = Math.abs(pos.yCoord - eyes.yCoord); double zDist = Math.abs(pos.zCoord - eyes.zCoord); return Math.sqrt(xDist * xDist + yDist * yDist + zDist * zDist); } public static Vec3 getNearestPointBB(Vec3 eye, AxisAlignedBB box) { double[] origin = {eye.xCoord, eye.yCoord, eye.zCoord}; double[] dest_mins = {box.minX, box.minY, box.minZ}; double[] dest_maxs = {box.maxX, box.maxY, box.maxZ}; for (int i = 0; i < 3; i++) { if (origin[i] > dest_maxs[i]) origin[i] = dest_maxs[i]; else if (origin[i] < dest_mins[i]) origin[i] = dest_mins[i]; } return new Vec3(origin[0], origin[1], origin[2]); }`

Could you make a pull request? So it's fixed faster https://github.com/CCBlueX/LiquidBounce/blob/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/extensions/PlayerExtension.kt

**Comment by aftery142** [comment]
> Could you make a pull request? So it's fixed faster https://github.com/CCBlueX/LiquidBounce/blob/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/extensions/PlayerExtension.kt

I can't actually, I completely suck at Kotlin and I don't plan to learn it either. But you can rewrite it if you want.

**Comment by yorik100** [comment]
> 
> 
> > Could you make a pull request? So it's fixed faster https://github.com/CCBlueX/LiquidBounce/blob/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/extensions/PlayerExtension.kt
> 
> I can't actually, I completely suck at Kotlin and I don't plan to learn it either. But you can rewrite it if you want. _ew kotlin_

I can try to do that but I'm not sure if xCoord, yCoord, ... are a thing in LiquidBounce/Kotlin or idk
