### ISSUE TITLE
[FEATURE] .toggle module on/off

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3518]

**Comment by Tcm9** [comment]
the idea is basically good, but adding two new commands seems strange to me. 
You could simply extend the .toggle command.
e.g.
.toggle fly on
.toggle fly off

**Comment by apexCode1337** [comment]
Yes it was just an suggestion. Your idea is great

**Comment by SenkJu** [comment]
Added sub-command for enabling or disabling modules
```
.toggle <module> [on/off]
```
