### ISSUE TITLE
[FEATURE] FileSpammer

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3523]
Just a file option into spammer and a txt file from Lb settings folder for that
Also its need work with bypass (>h383ueh<)
https://forum.ccbluex.net/thread.php?id=837
https://forum.ccbluex.net/thread.php?id=1830
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1139
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1950

**Comment by Teals53** [comment]
bumpestia

**Comment by superblaubeere27** [comment]
Dublicate x2 #1950 #1139

**Comment by SenkJu** [comment]
https://forum.ccbluex.net/thread.php?id=837

**Comment by Teals53** [comment]
> Dublicate x2 #1950 #1139



> https://forum.ccbluex.net/thread.php?id=837

as you can see i already put this issues and other links here so i know that but all other one is already closed why u closed this too ?
