### ISSUE TITLE
[BUG] AltManager Have INSANE LAG AND HEAVY

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3525]
from last b71 build

**Comment by Teals53** [comment]
no just because my acc is flagged and hidden.. i lost 1 milestoned issues sad

**Comment by superblaubeere27** [comment]
@Teals53 Nope. You should just stop reporting useless features xD You should see this in our perspective ;D

**Comment by Teals53** [comment]
> @Teals53 Nope. You should just stop reporting useless features xD You should see this in our perspective ;D

xd
