### ISSUE TITLE
[BUG] About Optifine Fast Render And ESP Modules Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3526]
When i open fastrender from video settings and select specifiy options from ESP modules

Result:
 ItemESP--> "ShaderOutline" Option
![image](https://user-images.githubusercontent.com/13446881/74065853-dc081d80-4a06-11ea-9037-e1b72333542f.png)

Esp--> "Outline" Option
![image](https://user-images.githubusercontent.com/13446881/74065165-4ddf6780-4a05-11ea-93f6-582a8024046b.png)

StorageESP-->ShaderGlow & ShaderOutline
![image](https://user-images.githubusercontent.com/13446881/74070170-66ee1580-4a11-11ea-8372-2299fb362c6e.png)
StorageESP-->Outline
![image](https://user-images.githubusercontent.com/13446881/74070196-7f5e3000-4a11-11ea-91fb-ee63c1f8e015.png)

And if this bugged options is enabled u cant change Fastrender on/off position

Other Options Not Have Any Problems

**Comment by Teals53** [comment]
bumperia

**Comment by superblaubeere27** [comment]
The ESP is just completely incompatible with it. There is no real way of making this work.

**Comment by Teals53** [comment]
> The ESP is just completely incompatible with it. There is no real way of making this work.

so there is no way to fix that ? thats sad
