### ISSUE TITLE
[BUG] LiquidBounce latest devbuild problems

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3527]
**Describe the bug**
Gigantic lags in alts menu sometimes

**Comment by superblaubeere27** [comment]
Ok. How to replicate it?

**Comment by yorik100** [comment]
> Ok. How to replicate it?

Log in with a premium account (it doesn't lag when logged with altening acc)

**Comment by superblaubeere27** [comment]
What you described is the client waiting for the Authentification Service to respose it's request. If your connection is bad, you have to wait some time. It is intended to work in the way it does now.

**Comment by yorik100** [comment]
> 
> 
> What you described is the client waiting for the Authentification Service to respose it's request. If your connection is bad, you have to wait some time. It is intended to work in the way it does now.

https://streamable.com/0pwwi

**Comment by SenkJu** [comment]
Fixed.
