### ISSUE TITLE
[FEATURE] clearinv command

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3530]
**Describe your feature request.**
If you type .clearinv or .clearinventory, then your inventory should be dropped except for the armor.

If you enter .clearinv all or .clearinventar all, the armor should also be dropped.

The drop speed must not be instant, but it can be fast.

If the dropspeed should be instant, then you should be able to enter 
.clearinv instant or .clearinventory instant

**Comment by aftery142** [comment]
why?

**Comment by Tcm9** [comment]
Because.

**Comment by superblaubeere27** [comment]
Why? Implementing this would just be trashing the client with useless features
