### ISSUE TITLE
[FEATURE] more Fastbow bypasses

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3531]
**Describe your feature request.**
please add 2 new fastbow modes.
-AAC
-NCP

There must be a way to shoot arrows faster than legit.

**Comment by aftery142** [comment]
im pretty sure that requires sending c03s, which can be detected

**Comment by yorik100** [comment]
> im pretty sure that requires sending c03s, which can be detected

You can prob shoot as fast as fastuse eat things
Same for AAC as fast as AAC fastuse (will flag tho)

**Comment by aftery142** [comment]
> 
> 
> > im pretty sure that requires sending c03s, which can be detected
> 
> You can prob shoot as fast as fastuse eat things
> Same for AAC as fast as AAC fastuse (will flag tho)

ye pretty sure u can, but the question here is why

**Comment by yorik100** [comment]
> > > im pretty sure that requires sending c03s, which can be detected
> > 
> > 
> > You can prob shoot as fast as fastuse eat things
> > Same for AAC as fast as AAC fastuse (will flag tho)
> 
> ye pretty sure u can, but the question here is why

Spambow other cheaters

**Comment by Tcm9** [comment]
> > > im pretty sure that requires sending c03s, which can be detected
> > 
> > 
> > You can prob shoot as fast as fastuse eat things
> > Same for AAC as fast as AAC fastuse (will flag tho)
> 
> ye pretty sure u can, but the question here is why

Because!

**Comment by aftery142** [comment]
> 
> 
> > > > im pretty sure that requires sending c03s, which can be detected
> > > 
> > > 
> > > You can prob shoot as fast as fastuse eat things
> > > Same for AAC as fast as AAC fastuse (will flag tho)
> > 
> > 
> > ye pretty sure u can, but the question here is why
> 
> Spambow other cheaters

*gets flagged*

**Comment by superblaubeere27** [comment]
Saying `ThErE mIgHt Be A ByPaSs FoR fAsTbOw` isn't the purpose of an issue ._.
