### ISSUE TITLE
[BUG] Fucker range

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3535]
**Describe the bug**
I se it to 10 and this happens https://streamable.com/olzjj

**Comment by aftery142** [comment]
Don't set it to 10 maybe??? (more question marks here)

**Comment by yorik100** [comment]
> 
> 
> Don't set it to 10 maybe??? (more question marks here)

![image](https://user-images.githubusercontent.com/16320315/74102164-41602980-4b41-11ea-9af6-1f3efb59c4d8.png)

**Comment by apexCode1337** [comment]
xd

**Comment by apexCode1337** [comment]
If liquidbounce got a bug just don't use liquidbounce

**Comment by gitvitox** [comment]
I really don't see the bug here.

**Comment by yorik100** [comment]
> I really don't see the bug here.

Then you are blind

**Comment by aftery142** [comment]
> > I really don't see the bug here.
> 
> Then you are blind

.killaura range 50

**Comment by gitvitox** [comment]
> > I really don't see the bug here.
> 
> Then you are blind

This isn't even a bug report. You showed off a Video where you set the Bedfucker range to 10. Okay, what do you think will happen? A range of ten is clearly unreachable. So this isn't a bug.

**Comment by leumasme** [comment]
I think he is talking about the hand only swinging when he stands in a specific spot @gitvitox @yorik100 correct?

**Comment by superblaubeere27** [comment]
@leumasme This is the Wall-Detection of Fucker.

**Comment by kawaiinekololis** [comment]
I don't know why you even would try to ... set the range to 10 ... but anyway... gonna fix it.

**Comment by kawaiinekololis** [comment]
Reason:
![](https://axolotl.vip/tuq5sfrD?key=4e0b1TLBTYHvbV)

The roations are not able to find a working corner in a range of 4 blocks, so it just blocks the execution.

**Comment by kawaiinekololis** [comment]
https://axolotl.vip/1FmsUJXF.mp4?key=gg4333j1keiYqX
fixed
