### ISSUE TITLE
[FEATURE] sameY improvement

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3536]
The problem is that sameY prevents the scaffold from building if you're over the coordinate you started with but if you're legit jumping you jump 1.25 blocks high. That's why you will fall down even if you use sameY in vanilla while jumping. 

- **Please let the scaffold build with sameY at any height.**

- **Please let the selected build range affect to the scaffold too.**

Here is a video to better understand the problem (In the last clip in the video I used a lowhop that jumps 1.03 blocks high so you fall down rarely.):

https://streamable.com/iytli

_**Edit:**
 I don't think this change could lead to new problems for other users. And even if it does it would be very simple to reproduce sameY like it is at the moment in a script._

**Comment by apexCode1337** [comment]
Please add it to the milestone it's very important

**Comment by apexCode1337** [comment]
Oh that was fast thank you <3

**Comment by apexCode1337** [comment]
Could someone do this please? I still really need it. :(

**Comment by kawaiinekololis** [comment]
SameY is now going to use the block location instead of the player location. Should be much better now.
https://axolotl.us/y3GVPKfEje5KQw/ADAP5VfG.mp4

**Comment by apexCode1337** [comment]
No it didn't fix it :(

**Comment by apexCode1337** [comment]
The problem is that the scaffold won't build if you are higher then 1 block. But it should build even if you're at 1.5 blocks or higher

**Comment by kawaiinekololis** [comment]
Should work. I'll have to try it again.

**Comment by apexCode1337** [comment]
Please fix it in the final b72
