### ISSUE TITLE
[FEATURE] aimbot improve (basically just bumping that aimbot improve update that a lot of people wanted)

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3537]
**Describe your feature request.**
Some servers detect killaura but not aimbot (even with low settings) but you still end up being banned
1. Aimbot min and max speed
2. Aimbot with center disabled doesn't properly go inside of the enemy's hitbox, it's a bit off
3. Vertical and horizontal speed
4. Aimassist like aiming (if possible)
(5. Fix range calculation)
6. Predict option with min and max
(7. Silentmode)
(8. Throughwallsrange)

**Additional context**
LiquidBounce has one of the most powerful aimbot and the most undetectable but it's been forgotten and underestimated for a long time

**Comment by 6alpha9** [comment]
Im having trouble with intave anticheat.
Even if i use aimbot with turnspeed 1 im getting banned

**Comment by yorik100** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3382
https://forum.ccbluex.net/thread.php?id=350

**Comment by superblaubeere27** [comment]
You know our restriction on List issues. You can make such a post in the community forum to discuss, but GitHub is only for specific instructions what to implement.

1, 2, 8 wouldn't be bad features. 3, 5, 7 are unnecessary.

**Comment by apexCode1337** [comment]
Maybe some things that maybe are unnecessary but if they take just 1 minute to code it's better to add them. The more features and options the better. That's why liquidbounce is such a good client and community project.
