### ISSUE TITLE
[FEATURE] Killaura blockmode

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3538]
**Describe your feature request.**
Some ACs detect NCP autoblock, make a vanilla autoblock that doesn't unblock before hitting
Make an option to stop blocking the tick where you attack too for servers that blocks vanilla and NCP autoblocks

**Comment by aftery142** [comment]
NNNo.

**Comment by apexCode1337** [comment]
Yes pls

**Comment by aftery142** [comment]
>  Some ACs detect NCP autoblock, make a vanilla autoblock that doesn't unblock before hitting
Not unblocking before hitting will make the hit not register.

> Make an option to stop blocking the tick where you attack too for servers that blocks vanilla and NCP autoblocks
I believe LB already does this.

**Comment by yorik100** [comment]
> > Some ACs detect NCP autoblock, make a vanilla autoblock that doesn't unblock before hitting
> 
> Not unblocking before hitting will make the hit not register.
> 
> > Make an option to stop blocking the tick where you attack too for servers that blocks vanilla and NCP autoblocks
> 
> I believe LB already does this.

LB unblocks attack and block the same ticks
There should be an option to only attack while blocking (it would register still, on ACs that don't block that), would be way better for vanilla servers with packet limiters
There should be an option not to block during an attack tick, unblock and attack then after the attack tick block again

**Comment by aftery142** [comment]
> There should be an option to only attack while blocking (it would register still, on ACs that don't block that), would be way better for vanilla servers with packet limiters

doesn't the server itself block that

**Comment by yorik100** [comment]
> > There should be an option to only attack while blocking (it would register still, on ACs that don't block that), would be way better for vanilla servers with packet limiters
> 
> doesn't the server itself block that

Nope not at all, I'm 200% sure about that, try sending an attack packet while blocking on a server with no AC (like tree.ac vanilla mode)

**Comment by Tcm9** [comment]
you can easily make your own autoblock module with the scripts.
Should be very easy.

**Comment by yorik100** [comment]
> you can easily make your own autoblock module with the scripts.
> Should be very easy.

So? Killaura will still send unblock and block packets when getting used, it would be useless

**Comment by Soulplexis** [comment]
NCP will block the vanilla autoblock but vanilla doesn't 
maybe it could depend on NoSlow

**Comment by yorik100** [comment]
wtf, just add vanilla autoblock
