### ISSUE TITLE
[BUG-QUESTION] KeepAlive

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3539]
Why KeepAlive send /heal message when your health is 0 ? if your health is 0 you are already dead how "mc.thePlayer.sendChatMessage("/heal")" can keep alive you ?

for example on tree.ac i test this new module firstly but its useless bcs its try to heal you after you died ?

**Comment by xHackerBey-Egemen** [comment]
dumbest way to keeping alive

**Comment by kawaiinekololis** [comment]
KeepAlive just means to revive your health when you died.
There are a lot of plugins out there which will just set your health back to 20 when you died.
As example Soup plugins or heal plugins.
