### ISSUE TITLE
[FEATURE] Killaura rotations (actually useful, see the issue)

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3547]
**Describe your feature request.**
Disable rotations in killaura

**Additional context**
Context : There is a server where too fast rotations don't bypass but any aura without rotations bypass, even in multi mode (tried with another client where you can disable rotations)

**Side note**
To people who say that it's ridiculous, it is but what would be even more ridiculous is to point out that's it's ridiculous, so please, do not comment to basically say nothing.

**Comment by Soulplexis** [comment]
It's ridiculous!
it just might work!

**Comment by apexCode1337** [comment]
Thats a very good feature that would help me too.

**Comment by superblaubeere27** [comment]
Already in it. For years. 2 years or so? 
![grafik](https://user-images.githubusercontent.com/22642852/74611096-413fcb00-50f9-11ea-9361-501c9380a82a.png)

**Comment by yorik100** [comment]
> Already in it. For years. 2 years or so?
> ![grafik](https://user-images.githubusercontent.com/22642852/74611096-413fcb00-50f9-11ea-9361-501c9380a82a.png)

No? Setting them to 0 will not make you attack

**Comment by apexCode1337** [comment]
Me too

**Comment by superblaubeere27** [comment]
Nobody needs a feature where you can disabling rotation. It won't help you.

**Comment by yorik100** [comment]
> 
> 
> Nobody needs a feature where you can disabling rotation. It won't help you.

Making a whole post proving that it's useful -> Ignoring it and closing the issue
That's not how it works, let me use some language you might understand
Server bad anticheat, detecc rotation too fast :( but me can attack players without looking at them with another client :o, killaura can't attack without rotating on LiquidBounce :( me sad me getting canceled hits but with other clients with rotations completlty disabled 0 hits canceled, wow :o what an amazing feature, LiquidBounce should have it

**Comment by apexCode1337** [comment]
Hmmm xd

**Comment by apexCode1337** [comment]
> It's ridiculous!
> it just might work!

Sarkasm?

**Comment by superblaubeere27** [comment]
@yorik100 If the server detects the client's too fast rotation, it will detect it not rotating at all too

**Comment by yorik100** [comment]
> @yorik100 If the server detects the client's too fast rotation, it will detect it not rotating at all too

IT DOESN'T ???? I CAN MULTIAURA INFINITELY WITHOUT ROTATIONS

**Comment by apexCode1337** [comment]
@superblaubeere27 He's right. I heard of that too. And even if he's not it's 3 lines of code and will be useful for someone else in the future. I need this feature for something else for example.

**Comment by superblaubeere27** [comment]
@apexCode1337 No. Thinking what a user might find useful in the future isn't the right approach to this.

**Comment by yorik100** [comment]
> @apexCode1337 No. Thinking what a user might find useful in the future isn't the right approach to this.

It helps bypassing

**Comment by superblaubeere27** [comment]
@yorik100 This is the last thing I say about this: No. It is just an additional trash option to KillAura

**Comment by yorik100** [comment]
> 
> 
> @yorik100 This is the last thing I say about this: No. It is just an additional trash option to KillAura

Nice repartee, I have fact, you have nothing

**Comment by apexCode1337** [comment]
@superblaubeere27 there are two users, both of them do scripts etc, both of them need this feature now and you say no? Why?   Is this just a demonstration of power?

**Comment by Shyrogan** [comment]
> 
> 
> @yorik100 This is the last thing I say about this: No. It is just an additional trash option to KillAura

I know a server like this, there are not a lot but few of them. Just adjust the setting to have a minimum of 0 and ignore the rotation check if it's equals to 0 doesn't cost much.

**Comment by Shyrogan** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/66

**Comment by apexCode1337** [comment]
could you please add that you can use killaura as "triggerbot"? usually i use this with rotspeed on 0 to test if the rotations have autobanns but now i cant do that anymore.

**Comment by yorik100** [comment]
XDDDDD
