### ISSUE TITLE
[BUG] InventoryCleaner throwing axe away all the time

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3549]
**Describe the bug**

**To Reproduce**
Get enchanted stone sword sharp 1 and a wooden axe in your inventory, it'll throw the axe

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by superblaubeere27** [comment]
You have to configure the InvCleaner to put it in a hotbar slot. Otherwise the Pickaxe is considered useless. This is not a bug this is a feture .-.

**Comment by yorik100** [comment]
> You have to configure the InvCleaner to put it in a hotbar slot. Otherwise the Pickaxe is considered useless. This is not a bug this is a feture .-.

Axe is set to the 2nd slot and still gets thrown away

**Comment by superblaubeere27** [comment]
@yorik100 I can't replicate it. Do you have an other axe in your inventory?

**Comment by yorik100** [comment]
Seems like axe randomly got removed from my autoslot, oopsie
