### ISSUE TITLE
[BUG] Autoarmor prefers leather prot 3 over iron

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3550]
**Describe the bug**

**To Reproduce**
1. Get a leather prot3 legging and iron legging, it'll prefer the leather one

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by superblaubeere27** [comment]
This is exactly what it is suppose to do. The Leather Armor has more Damage-Reduction.
A Leather Chestplate has a base damage reduction of 10%, an Iron Chestplate 18%. Protection 3 has an additional reduction of 12%, so the Leather Chestplate has a reduction of 22% and the Iron Chestplate has 18%. So do you think it is suppose to use the Iron Chestplate?

 I invested hours to make the AutoArmor calculate every effect and make it always pick the best armor to stop people complaining about it. Stop reporting features as bugs.
