### ISSUE TITLE
[FEATURE] scaffold edgedistance

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3551]
please add an adjustible edgedistance setting to the scaffold. it would help to bypass a better scaffold on different anticheats.

**Comment by superblaubeere27** [comment]
Nope. Absolutely useless for most anticheats I thought this in the past too, but nope

**Comment by apexCode1337** [comment]
There is a new cubecraft scaffold bypass where this is needed.

**Comment by superblaubeere27** [comment]
Then we will implement it if it is needed for this bypass. But idc why this could come to handy

**Comment by apexCode1337** [comment]
Thank you
