### ISSUE TITLE
[FEATURE] Make cross version system

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#3553]
https://github.com/CCBlueX/LiquidBounce/tree/cross_version

**Comment by Lytexx** [comment]
What does cross version mean?

**Comment by kawaiinekololis** [comment]
it just means one source for 1.8 and 1.12.2 as example. Mostly a fantasy thing with a client so huge like liquidbounce but... I'll try it.

**Comment by yorik100** [comment]
1.12 LiquidBounce with 1.8 features would be hella damn good

**Comment by whycantiusemyname** [comment]
omg

**Comment by superblaubeere27** [comment]
As @kawaiinekololis is currently not able to work on LiquidBounce, I decided that it is time to pause the development until the codebase-refactoring is done.

**Comment by superblaubeere27** [comment]
Supported will be 1.8.9 and 1.12. Maybe we will support 1.15, 1.7, 1.9, etc. (priorized in this order btw)

**Comment by Teals53** [comment]
finally 1.12 sections will be deleteable

**Comment by kawaiinekololi** [comment]
worst idea ever ngl

**Comment by Teals53** [comment]
> worst idea ever ngl

wtf xD

**Comment by Lytexx** [comment]
XDDDD

**Comment by Tcm9** [comment]
XD
