### ISSUE TITLE
[BUG] Fix hurttime

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3558]
**Describe the bug**
It stops aiming at the enemy when the enemy's hurttime is bigger than the set value, it should keep aiming at it and only stop attacking when hurttime is bigger than the set value (and aims at the enemy with the lowest hurttime)
It stops blocking with AutoBlock too

**Comment by apexCode1337** [comment]
yeah that would be much better. but please make it optional i still need it like that for something else.

**Comment by je5442804** [comment]
what do you mean optional?

**Comment by apexCode1337** [comment]
An option that keeps aiming on a single target even if it's out of the Hurttime that you can enable or disable.

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3510
