### ISSUE TITLE
[QUESTION] License in README.md

### ISSUE THREAD

**Issue by commandblock2** [CCBlueX/LiquidBounce1.8-Issues#3561]
README.md line:26
> Your modified application must also be licensed under the GPL

Is is correct that the modified application can also be licensed under the AGPL license, which is even stricter then the GPL license. The AGPL license closed the SaaS loophole. And I think there might be a possibility that someone may use the LiquidBounce's codebase to create a "LiquidBot"(like minebot) and sell the service.

**Comment by SenkJu** [comment]
Thanks. We'll think about changing the license.

**Comment by superblaubeere27** [comment]
I don't think that anyone is going to use LiquidBounce in a cloud 🤔
