### ISSUE TITLE
[BUG] Killaura switch mode doesn't clear last targets correctly

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3563]
**Describe the bug**
https://streamable.com/pq0xn the video talks about itself

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by scorpion3013** [comment]
As far as I can see, it has less todo with thruwallsrange.
And more todo with the entities that are around you.
-> Killaura switch problem
Mostlikely the same thing that happens here https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3408#issuecomment-578288262

**Comment by yorik100** [comment]
> As far as I can see, it has less todo with thruwallsrange.
> And more todo with the entities that are around you.
> -> Killaura switch problem
> Mostlikely the same thing that happens here [#3408 (comment)](https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3408#issuecomment-578288262)

Not really

**Comment by yorik100** [comment]
Edit : It's 100% Switch mode problem
