### ISSUE TITLE
[BUG] Model Custom/Player Bug

### ISSUE THREAD

**Issue by xHackerBey-Egemen** [CCBlueX/LiquidBounce1.8-Issues#3567]
**Describe the bug**
watch the video bottom

**To Reproduce**
go to hud customizer
create model
choose custom yaw and custom pitch
set 0/0 
turn your head up and down
look at model

**Screenshots**
https://youtu.be/X7l-WwT416I

**Additional information:**
 - OS: win7
 - LiquidBounce Build Version Last Dev Build (be012c3c61894ebef0432deadfe0d314821e09d0)
 - Minecraft Version 1.8.9

**Comment by kawaiinekololis** [comment]
well not a bug. pitch is more body pitch and not head pitch

**Comment by xHackerBey-Egemen** [comment]
i want to make a just standing model how can i do it?
