### ISSUE TITLE
[BUG] Timer bug.

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3587]
**Describe the bug**
If I make the timerspeed higher than 20, nothing gets faster. For some bugs I need a very high timer. But it does not get faster above 20.

**Additional information:**
 - OS: Windows
 - LiquidBounce Build Version B71
 - Minecraft Version 1.8.9

**Comment by kawaiinekololis** [comment]
Not a bug. Just minecraft.

**Comment by Teals53** [comment]
xD
