### ISSUE TITLE
[BUG] Killaura Keepsprint

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3590]
**Describe the bug**
Disabling it makes you slow down way more than a normal person should while hitting, that's how AGC detects LB's aura

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by NurMarvin** [comment]
Closing since we weren't able to reproduce this bug.
