### ISSUE TITLE
[BUG] KillAura facing check not disabled when rotations disabled by turn speed zero

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#3597]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by superblaubeere27** [comment]
Oh xD I haven't thought about this when I merged the PR xD
