### ISSUE TITLE
[FEATURE] .hide clear, reset and list sub command

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3598]

**Comment by Lytexx** [comment]
also something like .hide render or .hide combat to hide all toggled modules in that Sektion

**Comment by apexCode1337** [comment]
I think just the render category is needed for this

**Comment by apexCode1337** [comment]
Why yagni? I've already forgotten what modules I hid

**Comment by Tcm9** [comment]
What is important is that you can see which modules are hidden. So ".hide list" is important. Just like ".hide clear" to show everything again. But for example ".hide render" is not relevant. When do you want to hide everything from a category. And if you do, you can do this one by one.

**Comment by apexCode1337** [comment]
Yeah that's true
