### ISSUE TITLE
[BUG] .scriptmanager reload don't work in clickgui

### ISSUE THREAD

**Issue by xHackerBey** [CCBlueX/LiquidBounce1.8-Issues#3599]
remove a script in your scripts folder
and use .scriptmanager reload 
check the clickgui
script is still there but it doesn't work

but .reload is works fine

**Comment by CzechHek** [comment]
.scripts reload doesn't reload clickgui because it's literally called scripts reload

**Comment by apexCode1337** [comment]
Yes that's right you always have to use .reload if you want the gui to be updated

**Comment by SenkJu** [comment]
Not a bug.

**Comment by CzechHek** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/68
https://github.com/CCBlueX/LiquidBounce/pull/69
