### ISSUE TITLE
[FEATURE] Searchbar for Modules/ Values in Clickgui

### ISSUE THREAD

**Issue by derech1e** [CCBlueX/LiquidBounce1.8-Issues#3601]
**Describe your feature request.**
I think it would be great if there was a search bar in the Clickgui. This Searchbar should be have the options to search for "modules" or "module-values" and highlight them accordingly. Sometimes its really difficult to find the modules I'm looking for ...

Thx for reading :D

**Additional context**
%

**Comment by SenkJu** [comment]
We might add this feature when we recode the ClickGUI.
#2659

**Comment by apexCode1337** [comment]
Nice to hear that
