### ISSUE TITLE
[BUG] Killaura bug is back again

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3603]
**Describe the bug**
When moving too fast, it stops attacking even if it's completly able to attack the enemy
https://streamable.com/1hzsd Randomly stops attacking with 180 rotationspeed
https://streamable.com/ir4mx Also this (stops attacking for no reasons)
**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by CzechHek** [comment]
I can confirm this.

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3690
