### ISSUE TITLE
[BUG]Sprinting/speeding backwards

### ISSUE THREAD

**Issue by Lytexx** [CCBlueX/LiquidBounce1.8-Issues#3609]
if you can sprint or not should be calculated by your serverside view and not your clientside view

https://streamable.com/4yoyx
https://streamable.com/gek9b

**Comment by yorik100** [comment]
It's easy to understand but they might not understand you

**Comment by scorpion3013** [comment]
Why dont you just use the sprint module to sprint?

**Comment by Lytexx** [comment]
> Why dont you just use the sprint module to sprint?

What does the sprint module change here? That doesnt have to do with the bug

**Comment by yorik100** [comment]
> Why dont you just use the sprint module to sprint?

Scorpion pls, so if you look backwards because of aura and use speed and go forwards you'll do a sprint jump that goes backwards server sided, you will flag

**Comment by Lytexx** [comment]
> > Why dont you just use the sprint module to sprint?
> 
> Scorpion pls, so if you look backwards because of aura and use speed and go forwards you'll do a sprint jump that goes backwards server sided, you will flag

Yes same with just normal sprinting

**Comment by scorpion3013** [comment]
Cause Sprint has a handy option called checkserverside.....

**Comment by yorik100** [comment]
> 
> 
> Cause Sprint has a handy option called checkserverside.....
> https://streamable.com/eentj

It's possible to do a SilentRotationStrafe based on these calcs

**Comment by scorpion3013** [comment]
Nobody said that its not possibgle, just nobody wants todo it atm lol cause
