### ISSUE TITLE
[FEATURE] onStrafe ScriptAPI event

### ISSUE THREAD

**Issue by aftery142** [CCBlueX/LiquidBounce1.8-Issues#3611]
**Describe your feature request.**
issue title

**Additional context**
thanks

**Comment by yorik100** [comment]
That would be useful to remove the slowdown you get while changing direction in mid-air

**Comment by superblaubeere27** [comment]
Where in the world should `onStrafe` be hooked?

**Comment by aftery142** [comment]
> Where in the world should `onStrafe` be hooked?

Uhh, StrafeEvent/moveFlying?

**Comment by SenkJu** [comment]
Already in LiquidBounce. Was probably added in b72.
