### ISSUE TITLE
[BUG]Commands can't change script module's value after typing .reload

### ISSUE THREAD

**Issue by dddkj** [CCBlueX/LiquidBounce1.8-Issues#3613]
**Describe the bug**
For example I create a script module called Criticals
It has a value called delay
You can use command to change "delay"
But after typing .reload,you can't

**To Reproduce**
1. Create a script module with a value
2. Type .reload
3. See error

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by CzechHek** [comment]
Commands don't get reloaded with .reload.
Marco tried to change values on stream after reloading, then just said oh and restarted LB. So they know about it.

**Comment by dddkj** [comment]
hmmmmmmm
idk why but Marco is always missing after updating lb

**Comment by CzechHek** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/68

**Comment by CzechHek** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/69

**Comment by dddkj** [comment]
Thank you!
