### ISSUE TITLE
[FEATURE] Killaura pitch rotationspeed

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3614]
**Describe your feature request.**
Useful

**Additional context**

**Comment by apexCode1337** [comment]
Useful for me too

**Comment by superblaubeere27** [comment]
For what? ._.

**Comment by yorik100** [comment]
> For what? ._.

Pitchpattern

**Comment by yorik100** [comment]
Nevermind, it's useless

**Comment by aftery142** [comment]
> 
> 
> Nevermind, it's useless

rofl
