### ISSUE TITLE
[FEATURE] Improve AutoArmor/InventoryCleaner NoMove

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3616]
**Describe your feature request.**
Actual NoMove makes you displace items when you don't press any movement keys, it should wait for pure XZ 0 motion otherwise you're still in motion 1-2 ticks after releasing the move key

**Additional context**

**Comment by superblaubeere27** [comment]
Why tho?

**Comment by yorik100** [comment]
> Why tho?

Verus flags otherwise

**Comment by scorpion3013** [comment]
Thats a versus problem.

**Comment by yorik100** [comment]
> Thats a versus problem.

Verus doesn't try to more your items while you're in mid motion afaik

**Comment by scorpion3013** [comment]
You its a legit thing... its a versus false positive cause you can have motion and be in the invetory while being legit... so blame them.

**Comment by yorik100** [comment]
> You its a legit thing... its a versus false positive cause you can have motion and be in the invetory while being legit... so blame them.

I don't want to make a module that disable and enable autoarmor constantly, it takes like 1 min to add if motion X and Z are 0

**Comment by scorpion3013** [comment]
Just annoy the Anti-Cheat devs that they should fix their shitty false positive.

**Comment by yorik100** [comment]
> 
> 
> Just annoy the Anti-Cheat devs that they should fix their shitty false positive.

And make the 20 servers using it to use a new version plus the dev is AFK since 8 months

**Comment by superblaubeere27** [comment]
As @scorpion3013 pointed out, it's a problem of the AntiCheat
