### ISSUE TITLE
[FEATURE] Option to switch to regular Minecraft menu instead of the LiquidBounce one.

### ISSUE THREAD

**Issue by freaky767** [CCBlueX/LiquidBounce1.8-Issues#3619]
Self explanatory

**Comment by freaky767** [comment]
I know you can switch backgrounds (or have regular) but i'd want menu design n shiz

**Comment by superblaubeere27** [comment]
Why would you want to do this?

**Comment by yorik100** [comment]
> Why would you want to do this?

So he can have a custom Minecraft menu or he wants to join realms or nostalgia I guess

**Comment by superblaubeere27** [comment]
@yorik100 A realms button is a legit request, but nostalgia? Why don't you just play vanilla 🤔

**Comment by Tcm9** [comment]
so I would use it when I'm playing at a lan party with friends, I don't want the others to know I'm hacking. That's what I'd use it for. But then the Liquidbounce logo would have to become a normal Minecraft logo.

**Comment by Tcm9** [comment]
In addition Liquidbounce is a mod. And when I install a modpack where the menu changes, it can be helpful if the Liquidbounce menu is not there.

**Comment by yorik100** [comment]
> In addition Liquidbounce is a mod. And when I install a modpack where the menu changes, it can be helpful if the Liquidbounce menu is not there.

There are 1.8 modpacks?
