### ISSUE TITLE
[BUG]AutoArmor 

### ISSUE THREAD

**Issue by SanJiYT** [CCBlueX/LiquidBounce1.8-Issues#3620]

**Comment by SanJiYT** [comment]
Example : i want to pick the Diamond Armor instead Leather Armors with Protection IV 
on Some server the Diamond Armor without any enchantments will stronger
Thank You Google Translator

**Comment by CzechHek** [comment]
cool

**Comment by Teals53** [comment]
AQSQEASRUAPOARUTLUAFJLATUPIULARULRAUOUT

**Comment by superblaubeere27** [comment]
This issue has an invalid format. Please tell what you want
