### ISSUE TITLE
[FEATURE] AutoArmor intiligent

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3622]
**Describe your feature request.**
The armor you wear adapts to the environment.

If I shoot with a bow, Autoarmor should give the best armor in the inventory against arrows. 

If I fall into lava, or i burn, then Autoarmor should give me armor with Fire Protection.

If TNT or a creaper explodes right next to me, let Autoarmor put on armor with Blast Protection.

If I fall from any place, and would get fall damage, then Autoarmor should put me into springy fall shoes. 

If I fight with someone, let Autoarmor put on the best armor for fighting. e.g thorns and protection.

If Setting Intelligence is enabled, then Inventory Cleaner should not drop armor when it is enchanted.

All this is only possible if you have more than one armor in your inventory, but if you have more than one armor, you are very immune to many things.

**Comment by Teals53** [comment]
wtf

**Comment by CzechHek** [comment]
no pls

**Comment by apexCode1337** [comment]
Kinda weird

**Comment by aftery142** [comment]
This would be **HELL** to implement and won't benefit you most of the time.

**Comment by apexCode1337** [comment]
Could lead to Corona

**Comment by superblaubeere27** [comment]
This is such a useless idea. Do you want LiquidBounce to look like this? ![grafik](https://user-images.githubusercontent.com/22642852/76142425-e3eec800-606d-11ea-8b52-eed5f5eb2e4b.png)
![grafik](https://user-images.githubusercontent.com/22642852/76142427-efda8a00-606d-11ea-8340-2b18f68da348.png)
![grafik](https://user-images.githubusercontent.com/22642852/76142435-0680e100-606e-11ea-976b-56587a9c216d.png)

**Comment by Teals53** [comment]
asğdkfağdfojawkdfpaowejd xD

**Comment by apexCode1337** [comment]
xd

**Comment by MaxHD00** [comment]
XD
