### ISSUE TITLE
[FEATURE] Make ClickGUI panel animation use easing functions

### ISSUE THREAD

**Issue by dddkj** [CCBlueX/LiquidBounce1.8-Issues#3624]
**Describe your feature request.**

**Additional context**

**Comment by superblaubeere27** [comment]
Uhm what?

**Comment by dddkj** [comment]
You guys added a animation for notification and arraylist right?
This animation can be used for clickgui panel(while opening and closing)

**Comment by aftery142** [comment]
> 
> 
> You guys added a animation for notification and arraylist right?
> This animation can be used for clickgui panel(while opening and closing)
isnt there already an animation

**Comment by dddkj** [comment]
> > You guys added a animation for notification and arraylist right?
> > This animation can be used for clickgui panel(while opening and closing)
> 
> isnt there already an animation

y not use a newer and better one

**Comment by NurMarvin** [comment]
This will be incoperated in #2659.
