### ISSUE TITLE
[FEATURE] Make killaura work with blink

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3626]
**Describe your feature request.**
Would be super useful since now blink delays attack packets too

**Additional context**

**Comment by superblaubeere27** [comment]
Won't work. I can tell you that much

**Comment by yorik100** [comment]
> 
> 
> Won't work. I can tell you that much

Then why attacking manually while blinking and disabling blink would still buffer the attack, why does Shiv3r's Killaura works while blinking?
