### ISSUE TITLE
[FEATURE] PLEASE ADD .HIDE CLEAR COMMAND I NEED IT A LOT

### ISSUE THREAD

**Issue by xHackerBey** [CCBlueX/LiquidBounce1.8-Issues#3630]
or add .hide list i need it

**Comment by superblaubeere27** [comment]
CAN YOU STOP MAKING YOUR TITLES IN CAPS PLS?

Can't you do it with CustomHUD? 🤔

**Comment by apexCode1337** [comment]
This is the second time someone asked for that and still yagni?

**Comment by NurMarvin** [comment]
> This is the second time someone asked for that and still yagni?

Because you can remove it in the CustomHUD. There's no reason to add a command for that.

**Comment by apexCode1337** [comment]
Oh I didn't know that but it can't hurt either
