### ISSUE TITLE
[FEATURE] Step event POST

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3632]
**Describe your feature request.**
I'm always frustrated when I can't get the proper step height because it requires the equivalent of EventStep POST (getStepHeight returns the max step height and not how tall is the wall you collide with)
The actual onStep doesn't even have a pre or post, I guess it's pre tho

**Additional context**
Trying to make a step height detection (the way LiquidBounce get the height with step NCP spider thing is really terrible)

**Comment by kawaiinekololis** [comment]
```kotlin
@EventTarget
fun onStepConfirm(stepConfirmEvent: StepConfirmEvent) = call("onStepConfirm")
```

**Comment by yorik100** [comment]
> 
> 
> ```kotlin
> @EventTarget
> fun onStepConfirm(stepConfirmEvent: StepConfirmEvent) = call("onStepConfirm")
> ```

On step confirm needs you to step which is terrible, I need to teleport back to old position which resets my XYZ motion
