### ISSUE TITLE
[BUG] cant connect to some servers

### ISSUE THREAD

**Issue by ooodlllars** [CCBlueX/LiquidBounce1.8-Issues#3633]
**Describe the bug**
when I try to connect to some specific servers like invadedlands and manacube, it gives me an error, and I think it's the response for the server list.

**To Reproduce**
1. Go to multiplayer
2. Click on direct connect (or make a server thing in the list)
3. connect

**Screenshots**
![image](https://user-images.githubusercontent.com/25282930/77261274-97e57b00-6c4a-11ea-8508-cdcc86c1feb8.png)

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version b71
 - Minecraft Version 1.8.9

**Comment by ooodlllars** [comment]
i reset my liquidbounce folder and it got fixed

**Comment by NurMarvin** [comment]
Note: this is not an error with LiquidBounce. This is a general bug in Minecraft.
