### ISSUE TITLE
[FEATURE] Bring Login with DoubleClick back

### ISSUE THREAD

**Issue by cancerousname69** [CCBlueX/LiquidBounce1.8-Issues#3634]
**Additional context**
This is so sad. I just want to login to my alts using doubleclick again.

**Comment by superblaubeere27** [comment]
What do you mean?

**Comment by Teals53** [comment]
in my opinion he want to say "when i join altmanager and want to select alt for join i want to join alt with double click not with login button" but its weird bcs maybe lb already have it xD

**Comment by WentilatorWentox** [comment]
LB already has that. But sometimes its buggy.

**Comment by SenkJu** [comment]
LiquidBounce already has this feature.
