### ISSUE TITLE
[BUG] Weird Kill-Aura bug where the you're in range and aim distance, but it just wouldn't hit the wither.

### ISSUE THREAD

**Issue by freaky767** [CCBlueX/LiquidBounce1.8-Issues#3639]
**Describe the bug**
If you're a few blocks above, or below a wither, with silentrotation off (or on), it would seem that the kill-aura is aiming at the wither, but it just isn't hitting for some unknown reason.
Range and throughwallsrange are both 6 blocks.
Note: I think this also might happen to other mobs (such as ghasts, enderdragon, spiders)

**Video to show bug**
https://www.youtube.com/watch?v=rCMzcpHunF0

**Comment by CzechHek** [comment]
KillAura is broken men))))

**Comment by freaky767** [comment]
yes men

**Comment by freaky767** [comment]
pretty sure sometimes while you're moving too fast, killaura is sometimes out of hitbox and cannot hit an entity (happens often to a player)

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3690
