### ISSUE TITLE
[BUG]kotlin compile falied in eclipse

### ISSUE THREAD

**Issue by xuetaolu** [CCBlueX/LiquidBounce1.8-Issues#3642]
Error during build of the project
Errors occurred during the build.
Errors running builder 'Java Builder' on project '1.8.9-Forge'.
Back-end (JVM) Internal error: Failed to generate property fontValue
File being compiled: (36,5) in G:\minecraft_mdk\LiquidBonuce\1.8.9-Forge\src\main\java\net\ccbluex\liquidbounce\features\module\modules\render\NameTags.kt
The root cause org.jetbrains.kotlin.util.KotlinFrontEndException was thrown at: org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.logOrThrowException(ExpressionTypingVisitorDispatcher.java:251)

Is it my kotlin plugin version is too last?

Eclipse Marketplace Client 1.8.2
Kotlin Plugin for Eclipse 0.8.20
Jvm target 1.6
Language version 1.3
Api version 1.3

**Comment by superblaubeere27** [comment]
Fix: Uninstall Eclipse and use IntelliJ. Eclipse isn't made for Kotlin.

**Comment by NurMarvin** [comment]
Kotlin isn't really made to work with eclipse, therefore it's pretty expected to not work.
As @superblaubeere27 suggested, it would be best if you switched [IntelliJ IDEA](https://www.jetbrains.com/idea/) from Jetbrains which will definitely work with Kotlin.
