### ISSUE TITLE
[FEATURE] Allow customizing auto-reconnect delay

### ISSUE THREAD

**Issue by Infinidoge** [CCBlueX/LiquidBounce1.8-Issues#3647]
**Describe your feature request.**
As of currently, the auto-reconnect takes 5 seconds to automatically reconnect, however for some cases (like spamming reconnect while waiting for a restart on 2b2t), that delay can be too much to jump past the queue or any such reasons for wanting a rapid reconnect. Or a longer delay for reconnecting.

In conjunction with #1667, and likely with a listing as a module (similar to how Impact does it), Auto Reconnect could seem more like a full feature, rather than a static afterthought.

**Comment by Infinidoge** [comment]
Going to leave this open, as it probably is useful for the 1.8 version, however I posted here on accident instead of the 1.12 version.

**Comment by kawaiinekololis** [comment]
Any progress? @NurMarvin

**Comment by NurMarvin** [comment]
Have it in a semi-dome state locally, will get it finished once I get on PC later today.
