### ISSUE TITLE
[BUG] AutoArmor picks wrong armor pieces

### ISSUE THREAD

**Issue by DGWAsureX** [CCBlueX/LiquidBounce1.8-Issues#3649]
AutoArmor should only concern the enchantment Protection e.G. it prefers a Protection 2 golden chestplate with unbreaking 10 over a protection 2 iron chestplate.
Anntoher example it takes a lether chestplate with protection 2 and fireProtection 10 over diamond chestplate with protection 2.
PLease fix it !

**Comment by Leejames2305** [comment]
@DGWAsureX 
Autoarmor has a really good damage calculation already , there is no problem with it .
It prefer reducing damage instead of durability .

**Comment by DGWAsureX** [comment]
> @DGWAsureX
> Autoarmor has a really good damage calculation already , there is no problem with it .
> It prefer reducing damage instead of durability .

Im sure that a golden chestplate with protection 2 is worse than a iron chestplate with protection 2

**Comment by aftery142** [comment]
> 
> 
> > @DGWAsureX
> > Autoarmor has a really good damage calculation already , there is no problem with it .
> > It prefer reducing damage instead of durability .
> 
> Im sure that a golden chestplate with protection 2 is worse than a iron chestplate with protection 2

and fire protection 10

**Comment by superblaubeere27** [comment]
Not a bug.
