### ISSUE TITLE
[Feature] Blockcap

### ISSUE THREAD

**Issue by DGWAsureX** [CCBlueX/LiquidBounce1.8-Issues#3650]
I would recomend a inventoryCleaner blockcap mode to configure the maximum capacity of blocks in your inventory.

**Comment by WentilatorWentox** [comment]
as far as I know, this is already planned in the recode

**Comment by DGWAsureX** [comment]
> as far as I know, this is already planned in the recode of the invcleaner

When will it come out about

**Comment by WentilatorWentox** [comment]
idk but heres the issue
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3604

**Comment by NurMarvin** [comment]
Duplicate of #3604
