### ISSUE TITLE
[FEATURE]ClickGUI improvements

### ISSUE THREAD

**Issue by Lytexx** [CCBlueX/LiquidBounce1.8-Issues#3652]
1. You should be able to toggle modules while having the clickgui open

2. NoInvAttack on killaura should affect the Clickgui too
(or make an extra option)

3. Fix overlapping bug (it toggles the module behind the slider)
https://i.imgur.com/kYSoWGT.gifv

4. The clickgui should not close when falling
(only happens when the block below you gets removed)
https://i.imgur.com/WU3Zsxj.gifv

**Comment by aftery142** [comment]
1. ?????????????????
2. ?????????????????
3. ye the clickgui is supposed to get a recode
4. description is incorrect, server sends a packet to close the open window

**Comment by kawaiinekololis** [comment]
1 & 2. why?
3. https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2659
4. https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3693
