### ISSUE TITLE
[BUG/Improve] Donator Cape

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#3653]
Kein Bock für Detalierte Info

Donator Cape verbessern, wenn ich mit mein Account wo joine habe ich nicht das Donator Cape ich muss zuerst mit dem account wo joinen und dann wird es bei den anderen Accounts angezeigt. Habe den Code bei Cape angegeben und Enabled bla bla. Pls verbessern, danke.

**Comment by kawaiinekololis** [comment]
Donator Cape funktioniert bei mir einwandfrei. Du hast weder weitere Informationen wie Logs geboten, daher kann ich dir auch nicht helfen.
