### ISSUE TITLE
[FEATURE]cannot enter Craftrise server with Liquidbounce.

### ISSUE THREAD

**Issue by SatlaNinjaTR** [CCBlueX/LiquidBounce1.8-Issues#3668]
I can entering the lobby with Liquidbounce. (Thanks to Anti-Forge) But when I enter any game, he says don't log in with cheat.

Server İp: play.craftrise.tc
Server website: https://www.craftrise.tc
Discord: SatlaNinja#2769
I want to add: They have a silly client of their own. You can only log in with this.
So they say so. But they said so before.

**Comment by Leejames2305** [comment]
Duplicated
#3666 
Please close it .
