### ISSUE TITLE
[BUG] Build Error

### ISSUE THREAD

**Issue by burtoSUPERIOR** [CCBlueX/LiquidBounce1.8-Issues#3669]
Getting this error when i try to build
jessica👑👑👑Today at 11:08 PM
20:31:06.038 [INFO] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] An attempt to start the daemon took 0.073 secs.
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Unable to start the daemon process.
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] This problem might be caused by incorrect configuration of the daemon.
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] For example, an unrecognized jvm option is used.
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Please read the following process output to find out more:
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] -----------------------
20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Error occurred during initialization of VM20:31:06.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not reserve enough space for 3145728KB object heap

**Comment by NurMarvin** [comment]
It seems you don't have enough heap size dedicated to your gradle process.
I have never seen that error myself before, would you mind sharing some system information with us (like what CPU, how much RAM etc you have), so we can tell if it's an issue with your computer setup or the project?

**Comment by SenkJu** [comment]
Closing this. You can still reply to this thread if you have any further questions.
