### ISSUE TITLE
[FEATURE] rename inventorymove to invmove and all aacadditionpro-modes to aacap

### ISSUE THREAD

**Issue by apexCode1337** [CCBlueX/LiquidBounce1.8-Issues#3670]
It's too much text in the arraylist at the Moment.

**Comment by yorik100** [comment]
And everyone will have to update every config files 1 per 1
BIG OOF

**Comment by apexCode1337** [comment]
There can be 2 names for one mode or module but this is just too much xd
![Screenshot_20200505-124651__01](https://user-images.githubusercontent.com/56940007/81058387-a623e980-8ece-11ea-9323-9d6138b3666a.jpg)

**Comment by apexCode1337** [comment]
Or the client could just automatically create and "translate" the 2 names of invmove. So there are the same values for invmove and inventorymove in each config. And if you load an old config the client automatically creates the second setting in the config with same values for the "new" invmove module

**Comment by kawaiinekololis** [comment]
no

**Comment by apexCode1337** [comment]
:(

**Comment by Tcm9** [comment]
wtf apex. The Names are good. 
If the text is too long for you, you can switch to not displaying the under-settings.
