### ISSUE TITLE
[BUG] C03 flaws in Regen/FastUse/Zoot

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3671]
**Describe the bug**
Regen/FastUse and maybe other modules sending C03 packets send onGround false packets
InventoryCleaner item drop packets are also impossible

**Comment by kawaiinekololis** [comment]
> InventoryCleaner item drop packets are also impossible

Could you make a second issue and explain what's wrong with it.
