### ISSUE TITLE
[FEATURE] Regen only under renegeration status effect

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3673]
**Describe your feature request.**
An option to make regen only work when we have the regeneration potion status effect. Super useful for HCF with the kit that gives you perma regen and some anticheats don't block regen when under regeneration potion status effect.

**Additional context**
DO NOT MAKE AN OPTION THAT THROWS REGEN POTION, THAT'S NOT WHAT I SAID (would be a good idea tho, but separate both if you do it)

**Comment by ChocoPieisme** [comment]
he added it to b72 milestone lmao

**Comment by ChocoPieisme** [comment]
var scriptName = "Regen";
var scriptAuthor = "Choco";
var scriptVersion = 1.0;

var Potion = Java.type('net.minecraft.potion.Potion');
var c03 = Java.type("net.minecraft.network.play.client.C03PacketPlayer");

function ExampleModule() {
    this.getName = function() {
        return "lol regen";
    }
    this.getDescription = function() {
        return "regen lol"
    }
    this.getCategory = function() {
        return "Combat"; 
    }
    this.onEnable = function() {  
    }
    this.onDisable = function() {
        
    }
    this.onUpdate = function() {
          if (mc.thePlayer.isPotionActive(Potion.regeneration)) { 
         mc.thePlayer.sendQueue.addToSendQueue(new c03(true));
         }
}
var exampleModule = new ExampleModule();
var exampleModuleClient;

function onLoad() {}

function onEnable() {
    exampleModuleClient = moduleManager.registerModule(exampleModule);
}

function onDisable() {
    moduleManager.unregisterModule(exampleModuleClient);
}

**Comment by yorik100** [comment]
That's absolute shit and flags spoofground in air

**Comment by ChocoPieisme** [comment]
but that's the only way to regen that I know, maybe you can tell me the another way?
or i will add onGround option

**Comment by CzechHek** [comment]
> but that's the only way to regen that I know, maybe you can tell me the another way?
> or i will add onGround option

what about new c03(mc.thePlayer.onGround)

**Comment by ChocoPieisme** [comment]
i tried that but it doesn't regen, it only speeds up your effect (i think this is how Zoot work)

**Comment by Soulplexis** [comment]
i think to regen you need to be on the ground/onground=true so jst make the script do it when onground?

**Comment by yorik100** [comment]
> 
> 
> i think to regen you need to be on the ground/onground=true so jst make the script do it when onground?

Ah yes, when you jump you hear the regen toggle/untoggle sound, very nice, especially when you jump under a block it goes tick tick tick tick tick click click click click
