### ISSUE TITLE
[FEATURE]ChestStealer first item pick delay

### ISSUE THREAD

**Issue by wzihan2007** [CCBlueX/LiquidBounce1.8-Issues#3677]
**Describe your feature request.**
When you open a chest, delay, then start pick item.
https://forum.ccbluex.net/thread.php?id=2929
**Additional context**

**Comment by yorik100** [comment]
+1

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2912

**Comment by Teals53** [comment]
this issue and scaffold headrotation issues need to be fixed asap for make bypass on servers  :3

**Comment by superblaubeere27** [comment]
@Teals53 What is the problem about HeadRotation?

**Comment by superblaubeere27** [comment]
I decided that this is easy to implement so I will add it.

**Comment by yorik100** [comment]
Adding vanilla blockhit is also easy to implement

**Comment by Teals53** [comment]
> @Teals53 What is the problem about HeadRotation?
i mean this problem @superblaubeere27 

https://forums.ccbluex.net/topic/287/scaffold-rotations-module-needs-to-be-fixed-updated/10
