### ISSUE TITLE
[FEATURE] [ScriptAPI] Better ServerRotation setblock method

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3683]
**Describe your feature request.**
RotationUtils.setTargetRotation(new Rotation(Yaw , Pitch)); the player only looks at the server side. But where I look I can not build. I would have to make this complicated with mc.playerController.onPlayerRightClick(...). But there I would have to enter the block, vector etc. But he should only build where I already look only on the server side.

**Comment by Tcm9** [comment]
#3656 
oh. Has it been added yet? If so, I'm going to close this issue. Or is that something else?

**Comment by kawaiinekololis** [comment]
What do you mean?

**Comment by Tcm9** [comment]
There is already a possibility to build a block only on the server side.

mc.playerController.onPlayerRightClick(mc.thePlayer, mc.theWorld, mc.thePlayer.inventory.getCurrentItem(), Blockpos, EnumFacing.DOWN, vector)

but it can be very complicated if you want to do a clever bypass.

It would be easier if you could only specify the yaw and pitch. Then you can't achieve everything, but first of all you can only build Legit and secondly you can see exactly where you are really building to.
I miss one:
mc.thePlayer.setServerBlock(Yaw, Pitch);
or mc.thePlayer.setServerBlock(Yaw, Pitch, mc.thePlayer.inventory.getCurrentItem());

This would make many modules easier to code, especially beginners can build a block much better, because mc.playerController.onPlayerRightClick(...) is very complex. Starting with the fact that you have to specify a vector, because you just set it to Vec3(0, 1, 0);.

Especially if the block side always varies, then it is even harder to do that. 
An mc.thePlayer.setServerBlock(Yaw, Pitch); would make writing the script much easier. 

If you execute mc.thePlayer.setServerBlock(Yaw, Pitch, mc.thePlayer.inventory.getCurrentItem()), it simply sets a block with the item you have in your hand.

**Comment by kawaiinekololis** [comment]
No. Just do it yourself or abuse our RotationsUtils (https://github.com/CCBlueX/LiquidBounce/blob/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/utils/RotationUtils.java)
There is a `faceBlock` method which allows you to get the closest rotation to a block.
You're going to get a VecRotation which allows you to set your client rotations or server side rotations (using `setTargetRotation` method of our RotationUtils)
