### ISSUE TITLE
[FEATURE] [ScriptAPI] Chat listener

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3687]
**Describe your feature request.**
There should be a method to check the chat if a certain word is written. The listener should give true once and then show false again until the word is written again.
e.g.

if(chat.listener("Hello")) {
     chat.print(Hello back);
}

When someone writes hello, the if query is executed.

Color codes should also be counted if you put a color code in. Otherwise the color should not matter.

chat.listener("&4hello") //true if the chat contains a red hello

if you use chat.listener(* )*or* chat.listener(true), then it should be true every time a message appears in the chat at that moment. If nothing is written, then chat.listener(*) or chat.listener(true) should be false.

**Comment by ChocoPieisme** [comment]
you can do it with S02PacketChat bruh

**Comment by Tcm9** [comment]
isn't this better?

I admit I don't know the S02Packet and co. Unless I don't know how to use them.

**Comment by ChocoPieisme** [comment]
of course you don't know how to use it men))) you can do the same with S02 packet

**Comment by ChocoPieisme** [comment]
his.onPacket = function(event) {
		if(event.getPacket() instanceof S02PacketChat) {
           if event.getPacket().getChatComponent().getUnformattedText().contains("You won the game!")) {
           mc.thePlayer.sendChatMessage("gg")

this is a simple autogg
