### ISSUE TITLE
[FEATURE] NCP Phase (with Source)

### ISSUE THREAD

**Issue by Moritz-github** [CCBlueX/LiquidBounce1.8-Issues#3689]
I found this NCP Fullblock Phase source code on GitHub (https://github.com/NoCheatPlus/Issues/issues/597), but sadly I can't get LiquidBounce running in any of my IDE's and my own "client" does not have event listeners. Could you please add this to LiquidBounce?
Thank you very much!

Code: https://hastebin.com/raw/sofuqexoca

Same code:
`    if ((!this.I) && (str1.equalsIgnoreCase("NCP"))) {
      if (Z())
      {
        mc.thePlayer.rotationYaw = this.Z;
        mc.thePlayer.rotationPitch = this.B;
      }
      else
      {
        this.Z = mc.thePlayer.rotationYaw;
        this.B = mc.thePlayer.rotationPitch;
      }
    }
    Object localObject1;
    if ((paramEvent instanceof EventPushBlock))
    {
      localObject1 = (EventPushBlock)paramEvent;
      if (((EventPushBlock)localObject1).Code()) {
        paramEvent.setCancelled(true);
      }
    }
    double d4;
    double d6;
    double d8;
    if ((paramEvent instanceof EventPacket))
    {
      localObject1 = (EventPacket)paramEvent;
      im localim = ((EventPacket)localObject1).getPacket();
      Object localObject2;
      if ((localim instanceof C03PacketPlayer))
      {
        localObject2 = (C03PacketPlayer)localim;
        d4 = ((C03PacketPlayer)localObject2).V();
        d6 = ((C03PacketPlayer)localObject2).Code();
        d8 = ((C03PacketPlayer)localObject2).I();
        String str2 = ((C03PacketPlayer)localObject2).C() ? "�a" : "�c";
        if (d4 == 0.0D) {}
      }
      if ((localim instanceof S08PacketPlayerPosLook))
      {
        localObject2 = (S08PacketPlayerPosLook)((EventPacket)localObject1).getPacket();
        ((S08PacketPlayerPosLook)localObject2).yaw = mc.thePlayer.rotationYaw;
        ((S08PacketPlayerPosLook)localObject2).pitch = mc.thePlayer.rotationPitch;
        this.I = true;
        if (!this.I) {
          this.V = 0.0D;
        }
      }
      if (((EventPacket)localObject1).isOutgoing())
      {
        if (Z()) {
          return;
        }
        double d3 = 0.2D;
        double d5 = Math.cos(Math.toRadians(mc.thePlayer.rotationYaw + 90.0F));
        double d7 = Math.sin(Math.toRadians(mc.thePlayer.rotationYaw + 90.0F));
        double d9 = mc.thePlayer.movementInput.moveForward * 0.2D * d5 + mc.thePlayer.movementInput.moveStrafe * 0.2D * d7;
        double d11 = mc.thePlayer.movementInput.moveForward * 0.2D * d7 - mc.thePlayer.movementInput.moveStrafe * 0.2D * d5;
        if ((mc.thePlayer.J) && ((((EventPacket)localObject1).getPacket() instanceof C03PacketPlayer)))
        {
          this.F += 1;
          C03PacketPlayer localC03PacketPlayer = (C03PacketPlayer)((EventPacket)localObject1).getPacket();
          if (this.F >= 5)
          {
            localC03PacketPlayer.Code += d9;
            localC03PacketPlayer.I += d11;
            localC03PacketPlayer.V -= 1.0D;
            this.F = 0;
          }
        }
      }
    }
    if ((paramEvent instanceof aS))
    {
      localObject1 = (aS)paramEvent;
      if ((!S) && (mc.thePlayer == null)) {
        throw new AssertionError();
      }`

**Comment by scorpion3013** [comment]
Will not be added to LiquidBounce cause the code is from a client called "Sigma".
