### ISSUE TITLE
[BUG] Killaura randomly won`t hit entity

### ISSUE THREAD

**Issue by Leejames2305** [CCBlueX/LiquidBounce1.8-Issues#3690]
**Describe the bug**
KillAura will stop hitting randomly for no reason .
https://ctrlv.tv/VgRm

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version B71
 - Minecraft Version 1.8.9

**Comment by CzechHek** [comment]
Someone said that some part of KillAura is broken (probably the rotations part). It calculates rotation that doesn't look at the enemy and the hittable check stops it from attacking.

**Comment by freaky767** [comment]
yea the ka needs to be fixed, sometimes if youre moving too fast it also sometimes doesnt hit the player, or if you're in a specific position (like above player) it wont hit

**Comment by kawaiinekololis** [comment]
The reason is our facing check. The rotations are working fine. I noticed it myself already but didn't fixed it yet.
