### ISSUE TITLE
[FEATURE] Add a mode to KillAura where it aims to only a specific part of player

### ISSUE THREAD

**Issue by freaky767** [CCBlueX/LiquidBounce1.8-Issues#3691]
So for example, the modes im thinking could be a good addition would be aim at head, torso, or legs. And it would just aim specifically to that part of player.

**Comment by superblaubeere27** [comment]
Where do you need it for?

**Comment by icewormy3** [comment]
> Where do you need it for?

maybe to bypass an anticheat, idk

**Comment by aftery142** [comment]
So a gimmick setting.

**Comment by superblaubeere27** [comment]
Yea... You know our handling of unuseful features
