### ISSUE TITLE
[FEATURE] ClientBrand

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3692]
**Describe your feature request.**
in sigma there is a mod called fakeforge that lets you rebrand your client to whatever you want. not sure what this could be used for but its gotta be good for something. 

**Additional context**
the default setting says "fml,forge"

**Comment by ChocoPieisme** [comment]
skidma is bad

**Comment by superblaubeere27** [comment]
> 
> 
> not sure what this could be used for but its gotta be good for something.

There is a simple rule in software engineering: If you don't need it, don't do it. The only thing you will achieve is building bugs into your architecture.

If there was a scenario where this is needed to bypass a server, we might think about doing it.
