### ISSUE TITLE
[FEATURE] Freecam/blink distance count

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3694]
**Describe your feature request.**
When freecam is on maybe it could count the # of blocks away from your real position

**Additional context**

**Comment by Tcm9** [comment]
at freecam i don't see the sense of the feature in that. With Blink, it could be useful.

**Comment by superblaubeere27** [comment]
At Blink, only a packet counter would be useful, which is already implemented ([Here](https://github.com/CCBlueX/LiquidBounce/blob/9f5542b525a6e69b345204f1eb0a6db4e8a96449/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/Blink.java#L145)).
