### ISSUE TITLE
[FEATURE] Please allow customization of the text on main menu, instead of just saying 'Liquidbounce'

### ISSUE THREAD

**Issue by EternalFear** [CCBlueX/LiquidBounce1.8-Issues#3706]
**Describe your feature request.**
I like to closet cheat, and sometimes even stream while doing so, but I like the shader main menu that Liquidbounce has. The problem is is that the big fat 'Liquidbounce' logo gives away the fact that you are cheating no matter what. Please make it so you can delete/customize the text.

**Comment by aftery142** [comment]
Yes, because the normal liquidbounce ui isn't suspicious at all without the watermark

**Comment by superblaubeere27** [comment]
If you just remove the LiquidBounce, it is still suspicious. I don't think that there are much people from the userbase who need it. A possible solution would be a ghost mode, where no LiquidBounce-y GUI is shown, but this is hard to do.

**Comment by EternalFear** [comment]
It's fine. I used the source code and got rid of most of the Liquidbounce ui features. Along with using it on Labymod, which can override alot of GUI elements. I managed to have basically only the LB cheats running, and the RPC removed aswell, so I can have the Labymod discord presence.

**Comment by EternalFear** [comment]
> Yes, because the normal liquidbounce ui isn't suspicious at all without the watermark

I mean, there are mods that can do the exact same thing. That are completely legit. So, not really.

**Comment by superblaubeere27** [comment]
> 
> 
> It's fine. I used the source code and got rid of most of the Liquidbounce ui features. Along with using it on Labymod, which can override alot of GUI elements. I managed to have basically only the LB cheats running, and the RPC removed aswell, so I can have the Labymod discord presence.

Ok, then I think this can be closed
