### ISSUE TITLE
[BUG] Velocity(AAC) Error in code

### ISSUE THREAD

**Issue by TheFleksisCekcu** [CCBlueX/LiquidBounce1.8-Issues#3710]
Change code from
"aac" -> if (velocityInput && velocityTimer.hasTimePassed(80L)) {
                mc.thePlayer.motionX *= horizontalValue.get()
                mc.thePlayer.motionZ *= verticalValue.get()
                velocityInput = false
            }
to
"aac" -> if (velocityInput && velocityTimer.hasTimePassed(80L)) {
                mc.thePlayer.motionX *= horizontalValue.get()
                mc.thePlayer.motionY *= verticalValue.get()
                mc.thePlayer.motionZ *= horizontalValue.get()
                velocityInput = false
            }

**Comment by ChocoPieisme** [comment]
he did it

**Comment by superblaubeere27** [comment]
Horizontal = X
Vertical = Z

Works as intended

**Comment by kawaiinekololis** [comment]
Has been already fixed.
https://github.com/CCBlueX/LiquidBounce/commit/07b89b0dbc1165e2d2261a1fd4a27086bafb482d

**Comment by kawaiinekololis** [comment]
and I forgot to create a issue for it, so just added this one.

**Comment by superblaubeere27** [comment]
@kawaiinekololis He meant that the vertical setting should affect the Y-Velocity. But this is also a fixed bug xD
