### ISSUE TITLE
[FEATURE] Icon Image

### ISSUE THREAD

**Issue by ChocoPieisme** [CCBlueX/LiquidBounce1.8-Issues#3712]
**Describe your feature request.**
So I want to change the icon, but i don't know how to make a image, so i want a feature that you can change the icon with a png file (like userbackground.png)

**Comment by aftery142** [comment]
No

**Comment by lolmc1982** [comment]
no
liquid is liquid
lol =))

**Comment by Tcm9** [comment]
Liquidbounce is open source. You can easily change the icon yourself

**Comment by SenkJu** [comment]
Just replace the icon inside the assets folder. You can open up the jar using any archiving program (eg. WinRAR, 7-Zip).

**Comment by ChocoPieisme** [comment]
i can't find the icon in the assets folder

**Comment by kawaiinekololis** [comment]
![](https://axolotl.us/ZVIgghD7sustoY/f93pgigY)

**Comment by ChocoPieisme** [comment]
nvm i changed it thx
