### ISSUE TITLE
[BUG] [ScriptAPI] Creative Tab Function Name spelt wrong everywhere

### ISSUE THREAD

**Issue by leumasme** [CCBlueX/LiquidBounce1.8-Issues#3713]
https://liquidbounce.net/docs/ScriptAPI/Creating%20Inventory%20Tabs
"this.displayAllReleventItems"
This is a typo, relev**a**nt is how you spell that (with an A).
It's also missspelt in the code everywhere
https://github.com/CCBlueX/LiquidBounce/search?q=displayAllReleventItems&unscoped_q=displayAllReleventItems

**Comment by kawaiinekololis** [comment]
I can't do anything about the misspelling in the name of the method (the method is from minecraft - we are just overriding it), but I'm able to change it in the ScriptAPI.

**Comment by SenkJu** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues/140

**Comment by kawaiinekololis** [comment]
I think we should just wait until the new script api is done.
https://github.com/CCBlueX/LiquidBounce/pull/96
