### ISSUE TITLE
[FEATURE] PositionRenderer

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce1.8-Issues#3714]
**Describe your feature request.**
HeadRotations renders the rotations that are sent 
this would be that but for positions that are sent. there isnt a lot in liquidbounce that sends positions though.

**Additional context**

**Comment by superblaubeere27** [comment]
No

**Comment by Soulplexis** [comment]
why not

**Comment by superblaubeere27** [comment]
The YAGNI-Label already explained it:
- It is absolutely useless
- It might distract users
- It add crucial bugs to the client
- It wastes our time implementing it

**Comment by kawaiinekololis** [comment]
Not really useful but would be easy to implement.

**Comment by Soulplexis** [comment]
oh oke
