### ISSUE TITLE
[REMOVE] Remove GuiCredits

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#3716]
Since LiquidBounce is now open-source, this GUI is no longer necessary. A list of people who contributed to LiquidBounce can be found by visiting the repository: https://github.com/CCBlueX/LiquidBounce/graphs/contributors

In addition, the list of credits has not been updated for a long time anyway.

**Comment by superblaubeere27** [comment]
I think replacing the GuiCredits with GuiContributors is the better approach

**Comment by kawaiinekololis** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3718
