### ISSUE TITLE
[FEATURE] Remake GuiCredits as GuiContributors

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce1.8-Issues#3718]
**Describe your feature request.**
As described in #3716 the credits GUI (`GuiCredits` in the code) will be removed for the b72.
Considering LiquidBounce is now open-source we could however also add a contributors GUI in it's place which shows a screen of all GitHub contributors with their avatar and amount of contributions.
Additionally we could also put a link to the GitHub repository in said screen to encourage more people to contribute to the client.

**Additional context**
N/A

**Comment by superblaubeere27** [comment]
Would you do it?

**Comment by NurMarvin** [comment]
> 
> 
> Could you do it?

That was the plan, yes, just didn't assign myself to it yet, because I currently have other things to do, so we can just remove the credits GUI for now and then add the contributors GUI at a later time.

**Comment by superblaubeere27** [comment]
I started develeopment on the [gui_contributor](https://github.com/CCBlueX/LiquidBounce/tree/gui_contributors) branch (Pull Request CCBlueX/LiquidBounce#101)
