### ISSUE TITLE
[FEATURE] *Real* 2D-ESP

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#3723]

**Comment by ChocoPieisme** [comment]
i like the old 2D, pls don't remove it

**Comment by Teals53** [comment]
> i like the old 2D, pls don't remove it

he not removing he just improving that

**Comment by superblaubeere27** [comment]
> 
> 
> i like the old 2D, pls don't remove it

Dw, the old mode will not be changed. But there will be a new Mode called `Real2D`
