### ISSUE TITLE
[IMPROVE] Make tracers use world-to-screen functions instead of rendering 3D-verticies

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce1.8-Issues#3724]
Tracers sometimes has weird bugs, where OpenGL tries to render the tracer line through the nPlane

**Comment by Pokemonplatin** [comment]
Just a waste of performance in my opinion

**Comment by superblaubeere27** [comment]
@Pokemonplatin What waste of performance? This is the performance of the world-to-screen function used (Full llvm-mca log: https://hastebin.com/mukurehiki.txt):
![grafik](https://user-images.githubusercontent.com/22642852/83168111-4ad1c980-a111-11ea-8f5c-576fcb4ae447.png)
102 cycles will take 50ns to execute on a 2.1 GHz CPU.
If you used that function with 1k entities à 4 verticies (which is completely unrealistic), the program will be busy for less than 194 μs (will be a bit faster because of cashing etc.). Rendering a 2D-font takes 30-100 μs. It actually takes longer to draw the Fonts of the TabGui, than it takes to do those 4k world-to-screen function calls
