### ISSUE TITLE
[FEATURE][ScriptAPI] ES6 supporting

### ISSUE THREAD

**Issue by KaguwaScarlet** [CCBlueX/LiquidBounce1.8-Issues#3727]
Support JavaScript ES6 Standard.

**Comment by SenkJu** [comment]
LiquidBounce is using Nashorn as its script engine which does not support ES6. You can however use Babel to transpile modern JS down to ES5.

https://liquidbounce.net/docs/ScriptAPI/Setting%20up%20Babel
