### ISSUE TITLE
[FEATURE] New ScriptAPI

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#3731]
LiquidBounce's current script API is not very idiomatic and requires a lot of boilerplate code. This will change with the new script API currently in development.

Checkout https://github.com/CCBlueX/LiquidBounce/pull/96 for more information.

**Comment by ChocoPieisme** [comment]
i still like old scriptapi xd

**Comment by lolmc1982** [comment]
yes xd

**Comment by Tcm9** [comment]
yes xd

**Comment by MaxHD00** [comment]
yes xd

**Comment by Tcm9** [comment]
with the old scriptapi the code looks much better. The many brackets are hideous

**Comment by Tcm9** [comment]
especially there are more important things than the scriptapi that need to be recoded.

**Comment by Tcm9** [comment]
mostly the old scripts will not work anymore.

**Comment by scorpion3013** [comment]
> mostly the old scripts will not work anymore.
Why should they stop working?

**Comment by SenkJu** [comment]
Old scripts are still working with the new script API but should be updated.

**Comment by ChocoPieisme** [comment]
but i want to code in old scriptapi

**Comment by superblaubeere27** [comment]
@ChocoPieisme Then do it.

**Comment by SenkJu** [comment]
You will have to adapt.

**Comment by yorik100** [comment]
> 
> 
> Old scripts are still working with the new script API but should be updated.

Wait, old ScriptAPI scripts will not work natively anymore??

**Comment by SenkJu** [comment]
> > 
> > 
> > Old scripts are still working with the new script API but should be updated.
> 
> Wait, old ScriptAPI scripts will not work natively anymore??

They will still work but we might drop support for them some time in the future. So you are better off using the new API when developing new scripts.

**Comment by yorik100** [comment]
> 
> 
> > > Old scripts are still working with the new script API but should be updated.
> > 
> > 
> > Wait, old ScriptAPI scripts will not work natively anymore??
> 
> They will still work but we might drop support for them some time in the future. So you are better off using the new API when developing new scripts.

Excuse me? Are you serious? No one asked for that bullshit, that's just being annoying just to be annoying

**Comment by SenkJu** [comment]
No, that's just how it goes. You can't expect your scripts to work forever without updating them. Sometimes you just have to adapt to new conditions.

**Comment by yorik100** [comment]
> 
> 
> No, that's just how it goes. You can't expect your scripts to work forever without updating them. Sometimes you just have to adapt to new conditions.

I have over 25 scripts, what the fuck am I supposed to do? How about scripts that are public, the ones in videos, noone will work anymore

**Comment by SenkJu** [comment]
Like I said. All those scripts will still work until we decide to drop support for them. We won't do that anytime soon. We just ask all developers to use the new API for new scripts and update those scripts who are most likely to still be relevant after we dropped support. You also should not overestimate the amount of work you would have to put into porting a script. We are still using Nashorn. All your actual code will still work. The only thing you have to update is the way a script/module/command is registered and how events are called. Even if you have an extremely large script, it should not take more than 10-15 minutes to do so.

**Comment by yorik100** [comment]
> 
> 
> Like I said. All those scripts will still work until we decide to drop support for them. We won't do that anytime soon. We just ask all developers to use the new API for new scripts and update those scripts who are most likely to still be relevant after we dropped support. You also should not overestimate the amount of work you would have to put into porting a script. We are still using Nashorn. All your actual code will still work. The only thing you have to update is the way a script/module/command is registered and how events are called. Even if you have an extremely large script, it should not take more than 10-15 minutes to do so.

I have MULTIPLE large scripts

**Comment by SenkJu** [comment]
Send me one of them and I will show you hoe quickly you can update it to the new script API.

**Comment by MaxHD00** [comment]
nevertheless the old scriptapi is more beautiful.
Does the new version have any advantages?
can you do more?
And please don't say that the code will be shorter or clearer. It's not really an advantage, because the code itself stays quite the same and even brackets are added.

**Comment by MaxHD00** [comment]
We simply make a Liquidbounce 2.0 where the old scripttapi is still supported. The src is public there.
:D

**Comment by yorik100** [comment]
It's probably lowering FPS loss or something like that

**Comment by ChocoPieisme** [comment]
i still prefer to code in old scriptapi
pls don't remove it :<

**Comment by AsOne2020** [comment]
> Old scripts are still working with the new script API but should be updated.

i think it is better if you can make both the old and the new API supportive without change anything in your script.
The new one does have some good features, but the old one also has some features that the new one does not

**Comment by superblaubeere27** [comment]
To make that clear: The new script API has much better architecture and is far more easy to get used to. It doesn't even matter how large your old scripts are, you can still translate them in under 10min. Just change the Module/Command/Event registering and you are done. You will still program the same minecraft.

**Comment by yorik100** [comment]
> > Old scripts are still working with the new script API but should be updated.
> 
> i think it is better if you can make both the old and the new API supportive without change anything in your script.
> The new one does have some good features, but the old one has some advantages that the new one doesn't have

**Comment by ChocoPieisme** [comment]
NO I WANT OLD SCRIPTAPI PLSSSSSSSSSSSS
and how about obfuscated script
BUT I STILL WANT OLD SCRIPTAPI

**Comment by MaxHD00** [comment]
for example?
please tell me the advantages of the new scriptapi on the subject of features?

and tell me advantages the old scriptapi has but the new one doesn't?

**Comment by MaxHD00** [comment]
I see the scripts that don't have a coder anymore, because they are gone, but have the code obfuscated. These scripts are then lost.

**Comment by MaxHD00** [comment]
and otherwise the code has changed slightly. 
at onUpdate and co there are now more brackets.
but it means it should be more compact.
i think it balances itself out, if there are no new features like that you can create a button in the gui (e.g. enchantmenttable).

**Comment by MaxHD00** [comment]
in the end it is just a small synthax change that makes all scripts non-functional. Sure, it can be converted, but it can't be done everywhere. Like I said before. Scripts without coder that are obfuscated.

**Comment by MaxHD00** [comment]
but I am neutral to the new scriptapi.
i can simply convert my few scripts.
and maybe it will bring some advantages.
But it feels like a useless update of Windows, android and co, who sometimes have simply removed or changed things, and then many things just don't work anymore. I see that with Minecraft too. With almost every minecraft version since 1.9 they changed the synthax of commands. That can fuck up.

**Comment by MaxHD00** [comment]
With the minecraft commands it can look like this. This is really stupid.
![image](https://user-images.githubusercontent.com/31143468/83515065-08273d00-a4d5-11ea-92d1-a66441296bbb.png)
But with the 1.8 it still says (1.8 and before)
![image](https://user-images.githubusercontent.com/31143468/83515136-28ef9280-a4d5-11ea-8a57-04e25819e697.png)

**Comment by superblaubeere27** [comment]
@MaxHD00 This is **ONE** update which is necessary as the current API has a very bad design

**Comment by superblaubeere27** [comment]
@yorik100 @AsOne2020 Nope. The new one has only one disadvantage, it is new

**Comment by MaxHD00** [comment]
> @MaxHD00 This is **ONE** update which is necessary as the current API has a very bad design

ok this is a statement

**Comment by SenkJu** [comment]
> > Old scripts are still working with the new script API but should be updated.
> 
> i think it is better if you can make both the old and the new API supportive without change anything in your script.
> The new one does have some good features, but the old one has some advantages that the new one doesn't have

What features does the new API lack?

**Comment by SenkJu** [comment]
> NO I WANT OLD SCRIPTAPI PLSSSSSSSSSSSS
> and how about obfuscated script
> BUT I STILL WANT OLD SCRIPTAPI

Obfuscating scripts should be much easier and more secure with the new API as there aren't any magic variables on the top level that have to stay unchanged.

**Comment by MaxHD00** [comment]
> > NO I WANT OLD SCRIPTAPI PLSSSSSSSSSSSS
> > and how about obfuscated script
> > BUT I STILL WANT OLD SCRIPTAPI
> 
> Obfuscating scripts should be much easier and more secure with the new API as there aren't any magic variables on the top level that have to stay unchanged.

I've been waiting for an answer like that. Obfuscating is better and safer there. I'm glad to hear that.

**Comment by ChocoPieisme** [comment]
how about 2 scriptapi?
maybe you like it but nobody in here like it

**Comment by ChocoPieisme** [comment]
> > > Old scripts are still working with the new script API but should be updated.
> > 
> > 
> > i think it is better if you can make both the old and the new API supportive without change anything in your script.
> > The new one does have some good features, but the old one has some advantages that the new one doesn't have
> 
> What features does the new API lack?

easy to code

**Comment by SenkJu** [comment]
> how about 2 scriptapi?
> maybe you like it but nobody in here like it

No.

**Comment by SenkJu** [comment]
> > > > Old scripts are still working with the new script API but should be updated.
> > > 
> > > 
> > > i think it is better if you can make both the old and the new API supportive without change anything in your script.
> > > The new one does have some good features, but the old one has some advantages that the new one doesn't have
> > 
> > What features does the new API lack?
> 
> easy to code

The new script API isn't any harder to use. Actually, it should be easier for anyone who has worked with JavaScript APIs before.

**Comment by yorik100** [comment]
"mySetting: Setting.boolean({
            name: "MyBooleanSetting",
            default: true
        })"
I usually don't complain about these stuff when they're well done, but this is absolute ****, that's the reason I never did scripts before it became what it is right now and not the same thing than in LB 1.12, this is only one thing, we can adapt, right? False, everything else looks like an absolute mass of words, in the future API, what would've bee "who" now will become "whomst'd" (meme example to show that you just add more difficulty in the making of scripts).

**Comment by SenkJu** [comment]
> "mySetting: Setting.boolean({
>             name: "MyBooleanSetting",
>             default: true
>         })"
> I usually don't complain about these stuff when they're well done, but this is absolute ****, that's the reason I never did scripts before it became what it is right now and not the same thing than in LB 1.12, this is only one thing, we can adapt, right? False, everything else looks like an absolute mass of words, in the future API, what would've bee "who" now will become "whomst'd" (meme example to show that you just add more difficulty in the making of scripts).

Here are a few (popular) JavaScript libraries, that I enjoy using:
- https://www.npmjs.com/package/ws
- https://www.npmjs.com/package/express
- https://www.npmjs.com/package/discord.js
- https://www.npmjs.com/package/minecraft-protocol

You may notice some similarities between the APIs of these libraries and LiquidBounce's new script API. This is no coincidence. This is how JavaScript APIs should work. If you don't recognize this, you probably just don't have the experience to do so yet. Maybe you will come to like the new API once you have gotten used to it.

**Comment by yorik100** [comment]
> 
> 
> > "mySetting: Setting.boolean({
> > name: "MyBooleanSetting",
> > default: true
> > })"
> > I usually don't complain about these stuff when they're well done, but this is absolute ****, that's the reason I never did scripts before it became what it is right now and not the same thing than in LB 1.12, this is only one thing, we can adapt, right? False, everything else looks like an absolute mass of words, in the future API, what would've bee "who" now will become "whomst'd" (meme example to show that you just add more difficulty in the making of scripts).
> 
> Here are a few (popular) JavaScript libraries, that I enjoy using:
> 
>     * https://www.npmjs.com/package/ws
> 
>     * https://www.npmjs.com/package/express
> 
>     * https://www.npmjs.com/package/discord.js
> 
>     * https://www.npmjs.com/package/minecraft-protocol
> 
> 
> You may notice some similarities between the APIs of these libraries and LiquidBounce's new script API. This is no coincidence. This is how JavaScript APIs should work. If you don't recognize this, you probably just don't have the experience to do so yet. Maybe you will come to like the new API once you have gotten used to it.

You make a new API so it looks more user friendly but it's doing the opposite

**Comment by SenkJu** [comment]
I'm not going to discuss this any further with you as you seem to be unwilling to understand why the new API is indeed more user-friendly.

**Comment by yorik100** [comment]
> 
> 
> I'm not going to discuss this any further with you as you seem to be unwilling to understand why the new API is indeed more user-friendly.

You're the one that doesn't understand that the new API is absolutely terrible

**Comment by SenkJu** [comment]
So are pretty much all JavaScript APIs in your opinion?

**Comment by yorik100** [comment]
Stop being stubborn

**Comment by SenkJu** [comment]
I have seen dozens of JavaScript APIs in the many years I have been using JavaScript. This is how JavaScript APIs work. You are the one who is being stubbern. I will lock this conversation. If you dislike the new API so much and are unwilling to adapt to changes, you can still use the old API until we decide to no longer support it but even after we did so, you can still emulate the old API with a helper script.

**Comment by superblaubeere27** [comment]
> 
> 
> > I'm not going to discuss this any further with you as you seem to be unwilling to understand why the new API is indeed more user-friendly.
> 
> You're the one that doesn't understand that the new API is absolutely terrible

@yorik100 You are the one who never programmed.
