### ISSUE TITLE
[FEATURE] Criticals visual in KillAura

### ISSUE THREAD

**Issue by ChocoPieisme** [CCBlueX/LiquidBounce1.8-Issues#3732]
**Describe your feature request.**
KillAura has a fakesharp, but i want fakecrit

**Comment by scorpion3013** [comment]
bruh

**Comment by aftery142** [comment]
> 
> 
> bruh

**Comment by superblaubeere27** [comment]
This is already present when you activate `Criticals`. Most of the users won't need it so we won't include it in the mainline. You can make a fork tho
