### ISSUE TITLE
[BUG] Killaura not working on Redesky.com

### ISSUE THREAD

**Issue by JArm3945** [CCBlueX/LiquidBounce1.8-Issues#3738]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by PBTada** [comment]
ok retard

**Comment by NurMarvin** [comment]
Can you provide us with a screenshot of your Killaura settings, your targets settings, as well as a list of all other enabled modules?

**Comment by PBTada** [comment]
marvin bad coder

**Comment by PBTada** [comment]
marvin admin abuser

**Comment by PBTada** [comment]
i will 1337 you

**Comment by JArm3945** [comment]
um here it is
![image](https://user-images.githubusercontent.com/66204982/83358343-da10f400-a340-11ea-83e5-c36ad0a8ace2.png)
idk

**Comment by superblaubeere27** [comment]
AntiBot-Config?

**Comment by JArm3945** [comment]
idk

**Comment by JArm3945** [comment]
![image](https://user-images.githubusercontent.com/66204982/83358488-e6e21780-a341-11ea-9487-50581fc0f8ca.png)
here u go

**Comment by TheFleksisCekcu** [comment]
Configure it normally, It working beatifully, Dont use coccocoa's killaura. I recommended to use rewinside's antibot and aura

**Comment by TheFleksisCekcu** [comment]
Please, delete theme. Killaura working perfectly, if configure it normally. His config is shitty and no more. Client's aura is normal working on redesky, but criticals may flag
