### ISSUE TITLE
[FEATURE] Make the highest AutoReconnect Setting disable AutoReconnect

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#3741]
**Describe your feature request.**
On the B72 new buttons were added and the Reconennct button was scaled down although this is the most important button.

What would it be like to remove the Autoreconnect and Autoreconnect delay buttons completely?

If you want to turn autorecconect off or on, you can do so by right-clicking on Reconnect.

And you can change the delay +1 or -1 by pointing the mouse at Reconnect and turning the mouse wheel.

Also, please do not use milli seconds.
Seconds are enough. 
If you really need the ms, you can change this in values.json.

**Additional context**
![image](https://user-images.githubusercontent.com/31143468/83438101-22174000-a441-11ea-82e9-76ee26f70212.png)

**Comment by RypedLuis** [comment]
NICE

**Comment by superblaubeere27** [comment]
I will change the newly implemented AutoReconnectDelay. The highest setting will disable the autoreconnect.

**Comment by superblaubeere27** [comment]
As there is already a setting for this, I will close this issue.
