### ISSUE TITLE
[FEATURE] Remove AutoReconnect button

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#3742]
**Describe your feature request.**
If you set the slider to 0, you can deactivate autoreconnect. You don't need an extra button for this.

**Additional context**
![image](https://user-images.githubusercontent.com/31143468/83464796-2f98ee00-a472-11ea-9524-e5d1c7eca8c0.png)

**Comment by MaxHD00** [comment]
slider = minimum => AutoReconnect = off
![image](https://user-images.githubusercontent.com/31143468/83464907-80104b80-a472-11ea-8c6e-47b0b69632ac.png)

**Comment by superblaubeere27** [comment]
Already done, but the highest value will disable it. [e1166b3](https://github.com/CCBlueX/LiquidBounce/commit/e1166b30e4d3ba6bd1db5ca089bce6190ffdd99b)

**Comment by MaxHD00** [comment]
can you still convert milliseconds to seconds? You don't need milliseconds with something like this. And if you still need it, you can change it in the value.json.

**Comment by MaxHD00** [comment]
or, if need be, a comma column.
so for example 10.8 seconds
or 5.5 seconds

**Comment by superblaubeere27** [comment]
@MaxHD00 This is how it looks like 
![grafik](https://user-images.githubusercontent.com/22642852/83509876-66035700-a4cc-11ea-995a-f050aa72e6bf.png)

**Comment by MaxHD00** [comment]
nice. Thanks. One more question, why is reconnect beside the slider?
The slider fits more at the bottom.

**Comment by MaxHD00** [comment]
as you know, I want the reconnect button bigger. Sorry about that.

**Comment by MaxHD00** [comment]
I also thought that there should be a way to hide the slider. Because sometimes, for example, the time only wants to set once. So I thought, if you press the middleclick button, the slider will be faded in or out. An info should then still appear:
e.g.
"Autoreconnect slider was hidden by middle click"

**Comment by MaxHD00** [comment]
But this looks a lot better than it did before.

**Comment by MaxHD00** [comment]
If you can hide autoreconnect, then you don't need to move autoreconnect down, because the reconnect button will increase in size anyway.
