### ISSUE TITLE
[FEATURE] BodyRotations

### ISSUE THREAD

**Issue by TheFleksisCekcu** [CCBlueX/LiquidBounce1.8-Issues#3743]
Add module, that allows you see server body rotations.

**Comment by superblaubeere27** [comment]
HeadRotations already does the Job, but it would make much more sense when the whole body is rotated. I am not sure if this is a duplicate, but I can't find the original

**Comment by MaxHD00** [comment]
it exist a BodyRotations script.

**Comment by superblaubeere27** [comment]
@MaxHD00 Englisch Abi NRW? xD

**Comment by MaxHD00** [comment]
https://forum.ccbluex.net/thread.php?id=2153

There exists a Bodyrotatins script would be correct. lul

**Comment by superblaubeere27** [comment]
@MaxHD00 Das ist HeadRotations .-.

**Comment by MaxHD00** [comment]
![image](https://user-images.githubusercontent.com/31143468/83536740-ebe6c880-a4f3-11ea-9014-6c167228d165.png)

**Comment by superblaubeere27** [comment]
@MaxHD00 Yea, but it is still what is called HeadRotations

**Comment by MaxHD00** [comment]
go to page 3

**Comment by MaxHD00** [comment]
no idea. I saw "body rotations" there. I don't use that script, so I can't tell if that's really body rotation or not.

**Comment by MaxHD00** [comment]
if there is no body rotation, sorry for that.

**Comment by SenkJu** [comment]
#3522
