### ISSUE TITLE
[IMPROVE] Make ArrayList rainbow seamless

### ISSUE THREAD

**Issue by TheFleksisCekcu** [CCBlueX/LiquidBounce1.8-Issues#3750]
Fix rainbow, its not correctly working
Broken rainbow screenshot: 
![Без названия](https://user-images.githubusercontent.com/55242111/83729927-05e9ed80-a651-11ea-808f-be01f7de1338.png)

**Comment by TheFleksisCekcu** [comment]
Its not smooth.

**Comment by superblaubeere27** [comment]
I don't understand

**Comment by Leejames2305** [comment]
He means the rainbow colours are not mixed smoothlly and seamlessly ( you can see each colour has its own block dividing with each other )

**Comment by derech1e** [comment]
> I don't understand

He mean, that the transition is not perfectly smooth overall. He want, a transition with more than one color per activated module.

![image](https://user-images.githubusercontent.com/39240736/83760320-144a0080-a675-11ea-94a2-4c02824d49e1.png)

**Comment by derech1e** [comment]
> He means the rainbow colours are not mixed smoothlly and seamlessly ( you can see each colour has its own space/block dividing with the other colour beside it )

He perfectly described it.

**Comment by superblaubeere27** [comment]
> 
> 
> > I don't understand
> 
> He mean, that the transition is not perfectly smooth overall. He want, a transition with more than one color per activated module.
> 
> ![image](https://user-images.githubusercontent.com/39240736/83760320-144a0080-a675-11ea-94a2-4c02824d49e1.png)

This is what it is suppose to look like
