### ISSUE TITLE
[BUG] Infinite loading animation in Contributors Screen

### ISSUE THREAD

**Issue by derech1e** [CCBlueX/LiquidBounce1.8-Issues#3752]
**Describe the bug**
Sometimes it's get stuck in the loading animation and stay there forever. I recommend to add a "Failed to Load" Information or something else.

**To Reproduce**
1. Start the Client
2. Click on the "Contributors" button
3. ... Exception: https://pastebin.com/ESZ7zC8a

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version 72-Dev
 - Minecraft Version 1.8.9

**Comment by superblaubeere27** [comment]
I never faced this kinda bug

**Comment by superblaubeere27** [comment]
Fixed.
