### ISSUE TITLE
[BUG] Nvidia Driver 309.08 (Nvidia GeForce 6150SE nForce 430)

### ISSUE THREAD

**Issue by GorkemYakar** [CCBlueX/LiquidBounce1.8-Issues#3754]
**My PC have amd procccessor and nvidia geforce 6150se nforce 430 gpu (onboard)
and i cant start liquidbounce (sorry for my bad english)

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/66495758/83924032-3bdfbc80-a78c-11ea-8c3c-e96edcc48171.png)

![Screenshot_2](https://user-images.githubusercontent.com/66495758/83924045-4306ca80-a78c-11ea-92dc-296d92af17ff.png)

**Additional information:**
 - OS: Windows 7 Ultimate SP1 64 Bit 
 - LiquidBounce Build Version : b71
 - Minecraft Version : 1.8.9

I signed up to tell GitHub about this issue. and this is my first issue.**

**Comment by superblaubeere27** [comment]
This is not specificly a problem of liquidbounce, rather a problem of your display driver. Do you have the latest version installed?

**Comment by GorkemYakar** [comment]
latest version 309.08 for my graphics card alreayd. can you help me?

**Comment by GorkemYakar** [comment]
> This is not specificly a problem of liquidbounce, rather a problem of your display driver. Do you have the latest version installed? (I marked this issue as invalid, because there is nothing we can do about it, but I can still try to help you)

latest version 309.08 for my graphics card alreayd. can you help me?

**Comment by MaxHD00** [comment]
Can you use Forge 1.8.9 without Liquidbounce?
