### ISSUE TITLE
[BUG]Sometime cant jump when scaffolding with scaffold module

### ISSUE THREAD

**Issue by lolmc1982** [CCBlueX/LiquidBounce1.8-Issues#3756]
**Describe the bug**
title

**Additional information:**
 - OS: Windows 10 1909 64 bit
 - LiquidBounce Build Version b72
 - Minecraft Version 1.8.9

**Comment by superblaubeere27** [comment]
Can you send your config of scaffold you use when this bug occurs?

**Comment by lolmc1982** [comment]
bruh
i dont know why this issue fixed in lastest version lol
you can close this
