### ISSUE TITLE
[Suggestion]Remove NoscoreBoard module

### ISSUE THREAD

**Issue by lolmc1982** [CCBlueX/LiquidBounce1.8-Issues#3757]
why dont remove that
we can change scoreboard pos/sca/remove it from customhud
bruh

**Comment by kawaiinekololis** [comment]
No. Scoreboard is something you often need and it's annoying to remove it from the custom hud instead of toggling on NoScoreboard. It could also happen that some people don't notice that they removed their scoreboard.
