### ISSUE TITLE
[FEATURE] Add target hud to CustomHUD

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#3761]
- Box
- Name
- Smooth Health Bar
- Armor Bar

**Comment by ChocoPieisme** [comment]
i like the smooth health bar feature xd
btw can i have a picture of it

**Comment by kawaiinekololis** [comment]
I didn't started yet, so no pictures yet.

**Comment by kawaiinekololis** [comment]
![](https://axolotl.us/No3yOI0UZ0QE14/tTMHV3fp)
Any ideas?
Looks pretty empty right now

**Comment by ChocoPieisme** [comment]
The "Distance" and "Ping" is too near, you should add "ms" and maybe more informations (useless, but kinda fun)

**Comment by Teals53** [comment]
well where is armor bar ? xd also its can be looks like more good if u add something like that
for example if enemy health is full this health bar neeed to be green and going to be red slowly every when health gonna be low more  @kawaiinekololis @superblaubeere27
