### ISSUE TITLE
[BUG] Scripts doesnt work on latest build of LB.

### ISSUE THREAD

**Issue by TheFleksisCekcu** [CCBlueX/LiquidBounce1.8-Issues#3765]
title

**Comment by SenkJu** [comment]
How are we supposed to fix a bug with that little information? I will close this issue until the necessary information is provided. What script are you trying to use? Is their an exception in the log?

**Comment by TheFleksisCekcu** [comment]
Scripts are not loading(all), i dont know how to say more.

**Comment by superblaubeere27** [comment]
@TheFleksisCekcu Ok, can you send us those scripts? We changed the ScriptAPI, older scripts might have losen their compatiblity.

**Comment by TheFleksisCekcu** [comment]
i have more than 144 scripts

**Comment by superblaubeere27** [comment]
So none of these loads? Can you send us the log of the client?

**Comment by TheFleksisCekcu** [comment]
Wait, ill send.

**Comment by TheFleksisCekcu** [comment]
[latest.log](https://github.com/CCBlueX/LiquidBounce1.8-Issues/files/4747079/latest.log)
I used old pc to log, but i used scripts from my new pc

**Comment by TheFleksisCekcu** [comment]
uhm...
there are too many errors in log
https://i.imgur.com/BFHyDmK.png

**Comment by NULLYUKI** [comment]
Try to remove the script "AAC 4.11 NO WEB.js" and start the client.

**Comment by SenkJu** [comment]
Re-download the jar file and disable your AntiVirus software if you have one. Looks like the jar file is broken.

**Comment by TheFleksisCekcu** [comment]
This is mine build of liquidbounce

**Comment by superblaubeere27** [comment]
@TheFleksisCekcu Maybe you haven't merged the changes correctly?

**Comment by TheFleksisCekcu** [comment]
CLOSED: Broken jar file + broken sources. Fixed.
