### ISSUE TITLE
[BUG] Nofall gets detected on Hypixel again

### ISSUE THREAD

**Issue by lolmc1982** [CCBlueX/LiquidBounce1.8-Issues#3766]
the lb b72 was release
why it get banned again?
sad

**Comment by lolmc1982** [comment]
before i update i use mode cubecraft(not ban)
after the update,i tried use hypixel nofall
and get ban

**Comment by superblaubeere27** [comment]
Are you sure you got banned because of the NoFall?

**Comment by kawaiinekololis** [comment]
It could be already patched. https://github.com/CCBlueX/LiquidBounce/pull/67 got merged 2 months ago, so very likely to be patched. Sorry.

**Comment by lolmc1982** [comment]
100% patched

**Comment by lolmc1982** [comment]
i can use it 2~3 time before get ban
not instant

**Comment by lolmc1982** [comment]
why no any pepe trust me lmaO
https://streamable.com/unvcsu
watch
now it instant
i use step aac mode(still working)

**Comment by superblaubeere27** [comment]
We will remove it from the configuration.
