### ISSUE TITLE
[FEATURE] Make risekey bypass

### ISSUE THREAD

**Issue by Emreploit** [CCBlueX/LiquidBounce1.8-Issues#3772]
I want client uid spoofer. Server: play.craftrise.tc
With other clients
![image](https://user-images.githubusercontent.com/41109879/84168166-be63c700-aa7f-11ea-933a-85512b2f808b.png)
With server's compulsory client
![image](https://user-images.githubusercontent.com/41109879/84174338-2964cc00-aa87-11ea-95c5-690259c15f96.png)

**Comment by superblaubeere27** [comment]
#3666
