### ISSUE TITLE
[BUG] KillAura isn't aiming at the closest point of the enemy's hitbox

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3779]
**Describe the bug**
KillAura is using the nearest point of the hitbox for the distance check, but the rotations is using the nearest point to your mouse (last rotation) which makes killaura do weird stuff like that : 
https://gyazo.com/7c86ff494af21806974555d84e000baa
You can clearly see that it's not aiming where it should aim, it aims at the feet instead of the torso

**Comment by yorik100** [comment]
It's a major issue as it's how Verus detects LB's killaura with 3.0 reach, if you aim at the feet of your opponement, you have 3.1 reach max, if you were aiming at the closest point of the enemy's hitbox, it'd be 3.0 max

**Comment by yorik100** [comment]
This bug is even more annoying with aimbot

**Comment by kawaiinekololis** [comment]
> This bug is even more annoying with aimbot
> https://gyazo.com/dee9f84515ba9db6fd9b69c39842848f LiquidBounce feet rekter edition

This is not a bug. It's just because you're aiming on his feet. He always takes the closest spot to your mouse.

**Comment by kawaiinekololis** [comment]
> It's a major issue as it's how Verus detects LB's killaura with 3.0 reach, if you aim at the feet of your opponement, you have 3.1 reach max, if you were aiming at the closest point of the enemy's hitbox, it'd be 3.0 max

This is not really a major issue. The rotations are fine, but we doesn't calculate the reach for every point of the hitbox. So we just take the closest point of the hitbox to calculate the reach.

**Comment by yorik100** [comment]
> > It's a major issue as it's how Verus detects LB's killaura with 3.0 reach, if you aim at the feet of your opponement, you have 3.1 reach max, if you were aiming at the closest point of the enemy's hitbox, it'd be 3.0 max
> 
> This is not really a major issue. The rotations are fine, but we doesn't calculate the reach for every point of the hitbox. So we just take the closest point of the hitbox to calculate the reach.

Then why don't you take that closest point and aim at it instead of making you attack your opponement's feet???

**Comment by kawaiinekololis** [comment]
> > > It's a major issue as it's how Verus detects LB's killaura with 3.0 reach, if you aim at the feet of your opponement, you have 3.1 reach max, if you were aiming at the closest point of the enemy's hitbox, it'd be 3.0 max
> > 
> > 
> > This is not really a major issue. The rotations are fine, but we doesn't calculate the reach for every point of the hitbox. So we just take the closest point of the hitbox to calculate the reach.
> 
> Then why don't you take that closest point of the hitbox and aim at it instead of making you attack your opponement's feet???

KillAura is just attacking the feet because it's the CLOSEST POINT TO YOUR LAST ROTATION (YOUR MOUSE POSITION).

**Comment by yorik100** [comment]
> 
> 
> > > > It's a major issue as it's how Verus detects LB's killaura with 3.0 reach, if you aim at the feet of your opponement, you have 3.1 reach max, if you were aiming at the closest point of the enemy's hitbox, it'd be 3.0 max
> > > 
> > > 
> > > This is not really a major issue. The rotations are fine, but we doesn't calculate the reach for every point of the hitbox. So we just take the closest point of the hitbox to calculate the reach.
> > 
> > 
> > Then why don't you take that closest point of the hitbox and aim at it instead of making you attack your opponement's feet???
> 
> KillAura is just attacking the feet because it's the CLOSEST POINT TO YOUR LAST ROTATION (YOUR MOUSE POSITION).

It should target the closest point of the enemy's hitbox, why would you make it aim at the closest point of the mouse position, that doesn't make any sense

**Comment by kawaiinekololis** [comment]
No. Not really, but it should consider the range option of your killaura for the future.

**Comment by kawaiinekololis** [comment]
Fixed it.
https://axolotl.vip/jVJhygp1bl6l97/GcyUMSb7.mp4
