### ISSUE TITLE
[BUG] AutoClicker creates insane CPS when mining

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3780]
**Describe the bug**
When mining, it still autoclicks instead of stopping, which makes you do like 30 swing animations per second, it's super easy to detect

**To Reproduce**
Mine a block while autoclicking

**Comment by superblaubeere27** [comment]
Why would you want to mine with AutoClicker

**Comment by kawaiinekololis** [comment]
Not really a bug, but we could change it.

**Comment by kawaiinekololis** [comment]
well poke is also showing cps when I'm just breaking the block without auto clicker
https://axolotl.vip/wBKZZmxUjtZxfZ/XKYwP2TD.mp4
but I know what you mean, it just doesn't really click. It's just poke.

**Comment by kawaiinekololis** [comment]
anyway I fixed it
https://axolotl.lol/v9HPkk8HI4gMjq/5ZwvwmJb.mp4
like you can see when I'm just attacking the air the jitter is working, but when I'm breaking a block it stops.
