### ISSUE TITLE
[FEATURE] NoFall Legit Option

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3781]
so basically just put water on ground in your hotbar then take it back. also with selected height settings

its usefull when u r falling and not have enought skill for do that fastly

**Comment by TheFleksisCekcu** [comment]
do it urself it easy todo

**Comment by superblaubeere27** [comment]
#2124 #2892

**Comment by Teals53** [comment]
anyone can make a script for add this option for me ?
