### ISSUE TITLE
[BUG] BowAimbot Distance And Direction Options Still Broken

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3784]
idk why its still not fixed ?

latest version*

since this https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3351

**Comment by superblaubeere27** [comment]
Because none of us was able to reproduce the bug. We can't fix something without knowing what is even is and why it is

**Comment by Teals53** [comment]
So why u closed that instantly?

**Comment by superblaubeere27** [comment]
Because it is a duplicate?

**Comment by Teals53** [comment]
but duplicated issues are closed so it doesnt matter ?

**Comment by Teals53** [comment]
@superblaubeere27 ??

**Comment by superblaubeere27** [comment]
If we are unable to reprodce a bug and we don't have instructions how to do so we will just close the issue. If we were able to do reproduce it, we will reopen and fix it.

**Comment by Teals53** [comment]
what do you want from me ?

**Comment by Teals53** [comment]
what can i do for fix this issue ?

**Comment by superblaubeere27** [comment]
A setup to reproduce the bug.

**Comment by Teals53** [comment]
what ?

**Comment by Teals53** [comment]
damn just select distance or direction options on bowaimbot and try that then see what happening

**Comment by superblaubeere27** [comment]
I tried it and I had 0 problems

**Comment by Teals53** [comment]
well i formatted my pc today and everything is fine so i dont have any problem now and its not working for me i send u video too what can i do more ? if you come discord i can share my screen so i can show you that live also i tried other pcs aka my friends and they are have same problem idk why its happen and i just wanna show this to u 

Teals53#1508

**Comment by superblaubeere27** [comment]
I have to be able to reproduce it on *my* PC

**Comment by Teals53** [comment]
So tell me when u r ready

**Comment by Teals53** [comment]
and now fully broken
