### ISSUE TITLE
[FEATURE] Update Fastalts/Thealtening API/Token

### ISSUE THREAD

**Issue by barbiehunter** [CCBlueX/LiquidBounce1.8-Issues#3787]
Fastalts ist jetzt auch über Tokens und wenn man ein Token von dort benutzt wird der als "Thealtening" angezeigt. Vielleicht anpassen damit da Fastalts steht und maybe auch den Knopf updaten oder einfach Trennen jeweils idk. 
![image](https://user-images.githubusercontent.com/38357837/84428858-7d0e1b80-ac27-11ea-8ac9-f5ed4eeecd24.png)
Edit: Die Fastalts API Funktioniert nicht bei Liquidbounce (Siehe bild) Vielleicht wird das von Xevier gefixt oder verbessert weiß ich aber natürlich nicht. 
![image](https://user-images.githubusercontent.com/38357837/84429083-e1c97600-ac27-11ea-9f9e-48dbbff43c8a.png)

**Comment by TheFleksisCekcu** [comment]
you need to get premium in TheAltening
