### ISSUE TITLE
[BUG] AAC KillAura gets kicked when you stand on Slab and Stairs

### ISSUE THREAD

**Issue by 1337quip** [CCBlueX/LiquidBounce1.8-Issues#3788]
**Describe the bug**
When I use KillAura, I get kicked when I stand on Stairs and Slab in AAC.

**To Reproduce**
Fix it

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version 72
 - Minecraft Version 1.8.9

**Comment by kawaiinekololis** [comment]
Video? Server? Config? We need more information.

**Comment by 1337quip** [comment]
OK i will upload video

**Comment by 1337quip** [comment]
Video: https://streamable.com/n0dtdo
Server: Mc-SekSin.net (Thailand only cuz this server is blocking other country)
Config: https://pastebin.com/raw/jxvXxQ5c

**Comment by ChocoPieisme** [comment]
turn off silent rotation or even rotation

**Comment by ChocoPieisme** [comment]
it's because silent rotation is patched in aac

**Comment by kawaiinekololis** [comment]
Change your Strafe option in KillAura to Strict or Silent, should fix the issue.

**Comment by KamThail** [comment]
Ok thanks i will change

**Comment by 1337quip** [comment]
Oh thanks i will try

**Comment by 1337quip** [comment]
Thanks it working very well
