### ISSUE TITLE
[BUG] Arraylist Bugs 

### ISSUE THREAD

**Issue by xHackerBey** [CCBlueX/LiquidBounce1.8-Issues#3800]
**Describe the bug**
weird color and rect rainbow-white bug
watch the video below

**Video**
https://streamable.com/q0qlek

**Additional information:**
 - OS Windows 10
 - LiquidBounce Build Version Latest Dev Build (509b6cf)
 - Minecraft Version 1.8.9

**Comment by superblaubeere27** [comment]
Fixed.

**Comment by Teals53** [comment]
Milestone ?

**Comment by Teals53** [comment]
@superblaubeere27

**Comment by SenkJu** [comment]
> Milestone ?

Since this issues refers to a bug introduced in a development build, it won't be addes to the b73 milestone.

**Comment by Teals53** [comment]
kk
