### ISSUE TITLE
[BUG] Space Between Values (or whatever idk)

### ISSUE THREAD

**Issue by xHackerBey** [CCBlueX/LiquidBounce1.8-Issues#3801]
**Describe the bug**
When you press TAB button while setting value LiquidBounce automaticly put space between words.

**To Reproduce**
1. Write .fastuse custom
2. Click on tab
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/45121448/84567142-4d722700-ad7f-11ea-8c8a-d738002396bf.png)

**Additional information:**
 - OS Windows 10
 - LiquidBounce Build Version Latest b73 (509b6cf)
 - Minecraft Version 1.8.9

**Comment by derech1e** [comment]
This should be easy to fix. There are spaces in the value definition.

**Comment by xHackerBey** [comment]
> This should be easy to fix. There are spaces in the value definition.

yeah me too think same

**Comment by derech1e** [comment]
@superblaubeere27 @xHackerBey 
This issue can be closed.
