### ISSUE TITLE
[FEATURE] Donator Cape not working on Cracked Server

### ISSUE THREAD

**Issue by 1337quip** [CCBlueX/LiquidBounce1.8-Issues#3807]
**Describe your feature request.**
Donator Cape working on Cracked Server

**Additional context**
Please

**Comment by Teals53** [comment]
if server give u a valid uuuid so whats wrong ?

**Comment by 1337quip** [comment]
> if server give u a valid uuuid so whats wrong ?

When I was on a Premium server, I had a cape, but when I was on a Cracked server, I didn't have Cape.

**Comment by superblaubeere27** [comment]
On Cracked Servers the Client can't verify your identity, so it won't give you a donator cape. I will leave this one open since I am not 100% certain if this is really intended behaviour

**Comment by Teals53** [comment]
> > if server give u a valid uuuid so whats wrong ?
> 
> When I was on a Premium server, I had a cape, but when I was on a Cracked server, I didn't have Cape.

every server not same
