### ISSUE TITLE
[FEATURE] Inventory-cleaner-customization

### ISSUE THREAD

**Issue by Kayanchi** [CCBlueX/LiquidBounce1.8-Issues#3808]
I'm always frustrated when the inventory-cleaner throws an item away that I need or when my blocks end up in the 8 slot when I have blocks for slot 8 and 9......
so I would like to customize wich items get not thrown away and wich slot is prefert for a item

And if you want to see me throwing away eggs or me having blocks in the 8th slot, you can check out the attachment
![2020-06-14_04 24 19](https://user-images.githubusercontent.com/66892428/84583308-83eb8880-adf7-11ea-8651-ff026c28d51a.png)
![2020-06-14_04 23 28](https://user-images.githubusercontent.com/66892428/84583315-8f3eb400-adf7-11ea-82d2-1c10a65b1a13.png)

And yes, I made them as lazy that I am in a creative world

**Comment by Teals53** [comment]
wtf

**Comment by Leejames2305** [comment]
#3604

**Comment by superblaubeere27** [comment]
I am planning to include a ScriptAPI-Support in the Rework of the InvCleaner. I will staert this when I know how I want to realize it

**Comment by superblaubeere27** [comment]
I will close this, if you have any other ideas, you can add them to #3604
