### ISSUE TITLE
[FEATURE] [SUGGESTION] NoInventoryClose module

### ISSUE THREAD

**Issue by TheFleksisCekcu** [CCBlueX/LiquidBounce1.8-Issues#3809]
Sometimes, when i walking in my inventory, server can close it.
I have a code for NoInvClose module, but add this to LB, please.

**Comment by lolmc1982** [comment]
it not important

**Comment by superblaubeere27** [comment]
As @lolmc1982 stated out, it isn't that much important. You can make a Script though (see https://liquidbounce.net/docs/ScriptAPI/Getting%20Started)

**Comment by kawaiinekololis** [comment]
there is already a module for it
KeepInventory
