### ISSUE TITLE
[FEATURE] Altmanager Export button 

### ISSUE THREAD

**Issue by Tcm9** [CCBlueX/LiquidBounce1.8-Issues#3818]
**Describe your feature request.**
in accounts.txt they are badly displayed. Or alt testers cannot do much with it.
accounts.txt:
["email:password", "email:password", ... ]

If you press the export button, Liquidbounce displays the alt list sorted:
email:password
email:password
...

Please add an export button, which specifies the alts cleanly one below the other and saves them in an Export_%date%.txt on the desktop.

**Comment by Teals53** [comment]
use this website for edit this things easily

https://textitor.com/

**Comment by Teals53** [comment]
u can remove all of those things just in few seconds

**Comment by kawaiinekololis** [comment]
Not really useful.

**Comment by MaxHD00** [comment]
with the old accounts.json this is not necessary, because in a text editor with "search and replace" you can easily remove the brackets and add a line break for each ",".
but with the new one, it's important
