### ISSUE TITLE
[FEATURE] Export button in Alt Manager

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#3821]
**Describe your feature request.**
A few versions ago accounts.json was quite clear. But with the new update it is now much harder to make a smart email:password out of the old ones. It is perhaps possible to convert this somehow via internet pages. Many do not know these websites. Ergo you export everything by hand. Please insert the old synthax, or add an export button, so that you have your alts sorted as txt.

What it used to look like:
![image](https://user-images.githubusercontent.com/31143468/84812558-e10d5700-b00e-11ea-91be-53c719ce1a6a.png)

The look of it now:
![image](https://user-images.githubusercontent.com/31143468/84812666-05693380-b00f-11ea-930c-30fa54d63eda.png)

How the txt should look like after the export:
![image](https://user-images.githubusercontent.com/31143468/84812982-8a544d00-b00f-11ea-8d08-5b1e08e59377.png)

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3818

**Comment by MaxHD00** [comment]
no

**Comment by Teals53** [comment]
for what

**Comment by MaxHD00** [comment]
with the old version of the .json it was still easy to convert with the alt to email:password.
in the new version this is not so easy anymore, because everything is done extra.
![image](https://user-images.githubusercontent.com/31143468/84814003-1c108a00-b011-11ea-8c0d-f5d40fa034a2.png)

**Comment by MaxHD00** [comment]
with the old one you could simply remove the brackets and add a line break when a  "," is come. For the old accounts.json I think you don't need an export button. But for the new one already

**Comment by MaxHD00** [comment]
```
const fs = require('fs');

const rawAlts = fs.readFileSync('accounts.json');
const alts = JSON.parse(rawAlts);

fs.writeFileSync('accounts.txt', '');

for (let alt of alts) {
  const { name, password } = alt;
  fs.appendFileSync('accounts.txt', `${name}:${password}\n`);
}
```

**Comment by Teals53** [comment]
oh yeah its changed in last version sorry i cant see that i think its still same like old one 
anyway yeah in this case a export button should to be good and useful

**Comment by derech1e** [comment]
> ```
> const fs = require('fs');
> 
> const rawAlts = fs.readFileSync('accounts.json');
> const alts = JSON.parse(rawAlts);
> 
> fs.writeFileSync('accounts.txt', '');
> 
> for (let alt of alts) {
>   const { name, password } = alt;
>   fs.appendFileSync('accounts.txt', `${name}:${password}\n`);
> }
> ```

Add this on your own and create a PR, if you think that is useful.

**Comment by MaxHD00** [comment]
it's not about me. I can make my own exporter or I can use
https://img.liquidbounce.net/uxc/alt-export.html
that was made especially for me. But all others who want to export hane no idea how and what

**Comment by superblaubeere27** [comment]
Duplicate #3818

**Comment by Teals53** [comment]
> Duplicate #3818

its duplicated but duplicated issue is closed ?

**Comment by MaxHD00** [comment]
No, it's not double. It's something else. We wrote about it on the discord. Senk ju told me to make an issue. The other issue is about the old version of acounts.json. It really doesn't matter there. But now it is important
