### ISSUE TITLE
[FEATURE] NoFall MLG mode should pick up water again

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3822]
so i not need take it back manually for use that couple times

**Comment by superblaubeere27** [comment]
What do you mean?

**Comment by Teals53** [comment]
i mean when nofall mlg option put water it should be take it back for use another fall

**Comment by Teals53** [comment]
well its not a remove request ? @SenkJu @superblaubeere27

**Comment by SenkJu** [comment]
@superblaubeere27 misunderstood what you meant.

**Comment by yorik100** [comment]
Take back the water that got placed by MLG NoFall

**Comment by superblaubeere27** [comment]
This feature was on implemented on purpose due to the fact that the user should decide when to pick it up.

**Comment by yorik100** [comment]
> 
> 
> This feature was on implemented on purpose due to the fact that the user should decide when to pick it up.

Doubt

**Comment by Teals53** [comment]
Damn just make a option for that so if he wanna take it manually after delay just dont open this option????? @superblaubeere27

**Comment by Teals53** [comment]
Bruh

**Comment by superblaubeere27** [comment]
@Teals53 No. You can pick the water up yourself, can't you? The user should decide when the water should be picked up.
