### ISSUE TITLE
[BUG] ChestAura

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3823]
when chestaura try to open chest sometimes it cant open chest and not try anymore for open chest just trying one time its need check chest succesfully opened or not if not need to try again for open chest

**Comment by superblaubeere27** [comment]
Then you can open the chest by hand

**Comment by Teals53** [comment]
thats already why i create this issues i wanna client do this automatically

**Comment by superblaubeere27** [comment]
Yes. But that feature would cause tons of bugs, just because you are too lazy to press on some chests manually ;D

**Comment by CzechHek** [comment]
> Yes. But that feature would cause tons of bugs, just because you are too lazy to press on some chests manually ;D

It can be easily implemented:
don't add opened chest to blacklist instantly, store it as lastchest
onPacket: check for e.getPacket() instanceof S2DPacketOpenWindow, if it is chest, add lastChest to blacklist

**Comment by Teals53** [comment]
lol

**Comment by superblaubeere27** [comment]
@CzechHek With lags this can cause lots of trouble.
