### ISSUE TITLE
[BUG] Scaffold and InventoryCleaner keeps mushrooms as block

### ISSUE THREAD

**Issue by Aleaf-Egemen** [CCBlueX/LiquidBounce1.8-Issues#3826]
title is explanatory.

**Comment by xHackerBey** [comment]
also sunflowers and maybe more idk

**Comment by Aleaf-Egemen** [comment]
Why this is still open. Are liquidbounce developers too lazy for fix? :D

**Comment by Teals53** [comment]
> Why this is still open. Are liquidbounce developers too lazy for fix? :D

no marco no dev

**Comment by SenkJu** [comment]
Not too lazy, we are just busy with other things. Currently porting LiquidBounce to a multi-version system.

**Comment by kawaiinekololi** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3908 for scaffold and tower
and this one for inventory cleaner
