### ISSUE TITLE
[BUG] Blue world border is invinsible

### ISSUE THREAD

**Issue by Aleaf-Egemen** [CCBlueX/LiquidBounce1.8-Issues#3827]
**Screenshots**
![image](https://user-images.githubusercontent.com/45121448/85038426-3a03f900-b18f-11ea-929c-01a93ce2c85e.png)
(there was a border when im using b72 and the server not removed border)

**Additional information:**
 - OS: windows 10
 - LiquidBounce Build Version latest development build
 - Minecraft Version 1.8.9

**Comment by superblaubeere27** [comment]
Might this be caused by AntiBlind?

**Comment by xHackerBey** [comment]
> Might this be caused by AntiBlind?

i will check again rn

**Comment by xHackerBey** [comment]
![image](https://user-images.githubusercontent.com/45121448/85040343-5ef96b80-b191-11ea-8541-b2c592982eb8.png)
same nothing changed

**Comment by xHackerBey** [comment]
![image](https://user-images.githubusercontent.com/45121448/85042101-789bb280-b193-11ea-8373-5cd002f94466.png)
caused by liquidbounce now remove unverified

**Comment by superblaubeere27** [comment]
No, Unverified means that we haven't reproduced it yet or we aren't able to reproduce it.

**Comment by TheFleksisCekcu** [comment]
I see the world border.

**Comment by derech1e** [comment]
> ![image](https://user-images.githubusercontent.com/45121448/85040343-5ef96b80-b191-11ea-8541-b2c592982eb8.png)
> same nothing changed

Maybe you was too far away from the border, to actually see the world border.

**Comment by xHackerBey** [comment]
> > ![image](https://user-images.githubusercontent.com/45121448/85040343-5ef96b80-b191-11ea-8541-b2c592982eb8.png)
> > same nothing changed
> 
> Maybe you was too far away from the border, to actually see the world border.

but always same not 1-2 times

**Comment by yorik100** [comment]
Happened to me with reach indicator mod, maybe it's one of your mod

**Comment by Aleaf-Egemen** [comment]
> Happened to me with reach indicator mod, maybe it's one of your mod

Okay I will test again.

**Comment by Aleaf-Egemen** [comment]
![image](https://user-images.githubusercontent.com/45121448/85324945-6ee7b700-b4d3-11ea-838f-5b7a8941c010.png)
okay solved was caused because of time changer
