### ISSUE TITLE
[BUG] InventoryCleaner ignores Delay for first action after opening inventory

### ISSUE THREAD

**Issue by bestnub** [CCBlueX/LiquidBounce1.8-Issues#3828]
InventoryCleaner instantly sortes/cleanes the first time.

**Comment by Teals53** [comment]
yeah its need for cheststealer too

**Comment by kawaiinekololi** [comment]
Not really a bug. Most anti cheats are just checking how often you click.
Should be moved to https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3677
