### ISSUE TITLE
[FEATURE] ProxyManager

### ISSUE THREAD

**Issue by Timeox2k** [CCBlueX/LiquidBounce1.8-Issues#3841]
**Describe your feature request.**
The possibility to use Proxys, like clipboard Proxy so you can press the Button then it uses theProxy like in Wurst .proxy command.

**Comment by Teals53** [comment]
duplicated ?

**Comment by Timeox2k** [comment]
no, one is Tor one is ProxyManager

**Comment by SenkJu** [comment]
Duplicate of #2009
