### ISSUE TITLE
After updating i dont have RazerKeyboard option

### ISSUE THREAD

**Issue by Roki100** [CCBlueX/LiquidBounce1.8-Issues#3844]
Uh i have razer keyboard and i had RazerKeyboard feature available on older version(s) but after updating to latest its gone
did it get removed?

**Comment by Teals53** [comment]
yeah

**Comment by lolmc1982** [comment]
because it was covert into scriptapi from lb b67
https://dl.ccbluex.net/download/skip/index.php?target=f443725b6 (the link is dead)
@SenkJu can you update the link, 404 not found .-.

**Comment by SenkJu** [comment]
You can download it as a script from here. Simply place it inside the scripts folder.
https://forums.ccbluex.net/topic/84/razerkeyboard-script
