### ISSUE TITLE
[BUG]Autopot broken

### ISSUE THREAD

**Issue by lolmc1982** [CCBlueX/LiquidBounce1.8-Issues#3848]
**Describe the bug**
https://streamable.com/z3obst
the video say all
**To Reproduce**

**Screenshots**

**Additional information:**
 - OS: Windows 10 64 bit
 - LiquidBounce Build Version Lastest dev build
 - Minecraft Version 1.8.9

**Comment by Litely1222** [comment]
no

**Comment by Litely1222** [comment]
Change grounddistance to 2
