### ISSUE TITLE
[BUG]background broken

### ISSUE THREAD

**Issue by Litely1222** [CCBlueX/LiquidBounce1.8-Issues#3852]
here : https://streamable.com/tl11jc

 - Windows 7
 - LiquidBounce Build Version [Development Build b73]
 - Minecraft Version [1.8.9]

**Comment by ChocoPieisme** [comment]
that's not a bug, it's just TOO LAGGY

**Comment by Tcm9** [comment]
i think he doesn't mean the liquidbounce animation, but his own background, which is green in liquidbounce, but not in windows.

**Comment by Tcm9** [comment]
Windows:
![image](https://user-images.githubusercontent.com/31276706/87078445-ec762b80-c224-11ea-9416-2d013bb597e5.png)
Liquidbounce:
![image](https://user-images.githubusercontent.com/31276706/87078487-fef06500-c224-11ea-9557-08c37762c48c.png)
