### ISSUE TITLE
[MODULE(?)] Rename Cubecraft Nofall As Hypixel Nofall

### ISSUE THREAD

**Issue by Aleaf-Egemen** [CCBlueX/LiquidBounce1.8-Issues#3853]
Cubecraft nofall is no longer bypassing Cubecraft. But bypass Hypixel well.

**Comment by Litely1222** [comment]
idk

**Comment by SpoilerRules** [comment]
just cubecraft sets mc.thePlayer.onGround = false, packet nofall same as it.

**Comment by Aleaf-Egemen** [comment]
lol cubecraft nofall no moe bypass hypixel
