### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by GorkemYakar** [CCBlueX/LiquidBounce1.8-Issues#3858]
Hello. My name is glory

In the new versions of LiquidBounce. As found in the Old v4.11 version of Sigma, I would like to see the Dolphin sub property of the Jesus (ie LiquidWalk) property and the BowFly sub property of the Fly feature in the same way. I hope you do it soon.

**Comment by Leejames2305** [comment]
This client will NOT use any leaked source code .

**Comment by Teals53** [comment]
they dont skid any codes like he said also LiquidWalk already have dolphin mode and we have a issues for bowfly and lastly which type of fly modes r u saying ? there already have lot of things for bypass fly  ?

**Comment by GorkemYakar** [comment]
> they dont skid any codes like he said also LiquidWalk already have dolphin mode and we have a issues for bowfly and lastly which type of fly modes r u saying ? there already have lot of things for bypass fly ?

That dolphin actually not "that dolphin" man Sigma's Dolphin if you walk on the water Sigma's dolphin Fly your character
use and tell them

**Comment by Teals53** [comment]
Wtf so u mean other bypass ? Then whats not exist in liquidbounce ?

**Comment by GorkemYakar** [comment]
> Wtf so u mean other bypass ? Then whats not exist in liquidbounce ?

i will show you with video

**Comment by Teals53** [comment]
ok

**Comment by GorkemYakar** [comment]
> ok

https://anonfiles.com/b8f4dcGdo2/bandicam_2020-07-15_16-28-24-691_avi

**Comment by Teals53** [comment]
> > ok
> 
> https://anonfiles.com/b8f4dcGdo2/bandicam_2020-07-15_16-28-24-691_avi
> 
> sorry for game and pc freezes this pc is old and very slow

next time try to use website like streamable

**Comment by Teals53** [comment]
still same what i say before, we already have a issue for a bowfly(since two years not added yet) so forgot that and this dolphin looks like vanilla liquidwalk with high jump but if not so if its a custom bypass with a different method they cant add this from other clients its mean code skidding and like i say before they not skid any codes so if u wanna see this bypass in Lb just hope someone do that or do it yourself idk xd

**Comment by Aleaf-Egemen** [comment]
LiquidBounce doesn't skid codes from other clients or leaks etc.

**Comment by MaxHD00** [comment]
I've been doing this Water NCP high jump myself for a long time. There is also a script for Liquidbounce. But the NCP dolphin from Sigma is bad. Mine goes much higher and much further. Slowly got the Dolphin from me. So he coded it himself, but with my help. But please don't get involved in these Sigma issues. Sigma is not a good client right now. I can hear the fall damage sound in the video. It's totally sloppy. You shouldn't get the fall damage. I'm thinking about reprogramming the NCPDolphin into my big script, but please don't do the sigma issues.
