### ISSUE TITLE
[FEATURE] Better AltManager

### ISSUE THREAD

**Issue by Aleaf-Egemen** [CCBlueX/LiquidBounce1.8-Issues#3866]
New options for altmanager. for example favourite alts. ban checker (i saw that on sigma). sorting, alphabetical, unbanned, last used or more. and next alt and random unbanned alt option for random alt button.

**Comment by Tcm9** [comment]
First of all, stop with sigma. When sigma is mentioned, the issue is usually simply closed. We are not skidders or writers from other known clients.
And the second is that I have already posted this idea.

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3205

**Comment by yorik100** [comment]
> 
> 
> First of all, stop with sigma. When sigma is mentioned, the issue is usually simply closed. We are not skidders or writers from other known clients.
> And the second is that I have already posted this idea.
> 
> #3205

It isn't skidded when you code it by yourself bruv, also, NCPBHop is from Tomato client

**Comment by Aleaf-Egemen** [comment]
> > First of all, stop with sigma. When sigma is mentioned, the issue is usually simply closed. We are not skidders or writers from other known clients.
> > And the second is that I have already posted this idea.
> > #3205
> 
> It isn't skidded when you code it by yourself bruv, also, NCPBHop is from Tomato client

I agree with you.

**Comment by Aleaf-Egemen** [comment]
> First of all, stop with sigma. When sigma is mentioned, the issue is usually simply closed. We are not skidders or writers from other known clients.
> And the second is that I have already posted this idea.
> 
> #3205

Sorry for duplicate i wasn't know

**Comment by Tcm9** [comment]
I mean the sigma client alone, actually. In the meantime almost everything that sigma has but lb is not mentioned here. Annoys meanwhile. Especially because the proposal is usually already an issue.
