### ISSUE TITLE
[FEATURE] Visual mode in Criticals

### ISSUE THREAD

**Issue by ChocoPieisme** [CCBlueX/LiquidBounce1.8-Issues#3868]
**Describe your feature request.**
Add a visual mode in criticals that will spawn critical particles on hit. This is literally 1 line, so why not add it?

**Comment by Tcm9** [comment]
Because it's already in there... It's down in the killaura module. FakeCrits or something like that.

**Comment by ChocoPieisme** [comment]
> Because it's already in there... It's down in the killaura module. FakeCrits or something like that.

R U SERIOUS IT'S FAKE SHARP AND KILLAURA'S FAKECRIT ONLY WORK IF YOU ARE IN THE AIR

**Comment by Teals53** [comment]
but why are you yelling ?
