### ISSUE TITLE
[BUG] Scaffold KeepRotationLenght Bug

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3878]
basically not work or i understand this option wrong ?

**Comment by lolmc1982** [comment]
If you use that
you need to turn off keeprotation in scaffold

**Comment by Teals53** [comment]
> If you use that
> you need to turn off keeprotation in scaffold

i already close that but no thats not changing anything ?

**Comment by Teals53** [comment]
oh fuck i understand this wrongly anyway.
