### ISSUE TITLE
[BUG] Criticals NoGround Mode

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3884]
idk its bug or not but when i open criticals with noground mode and when i try to break blocks its breaking slowly like i am always in air maybe its causing of crit spoof you u r always in air also i can fix this with noslowbreak xd

**Comment by Litely1222** [comment]
:thinking:

**Comment by lolmc1982** [comment]
criticals noground spam onground = false
make server think you are not on ground=>break block slower
just use Noslowbreak module to bypass it

**Comment by Teals53** [comment]
> criticals noground spam onground = false
> make server think you are not on ground=>break block slower
> just use Noslowbreak module to bypass it

yeap i think same and i just open this issue for correct myself ^^
