### ISSUE TITLE
[BUG] Silent Strafe mode caused KillAura facing checks failure

### ISSUE THREAD

**Issue by Leejames2305** [CCBlueX/LiquidBounce1.8-Issues#3885]
**Describe the bug**
Silent Strafe mode caused KillAura facing checks failure again. ( Doesn't when KillAura Strafe mode is off )

**To Reproduce**
1. Turn KillAura Strafe mode to Silent
2. Walk around in a circle while hitting your enemies

**Screenshots**
https://ctrlv.tv/yJOL

**Additional information:**
 - Latest LiquidBounce B73 DEV ( Not the cross version one )
 - Minecraft 1.8.9

**Comment by superblaubeere27** [comment]
This is not a bug. KillAura is just unable to rotate to the target while you are moving. Just turn the Rotation speed up and you should be good. Otherwise you can enable HitBox

**Comment by Leejames2305** [comment]
Ok
