### ISSUE TITLE
[BUG] fix shortcut syntax

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3891]
![image](https://user-images.githubusercontent.com/13446881/89899340-cf999300-dbea-11ea-80a7-32fb5ace2b1b.png)

**Comment by Teals53** [comment]
also i forget what shortcut do ?

**Comment by CzechHek** [comment]
What did you write?

**Comment by Teals53** [comment]
.shortcut

**Comment by Teals53** [comment]
Its done ? @kawaiinekololi

**Comment by Teals53** [comment]
weird
