### ISSUE TITLE
[BUG] REJOIN BUG

### ISSUE THREAD

**Issue by EthanSolid** [CCBlueX/LiquidBounce1.8-Issues#3892]
**Describe the bug**
Sometimes when you click rejoin after it says "Connecting to *server IP*" the server gives the error "You are already connected to server" so you can't join the server back for about a minute but the thing is it doesn't happen every time so its confusing, I can't tell if it's just happening to me or it's a Liquidbounce bug but might post it here to make sure it's not a Liquidbounce bug.

**To Reproduce**
Steps to reproduce the behaviour:
1. Join a server
2. Press ESC on your keyboard
3. Click "Rejoin"
4. You might get the error "You are already connected to server"

**Screenshots**

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version: Latest b73 (June 21, 2020, 1:20 am)
 - Minecraft Version: 1.8.9

**Comment by Leejames2305** [comment]
That's why there is something called AutoReconnect

**Comment by Teals53** [comment]
thats not a lb bug its a serverside bug so they cant do anything about that

**Comment by NurMarvin** [comment]
That's not a bug in LiquidBounce, that's an issue of the server you are trying to connect to.
