### ISSUE TITLE
[FEATURE] CustomHUD Health/MaxHealth/Food Option

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3899]
Health: %health%
![image](https://user-images.githubusercontent.com/13446881/90986292-67539580-e58a-11ea-907e-5dd8b09477ec.png)

**Comment by Aleaf-Egemen** [comment]
![image](https://user-images.githubusercontent.com/45121448/90986484-e09fb800-e58b-11ea-9973-81c2d3123c34.png)
