### ISSUE TITLE
[BUG] Velocity in 1.8.9-Forge in the devbuild doesn't work as expected

### ISSUE THREAD

**Issue by commandblock2** [CCBlueX/LiquidBounce1.8-Issues#3903]
**Describe the bug**
Velocity in 1.8.9-Forge in the devbuild doesn't work as expected

**To Reproduce**
1. choose simple mode in velocity.
2. no matter horizontal/vertical was set it all behave like 0,0
3. most of other modes has this behavior as well

**Additional information:**
 - OS: Gentoo GNU/Linux
 - LiquidBounce Build Version b73 c784d84 (tested both in self built one and the github one)
 - Minecraft Version 1.8.9

**Comment by yorik100** [comment]
> **Describe the bug**
> Velocity in 1.8.9-Forge in the devbuild doesn't work as expected
> 
> **To Reproduce**
> 
> 1. choose simple mode in velocity.
> 2. no matter horizontal/vertical was set it all behave like 0,0
> 3. most of other modes has this behavior as well
> 
> **Additional information:**
> 
> * OS: Gentoo GNU/Linux
> * LiquidBounce Build Version b73 c784d84 (tested both in self built one and the github one)
> * Minecraft Version 1.8.9

Don't tell me that you tried on Hypixel

**Comment by commandblock2** [comment]
I found this in single player. Also happens in other servers. ik Hypixel just use explosion packets which would be canceld. But the problem is velocity packets is canceled in 1.8.9-Forge cross_version because of it is recognized as explosion packet and got canceled. `override fun isSPacketExplosion(obj: Any?): Boolean = obj is PacketImpl<*> && obj.wrapped is S12PacketEntityVelocity` which is supposed to be `S27PacketExplosion`
