### ISSUE TITLE
[BUG] Remove Vanilla ?

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3906]
![image](https://user-images.githubusercontent.com/13446881/91647268-89a15380-ea61-11ea-8077-d90ec8ec2734.png)
vanilla need to remove or not ? or 1.12 need to add ?

**Comment by Teals53** [comment]
@kawaiinekololi

**Comment by kawaiinekololi** [comment]
sure I'll add it

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3907

**Comment by kawaiinekololi** [comment]
done
