### ISSUE TITLE
WTF ? !

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3907]
fake marco ? double marco ?
![image](https://user-images.githubusercontent.com/13446881/91647891-37fcc700-ea69-11ea-81ef-14fd10b99c8a.png)

**Comment by yorik100** [comment]
One account got stolen by Germany itself smth like that

**Comment by Teals53** [comment]
> One account got stolen by Germany itself smth like that

wtf why what xD

**Comment by kawaiinekololi** [comment]
we'll that's true.

**Comment by kawaiinekololi** [comment]
Don't ask.

**Comment by Teals53** [comment]
ok im happy cuz u r comeback and maybe u take your eqiupments again :d
