### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3912]
why %90 of autosettings have shitty outdated idiot and not bypassing stuff also not clear ? inculded hypixel lol

**Comment by lolmc1982** [comment]
https://github.com/CCBlueX/LiquidCloud/pull/61
Small update
Iam not have time to update it

**Comment by Teals53** [comment]
i not mean just u dude

**Comment by yorik100** [comment]
Why would someone use autosettings bruh

**Comment by Teals53** [comment]
> Why would someone use autosettings bruh

what ? why not ? lol

**Comment by kawaiinekololi** [comment]
It's hard for us to keep the settings up-to-date ourself. There are sadly just a few people doing pull requests.

**Comment by ghost** [comment]
I would update the jartexnetwork one, but it would need a few requirements:

1. #3913 
2. AutoBlock fix, which right now there's a script for that but still appreciated if the developers would fix it: https://github.com/CzechHek/Core/commit/b9e5d8bffa9bbef8648f422897d56f4e6f60c05a
