### ISSUE TITLE
[BUG] weird forge buttons

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3916]
![image](https://user-images.githubusercontent.com/13446881/92125573-d8efd700-ee07-11ea-96dc-5c1d4898ca9e.png)
weird bug when i click buttons

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/afafda7bfa4f1949ee51398123498af686208832

**Comment by 1zun4secondary** [comment]
It has been fixed already.

**Comment by Teals53** [comment]
yeah i just open that for add milestone xD @kawaiinekololi

**Comment by Teals53** [comment]
bcs old one is not a single issue
