### ISSUE TITLE
[BUG] bowaimbot...

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3918]
bowiambot fully broken now (in older versions just health options is working) also fast use instant mode is broken too like i say on differnet issue bruh...

**Comment by 1zun4secondary** [comment]
Can you stop reporting your "bowaimbot" issues cuz you're the ONLY ONE with the issue and we can't reproduce it. Nobody else is complaining. Same for FastUse Instant. Works fine for me, wdym?

**Comment by Teals53** [comment]
maybe i am a selected person who living this shits alone xD

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/fa703b804d8fbd180665e9fc398a9da8447e3df6
fixed finally xD
