### ISSUE TITLE
[BUG] ServerStatus

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3920]
new one
![image](https://user-images.githubusercontent.com/13446881/92148386-2a5a8f00-ee25-11ea-98d1-793441f5f2fc.png)

old one
![image](https://user-images.githubusercontent.com/13446881/92148408-35152400-ee25-11ea-8f69-7cdef6e0415a.png)

**Comment by Teals53** [comment]
this white color is a bug like old buged titles or just a difference ?

**Comment by 1zun4secondary** [comment]
Not a bug.
