### ISSUE TITLE
[BUG] InventoryCleaner Not Working

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3921]
invcleaner not doing anything if auto armor closed, and its not working properly with auto armor.

with latest build on blocksmc with .config load blocksmc

**Comment by derech1e** [comment]
Bro your issues are so cracked. It's not for nothing a development build. So there are **BUGS**. You reportet this bug many times. It doesn't help at all if you write it so often. I will write a conclusion/ summary tommorow, were I'm going to describe everything exactly. I thik it makes the recode easier. If I have time this weekend, i try to prepare a recode base and create a PR. So the recode should then finish quicker. Dont **SPAM** the same **ISSUE** **continuously**
Thanks.

**Comment by Teals53** [comment]
well firstly sorry and i wanna say its my first single issue about this bug bcs old one have lot of stuff and i parse that per issue per bug and i think this one have differnet information too if compare yorik issue or not idk anyway thx

**Comment by derech1e** [comment]
I meant that in general for all of your reports / comments, for example with the Bowaimbot. But okay. I will write a summary.

**Comment by Teals53** [comment]
from last commit bowaimbot is fixed finally..

**Comment by derech1e** [comment]
> well firstly sorry and i wanna say its my first single issue about this bug bcs old one have lot of stuff and i parse that per issue per bug and i think this one have differnet information too if compare yorik issue or not idk anyway thx



> I meant that in general for all of your reports / comments, for example with the Bowaimbot. But okay. I will write a summary.

Summary: #3928
