### ISSUE TITLE
[BUG] command

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3922]
value ? xD
![image](https://user-images.githubusercontent.com/13446881/92248674-b3c79b00-eed1-11ea-89dc-545a2e1b6220.png)

**Comment by Teals53** [comment]
@kawaiinekololi there is no value option for autorespawn dude ?

**Comment by derech1e** [comment]
> @kawaiinekololi there is no value option for autorespawn dude ?

There is a value! A Boolean value: true/false.

**Comment by Teals53** [comment]
fuck im idiot
