### ISSUE TITLE
Question about bypass forge

### ISSUE THREAD

**Issue by Quin32** [CCBlueX/LiquidBounce1.8-Issues#3929]
If bypass forge is off and a server looks at my modlist will they see LiquidBounce as one of them?

**Comment by Teals53** [comment]
nope maybe its just seeing you r logged with forge

**Comment by Quin32** [comment]
But it should show the rest of my mods in the list right?

**Comment by yorik100** [comment]
> But it should show the rest of my mods in the list right?

Only if they have a plugin to check the mods you're using which is uncommon

**Comment by 1zun4secondary** [comment]
LiquidBounce is a core mod which means it doesn't show up in the mod list. (& not for the server)
