### ISSUE TITLE
[BUG] Latest Build Broken

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3937]
I cant play on latest build its stuck on there
![image](https://user-images.githubusercontent.com/13446881/93015024-7ee8d180-f5be-11ea-9a7b-80eb044231bb.png)

**Comment by Teals53** [comment]
well its not working with optifine @kawaiinekololi

**Comment by Teals53** [comment]
also where is fonts 
![image](https://user-images.githubusercontent.com/13446881/93015201-169aef80-f5c0-11ea-9bea-6d7b49981e19.png)

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/93015234-6f6a8800-f5c0-11ea-8ed7-e3299e9d4069.png)
and same sht again

**Comment by 1zun4secondary** [comment]
How about sending me your client log? Which Hardware are you using? etc
Stop creating useless issues where you just say: *smth* not working!

**Comment by ghost** [comment]
I don't know what you're talking about, loads fine on my PC.

**Comment by Teals53** [comment]
my specs (not my main)
![image](https://user-images.githubusercontent.com/13446881/93017395-0e977b80-f5d1-11ea-84e0-bf808cfda88f.png)
![image](https://user-images.githubusercontent.com/13446881/93017396-16572000-f5d1-11ea-8523-5d553d5e9398.png)

my logs
i really dont understand what tf is that, but now its working after i clear my .mc folder old logs settings etc

information
if i delete optifine in mods folder its working but if i have optifine in mods folder its stuck white screen like that and im playing 10 fps without optifine xD

also sorry for this shitty issue style fuck me im retard

**Comment by Teals53** [comment]
thats f/cking weird

**Comment by Teals53** [comment]
but really where are the fonts and why thats 0 kb xd

**Comment by Teals53** [comment]
ok now i understand why its happen
basically if u play with upper version like 1.16 with optifine and your optifine settings file changed for that then after trying to open liquidbounce this bug is happen, so cuz of that if u do smth like that u must be need delete your optisettings txt

**Comment by Teals53** [comment]
[latest.log](https://github.com/CCBlueX/LiquidBounce-Issues/files/5221652/latest.log)
and here the log can u check it ? @kawaiinekololi
