### ISSUE TITLE
Special Items (like 1.11 Version) in the Creative inventory

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#50]
Schaut euch mal das Kreativ Inventar in der 1.11.2 Version an von LiquidBounce, dort sind spezielle Items welche sehr cool sind.

Was ich mir wünsche:

Kopf Suche (Alle Köpfe aus der MC Datenbank)
Crash Items
Troll Items
Grief Items

**Comment by Marco-MC** [comment]
Nein, sorry ich werde es vielleicht in einem anderen Update einbauen aber nicht in der b24. Ich habe mich für dieses Update zu viel vorgenommen.

**Comment by Benjarobbi** [comment]
@Marco-MC push

**Comment by Marco-MC** [comment]
https://gyazo.com/e834fae985f5c9e264d72aeb1d433910
https://gyazo.com/a35bc1d215c2a079748f8053f09bb053
Added.
