### ISSUE TITLE
Settings im Panel der Kategorie (ClickGUI)

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#51]
Packt bitte die Settings in den Kategorie Reiter, und nicht daneben, dann ist es viel übersichtlicher, und wird durch Scrollen auch nicht zu groß.

Und falls das nichts wird, macht bitte die Settings an der Seite scrollbar, dass man auch auf kleineren Bildschirmen alles sehen kann.

**Comment by Marco-MC** [comment]
Wie ist das jetzt gemeint?

**Comment by Marco-MC** [comment]
Okay, verstehe... Ja könnte ich machen nur ist das wieder so etwas leicht komplexes.

**Comment by Linus789** [comment]
Ich finde das es rechts angezeigt gut, aber es sollte schon scrollbar sein. Denn wenn man die Gui-Größe auf Groß hat, fehlt ein Teil.

**Comment by RealFantaCoke** [comment]
Dann stellst du die Scale bei dem Modul "ClickGUI" in der Kategorie "Render" etwas runter.
Ich habe meine GUI-Größe auf Groß, und die Scale des GUI's auf 0.7 (ab und zu sogar tiefer).

**Comment by MaxHD00** [comment]
ja aber die HUD bleibt auch riesig. Ich spiele ja gerne auf automatisch. nur die gui passt da 0% rein. Sonnst finde ich die Gui aber super.

**Comment by MaxHD00** [comment]
Aber bitte so das es einstellbar ist. Das derzeitige design würde ich besser finden.
