### ISSUE TITLE
NoSlowdown Settings

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#572]
![image](https://user-images.githubusercontent.com/13446881/27003867-71f3ac14-4e07-11e7-893d-e8b3f193a3cf.png)

**Comment by MaxHD00** [comment]
Man soll es aber alles noch einstellen können wie stark der Noslowdown ist. Sneak kann mal auf 8% machen.
Swordblock muss man auf 80% machen bei 100% wird man geflagt.

[------[]----] Waterslow
[---[]-------] Sneak
[-[]---------] SwordBlock
[-[]---------] Soulsand
[--[]--------] Eat
[--[]--------] Bow

PS: ne web braucht man nicht. gibt je ein Extra hack dafür.

**Comment by MaxHD00** [comment]
Marco. So das mit dem noslowdown% wird nicht richtig funktionieren können. Wenn ich noslowdown% auf 75% machen würde würde zwar NoSwordblock gehen aber beim Sneaken würde ich dauernd zurückgebugt werden. Da muss man schon jedes einzeln einstellen. Und am besten und am einfachsten geht das vom letzten Kommentar.

**Comment by MaxHD00** [comment]
Wenn du es anders machst kannst du es direkt sein lassen. Bringt nämlich nichts. (wenig)

**Comment by Teals53** [comment]
WOULD YOU STOP WRİTİNG GERMAN ? I DONT UNDERSTAND YOU

**Comment by MaxHD00** [comment]
you can use google translate ^^

**Comment by MaxHD00** [comment]
http://www.fotos-hochladen.net/view/unbenanntyl7ugfwk9r.png

**Comment by MaxHD00** [comment]
nur halt in der clickgui

**Comment by Teals53** [comment]
Google Translate Does not translate properly I Dont Understand Google Germany>Turkish Translate

**Comment by MaxHD00** [comment]
-.-

**Comment by superblaubeere27** [comment]
Why?

**Comment by Marco-MC** [comment]
I will just add a option for
Sword
Food
Bow
and
soulsand

**Comment by Teals53** [comment]
yes its good bcs aac noslow bypass eating or arrow but not bypass some server soulsand

**Comment by Marco-MC** [comment]
Added
