### ISSUE TITLE
AACBHOP | AAC 3.1.7/AAC 3.2.0 | 

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#576]
https://www.youtube.com/watch?v=FC-H9RzJgYk

**Comment by Marco-MC** [comment]
wtfff xddd
this bhop is so fucking slow
slower than legits.

**Comment by Teals53** [comment]
PDOIAKJOFRAEWDKFRAWEFD :D

**Comment by Teals53** [comment]
This Turkish laughter symbol

**Comment by Teals53** [comment]
a:RAWfdrQWA:RFQ 
qwERQ:ERQWERQWRWQR
afopakfaı9ofjuaweıofdjaews
sjsjssjssjsjsjsjs
OPWASKJDFQWAEIRFJWAEMFDS
AWDOPQWAFÖSCPOSAFCA
FAKOPDFKAÖFDAWE

it is a random laught symbol
All you need to do is press the keys on the keyboard
Like this kkkkkkkkkkk or jajajajajaja

**Comment by MaxHD00** [comment]
k?

**Comment by Teals53** [comment]
what is k ?

**Comment by MaxHD00** [comment]
ok?

**Comment by Marco-MC** [comment]
We got a bhop for the AAC 3.2.0 from Trol. ^^

**Comment by MaxHD00** [comment]
nice
