### ISSUE TITLE
AAC 3.1.7/3.2.0 Reverse Velocity

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#577]
https://www.youtube.com/watch?v=KiDEtFaMeWw

**Comment by Marco-MC** [comment]
Reserve Velocity:

.velocity horizontal -1
.velocity vertical -1

**Comment by MaxHD00** [comment]
er meint ein bypass für aac velocity. mit .velocity horizontal -1 .velocity vertical -1 wird man gebannt. Und jetzt gibt es ein bypass dafür.

**Comment by Marco-MC** [comment]
Added.
