### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#579]
Die Tentakeln von Tintenfischen. Der Schwanz von Hunden ect.
Drehen sich ständig im Kreis. (nicht normal)
http://www.fotos-hochladen.net/view/20170610191bl9t5g67nd.png

**Comment by Marco-MC** [comment]
Der Bug kommt von OptiFine.
Daher ist der eh wegen der Injection dann gepatcht.

**Comment by MaxHD00** [comment]
ok
