### ISSUE TITLE
Antibot optionen 

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#580]
- Firsthit (Killaura schlägt nur die Spieler die ich (in dieser Runde) mindestens 1 mal gehittet habe. (du musst also ein Spieler 1 mal hitten der Rest macht die Killaura (Timolia Bypass)))

- Secondlyhit (Die Killaura schlägt nur die Spieler die dich mindestens 1 mal geschlagen haben (und dir mindestens 0,5 Herzen abgezogen haben.)) (für jeden Server ein bypass (ausser Timolia))

Bugs: 

- Wenn Tab aktiviert ist schlägt die Killaura keine Spieler wenn die Spieler eine Bestimmte farbe haben.
  Tab soll nur überprüfen ob der spieler in der Tab-liste drin ist und nicht welche Farbe er hat.

- Health wenn ein Spieler mehr als 10 Herzen hat schlägt die Killaura nicht mehr. 
Health soll nur überprüfen ob der gegnerische Spieler seine Leben ständig wechselt.

**Comment by MaxHD00** [comment]
Diese Einstellungen können in die B27 oder 26,1 kein kommen.

**Comment by MaxHD00** [comment]
.

**Comment by superblaubeere27** [comment]
Ok

**Comment by Marco-MC** [comment]
FirstHit Idee ist umsetzbar, was ich auch machen werde.
SecondlyHit ist schon möglich, nur giebt mir Minecraft nicht die möglichkeit  wer dich einmal geschlagen hat.
Der Tab bug ist eigentlich kein richtiger Bug... Er soll das eigentlich auch so machen. Ich weiß nicht ob ich da noch ne extra Mode rein mache.
Health ist auch kein Bug, da Health checken soll ob der Spieler mehr Herzen hat als 10. :)

**Comment by Marco-MC** [comment]
- [ ] Need Hit (FirstHit)
- [ ] HealthChanged
