### ISSUE TITLE
Autoarmor bypass NewItemTimer

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#581]
Wenn du Rüstung aufhebst dauert es (nach dem Inventar öffnen)  3 Sekunden bis du die Rüstung anzieht. (Zählt auch wenn dir jemand eine Rüstung mit /give gibt) (Gommebypass und nicht nervig wie der Autoarmor bypass Gomme.)

**Comment by SenkJu** [comment]
AutoArmor InvOpen tut das und bypasst GommeHD. Und bitte schreib in Englisch.

**Comment by MaxHD00** [comment]
ok
