### ISSUE TITLE
InventoryPlus (XCarry)

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#582]
Allows you to carry stuff in the crafting slots of your inventory

**Comment by MaxHD00** [comment]
gibt es das nicht schon???? lol

**Comment by MaxHD00** [comment]
lol echt nicht. Dachte es währe dabei XD

**Comment by Marco-MC** [comment]
Ich dachte auch das giebt es schon. MEDUSA EFFEKT. :⭕️

**Comment by MaxHD00** [comment]
Ich hoffe es wird nicht Xcarry heissen. Nennt es InventoryPlus oder Morecarry.

**Comment by Marco-MC** [comment]
Added.
