### ISSUE TITLE
Tracer

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#583]
Plz irgend ein Tracer update. So wie es jetzt ist ist es lame.

**Comment by MaxHD00** [comment]
Das währe am Besten:

Farbe:
Wenn der Spieler sehr nah ist soll der Tracer rot sein. Und umso der spieler sich entfernt um so grüner wird die Farbe vom Tracer. (von rot zu gelb und von gelb zu grün) (komplett gelb soll es bei 40 blöcken sein) (bei Freunden bleibt es blau) (0-40 Blöcken rot zu gelb)(40-100 Blöcken gelb zu grün) (100+ grün)

**Comment by superblaubeere27** [comment]
Hmm, kann man mehrere Modi machen wie:
### > Mode
   - Near
   - Health
   - Teamcolor

**Comment by MaxHD00** [comment]
+1

**Comment by IloveRickandmorty** [comment]
Ja währe richtig cool. Am besten noch, dass man die Strichdicke vom Tracer einstellen kann.

**Comment by Marco-MC** [comment]
@IloveRickandmorty Kommst du dir nicht irgendwie lächerlich vor wenn du dir deine eigenen Sache hoch lobst?
Du bist MaxHD, als ob ich das nicht checke. So dumm bin ich auch wieder nicht.
Natürlich sage ich nicht wie ich es mir aufgefallen ist. ;)

**Comment by DieErdnuss** [comment]
Mit der hochlobung meine ich superblaubeere und nicht meins.
Zudem ist es nicht schwer mich zu identifizieren. Ich bin 1 der wenigen die eine issue schreiben xD zudem hiess ich auch so auf discord.

**Comment by DieErdnuss** [comment]
Vorallem kann man es sehen weil ich oft mit () oder [] schreibe. Wer bitteschon schreibt ausser mir  mit () oder []. Naja. XD ausserdem mache ich halt am meissten issue. Wobei es dir eigendlich helfen sollte. Du musst es ja nie sofort machen. Ich schreibe die ideen und 2 Versionen später ist es dann irgenwann drin.
