### ISSUE TITLE
ServerCrasher

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#584]
ServerCrasher soll diese Modis haben:

- CreativeItemSpam

- CreativeItemDrop

- Swing

- AACNew

- AACOther

- AACOld

- WorldEditCrasher

(AACNew, AACOther, AACOld und WorldEditCrasher werden zu einem Modul zusammengefügt.)

(Umbenennung AACNew soll zu AAC3.1.5)

(Umbenennung AACOther soll zu AAC(in welcher Version geht dieser Crash))

(Umbenennung AACOld soll zu AAC(in welcher Version geht dieser Crash))

**Comment by MaxHD00** [comment]
Wenn man den Server verlässt (oder gekickt wird) soll sich ServerCrasher automatisch ausschalten.

**Comment by superblaubeere27** [comment]
Sry, aber für die ersten 3 nutz Wurst, ausser Swing :smile:

**Comment by MaxHD00** [comment]
-.- CreativeItemSpam CreativeItemDrop hat kein wurst. ok CreativeItemSpam aber der ist total scheisse und funktioniert kaum.

**Comment by superblaubeere27** [comment]
Ah ok, können wir vlt mal umsetzen
