### ISSUE TITLE
rename modules.

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#585]
LiquidWalk > Jesus
Trigger > Triggerbot
Velocity > AntiKnockback
NoSlow > NoSlowdown
StorageESP > ChestESP

**Comment by SenkJu** [comment]
LiquidWalk: Because of LiquidBounce.
Trigger: Why should we rename it?
Velocity: No, because its not necessarily NoKnaokback.
NoSlow: Why?
StorageESP: No, because it doesn't only show chests but also everything else which can store items.

**Comment by MaxHD00** [comment]
k
