### ISSUE TITLE
CamaraNoClip

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#586]

**Comment by SenkJu** [comment]
Use Freecam

**Comment by MaxHD00** [comment]
Im livestream sagte marco er fügt es ein. Ich habe es jetzt halt nochmal hingeschrieben.

**Comment by MaxHD00** [comment]
Zudem nervt das zoomen immer. Ich verwende f5 jedesmal und wenn er dann zoomt fuckt es ab.
