### ISSUE TITLE
Sneak modes

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#587]
- Normal (Von Server aus Sneakst du. Aber ingame sneakst du nicht. (du läufst normal))

- Switch (du Sneakst dann wieder nicht dann Sneakst du wieder dann wieder nicht. (ist wie als ob du die Sneak taste spammst.))

- Legit (du Sneakst dauerhaft ohne die Sneaktaste gedrückt zu halten.)

- Motion (Von Server aus Sneakst du. Aber ingame sneakst du nicht. jedoch hast du noch einen speed an der dich auf die gleiche Geschwindigkeit bringt wie Unsneak. (Funktionierte mal auf AAC. inzwischen kp.) 

(Motion kannst du wenn du willst auch lassen.)

**Comment by superblaubeere27** [comment]
Legit nich "Lagit"
