### ISSUE TITLE
NCP phase

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#588]
Wenn ich in LB b25.5 phase (skip), Teleport(blink) und NoClip an habe kann ich mich oft durch alle Blöcke porten. Daraus kann man ein neuen NCP phase machen. 

Der Teleport wählt automatisch 2 Blöcke vor sich aus. + NoClip + phase (skip) ergibt NCPPhase.

**Comment by superblaubeere27** [comment]
Dann machs doch so

**Comment by MaxHD00** [comment]
viel zu umständlich.

**Comment by MaxHD00** [comment]
(es geht nicht. Ich hatte es nur auf eurem Server getestet. Da aber auf Ncp bei euch jeder Phase durchgeht geht das hier doch nicht.)
