### ISSUE TITLE
Deadspawn

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#589]
Wenn du stirbst spawnst du direkt da wo du gestorben bist. 

AAC ist das relativ leicht. Genau wenn du stirbst Versuchst du dich zu teleportieren. (Du musst dich 3 Sek die Ganzezeit Teleportieren)  AAC flagt dich und schon bist du am Todespunkt. So war es jedenfals bis jetzt. Ob es fürs neuste AAC geht Kp. Noch nicht getestet.

**Comment by SenkJu** [comment]
Auf Vanilla geht das nicht. Das funktioniert nur, weil AAC dich flagt.

**Comment by MaxHD00** [comment]
ok dann nur aac

**Comment by MaxHD00** [comment]
Wie er immer alles sofort mitbekommt XD

**Comment by MaxHD00** [comment]
Dieser grüne Ring erinnert mich an Zelda XD Die Ausdauerleiste XD

**Comment by Crax9999** [comment]
Man könnte es setback nennen (heißt so bei Ambien)

**Comment by MaxHD00** [comment]
Set back erinnert mich an das modul Bugup. Ne das passt nicht.

**Comment by MaxHD00** [comment]
warum abgelehnt? das ist doch eine gute idee. Funktionieren tut es auch.

**Comment by maxhd0** [comment]
Hem

**Comment by maxhd0** [comment]
Also doch abgelehlt ._.
