### ISSUE TITLE
Hide and seek ESP

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#590]
Fallende Objekte werden vom ESP angezeigt. (Wenn sie zum Festen Block werden sollen sie immernoch vom ESP angezeigt werden. )

**Comment by Crax9999** [comment]
Warum?

**Comment by Marco-MC** [comment]
Junge. @superblaubeere27 lass einfach die Issues entruh boar.

**Comment by Marco-MC** [comment]
Du kannst die Labels setzen, aber was ich annehme und was nicht entscheide noch ich.
