### ISSUE TITLE
Fast villager buy-gui

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#593]
Neben der normalen Villiger gui sollen alle Prudukte aufgelistet sein, die der Villiger anbietet. Wenn man dann auf das Prudukt draufdrückt soll es gekauft werden. 
 (Linksklick = Er kauft so viel wie es geht von dem Prudukt)
 (Rechtsklick= Er kauft nur ein Exemplar von dem Prudukt.)

(Es soll für normale Villiger gehen. (Singleplayer etc.) Und es soll für Gomme gehen.)

Der erweiterte Shop soll rechts neben der Villiger GUI sein.)

**Comment by superblaubeere27** [comment]
Also als erstes heißt ein Villager nicht "Villiger" sondern "Villager"

**Comment by superblaubeere27** [comment]
Es ist nicht sehr sinnvoll sowas einzubauen, da das auch ohne geht

**Comment by superblaubeere27** [comment]
Formulier sowas auf deutsch, dann übersetzen wir das
