### ISSUE TITLE
Truesight options

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#595]
Es soll eine Option geben das man Barrieren sieht.

Zudem noch eine Option, dass alle unsichtbaren 100% angezeigt werden und nicht so halb durchsichtig.

SeeBarriers
100%

PS: es ist nicht unnötig. Oft muss ich einen anderen Client starten weil der es hat. (Ich habe es schon oft gebraucht)

und das das man die Unsichtbaren 100% sieht ist auch nicht unnötig. Es gibt server wo alle so halb unsichtbar sind (auch ohne Truesight und da kann es helfen.)

**Comment by MaxHD00** [comment]
plz nicht entfernen. Es ist nicht unnötig.

**Comment by byCaptain** [comment]
denied.

**Comment by Marco-MC** [comment]
Nein. Junge raff es. WENN WIR EINMAL ETWAS ABGELEHNT HABEN DANN BLEIBT DAS AUCH SO... .-.
