### ISSUE TITLE
.  -  + oder # befehle

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#596]
Man soll einstellen können ob die Befehle mit ., -, + oder # ausgeführt werden sollen. 

wenn dich jemand fragt das du ein Punkt in den Chat schreiben sollst und du es nicht kannst weiss er du Hacks und bannt dich direkt.

Ist mir schon mehrmals passiert.

Zudem mache sind gewönnt mit # oder + zu schreiben weil manche Clients es so haben.

**Comment by SenkJu** [comment]
.say .
