### ISSUE TITLE
AAC Phase/inSight/waterspeed etc...

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#599]
Ich kann dir später ein Client geben der gute Bypasses hat (z.b AAC Phase der durch 3 volle Blöcke gehen kann (Vanilla, AAC Und NCP) Zudem hat er noch weitere Bypasses und features die Sehr Cool sind.
Schreibe mich einfach per Discord an.

**Comment by Fleroxh** [comment]
Ich? Wir sind eine Gruppe, aber okay.

**Comment by MaxHD00** [comment]
Ich meine in dem Sinne jetzt Marco, da er ja am Client codet.

**Comment by Fleroxh** [comment]
Wäre trotzdem etwas freundlicher, wenn du "euch" benutzt. :)

**Comment by MaxHD00** [comment]
.-. ok

**Comment by MaxHD00** [comment]
diese issues könnt ihr löschen
