### ISSUE TITLE
CameraClip

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#601]

**Comment by Crax9999** [comment]
Sau unnötig

**Comment by MaxHD00** [comment]
Ich nutze es oft.

**Comment by MaxHD00** [comment]
Marco sagte zudem er macht es rein. Sind ja nur 3 Zeilen Code. Ist ja nicht schwer.

**Comment by Crax9999** [comment]
Wofür braucht man es überhaupt
Man kann damot fast nichts sehen

**Comment by MaxHD00** [comment]
Ich benutze es viel. Aber es kommt drauf an.

**Comment by MaxHD00** [comment]
Lol wurde ich gebannt? oder warum steht da ober ghost? Scheimbar haben die mich genannt und mein Programm hat das gemerkt und direkt einen neuen account erstellt. Naja.

**Comment by Marco-MC** [comment]
Added.
