### ISSUE TITLE
ServerCrasher

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#603]
*[Dieser Hack ist eine Zusammenfassung. Alle Crash module sollen zu einem Verschmelzen. Zudem werden noch Swing und CreativeCrasher hinzugefügt. Relativ leicht zu programmieren. Und sortierter(bzw aufgeräumter). Man kann also keinen Grund haben diese Issues zu schliessen. Wenn ihr jetzt kein Bock habt es einzufügen lasst es offen und fügt es in der B99 ein.] *

ServerCrasher soll diese Modis haben:

CreativeItemSpam

CreativeItemDrop

Swing

AACNew

AACOther

AACOld

WorldEditCrasher

(AACNew, AACOther, AACOld und WorldEditCrasher werden zu einem Modul zusammengefügt.)

(Umbenennung AACNew soll zu AAC3.1.5)

(Umbenennung AACOther soll zu AAC(in welcher Version geht dieser Crash))

(Umbenennung AACOld soll zu AAC(in welcher Version geht dieser Crash))

**Comment by Marco-MC** [comment]
Renamed AACCrasher to ServerCrasher
{
  Renamed New to AACNew
  Renamed Other to AACOther
  Renamed Old to AACOld
}

Moved WorldEditCrasher as setting to Server Crasher (WorldEdit mode)
Deleted WorldEditCrasher

**Comment by Marco-MC** [comment]
Was soll man unter Swing verstehen?

**Comment by Marco-MC** [comment]
CreativeItemSpam
Swing

Baue ich nicht ein in den ServerCrasher.
Würde ich eher als extra Modul machen, aber wegen Swing weiß ich nicht. Weiß ja nicht mal was dass sein soll.
