### ISSUE TITLE
KeepOpen Inventory (Background Inventory)

### ISSUE THREAD

**Issue by scorpion3013** [CCBlueX/LiquidBounce1.8-Issues#604]
Modulvorschlag: KeepOpen - Erlaubt es, Chestmenüs in den Hintergrund zu tabben, und zu einen anderen zeitpunkt wieder anzusehen. Beispiel: Der Shop auf Hypixel. Wenn du in der Base bist Aktivierst du KeepOpen, klickst du ein mal auf den Shop, und wenn du den shop wieder zu machst wird er Serverside nicht geschlossen, sondern nur clientside Versteckt. Dann kann man von Überall auf der map einen Festgelegten Keybind drücken, m den Shop wieder anzeigen zu Lassen. Funktioniert nur auf Servern wo der Shop nicht nach einer bestimmten distanz Geschlossen wird.

Vorschlag von Temm (Discord: Temm#5625)

**Comment by MaxHD00** [comment]
hem. Ich sehe zwar keinen Sinn dafür aber schlecht ist die Idee nicht. Aber ausbaufähig.

**Comment by Marco-MC** [comment]
@MaxHD00 https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/606 Und dass soll mehr sinn machen?

**Comment by MaxHD00** [comment]
das haben halt viele Clients. 

ich sage ja nicht das man KeepOben nicht einfügen soll. Er sagte ja seinen grund: "Der Shop auf Hypixel. Wenn du in der Base bist Aktivierst du KeepOpen, klickst du ein mal auf den Shop, und wenn du den shop wieder zu machst wird er Serverside nicht geschlossen, sondern nur clientside Versteckt." Ich nenne auch immer einen Grund. Egal wie unnötig. zudem kann man jeden hack irgendwann gebrauchen. Desshalb ist es gut alle hacks zu haben.

**Comment by Marco-MC** [comment]
Added
