### ISSUE TITLE
Add BreadCrumbs to Blink

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#605]
wenn du Blink aktivierst ziehst du hinter dir eine Blaue spur. deaktivierst du Blink verschwindet die Spur.
(kann sehr hiffreich sein um Bypasses zu finden)

(es sind 2 zeilen Code und es stört nicht. Mir hat es bei einem anderen Client oft geholfen.)

**Comment by Marco-MC** [comment]
Das mit den 2 zeilen code war ein Witz? Du hast 0 Plan von Coding und redest hier von Code lenght...

**Comment by MaxHD00** [comment]
war auch einer. Ich will damit sagen es geht relativ schnell

**Comment by Marco-MC** [comment]
Added.

**Comment by Maxhd00** [comment]
nice
