### ISSUE TITLE
[Idee] [Label] [Request] [Issue] [B26] [GommeHD.net] [LiquidBounce] [Marco] CPS Anzeige fehlt

### ISSUE THREAD

**Issue by byCaptain** [CCBlueX/LiquidBounce1.8-Issues#607]
Hallo bitte cps anzeige einfügen wie früher in der b9 das fehlt mir danke cao

**Comment by byCaptain** [comment]
heyho minecraft freunde

**Comment by byCaptain** [comment]
wieso nicht ich mag das marco

**Comment by Maxhd00** [comment]
Ich auch :/   



Ich das ist ne lüge mir ist das egal XD

**Comment by byCaptain** [comment]
junge 5 tage ago
