### ISSUE TITLE
Ein paar Ideen

### ISSUE THREAD

**Issue by Crax9999** [CCBlueX/LiquidBounce1.8-Issues#613]
Ihr könntet ja vielleicht bei killaura die
Rotationmode:AAC/NCP/Spartan, Ywrate
Spartan jesus
Fucker break speed setting
Autopot cooldown option

Es wäre echt nett wenn ihr dass adden 
könntet
<3LiquidBounce Dev Team<3

**Comment by Marco-MC** [comment]
RotationMode bau ich nicht ein.
Spartan jesus vielleicht falls ich einen finde. Ich werde gleich mal schauen, ob ich einen find. :)
AutoPot Cooldown... Bau ich glaube mal ein.

**Comment by Crax9999** [comment]
Danke :)

**Comment by Marco-MC** [comment]
#695 
Und Autopot cooldown option lass ich raus.
