### ISSUE TITLE
isBanned - AltManager

### ISSUE THREAD

**Issue by zikdriver** [CCBlueX/LiquidBounce1.8-Issues#614]
Hey,

wie wäre es wenn man beim Altlogin angezeigt bekommt (bei größere Server) ob der Alt eventuell gebannt ist? Es dauert zwar nicht so lange selber nach zugucken, aber bei mehreren Servern denke ich es schon. Wie seht ihr es? Lohnt sich das Aufwand/Nutzungsverhältnis?

z.B:

Hive - Banned
Gomme - Banned
Mineplex - Unbanned

**Comment by SenkJu** [comment]
Das wäre nicht wirklich möglich. Der Client müsste dazu mit jedem Alt auf alle diese Server joinen, um herauszufinden, ob man gebannt ist. Das würde die Performance ziemlich kaputt machen, oder wie stellst du dir das vor? Ich weiß aber, dass es einen AltChecker gibt, der testen kann, ob ein Alt auf einem bestimmten Server gebannt ist: https://github.com/TeamVeiv/AltChecker

**Comment by zikdriver** [comment]
Ja das ist mir bewusst.
Deswegen meinte ich nicht alle Server die man in der Serverliste hat, sondern vlt max. nur 3-5 Server. Die ihr entweder vorher aussucht, oder die jeder Clientnutzer selbst konfigurieren kann. Mir gehts auch dadrum das LB ein bisschen abwechslung reinbekommt was keine anderern Clients haben.

**Comment by MaxHD00** [comment]
Macht es doch so: neben dem Account steht immer auf welchen Server er gebannt ist. (Er trägt es nur ein wenn man mit diesem Account auf gomme etc joint und du wurdest gebannst steht. Davor soll nichts stehen. Zudem soll es nur für Gomme, mineplax, Hive, hypixel und ein server nach seiner wahl sein. (Einfach ein button beim Alt manager einfügen wo man die domain eingibt.)

**Comment by MaxHD00** [comment]
Zudem soll es mit farben sein. Wenn Gomme im altmanager rot geschrieben ist, ist der account gebannt. Wenn gomme grün ist dann ist er unbannt.

**Comment by Bircko** [comment]
Nein aber z.B. wenn man gebannt wird könnte er es abspeichern und neben dem Alt hinschreiben. Wäre ganz praktisch.

**Comment by MaxHD00** [comment]
das macht das was ich sage auch XD

**Comment by superblaubeere27** [comment]
Ist eigentlich ne geile Idee, würde @Marco-MC Mich am client coden lassen würde, wäre sowas schon eingebaut

**Comment by byCaptain** [comment]
push oder so @Marco-MC mach mal nen alt checker mit proxys du kannst den von teamveiv benutzten und optimieren

**Comment by maxhd0** [comment]
warum schließt das jetzt senk ju?
