### ISSUE TITLE
Raycast bug? 

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#617]
Wenn ich einen Spieler schlage und Raycast an habe und sich einer dazwischen stellt schlägt die Killaura immer noch den einen Spieler ( er hittet also durch den anderen spieler)

Raycast ist doch das die Killaura nicht durch entitys schlägt.

**Comment by Marco-MC** [comment]
Das ist kein Bug. ^^
Es ist schon korrekt das dass so ist. Raycast überprüft die Sicht deiner KillAura die du selbst nicht sehen kannst, daher kann es sein das die KillAura grade trz so guckt das sie den anderen Spieler dahinter trz hitten kann. :)

**Comment by MaxHD00** [comment]
.-. Ok

**Comment by Marco-MC** [comment]
Da ist anscheind doch n Bug... Der ist mir eben aufgefallen das da was nicht stimmt.

**Comment by MaxHD00** [comment]
XD

**Comment by MaxHD00** [comment]
Marco entferne Raycast und füge es direkt in die Killaura ein. Denn selbst auf vanilla servern wirst du nach der zeit gekickt weil er duch entitys schlug. Das ist nicht nur bei LB der fall. Auch andere clients wie Alpha centauri war es so das man gekickt wurde. Zudem kann man raycast eigendlich immer an haben, da jeder server so ein check hat. Mach so das Raycast immer automatisch an ist und füge die option weg.

**Comment by Marco-MC** [comment]
Nein, ich werde den nicht entfernen?
Und vanilla checkt sowas nicht.

**Comment by MaxHD00** [comment]
Auch für gewisse kinder die viele hacks nicht kennen. Die lassen die funktion aus und schon sind sie gebannt oder werden gekickt und wundern sich warum. Zur sicherheit ist es immer besser.

**Comment by Marco-MC** [comment]
Nein.

**Comment by MaxHD00** [comment]
Dann nenn Raycast mindestens in Entityenough um. 1. Passt es zu Blockenough und 2. Man ist das gewohnt. Ich habe 20 clients schon benutzt. LB ist der erste wo es Raycast heisst. PLZ

**Comment by Marco-MC** [comment]
Nein.

**Comment by MaxHD00** [comment]
:-( mindestens 1 mal ja.

**Comment by Marco-MC** [comment]
Nein.

**Comment by MaxHD00** [comment]
Dann nenne Blockenough halt in Blockcast um. Die beiden settings sind sehr gemeinsam heissen aber total unterschiedlich.

**Comment by Marco-MC** [comment]
Nein.

**Comment by MaxHD00** [comment]
Na dann.

**Comment by MaxHD00** [comment]
Ich hoffe irgendwann kann man mit einem Skript die module umbennenen.

**Comment by Marco-MC** [comment]
Yaaaaaaaaaaaaaaaaaaaaaaayyyyyyyyyy, der Bug ist patched... Jetzt bypassed die Aura auch wieder richtig auf Gomme etc. :3

**Comment by Marco-MC** [comment]
Ich hatte erst das raycast von Minecraft machen lassen und dass hat die rots von der clientside genommen, jetzt habe ich mir selbst einen Code geschrieben.. :)

**Comment by MaxHD00** [comment]
Ok
