### ISSUE TITLE
GuiDisconnect (Random alt button)

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#618]

**Comment by SenkJu** [comment]
Es gibt doch schon einen random Alt Button?

**Comment by Marco-MC** [comment]
Er meint dass wenn man z.B gebannt wird und da wo dann dieser AutoReconnect ist auch noch n random alt button hin

**Comment by MaxHD00** [comment]
Ja aber wenn du gekickt wirst steht da nur neu joinen . (Nicht im alt manager)

**Comment by MaxHD00** [comment]
Ja marco

**Comment by Marco-MC** [comment]
Added.
