### ISSUE TITLE
BowAimbot target search mode (Nearest, crosshair nearest)

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#621]

**Comment by MaxHD00** [comment]
Füge noch hinzu, dass wenn du die Sneak taste drückst der Bow aimbot das target wechselt.

**Comment by Marco-MC** [comment]
Nein @MaxHD00

**Comment by MaxHD00** [comment]
Zu mir ist es immer nein. Dabei sind die ideen gut :/

**Comment by Marco-MC** [comment]
Added.
