### ISSUE TITLE
ArmorBreaker

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#622]
Funktioniert mit Packets

Es gibt derzeit ein AAC bypass. Sollte aber auch in Vanilla gehen

(Wenn du es nicht umsetzen kannst lass es trotzdem noch offen)

**Comment by MaxHD00** [comment]
(Es soll ein eigenes Modul sein und nicht ein setting in der Killaura)

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/129

**Comment by MaxHD00** [comment]
ups
