### ISSUE TITLE
.hentai befehl

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#625]
wenn du .hentai eingibts soll ein random hentai link im Chat kommen XD

**Comment by scorpion3013** [comment]
+1

**Comment by MaxHD00** [comment]
+2

**Comment by Marco-MC** [comment]
飛び回る

**Comment by Marco-MC** [comment]
変態は私の人生です

**Comment by MaxHD00** [comment]
ok verstanden

**Comment by Bircko** [comment]
unnötig und performance lastig

**Comment by MaxHD00** [comment]
Bircko. Marco-MC hat es vorgeschlagen XD Ich habe es nur hie reingeschrieben XD. performance lastig währe es zudem nicht. (nicht solange du den befehl nicht eingibst ^^ )
