### ISSUE TITLE
Criticales settings + mode

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#626]
- JumpHeight (du kannst von 0,1 bis 1 die höhe des jumps einstellen.)(mit dem befehl .JumpHeight <sprunghöhe> kann man die sprunghöhe auch über 1 machen und auch in den Minusbereich (du wirst nach unten gedrückt.)(ist zwar dann kein crit kann aber in manchen sachen auch nötig sein.))

- Legit mode (wie Packets nur das nicht jeder Schlag ein Crit ist sondern nur 60%
 (wie viel Crit Packets gesendet werden sollen soll einstellbar sein.))
 

- Teleport (bei einem Schlag teleportierst du dich 0,1 blöcke nach oben und direkt wieder nach unten. (Ingame sollst du dich nicht bewegen. (clientside) Nützlich für Vanilla, denn wenn du noch ne multiaura an hast wirst du mit crit packets gekickt für "you sending too many packets" wenn du den Teleport mode an hast passiert das nicht. 

- Wiggle (du bewegst dich die ganze zeit schwach hoch und runter. (Funktioniert perfekt auf Hypixel zudem ist es dort auch ein Nofall) (Clientside sollst du dich nicht bewegen)

(Minijump und Hop soll verschwinden , da man es dann mit JumpHeight einstellen kann.)

(langsamer soll man beim schlagen nicht werden.)

**Comment by MaxHD00** [comment]
sollte glaub auch newst NCP gehen.

**Comment by byCaptain** [comment]
dasbraucht man nicht weil jedes anticheat außer vanilla das patcht?

**Comment by MaxHD00** [comment]
kommt drauf an welcher mode du meinst. 
JumpHeight kann man bei NCP auf 3 machen

Legit geht überall.

Teleport soll nur Vanilla gehen. Ist nützlich da mann in Verbindung mit Multiaura etc nicht gekickt wird.

Wiggle funktioniert super auf Hypixel.
