### ISSUE TITLE
AAC 3.2.0 Highjump

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#627]
Auf eurem Server war einer der 16 Blöcke hoch sprang auf AAC. er bugte leicht rum und dann sprang er 16 Blöcke hoch. Vielleicht ist es umsetzbar.

**Comment by scorpion3013** [comment]
aac bugt auf deren server oft ein bissel.

**Comment by MaxHD00** [comment]
geht allgemein grade.

**Comment by MaxHD00** [comment]
k?

**Comment by Marco-MC** [comment]
So einen Bypass giebt es derzeit nicht. ^^
Liegt ledeglich an unserem TestServer.
Habe ich ausgetestet.
TestServer & poke.sexy: HighJump geht
Gomme etc: HighJump geht net
