### ISSUE TITLE
Chestaura mode

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#628]
- CoolDown (0- 10 sek)

- NeedsOnGround (du öffnest Truhen nur wenn du am Boden bist.)

- UseRedstoneChest (wenn aus öffnet sie keine Redstonetruhen mehr)

- Slowrotate  (wenn an rotatet es langsamer)

**Comment by scorpion3013** [comment]
"CoolDown (0- 10 sek)"  ist meiner meinung nach das einzigst gute hier

**Comment by MaxHD00** [comment]
Slowrotate ist auf Mineplax nötig. Die haben seit gestern da was.

**Comment by MaxHD00** [comment]
NeedsOnGround: wenn du in der Luft (bei LPmitKev) eine Truhe öffnest wirst du geflagt und du buggst rum.

**Comment by MaxHD00** [comment]
"Ebenfalls währe es gut ein check falls ein Inventar geöffnet ist (Kiste, Spieler etc) das dann keine Kisten von chestaura geöffnet werden." es soll da kein mode geben. das soll automatisch passieren.
