### ISSUE TITLE
Spammer 

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#629]
Mann soll mehrere nachrichten speichern können. Erstellen kann man sie mit .spammer message2 <>

es soll weiterhin .spammer message <> sein und nicht .spammer message**1** <>

mann soll bis 4 Nachrichten speichern können.

es soll zudem ein switch mode geben. ( er spammt nachricht 1 dann 2 dann 3 dann 4 dann wieder 1 usw. )

**Comment by scorpion3013** [comment]
#156 also das mit meheren nachrichten

**Comment by MaxHD00** [comment]
oh sehe ich jz erst XD
aber ja.

**Comment by WistarWolf** [comment]
War klar.... Meins wir abgelehnt und das wahrscheinlich angenommen ._.

**Comment by SenkJu** [comment]
Es hat das Duplicated Label. Außerdem steht das sehr weit unten auf der Todo Liste.

**Comment by WistarWolf** [comment]
Aber meins wurde geschlossen. Also wieso sollte dann das hier angenommen werden?

**Comment by MaxHD00** [comment]
:p

**Comment by Fleroxh** [comment]
Weil max halt gerne mal kopiert. 😄

**Comment by WistarWolf** [comment]
xd

**Comment by Maxhd00** [comment]
ich skidder ;-)
