### ISSUE TITLE
Silent aim Killaura(Serversided)

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#631]
Also die Killaura soll serversided nicht auf Spieler aimen.

**Comment by Marco-MC** [comment]
Wozu?

**Comment by SenkJu** [comment]
Dann bypasst sie ja überhaupt nicht mehr

**Comment by Bircko** [comment]
Auf Servern wie Cubecraft würde es mit noswing zusammen ganz lustig aussehen

**Comment by SenkJu** [comment]
Selbst Cubecraft detected NoSwing und Killauren ohne Rotations

**Comment by MaxHD00** [comment]
das ist doch noswing mit serverside an

**Comment by MaxHD00** [comment]
das ist doch drin

**Comment by MaxHD00** [comment]
(falls es nicht im Client ist währe es gut. Man ist ja auch noch genügend auf Vanilla servern. Da kann man immer sagen ich habe nicht geschlagen. XD

**Comment by Bircko** [comment]
SenkJu Cubecraft detected keine serversided noswing

**Comment by SenkJu** [comment]
Vor einer Woche hat Cubecraft es noch getan
