### ISSUE TITLE
Scrollable TabGUI

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#632]
Teilweise gehen sich die ganzen Module im TabGUI nicht aus jedenfalls wenn man zusätzlich auch noch Scripts used.

**Comment by MaxHD00** [comment]
TabGUI????? JUNGE wie viele Scripts hast du da???? da musst du ja Gui grösse automatisch +30 module haben. Aber naja. Ich benutze die TabGUi ehh nicht XD also habe ich keine Meinung dazu.

**Comment by Bircko** [comment]
Ich benutz es auch nicht wirklich, trotzdem sieht es scheiße aus ne ganze Leiste bis zur Hotbar zu haben.

**Comment by Bircko** [comment]
Zusatz Info: Bitte nicht mit mausrad sondern das er einfach mit denn pfeiltasten dann runter scrolled.

**Comment by coolpvpv1** [comment]
> Teilweise gehen sich die ganzen Module im TabGUI nicht aus jedenfalls wenn man zusätzlich auch noch Scripts used.

um just use arrow keys to use the tabgui? can someone take this down cause this issues just stupid a scrollable tabgui? boy thats been around like ever sense liquidbounce first made a tabgui so please remove this issue its just stupid
