### ISSUE TITLE
velocity (lol)

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#634]
Ich habe was rausgefunden. Alle anticheats achten nur bei Velocity auf spieler schläge. (wenn ich von einem anderen Spieler geschlagen werde oder wenn ich mit nem bogen getroffen werde.) alles andere nicht. Ihr könnt also ein Mode hinzufügen das man bei  Kakten, Wasserströmung, Schneebällen, Eier, Fallschaden, Angel, Feuerschaden, Vergiftung und Wither der Knockback auf 0 ist.

(PS:  2 Aufzählungen habe ich nicht ausprobiert, da ich nicht dazu kam.)

**Comment by SenkJu** [comment]
Zumindest AAC checkt das so gut wie alles.

**Comment by MaxHD00** [comment]
Schneebällen und Eier habe ich nicht ausprobiert.

**Comment by MaxHD00** [comment]
ne. konnte gemütlich auf gomme spielen mit dem mode (eigener client) (6 runden immernoch unband)

**Comment by byCaptain** [comment]
aac checkt alles und hat tdm noch fp

**Comment by MaxHD00** [comment]
es gibt eh jetzt ein neues velocity
