### ISSUE TITLE
Discord Integration 

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#636]
Das man Discord auch in Minecraft benutzte  kann mit der api.

**Comment by MaxHD00** [comment]
em.

**Comment by MaxHD00** [comment]
Kein Kommentar

**Comment by SenkJu** [comment]
Viel zu aufwendig und außerdem gibt es schon eine Forge Mod für Discord Integration. Die kannst du dann nutzen.
