### ISSUE TITLE
Teleport verbesserung

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#637]
derzeit ist es so, dass wenn ich die Sneakteste 1 mal drücke der Teleport sich 1 mal teleportieren will.

Macht es so solange ich die Sneaktaste drücke soll der Teleport versuchen zu Teleportieren.

**Comment by SenkJu** [comment]
Der Teleport tut das schon. Er versucht zu teleportieren, bis man es deaktiviert.

**Comment by MaxHD00** [comment]
Ne. Habe es grade getestet. es macht nur der Rewi Teleport. 

Macht es so (bei allen Teleport modes) er teleportiert sollange ich die Sneak taste drücke. Wenn ich loslasse soll er aufhören. (ihr könnt auch ein Mode machen. Wie der client skash. 

Mode1: wenn du middlklick drückst teleportierst du dich 1 mal sofort

Mode2: wenn du middlklick drückst Wählst du dein ort wohin du teleportiert wirst. Um aber zu teleportieren muss du sneaken (lass los wenn du dich nicht mehr teleportieren willst.)

**Comment by Marco-MC** [comment]
Den vorschlag finde ich sogar ganz gut.

**Comment by Marco-MC** [comment]
Changed.
