### ISSUE TITLE
InSight

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#639]
wenn jemand dich anschaut steht oben INSIGHT

(Es ist ein Griefer tool das nur sehr wenige Clients haben. Es ist aber sehr nützlich wenn man griefen will ohne gesehen zu werden ODER wenn mal Legit hacken will und dich keiner bemerken soll.

**Comment by MaxHD00** [comment]
http://www.bilder-upload.eu/show.php?file=b57acf-1498065641.png

**Comment by MaxHD00** [comment]
so soll es aussehen.

**Comment by scorpion3013** [comment]
Nicht nötig wenn man aufmerksam ist und Augen hat

**Comment by MaxHD00** [comment]
wenn hinter dir einer steht der 20 blocke weg ist?

wenn jemand unsichtbar ist?

**Comment by MaxHD00** [comment]
das siehst du nicht.

**Comment by MaxHD00** [comment]
zudem ist jetzt nicht jeder aufmerksam XD
