### ISSUE TITLE
Nuker Modis

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#640]
- Normal

- Click (erst wenn du die Linke Maustaste drückst nuket er. (Ist mit Blink super)

- ID (er baut nur 1 blocksorte ab) (ich weiss das es auch mit fucker geht jedoch kann man dann 2 Blocksorten nuken zudem muss man es anschliessend nicht wieder zum bett machen.

- Smash (er baut nur One-Hit-Blocke ab(z.b Schleim oder Blumen))

Marco du sagtest mal sowas gehört in den Skill client. Ja aber dein Client soll doch so gut werden. (zudem will man nicht 100 clients im Launcher haben)

**Comment by Marco-MC** [comment]
JUNGE.
WENN WIR ETWAS EINMAL ABLEHNEN DANN BLEIBT ES AUCH SO.
JUNGE RAFF DAS ENDLICH. BOAR.
