### ISSUE TITLE
CaveFinder

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#641]
Ähnlich wie bei X-Ray werden nur Höhlen angezeigt.

**Comment by MaxHD00** [comment]
siehe hier:
http://www.bilder-upload.eu/show.php?file=4d0a16-1498067903.png

**Comment by SenkJu** [comment]
Du kannst auch einfach mit Freecam ein bisschen in den Boden fahren

**Comment by MaxHD00** [comment]
oft sieht man da nicht richtig. Zudem dient es ja nicht nur um Caves zu finden.
