### ISSUE TITLE
Lagging modul

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#642]
Für andere Spieler sieht es so aus als ob du laggst, was dich zu einem schwierigen Ziel für Pfeile und Schwerter macht. 

(mann soll die stärke wie stark man laggt einstellen können [----[]---])

**Comment by scorpion3013** [comment]
Sozusagen ein Pulse Blink ?

**Comment by MaxHD00** [comment]
ja. Nur das du wirklich laggst. Bei blink kannst du den Skin schlagen. bei lagging nicht.

**Comment by Bircko** [comment]
Fakelag wie in cs go cheats?

**Comment by MaxHD00** [comment]
kp spiele ich nicht

**Comment by Maxhd00** [comment]
l
