### ISSUE TITLE
PotionSaver

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#643]
Während du dich nicht bewegst, bekommst du keinen Feuerschaden, verlierst keinen Hunger, kannst nicht ertrinken, deine Potion Effekte bleiben erhalten und du regenerierst kein Leben.

**Comment by Marco-MC** [comment]
Added.

**Comment by Maxhd00** [comment]
ich habe schon Nein gelesen XD
