### ISSUE TITLE
auto bed/core/egg button (fucker)

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#644]
Unter fucker sollen 3 Knöpfe sein (Bed,Core und egg) wenn ich da drauf drücke wechselt der fucker direkt zu dem Block. In dem sinne Bett, Beakon, und Dragonegg

**Comment by Marco-MC** [comment]
Hm... Wo für meinst du wohl giebt es:
.fucker select bed
oder auch per ClickGUI kann man einstellen... ._.
