### ISSUE TITLE
Give item GUI

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#645]
Könnt ihr eine gui erstellen wo man sich ein Item geben kann und:
dem Item einen Namen geben kann

dem Item eine Farbe geben kann (für plugins)

dem Item ein Enchantment  geben kann. + lvl

(es soll ähnlich wie der hack Commandsign sein)

(beim .give befehl kann man nichts einstellen. Man kann dem item keinen Namen geben. Keine Farbe und keine Verzauberung.)

**Comment by MaxHD00** [comment]
so wie der Client:
http://www.bilder-upload.eu/show.php?file=fb82b6-1498075493.png

**Comment by MaxHD00** [comment]
So wie dieser Client:
http://www.bilder-upload.eu/show.php?file=4f0999-1498075568.png

**Comment by MaxHD00** [comment]
Macht einfach ein eigenes Too many items. (für die 1.8.9 gibt es kein Too many items. Leider :-(    Und die 1.8 version funktioniert nicht.

**Comment by MaxHD00** [comment]
Ich weiss es ist nicht einfach. Jedoch ist es sehr nützlich. Macht es wenn ihr nicht zu tun habt XD

**Comment by Marco-MC** [comment]
https://www.file-upload.net/download-12578187/Just-Enough-Items-Mod-1.8.9.jar.html
