### ISSUE TITLE
Scaffold gui bug

### ISSUE THREAD

**Issue by Fleroxh** [CCBlueX/LiquidBounce1.8-Issues#646]
Wenn ich scaffold aktiviere und ein Item in der Hand habe und dieses Item ein gui hat, öffnet scaffold ständig das gui des items erneut. Und das in einer Endlosschleife.

**Comment by SenkJu** [comment]
Das ist kein Bug. Der Scaffold versucht halt den Block zu platzieren

**Comment by Fleroxh** [comment]
Habe ich mir schon gedacht. Das passiert aber auch, wenn ich mich nicht bewege. Das kann aber am Expand-Mode liegen.

**Comment by MaxHD00** [comment]
em k?

**Comment by MaxHD00** [comment]
und wie soll man das jetzt "fixen"

**Comment by MaxHD00** [comment]
?

**Comment by Fleroxh** [comment]
In dem du deinen schnellen Mund hältst. BTW: Man kann auch das Fragezeichen in die Antwort einbauen. Da muss man nicht extra eine Antwort erstellen.

**Comment by MaxHD00** [comment]
n

**Comment by MaxHD00** [comment]
e

**Comment by MaxHD00** [comment]
-.-

**Comment by Fleroxh** [comment]
Dann geh Pflaumen pflücken.

**Comment by MaxHD00** [comment]
:P

**Comment by Fleroxh** [comment]
Aber auf dem Discord. 😋

**Comment by MaxHD00** [comment]
würde ich auch garnicht merken. Marco hat mir ja schon 8 mal glaub gebannt. Mein bot erstellt sofort einen neuen account.

**Comment by Fleroxh** [comment]
So, blockiert.
[
![image](https://cdn.discordapp.com/attachments/304419444015366147/327461425930960897/Unben153215351annt.PNG)
](url)

**Comment by MaxHD00** [comment]
Also ich bemerke nichts.

**Comment by MaxHD00** [comment]
oh. Doch. Alle sachen wo ich geschrieben habe steht jetzt ghost.

**Comment by MaxHD00** [comment]
ja dann halt.  Ist ja eh egal.

**Comment by byCaptain** [comment]
max alter chill mal du bist der nächste

**Comment by Maxhd00** [comment]
der nächste mit?

**Comment by Namebittehiereingeben** [comment]
close XD

**Comment by byCaptain** [comment]
Xd
