### ISSUE TITLE
1.12 er LiquidBounce

### ISSUE THREAD

**Issue by MaxHD00** [CCBlueX/LiquidBounce1.8-Issues#647]
Gomme wechselt jetzt auf die 1.12 (nurnoch die 1.12) und da währe es hilfreich eine 1.12 version zu erstellen und sie auch als hauptversion zu machen.

**Comment by Marco-MC** [comment]
....
Für sowas soll kein Issue created werden, da wir es sowieso machen.
Außerdem steht oben: "LiquidBounce1.8-Issues"
Heißt es ist **FÜR DIE 1.8...**

**Comment by MaxHD00** [comment]
habe ich mir schon gedacht.
