### ISSUE TITLE
FastBuy // Villagers // BedWars

### ISSUE THREAD

**Issue by byCaptain** [CCBlueX/LiquidBounce1.8-Issues#648]
Hallo,

ich hatte die Idee, dass wen man beispielsweise diesen Cheat anmacht, er Items schneller im BedWars Shop kauft (Gomme). Man kann sich Profile oder Vorlagen erstellen, die dann sehr schnell gekauft werden, somit würde die Wartezeit entfallen und der Spielspaß sich erhöhen. 
Sowas gabs schonmal bei nem haze client, daher kein copyright oder so.

lg

**Comment by Maxhd00** [comment]
em XD. diesen Vorschlag brachte ich schon. Ich finde ihn auch gut aber Marco hat einfach kein Bock es zu machen.

**Comment by Maxhd00** [comment]
Ich antworte trotzdem :P

**Comment by Maxhd00** [comment]
#593

**Comment by superblaubeere27** [comment]
Man warum brauch mann sowas?
3 Stunden arbeit dafür, dass 2 Leute etwas haben, was sonst niemand braucht?
Nope

**Comment by byCaptain** [comment]
diggi du juckst mich nicht mich juckt @Marco-MC
