### ISSUE TITLE
Cubecraftfly up

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#653]
Das man mit dem Cubecraft fly hochfliegen kann, geht 3-4 blöcke bei dem script auch und wenn man runterfällt, wo keine Blöcke mehr sind, ist es hilfreich sich damit auch hoch zu buggen.

**Comment by Bircko** [comment]
und der fly wird bremst ab, wenn man von jemanden gehittet wird.

**Comment by Marco-MC** [comment]
Added.
