### ISSUE TITLE
Ncp multiaura bug

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#660]
NCP multiaura schlägt immer nur 1 spieler. (es sollte doch 2 oder 3 schlagen.)

**Comment by Maxhd00** [comment]
fügt doch eine leiste hinzu wie viel Targets die Killaura haben soll. [-----[]------] 1-10

Dann könnt ihr Vanilla und Ncp mode streichen, da man das in der Leisste einstellen kann. 

PS: wenn man mehr als 10 targets hat wird man  immer für packets gekickt. Auch Vanilla.

**Comment by Marco-MC** [comment]
Bruh, du weißt nicht wie die NCP MultiAura geht?...

Die NCP Aura geht nicht auf Targets aus sondern auf Rotation.

**Comment by Maxhd00** [comment]
Oh

**Comment by Maxhd00** [comment]
Es heisst doch multi Xd

**Comment by Maxhd00** [comment]
2 targets geht aber auf Ncp füge das mit der leiste ein.
