### ISSUE TITLE
MCLaks Login not working

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#663]

**Comment by byCaptain** [comment]
laks mois

**Comment by Crax9999** [comment]
falls ihr den fehler mit "not authented with minecraft.net" meint dann ist das nicht der Fehler von euch
sondern manche Server wie z.b Hypixel oder Gomme haben nen fix dafür also ist das kein bug probiert es auf anderen servern

**Comment by SenkJu** [comment]
#664

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SenkJu** [comment]
#663

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Marco-MC** [comment]
Fixed.
