### ISSUE TITLE
Add AntiBot TabContains setting

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#666]
er schlägt einfach nicht. Nur weil die Farbe in tab anders ist. Ich was du sagtest es sei kein bug. aber wann soll es dann schlagen? wenn es die gleiche farbe hat wie du? dann würde man ja immer nur team mades schlagen. und wenn es nur schlägt wenn die farbe weiss ist dann geht das ja nie für premiums etc. 

du merkst selber das das unnötig ist. 

Bitte machen, dass Antibot nur testet ob der Spieler im Tab drinsteht. das mit der farbe macht doch eh Color?

Was macht eigendlich color? Teams gibts ja schon.

**Comment by SenkJu** [comment]
Der Tab Check checkt ob der Spieler in der Tablist steht.

**Comment by Maxhd00** [comment]
Ja aber auch die Farbe.
http://www.bilder-upload.eu/show.php?file=80ff7c-1498243376.png

**Comment by Maxhd00** [comment]
leider

**Comment by Maxhd00** [comment]
(ich könne alles ausser Tab aushaben er schlägt nicht.)

**Comment by Marco-MC** [comment]
Color überprüft ob ein Spieler einen weißen Namen hat. Wenn schon, dann ist es ein Bot. War nämlich mal der Bypass für Spectra AntiCheat oder wie das nomma hieß.

**Comment by Maxhd00** [comment]
gibts spectre eigendlich noch? XD

Da würde ich color die und die  spectre speeds weg machen. (ok der schnellste speed von denen nicht.)

Tab soll aber auch nur die Tabliste nach dem namen suchen. nicht nach farben. Mann kann Tab nie nutzen weil die farbe immer das problem ist.

**Comment by Maxhd00** [comment]
mir ist noch was aufgefallen.
http://www.bilder-upload.eu/show.php?file=52e570-1498246871.png

wenn etwas vor dem namen ist hittet er auch nicht. Bitte beheben.
ist doof wenn jemand den Premium rang hat. dann schlägt er diesen nämlich nicht

**Comment by Marco-MC** [comment]
Ich entferne keine Bypasses, da z.B der SpectreOnGround Speed oft auf manchen low AntiCheats geht etc.

**Comment by Maxhd00** [comment]
ja dann lass diesen speed noch da. die anderen kannst du löschen.

Das problem ist das der client so viele speeds hat das die kaum noch auf den Bildschirm passen. (gui grösse normal.) zudem kann man die nie verwenden. wenn es irgendwann mal wieder geht kann man es ja wieder reinmachen.
Ich muss speed schon nach ganz oben machen + das ganze movement nach oben das ich an die speeds drankomme geschweigeden die custom settings.

Aber ich rede jetzt eigendlich von antibot

color kannst du echt raus machen. Jetzt mal nur firsthit bypasst alles. und bei spaktre kann man einfach ground an machen oder was invissible und schon gehts wieder.

Aber ich will eher das man Tab wieder verwenden kann. Also mach diese farbenkontrolle bei Tab bitte raus. So hat es keinen nutzen.

**Comment by Marco-MC** [comment]
Added.

**Comment by Marco-MC** [comment]
https://gyazo.com/77d96f9bfd8ebefecd02b76df55ba87b

**Comment by Maxhd00** [comment]
mach doch den tabmod als command . das sieht hesslich aus. (LOL ich will mal was als command o_O)

**Comment by Maxhd00** [comment]
bzw mach es ganz unten hin. erst die modis anschliesend die einstellungen dazu.
