### ISSUE TITLE
AAC Jesus Bug

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#668]
wenn du Jesus an hast und Fallschaden kriegst wirst du stark abgebremst.

PS: Jesus geht irgendwie gar nicht mehr. (AACmode)(ausser vanilla) Egal welchen Server ich betrete.

**Comment by Marco-MC** [comment]
Fixed, but the Jesus was patched. :c

**Comment by Maxhd00** [comment]
ok. dann versuche ich mal einen neuen jesus zu finden ;-)
