### ISSUE TITLE
Alt manager

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#670]
Bitte fügt das alte Design wieder ein. Bei hellen Hintergrundbildern kann man nichts sehen.

http://www.bilder-upload.eu/show.php?file=cb9183-1498246590.png

**Comment by Marco-MC** [comment]
Wir packen einfach nen Schattendarunter, mal sehen ob es dann klappt... Schicke gleich ein Bild, wenn ich das umgeändert habe.

**Comment by Marco-MC** [comment]
https://gyazo.com/6209dbd244d8c3fc642c0ec55cece32a Es sieht schrecklich aus das grüne und das graue...

**Comment by Marco-MC** [comment]
https://gyazo.com/a860cea3c7caa9b49b27db479dc654aa Hat sich erledigt...
Ich sollte aufhören Minecraft Color Codes zu benutzen. ^^
