### ISSUE TITLE
Eigene Configs erstellen.

### ISSUE THREAD

**Issue by byCaptain** [CCBlueX/LiquidBounce1.8-Issues#671]
Hallo,

es sollte möglich sein eigene Configs zu erstellen, aufgebaut so ähnlich wie die Scripts (damals), in Text-Form.
Man könnte die an CCBlueX Mitglieder schicken, die diese dann auf GitHub hochladen oder unter einem Discord Channel: #scripts und somit wird es dann Spieler geben die bessere und schneller Settings als ihr bringen könnten. 
Sowas würde die Hackercommunity sehr stark fördern.

Meinung?

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/FileCloud/tree/master/LiquidBounce/autosettings Giebt es schon.
Die AutoSettings können von jedem der ein GitHub Account bearbeitet werden. :)
Es ist ledeglich wichtig das die Syntax stimmt und keine Fehler auftreten.
