### ISSUE TITLE
AAC 3.2.0 NoFall bypass

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#675]
Turn on OldNcp Fly twice when Close to the Ground

First
(6 Blocks higher than Ground)

Second:
(2 Blocks higher than Ground)

and AAC will lag you to the Ground with no damage

**Comment by Maxhd00** [comment]
auch für gomme? (da ist ja 3.2.1 drauf)

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/676
