### ISSUE TITLE
AutoArmor Gomme bypass verbuggt

### ISSUE THREAD

**Issue by ImDrops** [CCBlueX/LiquidBounce1.8-Issues#677]
Der AutoArmor bypass für Gomme zieht die Rüstung immer instant an. Dies kann natürlich autobannen. Danke für den fix :)

**Comment by Maxhd00** [comment]
Ich habe es auch bemerkt. Ich habe 3 stunden aber gespielt und ich wurde nicht gebannt.
diese Rüstung soll nur abschrecken. du kannst es sogar auf none machen 

Und zum gomme bypass.

macht den setting weg und fügt ne leiste hinzu wieviele sekunden er keine Rüstungsgegenstände anziehen soll.
RandyMC macht das auch. Aber ganz versteckt. da muss man es nur auf 0.3 sek stellen.
 [---[]----] 0.0 - 3.0 sek

**Comment by Maxhd00** [comment]
wenn du bei gomme läufst bekommst du nur kurz die Rüstung also muss man die Leiste nur auf 2 machen und dann kann man den setting auf none machen.

**Comment by superblaubeere27** [comment]
Nein es gibt keine Fastclick check auf gomme
