### ISSUE TITLE
Crashhead BUG

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#678]
Mein Client crasht wenn ich den crashhead als Kopf aufsetzen will. Du kannst glaub noch einen Command einbauen, dass man den Crashhead direkt auf den helmslot bekommt.

**Comment by Marco-MC** [comment]
https://gyazo.com/e0c3365e5a309611884621f0dfc5612c

**Comment by Marco-MC** [comment]
Zwar sind wenn man den Crashhead auf den Kopf setzt viele OpenGL Fehler... Aber wieso willst du den überhaupt anziehen? xd
