### ISSUE TITLE
velocity settings verbinden.

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#679]
wenn ich hor und vertikal auf 0.5 mache und Reverse an habe. Soll ich nach vorne mit 1/2 Geschwindigkeit fliegen.
Oder wenn ich hor und vertikal 1 habe und aac und revence an habe soll ich nach vorne geworfen werden und dann stoppen. etc.

**Comment by Maxhd00** [comment]
revence so wie es ist geht auf gomme nicht mehr. da muss man horizontal und vertikal auf 0.8 machen damit es wieder funktioniert.

**Comment by FlorijonG** [comment]
Reverse*

**Comment by MaxHD0** [comment]
Ja aber man soll algemeinn alles verbinden können.

z.b aac mit reverse oder aac mit sterke 0.5 h 0.6 v
