### ISSUE TITLE
Spammer error/bug

### ISSUE THREAD

**Issue by Fleroxh** [CCBlueX/LiquidBounce1.8-Issues#682]
Als ich spammer aktiviert habe: 
![unbe42222222222222222222222222222222222222nannt](https://user-images.githubusercontent.com/25283927/27508399-102e3b60-58e4-11e7-87e2-83d791398837.PNG)

**Comment by Marco-MC** [comment]
Der Fehler ist nicht vom Spammer... xD
Das ist ein Bug vom Server. :3

**Comment by Fleroxh** [comment]
lol xD
