### ISSUE TITLE
[Bug] Like a Crazy Memory Fucker !?   :<

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#685]
**(7000Mb Memory Got Fucked)**

Crazy Memory Fucker(Increase like a **bomb**): http://prntscr.com/fnm3x9
Command Line **keep spamming** this!?: `http://prntscr.com/fnm4fu
Turned on mods: http://prntscr.com/fnm4i8

(when Memory close to 7000 Game will crash or lag)
my mods(Optifine,LiquidBounce6.2)

When I **first** use it
It's Ok.
But 1 hour later....

I have **restarted** my computer
and **test other client**.

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 162661392 bytes (155 MB) / 7145728000 bytes (7000 MB) up to 7145728000 bytes (7000 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: HMCL 2.5.3.88
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [Mix resourcepack 1.1.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	OptiFine Version: OptiFine_1.8_HD_U_H6
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by Fleroxh** [comment]
The tasks ram usage gets higher and higher by time, right? 🤔

**Comment by CrackFileso** [comment]
Found it .Forge bug

Use  forge1.8.9-11.15.1.1902 will fix this
