### ISSUE TITLE
ANTWORT CRASHHEAD BUG

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#686]
Ich trolle zurzeit ein paar spieler auf neruxvace.net (da kann man eigene server erstellen) und wenn ich den client von garkolym benutze geht das mit dem crashhead und bei liquidbounce nicht, da wird man dann einfach vom server geckickt. Du musst das mit dem crashhead mal auf einem server austesten und nicht im singleplayer XD. Wenn man die eine poison ins inventar nimmt wird man auch gekickt. Also sind diese zwei sachen zurzeit unnötig weil sie nur im singelplayer gehen (vlt. auch auf vanilla servern). Darum denke ich wenn man einen .crashhead cmd (genbauso wie .holostand) in den client einbaut der dir den kopf dann auf den helmslot tut (wie bei garkolym) wird man nicht gekickt und man kann die spieler auch mit lb verarschen. Ich fände es cool wenn noch ein paar trollfunktionen von garkolym in den client kommen. Aber wenn diese funktionen gefixt werden bin ich auch schon zufrieden.

**Comment by QWER16** [comment]
der crashhead bug funktioniert so man setzt den kopf auf den helmslot läuft um ein paar spieler, dann plaziert man den kopf auf dem boden und die spieler werden meißtens gecrasht. https://www.youtube.com/watch?v=ZAPzJIdcSaw

**Comment by SenkJu** [comment]
Wir testen nicht nur im Singleplayer. Für wie doof hältst du uns eigentlich? Wenn man wegen Crashhead gekickt wird, dann liegt das daran, dass der Server ihn gepatcht hat und wir wollen nicht noch einen Command adden, nur damit man den Crashhead da verwenden kann. Nimm doch zum Trollen auf dem Server einfach Garkolyms Client.

**Comment by QWER16** [comment]
Marco-mc hat mir aber bei meinem letzten bugreport ein video geschickt wo er den kopf antscheinend auf einem singleplayerserver getestet hat und warum geht der client von garkolym dann auf dem server? Übrigends finde ich lb besser weil der client noch mehr funktionen hat. Und ich halte euch nicht für doof ich könnte sowas nicht programmieren.

**Comment by QWER16** [comment]
https://gyazo.com/e0c3365e5a309611884621f0dfc5612c

**Comment by QWER16** [comment]
Wenn ich euch für doof halte würde ich den client ja nicht benutzen.

**Comment by SenkJu** [comment]
Was soll denn ein Singleplayer Server überhaupt sein? Das ist doch schon ein Widerspruch in sich. Und anscheinend ist das ein Bypass, wenn man den Head direkt in einen Armorslot legt.

**Comment by QWER16** [comment]
Sorry singleplayer, schau dir einfach das video von garkolym an wenn du wissen willst wie das geht, ich !DENKE! dass man nicht gekickt wird wenn der head direkt auf den kopfslot kommt (ich kann nicht Progarammieren also weiß ich nicht ob das stimmt). Aber egal ich benutze dann halt den client von Garkolym: https://www.youtube.com/watch?v=ZAPzJIdcSaw

**Comment by QWER16** [comment]
Und zum Hacken benutze ich dann Liquid Bounce.
