### ISSUE TITLE
AutoRod is missing

### ISSUE THREAD

**Issue by Fleroxh** [CCBlueX/LiquidBounce1.8-Issues#687]
Passt zwar nicht wirklich in einen PVP hacked client,  aber ganz nützlich.
(Idee von Khaled813)

**Comment by Fleroxh** [comment]
944. What's your emergency? 
Hi, auto rod is missing. I can't see it anymore.

**Comment by Fleroxh** [comment]
911. What's your emergency?
Hello, auto rod is missing. I think it's invisible, or it doesn't exists. 
Okay, we will send an emergency to you. Bye, bye.
Bye.

**Comment by Marco-MC** [comment]
Inwiefern AutoRod?
AutoRod für PvP?
oder AutoFish?

**Comment by MaxHD0** [comment]
Beides :P
