### ISSUE TITLE
.CMDstand befehl

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#689]
wenn man .CMDstand <befehl> macht bekommt man ein Armorstand der als Kopf einen Commandblock mit Befehl hat.

https://www.youtube.com/watch?v=HvIkGbSBltU

**Comment by SenkJu** [comment]
Wir wissen nicht, wie man das macht.

**Comment by Maxhd00** [comment]
wie man ein cmd block mit befehl mach wisst ihr. (wenn nicht skiddet von wurst client XD)
und diesen block einfach als entity auf den armorstand legen. 
(ihr habt doch schon oft gesehen wie ein zombie auf einem zombie sitzt. so geht das)

**Comment by SenkJu** [comment]
Das geht nicht so einfach. Minecraft hat extra etwas dagegen eingebaut, dass man keine Spawneggs mit Passengers machen kann.

**Comment by Maxhd00** [comment]
ja desshalb ist es ja ein armorstand ^^

**Comment by Maxhd00** [comment]
mit denen gehts nämlich.

**Comment by Maxhd00** [comment]
das mit dem Zombie war ja nur ein beispiel.

**Comment by SenkJu** [comment]
Junge, ein ArmorStand ist im Prinzip ein SpawnEgg

**Comment by Maxhd00** [comment]
.-.
