### ISSUE TITLE
Change Wallpaper BUG

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#696]
Man kann den Hintergrund nichtmehr normal ändern (Nur wenn man das Bild zu userbackground.png unbenennt und in den liquidbounce ordner kopiert). [https://prnt.sc/fnosk2](url)

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/684

**Comment by QWER16** [comment]
Ok wusste ned dass der bug schon bekannt ist.
