### ISSUE TITLE
arrow cam 

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#698]
könnt ihr den Arrow cam mod reimmachen . das wird lustig

https://minecraft.curseforge.com/projects/arrow-cam/files/2322425

(das wird lustig wenn jeder das hat XD)

**Comment by SenkJu** [comment]
Nein, definitiv nicht.

**Comment by SenkJu** [comment]
Warum nutzt du bitte nicht einfach die Mod? Die ist doch sogar für 1.8.9.

**Comment by Maxhd00** [comment]
weil es alle haben sollen XD

**Comment by SenkJu** [comment]
Wer außer dir will sowas?

**Comment by Maxhd00** [comment]
kp XD ich wills  auch nicht XD

**Comment by FlorijonG** [comment]
Ich
