### ISSUE TITLE
Real 1.8 OP Sign

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#700]
The one thats working in survival

**Comment by QWER16** [comment]
Ja das wollt ich auch noch in dem Client haben haben XD

**Comment by Maxhd00** [comment]
Das Problem ist für die 1.8 geht es nur bis zur 1.8.3 ab dann geht es nicht mehr.
Und dann geht es erst wieder in der 1.11

**Comment by RealFantaCoke** [comment]
Es geht bis zur 1.8.4, die 1.8.3 ist normal wie jede andere 1.8 Version (vorher) auch.

**Comment by MaxHD0** [comment]
Ok wie es auch ist. Aber alle 1.8 server sind 1.8.8 oder 1.8.9

**Comment by Marco-MC** [comment]
Der CommandSign geht auch auf 1.8... ich änder mal dieses 1.10.0 - 1.10.2 zu 1.8.0 - 1.8.3

**Comment by Marco-MC** [comment]
ich lass einfach den quatsch ganz weg
