### ISSUE TITLE
Pictures to the .holostad cmd

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#701]
Die Funktion dass man nicht nur Texte sondern auch ganze Bilder über die Bild Adresse Spawnen kann. (bin mir nicht ganz sicher ob der Command .holostad heißt)

**Comment by Maxhd00** [comment]
.hologramm gibt es im client noch garnicht. Ja ich währe dafür. Es wurde halt in spigot inzwischen gefixt.

**Comment by Marco-MC** [comment]
Nein zur Idee und es heißt .holostand
