### ISSUE TITLE
LiquidScript | v1.2

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#705]

**Comment by Marco-MC** [comment]
**Create own Tabs** https://twitter.com/Marco_09MC/status/878739132364836868

**Comment by Marco-MC** [comment]
##  Working status: 
Improving **if checks**

**Comment by Marco-MC** [comment]
Improved math check:

if double $player.posY > 40 {
## Code
}

**Comment by Marco-MC** [comment]
Added ifcall **{function_name}** _double $player.posY$ > 40_

**Comment by Marco-MC** [comment]
Improved script parser {
  Better dynamic
  Fixed some bugs
}

**Comment by Marco-MC** [comment]
Fixed script stop bug if you set a value

**Comment by Marco-MC** [comment]
Added "call **{functionname}**" method
Added "player.rotationYaw" value
Added "player.rotationPitch" value
Added "player.prevRotationYaw" value
Added "player.prevRotationPitch" value

**Comment by Marco-MC** [comment]
Added "player.hurtTime" value
Added "player.capabilities.isFlying" value
Added "player.capabilities.flySpeed" value
Added "player.capabilities.walkSpeed" value

**Comment by Marco-MC** [comment]
Added else to ifcall

ifcall **{function_name}** double $player.posY$ > 40 else **{function_name}**

**Comment by Marco-MC** [comment]
Added incode comments
Comment: %Hello world%

```
scriptName = "Test"
scriptVersion = 1.0
scriptAuthor = "CCBlueX"

registerTab(TestTab) {
	setFavicon paper
	registerItem cactus
	registerItem skull 1 3 {display:{Name:"Skull of Death"}}
}

registerModule(TestMod, Misc) {
	
	func onUpdate {
		ifcall a0 $player.onGround$ else a5
	}
	
	func a0 {% HalloWelt %
		do.player%asdfasdfasd fsdfon%.jump
		
		ifcall a1 double $player.posY$ > 40
	}
	
	func a1 {
		chat.display Deine Y Postion ist über 40!
	}
	
	func a5 {
		player.motionY = $player.motionY$ - 1
	}
}
```

**Comment by Marco-MC** [comment]
Added Obfuscator:
https://twitter.com/Marco_09MC/status/879019840991834112
https://twitter.com/Marco_09MC/status/878998151092371457
https://twitter.com/Marco_09MC/status/878983228417290240
https://youtu.be/a_GgHI46TYc

**Comment by Marco-MC** [comment]
Added command.call **{command..}** method
Added clientModule.**{moduleName}**.toggled = true/false

**Comment by RealFantaCoke** [comment]
That is a really nice Feature, i like it.

**Comment by Marco-MC** [comment]
Added Syntax Handling (False syntax errors etc)

**Comment by Marco-MC** [comment]
## Optimized:
`do.glmanager.scale = double(x) = double(y) = double(z)`
_to_
`do.glmanager.scale double(x) double(y) double(z)`

`mcfont.drawString = int(x) = int(y) int(color) boolean(shadow) string(text)`
_to_
`mcfont.drawString int(x) int(y) int(color) boolean(shadow) string(text)`

`mcfont.drawString = int(x) = int(y) int(color) boolean(shadow) string(text)`
_to_
`mcfont.drawString int(x) int(y) int(color) boolean(shadow) string(text)`

`do.player.setPosition = double(x) = double(y) = double(z)`
_to_
`do.player.setPosition double(x) double(y) double(z)`

**Comment by Marco-MC** [comment]
Added `do.player.sendPacket CPacketPlayer [onGround]`
Added `do.player.sendPacket CPacketPlayerPosition <X> <Y> <Z> <onGround>`

**Comment by Marco-MC** [comment]
Added `display.height` value
Added `display.width` value

**Comment by Marco-MC** [comment]
Added `gui.drawRect <left> <top> <right> <bottom> <color>` method

**Comment by byCaptain** [comment]
ok

**Comment by Marco-MC** [comment]
Added `object <name> RGB <r> <g> <b> <alpha>`

**Comment by Marco-MC** [comment]
drawRect Example:

```
scriptName = "TestScript";
scriptVersion = 1.0
scriptAuthor = "Marco_MC";

registerModule(TestModule, Movement) {
	
	func onDraw2D {
		object posY INTEGER $display.height$ / 2
		object colorino RGB 0 128 255 100
	
		gui.drawRect 0 0 $display.width$ $posY$ $colorino$
	}
}
```

https://gyazo.com/ee2409057098695763faa6dd83cd6667

**Comment by byCaptain** [comment]
wir sind doch alle braun

**Comment by Marco-MC** [comment]
Added `player.isSneaking` value
Added `player.inventory.currentItem` value

**Comment by Marco-MC** [comment]
Added `javascript.eval <code...>` method

**Comment by Marco-MC** [comment]
Added `player.session.username` value
Added `player.session.playerid` value
Added `player.session.token` value
Added `player.session.sessionid` value
Added `player.session.sessiontype` value
