### ISSUE TITLE
Connect BowAimbot with Projectiles

### ISSUE THREAD

**Issue by Cloak3** [CCBlueX/LiquidBounce1.8-Issues#709]

**Comment by SenkJu** [comment]
What do you mean?

**Comment by Cloak3** [comment]
It predicts the player's position where the arrow is going to hit.

**Comment by SenkJu** [comment]
Use Projectiles?

**Comment by Cloak3** [comment]
No, it aims automatically.

**Comment by Marco-MC** [comment]
Connected.
https://gyazo.com/399d778d07ce4ccd5026fd9e6fa41b21
