### ISSUE TITLE
Client for 1.12

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#710]
Kann man nicht so einen Button ins Menü bei den Servern machen womit man auswählen kann auf welcher Version von MC dein Client läuft also dass man z.B. 1.12 auswählt und dann 1.12 Server joinen kann. Das hat Garkolym mal bei einem Client gemacht. Ist das möglich ?

**Comment by QWER16** [comment]
Der Button gibt dem Client dann halt die Eigenschaften, so dass die Server denken es wäre ein z.B. 1.12 Client

**Comment by SenkJu** [comment]
Das ist nur bedingt möglich. 1.11 ginge auf 1.12 aber nicht 1.8 auf 1.12. Das würde, wenn es überhaupt irgendwie geht, extrem verbugt.

**Comment by QWER16** [comment]
Schade

**Comment by Bircko** [comment]
Außerdem ist das dank Forge Injection, denk ich mal gar nicht möglich.

**Comment by Maxhd00** [comment]
Es geht. Da braucht man einen 1.12 client. Mit dem 1.12 client kann man auf einen 1.8 server joinen.

Forge ist egal.

**Comment by SenkJu** [comment]
Nein, mit 1.12 wirst du nicht auf 1.8 kommen. Zumindest nicht, ohne extrem viel Bugfixing zu betreiben. Da wäre es 100x leichter und schneller einen getrennten 1.12 Client zu machen.

Und nein, Forge ist nicht egal. Es könnte durchaus sein, dass man das mit Forge nicht machen kann.
