### ISSUE TITLE
(AltManager) Client crash

### ISSUE THREAD

**Issue by Fleroxh** [CCBlueX/LiquidBounce1.8-Issues#712]
Als ich einen Alt beim AltManager adden wollte, ist komischerweise der Client gecrashed. 
Der  Alt enthielt ein Ausrufezeichen. 

Version/Build: b26.2

Mods: 
- OptiFine_1.8.9_HD_U_H8.jar
- LiquidBounce1.8.9.jar

Zusätzliche Mods: Nein

Optifine version: (release) 1.8.9-forge1.8.9-11.15.1.1902-1.8.9

Login-Daten vom Alt beim crash: 

**mathewlancaster@hotmail.co.uk:Remember12!** 
Crasht der Client bei euch auch? 

Eventuelle(r) Hinweis(e) aus dem latest crash log:
```
[11:53:21] [Client thread/INFO]: Logging in with username & password
[11:54:08] [Client thread/INFO]: Logging in with username & password
[11:54:12] [Client thread/INFO]: Logging in with username & password
[11:56:53] [Client thread/INFO]: Logging in with username & password
```

Latest crash log:
[latest.zip](https://github.com/CCBlueX/LiquidBounce1.8-Issues/files/1100229/latest.zip)

Mfg,

Fleroxh

**Comment by Marco-MC** [comment]
Hm? Ich sehe garkein Error?
Was passiert denn?

**Comment by Fleroxh** [comment]
Der client crasht einfach.. Genauso, wenn ich auf "Import" klicke.
