### ISSUE TITLE
Render waypoint features

### ISSUE THREAD

**Issue by Fleroxh** [CCBlueX/LiquidBounce1.8-Issues#715]
Like https://www.youtube.com/watch?v=L4oykbnV9PE.

You can remove, edit or add waypoints. 
Maybe a teleport function.

**Comment by Fleroxh** [comment]
And a gravestone function.

It automatically creates a waypoint, which is called "Deathpoint", or something else. 
You can add a AutoDelete modifier, which auto deletes the gravestone waypoint, after a definite time.

**Comment by Marco-MC** [comment]
Install a mod...
