### ISSUE TITLE
CubeCraft Fly

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#716]
Wäre es möglich den CubeCraft Fly schneller zum machen?

**Comment by Marco-MC** [comment]
Nein, ich werde den nicht noch schneller machen was auch glaube nicht mehr so wirklich geht.

**Comment by WistarWolf** [comment]
Ich habe auf CubeCraft aber Leute gesehen, die doppelt so schnell wie ich geflogen sind.

**Comment by Bircko** [comment]
Das liegt daran, dass wenn du mit dem Fly nach links und rechts strafest er schneller wird.
