### ISSUE TITLE
InventoryCleaner: One compass check

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#719]
Dass man jeweils nur eine Sache von manchem im Inventar behält. z.B. nur einmalen stärksten Bogen, nur einen Kompass usw

**Comment by Crax9999** [comment]
Ihr könntet vielleicht so es so machen dass man sich es aussuchen kann was drinnen blieibt u. was rausgeworfen wird dass hat der client Xave
Ich glaube dass es aber ziemlich lang dauert um 
sowas hinzukriegen

**Comment by superblaubeere27** [comment]
Warum?

**Comment by WistarWolf** [comment]
Da man das Inventar dann troz inventorycleaner zu voll hat. Manchmal passiert mir das auf cubecraft skywars

**Comment by Maxhd00** [comment]
Ich finde invcleaner so schlecht in LB. Xave ist es viel besser. invcleaner wirft immer mein  schwert weg. und die sinnlosen items lässt er.

**Comment by SenkJu** [comment]
Du besitzt Xave doch nicht einmal.

**Comment by MaxHD0** [comment]
sicher? ;-)

**Comment by MaxHD0** [comment]
doch ich habe noch die b12.

**Comment by B3nutz3r** [comment]
Woher?

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/954 Bögen

**Comment by Marco-MC** [comment]
Ich werde nen Check zu InventoryMove einbauen der alle Kompasse rauswirft bis auf einen.

**Comment by Marco-MC** [comment]
Added.
