### ISSUE TITLE
Too many items.

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#720]
(only creative)
Wenn du dein Inventar öffnest siehst du am rand alle items die es gibt. 
(du kannst damit dir auch eigene verzauberungen und eigene tränke geben.)
(diesen mod gibt es nicht für die 1.8.9)

**Comment by Marco-MC** [comment]
Junge, dann geh zu dem Entwickler dieser Mod und bettel nach einer 1.8.9 Version.
Wir sind nicht für sowas zuständig.
