### ISSUE TITLE
Chest steal /store in der Chestgui

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#722]
Man soll in der Chest gui 2 Knöpfe haben 1 das alles ins Inventar kommt. und 1 das alles in die Truhe kommt.

Cheststealer kann da manchmal nerven da Cheststealer jedes mal wenn man eine GUI öffnet alles rausklauen will. 

http://www.bilder-upload.eu/show.php?file=079d42-1498419761.png

**Comment by Maxhd00** [comment]
Es soll nir nicht oben sein sondern links store und rechts steal. (Wegen einer grossen chest)
