### ISSUE TITLE
Autosettings Nachrichten

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#727]
wenn man Autosettings erstellt soll man Nachrichten hinterlassen können.
z.b 4er Range Killaura kann Buggy sein. Wenn es zu Problemen führt einfach runterstellen.

nachrichten sollen mit @ funktionieren.

**Comment by SenkJu** [comment]
Gibt es schon "chat 4er Range kann buggy sein"

**Comment by Maxhd00** [comment]
ok
