### ISSUE TITLE
AutoSort

### ISSUE THREAD

**Issue by niikooartz** [CCBlueX/LiquidBounce1.8-Issues#728]
hey evtl weis man schon was gemeint ist :D 
ist alles nur ein vorschlag :)

falls nicht:

Automatisches sortieren von gegenständen im inv und switchen der items in die hotbar.

rechtsklick auf AutoSort
+ -> Slot1: Schwert
        Slot2: Rod
        Slot3:....
        usw
        usw
        usw

alles halt manuell via command z.b. konfigurierbar.
evtl auch machbar mit editierbaren values im + fenster :D 

ansich ist der client echt top ! und respekt für die arbeit und für das was der client alles kann !
dafür das es ein free client ist ist er echt top ! :)
weiter so :+1:

**Comment by Maxhd00** [comment]
+1

**Comment by Maxhd00** [comment]
k

**Comment by Bircko** [comment]
Noch besser das man am anfang das konfigurieren kann und dann abspeichen wie man z.b bei not enough items oder too many items das inventar abspeichern kann.

**Comment by IloveRickandmorty** [comment]
funktionierte aber nur bei Too many items. Bei not enough items ging es nur wenn du op hattest.

Too many items war so cool. Warum wird es nicht mehr geupdatet ;^(
