### ISSUE TITLE
Crasher modi

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#729]
- CreativeItemDrop

 (in creative droppst du gansschnell items die viel FPS verarbeiten. z.b op apfel, bett, uhren, verzauberte blaue lederrüstung etc.) (NoRender wird empfohlen an zu haben damit es nicht laggt.) (wenn es rein kommt)

- CreativeItemSpam 

(du nimmst die ganz schnell Items ins Inventar und löscht sie wieder.)

- Crashchat

(du schreibst viele (funktionierende Sonderzeichen in den chat)(spam) (funktioniert nur auf servern wo du nicht für spamming gekickt wirst.

- Rodcrash (mach das am besten in die donate version, da es immernoch auf sehr vielen Servern geht.)

(du crashst server indem du ganzschnell eine Angel ausfährst aber nicht mehr einfährst.) Diese vielen hacken crashen den server nach ner zeit. (der LB client soll die rods nicht Rendern)(Skash Client und der United Client hatten es.))

**Comment by Maxhd00** [comment]
Marco falls zu was anderes machen willst erst mach es. Lass diese issue offen bis du es dann irgendwann reinmachst.
