### ISSUE TITLE
NoRender

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#730]
Soll 6 Einstellungen haben.

NoPumpkin (Wenn man halt nicht diesen scheiss Kürbis aufhaben will. Bei manchen Spielmodi gibts das o_O das nervt richtig.)

NoXP (Like Gomme)

NoBanner (die laggen ja eh nur und keiner schaut sie an XD)

NoItemRender (wichtig für Crashmodis. kann sehr laggen ^^)

NoEntity (Mobs, Tiere und Armorstands werden nicht mehr angezeigt.) (NoItemRender und NoEntity sollen getrennt sein da man nicht immer beides gleichzeitig braucht.) (NoEntity ist nützlich, dass man nicht bei Crashmobs etc. gekickt wird.)

NoHurtcam ( NoHurtcam wird einfach zu NoRender umbennant und NoBanner, NoEntity, NoXP,  NoItemRender und NoPumpkin werden hinzugefügt.)

**Comment by Maxhd00** [comment]
alle Settings sind Notwendig für den Client.

**Comment by niikooartz** [comment]
NoWeather kann man sich sparen lol
https://prnt.sc/fouf3c

**Comment by Maxhd00** [comment]
ja gut stimmt das ist ja die 1.8.9 in der 1.8.0 funktionierte der button nie XD

**Comment by superblaubeere27** [comment]
Worfür?

**Comment by Maxhd00** [comment]
habe ich doch oben geschrieben.
