### ISSUE TITLE
Spawner in creative +

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#731]
Neuer tab: Spawner
Enthalten:
Alle Spawner die man machen kann.(von dem Schwein bis zum Enderdrache.) + Firework Spawner

**Comment by SenkJu** [comment]
Geht nicht. Ohne OP kann man keine Spawner erstellen.

**Comment by Maxhd00** [comment]
ok? Ist das seit dem neuen Spigot update so?

**Comment by SenkJu** [comment]
Nein, das ist schon immer so.
