### ISSUE TITLE
Update AAC Scaffold for AACAdditionPro

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#732]
Derzeit funktioniert kein Scaffold auf Gomme.

Allgemein auf dem neusten AAC geht weder der AAC mode noch eagle. PLZ updaten auf AAC 3.2.0/AAC 3.2.1

**Comment by Maxhd00** [comment]
mach auch eins das 1 zu 1 legit ist. (nur halt als scaffold. er soll sich also umdrehen und eageln. (clientside soll er aber noch nach vorne sehen.)

**Comment by SenkJu** [comment]
Oh Junge...

**Comment by Marco-MC** [comment]
Der Scaffold funkt auf AAC 3.2.1... Nur... nicht auf AACAdditionPro.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/971

**Comment by Marco-MC** [comment]
AACAD flaggt mich aber nach ner Zeit für Scaffold

**Comment by Marco-MC** [comment]
https://gyazo.com/8162e489e9de1649b9268b61434d70b1 AAC Mode
https://gyazo.com/c77665e7d7b2b0a0e9e49d8eeab7a0f3 AAC Mode + Slow

Also... Der Scaffold bypasst. Man muss ledeglich den Slow Mode anmachen.  :)
