### ISSUE TITLE
AAC Aura

### ISSUE THREAD

**Issue by Games4k** [CCBlueX/LiquidBounce1.8-Issues#733]
This is not bypassing AAC KillAura :(
Detected by Heuristic.

**Comment by Maxhd00** [comment]
Das lag an Raycast. aber seit der b26 sollte es gehen. Was denkst du soll man denn machen?

**Comment by Marco-MC** [comment]
@Maxhd00 Junge, du laberst schon wieder Müll.... RayCast hat nichts mit dem Heuristics Check zu tun und er kann sehr warscheinlich auch nur English...

**Comment by Marco-MC** [comment]
@Games4k Its not possible to bypass this killaura check of aac complete... We can bypass some patterns of this heuristics check but not the complete check.

**Comment by Maxhd00** [comment]
Ich kenn Heuristics garnicht. Ich dachte er meint AAC. So wie man es runterläd.
