### ISSUE TITLE
Server Finder

### ISSUE THREAD

**Issue by xXTimGamerXx** [CCBlueX/LiquidBounce1.8-Issues#734]
Mit denn Server Finder könnte man BungeeCord Netzwerke Suchen die lücken haben und auch verstäkte Nitrado Server. (bitte mit Port Scanner)

**Comment by Maxhd00** [comment]
Bitte auch ein eine eigene liste und nicht in den Multiplayer. Als ich das mal mit Wurst machte waren 1000 Server in meiner Liste. Ich konnte die gesamte Liste löschen. :/

**Comment by superblaubeere27** [comment]
Nimm doch Wurst oder das Programm von Garkolym [Hier zum vid](https://www.youtube.com/watch?v=rjJP3aXjoAY)

**Comment by Maxhd00** [comment]
das sagte ich ja grade beide sind scheisse da alles in Multiplayer kommt. und dann alles zugemüllt wird.
