### ISSUE TITLE
Random Ping (Spoofer)

### ISSUE THREAD

**Issue by xXTimGamerXx** [CCBlueX/LiquidBounce1.8-Issues#735]
Das würde bestimmt einige AntiCheats Bypassen

**Comment by Maxhd00** [comment]
Du meinst wenn ich den Ping auf 1000 mache wechselt er von 980 bis 1020?

**Comment by xXTimGamerXx** [comment]
Ja

**Comment by superblaubeere27** [comment]
Naja, wenns legiter is

**Comment by Maxhd00** [comment]
ich wusste es XD
