### ISSUE TITLE
Tastertur 

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#737]
So dass sich die Farben bei der Tastertur ändern wie z.B.: wenn man geschlagen wird kurz rot, die Keybinds werden Orange usw. sowie bei der 5Zig mod.

**Comment by Maxhd00** [comment]
sowas geht o_O

**Comment by Maxhd00** [comment]
wenn man sowas umsetzen kann würde ich es sehr cool finden.

**Comment by Maxhd00** [comment]
ich denke Marco ist aber zu faul.

**Comment by SenkJu** [comment]
Ähmm, nein.

**Comment by FlorijonG** [comment]
Wieso ?

**Comment by Maxhd00** [comment]
ich wusste es. Florijon die sind zu faul. Man muss denen leitere issues geben. Zum Beispiel ein timerspeed.
:P

**Comment by SenkJu** [comment]
Weil das hier ein Client ist und kein Multifunktionalwerkzeug. Was willst du als nächstes im Client? Einen YouTube Downloader? Einen DVD Player?

**Comment by Maxhd00** [comment]
hä das hat doch nicht mit was anderes zu tun. wenn alle keybinds orange leuten das gibts überhaupt garnicht. Würde einfach das spielen leichter und cooler machen.
