### ISSUE TITLE
Autoarmor worst mode

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#739]
Ein mode in Autoarmor das er immer die schlechteste Rüsstung anzieht.

**Comment by SenkJu** [comment]
Willst du einen Ban?

**Comment by Maxhd00** [comment]
was ist der sinn dahinter?

**Comment by SenkJu** [comment]
Uns auf die Nerven zu gehen

**Comment by Maxhd00** [comment]
es könnte ein spielmod geben wo man das braucht XD
