### ISSUE TITLE
Autoarmor bug 

### ISSUE THREAD

**Issue by Maxhd00** [CCBlueX/LiquidBounce1.8-Issues#741]
Manchmal zieht der Autoarmor schlechtere Rüstungsteile an. Z.b. er zieht lieber gold schuhe/helm an als ketten schuhe/helm

Priorität:

Verzaubert Diamant

Diamant

Verzaubert Eisen

Eisen

Ketten

Gold

Leder

PS: bei manchen erhört sich nicht der Rüstungswert. Aber wenn man von nem Bogen getroffen wird bekommt man weniger schaden.

**Comment by Marco-MC** [comment]
Es ist kein richtiger Bug.

**Comment by Marco-MC** [comment]
Fixed.
