### ISSUE TITLE
Add ControllerControl (Allows you to play minecraft with a controller)

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#743]

**Comment by Marco-MC** [comment]
Added.

Supported:
XBOX 360 Controller

**Comment by Maxhd00** [comment]
auch ps3/4?

**Comment by Maxhd00** [comment]
xbox spielt keiner XD

**Comment by Marco-MC** [comment]
Junge, bist du eigentlich zurückgeblieben?
Für das brauchst du keine PS3/PS4 oder XBOX?!
Du brauchst ledeglich einen XBOX 360 Controller, denn du für ca. 29€ auf Amazon etc kaufen kannst.
Du brauchst keine komplette Konsole dafür, alta...

**Comment by Maxhd00** [comment]
"@開発元 ne denke ich nicht. ich frage nur ob man auch mit ps3 oder 4 contoller  spielen kann. Ich kann X-box allgemein nicht leiden. Die Spiele sind scheisse. Die Firmware der Konsole ist scheisse und der Controller ist scheisse. egal ob 360 oder one"
