### ISSUE TITLE
NoRender (es hat einen sinn.) 

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#748]
Soll 6 Einstellungen haben. (BITTE DURCHLESEN. ES HATT EINEN SINN! Ich könnte euren Testserver auch wieder mit Items zuspammen :P Da muss man wohl NoRender haben.)

NoPumpkin (Wenn man halt nicht diesen scheiss Kürbis aufhaben will. Bei manchen Spielmodi gibts das o_O das nervt richtig.)

NoXP (Like Gomme)

NoBanner (die laggen ja eh nur und keiner schaut sie an XD)

NoItemRender (wichtig für Crashmodis. kann sehr laggen ^^ Zudem wenn ich den server Mit items vollspamme habe ich 60 FPS während die andern 3 haben.)

NoEntity (Mobs, Tiere und Armorstands werden nicht mehr angezeigt.) (NoItemRender und NoEntity sollen getrennt sein da man nicht immer beides gleichzeitig braucht.) (NoEntity ist nützlich, dass man nicht bei Crashmobs etc. gekickt wird.)

NoHurtcam ( NoHurtcam wird einfach zu NoRender umbennant und NoBanner, NoEntity, NoXP, NoItemRender und NoPumpkin werden hinzugefügt.)

**Comment by Maxhd00** [comment]
Bis dahin Spamme ich mal mit Items auf eurem Server. Ihr habt ja kein NoRender :-P

**Comment by Maxhd00** [comment]
(falls ihr es nicht jetzt machen wollt macht es Später.)

**Comment by Fleroxh** [comment]
Was willst du eigentlich noch hier? xD Schön spammen, gell?

**Comment by Maxhd00** [comment]
ne vorschläge machen o_O

**Comment by Maxhd00** [comment]
wass willst du eigendlich noch machen? xD Schön nerven, gell?

**Comment by MaxHD0** [comment]
naja .-.  Dann kann man halt alles vollspammen.
