### ISSUE TITLE
Settings Update

### ISSUE THREAD

**Issue by byCaptain** [CCBlueX/LiquidBounce1.8-Issues#751]
Can you please add .settings vanilla. Because there are some servers with no anticheats and it's easier with it.

**Comment by Maxhd00** [comment]
I have Send

**Comment by Fleroxh** [comment]
Finde ich gut! 👍

**Comment by Maxhd00** [comment]
ICH HABE ES JA EUCH SCHON 8 MAL GESENDET. Gomme, minesucht etc habt ihr angenommen. vanilla nicht o_O

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/FileCloud/blob/master/LiquidBounce/autosettings/vanilla
