### ISSUE TITLE
Scaffold replace mode

### ISSUE THREAD

**Issue by Fleroxh** [CCBlueX/LiquidBounce1.8-Issues#752]
Scaffold replaced Blöcke, die selected wurden und in der range sind.

**Comment by MaxHD00** [comment]
Ja aber dann muss er die Blöcke ja erst abbauen.

Da müsste man in creative sein .-.

**Comment by MaxHD00** [comment]
:P

**Comment by byCaptain** [comment]
max banumgehung

**Comment by Fleroxh** [comment]
@MaxHD00 Bye. Wir brauchen keine pupertierenden

**Comment by Fleroxh** [comment]
Sorry, @MaxHD00 aber wer mit Alts spammt sollte bestraft werden.

**Comment by MaxHD0** [comment]
ok.

**Comment by MaxHD0** [comment]
byCaptain  ich habe ein bot der bit immer einen neuen account macht :P
PS: ja ich bin auf dem Discord. Aber wenn ich schreibe werde ich ehh gebannt. desshalb ist es mir jz eh egal.

**Comment by byCaptain** [comment]
gib mri deine ip ich ddose dich

**Comment by MaxHD0** [comment]
Router neustarten .-.
