### ISSUE TITLE
Old Picture hud

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#753]
Mach wieder Das Alte Bild Von LB wieder rein (Hud. Es sah recht schön aus.)

http://www.bilder-upload.eu/show.php?file=01b524-1498764658.png

**Comment by Maxhd00** [comment]
oder vielleicht etwas überarbeitet.

**Comment by Marco-MC** [comment]
OH GOTT NEIN

**Comment by MaxHD0** [comment]
so schlimm ?

**Comment by B3nutz3r** [comment]
war eigentlich ganz nice
