### ISSUE TITLE
AAC Teleport

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#936]
So einen wie in diesem Video, wenn möglich.

https://www.youtube.com/watch?v=ie-F509Nn2M

**Comment by SenkJu** [comment]
Solange er den Teleport nicht auf Gomme zeigt, könnte das auch Blödsinn sein.

**Comment by Marco-MC** [comment]
... Yap... Auf HeroCode gehen ein haufen Phases, Teleport etc durch aber auf gomme gehen sie dann nicht.

**Comment by MaxHD0** [comment]
Euer aber auch XD

**Comment by byCaptain** [comment]
wer hat dich gefragt. liegst du so sehr an liquidbounce, dass du keine anderen hobbys hast

**Comment by MaxHD0** [comment]
:P
