### ISSUE TITLE
First Start Binds

### ISSUE THREAD

**Issue by WistarWolf** [CCBlueX/LiquidBounce1.8-Issues#940]
Wenn man das erste mal LiquidBounce startet ist bis auf die ClickGUI noch kein keybind gesetzt.

**Comment by MaxHD0** [comment]
oh. Ja bitte.

**Comment by Marco-MC** [comment]
Nope. Es giebt voreingestellte Keybinds:
KillAura = R
Fly = F
Glide = Z
LiquidWalk = J
Scaffold = I
Tower = O
