### ISSUE TITLE
[Anti bot Bug]Reflex Anti-bot bug

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#941]
I turned on 'wasInvisible' Option.
Although it bypassed the bots,
But after a while,It won't hit some real players.

**Comment by Marco-MC** [comment]
This is not a bug... maybe was the real players invisible for a time.

**Comment by CrackFileso** [comment]
@Marco-MC This Bug will happened When You Turn On Autoblock(with antibots and turn on 'wasInvisible' Option) In a AAC server
