### ISSUE TITLE
Latest NCP YPORT

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce1.8-Issues#945]
Like yport2 but mucho more bypasso

**Comment by Marco-MC** [comment]
Hm...
Ich habe jetzt versucht das er nach paar Sprüngen aufhöhrt und dann wieder anfängt, nur... das macht es sogar schlimmer...
Mischung aus OnGround Speed und YPort2 habe ich auch nicht geschafft...

https://gyazo.com/e109ee75b563256143b951fd9f19c970 NCP erkennt das als BunnyHop...

**Comment by Marco-MC** [comment]
https://gyazo.com/ed5794143d594ced6b4d25fec89779c6
https://gyazo.com/b29b36bcd634889f78259b39f601018d

Das ist slow af

**Comment by Marco-MC** [comment]
Besser gehts... nicht... Natürlich schon, aber das ist das max was ich bisher geschafft habe...

Dann ist es eindeutig sinnvoller die anderen Modes zu nehmen... sie flaggen halt ab und zu...
https://gyazo.com/18122b7583188688988d1ff447e48f60 YPort2
https://gyazo.com/741a9f0ab9a9cd8397ec96655dff64ac OnGround

Ich adde es trz jetzt einfach mal als NCPYPort
