### ISSUE TITLE
InventoryCleaner: Hotbar Option

### ISSUE THREAD

**Issue by B3nutz3r** [CCBlueX/LiquidBounce1.8-Issues#946]
und ja Marco, ich möchte das wenn ich gerade einen Gegner besiegt hab und der eine bessere Waffe hat das meine Waffe rausgeschmissen wird

**Comment by Marco-MC** [comment]
Ich habe da ne kleine Idee... Ich mache das er auch die Hotbar cleared, aber halt nur die Combat/Tool Items ignoriert.

**Comment by Marco-MC** [comment]
was? code sharing?
wut?

**Comment by WistarWolf** [comment]
"Ich habe da ne kleine Idee... Ich mache das er auch die Hotbar cleared, aber halt nur die Combat/Tool Items ignoriert." Wow. Dann ist es aber unnötig. Es sollte genau so wie im Inventar auch die Hotbar clearen. Da es nervt dass man die Items die man nicht brauch aus der hotbar extra entfernen mus

**Comment by WistarWolf** [comment]
Mach es doch einfach so dass im ganzen Inventar + Hotbar nur die besten und wichtigen Sachen behalten werden. Alles andere kommt raus. So wie halt in den meisten anderen clients auch.

**Comment by Marco-MC** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/2238
