### ISSUE TITLE
FastMotion, FastMotion 2 Tower types

### ISSUE THREAD

**Issue by QWER16** [CCBlueX/LiquidBounce1.8-Issues#951]
LiquidDev hat nen schnellen rewi und ncp Tower mit souce zu seinen 500 abbos released. Bitte in den Client einbauen.

**Comment by Marco-MC** [comment]
https://www.youtube.com/watch?v=UIZ6EY5DnDg

**FastMotion** Verschnellerte Variante (only NCP)
**FastMotion 2** https://hastebin.com/piqovucoba.java (Rewinside, NCP) (by @LiquidDev)
