### ISSUE TITLE
InventoryCleaner: Add bow check

### ISSUE THREAD

**Issue by B3nutz3r** [CCBlueX/LiquidBounce1.8-Issues#954]
Der InventoryCleaner behält mehrere Bögen im Inventar

**Comment by Marco-MC** [comment]
Das ist kein Bug... Das liegt daran das wir noch keinen Check für Bows in InventoryCleaner haben...
Ich werde jetzt machen das wenigstens die unverzauberten Bögen aussortiert werden, da dass mit Verzauberung beachten bei Bögen wieder relativ schwer ist...

**Comment by Marco-MC** [comment]
https://gyazo.com/4f61898c64865d6c3f9580c9959b737b
https://gyazo.com/54ef513900957456fc6b73205dbefbe6

Added.
