### ISSUE TITLE
ShaderESP

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#96]
Könntet ihr ein ESP mode machen der sowie in der 1.9 ist für Items und Player.
Mit Teams Einstellung damit wenn man Bw spielt man die anderen Teams in der Teamfarbe sieht.

**Comment by DieSchuessel** [comment]
ShaderESP für Item, Kisten und blöcke auch

**Comment by FlorijonG** [comment]
Meinte aber nicht ShaderESP weil die bei mir nicht gut laufen nur dieses Glow bei der 1.9 läuft bei mir Flüssig.

**Comment by Marco-MC** [comment]
Added (by Slowly)

**Comment by WistarWolf** [comment]
Skid Kappa
