### ISSUE TITLE
Chat öffnen animation

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#963]
https://youtu.be/UIZ6EY5DnDg?t=26

Das sieht richtig cool aus. Viel besser als der Chat einfach erscheint. 

(die Leiste unten)

**Comment by Marco-MC** [comment]
Das wird mit ForgeInjection tikkel problematisch, aber vielleicht bekomme ich es hin.

**Comment by MaxHD0** [comment]
danke.

PS: Tut mir leid was ich vor paar Tagen abgeliefert habe.

**Comment by Marco-MC** [comment]
So... Mal schauen ob es klappt.

**Comment by Marco-MC** [comment]
Ich hoffe das es auch flüssig aussieht, da ich updateScreen zum moven verwende.

**Comment by Marco-MC** [comment]
Hm... Klappt nicht.

**Comment by MaxHD0** [comment]
wenn es nicht geht: kannst du ja etwas anderes machen z.b das es sichtbar wird (von unsichtbar zu sichtbar)
und wenn du den Chat schließt wird der Balken wieder unsichtbar. (so in 1 sek)

**Comment by Marco-MC** [comment]
Von unsichtbar zu sichtbar ist noch schwieriger... das mit den schließen würde auch nicht funken. Auf jedenfall schaue ich grade why es nicht geht richtig...

**Comment by Marco-MC** [comment]
ach xD bin behindert ... das schwarze kommt nicht von der TextBox sondern von drawRect...

**Comment by Marco-MC** [comment]
Das ist jetzt Problematisch... ich muss die drawScreen Methode overwriten...

**Comment by Marco-MC** [comment]
ähhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh... ._.

**Comment by Marco-MC** [comment]
https://gyazo.com/fbc4c25005dc42009149b0f826426832
https://gyazo.com/254bbe8a3b5a84d2b4e4089a56ad5517
Der Spasti macht aus der Methode ein abstract method... ._.

**Comment by Marco-MC** [comment]
Reflections helfen immer. :D

**Comment by Marco-MC** [comment]
So... Mal schauen ob alles klappt.

**Comment by Marco-MC** [comment]
Yoa, klappt.

**Comment by Marco-MC** [comment]
Smooth ist es auch.

**Comment by Marco-MC** [comment]
Schicke gleich mal Bild...

**Comment by Marco-MC** [comment]
https://gyazo.com/d9fc61d33d9aae02caeb5b2c14d78564
So der start gefällt mir nicht... da ist immer so n kleiner hüfer drin..n

**Comment by Marco-MC** [comment]
So... Der Hüpfer ist auch gefixt oder wie man es nennen will...

**Comment by Marco-MC** [comment]
Habe... fucking 1 Stunde dafür gebraucht... Ernsthaft?
Naja... die Zeit um Forge überhaupt zu starten...

**Comment by MaxHD0** [comment]
Hem. Es öffnet sich etwas langsam.

**Comment by Bircko** [comment]
Ja viel zu langsam

**Comment by Marco-MC** [comment]
Habe es jetzt schneller gmacht... ._.
