### ISSUE TITLE
NameTags-Nuker-Xray Customination

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#967]
Ping Healt Armor İnvisible Box İtem İd İnstant Nuker Select Xray Blocks İn Gui Etc Etc

**Comment by SenkJu** [comment]
?

**Comment by MaxHD0** [comment]
Ich habe es verstanden. Er meint:

man soll bei Nametags: Ping, Health und Armor hinzufügen.

Bei Nuker : Id mode, Instant

und bei Xray eine eigene Gui welche Items hinzugefügt werden sollen.

Fazit: Ausser die XrayGui ist doch alles drin XD

**Comment by scorpion3013** [comment]
- Gamemode Check bitte auch. xD

**Comment by MaxHD0** [comment]
XD

**Comment by Teals53** [comment]
What :D ?
