### ISSUE TITLE
Enchanted Priority 

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#968]
AutoArmor And AutoSword

**Comment by MaxHD0** [comment]
.-. er hat das sogar noch bearbeitet. Das ist nicht so einfach. Marco hat sich genügend damit befasst.
Du darfst nicht vergessen das z.b man nicht immer schutz braucht. manchmal braucht man auch Schusssicher etc.

Ein Autoarmor mit Enchantmens kann man nicht richtig machen. er hat ja schon gemacht das wenn ein Rüstungsteil verzaubert ist (egal was für ne Verzauberung) tauscht er dies bereits aus.

**Comment by Teals53** [comment]
I Dont Understand You Do You Try Writing English ?

**Comment by Teals53** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/102
