### ISSUE TITLE
CMDBlock (bitte durchlesen)

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#973]
Selbst wurst hat das. Sogar mit ner GUI.

 http://www.bilder-upload.eu/show.php?file=6d4453-1499283824.png

Kann oft nützlich sein. Und wenn man dann noch den client wechselt, dann bist du sicherlich kein gm1 mehr. 

man soll .cmdblock < befehl> statt .give command_block 1 0 {Command:"/gamemode @p"} machen.

**Comment by MaxHD0** [comment]
das währe beschämend gegenüber liquidbounce

**Comment by MaxHD0** [comment]
mann will es etwas einfacher haben. Denkst du ein nicht programmierer kann das?

Vorallem was machen die schweizer? Meine schweizer tastatur hat dieses ( und ) nicht. Also diese gewölbten ( (die du oben geschrieben hast)

**Comment by Marco-MC** [comment]
Das hat jede Tastatur du Tömpel.
Einfach STRG + ALT + 7 um { zu bekommen und STRG + ALT + 0 um } zu bekommen.
UND WANN RAFFST DU ES WENN ICH EINMAL NEIN SAGE ICH AUCH IN ZUKUNFT NEIN SAGEN WERDE.

**Comment by Marco-MC** [comment]
Der .give Command ist genauso wie /give...
/give @p command_block 1 0 {Command:"/gamemode @p"}
.give command_block 1 0 {Command:"/gamemode @p"}

**Comment by SenkJu** [comment]
Klar hast du noch GM1, wenn du den Client änderst. Solche Dinge sind verknüpft mit dem Account, nicht mit dem Client.

**Comment by MaxHD0** [comment]
junge wer macht schon bitte  .give command_block 1 0 {Command:"/gamemode @p"}

**Comment by MaxHD0** [comment]
kannst ne umfrage machen. Alle Programmierer würden ja sagen da es denen egal sein würde. Alle ander NICHT!
