### ISSUE TITLE
CMDBlock

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#974]

**Comment by MaxHD0** [comment]
sowas einzüfügen ist wirklich nicht schwer.

**Comment by MaxHD0** [comment]
und wenn ich wirklich sage meine ich wirklich.

**Comment by SenkJu** [comment]
Und wenn wir sagen 'Nein', dann meinen wir 'Nein'. Wieso geht das nicht in dein unterentwickeltes Hirn rein?
