### ISSUE TITLE
AAC320fly

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#983]
https://pastebin.com/raw/2RjuEUzL

Code by M1CEClient
 Only works on servers that use viaversion

(https://leakforums.net/thread-920036?page=1)

**Comment by Marco-MC** [comment]
Added as AAC320 Mode to Fly.
https://hastebin.com/enimizabef.scala

**Comment by CrackFileso** [comment]
LOL

**Comment by Marco-MC** [comment]
?

**Comment by ImDrops** [comment]
Useless, only work on ccbluex testserver. Its broken right now, Test it on poke.sexy or something.

**Comment by Marco-MC** [comment]
poke.sexy have AAC 3.2.1...

**Comment by Marco-MC** [comment]
https://www.youtube.com/watch?v=uiEEieBcTwU It worked.
