### ISSUE TITLE
AAC BOT bypass

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#984]
http://prntscr.com/fs8ugx
http://prntscr.com/fs8ut5
If I turn on the "wasInvisible" Option ，It won't hit **Some** real Players.
Might be AAC's Problem
(AAC3.2.1)
("wasInvisible"  Works fine in none Anti-cheat Servers)

**Comment by Marco-MC** [comment]
AAC 3.2.1 have no Bots? 
When "wasInvisible" make problems disable it.

**Comment by CrackFileso** [comment]
I think it has bot.
Turn truesight on when you fighting

**Comment by Marco-MC** [comment]
Are you sure that its only AAC 3.2.1 xd...

**Comment by CrackFileso** [comment]
since AAC3.1.7

**Comment by CrackFileso** [comment]
If I disable "wasInvisible",I will got kicked after 1 minute.(If I hit the Bots for too much times)

**Comment by Marco-MC** [comment]
AAC 3.X.X HAVE NO BOTS

**Comment by CrackFileso** [comment]
xD
