### ISSUE TITLE
Recode Teleport Button

### ISSUE THREAD

**Issue by B3nutz3r** [CCBlueX/LiquidBounce1.8-Issues#990]
Teleport Button bitte auf Rechtsklick machen

**Comment by MaxHD0** [comment]
das auswählen? Wo man sich teleportieren will? Hem. mittelklick finde ich eigendlich recht gut. Aber marco kann es entscheiden wo er es besser findet.

**Comment by Bircko** [comment]
Außerdem muss man dafür nichts "recoden"....

**Comment by RealFantaCoke** [comment]
Bin dagegen, die mittlere Maustaste ist gut!

**Comment by Marco-MC** [comment]
Nein, das bleibt in der Mitte wie die Tritte bei Mitte bleiben.
