### ISSUE TITLE
NCP/OLDNCP fly bug

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#991]
Wenn ich NCP oder OLDNCP fly an schalte schlägt mein spieler mit der Hand und ich werde (nicht auf jedem server) gekickt. 
Das ist nur beim NCP oder OLDNCP fly. 

(er schlägt nur mit der hand wenn du auf dem Boden bist. (dann wird man gekickt))

(man wird für packets gekickt)

**Comment by SenkJu** [comment]
Das ist kein Bug. Der Fly funktioniert nunmal so.

**Comment by MaxHD0** [comment]
ok? Ein fly der dich bei ncp/aac/spartan/etc kickt. Nice. Super fly XD

**Comment by SenkJu** [comment]
Du bist echt so blöd, dass es kracht, oder? Der Fly ist weder für Latest NCP, noch AAC, Spartan  oder sonstwas. Wenn er auf den AntiCheats kickt, können wir das auch nicht ändern. Sieht so aus, als hatten die Devs den Fly gepatcht, was?

**Comment by MaxHD0** [comment]
Ok dann kann man ein neues modul hinzufügen wo mal alles einstellen kann. (custom fly) da kann man dann neue flys ausprobieren. etc

**Comment by MaxHD0** [comment]
senkju zudem woher soll ich das wissen. Ich dachte der fly ist einfach zum testen. z.b AAC 3.1.5 ging der Ncp fly wenn man die motion auf 0,8 macht.
