### ISSUE TITLE
NCP fly speed.

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#993]
man soll die Schnelligkeit vom NCP fly einstellen können.

(auf gomme ging es mal. Vieleicht wird es ja mal wieder gehen ;-) )

https://www.youtube.com/watch?v=F64fg9Nd8LQ

(später ging er nach unten)

**Comment by MaxHD0** [comment]
(wenn customfly reinkommt muss man den speed nicht hinzufügen)
