### ISSUE TITLE
Customfly mode

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#994]
ein fly wo man alles einstellen kann.

Speed xz [----[]--]

Speed y [----[]--]

Motion  [----[]--]

OnlyXZ [an|aus] (wenn an kann man nicht mehr diagonal fliegen sondern nur etwa X achse oder Z achse)

Timer [----[]--]

Smooth [an|aus]

AirYport (so ein hoch und runterbewegen(so wie der aac3fly. )(um so sterker eingestellt um so mehr wippt er.) [----[]--]

**Comment by SenkJu** [comment]
Lern LiquidScript.

**Comment by MaxHD0** [comment]
rly.

**Comment by MaxHD0** [comment]
aber bei Custom speed sagt ihr nichts XD
