### ISSUE TITLE
Chat bubbles

### ISSUE THREAD

**Issue by MaxHD0** [CCBlueX/LiquidBounce1.8-Issues#996]
Wenn jemand was schreibt wird das im Chat und über dem Skin gezeigt.

(es gab ein mod. der ist jedoch nur für die 1.7.2)

http://www.bilder-upload.eu/show.php?file=631270-1499467381.png

**Comment by SenkJu** [comment]
WTF, nein. Das hier ist die immer noch ein Client und kein Thermomix
