### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by Crax9999** [CCBlueX/LiquidBounce1.8-Issues#998]
Step delay [------[]------]
Motion speed
Porthop (porthop ist ein langsamer bhop der dich ein bisschen nach vorne teleportiert hat mal auf AAC gebypasst funktioniert glaube noch)
Killaura:prehit,Smoothaiming,crush,smash

**Comment by Crax9999** [comment]
Es wäre wirklich sehr nett wenn ihr das adden könntet :)

**Comment by B3nutz3r** [comment]
Was ist crush und smash?

**Comment by Marco-MC** [comment]
- [ ] **StepDelay (https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1045)**

**KillAura PreHit** (Was soll das sein?)
**KillAura SmoothAiming** = TurnSpeed... ._.
**KillAura Crush** (Was soll das sein?)
**KillAura Smash** (Was soll das sein?)

PortHop und MotionSpeed lehne ich ab, also bleibt ledeglich nur noch StepDelay...

**Comment by Crax9999** [comment]
Ok
